### ISSUE TITLE
Albany build failing in MueLu: AggregationStructuredAlgorithm_kokkos

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#4334] opened 2019-02-06 12:25 UTC
@trilinos/muelu 

## Current Behavior

```
.../Trilinos/packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_def.hpp:221:39: error: unknown type name 'AggregationStructuredAlgorithm_kokkos'; did you mean 'AggregationStructuredAlgorithm'?

      myStructuredAlgorithm = rcp(new AggregationStructuredAlgorithm_kokkos());
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      AggregationStructuredAlgorithm
/.../Trilinos/packages/muelu/src/Interface/../Headers/MueLu_UseShortNamesOrdinal.hpp:36:80: note: 'AggregationStructuredAlgorithm' declared here
typedef MueLu::AggregationStructuredAlgorithm<LocalOrdinal,GlobalOrdinal,Node> AggregationStructuredAlgorithm;
                                                                               ^
```

**Comment by lucbv** [comment] 2019-02-06 14:15
@ibaned I will look into it, somehow this did not get picked up by the PR auto-tester.
Are you building using any special configuration?

**Comment by ibaned** [comment] 2019-02-07 02:16
Here is the full CMake command:
```
"/usr/bin/cmake" \
"-DBUILD_SHARED_LIBS:BOOL=ON" \
"-DCMAKE_BUILD_TYPE:STRING=RELEASE" \
"-DCMAKE_CXX_COMPILER:FILEPATH=/usr/lib64/openmpi/bin/mpicxx" \
"-DCMAKE_C_COMPILER:FILEPATH=/usr/lib64/openmpi/bin/mpicc" \
"-DCMAKE_Fortran_COMPILER:FILEPATH=/usr/lib64/openmpi/bin/mpif90" \
"-DCMAKE_INSTALL_PREFIX:PATH=/home/lcm/LCM/trilinos-install-serial-clang-release" \
"-DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF" \
"-DTPL_ENABLE_MPI:BOOL=ON" \
"-DTPL_ENABLE_BinUtils:BOOL=OFF" \
"-DTPL_MPI_INCLUDE_DIRS:STRING=/usr/include/openmpi-x86_64" \
"-DTPL_MPI_LIBRARY_DIRS:STRING=/usr/lib64/openmpi/lib" \
"-DMPI_BIN_DIR:PATH=/usr/lib64/openmpi/bin" \
"-DTPL_ENABLE_Boost:BOOL=ON" \
"-DTPL_ENABLE_BoostLib:BOOL=ON" \
"-DBoost_INCLUDE_DIRS:STRING=/usr/include/boost" \
"-DBoost_LIBRARY_DIRS:STRING=/usr/lib64" \
"-DBoostLib_INCLUDE_DIRS:STRING=/usr/include/boost" \
"-DBoostLib_LIBRARY_DIRS:STRING=/usr/lib64" \
"-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF" \
"-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF" \
"-DTrilinos_ENABLE_CXX11:BOOL=ON" \
"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF" \
"-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON" \
"-DTrilinos_VERBOSE_CONFIGURE:BOOL=OFF" \
"-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=" \
"-DTeuchos_ENABLE_STACKTRACE:BOOL=OFF" \
"-DTeuchos_ENABLE_DEFAULT_STACKTRACE:BOOL=OFF" \
"-DKokkos_ENABLE_Cuda_UVM:BOOL=OFF" \
"-DKokkos_ENABLE_EXAMPLES:BOOL=OFF" \
"-DKokkos_ENABLE_OpenMP:BOOL=OFF" \
"-DKokkos_ENABLE_Pthread:BOOL=OFF" \
"-DKokkos_ENABLE_Serial:BOOL=ON" \
"-DKokkos_ENABLE_TESTS:BOOL=OFF" \
"-DTPL_ENABLE_CUDA:STRING=OFF" \
"-DTPL_ENABLE_CUSPARSE:BOOL=OFF" \
"-DAmesos2_ENABLE_KLU2:BOOL=ON" \
"-DEpetraExt_USING_HDF5:BOOL=OFF" \
"-DROL_ENABLE_TESTS:BOOL=OFF" \
"-DPhalanx_INDEX_SIZE_TYPE:STRING=INT" \
"-DPhalanx_KOKKOS_DEVICE_TYPE:STRING=SERIAL" \
"-DPhalanx_SHOW_DEPRECATED_WARNINGS:BOOL=OFF" \
"-DTpetra_ENABLE_Kokkos_Refactor:BOOL=ON" \
"-DTpetra_INST_PTHREAD:BOOL=OFF" \
"-DTPL_ENABLE_HDF5:BOOL=OFF" \
"-DTPL_ENABLE_HWLOC:STRING=OFF" \
"-DTPL_ENABLE_Matio:BOOL=OFF" \
"-DTPL_ENABLE_Netcdf:BOOL=ON" \
"-DTPL_ENABLE_X11:BOOL=OFF" \
"-DTPL_Netcdf_INCLUDE_DIRS:STRING=/usr/local/netcdf/include" \
"-DTPL_Netcdf_LIBRARY_DIRS:STRING=/usr/local/netcdf/lib" \
"-DTPL_Netcdf_LIBRARIES:STRING=/usr/local/netcdf/lib/libnetcdf.so" \
"-DTPL_Netcdf_PARALLEL:BOOL=OFF" \
"-DTrilinos_ENABLE_Amesos2:BOOL=ON" \
"-DTrilinos_ENABLE_Amesos:BOOL=ON" \
"-DTrilinos_ENABLE_Anasazi:BOOL=ON" \
"-DTrilinos_ENABLE_AztecOO:BOOL=ON" \
"-DTrilinos_ENABLE_Belos:BOOL=ON" \
"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF" \
"-DTrilinos_ENABLE_Epetra:BOOL=ON" \
"-DTrilinos_ENABLE_EpetraExt:BOOL=ON" \
"-DTrilinos_ENABLE_Ifpack2:BOOL=ON" \
"-DTrilinos_ENABLE_Ifpack:BOOL=ON" \
"-DTrilinos_ENABLE_Intrepid2:BOOL=ON" \
"-DTrilinos_ENABLE_Kokkos:BOOL=ON" \
"-DTrilinos_ENABLE_KokkosAlgorithms:BOOL=ON" \
"-DTrilinos_ENABLE_KokkosContainers:BOOL=ON" \
"-DTrilinos_ENABLE_KokkosCore:BOOL=ON" \
"-DTrilinos_ENABLE_KokkosExample:BOOL=OFF" \
"-DTrilinos_ENABLE_MiniTensor:BOOL=ON" \
"-DTrilinos_ENABLE_ML:BOOL=ON" \
"-DTrilinos_ENABLE_MueLu:BOOL=ON" \
"-DTrilinos_ENABLE_NOX:BOOL=ON" \
"-DTrilinos_ENABLE_OpenMP:BOOL=OFF" \
"-DTrilinos_ENABLE_Pamgen:BOOL=ON" \
"-DTrilinos_ENABLE_Phalanx:BOOL=ON" \
"-DTrilinos_ENABLE_Piro:BOOL=ON" \
"-DTrilinos_ENABLE_ROL:BOOL=ON" \
"-DTrilinos_ENABLE_Rythmos:BOOL=ON" \
"-DTrilinos_ENABLE_SEACAS:BOOL=ON" \
"-DTrilinos_ENABLE_SEACASAprepro_lib:BOOL=ON" \
"-DTrilinos_ENABLE_STKClassic:BOOL=OFF" \
"-DTrilinos_ENABLE_STKIO:BOOL=ON" \
"-DTrilinos_ENABLE_STKMesh:BOOL=ON" \
"-DTrilinos_ENABLE_Sacado:BOOL=ON" \
"-DTrilinos_ENABLE_Shards:BOOL=ON" \
"-DTrilinos_ENABLE_Stokhos:BOOL=OFF" \
"-DTrilinos_ENABLE_Stratimikos:BOOL=ON" \
"-DTrilinos_ENABLE_TESTS:BOOL=OFF" \
"-DTrilinos_ENABLE_Teko:BOOL=ON" \
"-DTrilinos_ENABLE_Tempus:BOOL=ON" \
"-DTrilinos_ENABLE_Teuchos:BOOL=ON" \
"-DTrilinos_ENABLE_ThreadPool:BOOL=ON" \
"-DTrilinos_ENABLE_Thyra:BOOL=ON" \
"-DTrilinos_ENABLE_Tpetra:BOOL=ON" \
"-DTrilinos_ENABLE_Zoltan2:BOOL=ON" \
"-DTrilinos_ENABLE_Zoltan:BOOL=ON" \
"-DTempus_ENABLE_TESTS:BOOL=OFF" \
"-DTempus_ENABLE_EXAMPLES:BOOL=OFF" \
"-DTempus_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON" \
"-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF" \
"-DTrilinos_ENABLE_DataTransferKit:BOOL=ON" \
"-DDataTransferKit_ENABLE_DBC:BOOL=ON" \
"-DDataTransferKit_ENABLE_TESTS:BOOL=OFF" \
"-DDataTransferKit_ENABLE_EXAMPLES:BOOL=OFF" \
"-DTPL_ENABLE_MOAB:BOOL=OFF" \
"-DTPL_ENABLE_Libmesh:BOOL=OFF" \
"-DTrilinos_EXTRA_REPOSITORIES:STRING=DataTransferKit" \
"-GUnix \
Makefiles" \
"/home/lcm/LCM/Trilinos"
```

**Comment by mhoemmen** [comment] 2019-02-07 16:18
@crdohrm saw this too.  @theguruat12 has been working with us on a CUDA build of Trilinos for Sierra, and this is a blocker :-)

**Comment by lucbv** [comment] 2019-02-07 16:45
@mhoemmen interestingly this is not showing up on the dashboard which has about 30 different MueLu builds at this point, including some with kokkos refactor on.
Of course the simplest fix for this issue is to avoid using the short name and instead use the longer version with all the templates explicitly invoked.
I will try to reproduce this problem but so far even my CUDA build on white is doing just fine so there must be some special configuration that breaks the short name logic...

**Comment by mhoemmen** [comment] 2019-02-07 19:02
@lucbv Could enabling complex possibly trigger this?  I know the above script doesn't, but perhaps enabling complex messes with the short name logic.

**Comment by ikalash** [comment] 2019-02-08 03:01
This seems to be happening in the Fedora builds of Trilinos/Albany.  One thing that may be specific there and different from other builds is we turn ETI off (b/c we use DTK which does not work with ETI).  Could that be an issue?  Sorry for the delay in my response to this issue - I am on travel.

**Comment by mhoemmen** [comment] 2019-02-08 20:33
@ikalash DTK _should_ work fine with ETI, if you enable the right GlobalOrdinal type.  (They want `unsigned long` for some reason that @rppawlo can explain.)  Try `Tpetra_INST_INT_UNSIGNED_LONG=ON`.  If that doesn't work, then DTK must be broken.

**Comment by lucbv** [comment] 2019-02-08 20:39
@ikalash @mhoemmen @ibaned 
I think that the ETI off was indeed the main difference between our builds, I have reproduced and fixed this issue. Hopefully you won't see this on your dashboard tomorrow!

Also I see that you actually turn on eti and then turn it back off in your configuration, that was a little confusing and seems a little risky to me.

**Comment by mhoemmen** [comment] 2019-02-08 20:48
@ikalash Now that we've opened the door to critiquing CMake options ;-)
```
"-DTrilinos_VERBOSE_CONFIGURE:BOOL=OFF" \
"-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=" \
"-DTeuchos_ENABLE_STACKTRACE:BOOL=OFF" \
"-DTeuchos_ENABLE_DEFAULT_STACKTRACE:BOOL=OFF" \
```
If there's no particular reason why you disable stack tracing, then you could safely omit all of these.
```
"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF" 
```
This disables examples in all the packages, so you don't need to turn off specific packages' examples explicitly.
```
"-DTpetra_ENABLE_Kokkos_Refactor:BOOL=ON"
```
You haven't needed this for years (literally not since Trilinos 12.0).
```
"-DTrilinos_ENABLE_KokkosAlgorithms:BOOL=ON" \
"-DTrilinos_ENABLE_KokkosContainers:BOOL=ON" \
"-DTrilinos_ENABLE_KokkosCore:BOOL=ON" \
```
Those get turned on automatically with `Trilinos_ENABLE_Kokkos:BOOL=ON`.

**Comment by mhoemmen** [comment] 2019-02-08 20:48
```
"-DTempus_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON" \
"-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF" \
```
This is weird and looks like it shouldn't work.  Does Tempus get its ETI through Thyra?  @bartlettroscoe might know.

**Comment by bartlettroscoe** [comment] 2019-02-08 20:53
That is strange.  Why would you not turn on ETI for all of Trilinos?  I don't think I have seen any Tempus code so I don't know how they do ETI but if they use Thyra, using the Thyra ETI macros and TriBITS support would seem to be the easiest thing to do.

**Comment by ibaned** [comment] 2019-02-08 20:56
Albany's long-standing excuse (not saying its good) for ignoring ETI has been some integration with DTK which I think instantiates Tpetra types with unsigned ordinals. Ordinal templating is going away anyways, so they'll be forced to fix this soon I think.

**Comment by mhoemmen** [comment] 2019-02-08 21:49
@ibaned @ikalash It's not correct to use a GlobalOrdinal type unless it's enabled in Tpetra, regardless of whether ETI is on.  Also, I spent quite a bit of effort getting unsigned GlobalOrdinal types to work a while back, and Tpetra does have an option to enable `GlobalOrdinal = unsigned long`.  Furthermore, none of the solver factories (I worked really hard on those and they save a lot of build time) work for types not enabled at configure time.

**Comment by ikalash** [comment] 2019-02-09 20:12
@lucbv : thanks for looking into this!  Unfortunately it looks like now there is a different muelu-related error now preventing my Trilinos builds from going through:
```
                                                     ^~~~~~~~~~~~~~~~
In file included from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/packages/muelu/src/MueLu_StructuredAggregationFactory_kokkos.hpp:2,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp:152,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/packages/muelu/src/Interface/MueLu_FactoryFactory.hpp:1,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp:73,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/packages/muelu/src/Interface/MueLu_ParameterListInterpreter.hpp:2,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp:24,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp:94,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/build/packages/muelu/src/MueLu_RefMaxwell.hpp:2,
                 from /home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/adapters/aztecoo/MueLu_AztecEpetraOperator.cpp:8:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_def.hpp: In member function ‘void MueLu::StructuredAggregationFactory_kokkos<LocalOrdinal, GlobalOrdinal, Node>::Build(MueLu::StructuredAggregationFactory_kokkos<LocalOrdinal, GlobalOrdinal, Node>::Level&) const’:
/home/ikalash/nightlyAlbanyTests/Results/Trilinos/packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_def.hpp:221:39: error: expected type-specifier before ‘AggregationStructuredAlgorithm_kokkos’
       myStructuredAlgorithm = rcp(new AggregationStructuredAlgorithm_kokkos());
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Is this related to your fix?

@mhoemmen : thanks  for the suggestions about cleaning up the Trilinos build.  I will implement them.

**Comment by mhoemmen** [comment] 2019-02-09 21:24
@ikalash PR https://github.com/trilinos/Trilinos/pull/4354 hasn't merged yet.  I can't quite tell what's going on with the PR tests there, so we may need to give it a bit.

**Comment by ikalash** [comment] 2019-02-09 21:26
@mhoemmen I see, that explains it.  I'll continue to keep an eye on it, and close the issue once the Albany builds are back to normal.

**Comment by mhoemmen** [comment] 2019-02-09 21:27
See https://github.com/trilinos/Trilinos/issues/3276#issuecomment-462067485 -- it looks like one of the PR test builds is on a machine that too easily runs out of memory, so it dies when building MueLu.  It may take a couple days for that machine to get taken out of the PR test rotation.

**Comment by lucbv** [comment] 2019-02-11 14:49
@mhoemmen @ikalash PR #4354 has been merged now so there is a shot that it was picked up last night in nightly test. Let me know if that is the case and if it fixes the issue you have been observing?

**Comment by ikalash** [comment] 2019-02-11 17:29
Thanks for the info @lucbv .  Unfortunately our Trilinos build is still failing but the error is different, and seems to be coming from Tpetra: 

```
In file included from Trilinos/packages/tpetra/core/src/Tpetra_Export.cpp:44:
In file included from trilinos-build-serial-clang-release/packages/tpetra/core/src/Tpetra_Export.hpp:2:

Trilinos/packages/tpetra/core/src/Tpetra_Export_def.hpp:56:8: error: redefinition of 'view_alloc_no_init'

auto view_alloc_no_init (const std::string& label) ->
```
Here is the full output:  http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81383

@mhoemmen , any thoughts?

**Comment by mhoemmen** [comment] 2019-02-11 21:21
@ikalash That's my bad.  You would only see that with an ETI off build.  Also, you wouldn't see this if we could get rid of the LocalOrdinal, GlobalOrdinal, and Node template parameters, as planned by @trilinos/tpetra.

**Comment by ikalash** [comment] 2019-02-12 00:01
Thanks, @mhoemmen .  I'll keep an eye out for your fix.  It would be great to get the Albany nightlies back up.

**Comment by mhoemmen** [comment] 2019-02-12 00:44
@ikalash Almost done -- these CUDA builds are slow ....

**Comment by mhoemmen** [comment] 2019-02-12 01:14
@ikalash I just submitted the PR: https://github.com/trilinos/Trilinos/pull/4376

We've been having some issues with PR testing lately -- the Intel license server has been on the blink, for example -- so it may take a day or two for this fix to get in.

**Comment by ikalash** [comment] 2019-02-12 01:15
@mhoemmen : that's fine, thanks for the heads up and for fixing the issue!  I'll keep an eye out for the PR to get merged in.

**Comment by ikalash** [comment] 2019-02-13 18:36
Looks like a couple of our Fedora builds have another muelu error after turning on ETI and setting ``` -D Tpetra_INST_INT_UNSIGNED_LONG=ON```

```
[ 98%] Building CXX object packages/muelu/src/CMakeFiles/muelu.dir/Graph/MueLu_LinkedList.cpp.o
In file included from trilinos-build-serial-clang-release/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_LocalLexicographicIndexManager.cpp:55:

Trilinos/packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp:471:34: error: non-constant-expression cannot be narrowed from type '__gnu_cxx::__alloc_traits, int>::value_type' (aka 'int') to 'MueLu::LocalLexicographicIndexManager >::GO' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]

    const GO multiplier[3] = {1, this->lFineNodesPerDir[0], this->lNumFineNodes10};
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
Trilinos/packages/muelu/src/Utils/MueLu_ETI_3arg.hpp:32:26: note: in instantiation of member function 'MueLu::LocalLexicographicIndexManager >::getCoarseNodeFineLID' requested here
  TPETRA_INSTANTIATE_LGN(MUELU_ETI_GROUP)
                         ^
Trilinos/packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp:471:34: note: insert an explicit cast to silence this issue
    const GO multiplier[3] = {1, this->lFineNodesPerDir[0], this->lNumFineNodes10};
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                                 static_cast(         )
```
(http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81461).

What's a bit puzzling is my machines have the same OS and compiler, and don't encounter the error.  Tagging @lxmota , the owner of the problematic builds.

**Comment by ikalash** [comment] 2019-02-18 19:51
We're still seeing a MueLu-related build issue in one of the Fedora gcc nightlies: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=81635 .  Here is the error:

```
[ 98%] Building CXX object packages/tempus/src/CMakeFiles/tempus.dir/Tempus_IntegratorBasic.cpp.o
In file included from trilinos-build-serial-clang-release/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_LocalLexicographicIndexManager.cpp:55:

Trilinos/packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp:471:34: error: non-constant-expression cannot be narrowed from type '__gnu_cxx::__alloc_traits, int>::value_type' (aka 'int') to 'MueLu::LocalLexicographicIndexManager >::GO' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]

    const GO multiplier[3] = {1, this->lFineNodesPerDir[0], this->lNumFineNodes10};
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
Trilinos/packages/muelu/src/Utils/MueLu_ETI_3arg.hpp:32:26: note: in instantiation of member function 'MueLu::LocalLexicographicIndexManager >::getCoarseNodeFineLID' requested here
  TPETRA_INSTANTIATE_LGN(MUELU_ETI_GROUP)
                         ^
Trilinos/packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp:471:34: note: insert an explicit cast to silence this issue
    const GO multiplier[3] = {1, this->lFineNodesPerDir[0], this->lNumFineNodes10};
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                                 static_cast(         )
```

**Comment by mhoemmen** [comment] 2019-02-19 18:20
@trilinos/muelu Looks like that bit of MueLu is assuming `GO=int`; Albany wants `GO=unsigned long`.

**Comment by lucbv** [comment] 2019-02-19 18:49
@mhoemmen the multiplier array should really be of type `LO` since it only operates on local quantities and is involved in the computation of other `LO` quantities. It is a simple mistake.

**Comment by lucbv** [comment] 2019-02-19 21:25
@ikalash PR #4429 has been merged so I hope that this will fix your issue.
Let me know how things are tomorrow so I can either work some more on it or close this issue, thanks!

**Comment by ikalash** [comment] 2019-02-20 15:52
@lucbv your commit fixed the issue, but it looks like a new one cropped up in some of our builds (see #4440 ).  

I feel like I am playing whack-a-mole...

**Closed by ikalash** 2019-02-20 15:52 UTC
Labels: build, pkg: MueLu
