### ISSUE TITLE
Tpetra:  build error related to default template arguments

### ISSUE THREAD

**Issue by maartenarnst** [trilinos/Trilinos#7339] opened 2020-05-10 13:34 UTC
## Bug Report
@trilinos/tpetra @seheracer

### Description
Build error of latest code from develop branch when both OpenMP and Cuda are enabled as execution spaces.

The compilation exits with an error in "tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp" related to line 531 "Tpetra::Vector<Scalar> diags(rowMap);"

The code just above this line extracts the map "rowMap" from a CrsMatrix stored in the OpenMP execution space.  It looks like what happens is that when the Cuda execution space is enabled in the same build, the vector "diags" is by default in the Cuda execution space, leading to incompatible execution spaces in the construction of "diags". 

In my build, this problem is solved upon replacing "Tpetra::Vector<Scalar> diags(rowMap);" with "Tpetra::Vector<Scalar, LocalOrdinal, GlobalOrdinal, Kokkos::Compat::KokkosOpenMPWrapperNode> diags(rowMap);"

**Comment by seheracer** [comment] 2020-05-10 16:32
Thanks for the notification! I will try to reproduce this error and fix it.

**Comment by seheracer** [comment] 2020-05-10 16:34
Oh you already fixed it! Thanks!  @maartenarnst

**Comment by maartenarnst** [comment] 2020-05-11 13:25
Thanks, @seheracer, for having looked into this and approved the PR.  The status message of the PR indicates that "Some checks haven't completed yet."  It lists "pre-merge inspection," "pre-test inspection," and "pull request autotester."  Do you know if I or we should do anything, such as adding another reviewer or another label, to move forward?  (This is my first time doing this, so I am discovering ...).  Thanks in advance!

**Comment by seheracer** [comment] 2020-05-11 17:04
I added a label for auto tester to test this. It will move on soon.

**Comment by seheracer** [comment] 2020-05-12 21:10
Closing this issue since https://github.com/trilinos/Trilinos/pull/7340 has been merged.

**Closed by seheracer** 2020-05-12 21:10 UTC
Labels: type: bug
