### ISSUE TITLE
MueLu_FixedMatrixPattern-Tpetra_MPI_4 randomly timing out in build Trilinos-atdm-waterman-cuda-9.2-debug starting before 2019-04-24

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5002] opened 2019-04-24 14:39 UTC
## Bug Report
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=MueLu_FixedMatrixPattern-Tpetra_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-04-23T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-03-24T00%3A00%3A00) the test:
* MueLu_FixedMatrixPattern-Tpetra_MPI_4

is randomly timing out in the build:
* Trilinos-atdm-waterman-cuda-9.2-debug

This test usually passes in about 6.5 seconds but has timed out (10 minutes) 5 times in the last 30 days

## Current Status on CDash

[Current 2 week history on CDash](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=MueLu_FixedMatrixPattern-Tpetra_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=today&field5=buildstarttime&compare5=83&value5=2%20weeks%20ago)

## Steps to Reproduce

One should be able to reproduce this failure on waterman as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by bartlettroscoe** [comment] 2019-04-24 16:11
FYI: As shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=75834114&build=4930687) it actually crashed today and showed:

```
...
******* WARNING *******
Level::Set: unable to store "AP reuse data" generated by factory 0x454a4f60 on level 1, as it has not been requested and no keep flags were set for it
sa: damping factor = 1.33   [default]
sa: calculate eigenvalue estimate = 0   [default]
sa: eigenvalue estimate num iterations = 10   [default]
matrixmatrix: kernel params -> 
 [empty list]

Transpose P (MueLu::TransPFactory)
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered /home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-debug/SRC_AND_BUILD/Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:119
Traceback functionality not available

[waterman1:141577] *** Process received signal ***
[waterman1:141577] Signal: Aborted (6)
[waterman1:141577] Signal code:  (-6)
...
```

**Comment by srajama1** [comment] 2019-05-04 02:25
@jhux2 : This seems like a problem

**Comment by jhux2** [comment] 2019-05-06 21:40
I am unable to reproduce on waterman, i.e., the test passes just fine.

**Comment by bartlettroscoe** [comment] 2019-05-06 22:36
@jhux2 said:

> I am unable to reproduce on waterman, i.e., the test passes just fine.

It is a randomly failing test.  Not sure what is needed to trigger this.  Might have to load the GPU up with other tests to trigger this behavior?

Otherwise, is this test testing an important feature for the ATDM customers?  If, not, we can mark this "ATDM Sev: Nonblocker" and we can ignore these failures.

**Comment by jhux2** [comment] 2019-05-07 00:12
> Otherwise, is this test testing an important feature for the ATDM customers? If, not, we can mark this "ATDM Sev: Nonblocker" and we can ignore these failures.

No, this is currently unimportant for ATDM.

**Comment by bartlettroscoe** [comment] 2020-02-28 22:43
As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-01&end=2020-02-28&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-debug&field2=testname&compare2=61&value2=MueLu_FixedMatrixPattern-Tpetra_MPI_4&field3=site&compare3=61&value3=waterman), this test has not timed out a single time since  2019-11-30.

Closing as fixed.

**Closed by bartlettroscoe** 2020-02-28 22:43 UTC
Labels: ATDM Sev: Nonblocker, PA: Linear Solvers, client: ATDM, pkg: MueLu, type: bug
