### ISSUE TITLE
Stratimikos CMake logic appears to depend on Tpetra CMake variables, even if Tpetra not enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#681] opened 2016-10-03 17:00 UTC
@bartlettroscoe @trilinos/stratimikos 

Michele Martone has been working on Epetra changes.  He has been trying to get the check-in test script to work.  When he enabled Epetra and disabled Kokkos explicitly, his SERIAL_RELEASE build got the following CMake errors:

```
Processing enabled package: Stratimikos (Libs, Tests, Examples)
CMake Error at cmake/tribits/core/utils/AssertDefined.cmake:79 (MESSAGE):
  Error, the variable Tpetra_INST_DOUBLE is not defined!
Call Stack (most recent call first):
  packages/stratimikos/test/CMakeLists.txt:166 (ASSERT_DEFINED)
CMake Error at cmake/tribits/core/utils/AssertDefined.cmake:79 (MESSAGE):
  Error, the variable Tpetra_INST_INT_INT is not defined!
Call Stack (most recent call first):
  packages/stratimikos/test/CMakeLists.txt:167 (ASSERT_DEFINED)
```

Does this mean that Stratimikos depends on Tpetra's CMake variables, but nevertheless does not declare a required dependency on Tpetra?  If so, this should be easy to fix: just have the above code check `DEFINED Tpetra_INST_DOUBLE` (etc.) before putting `Tpetra_INST_DOUBLE` (etc.) in an IF statement.

**Comment by bartlettroscoe** [comment] 2016-10-03 17:02
What is the full configure script and the version of Trilinos so that I can reproduce?

**Comment by mhoemmen** [comment] 2016-10-03 17:57
@bartlettroscoe I just forwarded Michele's e-mail to you, with attached configure script.  He says it's latest pull; don't know if that means master or develop.

**Comment by bartlettroscoe** [comment] 2016-10-04 17:23
I was able to reproduce with:

```
cmake \
-DTPL_ENABLE_MPI=ON \
-DCMAKE_BUILD_TYPE=DEBUG \
-DTrilinos_ENABLE_DEBUG=ON \
-DTrilinos_ENABLE_TESTS=ON \
-DTrilinos_ENABLE_Stratimikos=ON \
-DTrilinos_ENABLE_Tpetra=OFF \
../../../Trilinos
```

(using updated [SEMSDevEnv.cmake](https://github.com/trilinos/Trilinos/wiki/SEMS-Dev-Env)) and pushed the fix in commit cf657d2 (I used the wrong commit ID #645 on accident).

@MicheldeMessieres, can you please test this update on your side?  If this fixes this, can you please comment and then close this Issue?

**Comment by MicheldeMessieres** [comment] 2016-10-06 18:57
bartlettroscoe  hi Ross - I think you meant to contact Michele Martone, not me, on your last comment.

**Comment by bartlettroscoe** [comment] 2016-10-06 20:09
> @bartlettroscoe hi Ross - I think you meant to contact Michele Martone, not me, on your last comment.

Sorry about that.

@mhoemmen, is Michele on GitHub and can we ask him to confirm that this is fixed?

**Comment by bartlettroscoe** [comment] 2016-10-07 12:31
> Michele Martone has been working on Epetra changes. He has been trying to get the check-in test script to work. When he enabled Epetra and disabled Kokkos explicitly, his SERIAL_RELEASE build got the following CMake errors:

Just a note on this.  Yes, packages like Stratimikos should build and run tests with some optional dependencies turned off.  But no one should be using the checkin-test.py script to **PUSH** changes disabling packages like Kokkos.  If it is just for local testing that is fine.  But that can't be allowed for pre-push testing because that could break the CI build for other developers that correctly enable the optional dependencies.

**Comment by mhoemmen** [comment] 2016-10-07 15:47
@bartlettroscoe wrote:
> @mhoemmen, is Michele on GitHub and can we ask him to confirm that this is fixed?

Actually yes!  @michelemartone has a pull request open, #503.  However, he doesn't have access to a fast machine for compiling Trilinos, and I don't want to ask him to rebuild to test this.

**Comment by mhoemmen** [comment] 2016-10-07 15:48
@bartlettroscoe wrote:
> But no one should be using the checkin-test.py script to PUSH changes disabling packages like Kokkos.

What about the Epetra-stack-only use case with a pre-C++11 compiler?  Kokkos requires C++11, so if your compiler doesn't support C++11, you're in trouble.

**Comment by bartlettroscoe** [comment] 2016-10-07 17:46
> >  But no one should be using the checkin-test.py script to PUSH changes disabling packages like Kokkos.
>
> What about the Epetra-stack-only use case with a pre-C++11 compiler? Kokkos requires C++11, so if your compiler doesn't support C++11, you're in trouble.

For --extra-builds, that is fine.  But for the --default-builds, all optional packages have to be enabled for any tested package.  Otherwise, someone could break the build of Stratimikos with all optional packages turned on and they would never know it.  The checkin-test.py --default-builds need to be the same for everyone and needs to be identical to the post-push CI build that is posted to CDash to be the most effective. Does that make sense?

Further discussion and debate about CI should can be had in #482.

**Closed** 2021-02-17 12:26 UTC
Labels: CLOSED_DUE_TO_INACTIVITY, MARKED_FOR_CLOSURE, pkg: Stratimikos
