### ISSUE TITLE
Failing MueLu tests on mutrino in ATDM configuration

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#2839] opened 2018-05-29 21:52 UTC
## Next action Status

PR #3736 merged to 'develop' on 10/25/2018 re-enables these tests on 'mutrino'.   Next: Watch for these tests running again on 'mutrino' on 10/26/2018 and (hopefully) passing ...

## Description

The following tests are failing on mutrino in the ATDM configuration nightly testing.  Click links for test output.
[MueLu_CreateOperatorTpetra_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=48648533&build=3604771)
[MueLu_CreateOperatorTpetra_MPI_4](https://testing.sandia.gov/cdash/testDetails.php?test=48648552&build=3604771)
[MueLu_ParameterListInterpreterTpetra_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=48648532&build=3604771)
[MueLu_ParameterListInterpreterTpetra_MPI_4](https://testing.sandia.gov/cdash/testDetails.php?test=48648551&build=3604771)
[MueLu_ParameterListInterpreterTpetraHeavy_MPI_1](https://testing.sandia.gov/cdash/testDetails.php?test=48648535&build=3604771)
[MueLu_ParameterListInterpreterTpetraHeavy_MPI_4](https://testing.sandia.gov/cdash/testDetails.php?test=48648550&build=3604771)

They are failing on the following builds:
[Trilinos-atdm-mutrino-intel-opt-openmp](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3604771)
[Trilinos-atdm-mutrino-intel-debug-openmp](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3604985)

and have been failing since the builds were set up on 5/18/2018

@trilinos/muelu 
@bartlettroscoe 

## Steps to Reproduce
On mutrino clone trilinos and do the following.  This will automatically set up the environment the way that jenkins is running:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh intel-opt-openmp

$ cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
  $TRILINOS_DIR

$ make -j16

$ salloc -N 1 -p standard ctest -j16
```
for more information on how to reproduce see:
https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

**Comment by cgcgcg** [comment] 2018-05-29 22:18
@fryeguy52 Looks like none of the xml files are copied by cmake to the build folder. I don't have access to mutrino, but could you check if they end up somewhere else? This is odd, since it works on other systems. Maybe you could stick some debug statements into this logic block https://github.com/trilinos/Trilinos/blob/1a9e0546b639dad0abff827cd825c45e301d46af/packages/muelu/test/interface/CMakeLists.txt#L189

**Comment by bartlettroscoe** [comment] 2018-05-30 00:53
@fryeguy52, what is interesting, is that when I switched the 'serrano' Jenkins ctest -S driver from using 'salloc' to using 'sbatch', these MueLu failures seemed to go away on that system.  You can see that change by looking at the query:

* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&date=2018-05-29&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-toss3-&field2=groupname&compare2=61&value2=Specialized&field3=buildstarttime&compare3=84&value3=2018-05-28&field4=buildstarttime&compare4=83&value4=2018-05-14&field5=subprojects&compare5=93&value5=MueLu

If you look at what changed from 5/21/2018 to 5/22/2018 as shown at:

* https://testing-vm.sandia.gov/cdash/viewNotes.php?buildid=3536578#!#note1

you see the commits 2ce2ada and be26080:

```
2ce2ada:  Use srun instead of mpiexec on 'serrano' (TRIL-200, #2699)
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu May 17 12:38:26 2018 -0600

M	cmake/std/atdm/toss3/environment.sh

be26080:  Add atdm_run_script_on_compute_node to use sbatch instead of salloc on 'serrano' (TRIL-200)
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Thu May 17 07:44:18 2018 -0600

M	cmake/ctest/drivers/atdm/toss3/local-driver.sh
M	cmake/std/atdm/toss3/environment.sh
```

Can you try making the same switch on 'mutrino' and see if it fixes the problem?

**Comment by bartlettroscoe** [comment] 2018-06-19 00:12
@trilinos/muelu 

FYI: Unfortunately, after switching to use 'sbatch' instead of 'salloc' on 'mutrino' 4 days ago (see PR #2964 and  commit ff791f8edcf3bb6015b8b6f1744d7d95768a068f) these 6 MueLu tests are still failing as shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-06-18&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=7&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=site&compare4=61&value4=mutrino&field5=testname&compare5=65&value5=MueLu&field6=buildstarttime&compare6=84&value6=2018-06-19&field7=buildstarttime&compare7=83&value7=2018-06-16).  It was hopped that making this change would fix these tests because switching to 'sbatch' did in fact fix these failing tests on 'serrano'.

If some MueLu developer can't get on to 'mutrino' to debug this problem, can we just disable these tests for this platform for now so that we can promote this build so we can keep it clean?

**Comment by bartlettroscoe** [comment] 2018-06-20 21:53
Any objection to just disabling these 6 tests on this platform for now and then letting a MueLu developer reproduce and debug these offline?  We have limited funding and time to track down issues like this ourselves on the ATDM DevOps side.

**Comment by cgcgcg** [comment] 2018-06-20 22:06
@jhux2

**Comment by jhux2** [comment] 2018-06-21 01:37
@bartlettroscoe That's fine -- can we keep this issue open, however, so that we don't lose track of this?

**Comment by bartlettroscoe** [comment] 2018-06-21 13:39
@jhux2 said:

> @bartlettroscoe That's fine -- can we keep this issue open, however, so that we don't lose track of this?

Our policy which is outlined at:

* https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/ATDM+Builds+of+Trilinos#ATDMBuildsofTrilinos-Addressingfailures

is that when we disable tests to resolve failures showing up on CDash we keep the issue open and then mark it with the "Disabled Tests" and "Stalled" labels so we can filter them out of our query of issues we are trying to actively address:

* https://github.com/trilinos/Trilinos/issues?q=label%3AATDM+-label%3A%22Disabled+Tests%22+-label%3Aenhancement+sort%3Acreated-desc+is%3Aopen

**Comment by bartlettroscoe** [comment] 2018-07-13 22:49
I merged the commit 870b736 to 'develop' a few weeks ago to disable the tests:

* MueLu_CreateOperatorTpetra_MPI_1
* MueLu_CreateOperatorTpetra_MPI_4
* MueLu_ParameterListInterpreterTpetra_MPI_1
* MueLu_ParameterListInterpreterTpetra_MPI_4
* MueLu_ParameterListInterpreterTpetraHeavy_MPI_1
* MueLu_ParameterListInterpreterTpetraHeavy_MPI_4

As shown in the set of MueLu tests run on 'mutrino' yesterday in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-12&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-mutrino&field2=testname&compare2=65&value2=MueLu_), none of these tests are shown.

I am marking this issue with "Disabled Tests".

**Comment by jhux2** [comment] 2018-10-25 01:35
I believe this can be closed as resolved.

**Comment by jhux2** [comment] 2018-10-25 15:47
Huh, they are disabled in `ALL_BUILDS.cmake`, but I see some, but not all, of the tests running [here](https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=4092743).

**Comment by jhux2** [comment] 2018-10-25 15:48
I spoke too soon, I see they are in fact disabled.  I'll have a look.

**Comment by bartlettroscoe** [comment] 2018-10-25 19:34
FYI: the PR #3736 was just merged that re-enables these tests on 'mutrino'.  I have removed the "Disabled Tests" label and added the "in review" label and we will watch to see these show up (passing hopefully) on CDash tomorrow.

**Comment by jhux2** [comment] 2018-10-26 16:59
These tests are now showing as passing on the dashboard as seen [here](https://testing.sandia.gov/cdash/viewTest.php?onlydelta&buildid=4099480).   I do not see a corresponding build for Trilinos-atdm-mutrino-intel-debug-openmp.  I am closing this as fixed.

**Closed by jhux2** 2018-10-26 16:59 UTC
Labels: ATDM, MueLu, bug, in review

**Comment by bartlettroscoe** [comment] 2018-10-27 15:31
> I do not see a corresponding build for Trilinos-atdm-mutrino-intel-debug-openmp.

@jhux2, the build name was changed to `Trilinos-atdm-mutrino-intel-debug-openmp-HSW` to make the KOKKOS_ARCH being used explicit.

Thanks for fixing!
