### ISSUE TITLE
Document information concerning Clean, Nightly, and Specialized tracks

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1293] opened 2017-05-08 14:35 UTC
@william76 

I need to document the definition of, qualifications for, and process for moving between the 3 new tracks that we are dividing the Nightly track into for automated testing. Definition of done for this story is:

Trilinos GitHub wiki page exists listing
--Three develop branch testing tracks - Clean, Nightly, and specialized, with a description of each track.
--Process for moving from one track to another.

**Comment by jwillenbring** [comment] 2017-05-08 14:41
This needs to include email policies for each of the new tracks. @bartlettroscoe suggested a good place for this information would be here:

[https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing](https://github.com/trilinos/Trilinos/wiki/Policies--%7C-Testing)

**Comment by bartlettroscoe** [comment] 2017-06-12 14:23
What is the status of this?  I thought thought that "Nightly" builds were not supposed to be sending out CDash emails, let least initially until the "Clean" track can be kept clean.  See below email I just got from the "Nightly" track.

----

> -----Original Message-----
> From: stratimikos-regression-bounces@software.sandia.gov
> [mailto:stratimikos-regression-bounces@software.sandia.gov] On Behalf Of
> CDash
> Sent: Monday, June 12, 2017 12:44 AM
> To: stratimikos-regression@software.sandia.gov
> Subject: [Stratimikos-regression] FAILED (c=1): Trilinos/Stratimikos - Linux-GCC-
> 4.7.2-RELEASE_DEV_MueLu_Matlab - Nightly
> 
> A submission to CDash for the project Trilinos has configure errors.
> You have been identified as one of the authors who have checked in changes
> that are part of this submission or you are listed in the default contact list.
> 
> Details on the submission can be found at
> https://testing.sandia.gov/cdash/buildSummary.php?buildid=2944116
> 
> Project: Trilinos
> SubProject: Stratimikos
> Site: dorksaber.srn.sandia.gov
> Build Name: Linux-GCC-4.7.2-RELEASE_DEV_MueLu_Matlab
> Build Time: 2017-06-12T04:43:50 UTC
> Type: Nightly
> Configure errors: 1
> 
> 
> *Configure*
> Status: 1
> (https://testing.sandia.gov/cdash/viewConfigure.php?buildid=2944116)
> Output: ERROR: ld.so: object '/usr/local/gcc/gcc-4.7.2/lib64/libstdc++.so.6'
> from LD_PRELOAD cannot be preloaded: ignored.
> ERROR: ld.so: object '/usr/local/gcc/gcc-4.7.2/lib64/libgcc_s.so.1' from
> LD_PRELOAD cannot be preloaded: ignored.
> ERROR: ld.so: object '/usr
> 
> -CDash on testing.sandia.gov

**Comment by bartlettroscoe** [comment] 2017-09-27 11:56
Any updates on this?  I think that clearly defining and implementing these policies is a task that only the Trilinos framework team can do.  We need these polices clearly spelled out so that we can now how ATDM-focusesd build of Trilinos will be dealt with by the Trilinos Framework team and the Trilinos development community.  That will be a key part of a FY18 deliverable for ATDM.

**Comment by bartlettroscoe** [comment] 2018-01-16 17:19
It seems that the Trilinos project on testing.sandia.gov/cdash/ is not sending out CDash error emails for builds in the `Nightly` category.  Is that on purpose or on accident?  In order to manage the ATDM builds for Trilinos being set up as part of https://software-sandbox.sandia.gov/jira/browse/TRIL-171, we will need CDash to send out emails to the package-regression email lists.  The plan was to send these builds to `Nightly` but if that category does not trigger CDash emails then perhaps we should create a new `ATDM`  category and send builds there so that they send out emails.  Please advice how we should set things up to accomplish sending out emails automatically for failed ATDM builds.  It looks like the GCC 7.2.0 build in #2028 will be ready to elevate today to start sending out emails tomorrow.  Given the current CDash setup it looks like the only category that will trigger emails in ` Clean` but I don't know if that is the right category in this case.

**Comment by jwillenbring** [comment] 2018-01-29 17:11
I have started this here:

https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Test-Dashboard-Policy

A lot is still subject to change before an initial draft is completed.

**Comment by bartlettroscoe** [comment] 2018-01-30 00:00
@jwillenbring,

The page:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Test-Dashboard-Policy

currently talks about a "Clean Track", "Nightly Track", etc. but there is no such thing as a CDash "Track".  On CDash, it is called a "Group".  The term "Track" is used by CTest which submits to the CDash "Group" of that name but there is no such thing as a CDash "Track".

For example, you select the filter "Group" with:

*   https://testing.sandia.gov/cdash/index.php?project=Trilinos&iltercount=1&showfilters=1&field1=groupname&compare1=61&value1=Clean

and when you add a new one of these things.  There is no CDash filter for "Track".

Also, the CDash admin interface has a section called "Groups" under "Settings".  There is no admin section called "Tracks".

Therefore, to remove confusion, "Track" should be replaced with "Group".  You can mention on this page that CTest calls this "Track" if you want but on CDash, this is called a "Group".  Or do what I do and just call them the "Nightly" group/track, for example, to cover your bases.

**Comment by jwillenbring** [comment] 2018-01-30 16:33
> Therefore, to remove confusion, "Track" should be replaced with "Group".

@bartlettroscoe I have incorporated this feedback into the document.
@trilinos/framework 

Also, I have completed the initial draft of the document. There are some things that probably need to be tweaked, but I am ready for an initial round of feedback on the contents.

[https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Test-Dashboard-Policy](https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Test-Dashboard-Policy)

**Comment by bartlettroscoe** [comment] 2018-02-12 20:58
The policies and processes at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Test-Dashboard-Policy

look very reasonable.  I think the next steps are:

* Create a short bullet summary of the the content that can fit it one page (or so).
* Have this reviewed by the Trilinos Leaders and get feedback.

**Comment by bartlettroscoe** [comment] 2021-03-27 16:06
I think this is still needed, no?

**Comment by wadeburgess** [comment] 2021-08-31 20:54
Migrated to Trilinos Help Desk, so closing this issue now.

**Closed by wadeburgess** 2021-08-31 20:54 UTC
Labels: Framework tasks, DO_NOT_AUTOCLOSE
