### ISSUE TITLE
MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4 failing in every ATDM Trilinos build starting 2020-03-17

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#7041] opened 2020-03-18 14:42 UTC
CC: @trilinos/muelu, @srajama1 (Trilinos Linear Solvers Product Lead)

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label "impacting: tests"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

Should be fixed by merge of PR #7042 merged on 3/18/2020.  Next: Watch ATDM Trilinos builds on testing day 2020-03-19 and after to see if this test is fixed ...

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-02-17&end=2020-03-17&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4&field4=testoutput&compare4=94&value4=Error%3A%20Remote%20JSM%20server%20is%20not%20responding%20on%20host) the test:

* `MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4`

is failing in **every** ATDM Trilinos build (I will not bother listing them all) starting on testing day 2020-03-17.

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-02-17&end=2020-03-17&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4&field4=status&compare4=61&value4=failed&field5=testoutput&compare5=95&value5=muelu%2Fsrc%2FMueCentral%2FMueLu_VariableContainer.hpp), all of those failures show the bad dynamic cast:

```
terminate called after throwing an instance of 'Teuchos::bad_any_cast'
  what():  /vscratch1/jenkins/vortex-slave/workspace/Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg/SRC_AND_BUILD/Trilinos/packages/muelu/src/MueCentral/MueLu_VariableContainer.hpp:103:

Throw number = 11

Throw test that evaluated to true: data_->type() != typeid(T)

Error, cast to type Data<Teuchos::RCP<MueLu::GraphBase<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >> failed since the actual underlying type is 'Teuchos::RCP<MueLu::LWGraph_kokkos<int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > >!
[vortex51:137567] *** Process received signal ***
```

## Current Status on CDash

* [MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4 in all ATDM Trilinos Intel builds for current testing day](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4&field4=testoutput&compare4=94&value4=Error%3A%20Remote%20JSM%20server%20is%20not%20responding%20on%20host)

## Steps to Reproduce

One should be able to reproduce this failure on any of these machines as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for a SEMS RHEL7 machine are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue for one of those 'sems-rhel7' builds should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
    Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
 $TRILINOS_DIR

$ make NP=16

$ ctest -R MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4
```

**Comment by mayrmt** [comment] 2020-03-18 14:50
@kliegeois

**Comment by cgcgcg** [comment] 2020-03-18 15:02
Looks like some factories are not specified, and we're building kokkos factories by default. I tried fixing this yesterday, but it didn't seem to work. Will try to reproduce this locally now.

**Comment by lucbv** [comment] 2020-03-18 16:34
@cgcgcg a temporary measure could be to make this test experimental, after all I do not think that @kliegeois is finished working on this...

**Comment by kliegeois** [comment] 2020-03-18 16:39
Sorry for that issue, I did not encounter this issue during the PR process or on my computers.

**Comment by bartlettroscoe** [comment] 2020-03-18 16:49
> Sorry for that issue, I did not encounter this issue during the PR process or on my computers.

So this test passed in PR testing?

**Comment by kliegeois** [comment] 2020-03-18 16:52
> > Sorry for that issue, I did not encounter this issue during the PR process or on my computers.
> 
> So this test passed in PR testing?

Yes, the PR is #6931 and the CDash is [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-6931-test&field2=buildstarttime&compare2=84&value2=NOW).

**Comment by cgcgcg** [comment] 2020-03-18 17:28
Should be fixed now.

**Comment by kliegeois** [comment] 2020-03-18 17:35
Thanks @cgcgcg !

**Comment by bartlettroscoe** [comment] 2020-03-18 19:34
> Should be fixed now.

@cgcgcg, wow, thanks for the fast fix in PR #7042!

I would like to understand how this test passed in all the Trilinos PR builds but was able to fail in all of the ATDM Trilinos builds.  What is different about the PR build configurations from the ATDM Trilinos configuration that allows this test to behave differently?

**Comment by cgcgcg** [comment] 2020-03-18 19:43
@bartlettroscoe The difference is that the ATDM build are setting `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default` and the autotester isn't. 
Setting the variable to `ON` means that we will attempt by default to run kokkos code, unless specified otherwise e.g. via input xml.

I believe we discussed switching it always to `ON` for OpenMP/Cuda backends, but refrained from it until the kokkos code path has been tested more thoroughly.

**Comment by bartlettroscoe** [comment] 2020-03-18 19:49
> The difference is that the ATDM build are setting `MueLu_ENABLE_Kokkos_Refactor_Use_By_Default` and the autotester isn't.

I added #7046 to request on of that Trilinos PR builds set this option to `ON`.

**Closed** 2020-03-19 08:39 UTC
Labels: ATDM Sev: Blocker, PA: Linear Solvers, client: ATDM, client: EMPIRE, impacting: tests, pkg: MueLu, stage: in review, type: bug

**Comment by bartlettroscoe** [comment] 2020-03-19 13:53
FYI: As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2020-03-19&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=61&value3=MueLu_MeshTyingBlocked_SimpleSmoother_MPI_4&field4=testoutput&compare4=94&value4=Error%3A%20Remote%20JSM%20server%20is%20not%20responding%20on%20host), this test is now shown passing in all of the ATDM Trilinos builds run so far today.  So this is resolved.  Thanks!
