### ISSUE TITLE
Amesos2 does not compile with UMFPACK, SuperLU, complex double, and eti=off

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#4537] opened 2019-03-04 17:28 UTC
Basically the compiler cannot chose from 2 convert functions, but does fine the ETI is on as the instantiation gets only one at a time.

@trilinos/amesos2 

## Expectations
Amesos2 should build either with or without ETI on

## Current Behavior
A build matching https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4650329 but with ETI=off will fail to compile Amesos2_Details_registerLinearSolverFactory.cpp.o because it cannot pick between

packages/amesos2/src/Amesos2_Umfpack_TypeMap.hpp:98:7: error: candidates are: class Teuchos::ValueTypeConversionTraits<TypeTo, std::complex<double> >
 class ValueTypeConversionTraits<TypeTo, std::complex<double>>

and

Trilinos/packages/amesos2/src/Amesos2_Superlu_TypeMap.hpp:192:7: error:                 class Teuchos::ValueTypeConversionTraits<SLU::Z::doublecomplex, TypeFrom>
 class ValueTypeConversionTraits<SLU::Z::doublecomplex, TypeFrom>

These take opposite approaches, but can both fulfill the request.

## Motivation and Context
 This was found when checking a trilinos build against Sierra. Customers should be able to build either with or without ETI or one options should be disabled.

I am tagging framework as we need to make sure we have a t least one build that covers this at some level (we currently do all builds with ETI=on as far as I can tell.)

## Definition of Done
Amesos2 compiles both with and without ETI and the requested packages available.

**Comment by ndellingwood** [comment] 2019-03-07 06:38
PR #4564 issued with a fix; issue #4563 turns out to be a duplicate of this issue.

**Comment by ndellingwood** [comment] 2019-03-07 17:32
@prwolfe PR #4564 with a fix for this is merged into Trilinos' develop branch. Closing the issue, please reopen if any problems persist.

**Closed by ndellingwood** 2019-03-07 17:32 UTC
Labels: Framework, pkg: Amesos2

**Comment by prwolfe** [comment] 2019-03-07 17:57
Perfect - Thanks!
