### ISSUE TITLE
Ifpack2: Linking error, duplicate symbols, with TpetraKernels_ENABLE_Experimental=ON

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#786] opened 2016-11-07 18:31 UTC
Is anyone else getting this??  

4062/5246] Linking CXX executable packages/stratimikos/test/Stratimikos_issue_535.exe
FAILED: packages/stratimikos/test/Stratimikos_issue_535.exe 
: && /projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.10.1/bin/mpicxx   -std=c++11 -fopenmp -g -O0   packages/stratimikos/test/CMakeFiles/Stratimikos_issue_535.dir/test_issue_535.cpp.o  -o packages/stratimikos/test/Stratimikos_issue_535.exe  -rdynamic packages/stratimikos/src/libstratimikos.a packages/stratimikos/adapters/belos/src/libstratimikosbelos.a packages/stratimikos/adapters/aztecoo/src/libstratimikosaztecoo.a packages/stratimikos/adapters/amesos/src/libstratimikosamesos.a packages/stratimikos/adapters/ml/src/libstratimikosml.a packages/stratimikos/adapters/ifpack/src/libstratimikosifpack.a packages/ifpack2/adapters/libifpack2-adapters.a packages/ifpack2/src/libifpack2.a packages/thyra/adapters/tpetra/src/libthyratpetra.a packages/triutils/src/libtriutils.a packages/ml/src/libml.a packages/zoltan/src/libzoltan.a -lm packages/ifpack/src/libifpack.a packages/amesos/src/libamesos.a packages/belos/tpetra/src/libbelostpetra.a packages/belos/epetra/src/libbelosepetra.a packages/belos/src/libbelos.a packages/thyra/adapters/tpetra/src/libthyratpetra.a packages/aztecoo/src/libaztecoo.a packages/thyra/adapters/epetraext/src/libthyraepetraext.a packages/thyra/adapters/epetra/src/libthyraepetra.a packages/epetraext/src/libepetraext.a packages/triutils/src/libtriutils.a packages/thyra/core/src/libthyracore.a packages/rtop/src/librtop.a packages/tpetra/core/ext/libtpetraext.a packages/tpetra/core/inout/libtpetrainout.a packages/tpetra/core/src/libtpetra.a packages/epetra/src/libepetra.a packages/tpetra/kernels/src/libtpetrakernels.a packages/kokkos/algorithms/src/libkokkosalgorithms.a packages/kokkos/containers/src/libkokkoscontainers.a packages/tpetra/classic/LinAlg/libtpetraclassiclinalg.a packages/tpetra/classic/NodeAPI/libtpetraclassicnodeapi.a packages/tpetra/classic/src/libtpetraclassic.a packages/teuchos/kokkoscomm/src/libteuchoskokkoscomm.a packages/teuchos/kokkoscompat/src/libteuchoskokkoscompat.a packages/teuchos/remainder/src/libteuchosremainder.a packages/teuchos/numerics/src/libteuchosnumerics.a /usr/lib64/liblapack.so.3 /usr/lib64/libblas.so.3 packages/teuchos/comm/src/libteuchoscomm.a packages/teuchos/parameterlist/src/libteuchosparameterlist.a packages/teuchos/core/src/libteuchoscore.a /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/lib/libboost_program_options.so /projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/lib/libboost_system.so packages/kokkos/core/src/libkokkoscore.a /usr/lib64/libdl.so -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lgfortran -lquadmath -Wl,-rpath,/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.59.0/gcc/5.3.0/base/lib && :
packages/ifpack2/src/libifpack2.a(Ifpack2_Relaxation_OpenMP.cpp.o): In function `KokkosKernels::Experimental::Util::endswith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/include/c++/5.3.0/bits/char_traits.h:258: multiple definition of `KokkosKernels::Experimental::Util::endswith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
packages/ifpack2/src/libifpack2.a(Ifpack2_Details_OneLevelFactory_OpenMP.cpp.o):/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/include/c++/5.3.0/bits/char_traits.h:258: first defined here

**Comment by mhoemmen** [comment] 2016-11-07 19:01
This smells like a namespace issue...

**Comment by bathmatt** [comment] 2016-11-07 19:21
Not sure, you need to build with shared libraries to see it really, no idea what that means..

**Comment by mhoemmen** [comment] 2016-11-09 16:11
@bathmatt are you still getting this?  If it's still in issue, it should affect the release freeze today.

**Comment by bathmatt** [comment] 2016-11-30 14:37
Yes, I'm still getting this, sorry for the long delay, didn't see this.  Just checked this a.m. and got this


packages/ifpack2/src/libifpack2.a(Ifpack2_Relaxation_OpenMP.cpp.o): In function `KokkosKernels::Experimental::Util::endswith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/include/c++/5.3.0/bits/char_traits.h:258: multiple definition of `KokkosKernels::Experimental::Util::endswith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
packages/ifpack2/src/libifpack2.a(Ifpack2_Details_OneLevelFactory_OpenMP.cpp.o):/net/fs02eppic/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/base/include/c++/5.3.0/bits/char_traits.h:258: first defined here
collect2: error: ld returned 1 exit status

**Comment by mhoemmen** [comment] 2016-11-30 18:23
@bathmatt is this with Kokkos profiling enabled? Just curious.

**Comment by bathmatt** [comment] 2016-12-06 15:33
No, 
it happens on both mac and linux.  I'm guessing  I have something on in my config that is causing this.  I'll try to track it down.

**Comment by nmhamster** [comment] 2016-12-06 15:34
@mhoemmen why do you ask if its with profiling enabled? I can't see anything in the error to indicate that, have you seen this error with profiling before? That would be a big pain.

**Comment by bathmatt** [comment] 2016-12-06 15:37
No t is not, it happens on gcc/5.3 on my linux box and clang on my mac.  It looks like it might be a config option, well a bug in trilinos tickled by a config option

**Comment by mhoemmen** [comment] 2016-12-06 15:41
@nmhamster wrote:
> why do you ask if it's with profiling enabled? 

I was thinking that it had to be some option that's not enabled by default, since I saw KokkosKernels::Experimental::Util::endswith there.  I could be wrong, though.  I've never seen this one before.

**Comment by bathmatt** [comment] 2016-12-06 15:44
Siva had me turn that on a long time ago to test some things.  Like most
things in my config file, they get added and never ever go away...

I could try to buid with and w/o that and see if that is an issue, they we
can assign it to someone to fix

**Comment by rppawlo** [comment] 2016-12-06 15:48
Truman reported the same error when building Drekar, but I have not been able to reproduce in my Drekar builds.

**Comment by bathmatt** [comment] 2016-12-06 15:50
He got his config from me, so it is likely that is the case.

**Comment by bathmatt** [comment] 2016-12-06 16:22
I can confirm it is this flag that causes the error.
-D TpetraKernels_ENABLE_Experimental=ON \

We should open a new bug report and asiggn it to the right person.  WHo is
this?

**Comment by mhoemmen** [comment] 2016-12-06 18:37
@bathmatt Are you using Gauss-Seidel with coloring?  If so, @mndevec owns that interface.

**Comment by bathmatt** [comment] 2016-12-06 18:54
NO idea, I'm not using anything anymore from exp kernels.

**Comment by mhoemmen** [comment] 2016-12-07 00:18
@bathmatt can you turn off `TpetraKernels_ENABLE_Experimental` then?

**Comment by mndevec** [comment] 2016-12-07 04:20
Sorry I seem to overlook this issue. I will push a fix for this.

**Comment by mndevec** [comment] 2016-12-07 17:31
The latest push should fix this issue. Sorry for the bug and missing this issue. Cdash was not testing with TpetraKernels_ENABLE_Experimental=ON, but yesterday @csiefer2  set up a new test that experiments with TpetraKernels_ENABLE_Experimental=ON. Hopefully these errors will be caught early.

**Comment by bathmatt** [comment] 2016-12-08 16:46
I did turn it off, not using the experimental kernels anymore,

**Closed** 2016-12-09 05:00 UTC
Labels: Ifpack2, KokkosKernels, Stratimikos
