### ISSUE TITLE
Teplated Tpetra Matrices and LP64 vs ILP64 MKL 

### ISSUE THREAD

**Issue by davoodansari** [trilinos/Trilinos#7394] opened 2020-05-19 12:44 UTC
## Question
@trilinos/\<PackageName\>

What are you wondering about?  What has you confused?  What answers do you
need?  What are you trying to accomplish?  How does your question fit into what
you're trying to do?

**Comment by mayrmt** [comment] 2020-05-19 13:32
Closing, as this issue just posts the issue template and is probably a duplicate of #7395 .

@davoodansari Feel free to edit the description and reopen, if necessary.

**Closed by mayrmt** 2020-05-19 13:32 UTC
Labels: type: question
