### ISSUE TITLE
Sacado test Fad_KokkosTests_NoViewSpec_XXX.cpp CUDA build failures on all CUDA builds starting 11/10/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#3845] opened 2018-11-10 16:40 UTC
CC: @trilinos/sacado, @rppawlo  (Trilinos Nonlinear Solvers Product Lead)
 
## Next Action Status

Enable of `Sacado_ENABLE_HIERARCHICAL_DFAD=ON` in PR #3800 merged on 10/9/2018 triggered this build failure.  PR #3845 (once merged) should fix the failures for all builds ...

## Description

As shown in [this query](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-10&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda&field2=subprojects&compare2=93&value2=Sacado&field3=testspassed&compare3=43&value3=0) the Sacado test suite has two build errors in every Sacado build that builds the Sacado test suite.

The ATDM builds involved (that have submitted to as of 9:20 AM MT on 11/10/2018) include:

* hansen | Trilinos-atdm-hansen-shiller-cuda-8.0-debug
* hansen | Trilinos-atdm-hansen-shiller-cuda-8.0-opt 
* hansen | Trilinos-atdm-hansen-shiller-cuda-9.0-debug
* hansen | Trilinos-atdm-hansen-shiller-cuda-9.0-opt 
* waterman | Trilinos-atdm-waterman-cuda-9.2-debug
* waterman | Trilinos-atdm-waterman-cuda-9.2-opt
* white | Trilinos-atdm-white-ride-cuda-9.2-debug
* white | Trilinos-atdm-white-ride-cuda-9.2-opt
* waterman | Trilinos-atdm-waterman-cuda-9.2-release-debug
* ride | Trilinos-atdm-white-ride-cuda-9.2-debug
* ride | Trilinos-atdm-white-ride-cuda-9.2-debug-pt
* white | Trilinos-atdm-white-ride-cuda-9.2-debug-pt
* ride | Trilinos-atdm-white-ride-cuda-9.2-opt

Some of the non-ATDM Trilinos builds showing this build error include:

* ascic141 | Linux-gcc-7.3.0-Sierra_MPI_release_DEV_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-OFF_COMPLEX-ON
* ascic141 | Linux-gcc-7.3.0-Sierra_MPI_release_DEV_ETI_SERIAL-ON_OPENMP-ON_PTHREAD-OFF_CUDA-OFF_COMPLEX-ON

This results in the Not Run tests:

* Sacado_FadKokkosTests_NoViewSpec_Cuda_MPI_1
* Sacado_FadKokkosTests_NoViewSpec_Serial_MPI_1

in all of these builds.

The build error that occurs is in the files `sacado/test/UnitTests/Fad_KokkosTests_NoViewSpec_Cuda.cpp` and `sacado/test/UnitTests/Fad_KokkosTests_NoViewSpec_Serial.cpp` shown at, for example, [here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=4159745) which shows:

```
home/jenkins/waterman/workspace/Trilinos-atdm-waterman-cuda-9.2-release-debug/SRC_AND_BUILD/Trilinos/packages/sacado/test/UnitTests/Fad_KokkosTests.hpp(223): error: namespace "Kokkos" has no member "is_dynrankview_fad_contiguous"
          detected during instantiation of "void Kokkos_View_Fad_ScalarAssign_UnitTest<FadType, Layout, 

...

15 errors detected in the compilation of "/tmp/tmpxft_000167b4_00000000-6_Fad_KokkosTests_NoViewSpec_Serial.cpp1.ii".
```

The new commits that were pulled the day that these failures started are show, for example, [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4159745#!#note6).  From looking over that set of commits, there are no changes to the Sacado code or tests.  Therefore, one might assume that somehow the PR #3800 merged on 10/9/2018 must have triggered these failures?

## Current Status on CDash

To see the current status of all of these Sacado CUDA builds, see:

* [Sacado CUDA builds with Sacado tests enabled](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda&field2=subprojects&compare2=93&value2=Sacado&field3=testspassed&compare3=43&value3=0)

NOTE: To see the full status, one will need to look at the previous testing day (i.e. click above link and then click "Previous" at the top.

## Steps to Reproduce

One should be able to reproduce this failure on any of the ATDM Trilinos platforms that has a CUDA build as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

For example, on 'white' or 'ride' as described at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

the exact commands to reproduce this build error are:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-opt

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Sacado=ON \
 $TRILINOS_DIR

$ make NP=16
```

But, again, any of the CUDA builds on any of the ATDM Trilinos testing platforms should be able to reproduce this build failure.

**Comment by bartlettroscoe** [comment] 2018-11-10 16:44
CC: @etphipp 

@rppawlo, enabling `Sacado_ENABLE_HIERARCHICAL_DFAD=ON` in PR #3800 must have triggered this build failure.  I forgot to test the Sacado test suite and I am guessing you forgot to do that to.

Should we revert the merge of PR #3800 and fix this offline or can we fix this quickly?

**Comment by bartlettroscoe** [comment] 2018-11-10 16:52
@rppawlo and @etphipp,

What I don't understand is how does enabling `Sacado_ENABLE_HIERARCHICAL_DFAD=ON` in the file `cmake/std/atdm/ATDMDevEnvSettings.cmake` trigger the build failures in the non ATDM Trilinos builds shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda&field2=buildname&compare2=64&value2=Trilinos-atdm-&field3=subprojects&compare3=93&value3=Sacado&field4=testspassed&compare4=43&value4=0)?  Those builds should not include any of the ATDM Trilinos configuration settings, should they?  Looking at the CMakeCache.txt file for one of these builds shown [here](https://testing.sandia.gov/cdash-dev-view/viewNotes.php?buildid=4159783#!#note1), it shows:

```
Sacado_ENABLE_HIERARCHICAL:BOOL=FALSE
Sacado_ENABLE_HIERARCHICAL_DFAD:BOOL=FALSE
```

What is going on here?

**Comment by etphipp** [comment] 2018-11-12 17:07
Hm, that is indeed strange.  I reproduced the build error in a Cuda build (but not a non-Cuda build), and added a PR that fixes it.  I have no idea how you were seeing this error with Sacado_ENABLE_HIERARCHICAL_DFAD=OFF, since the line of code in question was explicitly #ifdef'd out when it is disabled.  Perhaps you have some pollution of configure variables between builds?

**Comment by bartlettroscoe** [comment] 2018-11-12 17:16
@etphipp said:

> I reproduced the build error in a Cuda build (but not a non-Cuda build), and added a PR that fixes it.

Thanks!  Just update this issue once this PR merges.  And you can verify things are fixed tomorrow by clicking the link under the "Current Status on CDash" section [above](https://github.com/trilinos/Trilinos/issues/3845#issue-379437497).

> Perhaps you have some pollution of configure variables between builds?

I don't see how that is possible.  The archived CMakeCache.txt file shows these turned off as shown [above](https://github.com/trilinos/Trilinos/issues/3845#issuecomment-437597897).  I guess one could try to reproduce this build error in the non-ATDM Trilinos and then verify that is is not impacted by the ATDM Trilinos build settings.  But if your PR #3845 fixes all of the builds, then it is not worth looking into from the ATDM perspective.

**Comment by etphipp** [comment] 2018-11-14 17:04
Looks like this did in fact fix the build errors, so I am closing this issue.

**Closed by etphipp** 2018-11-14 17:04 UTC
Labels: ATDM, Sacado, bug

**Comment by bartlettroscoe** [comment] 2018-11-14 17:14
@etphipp, indeed, Sacado built and 100% passed on all of the ATDM Trilinos builds yesterday as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&date=2018-11-13&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda&field3=subprojects&compare3=93&value3=Sacado).

Thanks for fixing so fast!
