### ISSUE TITLE
Building Sacado with relocatable device code enabled

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#4457] opened 2019-02-21 13:47 UTC
@trilinos/sacado 
CC: @trilinos/framework @bartlettroscoe @rppawlo @alanw0 

## Expectations

Multiple major Trilinos customers now need to build Trilinos with relocatable device code enabled for CUDA builds. Per @rppawlo this can take a lot of effort to get working. 

## Current Behavior

I fired off a build with rdc enabled to help gauge our current status and encountered [these issues](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4589862) with Sacado (note that the system caps errors at 50).

## Definition of Done

I had two objectives in filing this ticket. 

1. Post the current Sacado issues I am seeing so that they can be evaluated and possibly fixed.

1. Start a broader discussion about the effort that might be required to get rdc working across Trilinos.

## Steps to Reproduce

I used the jwillenbring/trilinos rdc_test branch and the standard PR CUDA build on ride to produce the errors. A fix can be tested by submitting a PR, or I would be willing to test a branch that someone points me to.

**Comment by rppawlo** [comment] 2019-02-21 14:33
RDC is not the most stable thing. Long term we will probably need two cuda builds for the PR testing - one with RDC enabled and one disabled. Failures are usually build errors with RDC, so maybe we get away with building but not running the tests for one of the two builds?

**Comment by etphipp** [comment] 2019-02-21 15:36
This is a duplicate of issue #2891, and this has nothing to do with Sacado per se.  It is caused by libteuchoscore.a, which defines some static symbols, appearing twice on the link line.  Reading through the comments on that issue, it is unclear if it was ever determined if this is a bug in CMake, Tribits, or nvcc/nvcc_wrapper.

**Comment by bartlettroscoe** [comment] 2019-02-21 16:05
FYI: I will go ahead and set up some nightly "Specialized" ATDM Trilinos CUDA 9.2 RDC builds on 'white'/'ride' and 'waterman'.  If you want to get updates on this, add yourself as a watcher to  [TRIL-262](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-262).

**Comment by vbrunini** [comment] 2019-02-21 16:19
nvcc_wrapper does have a "--remove-duplicate-link-files" option that helps a lot working around these issues.

**Comment by etphipp** [comment] 2019-03-05 14:56
PR #4546 fixed the dependencies for Sacado and I verified it eliminates the duplication of libteuchoscore.a on the link line, so I am closing this issue.

**Closed by etphipp** 2019-03-05 14:56 UTC
Labels: pkg: Sacado
