### ISSUE TITLE
Belos_pseudo_stochastic_pcg_hb_[0,1]_MPI_4 tests failing due to max iterations limit seemingly randomly in the `Trilinos-atdm-white-ride-cuda-debug` build on 'white'

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2920] opened 2018-06-08 16:43 UTC
CC: @trilinos/belos, @fryeguy52, @srajama1 (Linear Solvers Product Lead)

## Next Action Status

Disabled in build `Trilinos-atdm-white-ride-cuda-debug` in commit cc7fff2 pushed on 6/12/2018 and showed disabled and missing on CDash on 6/13/2018.  PR #3546 merged on 10/2/2018 which re-enables tests that should be fixed from PR #3050 merged before.  Next: Wait for confirmation on CDash.  If these tests never fail by 12/2/2018, then close ...

## Description

As shown in [this rather complex query showing all failing Belos tests other than Belos_rcg_hb_MPI_4 in all promoted ATDM builds since 5/10/2018](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=17&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-mutrino-intel-debug-openmp&field3=buildname&compare3=62&value3=Trilinos-atdm-mutrino-intel-opt-openmp&field4=buildname&compare4=62&value4=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field5=site&compare5=62&value5=ride&field6=testname&compare6=62&value6=Belos_rcg_hb_MPI_4&field7=buildstarttime&compare7=84&value7=2018-06-08&field8=buildstarttime&compare8=83&value8=2018-05-10&field9=buildname&compare9=62&value9=Trilinos-atdm-white-ride-cuda-opt&field10=buildname&compare10=62&value10=Trilinos-atdm-white-ride-gnu-opt-openmp&field11=site&compare11=62&value11=serrano&field12=site&compare12=62&value12=shiller&field13=buildname&compare13=62&value13=Trilinos-atdm-white-ride-cuda-debug-all-at-once&field14=site&compare14=62&value14=chama&field15=testname&compare15=65&value15=Belos&field16=status&compare16=62&value16=passed&field17=status&compare17=62&value17=notrun) the tests:

* Belos_pseudo_stochastic_pcg_hb_0_MPI_4
* Belos_pseudo_stochastic_pcg_hb_1_MPI_4

failed 5 times in total and appear to be randomly failing in the `Trilinos-atdm-white-ride-cuda-debug` build.  (The other failing test shown was `Belos_pseudo_pcg_hb_1_MPI_4` also for the `Trilinos-atdm-white-ride-cuda-debug` build but that only failed once yesterday so we will ignore that for now.) (The test `Belos_rcg_hb_MPI_4` was excluded from the above query because it is addressed in #2919.)

Looking at the testing history for these tests `Belos_pseudo_stochastic_pcg_hb_[0,1]_MPI_4` from 5/10/2018 through today 6/8/2018 in [this less complex query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=6&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=site&compare2=62&value2=ride&field3=testname&compare3=65&value3=Belos_pseudo_stochastic_pcg_hb_&field4=buildstarttime&compare4=84&value4=2018-06-08&field5=buildstarttime&compare5=83&value5=2018-05-10&field6=buildname&compare6=61&value6=Trilinos-atdm-white-ride-cuda-debug) one can see that these tests complete in about the same time in under 2 seconds when they pass or fail.

The output when these tests fail (such as shown for the test `Belos_pseudo_stochastic_pcg_hb_1_MPI_4` yesterday on 6/7/2018 [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48082702&build=3589607)) looks like:

```
Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (104, 1, Passed)
   Passed.......OR Combination -> 
     Failed.......Number of Iterations = 100 == 100
     Unconverged..(2-Norm Imp Res Vec) / (2-Norm Res0)
                  residual [ 0 ] = 8.95881e-09 < 1e-08
                  residual [ 1 ] = 1.21989e-08 > 1e-08
                  residual [ 2 ] = 6.84374e-09 < 1e-08
                  residual [ 3 ] = 9.15804e-09 < 1e-08
                  residual [ 4 ] = 7.2567e-09 < 1e-08

Passed.......OR Combination -> 
  Failed.......Number of Iterations = 100 == 100
  Unconverged..(2-Norm Imp Res Vec) / (2-Norm Res0)
               residual [ 0 ] = 8.95881e-09 < 1e-08
               residual [ 1 ] = 1.21989e-08 > 1e-08
               residual [ 2 ] = 6.84374e-09 < 1e-08
               residual [ 3 ] = 9.15804e-09 < 1e-08
               residual [ 4 ] = 7.2567e-09 < 1e-08

==================================================================================================================================

                                              TimeMonitor results over 4 processors

Timer Name                                               MinOverProcs     MeanOverProcs    MaxOverProcs     MeanOverCallCounts    
----------------------------------------------------------------------------------------------------------------------------------
Belos: Operation Op*x                                    0.06571 (101)    0.07122 (101)    0.07694 (101)    0.0007051 (101)       
Belos: Operation Prec*x                                  0.1014 (104)     0.108 (104)      0.1151 (104)     0.001039 (104)        
Belos: PseudoBlockStochasticCGSolMgr total solve time    0.2159 (1)       0.216 (1)        0.2162 (1)       0.216 (1)             
Epetra_CrsMatrix::Multiply(TransA,X,Y)                   0.0665 (102)     0.07206 (102)    0.07777 (102)    0.0007065 (102)       
Epetra_CrsMatrix::Solve(Upper,Trans,UnitDiag,X,Y)        0.101 (210)      0.1076 (210)     0.1147 (210)     0.0005122 (210)       
==================================================================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 : 	8.95881e-09
Problem 1 : 	1.21989e-08
Problem 2 : 	6.84374e-09
Problem 3 : 	9.15804e-09
Problem 4 : 	7.2567e-09

End Result: TEST FAILED
```

So this shows that the test fails due to the max iteration limit of 100 being reached before reaching the desired residual tolerance .  The other failures for the tests `Belos_pseudo_stochastic_pcg_hb_0_MPI_4` and `Belos_pseudo_stochastic_pcg_hb_1_MPI_4` look to all be maxing out the number of iterations at 100.

When the test `Belos_pseudo_stochastic_pcg_hb_1_MPI_4` passed the day before on 6/6/2018 as shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48012272&build=3584608) showed output like:

```
Belos::StatusTestGeneralOutput: Passed
  (Num calls,Mod test,State test): (89, 1, Passed)
   Passed.......OR Combination -> 
     OK...........Number of Iterations = 87 < 100
     Converged....(2-Norm Imp Res Vec) / (2-Norm Res0)
                  residual [ 0 ] = 5.02551e-09 < 1e-08
                  residual [ 1 ] = 5.92159e-09 < 1e-08
                  residual [ 2 ] = 6.61897e-09 < 1e-08
                  residual [ 3 ] = 8.2598e-09 < 1e-08
                  residual [ 4 ] = 3.67011e-09 < 1e-08

Passed.......OR Combination -> 
  OK...........Number of Iterations = 87 < 100
  Converged....(2-Norm Imp Res Vec) / (2-Norm Res0)
               residual [ 0 ] = 5.02551e-09 < 1e-08
               residual [ 1 ] = 5.92159e-09 < 1e-08
               residual [ 2 ] = 6.61897e-09 < 1e-08
               residual [ 3 ] = 8.2598e-09 < 1e-08
               residual [ 4 ] = 3.67011e-09 < 1e-08

=================================================================================================================================

                                              TimeMonitor results over 4 processors

Timer Name                                               MinOverProcs     MeanOverProcs    MaxOverProcs    MeanOverCallCounts    
---------------------------------------------------------------------------------------------------------------------------------
Belos: Operation Op*x                                    0.0652 (88)      0.06892 (88)     0.07251 (88)    0.0007831 (88)        
Belos: Operation Prec*x                                  0.09675 (89)     0.1009 (89)      0.1101 (89)     0.001134 (89)         
Belos: PseudoBlockStochasticCGSolMgr total solve time    0.195 (1)        0.195 (1)        0.195 (1)       0.195 (1)             
Epetra_CrsMatrix::Multiply(TransA,X,Y)                   0.06596 (89)     0.06969 (89)     0.07333 (89)    0.0007831 (89)        
Epetra_CrsMatrix::Solve(Upper,Trans,UnitDiag,X,Y)        0.09635 (180)    0.1006 (180)     0.1098 (180)    0.0005587 (180)       
=================================================================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 : 	5.02551e-09
Problem 1 : 	5.92159e-09
Problem 2 : 	6.61897e-09
Problem 3 : 	8.2598e-09
Problem 4 : 	3.67011e-09

End Result: TEST PASSED
```

which shows it converged in 87 iterations.  I looked at several other instances when these tests passed and they all look to be converging in 87 iterations.

Is this non-deterministic behavior due to fact that this is "stochastic" code and therefore the behavior is truly random or is it due to the fact that the random seed is not set consistently, or is it due to non-deterministic behavior in the accumulations with the CUDA 8.0 threaded Kokkos implementation on this machine?  The fact that the test seems to converge in 87 iterations when it passes suggests that this is not purposeful random behavior but is a result of some other undesired and unintended random behavior.

## Steps to reproduce

Following the instructions at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

one might be able to reproduce this behavior on 'white' or 'ride' by cloning the Trilinos github repo, getting on the 'develop' branch and then doing:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Belos=ON \
  $TRILINOS_DIR

$ make NP=16 

$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

But given that this test looks to be randomly failing, it may be hard to reproduce this behavior locally.

**Comment by bartlettroscoe** [comment] 2018-06-08 16:50
Given that the ATDM APP codes are unlikely to be using a [(symmetric) pseudo-block stochastic CG solver](https://trilinos.org/docs/dev/packages/belos/doc/html/classBelos_1_1PseudoBlockStochasticCGSolMgr.html#details) and this is breaking already cleaned up and promoted builds on 'white' and 'ride', I think it would be reasonable to disable these tests for at least the CUDA builds on 'white' and 'ride'.   (We can't have randomly failing tests in promoted builds (since there will soon be automating processes based on this build).

But if this is an important solver to some important customers, then someone should take the time to try to debug what is happening here in case this is a defect in the solver code and not just a defect in the test (like was causing the random test failures in #2473).

If we do disable theses tests for the CUDA builds on 'white' and 'ride', we will mark this issue with "Disabled Tests" and "Stalled" and leave it open as a reminder to address the problems.

**Comment by mhoemmen** [comment] 2018-06-08 17:08
@bartlettroscoe The [class documentation](https://trilinos.org/docs/dev/packages/belos/doc/html/classBelos_1_1PseudoBlockStochasticCGIter.html) says "THIS CODE IS CURRENTLY EXPERIMENTAL. CAVEAT EMPTOR."  I'd say, please feel free to disable the tests.

**Comment by srajama1** [comment] 2018-06-08 18:50
@hkthorn : Can you comment on disabling (and fixing later) these tests on CUDA ?

**Comment by bartlettroscoe** [comment] 2018-06-14 13:34
These tests were disabled for the build `Trilinos-atdm-white-ride-cuda-debug` in commit cc7fff2 pushed on 6/12/2018.  You can see that these tests were disabled on CDash on 6/13/2018 for this build at:

* https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3607499

which shows:

```
-- Setting default Belos_pseudo_stochastic_pcg_hb_0_MPI_4_DISABLE=ON
-- Setting default Belos_pseudo_stochastic_pcg_hb_1_MPI_4_DISABLE=ON
...
-- Belos_pseudo_stochastic_pcg_hb_0_MPI_4: NOT added test because Belos_pseudo_stochastic_pcg_hb_0_MPI_4_DISABLE='ON'!
-- Belos_pseudo_stochastic_pcg_hb_1_MPI_4: NOT added test because Belos_pseudo_stochastic_pcg_hb_1_MPI_4_DISABLE='ON'!
```

and those tests are missing from:

* https://testing-vm.sandia.gov/cdash/viewTest.php?buildid=3607499

(NOTE: These tests are not shown as "missing" since the 'bsub' command crashed the day before and therefore CDash does not note this.)

But these tests are being enabled and run for other builds as shown, for example, in:

* https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3607563

which shows:

```
-- Belos_pseudo_stochastic_pcg_hb_0_MPI_4: Added test (BASIC, NUM_MPI_PROCS=4, PROCESSORS=4)!
-- Belos_pseudo_stochastic_pcg_hb_1_MPI_4: Added test (BASIC, NUM_MPI_PROCS=4, PROCESSORS=4)!
```

**Comment by mhoemmen** [comment] 2018-06-18 04:17
I looked at the code -- it actually uses a random number, but on host, not on device.

**Comment by bartlettroscoe** [comment] 2018-06-18 13:21
> I looked at the code -- it actually uses a random number, but on host, not on device.

@mhoemmen, is it not given the same seed so that each run of the test is the same?  Or, is the behavior of the code in this test truly random (which makes it a problematic test in general)?

**Comment by bartlettroscoe** [comment] 2018-06-18 13:45
As shown in [this updated query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=14&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=62&value2=Trilinos-atdm-mutrino-intel-debug-openmp&field3=buildname&compare3=62&value3=Trilinos-atdm-mutrino-intel-opt-openmp&field4=buildname&compare4=62&value4=Trilinos-atdm-white-ride-cuda-debug-pt-all-at-once&field5=site&compare5=62&value5=ride&field6=testname&compare6=62&value6=Belos_rcg_hb_MPI_4&field7=buildstarttime&compare7=84&value7=2018-06-19&field8=buildstarttime&compare8=83&value8=2018-06-01&field9=site&compare9=62&value9=serrano&field10=site&compare10=62&value10=shiller&field11=site&compare11=62&value11=chama&field12=testname&compare12=65&value12=Belos&field13=status&compare13=62&value13=passed&field14=status&compare14=62&value14=notrun), the tests `Belos_pseudo_stochastic_pcg_hb_[0,1]_MPI_4` is also randomoly failing in the build `Trilinos-atdm-white-ride-cuda-opt` showing it hitting the 100 iteration max when it does fail (for example as seen [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48699102&build=3622294) and [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=48699103&build=3622294)).  Therefore these tests need to be disabled for that build as well.

**Comment by mhoemmen** [comment] 2018-06-18 16:13
@bartlettroscoe It uses `rand` which doesn't promise the same behavior on different compilers, hardware, etc.  A poor choice of random coefficient could affect convergence.

We should actually fix the solver by using one of the C++11 random number generators that promises cross-platform identical behavior, given the same seed.

**Comment by hkthorn** [comment] 2018-07-02 17:03
@bartlettroscoe @mhoemmen  Given that the single-vector CG solvers are just barely not converging on these test platforms,#2920 and #3007, I am increasing the maximum number of iterations by a little.  There is nothing wrong with the solvers.  This is not just due to the stochastic nature of this solver, the preconditioned CG solver has the same issue #3007.  That is because, there is still randomization used to generate the right-hand side for the linear system being solved.

I'm going ahead with the modification to the CMakeLists.txt so we can close this issue and get the tests back up and running on white/ride.

**Comment by srajama1** [comment] 2018-07-02 17:08
@hkthorn Thanks for taking care of this ! I am curious.  Does random rhs has any benefit over a fixing the answer x (say to all ones) and then do A *x to arrive at the rhs ? That way we will workaround this issue altogether.

**Comment by hkthorn** [comment] 2018-07-02 17:14
@srajama1 Fixing the answer to a constant value could be a bad choice for test matrices, it's dependent upon the eigenvalues/vectors.  I don't want to do that.  I have toyed with the idea of just creating a RHS vector for each matrix that we use, so we know the expected behavior of the solver and are not subject to platform-dependent randomization.

**Comment by srajama1** [comment] 2018-07-02 22:10
@hkthorn : I thought this was for one matrix. If it was multiple, then yes, I meant one answer for each. We can commit the rhs vector in another file, if needed.

**Comment by bartlettroscoe** [comment] 2018-07-03 01:29
> We can commit the rhs vector in another file, if needed.

That would eliminate the different behavior on different platforms.  Having tests that behave differently on different platform due to different behavior from the random number generator is generally not desirable behavior.

**Comment by bartlettroscoe** [comment] 2018-10-02 21:32
Reopening until we have confirmation on CDash.    I have removed the `Disabled Tests` label and have updated the "Next Action Status" field to say we will watch this until 12/2/2018 and will close if we don't see any more random failures of these tests by that time.

NOTE: If these were not randomly failing tests and they failed every day before, then we could look at the CDash results tomorrow and then comment and close this issue then if these tests passed.  But since these were random failures, we have to wait much much longer to get confirmation.

Make sense?

**Comment by bartlettroscoe** [comment] 2018-10-02 21:33
Reopening like I said I would :-)

**Comment by hkthorn** [comment] 2018-10-02 22:01
Alrighty, I expect that you will close this bug then.

**Comment by bartlettroscoe** [comment] 2018-10-03 00:10
> Alrighty, I expect that you will close this bug then.

@hkthorn, for now, yes.  But in the future, someone responsible for the Trilinos Linear Solvers Product Area will do it as part of a better structured process.

**Comment by fryeguy52** [comment] 2018-12-03 17:59
As per the next action status these have not failed and it is 12/3/2018 so I am marking this as closed. 

here are links to the tests' histories:
[Belos_pseudo_stochastic_pcg_hb_1_MPI_4](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-04&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-&field2=testname&compare2=63&value2=Belos_pseudo_stochastic_pcg_hb_0_MPI_4&field3=buildstarttime&compare3=84&value3=now&field4=site&compare4=61&value4=white)
[Belos_pseudo_stochastic_pcg_hb_1_MPI_4](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-09-04&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-&field2=testname&compare2=63&value2=Belos_pseudo_stochastic_pcg_hb_1_MPI_4&field3=buildstarttime&compare3=84&value3=now&field4=site&compare4=61&value4=white)

**Closed by fryeguy52** 2018-12-03 17:59 UTC
Labels: ATDM, PA: Linear Solvers, bug, in review, packages: Belos
