### ISSUE TITLE
Work-around for IBM xlC bug (was called "Attempt to intialize matrix in header file fails under IBM xlC")

### ISSUE THREAD

**Issue by djfitzgerald** [trilinos/Trilinos#2789] opened 2018-05-21 20:43 UTC
When attempting to unit test a fix I've been working on for #2781, the IBM XL compiler fails at  [packages/seacas/libraries/ioss/src/generated/Iogn_GeneratedMesh.h:493](https://github.com/trilinos/Trilinos/blob/3cc0152887609df06f04477ce483bca090fdab45/packages/seacas/libraries/ioss/src/generated/Iogn_GeneratedMesh.h#L493) with `error: 1540-2991 The expression is not supported.`  The failing expression is as follows:
```
double rotmat[3][3]{};
```

This change was added since 12.12.1, and I don't know what its purpose was so I am loath to "fix" it.  I am building Trilinos from Spack, using a Spack repository to recognize a fake Trilinos "version 12.13.1" that points to a working branch in my fork of this GitHub repository.  From the hacked Spack `package.py` file for my local Trilinos install:
```
version('12.13.1',
            git='https://github.com/basicmanfitz/Trilinos.git', branch='fix-2781')
```
My Spack install command is:
```
spack install --test=root trilinos@12.13.1%xl_r ~pnetcdf ^netlib-lapack+external-blas ^netcdf%gcc ^m4%gcc
```
And the pertinent text from my Spack build log:
```
     7271    cd /tmp/danfitz/spack-stage/spack-stage-g_hy3L/Trilinos/spack-build/packages/teuchos/comm/src && /opt/ibm/spectrum_mpi/bin/mpixlC -+ -DTEUCHOSCOMM_LIB_E
             XPORTS_MODE -Dteuchoscomm_EXPORTS -I/tmp/danfitz/spack-stage/spack-stage-g_hy3L/Trilinos/spack-build -I/u/danfitz/spack/var/spack/stage/trilinos-12.13.1
             -c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/teuchos/comm/src -I/u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h
             6/Trilinos/packages/teuchos/parameterlist/src -I/u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/teu
             chos/parser/src -I/tmp/danfitz/spack-stage/spack-stage-g_hy3L/Trilinos/spack-build/packages/teuchos/core/src -I/u/danfitz/spack/var/spack/stage/trilinos
             -12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/teuchos/core/src -I/tmp/danfitz/spack-stage/spack-stage-g_hy3L/Trilinos/spack-build/packages
             /kokkos/core/src -I/u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/kokkos/core/src -I/u/danfitz/spa
             ck/opt/spack/linux-rhel7-ppc64le/xl_r-16.1/boost-1.67.0-5bom5du2myssl3gywvnxdzxhurklibbg/include  -DMUMPS_5_0 -std=c++11 -g -qpic   -o CMakeFiles/teucho
             scomm.dir/Teuchos_YamlParameterListHelpers.cpp.o -c /u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages
             /teuchos/comm/src/Teuchos_YamlParameterListHelpers.cpp
     7272    In file included from /u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/seacas/libraries/ioss/src/gen
             erated/Iogn_GeneratedMesh.C:39:
  >> 7273    /u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/seacas/libraries/ioss/src/generated/Iogn_GeneratedM
             esh.h:493:44: error: 1540-2991 The expression is not supported.
     7274        double                     rotmat[3][3]{};
     7275                                               ^
     7276    1 error generated.
  >> 7277    Error while processing /u/danfitz/spack/var/spack/stage/trilinos-12.13.1-c4ai2lelm44crs4zncdh35bylpr766h6/Trilinos/packages/seacas/libraries/ioss/src/ge
             nerated/Iogn_GeneratedMesh.C.
  >> 7278    make[2]: *** [packages/seacas/libraries/ioss/src/generated/CMakeFiles/Iogn.dir/Iogn_GeneratedMesh.C.o] Error 1
     7279    make[2]: *** Waiting for unfinished jobs....
     7280    make[2]: Leaving directory `/tmp/danfitz/spack-stage/spack-stage-g_hy3L/Trilinos/spack-build'
  >> 7281    make[1]: *** [packages/seacas/libraries/ioss/src/generated/CMakeFiles/Iogn.dir/all] Error 2

```

**Comment by mhoemmen** [comment] 2018-05-22 04:57
Huh, I tried the expression in godbolt.org and it built with everything -- even MSVC 19 2017.  Here's what I tried:
```
int main (int argc, char* argv[]) {
    double rotmat[3][3] {};
    return 0;
}
```

**Comment by mhoemmen** [comment] 2018-05-22 05:03
I think it's valid C++11 code.  For example: http://en.cppreference.com/w/cpp/language/aggregate_initialization

> If the number of initializer clauses is less than the number of members ... or initializer list is completely empty, the remaining members are initialized ... by empty lists, in accordance with the usual list-initialization rules (which performs value-initialization for non-class types and non-aggregate classes with default constructors, and aggregate initialization for aggregates). If a member of a reference type is one of these remaining members, the program is ill-formed.

**Comment by mhoemmen** [comment] 2018-05-22 05:06
What XL version is it?  We've seen some issues with some versions: https://github.com/kokkos/kokkos-kernels/issues/230#issuecomment-390724973

**Comment by basicmanfitz** [comment] 2018-05-22 13:35
@mhoemmen Its xlC 16.1

**Comment by basicmanfitz** [comment] 2018-05-22 15:25
@mhoemmen It does not build.  I get the following error (which is different from the error I get from when Spack tries to build):
```
[/u/danfitz]> xlC test.cpp -o test 
test.cpp:2:24: error: expected ';' at end of declaration
    double rotmat[3][3] {};
                       ^
                       ;
1 error generated.
Error while processing test.cpp.
```

**Comment by mhoemmen** [comment] 2018-05-22 15:40
@basicmanfitz I'm pretty sure Seacas would accept a modest pull request to work around this issue in xlC.  Does the following code compile?
```
double rotmat[3][3] {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}};
```

**Comment by mhoemmen** [comment] 2018-05-22 15:48
@basicmanfitz Also, could you please file an xlC bug for this?  I think the empty curly braces expression is valid C++ code.

**Comment by basicmanfitz** [comment] 2018-05-22 17:44
@mhoemmen That didn't help.  It looks like the default behavior of xlC++ is to use `-std=gnu++98`.  If I set `-std=gnu++11` then that example (as well as the earlier one) compiles.  This might be an issue for the Spack package scripts for Trilinos and not for Trilinos itself.

**Comment by basicmanfitz** [comment] 2018-05-22 20:37
I'm still struggling with this, and I'm not sure if its an issue with Spack or the Trilinos cmake scripts.  I've been able to make progress by having the Spack package specify `-DTrilinos_CXX11_FLAGS:STRING=-std=gnu++11` to the cmake call, but the problem persists.  Looking at the logs, I've realized that this seems to be coming from a C header file, and not a C++ header file.  As a result, I've tried a number of things to force the GNU variant of the C11 standard, but still get the error.

I'm attaching a copy of my Spack Trilinos package definition and the full Spack build.out file to help the Trilinos developers shoot this problem:
[package.py.txt](https://github.com/trilinos/Trilinos/files/2028475/package.py.txt)
[spack-build.out.txt](https://github.com/trilinos/Trilinos/files/2028474/spack-build.out.txt)

**Comment by mhoemmen** [comment] 2018-05-22 20:53
@basicmanfitz Trilinos requires C++11, and the enabled set of packages in those scripts _definitely_ require C++11.  I'm glad that xlC++ isn't the issue :)

**Comment by basicmanfitz** [comment] 2018-05-22 21:33
@mhoemmen But remember that Spack works on Trilinos for 12.12.1 and earlier versions.  Something about the line of code that I tagged here is breaking it and I can't figure out why.  All I know is that its preventing me from testing a Trilinos fix I want to open a PR on.

**Comment by basicmanfitz** [comment] 2018-05-22 21:34
I have half a mind to open the PR anyway, but I am loath to do it because I haven't UT'd it on the latest Trilinos code.  I don't want to have the pull request rejected or to have egg on my face if anything breaks.  But I really don't have any more time to devote to shooting this problem... thats why I could use some help from the team here.

**Comment by mhoemmen** [comment] 2018-05-22 21:59
@basicmanfitz Literally no one I work with actually uses Spack to build Trilinos.  That seems to be an xSDK thing.

**Comment by mhoemmen** [comment] 2018-05-22 22:00
@basicmanfitz Do you have a contact for Spack issues?  It's pretty easy to patch Seacas, but if you can't get the compiler to enable C++11, you'll have lots of trouble building many Trilinos packages.  The Spack script definitely enables many packages that require C++11.

**Comment by nmhamster** [comment] 2018-05-22 22:12
@mhoemmen / @basicmanfitz - you should be using `-std=c++11` for XL. They are pretty much completely standards complaint (to the "real" standard) in our experience. We typically try to avoid other non-standard compiler implementations since its seen as being better to focus on the "real" standard. 

@mhoemmen - FYI - we are doing initial testing on IBM XL 16.1 for release on White, Ride and Waterman.

**Comment by mhoemmen** [comment] 2018-05-23 04:27
@nmhamster wrote:
> FYI - we are doing initial testing on IBM XL 16.1 for release on White, Ride and Waterman.

Just curious -- is the plan now to use Spack for deploying Trilinos on these platforms?  We don't have a lot of Spack expertise; hopefully it's not too different than just writing a CMake recipe.

**Comment by hubert-reinterpretcast** [comment] 2018-05-25 17:19
This looks to be a case where XL's support for default member initializers is incomplete. I think a workaround would be to move `rotmat` to a base class (so the initialization of that member can be done through the initialization of the base class):
```
class GeneratedMeshBaseImpl {
  friend class GeneratedMeshBase;
private:
  GeneratedMeshBaseImpl() = default;
  double rotmat[3][3];
};

class GeneratedMeshBase : private GeneratedMeshBaseImpl {
protected:
  GeneratedMeshBase() : GeneratedMeshBaseImpl() { }
  using GeneratedMeshBaseImpl::rotmat;
};

class GeneratedMesh : private GeneratedMeshBase {
private:
  using GeneratedMeshBase::rotmat;
  /* ... */
};
```

**Comment by mhoemmen** [comment] 2018-05-25 18:32
@hubert-reinterpretcast Thanks!  I would like it know first whether this is a Spack configuration issue, though.  @nmhamster 's comment above suggests that XL should be able to compile this straightforward C++11 language feature.  If that doesn't work, it's hard to tell what other parts of Trilinos might not build.

**Comment by hubert-reinterpretcast** [comment] 2018-05-25 19:40
> I would like it know first whether this is a Spack configuration issue, though.

The issue can be triggered with a small reproducer when invoking the compiler correctly for C++11. Unless if the configuration intent is to not use C++11, this is a problem that needs to be solved separately from the configuration.

> @nmhamster 's comment above suggests that XL should be able to compile this straightforward C++11 language feature. If that doesn't work, it's hard to tell what other parts of Trilinos might not build.

The issue seems limited to initializing multi-dimensional arrays. Default member initializers work in many cases.

**Comment by mhoemmen** [comment] 2018-06-08 18:27
Any update on this issue?

**Comment by djfitzgerald** [comment] 2018-06-11 16:32
I'm with @mhoemmen... I've got this patch sitting in a folder on my desktop and am itching to make it go away.  @gsjaardema what should be the next steps on this?

**Comment by mhoemmen** [comment] 2018-06-11 16:57
@djfitzgerald I'm e-mailing folks now; thanks!

**Comment by gsjaardema** [comment] 2018-06-11 17:54
@djfitzgerald Can you show me the patch?

**Comment by gsjaardema** [comment] 2018-06-11 18:45
Since eliminating the current '{}' initialization will probably result in a warning (although we don't see warnings in current SEACAS or Sierra code), the 'double rotmat[3][3]'  could be changed to `std::array<std::array<double,3>,3>> rotmat` which will be default initialized to all zeros and then the existing call to `initialize` will turn it into the identify matrix.

**Comment by mhoemmen** [comment] 2018-06-11 20:37
FYI further discussion here: https://github.com/trilinos/Trilinos/pull/2924

**Comment by gsjaardema** [comment] 2018-06-11 23:24
This should be working now.  Fix in #2924 which has been merged to develop.

**Closed by gsjaardema** 2018-06-11 23:24 UTC
Labels: seacas

**Comment by mhoemmen** [comment] 2018-06-11 23:41
Thanks @gsjaardema !

**Comment by mhoemmen** [comment] 2018-06-11 23:42
@djfitzgerald The fix is in Trilinos' develop branch now.  It should make it into the master branch in a day or two.

**Comment by hubert-reinterpretcast** [comment] 2018-06-18 15:17
> Since eliminating the current '{}' initialization will probably result in a warning (although we don't see warnings in current SEACAS or Sierra code), the 'double rotmat[3][3]' could be changed to std::array<std::array<double,3>,3>> rotmat which will be default initialized to all zeros and then the existing call to initialize will turn it into the identify matrix.

The default initialization of the `std::array` member results in no initialization (https://godbolt.org/g/W3Xyqb), but it seems that there is no problem in this context.

**Comment by mhoemmen** [comment] 2018-06-18 16:10
@hubert-reinterpretcast Huh, you're right.  I even tried adding some nontrivial code to your example, just in case the compiler was optimizing it away.
