### ISSUE TITLE
ThreadPool:  Removal of ThreadPool from Trilinos

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#3445] opened 2018-09-14 17:38 UTC
@trilinos/stk @trilinos/framework @bartlettroscoe 

## Expectations

Soon we will remove ThreadPool from the Trilinos code base.
Users of ThreadPool should respond to this issue ASAP with questions/concerns.

Within Trilinos, STKClassic depends on ThreadPool; STKClassic is also targeted for removal #3444 .  
STKSearch claims a dependence on ThreadPool, but, in truth, does not need it; this claim of dependence will be removed.

## Motivation and Context

ThreadPool is no longer supported; it has been replaced by the far superior Kokkos toolkit.
Users of ThreadPool can migrate to Kokkos.

Removing unsupported, obsolete code is necessary to effectively maintain the Trilinos code base.

## Definition of Done

ThreadPool removed from stk_search dependencies
ThreadPool source code removed
STKClassic source code removed
STK/Trilinos integration and testing completed

## Possible Solution
Removal of ThreadPool is preferred.
If, for some reason, #3444 cannot be done, ThreadPool will move into the stk_classic directory to prevent further adoption by applications.

## Related Issues
* Is blocked by #3444

**Comment by bartlettroscoe** [comment] 2018-09-14 18:45
FYI: I am almost at the place where I can test this with SPARC.  Hopefully later today.

**Comment by alanw0** [comment] 2018-09-14 19:51
Thanks @kddevin , the stk team agrees with removing stk-classic and ThreadPool.

**Comment by bartlettroscoe** [comment] 2018-09-14 20:57
When I disabled ThreadPool in the current SPARC configuration of Trilinos, you get the error:

```
Disabling forward required SE packages and optional intra-package support that have a dependancy on disabled SE packages Trilinos_ENABLE_<TRIBITS_PACKAGE>=OFF ...

CMake Error at cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1098 (MESSAGE):
   ***
   *** ERROR: Setting Trilinos_ENABLE_STKSearch=OFF which was 'ON' because STKSearch has a required library dependence on disabled package ThreadPool!
   ***

Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1181 (TRIBITS_PRIVATE_PRINT_DISABLE)
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1204 (TRIBITS_PRIVATE_PRINT_DISABLE_REQUIRED_PACKAGE_ENABLE)
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1396 (TRIBITS_PRIVATE_DISABLE_REQUIRED_PACKAGE_ENABLES)
  cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:2320 (TRIBITS_DISABLE_FORWARD_REQUIRED_DEP_PACKAGES)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1677 (TRIBITS_ADJUST_PACKAGE_ENABLES)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:167 (TRIBITS_ADJUST_AND_PRINT_PACKAGE_DEPENDENCIES)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:90 (TRIBITS_PROJECT)


-- Configuring incomplete, errors occurred!
```

This is as of the version of Trilinos from b783a65:

```
b783a65 "Remove --mca orte_abort_on_non_zero_status 0 on white/ride (#3287, #3291) (#3292)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Aug 13 15:08:03 2018 -0400 (4 weeks ago)
```

The problem is:

```
$ grep ThreadPool packages/stk/stk_search/cmake/Dependencies.cmake 
SET(LIB_REQUIRED_DEP_PACKAGES ThreadPool STKUtil Kokkos)
```

It looks like even the most current version of Trilinos 'develop'  cc749ea9b3b475528f00ab83442b15a542a5d15 still lists ThreadPool as a required dependency of STKSearch.

In case the STK team just forgot to remove this dependency from the Depenencies.cmake file, I will try removing it and see what happens.

**Comment by kddevin** [comment] 2018-09-14 21:41
Yup, removing ThreadPool from the dependencies of stk_search is the first step of "Definition of Done."  @prwolfe and I are working out the details (who does what when, etc.) wrt STK/Trilinos integration.  
Thanks for giving it a try, @bartlettroscoe .  If there are any problems when you remove ThreadPool from the stk_search dependencies, please add them here.  That test will be important.

**Comment by alanw0** [comment] 2018-09-14 21:42
@bartlettroscoe If it is a real dependence (i.e. if stk_search code actually uses threadpool) then I can take care of removing the dependence

**Comment by bartlettroscoe** [comment] 2018-09-14 21:46
Okay, I created the commit off of the SPARC Trilinos 'master' branch:

```
26f29e2 "Remove STKSearch dependency on ThreadPool (trilinos/Trilinos#3445)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Sep 14 14:58:38 2018 -0600 (44 seconds ago)

diff --git a/packages/stk/stk_search/cmake/Dependencies.cmake b/packages/stk/stk_search/cmake/Dependencies.cmake
index f259025..a353b11 100644
--- a/packages/stk/stk_search/cmake/Dependencies.cmake
+++ b/packages/stk/stk_search/cmake/Dependencies.cmake
@@ -1,4 +1,4 @@
-SET(LIB_REQUIRED_DEP_PACKAGES ThreadPool STKUtil Kokkos)
+SET(LIB_REQUIRED_DEP_PACKAGES STKUtil Kokkos)
 SET(LIB_OPTIONAL_DEP_PACKAGES)
 SET(TEST_REQUIRED_DEP_PACKAGES STKUnit_test_utils Gtest)
 SET(TEST_OPTIONAL_DEP_PACKAGES)
```

and rebuilt and reinstalled Trilinos and rebuilt and ran the SPARC regression tests and the all passed.

So from the ATDM perspective, you can go ahead and remove ThreadPool.  You just need to remove it from the file `packages/stk/stk_search/cmake/Dependencies.cmake`.

**Comment by bartlettroscoe** [comment] 2018-09-14 21:52
FYI: I pushed this commit `26f29e2 "Remove STKSearch dependency on ThreadPool (trilinos/Trilinos#3445)"` shown above to the branch:

```
To gitlab.sandia.gov:rabartl/Trilinos.git
   4f02eb7..ebdd7d2  tril-212-sparc-trilinos-config-cee-lan-gcc -> tril-212-sparc-trilinos-config-cee-lan-gcc
```

If someone cherry-picks this commit off of that branch onto the Trilinos branch created directly off of the Trilinos 'develop' branch, then we can leave that commit in SPARC's Trilinos 'master' branch and it will not cause a merge conflict when Trilinos 'develop' is later merged to SPARC Trilinos 'master'.  (That is the beauty of git and cherry-picks.)  OTherwise, if someone creates a new commit from scratch for that change, then it likely will cause a merge conflict (and cause SPARC headaches).

**Comment by bartlettroscoe** [comment] 2018-09-14 22:26
> ok. so I need to fetch upstream and update my fork, then cherry-pick your commit to my develop branch, then submit a PR to the upstream develop branch from my fork's develop branch? I'm a git novice so the probably of doing this wrong is nonzero.

@alanw0, that sounds correct.  But if you create a PR early with your unfinished branch (can actually just be a branch with no new commits), then I can do that work for you.  See:

* https://github.com/trilinos/Trilinos/wiki/Topic-branch-workflow-using-checkin-test-script#early-pr-creation

Let me know.

**Comment by alanw0** [comment] 2018-09-14 23:10
@bartlettroscoe on second thought, this may not work since we have a one-way flow of stk changes from sierra to trilinos...

**Comment by bartlettroscoe** [comment] 2018-09-15 00:18
> @bartlettroscoe on second thought, this may not work since we have a one-way flow of stk changes from sierra to trilinos...

@alanw0 don't worry about it it.  The conflict will be trivial to resolve if it occurs.

**Comment by kddevin** [comment] 2018-10-12 20:18
@prwolfe @bartlettroscoe @alanw0 
I believe all the STK dependencies on ThreadPool were resolved by #3444 and #3463.
Thus, if there are no protests, I will begin removal of ThreadPool.  
Thanks all for your efforts.

**Comment by bartlettroscoe** [comment] 2018-10-12 22:02
Sparc and EMPIRE don't need threadpool so it can be removed from the ATDM standpoint

**Comment by prwolfe** [comment] 2018-10-15 13:03
Thanks @kddevin

**Closed** 2019-01-15 22:05 UTC
Labels: Framework, pkg: STK

**Comment by mhoemmen** [comment] 2019-01-16 00:18
@theguruat12 FYI
