### ISSUE TITLE
build issue due to rbgen in Anasazi 

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#1199] opened 2017-04-02 04:59 UTC
I am encountering an issue building Anasazi with RBGen on my machine: 

[ 84%] Built target rbgenepetra
[ 84%] Linking CXX executable RBGenDriver_EpetraMV.exe
../../../tpetra/core/src/libtpetra.so.12.11: undefined reference to `Teuchos::BLAS<int, std::complex<double> >::GEMM(Teuchos::ETransp, Teuchos::ETransp, int, int, int, std::complex<double>, std::complex<double> const*, int, std::complex<double> const*, int, std::complex<double>, std::complex<double>*, int) const'
../../../tpetra/core/src/libtpetra.so.12.11: undefined reference to `Teuchos::BLAS<int, std::complex<float> >::GEMM(Teuchos::ETransp, Teuchos::ETransp, int, int, int, std::complex<float>, std::complex<float> const*, int, std::complex<float> const*, int, std::complex<float>, std::complex<float>*, int) const'
collect2: error: ld returned 1 exit status
packages/anasazi/epetra/src-rbgen/CMakeFiles/RBGenDriver_EpetraMV.dir/build.make:684: recipe for target 'packages/anasazi/epetra/src-rbgen/RBGenDriver_EpetraMV.exe' failed
make[2]: *** [packages/anasazi/epetra/src-rbgen/RBGenDriver_EpetraMV.exe] Error 1
CMakeFiles/Makefile2:9217: recipe for target 'packages/anasazi/epetra/src-rbgen/CMakeFiles/RBGenDriver_EpetraMV.dir/all' failed

@trilinos/anasazi @hkthorn

**Comment by ibaned** [comment] 2017-04-02 20:33
This doesn't actually have to do with Anasazi, it just seems like that executable was the first to try to link against Tpetra, which is where the real bug is. This is a duplicate of #1200, and I've proposed a fix in #1201. I'll close this in favor of those other two.

**Closed by ibaned** 2017-04-02 20:33 UTC
