### ISSUE TITLE
Building Tpetra and Amesos2 tests with double off and float on

### ISSUE THREAD

**Issue by MicheldeMessieres** [trilinos/Trilinos#1142] opened 2017-03-16 13:34 UTC
@srajama1 This is for the double/float issue we discussed. We decided to have Amesos2 Umfpack provide a warning that type conversion would take place if built with float on and double off since Umfpack only supports double. So I had these settings:
Trilinos_ENABLE_FLOAT=ON
Tpetra_INST_DOUBLE=OFF
I found that Tpetra will not link with these settings if tests or examples are on - for example TpetraCore_BugTests.exe would not link. With only Amesos2 tests on, there are also link issues. I can build Tpetra and then Amesos2 under these settings with tests and examples off. So we may want to reconfigure things so Tpetra and Amesos2 would build tests/examples under these conditions.

**Comment by srajama1** [comment] 2017-03-16 16:53
I think the problem is turning double off, not turning float on.

The larger question is "Should Trilinos work with DOUBLE off ?"

@maherou @kddevin @rppawlo @mperego

**Comment by mperego** [comment] 2017-03-16 19:12
In principle think we should be able to compile Trilinos with double off. This would prevent having hard-coded doubles used instead of the requested type.
However I'm not sure how practical it is to do so, especially for the tests.

**Comment by mhoemmen** [comment] 2017-03-19 04:48
If people want to be able to shut off Scalar=double, then we could add that as a feature request.  Note that enabling Scalar=complex<double> currently requires Scalar=double to be enabled.

**Comment by mhoemmen** [comment] 2017-03-21 17:22
I'm marking this as an "enhancement," since I have never met a Trilinos customer who wanted to shut off Scalar=double in their builds.  That doesn't mean it shouldn't work, but it does help us set the priority for making such a thing work.

**Closed** 2021-03-24 12:17 UTC
Labels: CLOSED_DUE_TO_INACTIVITY, MARKED_FOR_CLOSURE, type: enhancement
