### ISSUE TITLE
ATDM Build Scripts:  Error in get_known_system_info.sh

### ISSUE THREAD

**Issue by jmgate** [trilinos/Trilinos#6276] opened 2019-11-14 16:05 UTC
## Bug Report
@bartlettroscoe, @fryeguy52 

### Description
`get_known_system_info.sh` was modified in c2c3e244ea95d3f4396b3b3220f45e97216b1890 and 5188171ea2d68f6f4f9b9fec92280a6fa6c9a16d.  I'm not sure which of those is the culprit, but now when I use `load-env.sh`, I get the following error:
```
/path/to/Trilinos/cmake/std/atdm/utils/get_known_system_info.sh: line 118: \
systemNameTypeMatchedListHostNames[${hostnameMatchSystemName}]: bad array subscript
```

For full details of the run that led to this failure, [see this log](https://jenkins-srn.sandia.gov/user/jmgate/my-views/view/jmgate/job/EMPIRE-jmgate-build-test-Trilinos-cortado-clang-opt/ws/log/Build_Trilinos.html).

### Steps to Reproduce
See [this Jenkins job](https://jenkins-srn.sandia.gov/user/jmgate/my-views/view/jmgate/job/EMPIRE-jmgate-build-test-Trilinos-cortado-clang-opt/).  I've also run into the same problem trying to configure on my local RHEL7 machine with gnu.

**Comment by bartlettroscoe** [comment] 2019-11-14 16:32
@jmgate, what version of Trilinos is this?  What exact command did you run to generate this error?

**Comment by jmgate** [comment] 2019-11-14 16:35
2fc3a14830572701739f9c44cd246d1e1c426dee

**Comment by jmgate** [comment] 2019-11-14 16:36
`/path/to/Trilinos/cmake/std/atdm/load-env.sh EMPIRE-jmgate-build-test-Trilinos-cortado-clang-opt`

**Comment by jmgate** [comment] 2019-11-14 17:28
I'm seeing this problem on cortado, my local RHEL7 machine, and also on cee-build012.  Scot Swan mentioned there were some changes that went in for HPCs recently, but perhaps they inadvertently hosed RHEL machines.

**Comment by jmgate** [comment] 2019-11-14 17:44
<img width="1664" alt="Screen Shot 2019-11-14 at 10 42 18 AM" src="https://user-images.githubusercontent.com/20327215/68881995-805e1a80-06cb-11ea-9d32-5f9a5227b44d.png">

I'm getting a return code of 127 when sourcing `load-env.sh` via a Python script.  When I run the command manually in a terminal, no such problem.

This problem did not exist when last I tried this on Tuesday.

**Comment by jmgate** [comment] 2019-11-14 17:54
Rewinding Trilinos to 9afcb785cb0e907496e1963179b3785cf3265288 fixes the problem.

**Comment by jmgate** [comment] 2019-11-14 17:59
d475fc6684cb72c59eeddb36bee12626ea16c50e is the problematic merge (#6252).

**Comment by bartlettroscoe** [comment] 2019-11-14 20:28
This is strange because all of the ATDM Trilinos builds are all working as shown at:

* https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2019-11-14&filtercount=1&showfilters=1&field1=buildname&compare1=65&value1=Trilinos-atdm- 

@jmgate, can you reproduce manually yourself?

**Comment by bartlettroscoe** [comment] 2019-11-14 20:50
@jmgate, I will try to reproduce this on various machines and see what I see.

**Comment by bartlettroscoe** [comment] 2019-11-14 20:53
I found the problem.  I will submit a PR shortly ...

**Comment by jmgate** [comment] 2019-11-14 20:53
Does it have to do with quoting the argument to the array?  That's just what I was about to try messing with.

**Comment by jmgate** [comment] 2019-11-14 20:54
This was a very peculiar bug in terms of how it manifested.  I'm guessing there was some funny business I wasn't able to see inside the Python subprocess call, but I haven't dogged that down yet.

**Comment by jmgate** [comment] 2019-11-14 21:35
Here's the latest thought:  When running something via `popen` with `shell=True`, it'll default to `/bin/sh`, which I don't think supports array indexing.  I could look into what it would take to make `popen` use `bash` instead of `sh`.

**Comment by jmgate** [comment] 2019-11-14 21:50
It looks like I have a fix for this on the Python side of things, but I'd be curious to see what you found on your end.

**Comment by bartlettroscoe** [comment] 2019-11-14 22:40
@jmgate, the fix should be in PR #6280.  It was just a sloppy bug on my part.  I was in a rush to fix the problem that Scot Swan was happening and I pushed a sloppy commit in PR #6257.

Hopefully this should be the last structural fix for that file.

(These bash scripts really need to be put under strong automated testing.  Hence #5939 .  I learn this the hard way over and over again.)

**Comment by bartlettroscoe** [comment] 2019-11-15 02:38
@jmgate, PR #6280 just merged.  Hopefully this will fix the issue.  You should not have to change the Python code.  In fact, it was good because it caught this issue where the Jenkins bash driver scripts did not.

Sorry I let this bug slip through.

Putting in review.

**Comment by bartlettroscoe** [comment] 2019-11-15 23:01
@jmgate, is this fixed on the EMPIRE side?  How could I see this on my own (as I don't get the EMPIRE/Trilinos Jenkins Pipeline emails).

**Comment by bartlettroscoe** [comment] 2019-11-16 19:25
FYI: I confirmed that the ATDM Trilinos testing process saw this error on testing day 2019-11-14, for example, as shown in:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/250/consoleFull

which showed:

```
03:33:08 /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/Trilinos/cmake/std/atdm/utils/get_known_system_info.sh: line 118: systemNameTypeMatchedListHostNames[${hostnameMatchSystemName}]: bad array subscript
03:33:08 Hostname 'ascicgpu14' matches known ATDM host 'sems-rhel7' and system 'sems-rhel7'
```

but that same build on 2019-10-16 (today) as shown at:

* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/252/consoleFull

showed no error:

```
03:33:28 
03:33:28 Hostname 'ascicgpu14' matches known ATDM host 'sems-rhel7' and system 'sems-rhel7'
03:33:28 
```

Closing this as complete.

**Closed by bartlettroscoe** 2019-11-16 19:25 UTC
Labels: ATDM Config, ATDM DevOps, client: EMPIRE, type: bug

**Comment by jmgate** [comment] 2019-11-20 13:45
I just tested via our Python script and all is well on our end.  Thanks @bartlettroscoe.
