### ISSUE TITLE
SEACASIoss CGNS tests failing in ATDM configuration in cee-rhel6-intel-opt-serial builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3631] opened 2018-10-15 20:21 UTC
CC: @trilinos/seacas , @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe 
 
## Next Action Status

The intel install of the CGNS tools `cgnslist` executable loaded with the module `sparc-dev/intel` was fixed on 10/19/2018.  Next: Watch for passing tests on 10/20/2018 ...

## Description
As shown in [this query](https://testing.sandia.gov/cdash-dev-view/queryTests.php?project=Trilinos&date=2018-10-15&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-cee-rhel6-&field2=status&compare2=62&value2=passed) the tests:
* SEACASIoss_structured_cgns_roundtrip_zgc
* SEACASIoss_structured_cgns_roundtrip_single_fpp_single_fields
* SEACASIoss_structured_cgns_roundtrip_fpp2
* SEACASIoss_structured_cgns_roundtrip_fpp
* SEACASIoss_structured_cgns_roundtrip_fields
* SEACASIoss_structured_cgns_roundtrip_bump
* SEACASIoss_structured_cgns_roundtrip
* SEACASIoss_generated64_to_unstructured_cgns
* SEACASIoss_generated32_to_unstructured_cgns
* SEACASIoss_exodus64_to_unstructured_cgns
* SEACASIoss_exodus32_to_unstructured_cgns

are failing in the builds:
* Trilinos-atdm-cee-rhel6-intel-opt-serial

many of these are showing something like:
```
/projects/sparc/tpls/cee-rhel6-new/cgns-develop/cee-cpu_intel-17.0.1_intelmpi-5.1.2/bin/cgnslist: symbol lookup error: /sierra/sntools/SDK/compilers/intel/composer_xe_2017.1.132/compilers_and_libraries/linux/lib/intel64/libifport.so.5: undefined symbol: __FFfrand
```
## Steps to Reproduce

One should be able to reproduce this failure on any CEE LAN RHEL6 SRN as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the systemCEE LAN RHEL6 SRN are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#cee-rhel6-environment
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cee-rhel6-intel-opt-serial

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_SEACAS=ON \
  $TRILINOS_DIR

$ make NP=16

$ ctest -j16
```

**Comment by bartlettroscoe** [comment] 2018-10-15 23:09
@gsjaardema as per our email conversation archived [here](https://software-sandbox.sandia.gov/jira/browse/TRIL-212?focusedCommentId=23271&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23271), these are tests that have not ever gotten run in Trilinos builds and your desire was to enable all of these tests and then you would deal with the issues that came up.  So far, these are the only new SEACAS resulting from this decision.  Hopefully cleaning this up will not be too bad.

**Comment by bartlettroscoe** [comment] 2018-10-18 21:47
FYI: In an offline conversation over email with @gsjaardema, @micahahoward, and @sebrowne, it seems the problem is that the `cgnslist` tool pointed to by the `sparc-dev/intel` module that is used in the ATDM Trilinos 'cee-rhel6' env crashes when you try to run it.   When you try to run it, it produces the error:

```
undefined symbol: __FFfrand
```

And that is actually the error you see as shown above.

But when I ran `cgnslist` with the `sparc-dev/clang` module, it seemed to run okay.  (So that would explain why these tests don't fail with the 'clang' or 'gnu' builds.)

So it looks like this is a system env problem and not a code problem.  I will update the "Next Action Status" field for this.

**Comment by bartlettroscoe** [comment] 2018-10-19 17:12
@sebrowne fixed the intel install of the CGNS tools and now `cgnslist` appears to work:

```
$ /projects/sparc/tpls/cee-rhel6-new/cgns-develop/cee-cpu_intel-17.0.1_intelmpi-5.1.2/bin/cgnslist
usage  : cgnslist [options] CGNSfile [node]
options:
   -b      = brief - file summary only
   -i<cnt> = set indent level (default 2)
   -f      = follow links
   -l      = print node label
   -t      = print node data type
   -d      = print node dimensions
   -s      = print node size in bytes
   -a      = print all -ltds
```

So we should expect theses tests to clear up tomorrow.

Putting this issue in review and will close once we get confirmation on CDash that the tests are fixed.

**Comment by bartlettroscoe** [comment] 2018-10-20 12:00
As shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4073411), the SEACS tests for the build `Trilinos-atdm-cee-rhel6-intel-opt-serial` have cleaned up today (see the `-11` subscript and `+11`  superscript by the number of failing and passing SEACAS tests).    You can also see the newly passing tests [here](https://testing.sandia.gov/cdash-dev-view/viewTest.php?onlydelta&buildid=4073426).

Closing as complete.  Thanks all!

**Comment by bartlettroscoe** [comment] 2018-10-20 12:00
Closing for real this time

**Closed by bartlettroscoe** 2018-10-20 12:00 UTC
Labels: ATDM, bug, seacas
