### ISSUE TITLE
PanzerAdaptersSTK_response_residual_MPI_2 Failing on ATDM Chama build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3064] opened 2018-07-05 13:47 UTC
CC: @trilinos/panzer, @mperego (Trilinos Discretizations Product Area Lead)

## Next Action Status

PR #3082 which increases tolerance to `10*eps` was merged 7/9/2018.  Next: Watch for any new failures then close by 7/17/2018 ...

## Description

The test `PanzerAdaptersSTK_response_residual_MPI_2` has been failing in ATDM builds on `chama`.  It has been failing for the last three days and intermittently before that.

[query showing test's results from 6-15 to 7-4](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-01&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-chama&field2=groupname&compare2=61&value2=ATDM&field3=testname&compare3=61&value3=PanzerAdaptersSTK_response_residual_MPI_2&field4=buildstarttime&compare4=84&value4=2018-07-04&field5=buildstarttime&compare5=83&value5=2018-06-15)

both 
`Trilinos-atdm-chama-intel-debug-openmp`
and
`Trilinos-atdm-chama-intel-opt-openmp`
are being affected by this 

## Steps to Reproduce
On Chama clone Trilinos and then run the following which will take care of the environment as well
```
export JOB_NAME=Trilinos-atdm-chama-intel-debug-openmp
export TRILINOS_DIR=<Where ever you cloned trilinos>
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh $JOB_NAME

cmake \                                                                                                            
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \ 
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Thyra=ON \                                       
  $TRILINOS_DIR

make -j16                                                                                                          
ctest -j16 
```

**Comment by bartlettroscoe** [comment] 2018-07-07 02:38
As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-06&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildstarttime&compare2=83&value2=2018-06-27&field3=testname&compare3=61&value3=PanzerAdaptersSTK_response_residual_MPI_2&field4=buildname&compare4=61&value4=Trilinos-atdm-chama-intel-debug-openmp) and [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-06&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildstarttime&compare2=83&value2=2018-06-27&field3=testname&compare3=61&value3=PanzerAdaptersSTK_response_residual_MPI_2&field4=buildname&compare4=61&value4=Trilinos-atdm-chama-intel-opt-openmp) the test `PanzerAdaptersSTK_response_residual_MPI_2` seems to be failing randomly in the build `Trilinos-atdm-chama-intel-debug-openmp` and every day since 6/28/2018 in the build `Trilinos-atdm-chama-intel-opt-openmp`. 

When it fails, for example [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=49922220&build=3692206) it shows errors like:

```
 Random vector tests = 2
  
  Testing relative error between vectors v2.col[0] and v3.col[0]:
   ||v2.col[0]|| = 1.80465
   ||v3.col[0]|| = 1.80465
   Check: rel_err(v2.col[0],v3.col[0]) = 1.10071e-16 <= linear_properties_error_tol() = 1e-16 : FAILED
```

When it passes, for example [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=49677211&build=3677456), it shows:

```
 Random vector tests = 2
  
  Testing relative error between vectors v2.col[0] and v3.col[0]:
   ||v2.col[0]|| = 1.80465
   ||v3.col[0]|| = 1.80465
   Check: rel_err(v2.col[0],v3.col[0]) = 0 <= linear_properties_error_tol() = 1e-16 : passed
``` 

It seems there is some non-determinism in these numerical tests, but I guess that is to be expected with some.

The problem is that the tolerance of 1e-16 is just too tight.  Can we increase this tolerance to 1e-15 and see if that fixes this?

**Comment by bartlettroscoe** [comment] 2018-07-10 15:08
With the merge of PR #3082 yesterday to loosen the error tolerance just a little, hopefully this issue will be resolved.  We just need to give it a few days to ensure that none of the test runs fail (because the failures were semi-random).

I am putting this in review until 7/17/2018 and then will close if there are no new failures.

**Comment by bartlettroscoe** [comment] 2018-07-13 23:15
FYI: The 'chama' build has been down for the last few days due to an Intel license server being taken offline and 'chama' being put in system time for a few days.  But the build is back submitting results to CDash with this test passing today as shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-13&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-chama-&field2=testname&compare2=61&value2=PanzerAdaptersSTK_response_residual_MPI_2).  But since this was a semi-randomly failing test we will let this run a few days and then close the issue as fixed.

**Comment by bartlettroscoe** [comment] 2018-07-24 00:17
As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2018-07-23&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=testname&compare2=61&value2=PanzerAdaptersSTK_response_residual_MPI_2&field3=site&compare3=61&value3=chama&field4=groupname&compare4=61&value4=ATDM&field5=buildstarttime&compare5=83&value5=2018-07-01), the test `PanzerAdaptersSTK_response_residual_MPI_2` has been passing every day in the 'chama' builds `Trilinos-atdm-chama-intel-debug-openmp` and `Trilinos-atdm-chama-intel-opt-openmp` every day since 7/11/2018.  Before that, it failed almost every day.  Therefore, we can conclude that this issue has been resolved.  Closing as fixed.

**Closed by bartlettroscoe** 2018-07-24 00:17 UTC
Labels: ATDM, Panzer, bug, in review
