### ISSUE TITLE
Ifpack2: BlockTriDiContainer calls unknown method

### ISSUE THREAD

**Issue by lucbv** [trilinos/Trilinos#2871] opened 2018-06-04 13:35 UTC
@trilinos/ifpack2 
@kyungjoo-kim @ambrad 

## Expectations
Ifpack2 should build...

## Current Behavior
If does not build, gcc returns the following error:

```
In file included from /home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:59:0:
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp: In instantiation of ‘static tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::Int tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::test_BR_BTDC(const Teuchos::RCP<const Teuchos::Comm<int> >&, const StructuredBlock&, const StructuredBlockPart&, tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::Int, tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::Int, bool, bool, bool, bool, bool, const string&) [with Scalar = std::complex<double>; LO = int; GO = int; tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::Int = int; tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::StructuredBlock = tif_utest::BlockCrsMatrixMaker<std::complex<double>, int, int>::StructuredBlock; tif_utest::BlockTriDiContainerTester<Scalar, LO, GO>::StructuredBlockPart = tif_utest::BlockCrsMatrixMaker<std::complex<double>, int, int>::StructuredBlockPart; std::string = std::basic_string<char>]’:
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:292:51:   required from ‘LO run_teuchos_tests(const Input&, Teuchos::FancyOStream&, bool&) [with Scalar = std::complex<double>; LO = int; GO = int; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:313:53:   required from ‘void Ifpack2BlockTriDi_Unit_UnitTest<Scalar, LO, GO>::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const [with Scalar = std::complex<double>; LO = int; GO = int; Teuchos::FancyOStream = Teuchos::basic_FancyOStream<char>]’
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp:321:1:   required from here
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp:238:9: error: ‘class Ifpack2::BlockTriDiContainer<Tpetra::RowMatrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag>’ has no member named ‘createDefaultComputeParameters’
         T_bare->compute(T_bare->createDefaultComputeParameters());
         ^
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp:293:49: error: ‘class Ifpack2::BlockTriDiContainer<Tpetra::RowMatrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag>’ has no member named ‘getNorms0’
               const auto n0 = T_bare->getNorms0();
                                                 ^
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp:294:53: error: ‘class Ifpack2::BlockTriDiContainer<Tpetra::RowMatrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag>’ has no member named ‘getNormsFinal’
               const auto nf = T_bare->getNormsFinal();
                                                     ^
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp:311:63: error: ‘class Ifpack2::BlockTriDiContainer<Tpetra::RowMatrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag>’ has no member named ‘createDefaultApplyParameters’
             auto input = T_bare->createDefaultApplyParameters();
                                                               ^
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp:318:19: error: ‘class Ifpack2::BlockTriDiContainer<Tpetra::RowMatrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag>’ has no member named ‘createDefaultApplyParameters’
             input = T_bare->createDefaultApplyParameters();
                   ^
/home/lberge/Research/Trilinos_lucbv/packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp:325:21: error: ‘class Ifpack2::BlockTriDiContainer<Tpetra::RowMatrix<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag>’ has no member named ‘createDefaultApplyParameters’
               input = T_bare->createDefaultApplyParameters();
```

## Motivation and Context
This is blocking development and it also prevent nightly tests to run properly since Ifpack2 gets disabled by CMake.

## Definition of Done
Ifpack2 can be build again

## Possible Solution
It looks from the template: `Ifpack2::BlockTriDiContainerDetails::ImplNotAvailTag` that some implementation might be missing in which case BlockTriDiContatiner might not be ready to be pushed in develop?
Or the missing implementation needs to be added or guarded to avoid compilation issues?

## Steps to Reproduce
Get a fresh version of trilinos and enable Ifpack2, I tried with and without `openmp`, both are failing.

## Your Environment
- Trilinos SHA1: 0d2d3c9
- source Trilinos/cmake/load_sems_dev_env.sh
- Trilinos_ENABLE_Ifpack2

**Comment by william76** [comment] 2018-06-04 14:50
The failures in the nightly `Clean` track since Friday might also be related to this as well...

CDash: https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3614523  (ifpack2)
CDash: https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3614523 (errors in Clean)


`Standard Error | In file included from workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp:57:0,                  from workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/BUILD/packages/ifpack2/src/Ifpack2_BlockTriDiContainer.hpp:1,                  from workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/ifpack2/src/Ifpack2_ContainerFactory_def.hpp:51,                  from workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/BUILD/packages/ifpack2/src/Ifpack2_ContainerFactory_Serial.cpp:50: trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp: In constructor ‘Ifpack2::BlockTriDiContainerDetails::AsyncableImport<MatrixType>::AsyncableImport(const Teuchos::RCP<const typename Ifpack2::BlockTriDiContainerDetails::ImplType<MatrixType>::tpetra_map_type>&, const Teuchos::RCP<const typename Ifpack2::BlockTriDiContainerDetails::ImplType<MatrixType>::tpetra_map_type>&, Ifpack2::BlockTriDiContainerDetails::AsyncableImport<MatrixType>::local_ordinal_type, Ifpack2::BlockTriDiContainerDetails::AsyncableImport<MatrixType>::local_ordinal_type_1d_view)’: workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:590:72: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]          const auto mpi_comm = Teuchos::rcp_dynamic_cast<const Teuchos::MpiComm<int> >(tgt_map->getComm());                                                                         ^ workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:590:40: error: parse error in template argument list          const auto mpi_comm = Teuchos::rcp_dynamic_cast<const Teuchos::MpiComm<int> >(tgt_map->getComm());`

This SHA1 might also be one to check into for the commit: 24dde0df65fc2523fe419ddcc0aeaaf3c3476a32 

@trilinos/framework

**Comment by mhoemmen** [comment] 2018-06-04 15:18
@micahahoward

**Comment by lucbv** [comment] 2018-06-04 15:32
@trilinos/framework, I am also wondering why this was not caught by the auto-tester?
Do we need to enable something more in the configure script of the auto-tester?

**Comment by kyungjoo-kim** [comment] 2018-06-04 15:33
@lucbv It is because that the BlockTriDiContainer does not instanciate complex (double only). I have not heard that we have a use case with complex variables. Is this just for a linking purpose.

**Comment by mhoemmen** [comment] 2018-06-04 15:38
@kyungjoo-kim Sierra builds Trilinos with complex enabled, so it does at least need to build.  If it only makes sense to build the class for real-valued Scalar types, we can work around by introducing a parent class.  See e.g., `Belos::RealSolverManager`.

**Comment by lucbv** [comment] 2018-06-04 15:48
@kyungjoo-kim, I just want the code to build with `Trilinos_ENABLE_COMPLED_DOUBLE=ON`.
I can turn it off momentarily but a good chunk of my work in `MueLu` involves using coordinates that are templated on `double` instead of `Scalar` and I need to turn on complex to make sure that I am not breaking the build with complex...

**Comment by mhoemmen** [comment] 2018-06-04 16:05
@lucbv @kyungjoo-kim The typical model for Ifpack2 classes that really only work with real Scalar but need to build with complex Scalar, is `Ifpack2::Chebyshev`.  We only ever test it with real Scalar types (by e.g., using the `IFPACK2_INSTANTIATE_SLG_REAL` macro to instantiate templated unit tests), but we do build it (e.g., for ETI and the solver factory) with complex Scalar types.

**Comment by kyungjoo-kim** [comment] 2018-06-04 18:31
@william76 
the error message in cdash is a bit weird. 

```
Ifpack2_BlockTriDiContainer_impl.hpp:590:72: 
error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive] const auto 
mpi_comm = Teuchos::rcp_dynamic_cast<const Teuchos::MpiComm<int> >(tgt_map->getComm()); 
error: parse error in template argument list const auto mpi_comm = 
Teuchos::rcp_dynamic_cast<const Teuchos::MpiComm<int> >(tgt_map->getComm());
```
Parsing the rcp_dynamic_cast causes the error and I cannot reproduce this problem.

**Comment by mhoemmen** [comment] 2018-06-04 18:35
@kyungjoo-kim It looks like this is code that depends on MPI, but does not test the appropriate macro.  Other code in this file does test `HAVE_MPI` (which is not really the right macro but might work).

 If you know it's a `Teuchos::MpiComm<int>`, why use auto?

**Comment by mhoemmen** [comment] 2018-06-04 18:35
@kyungjoo-kim The only way to reproduce this would be to build with MPI disabled, I think.

**Comment by kyungjoo-kim** [comment] 2018-06-04 18:40
@mhoemmen You are right. It is my mistake but I think that PR test can prevent these problems and should automates the tests (with mpi and without mpi).

**Comment by mhoemmen** [comment] 2018-06-04 20:52
Should be fixed now in develop with PR merge just now.

**Comment by kyungjoo-kim** [comment] 2018-06-04 21:03
@mhoemmen You are too early to merge the code. It needs to include HAVE_MPI fix and is_convertible overloading between std::is_convertible<Kokkos::complex<T1> , T2>::value = std::is_convertible<T1,T2>.

**Comment by mhoemmen** [comment] 2018-06-04 21:47
@kyungjoo-kim Oops, sorry

**Comment by kyungjoo-kim** [comment] 2018-06-04 21:59
@lucbv 

I use is_convertible to check whether the input value is convertible to the data type in kokkos kernels SIMD. I am going to fix this in kokkos kernels but you should override the kokkoskernels src directory to compile the code with complex. In Trilinos, it will be merged later.

**Comment by csiefer2** [comment] 2018-06-04 22:33
@kyungjoo-kim That doesn't work for Trilinos.  Feel free to revert your commits to Ifpack2 and save them for the next Kokkos promotion.

**Comment by csiefer2** [comment] 2018-06-04 22:34
If Kokkos Kernels maintained a branch of Trilinos with changes needed to work with VOTD Kokkos kernels we wouldn't have problems like this :)

**Comment by ndellingwood** [comment] 2018-06-04 22:35
@kyungjoo-kim we can also issue a patch/hot-fix to Trilinos of the same PR you put in to kokkos-kernels. The Trilinos patch would get clobbered by the matching kokkos-kernels changes during the next promotion.

**Comment by csiefer2** [comment] 2018-06-04 22:42
That works too.

**Comment by kyungjoo-kim** [comment] 2018-06-05 22:06
The PR is merged and Ifpack2_BlockTriDiContainer is also tested with complex.

**Closed by kyungjoo-kim** 2018-06-05 22:06 UTC
Labels: Ifpack2, bug, build
