### ISSUE TITLE
TrilinosCouplings build failure

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#2786] opened 2018-05-21 14:01 UTC
@trilinos/muelu
@trilinos/framework @maherou ~~There is no GitHub team for TrilinosCouplings~~
Edit: there is now, not sure if I just missed it

## Expectations

TrilinosCouplings should compile without error

## Current Behavior

```
packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp(152): catastrophic error: cannot open source file "MueLu_AztecEpetraOperator.hpp"
  #include <MueLu_AztecEpetraOperator.hpp>
```

## Motivation and Context

This is preventing snapshotting a new Kokkos version

**Comment by cgcgcg** [comment] 2018-05-21 14:30
Do we have a build that is currently affected by this, so that I can try and reproduce the error?

**Comment by cgcgcg** [comment] 2018-05-21 16:31
You might want to try adding a `#if defined(HAVE_MUELU_EPETRA)` for the include at https://github.com/trilinos/Trilinos/blob/75b13d9d1e975ab7c25ca175e07cde1d47536bd3/packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp#L152

**Comment by jhux2** [comment] 2018-05-21 16:55
@trilinos/trilinoscouplings

**Comment by lucbv** [comment] 2018-05-21 16:59
@ibaned can you let us know how you configured Trilinos for this build?
If by any chance you kept the output of the configuration that would be ideal information for us.

**Comment by jhux2** [comment] 2018-05-21 17:16
> Edit: there is now, not sure if I just missed it

@ibaned Nope, I just created it :).

**Comment by ndellingwood** [comment] 2018-05-21 20:42
Checked with @lucbv and @cgcgcg, @lucbv pointed out guards may actually be better placed in the `CMakeLists.txt` file rather than within the code since the following packages are expected in order to compile:

```
IF(${PACKAGE_NAME}_ENABLE_Epetra AND ${PACKAGE_NAME}_ENABLE_EpetraExt AND
   ${PACKAGE_NAME}_ENABLE_Amesos AND ${PACKAGE_NAME}_ENABLE_AztecOO AND
   ${PACKAGE_NAME}_ENABLE_Intrepid AND ${PACKAGE_NAME}_ENABLE_ML AND
   ${PACKAGE_NAME}_ENABLE_Pamgen)
```

The reason this slips through is because all of these packages are enabled as well as MueLu, but we are testing with `MueLu_ENABLE_Epetra=OFF` following from issue #2319 discussion.

**Comment by ndellingwood** [comment] 2018-05-21 20:50
@cgcgcg it looks like one option could be to move the file include to after line 226 - 
`#if defined(HAVE_MUELU_EPETRA) and defined(HAVE_TRILINOSCOUPLINGS_MUELU)`

This way it is guarded in the proper place without changing the CMakeLists.txt file. Would you like me to give this a try?

**Comment by ndellingwood** [comment] 2018-05-21 22:15
Pushed the MueLu fix for the failing Kokkos tests and pushed a fix for Tpetra where the `KOKKOS_ENABLE_PTHREAD` macro was used instead of the `KOKKOS_ENABLE_THREADS` macro, resulting in many tests not running during the Shepard threads test.

**Comment by mhoemmen** [comment] 2018-05-22 05:14
@ndellingwood Thanks! :-D

**Comment by lucbv** [comment] 2018-05-22 14:49
@cgcgcg and I looked at it and decided to keep the CMakeFile.txt as is, this will allow potential test of the maxwell example using `Epetra`, `Aztec` and `ML` without `MueLu`.
I simply add the guard in `example_Maxwell.cpp`.

**Comment by lucbv** [comment] 2018-05-22 19:09
@ibaned, @ndellingwood let me know if this works for you now and we should be able to close this issue.
Thanks all!

**Comment by ndellingwood** [comment] 2018-06-21 23:29
Closing the issue since this has been resolved for some time, thanks @lucbv and @cgcgcg  :)

**Closed by ndellingwood** 2018-06-21 23:29 UTC
Labels: MueLu, Trilinos Couplings, bug
