### ISSUE TITLE
MiniTensor:  Test errors with the new CUDA 11 build

### ISSUE THREAD

**Issue by srbdev** [trilinos/Trilinos#11298] opened 2022-11-21 18:06 UTC
### Description
There are test errors for the MiniTensor package for the `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_all` build. It is currently ran on the following fork https://github.com/e10harvey/Trilinos and branch `sprint17_cpp17`.

See the [CDash link](https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=616428&filtercount=3&showfilters=1&filtercombine=and&field1=testname&compare1=63&value1=MiniTensor&field2=status&compare2=61&value2=failed&field3=details&compare3=64&value3=timeout) for additional details.

**Comment by lxmota** [comment] 2022-11-29 22:09
I'm not sure if this is related to https://github.com/trilinos/Trilinos/issues/11300

What is the https://github.com/e10harvey/Trilinos fork and how is it different to the Trilinos develop branch?

**Comment by srbdev** [comment] 2022-11-30 15:09
> What is the https://github.com/e10harvey/Trilinos fork and how is it different to the Trilinos develop branch?

It contains the current work in progress from the Framework team for the C++17 update. If all went well, it will be part of `develop` by the end of today.

**Comment by cwpearson** [comment] 2022-12-01 16:12
I'm entirely unfamiliar with this code, so take this with a grain of salt:

Here, for example, fill is called with a `Kokkos::View`, (which may live on the device)
https://github.com/trilinos/Trilinos/blob/901236a9aa18ae9ec066fce5fc80d928b5ca0b5b/packages/minitensor/test/test_01.cc#L193

And then in here that view is accessed on the host
https://github.com/trilinos/Trilinos/blob/901236a9aa18ae9ec066fce5fc80d928b5ca0b5b/packages/minitensor/src/MiniTensor_TensorBase.i.h#L496

That doesn't explain to me why it didn't show up until CUDA 11.

**Comment by sebrowne** [comment] 2022-12-01 20:26
@cwpearson I believe it's because that test was disabled previously in the CUDA10 builds.  When we advanced to CUDA11, we removed all of the disables so all packages are now built/tested with CUDA.

**Comment by lxmota** [comment] 2022-12-01 20:31
I'm the author of this code, but I'm not familiar at all with the intricacies of Kokkos. Someone else helped to introduce Kokkos to this library. I'm open to suggestions about how to fix this. I'm willing to do it, but I do need help about what needs to be done.

**Comment by jhux2** [comment] 2022-12-01 23:49
@lxmota Do you have access to an ascicgpu machine on the CEE lan?  If so, there are instructions on how to reproduce the errors [here](https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors).

**Comment by sebrowne** [comment] 2022-12-02 00:02
Is fill() supposed to support running on the GPU?  It doesn't look like it from my perspective (considering that the only parallel_for I can find in MiniTensor is in another test, not the code itself.  If not, I think this can be fixed by changing the Kokkos::DefaultExecutionSpace to Kokkos::DefaultHostExecutionSpace in test_01.cc (but I have very practical idea what I'm talking about, so I may not be the best person to provide input).

**Comment by lxmota** [comment] 2022-12-02 00:03
@jhux2 Thanks for the link. Yes, I do have access to an ascicgpu machine. I think the issue is more about what to do to avoid accessing device memory from the host as @cwpearson mentions above. I'm assuming that the fill function will need to be modified to do different things depending on whether it's being called by the host or device. I suppose that there are many other functions that will have the same problems. I don't have the resources or the knowledge to make major Kokkos modifications to the library.

**Comment by lxmota** [comment] 2022-12-02 00:05
> Is `fill()` supposed to support running on the GPU? It doesn't look like it from my perspective (considering that the only parallel_for I can find in MiniTensor is in another test, not the code itself. If not, I think this can be fixed by changing the `Kokkos::DefaultExecutionSpace` to `Kokkos::DefaultHostExecutionSpace` in test_01.cc (but I have very little practical idea what I'm talking about, so I may not be the best person to provide input).

No, fill is not supported on the GPU, or any of the other functions, for that matter. If what you suggest is the change that needs to be done, I'll do it.

**Comment by sebrowne** [comment] 2022-12-02 00:10
Well in that case, it definitely seems like passing in a View that is in device memory is unsupported, so that change would be an acceptable fix for the test (I think).  If somebody tries to pass a device-residing View into any of the methods, I assume that the compiler will tell them effectively the same thing that it does here with the test, which is probably satisfactory?

**Comment by sebrowne** [comment] 2022-12-02 00:29
I take back what I said previously: It will throw an error at runtime.  If that's satisfactory, I think that the specification of the exe space as host is all that is needed (the test passed for me on one of the ascicgpu machines with that change just now).

**Comment by lxmota** [comment] 2022-12-02 00:31
> I take back what I said previously: It will throw an error at runtime. If that's satisfactory, I think that the specification of the exe space as host is all that is needed (the test passed for me on one of the ascicgpu machines with that change just now).

Yes, an error at runtime is ok since this code wasn't designed to run on the GPU. I'll go ahead and make the changes. Thanks!

**Closed** 2022-12-15 23:53 UTC
Labels: type: bug, pkg: minitensor

**Comment by lxmota** [comment] 2022-12-15 23:56
Thank you for fixing this.

From: Samuel Browne ***@***.***>
Reply-To: trilinos/Trilinos ***@***.***>
Date: Thursday, December 15, 2022 at 15:53
To: trilinos/Trilinos ***@***.***>
Cc: "Mota, Alejandro" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [trilinos/Trilinos] MiniTensor: Test errors with the new CUDA 11 build (Issue #11298)


Closed #11298<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftrilinos%2FTrilinos%2Fissues%2F11298&data=05%7C01%7Camota%40sandia.gov%7Ce476f1c7db4d4cee957a08dadef7906f%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C638067452125181430%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yfDr%2BnxXzJoqkrIItg0VNNyYoz8ELEyImh0OmIT7GIg%3D&reserved=0> as completed.
