### ISSUE TITLE
Installed Ifpack2 header compile error

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#2896] opened 2018-06-06 14:36 UTC
@trilinos/ifpack2 

## Expectations

Should be able to include installed Ifpack2 headers and build without error.

## Current Behavior

```
trilinos-install-serial-intel-release/include/Ifpack2_BlockTriDiContainer_impl.hpp(1585): error: "Side" is ambiguous
```

## Motivation and Context
Building apps against installed Trilinos.

## Possible Solution
Maybe add namespace qualifiers to that symbol?

**Comment by mhoemmen** [comment] 2018-06-06 14:58
Sorry @kyungjoo-kim I know I keep assigning you stuff -- it means you're contributing a lot these days :)

**Comment by kyungjoo-kim** [comment] 2018-06-06 17:04
@ibaned What is the full error message ? ambiguous with what ?

**Comment by ibaned** [comment] 2018-06-06 17:33
@kyungjoo-kim unfortunately, CDash is not showing much more information. If you can access this internal website, here is where I'm getting my information from:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=71922

**Comment by kyungjoo-kim** [comment] 2018-06-06 17:41
@ibaned The link does not work on my computer (is srn only ?). The _impl file should not be included but I put it in _decl file accidently. I will file another PR for this.

**Comment by kyungjoo-kim** [comment] 2018-06-06 18:34
@ibaned I would like to see the error message in the link but the link does not work. If you don't mind , can I come by and see the error log  ?

**Comment by lxmota** [comment] 2018-06-06 22:13
Here is a typical error from an attempt to compile Albany:

```
In file included from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_decl.hpp:58:0,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_ContainerFactory_def.hpp:51,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_ContainerFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockRelaxation_decl.hpp:52,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockRelaxation.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_OneLevelFactory_def.hpp:54,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_OneLevelFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_Factory_def.hpp:46,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_Factory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Factory_decl.hpp:48,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Factory.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Thyra_Ifpack2PreconditionerFactory_def.hpp:51,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Thyra_Ifpack2PreconditionerFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_InvertMassMatrixDecorator_Def.hpp:57,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_InvertMassMatrixDecorator.hpp:165,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_VelocityVerletSolver_Def.hpp:49,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_VelocityVerletSolver.hpp:130,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_SolverFactory_Def.hpp:50,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_SolverFactory.hpp:97,
                 from /home/amota/LCM/Albany/src/Albany_SolverFactory.cpp:24:
/home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_impl.hpp: In member function ‘void Ifpack2::BlockTriDiContainerDetails::ExtractAndFactorizeTridiags<MatrixType>::factorize(const local_ordinal_type&) const’:
/home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_impl.hpp:1585:85: error: wrong number of template arguments (1, should be 5)
             SerialTrsm<Side::Left,Uplo::Lower,Trans::NoTranspose,Diag::Unit,AlgoType>
                                                                                     ^
In file included from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_impl.hpp:64:0,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_decl.hpp:58,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_ContainerFactory_def.hpp:51,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_ContainerFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockRelaxation_decl.hpp:52,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockRelaxation.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_OneLevelFactory_def.hpp:54,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_OneLevelFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_Factory_def.hpp:46,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_Factory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Factory_decl.hpp:48,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Factory.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Thyra_Ifpack2PreconditionerFactory_def.hpp:51,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Thyra_Ifpack2PreconditionerFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_InvertMassMatrixDecorator_Def.hpp:57,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_InvertMassMatrixDecorator.hpp:165,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_VelocityVerletSolver_Def.hpp:49,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_VelocityVerletSolver.hpp:130,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_SolverFactory_Def.hpp:50,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_SolverFactory.hpp:97,
                 from /home/amota/LCM/Albany/src/Albany_SolverFactory.cpp:24:
/home/amota/LCM/trilinos-install-serial-gcc-debug/include/KokkosBatched_Trsm_Decl.hpp:16:12: note: provided for ‘template<class ArgSide, class ArgUplo, class ArgTrans, class ArgDiag, class ArgAlgo> struct KokkosBatched::Experimental::SerialTrsm’
     struct SerialTrsm {
            ^~~~~~~~~~
In file included from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_decl.hpp:58:0,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_ContainerFactory_def.hpp:51,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_ContainerFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockRelaxation_decl.hpp:52,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockRelaxation.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_OneLevelFactory_def.hpp:54,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_OneLevelFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_Factory_def.hpp:46,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Details_Factory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Factory_decl.hpp:48,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_Factory.hpp:1,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Thyra_Ifpack2PreconditionerFactory_def.hpp:51,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Thyra_Ifpack2PreconditionerFactory.hpp:2,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_InvertMassMatrixDecorator_Def.hpp:57,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_InvertMassMatrixDecorator.hpp:165,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_VelocityVerletSolver_Def.hpp:49,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_VelocityVerletSolver.hpp:130,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_SolverFactory_Def.hpp:50,
                 from /home/amota/LCM/trilinos-install-serial-gcc-debug/include/Piro_SolverFactory.hpp:97,
                 from /home/amota/LCM/Albany/src/Albany_SolverFactory.cpp:24:
/home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_impl.hpp:1586:23: error: qualified-id in declaration before ‘(’ token
               ::invoke(one, A, B);
                       ^

```

**Comment by kyungjoo-kim** [comment] 2018-06-06 22:20
The error message is werid. It says that the number of template parameters does not match but apparently the number of template parameters match in the error message. 
```
/home/amota/LCM/trilinos-install-serial-gcc-debug/include/Ifpack2_BlockTriDiContainer_impl.hpp:1585:85: 
error: wrong number of template arguments (1, should be 5)
             SerialTrsm<Side::Left,Uplo::Lower,Trans::NoTranspose,Diag::Unit,AlgoType>
```
This error message is different from what @ibaned reports (ambiguous name space). 

Anyway it will be resolved as now the decl file cannot see the local impl header file anymore.
BTW, do you do ETI ?

**Comment by ambrad** [comment] 2018-06-07 00:11
@kyungjoo-kim this has happened before. See issue #1722 and this comment in particular for the explanation and fix: https://github.com/trilinos/Trilinos/issues/1722#issuecomment-328967698

Roughly speaking, KokkosKernels types must be namespaced carefully.

**Comment by mhoemmen** [comment] 2018-06-07 04:19
@lxmota wrote:
> There is an incompatibility between DTK and TPetra in the use of unsigned vs signed integers that results in a compile error when ETI is enabled.

Could you please clarify?  This is the first time I've heard of this.  I know that DTK insists on `GlobalOrdinal = unsigned long`; in fact, Tpetra has a CMake option to enable this feature.  It's a Bad Idea to rely on ETI OFF to make this work, and it's also a Bad Idea that y'all rely on this feature without any Trilinos builds (as far as I know) to test it.

Tpetra has FY18 plans to pick a single GlobalOrdinal type (probably `int64_t`).  It _will_ be a signed 64-bit integer type.

**Comment by rppawlo** [comment] 2018-06-07 11:21
> Tpetra has FY18 plans to pick a single GlobalOrdinal type (probably int64_t). It will be a signed 64-bit integer type.

@sslattery - FYI on GO type.

**Comment by mhoemmen** [comment] 2018-06-07 15:14
@rppawlo Y'all know how I feel about `GO=unsigned long` already; sorry to rub it in ;-)

**Comment by mhoemmen** [comment] 2018-06-07 15:14
Seriously though, saving >= 2x build time and library/executable size is really really attractive at this point.

**Comment by mhoemmen** [comment] 2018-06-07 15:15
So if there's some feature that will make this transition easier, please please let me know.  The plan is to add a backwards compatibility framework that will allow you to specify the same template parameters, but will reject all GO but the supported type.  The `global_ordinal_type` typedef will remain.  I have a prototype design already.

**Comment by mhoemmen** [comment] 2018-06-07 15:17
> It's a Bad Idea to rely on ETI OFF to make this work, and it's also a Bad Idea that y'all rely on this feature without any Trilinos builds (as far as I know) to test it.

To clarify Bad Idea: LinearSolverFactory depends on knowing the set of enabled GO types in order to do run-time registration of solvers for Dependency Inversion and Injection.  This is true whether or not ETI is enabled.  I can't promise that Ifpack2 will work correctly, for example, if you turn off ETI and use GO types that aren't in the original configure-time enabled list.

**Comment by kyungjoo-kim** [comment] 2018-06-07 15:21
@ambrad Thanks a lot. I think that I am encountering all the troubles that you have experienced. I never expect that the using statement can cause such a problem. It should be changed and I will submit another PR. Hopely, the PR would be the last one for this ifpack2.

**Comment by rppawlo** [comment] 2018-06-07 15:41
> Y'all know how I feel about GO=unsigned long already; sorry to rub it in ;-)

No worries @mhoemmen  :) I'm all in favor of removing template parameters when possible. That change will simplify panzer configure/ETI logic. Is the Tpetra plan somewhere online so we can see the scope of the template parameter changes?

**Comment by kyungjoo-kim** [comment] 2018-06-07 17:20
@ibaned @lxmota 

I submitted another PR to change the namespace things. This should pass PR test easily as I only change the name space things. @ibaned once you confirms that the problem is gone, please close this issue. 

@ambrad experienced the same problem but I fell in the same trip. I left a comment for someone who may touch the code in the future. I don't think that there is a systematic way to prevent this kind of problems.

**Comment by lxmota** [comment] 2018-06-07 23:09
@kyungjoo-kim I was able to compile successfully just now. Perhaps it would be prudent to wait for the Albany nightly tests to run and see what the dashboard looks like tomorrow.

Thanks!

**Comment by kyungjoo-kim** [comment] 2018-06-11 15:17
@lxmota Do we have a clean dash board ?

**Comment by ibaned** [comment] 2018-06-11 15:22
@kyungjoo-kim Yes, I think the dashboard is clean now. Thank you!

**Closed** 2018-06-11 15:22 UTC
Labels: Ifpack2, bug

**Comment by kyungjoo-kim** [comment] 2018-06-11 15:30
Ifpack2 block tridi container is finally done until I (or someone) break it again.
