### ISSUE TITLE
Ifpack2:  Build errors in BlockTriDiContainer with float enabled.

### ISSUE THREAD

**Issue by vbrunini** [trilinos/Trilinos#5148] opened 2019-05-09 21:15 UTC
## Bug Report

@trilinos/Ifpack2

### Description
```
/scratch/vebruni/src/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:2117:7:   required from 'void Ifpack2::BlockTriDiContainerDetails::performNumericPhase(const Teuchos::RCP<const typename Ifpack2::BlockTriDiContainerDetails::ImplType<MatrixType>::tpetra_block_crs_matrix_type>&, const Ifpack2::BlockTriDiContainerDetails::PartInterface<MatrixType>&, Ifpack2::BlockTriDiContainerDetails::BlockTridiags<MatrixType>&, typename Ifpack2::BlockTriDiContainerDetails::ImplType<MatrixType>::magnitude_type) [with MatrixType = Tpetra::RowMatrix<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >; typename Ifpack2::BlockTriDiContainerDetails::ImplType<MatrixType>::tpetra_block_crs_matrix_type = Tpetra::Experimental::BlockCrsMatrix<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >; typename Ifpack2::BlockTriDiContainerDetails::ImplType<MatrixType>::magnitude_type = float]'
/scratch/vebruni/src/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp:235:9:   required from 'void Ifpack2::BlockTriDiContainer<MatrixType, Ifpack2::BlockTriDiContainerDetails::ImplSimdTag>::compute() [with MatrixType = Tpetra::RowMatrix<float, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >]'
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_Serial.cpp:61:1:   required from here
/scratch/vebruni/src/Trilinos/packages/kokkos-kernels/src/batched/KokkosBatched_Scale_Internal.hpp:28:20: error: no match for 'operator*=' (operand types are 'KokkosBatched::Experimental::Vector<KokkosBatched::Experimental::SIMD<float>, 16>' and 'const double')
           A[i*as0] *= alpha;
           ~~~~~~~~~^~~~~~~~
```
and more of similar forms.

### Steps to Reproduce
1. SHA1:  cbb3aff10d4a55f56bb00cca6cdad6cb85d24f09
1. Configure script:
```
cmake -G "Ninja" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -D Trilinos_EXTRA_LINK_FLAGS:STRING="" \
  -D CMAKE_BUILD_TYPE:STRING=release \
  -D LAPACK_LIBRARY_DIRS:PATH=/path/to/lapack
  -D LAPACK_LIBRARY_NAMES:STRING="src-lapack-c;src-lapack-d;src-lapack-s;src-lapack-z" \
  -D BLAS_LIBRARY_DIRS:PATH=/path/to/blas
  -D BLAS_LIBRARY_NAMES:STRING="src-blas-c;src-blas-d;src-blas-s;src-blas-z" \
  -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
  -D Kokkos_ENABLE_Cuda_Relocatable_Device_Code:BOOL=OFF \
  -D TPL_ENABLE_CUDA:BOOL=OFF \
  -DCMAKE_C_COMPILER=/projects/sierra/linux_rh6/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpicc
  -DCMAKE_CXX_COMPILER=/projects/sierra/linux_rh6/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpic
  -DCMAKE_Fortran_COMPILER=/projects/sierra/linux_rh6/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/
  -DKokkos_ENABLE_SIERRA_BUILD:BOOL=OFF \
  -DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
  -DCMAKE_INSTALL_PREFIX:PATH="/path/to/install" \
  -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -DTrilinos_ENABLE_Gtest:BOOL=OFF \
  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DCMAKE_EXTRA_LINK_FLAGS:STRING= \
  -DCMAKE_C_FLAGS_RELEASE_OVERRIDE:STRING="-DNDEBUG" \
  -DCMAKE_CXX_FLAGS_RELEASE_OVERRIDE:STRING="-DNDEBUG" \
  -DCMAKE_Fortran_FLAGS_RELEASE_OVERRIDE:STRING="-DNDEBUG" \
  -DCMAKE_C_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -Wno-inline -w " \
  -DCMAKE_CXX_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -Wno-inline -w " \
  -DCMAKE_Fortran_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -Wno-inline -w  " \
  -DTrilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
  -DTPL_ENABLE_Pthread:BOOL=OFF \
  -DHAVE_GCC_ABI_DEMANGLE:BOOL=ON \
  -DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
  -DTPL_ENABLE_ParMETIS:BOOL=ON \
  -DParMETIS_INCLUDE_DIRS:PATH="/path/to/parmetis" \
  -DParMETIS_LIBRARY_DIRS:PATH="/path/to/parmetis" \
  -DMETIS_INCLUDE_DIRS:PATH="/path/to/metis" \
  -DMETIS_LIBRARY_DIRS:PATH="/path/to/metis" \
  -DTPL_ENABLE_UMFPACK:BOOL=ON \
  -DUMFPACK_INCLUDE_DIRS:PATH="/path/to/umfpack" \
  -DUMFPACK_LIBRARY_DIRS:PATH="/path/to/umfpack" \
  -DTPL_ENABLE_y12m:BOOL=ON \
  -Dy12m_LIBRARY_DIRS:PATH="/path/to/y12m" \
  -DTPL_ENABLE_Boost:BOOL=ON \
  -DTPL_Boost_INCLUDE_DIRS:PATH="/path/to/boost" \
  -DTPL_ENABLE_yaml-cpp:BOOL=OFF \
  -Dyaml-cpp_INCLUDE_DIRS:PATH="/path/to/yaml" \
  -Dyaml-cpp_LIBRARY_DIRS:PATH="/path/to/yaml" \
  -DSuperLU_INCLUDE_DIRS:PATH="/path/to/superlu" \
  -DSuperLU_LIBRARY_DIRS:PATH="/path/to/superlu" \
  -DScotch_INCLUDE_DIRS:PATH="/path/to/scotch" \
  -DScotch_LIBRARY_DIRS:PATH="/path/to/scotch" \
  -DTrilinos_ENABLE_ThreadPool:BOOL=ON \
  -DTrilinos_ENABLE_Zoltan:BOOL=ON \
  -DZoltan_ENABLE_Scotch:BOOL=OFF \
  -DTrilinos_ENABLE_Zoltan2:BOOL=ON \
  -DZoltan2_ENABLE_Scotch:BOOL=OFF \
  -DZoltan2_ENABLE_Experimental:BOOL=ON \
  -DZoltan2_ENABLE_HYPERGRAPHMODEL:BOOL=OFF \
  -DTrilinos_ENABLE_Shards:BOOL=ON \
  -DTrilinos_ENABLE_Mesquite:BOOL=OFF \
  -DTrilinos_ENABLE_Teuchos:BOOL=ON \
  -DTrilinos_ENABLE_RTOp:BOOL=ON \
  -DTrilinos_ENABLE_Epetra:BOOL=ON \
  -DTrilinos_ENABLE_EpetraExt:BOOL=ON \
  -DTrilinos_ENABLE_Triutils:BOOL=ON \
  -DTrilinos_ENABLE_Thyra:BOOL=ON \
  -DTrilinos_ENABLE_AztecOO:BOOL=ON \
  -DTrilinos_ENABLE_Amesos:BOOL=ON \
  -DTrilinos_ENABLE_Amesos2:BOOL=ON \
  -DTrilinos_ENABLE_Belos:BOOL=ON \
  -DTrilinos_ENABLE_Intrepid:BOOL=ON \
  -DTrilinos_ENABLE_IntrepidIntrepid2:BOOL=OFF \
  -DIntrepid_ENABLE_KokkosCore:BOOL=OFF \
  -DTrilinos_ENABLE_Ifpack:BOOL=ON \
  -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
  -DTrilinos_ENABLE_Tpetra:BOOL=ON \
  -DTrilinos_ENABLE_Kokkos:BOOL=ON \
  -DTrilinos_ENABLE_KokkosCore:BOOL=ON \
  -DTrilinos_ENABLE_KokkosContainers:BOOL=ON \
  -DTrilinos_ENABLE_KokkosTSQR:BOOL=OFF \
  -DTrilinos_ENABLE_Anasazi:BOOL=ON \
  -DTrilinos_ENABLE_ML:BOOL=ON \
  -DTrilinos_ENABLE_MueLu:BOOL=ON \
  -DTrilinos_ENABLE_Stratimikos:BOOL=OFF \
  -DTrilinos_ENABLE_NOX:BOOL=ON \
  -DTrilinos_ENABLE_FEI:BOOL=ON \
  -DTrilinos_ENABLE_TrilinosCouplings:BOOL=ON \
  -DTrilinos_ENABLE_MOOCHO:BOOL=OFF \
  -DTrilinos_ENABLE_Sacado:BOOL=ON \
  -DSacado_ENABLE_KokkosCore:BOOL=ON \
  -DTrilinos_ENABLE_Stokhos:BOOL=ON \
  -DTrilinos_ENABLE_Pamgen:BOOL=ON \
  -DPamgen_ENABLE_Boost:BOOL=OFF \
  -DTrilinos_ENABLE_Rythmos:BOOL=ON \
  -DTrilinos_ENABLE_ThyraEpetraExtAdapters:BOOL=ON \
  -DTrilinos_ENABLE_Xpetra:BOOL=ON \
  -DTrilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON \
  -DTacho_ENABLE_INT_INT:BOOL=ON \
  -DAmesos2_ENABLE_ShyLU_NodeTacho:BOOL=OFF \
  -DTrilinos_ENABLE_ShyLU_NodeHTS:BOOL=ON \
  -DTrilinos_ENABLE_ShyLUFastILU:BOOL=ON \
  -DTrilinos_ENABLE_Isorropia:BOOL=OFF \
  -DTrilinos_ENABLE_STKClassic:BOOL=OFF \
  -DTrilinos_ENABLE_STK:BOOL=OFF \
  -DTrilinos_ENABLE_SEACAS:BOOL=OFF \
  -DAmesos_ENABLE_SuperLU:BOOL=ON \
  -DAmesos2_ENABLE_SuperLU:BOOL=ON \
  -DAztecOO_ENABLE_AZLU:BOOL=ON \
  -DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
  -DTrilinos_ENABLE_FLOAT:BOOL=ON \
  -DZoltan_ENABLE_METIS:BOOL=OFF \
  -DStokhos_ENABLE_Ifpack:BOOL=OFF \
  -DStokhos_ENABLE_ML:BOOL=OFF \
  -DStokhos_ENABLE_Anasazi:BOOL=OFF \
  -DStokhos_ENABLE_Sacado:BOOL=ON \
  -DStokhos_ENABLE_NOX:BOOL=OFF \
  -DStokhos_ENABLE_KokkosClassic:BOOL=OFF \
  -DStokhos_ENABLE_KokkosCore:BOOL=OFF \
  -DStokhos_ENABLE_Tpetra:BOOL=OFF \
  -DStokhos_ENABLE_Ifpack2:BOOL=OFF \
  -DStokhos_ENABLE_AztecOO:BOOL=OFF \
  -DStokhos_ENABLE_Stratimikos:BOOL=OFF \
  -DStokhos_ENABLE_Belos:BOOL=OFF \
  -DML_ENABLE_ParMETIS:BOOL=OFF \
  -DML_ENABLE_METIS:BOOL=OFF \
  -DNOX_ENABLE_ABSTRACT_IMPLEMENTATION_THYRA:BOOL=OFF \
  -DKOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -DKOKKOS_ENABLE_PROFILING:BOOL=ON \
  -DTrilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION:BOOL=ON \
  -DTrilinos_ENABLE_MiniTensor:BOOL=ON \
  -DTrilinos_ENABLE_Galeri:BOOL=OFF \
  -DTpetra_INST_SERIAL:BOOL=ON \
  -DTpetra_INST_INT_LONG:BOOL=ON \
  -DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
 /path/to/Trilinos
```

**Comment by kddevin** [comment] 2019-05-09 21:16
@trilinos/kokkos-kernels

**Comment by mhoemmen** [comment] 2019-05-09 23:19
@Mark-E-Hamilton noticed this too.

**Comment by mhoemmen** [comment] 2019-05-11 00:24
I got Ifpack2 to build by adding the following code to `Ifpack2_BlockTriDiContainer_def.hpp`, after the includes and before `namespace Ifpack2`:
```c++
namespace KokkosBatched {
namespace Experimental {

KOKKOS_INLINE_FUNCTION
Vector<SIMD<float>, 16>
operator* (const Vector<SIMD<float>, 16>& x, const double y)
{
  return x * static_cast<float> (y);
}

KOKKOS_INLINE_FUNCTION
Vector<SIMD<float>, 16>
operator* (const double x, const Vector<SIMD<float>, 16>& y)
{
  return y * static_cast<float> (x);
}

KOKKOS_INLINE_FUNCTION
Vector<SIMD<float>, 16>&
operator*= (Vector<SIMD<float>, 16>& x, const double y)
{
  x = x * static_cast<float> (y);
  return x;
}

} // namespace Experimental
} // namespace KokkosBatched
```

**Comment by mhoemmen** [comment] 2019-05-11 00:42
@ajpowelsnl @Mark-E-Hamilton @rrdrake @sebrowne This issue blocks Sierra Trilinos integration.  PR #5154 proposes a temporary fix.  It is blocked by #5147 (PR testing is broken for likely non-Trilinos reasons).

**Comment by kyungjoo-kim** [comment] 2019-05-13 15:53
@vbrunini @mhoemmen Thank you for reporting error. Let me fix this problem today.

**Comment by mhoemmen** [comment] 2019-05-13 19:44
@kyungjoo-kim Thanks! :-D  btw we can't actually fix this today, at least not until #5147 gets fixed.

**Comment by kyungjoo-kim** [comment] 2019-05-13 22:04
@vbrunini  The PR is merged. Could you please check that the problem is resolved ?

**Comment by vbrunini** [comment] 2019-05-13 23:09
The fix resolved my issue, thanks.

**Comment by mhoemmen** [comment] 2019-05-14 00:16
@prwolfe @rrdrake @ajpowelsnl FYI

**Comment by kyungjoo-kim** [comment] 2019-05-15 18:36
@vbrunini if this issue is resoled, can we close this ?

**Comment by mhoemmen** [comment] 2019-05-15 18:59
I think it's OK to close, since the fix is in master.  Thanks!

**Closed by mhoemmen** 2019-05-15 18:59 UTC
Labels: client: Sierra, impacting: build, pkg: Ifpack2, pkg: KokkosKernels, type: bug
