### ISSUE TITLE
Nalu diffs due to latest Trilinos update

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#725] opened 2016-10-22 00:59 UTC
Bad test suite as of Trilinos SHA1:

commit 5320963fbe2ec9aeba1dc62871e4be4f44961970
Author: Tobias Wiesner tawiesn@sandia.gov
Date: Wed Oct 19 14:43:41 2016 -0600

Last good:

NaluCFD/Nalu SHA1: d2adbe8
Trilinos/master SHA1: 12fd285b28abeb7336a8d4f17913819b9ce7015b

This bisect is complicated in that the builds of Trilinos fail either due to configure errors or flat out build issues.

**Comment by spdomin** [comment] 2016-10-22 01:12
As I bisect, a number of the config steps are failing due to:

 Error, the variable TPL_ENABLE_CGNS is not defined

**Comment by spdomin** [comment] 2016-10-22 16:53
I resolved this and found the following commit caused the issue:

31d1a077ad748d89f227c359c9ebdb1b6fe40cbf is the first bad commit
commit 31d1a077ad748d89f227c359c9ebdb1b6fe40cbf
Author: Tobias Wiesner <tawiesn@sandia.gov>
Date:   Mon Oct 17 12:29:53 2016 -0600

    Ifpack: introduce optimized SGS algorithm for 1 rhs only.
    
    In most cases we have only one rhs vector. Avoiding double indices saves
    approximately 25-30% iteration time.

:040000 040000 90b1d9d2092ca94ff87580dd29b0a898950f8fda d66773473e928c43da31f8b5e9e1788f82b471fa M	packages

**Comment by tawiesn** [comment] 2016-10-23 00:42
I've ran the checkin test script with all downstream packages of MueLu and Zoltan2. I've explicitly also enabled the Ifpack tests and they passed without problem:

```
Build/Test Cases Summary
Enabled Packages: Zoltan2
Enabled all Forward Packages
0) MPI_DEBUG => Skipped configure, build, test due to no enabled packages! => Does not affect push readiness! (-1.00 min)
1) SERIAL_RELEASE => Skipped configure, build, test due to no enabled packages! => Does not affect push readiness! (-1.00 min)
2) MPI_DEBUG_ENIGMA => passed: passed=332,notpassed=0 (50.19 min)

```

I've slightly reordered the algorithmic steps in the optimized version which is the only reason that could explain your diffs (cancellation effects?). I've tested the algorithm with a rather complex MHD example in drekar both in serial on a small problem and in parallel up to 2048 cores before and after my commit and could reproduce the exact same results.
I could undo the reorganization of the algorithmic steps in the single-rhs branch. I don't think that the optimization by hand really helped that lot. But i want to keep the special single-rhs branch as it avoids the extra memory access.

**Comment by spdomin** [comment] 2016-10-23 01:10
Whatever you think is best. If you have confidence in the new implementation, I can accept the diffs.

Many turbulent flow simulations are very sensitive to the order of operations. The tests diffed at 1e-8-ish in the nonlinear residuals.

**Comment by tawiesn** [comment] 2016-10-23 06:07
Let me create a patch with the original ordering of the operations next Monday and submit it. It should produce the original numbers and the performance difference should not be significant. We should still get a performance boost for the single-rhs version since we need one memory access operation less each iteration. I was trying to get the Ifpack algorithm closer to what is done in the ML implementation.

**Comment by tawiesn** [comment] 2016-10-23 06:11
> It does, again, suggest that we should work to have a Nalu-like test added to the test suite.

That would help a lot to avoid problems like that in the future. You could create a docker container with Nalu that runs the test suite. That would simplify the testing process and would make sure that we really testing your environment (compiler version, TPLs,...)
I will talk about docker containers on Tuesday at the TUG meeting.

**Comment by tawiesn** [comment] 2016-10-24 17:01
I'm going to (temporarily) revert the problematic commit for preserving backwards compatibility of results. I think the slightly changed results are easily explained by numerical effects, but i don't want to change well-established code that has been used for years without more application-specific tests to get a better understanding of the impact on real-world examples.
@spdomin: Please test version 7176fb8f1e81999 (or later) in the develop branch.

**Comment by maherou** [comment] 2016-10-24 17:15
I added two labels to this issue (performance and results impacting), for easier tracking.

**Comment by spdomin** [comment] 2016-10-24 19:37
I test, nightly, Trilinos/master where the diffs are showing up. Once the update occurs, I can report back. Perhaps you can ask Brent for an update sooner than later?

For future reference, the below Nalu tests are showing the diff... Not all tests differ, which may give you more confidence...

..elemPipeCHT................. FAILED:  6.3  s  max diff:  .00000000000000010001765041178779
..fluidsPmrChtPeriodic........ FAILED:  54.9  s  max diff:  .00000000000000110003152420379279
..elemHybridFluidsShift....... FAILED:  40.7  s  max diff:  .00000000000323440700005104208539
..elemClosedDomain............ FAILED:  0.6  s  max diff:  .00000001410532082000097832755192
..mixedTetPipe................ FAILED:  13.4  s  max diff:  .00000000000000110000103101769164
..nonIsoNonUniformEdgeOpenJet. FAILED:  25.2  s  max diff:  .00000000000000013999929958808526

**Comment by spdomin** [comment] 2016-10-24 20:00
I just tested develop and it is, as expected, clean.

**Comment by tawiesn** [comment] 2016-10-24 20:06
Great, once i can run NALU tests (and maybe other required application tests) i will try to optimize the code again.

**Comment by spdomin** [comment] 2016-10-25 14:37
Nightly tests using master still diff. What is the status of the develop branch push to master?

Also, @tawiesn please interface with @jhux2 to obtain the milestone-based Nalu tests. This would be a good test suite to run your SGS improvements at scale. @crtrott also has the suite of meshes.

**Comment by jhux2** [comment] 2016-10-25 15:13
The smallest of the tests, and the one apparently with the largest diff, is elemClosedDomain.

**Comment by spdomin** [comment] 2016-10-25 16:38
Yes, that is a highly nonlinear pressurizing vessel (thermally heated). Not sure if that is a good test case to establish the correctness of the new single RHS SGS code base. It is, however, a great test to show sensitivities in algorithms that grow over time... I guess that means that it really is not a great test, however, that is the physics that we support:)

**Comment by spdomin** [comment] 2016-10-26 22:13
Still waiting on an update to maste. Correct me if I am wrong, however, this is another case in which a revert was applied in develop with master in abroken state.

@maherou please comment:)

**Comment by maherou** [comment] 2016-10-27 02:42
I don't understand your point: "this is another case in which a revert was applied in develop with master in a broken state."

**Comment by spdomin** [comment] 2016-10-27 14:19
All three of the past three Trilinos/Nalu issues were found in the master branch. In each case, some sort of patch or revert was applied to develop. However, due to the lag in the updating of master, the intended gold state of Trilinos is "broken". As such, as I have noted before, the develop branch is (from our applications perspective) the more agile and "correct" branch.

I feel that a simple policy of immediately patching both development and master in cases were reverts or known issues are identified in master would be the most reasonable process change.

The current situation is analogous to if a bug is found in a released code based and fixed in a branch along with a delayed update/redistribution of the released code base. Think of the user perspective in that situation. I know that master is not an intended release; I just make the analogy.

**Comment by tawiesn** [comment] 2016-10-27 14:59
Fyi: The master branch has been updated in the morning. We were all quite busy with the TUG the last couple of days.

**Comment by tawiesn** [comment] 2016-10-27 15:12
I think, the problem is that the Trilinos and the Nalu point of view differ: from a Trilinos point of view, the master branch never was "broken". The patch passed all tests and caused no issues within the Trilinos test suite. It also produced correct results on examples where you know the exact solution. However, from a numerical aspect it showed a different behavior and produced different results for some examples which make look it to brake things in Nalu (and maybe other applications, too).
In my opinion, the only reasonable way to avoid situations like this is, to extend the Trilinos test suite. Maybe not by adding the Nalu tests to the test suite, but by having an internal policy that requires certain (whatever that means) applications tests to pass before checkin in high-risk patches. It's clear that Nalu would not be the only application we have to test, though. From a practical point of view it would be necessary to make it as easy as possible for Trilinos developers to be able to run all these application tests (Nalu, drekar, albany). It's hard enough to have one or two applications installed on our workstations, properly updated, compiled, etc. I do it for the parts of drekar that i have access to. But even there i have days where drekar is broken and i have to wait until it is fixed, fix it on my own or go back in history and check out an older version...

**Comment by tawiesn** [comment] 2016-10-27 15:15
A possible solution could be docker containers, provided by the application containers, containing the application, the tests they want to be passed with the corresponding compilers, libraries etc...
Trilinos developers could use them, generate them with their local most-recent Trilinos version, run the test suite and make sure that the new patches would not break the application...

**Comment by agsalin** [comment] 2016-10-27 15:38
I agree that Trilinos testing is not thorough enough, and the applications you mention fill in many gaps. In particular, installation testing is essentially done post-push by Albany and Nalu, and STK goes through phases where they continually break backward compatibility, only to be caught by Drekar, Albany, and Nalu. 

I think we should we should work to having these apps as part of CI testing, although  it would take some work to make it so instabilities in the apps don't impact Trilinos integration. I also agree with what Ross said at TUG is that we need to start pre-push CI testing small and grow it.

**Comment by maherou** [comment] 2016-10-27 15:57
A few comments:
- I strongly agree that we need to gradually improve our pre-push CI.  We are moving in that direction.
- Master is updated from develop.  We do not selective revert commits to master.  That breaks the model.
- While we will try to address diffs that are due to changes in floating point arithmetic order for now, this is not a sustainable approach.  
- As thread parallel algorithms become more common, and eventually become the norm, any test that relies on text-based diffs will fail frequently.  Running the same executable twice will produce different results solely due to non-deterministic floating point behavior.  As a community we need to move away from this testing approach.

**Comment by jhux2** [comment] 2021-01-20 02:58
I'm going to close this due to age.

**Closed by jhux2** 2021-01-20 02:58 UTC
Labels: MARKED_FOR_CLOSURE, impacting: performance, results impacting
