### ISSUE TITLE
Belos compile error

### ISSUE THREAD

**Issue by ibaned** [trilinos/Trilinos#2999] opened 2018-06-21 14:13 UTC
@trilinos/belos

## Expectations

Belos should build without error.

## Current Behavior

```
repos/Trilinos/packages/belos/src/BelosTsqrOrthoManagerImpl.hpp:206:45: error: no type named ‘tsqr_adaptor_type’ in ‘class Belos::MultiVecTraits >’
```

**Comment by ibaned** [comment] 2018-06-21 14:15
A little bit more of the error message:
```
     typedef typename MVT::tsqr_adaptor_type tsqr_adaptor_type;
                                             ^~~~~~~~~~~~~~~~~
[ 73%] Building CXX object packages/ml/src/CMakeFiles/ml.dir/Utils/ml_MultiLevelPreconditioner_XML.cpp.o
[ 74%] Building CXX object packages/ml/src/CMakeFiles/ml.dir/Utils/ml_anasazi.cpp.o
/.../repos/Trilinos/packages/belos/src/BelosTsqrOrthoManagerImpl.hpp: In instantiation of ‘Teuchos::RCP Belos::TsqrOrthoManagerImpl::getValidParameters() const [with Scalar = double; MV = Xpetra::MultiVector<>]’:
repos/Trilinos/packages/belos/src/BelosTsqrOrthoManager.hpp:472:38:   required from ‘Teuchos::RCP Belos::TsqrMatOrthoManager::getValidParameters() const [with Scalar = double; MV = Xpetra::MultiVector<>; OP = Belos::OperatorT >]’
repos/Trilinos/packages/belos/src/BelosOrthoManagerFactory.hpp:198:38:   required from ‘Teuchos::RCP Belos::OrthoManagerFactory::getDefaultParameters(const string&) const [with Scalar = double; MV = Xpetra::MultiVector<>; OP = Belos::OperatorT >; std::__cxx11::string = std::__cxx11::basic_string]’
repos/Trilinos/packages/belos/src/BelosGCRODRSolMgr.hpp:1166:32:   required from ‘Teuchos::RCP Belos::GCRODRSolMgr::getValidParameters() const [with ScalarType = double; MV = Xpetra::MultiVector<>; OP = Belos::OperatorT >]’
repos/Trilinos/packages/belos/xpetra/src/Belos_Details_Xpetra_registerSolverFactory.cpp:170:1:   required from here
```

**Comment by mhoemmen** [comment] 2018-06-21 15:24
@MicheldeMessieres I suspect your changes didn't actually cause this, but somehow revealed it.

@ibaned Try putting a stub `tsqr_adaptor_type` typedef (just typedef it to `int` or something) in that Xpetra specialization of MultiVecTraits -- if that fixes the build, then my suspicions are correct.

**Comment by mhoemmen** [comment] 2018-06-29 20:31
@ibaned Is this still showing up for you?

**Comment by ibaned** [comment] 2018-06-29 20:33
@mhoemmen yep, looks like its still there

**Comment by mhoemmen** [comment] 2018-06-29 21:15
@ibaned Did adding the stub typedef help?

**Comment by ibaned** [comment] 2018-06-29 21:16
I'm afraid I won't have time to try that for a while... I'll post here if I get around to it

**Comment by gahansen** [comment] 2018-07-02 15:19
@mhoemmen , I'd try the stub if you can give me more guidance on where it needs to go - I'm not Belos-aware enough to integrate through the logic there and figure it out. We are seeing this compile issue in the Trilinos build that the Albany compile depends on:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=72929

we have configured:

"-DTrilinos_ENABLE_TpetraTSQR:BOOL=ON"
"-DTpetraCore_ENABLE_TSQR:BOOL=ON"
"-DBelos_ENABLE_TSQR:BOOL=ON"

I might suggest that we add a new Trilinos nightly that builds these options, or add them to an existing nightly as the Albany MOR package depends on tsqr. Right now, Trilinos folk might not know this is "broken" unless they look at the Albany dashboard or an Albany user initiates an issue.

**Comment by mhoemmen** [comment] 2018-07-02 16:12
@gahansen Hm, I would like to learn more about Albany's TSQR needs.  Could you please send me an e-mail about that?

I'll take a look at this.

**Comment by ibaned** [comment] 2018-07-02 16:18
It has to do with depending on rbgen in Anasazi. @ikalash knows more about this.

**Comment by mhoemmen** [comment] 2018-07-02 16:46
So you're not actually using TSQR?

**Comment by ibaned** [comment] 2018-07-02 16:48
I'm pretty sure we are, @ikalash should email you soon and CC others who can describe more details

**Comment by ikalash** [comment] 2018-07-02 17:10
@jfike : have we decided to remove Albany MOR's dependency on RBGen like we did for SPARC?  Per the discussion above, I think the MOR POD basis computation is the only thing that uses TSQR in Albany.  Perhaps we should turn it off if it is not needed anymore.

**Comment by mhoemmen** [comment] 2018-07-02 17:21
> I think the MOR POD basis computation is the only thing that uses TSQR in Albany.

Does it literally use TSQR?  I intend to maintain TSQR going forward, and have funding to do so :-) .

**Comment by hkthorn** [comment] 2018-07-02 17:39
@mhoemmen @ikalash The POD basis computation in RBGen uses Anasazi, which can use TSQR but does not need to.  So, I'm pretty sure that TSQR is not a requirement for Anasazi, it may be enabled though.  I think the issue with RBGen is still just the linking of the Epetra driver, is that right @ikalash ?

**Comment by jfike** [comment] 2018-07-02 17:39
Actually, we DO use TSQR within the MOR part of Albany.  Typically in MOR we solve (W \Phi)^T (W \phi) \Delta x = -(W \Phi)^T f, where f is the residual, W is the Jacobian, and \Phi is the POD basis.  We have an alternative version that solves  (W \phi) \Delta x = - f by using TSQR on (W \Phi).  I created the initial implementation, but @plindsa pushed the actual changes to MOR_GaussNewtonOperatorFactory.  It's been a while since I've done much with Albany, so I'm not sure if it is tested or not.

I'm not sure if MOR's use of RBGen uses TSQR, but I don't think we have plans to eliminate the use of RBGen from Albany MOR.

**Comment by mhoemmen** [comment] 2018-07-02 17:56
@jfike Good to know!  I plan to Kokkos-ize TSQR for another project.

**Comment by mhoemmen** [comment] 2018-07-02 21:32
I think I know how to fix this.  We would take the same approach as the stub TSQR adapter in Belos' Thyra adapter (see `Trilinos/packages/stratimikos/adapters/belos/src`).

1. Implement stub TsqrAdapter for Xpetra
2. Use that TsqrAdapter as tsqr_adapter_type typedef in Xpetra specialization of `Belos::MultiVecTraits`

Be sure both the TsqrAdapter and the typedef are protected by the `HAVE_BELOS_TSQR` macro.

**Comment by mhoemmen** [comment] 2018-07-03 16:35
It's not much harder to write a working TsqrAdapter for Xpetra (at least for the Tpetra back-end) so I'm working on it now.  I can't replicate this build error, alas.

**Comment by mhoemmen** [comment] 2018-07-03 18:31
I found out that `HAVE_BELOS_TSQR` is undefined by default, even if I explicitly enable TSQR.  Now I can test whether my new Xpetra TSQR adapter compiles ;-) .

**Comment by ikalash** [comment] 2018-07-03 20:47
@mhoemmen : this shows up with intel or clang compilers (e.g., intel compiler on CEE).  I believe you need Anasazi and RBGen on.  Here are some details about the Albany Trilinos configuration with an intel compiler on the CEE where the issue is manifesting itself: http://cdash.sandia.gov/CDash-2-3-0/viewConfigure.php?buildid=73002 .

**Comment by mhoemmen** [comment] 2018-07-05 20:56
Earlier today, I merged a PR into develop that will hopefully fix this.

#3068 refers to the observation that Belos' default build options didn't catch this issue.

**Closed** 2018-07-18 14:41 UTC
Labels: Belos, bug
