### ISSUE TITLE
Teuchos:  `make_rcp`

### ISSUE THREAD

**Issue by romintomasetti** [trilinos/Trilinos#10642] opened 2022-06-21 09:36 UTC
## Enhancement
@trilinos/teuchos 

Oftentimes in our code, we create a `Teuchos::RCP` as follows:
```c++
auto ptr = Teuchos::rcp(new MyClass(... some args ...));
```

Similarly to `std::make_shared`, it would be nice to have:
```c++
/**
 * Allocates and constructs an object of type \c T 
 * passing @p args to its constructor, and returns an object of type
 * @ref Teuchos::RCP that owns and stores a pointer to it.
 */
template <typename T, typename ... Args>
inline auto make_rcp(Args&& ... args)
{
    return Teuchos::rcp(
        new T(std::forward<Args>(args)...)
    );
}
```

such that one could write:
```c++
auto ptr = Teuchos::make_rcp<MyClass>(... some args ...);
```

I could make a PR to add the above code in `Teuchos_RCP.hpp`. What do you think ?

Thanks !

**Comment by bartlettroscoe** [comment] 2022-06-21 21:53
NOTE: This is a duplicate of #1016 that was closed due to in-activity.

If you want to supply a PR with some tests that adds this, please do and I will review.

**Comment by romintomasetti** [comment] 2022-06-29 09:49
@bartlettroscoe I think this issue can be safely closed, as the proposed PR was accepted.

**Comment by bartlettroscoe** [comment] 2022-06-29 12:49
With the merge of #10647, this can be closed.

**Closed by bartlettroscoe** 2022-06-29 12:49 UTC
Labels: type: enhancement
