### ISSUE TITLE
KLU2 in Amesos2 has a significant memory leak

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#745] opened 2016-10-27 23:39 UTC
When using KLU2 in Amesos2 in sequential mode, i.e.,
  -- allocate matrix;
  -- perform symbolic factorization once;
  -- update matrix values and rerun numeric factorization repeatedly;
there is a memory leak that appears linear in size with respect to the number of numeric factorizations.

Discussed with @hkthorn , who is currently helping the @trilinos/amesos2 team sort out other issues.  Heidi will take a look at it.

**Comment by hkthorn** [comment] 2016-10-31 16:57
@trilinos/amesos2 @dridzal @srajama1  The issue is when symbolic or numeric factorization is called multiple time on a single solver object.  The use of raw pointers means that previous symbolic and numeric factorization objects need to be cleaned up before generating a new one.  That is not happening, thus the memory leak.  This was the reason for the use of RCPs in Amesos' KLU interface and the use of the deallocation functors provided by RCPs.  Raw pointers seem to be preferred in the KLU2 interface, so I will add a check in the symbolic and numeric factorization to check if one already exists and then delete it before creating a new one.

**Comment by dridzal** [comment] 2016-11-01 16:36
@hkthorn @srajama1 @trilinos/amesos2  I accidentally pushed a partial fix by @hkthorn as part of the commit e4a5fc .  It has not been tested thoroughly, but it seems to work.  @hkthorn will complete the changes to the fix and run the tests.

**Comment by hkthorn** [comment] 2016-11-01 17:31
@trilinos/amesos2 @srajama1 These essentially the changes I had locally, save for a comment on why there is a call to destroy the symbolic and numeric factorization data structures (if they are non-null) before calling KLU2 to create them again.  It's probably self-explanatory, so I will leave it for now.

**Comment by hkthorn** [comment] 2016-11-02 16:28
This has been fixed by @dridzal and verified in a ROL application.

**Closed by hkthorn** 2016-11-02 16:28 UTC
Labels: Amesos2, bug
