### ISSUE TITLE
Zoltan2 tests failing on ATDM waterman builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3331] opened 2018-08-21 20:56 UTC
CC: @trilinos/zoltan2 , @kddevin  (Trilinos Data Services Product Lead), @bartlettroscoe 
 
## Description

As shown in [this query](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman-&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=testname&compare4=65&value4=Zoltan2) the tests:

* Zoltan2_teuchosSubcommTest_MPI_4 
* Zoltan2_TaskMappingProblemTest_MPI_4

are failing in the builds:

* Trilinos-atdm-waterman-gnu-opt-openmp
* Trilinos-atdm-waterman-gnu-debug-openmp
* Trilinos-atdm-waterman-cuda-9.2-opt
* Trilinos-atdm-waterman-cuda-9.2-debug

Zoltan2_teuchosSubcommTest_MPI_4 is timing out and here is some of the output:
```
[1534830586.894337] [waterman1:47105:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240)
```

Zoltan2_TaskMappingProblemTest_MPI_4 output:
```
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 3 with PID 0 on node waterman8 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

## Steps to Reproduce

One should be able to reproduce this failure on the machine <supported-atdm-machine> as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:

```

$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-debug

$ cmake \
  -GNinja \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON \
  -DTrilinos_ENABLE_Zoltan2=ON \
  $TRILINOS_DIR

$ make NP=20

$ bsub -x -Is -n 20 ctest -j20
```

**Comment by kddevin** [comment] 2018-08-24 00:12
OK, I'm stumped.  @trilinos/zoltan2 @crtrott  @mhoemmen  Anyone have ideas?  Thanks.

The Zoltan2_TaskMappingProblemTest above is segfaulting in an MPI_Allreduce.  

 2 0x0000000000074564 mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/util/debug/debug.c:641
 3 0x0000000000074ca4 mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/util/debug/debug.c:616
 4 0x000000000000ea3c do_lookup_x()  dl-lookup.c:0
 5 0x000000000021a104 hmca_bcol_ucx_p2p_sra_progress()  ??:0
 6 0x000000000021af7c hmca_bcol_ucx_p2p_sra_init()  ??:0
 7 0x0000000000088188 hmca_coll_ml_allreduce()  ??:0
 8 0x0000000000009c28 mca_coll_hcoll_allreduce()  ??:0
 9 0x000000000008e56c MPI_Allreduce()  ??:0
...

I checked the arguments to the Allreduce; before I call the Allreduce, I can print the entire arrays being passed to it and everything looks good.  I ran the code on my linux workstation under valgrind; no memory errors were reported.

The segfaulting Allreduce is MPI_SUM of arrays with 512 doubles.  The arrays are double *.  The error happens whether I use Teuchos::reduceAll with a Teuchos::Comm or MPI_Allreduce with MPI_COMM_WORLD.

The exact same Allreduce works correctly earlier in the code when the array sizes are 4 doubles instead of 512 doubles.

BTW:  I will disable the Zoltan2_teuchosSubcommTest; it actually tests Teuchos, not Zoltan2, and I don't think it is important.

Thanks for your help.

**Comment by mhoemmen** [comment] 2018-08-24 22:29
@kddevin This could be one of those known issues relating to using the wrong `MPI_Datatype` with long array results in an `MPI_Allreduce`.  Are you calling `Teuchos::reduceAll` or using `MPI_Allreduce` directly?

**Comment by kddevin** [comment] 2018-08-24 22:57
@mhoemmen I see the same behavior regardless of whether I call Teuchos::reduceAll or MPI_Allreduce directly.

**Comment by kddevin** [comment] 2018-08-24 23:36
I have a small standalone test failing now -- yea!  Stay tuned.

**Comment by kddevin** [comment] 2018-08-25 00:36
This issue appears to be a problem with Teuchos::Comm::duplicate().
I will add tests demonstrating the problem.  Stay tuned.

**Comment by kddevin** [comment] 2018-08-25 04:35
These failing tests are caused by issues in Teuchos::Comm.  See #3355.
This issue is blocked until #3355 is fixed.
Branch fix3331 contains tests for reproducing the problem on waterman.

**Comment by kddevin** [comment] 2018-08-25 04:39
@fryeguy52 thanks for the simple instructions for building on waterman.

**Comment by mhoemmen** [comment] 2018-08-25 19:16
@kddevin Thanks for the tests!  I made a PR, #3356, from your fix3331 branch.

**Comment by bartlettroscoe** [comment] 2018-08-27 21:09
FYI: @nmhamster informed us today that OpenMPI 3.1.0 does not work correctly on 'waterman' and we should be using the build env with OpenMPI '2.1.2' instead.  I will give that env a try.  Perhaps it will fix this issue.

While this test is still failing, we can't close the issue.  We can either disable the test for this build or resolve it some other way.  But we can't just close the issue until the failing test is addressed.  Does that make sense?

**Comment by kddevin** [comment] 2018-08-28 16:10
#3363 shows Zoltan2 is OK.
To help identify the true problem, I added new Teuchos tests #3356 that exercise the Teuchos::Comm.

**Closed by kddevin** 2018-08-28 16:10 UTC
Labels: ATDM, Teuchos, Zoltan2, bug

**Comment by bartlettroscoe** [comment] 2018-08-28 18:05
After the merge of PR #3363 last night, these Zoltan2 tests are no longer failing in any of the 4 'waterman' builds as shown [here](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&date=2018-08-28&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-waterman&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun).

**Comment by bartlettroscoe** [comment] 2018-11-13 23:36
FYI: I added a new label "ATDM Env Issue" and applied it to this issue.  This should help keep track of issues caused by problems/changes in the env and not Trilinos code issues.
