### ISSUE TITLE
Tpetra with IBM XL 16.1.0/CUDA 9.2.88 Build Error (Virtual Base Class and Delegating Constructor)

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#3296] opened 2018-08-14 16:59 UTC
@mhoemmen / @bartlettroscoe 

Building Trillinos on Ride with IBM XL 16.1.0 and CUDA 9.2.88 and a prototype for SPARC.

Getting the following error (see below). I am assuming this is a limitation in XL we need to get fixed?

```
[ 26%] Building CXX object packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_CrsGraph_CudaWrapperNode.cpp.o
/ascldap/users/sdhammo/git/trilinos-sparc-gitlab-repo/packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp:652:1: error:
      1540-2206 Class with virtual base class and delegating constructor is not supported.
CrsGraph< LocalOrdinal, GlobalOrdinal, Node> ::CrsGraph(const Teuchos::RCP< const Map< LocalOrdinal, GlobalO...
^
1 error generated.
Error while processing /tmp/tmpxft_0001f5b0_00000000-5_Tpetra_CrsGraph_CudaWrapperNode.cudafe1.cpp.
make[2]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/Tpetra_CrsGraph_CudaWrapperNode.cpp.o] Error 1
make[1]: *** [packages/tpetra/core/src/CMakeFiles/tpetra.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mhoemmen** [comment] 2018-08-14 17:12
*sigh* I think I've seen this before with XL.  There's a work-around, but I really would like them to try to implement C++11 correctly.

**Comment by hubert-reinterpretcast** [comment] 2018-08-14 20:30
This appears to be a duplicate of #2938.

**Comment by mhoemmen** [comment] 2018-08-15 15:36
@hubert-reinterpretcast Thanks for refreshing my memory :)  I'll close this issue in favor of #2938.

**Closed by mhoemmen** 2018-08-15 15:36 UTC
Labels: Tpetra, bug
