### ISSUE TITLE
Belos: Belos Tests failing randomly on ATDM cuda 10 build on ride

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5224] opened 2019-05-22 17:01 UTC
## Bug Report
CC: @trilinos/belos, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 There are seemingly random test failures in the belos package on the cuda 10 ride build.
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Belos&field3=status&compare3=61&value3=Failed&field4=buildstarttime&compare4=84&value4=2019-05-21T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-05-01T00%3A00%3A00) the tests:
* Belos_bl_pgmres_hb_0_MPI_4 
* Belos_bl_pgmres_hb_2_MPI_4
* Belos_gcrodr_hb_MPI_4 
* Belos_pseudo_gmres_hb_MPI_4

have failed at least once in the last 3 weeks in the build:
* Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug

The tests area all failing in the same way:
```
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 3 with PID 0 on node white35 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

## Current Status on CDash

The current status of the belos test suite on this build can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Belos&field3=buildstarttime&compare3=84&value3=today&field4=buildstarttime&compare4=83&value4=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Belos=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by srajama1** [comment] 2019-05-23 19:23
Isn't this unstable for lot of other packages too ?

**Comment by bartlettroscoe** [comment] 2019-05-23 19:29
@srajama1 asked:

> Isn't this unstable for lot of other packages too ?

Yes there is a lot of randomness, but if you look at [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=status&compare2=62&value2=passed&field3=status&compare3=62&value3=notrun&field4=buildstarttime&compare4=83&value4=2019-05-05) there a smaller subset of packages and a smaller subset of tests in those packages that are showing random failures.  We are only seeing failures in Anasazi, Belos, MueLu, NOX, Teko, and Tempus; and only a small subset of tests in those packages are failing.  What is the common thread between these tests?

So the failures are not completely random.

**Comment by bartlettroscoe** [comment] 2019-06-04 15:18
Looks like the test `Stratimikos_test_single_belos_thyra_solver_driver_nos5_kl190_MPI_1` shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=80070291&build=5125032) on 2019-06-03 also failed due to this issue showing:

```
[white35:47846:0:47846] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x3ffef2000030)
==== backtrace ====
    0  /home/projects/ppc64le-pwr8-nvidia/ucx/1.5.1/cuda/10.1.105/lib/libucs.so.0(+0x24b40) [0x3ffeff6b4b40]
    1  /home/projects/ppc64le-pwr8-nvidia/ucx/1.5.1/cuda/10.1.105/lib/libucs.so.0(+0x24e84) [0x3ffeff6b4e84]
```

**Comment by bartlettroscoe** [comment] 2019-06-05 00:13
FYI: As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=61&value2=Belos_gcrodr_hb_MPI_4&field3=site&compare3=61&value3=white&field4=buildstarttime&compare4=84&value4=2019-06-04T04%3A01%3A00UTC&field5=buildstarttime&compare5=83&value5=2019-05-05T04%3A01%3A00UTC) the test `Belos_gcrodr_hb_MPI_4` has passed every day in the last 30 days since setting the env var `UCX_MEMTYPE_CACHE=n`.

Therefore, I will remove this from the list of tests with issue trackers for our driver script for cdash_analyze_and_report.py.

**Comment by bartlettroscoe** [comment] 2019-08-14 18:24
Closing as duplicate of #5713

**Closed by bartlettroscoe** 2019-08-14 18:24 UTC
Labels: ATDM Env Issue, ATDM Sev: Blocker, PA: Linear Solvers, client: ATDM, pkg: Belos, resolved: duplicate, type: bug
