### ISSUE TITLE
Belos:  Using the Belos::BlockGmresSolMgr to solve complex matrix equations, the explicit residuals do not converge

### ISSUE THREAD

**Issue by lixiangliang** [trilinos/Trilinos#10065] opened 2022-01-06 06:14 UTC
## Question
@trilinos/\<Belos\>

I try to use Belos to solve a simple complex matrix equation A*X=B. Matrix A is a 14th-order complex matrix with all zero imaginary parts. Matrix B on the right hand side of the equation is a complex matrix with 14 rows and 2 columns. I wrote a custom "Tpetra::Operator" subclass to implement the A*X multiplication operation. Set the parameter "Block Size" to the number of columns of matrix B to achieve simultaneous solution.

In the actual test, it is found that when all the imaginary parts of the complex matrix are all zero, the explicit residual and the implicit residual will converge at the same time, but when the imaginary part of the complex matrix B is set to a number that is not zero, such as All are set to 1. When solving, it is found that only the implicit residual converges but the explicit residual does not, and the explicit residual does not decrease with the increase of the number of iteration steps.

Why does this happen? Can you give me some tips for improvement? thanks.

A_matrix：（RowMajor）
(1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (1,0)  (1,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (1,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (1,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (1,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (9,0)  (1,0)   (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (9,0)  (10,0)  (1,0)   (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (9,0)  (10,0)  (11,0)  (1,0)   (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (9,0)  (10,0)  (11,0)  (12,0)  (1,0)   (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (9,0)  (10,0)  (11,0)  (12,0)  (13,0)  (1,0)  
(1,0)  (2,0)  (3,0)  (4,0)  (5,0)  (6,0)  (7,0)  (8,0)  (9,0)  (10,0)  (11,0)  (12,0)  (13,0)  (14,0)  
B_：（ColMajor）
(0,1)  (1,1)  (2,1)  (3,1)  (4,1)  (5,1)  (6,1)  (7,1)  (8,1)  (9,1)  (10,1)  (11,1)  (12,1)  (13,1)  
(1,1)  (2,1)  (3,1)  (4,1)  (5,1)  (6,1)  (7,1)  (8,1)  (9,1)  (10,1)  (11,1)  (12,1)  (13,1)  (14,1)

**Comment by cgcgcg** [comment] 2022-01-06 18:03
@trilinos/belos

**Comment by cgcgcg** [comment] 2022-01-06 18:12
@lixiangliang Can you check if the obtained solution is actually correct? Both in the case when imaginary(B) = 0 and when it's not zero?

**Comment by jhux2** [comment] 2022-01-06 18:34
Shouldn't Belos handle this via templating, i.e., without the need for a custom operator?

**Comment by cgcgcg** [comment] 2022-01-06 18:37
Belos templated on a Tpetra operator definitely should.

**Comment by jhux2** [comment] 2022-01-06 18:42
@lixiangliang In addition to @cgcgcg's recommendations, I'd suggest checking convergence with a single RHS.

**Comment by jennloe** [comment] 2022-01-06 19:05
I've run this example in Matlab with the two right-hand sides separately.  The implicit and explicit residuals don't diverge in this case.  They shouldn't diverge in Belos, either.  

That said, the solver doesn't converge in either the implicit or explicit residuals until the 14th iteration.

Can you give us a printout of the Belos output?

**Comment by lixiangliang** [comment] 2022-01-07 02:05
> @lixiangliang Can you check if the obtained solution is actually correct? Both in the case when imaginary(B) = 0 and when it's not zero?

**Comment by lixiangliang** [comment] 2022-01-07 02:14
> @lixiangliang Can you check if the obtained solution is actually correct? Both in the case when imaginary(B) = 0 and when it's not zero?

Thank you for your reply. 
I have checked that when the imaginary part of the B matrix is zero, the solution is correct. But when the imaginary part is not zero, the result is wrong.

**Comment by lixiangliang** [comment] 2022-01-07 02:17
> Belos templated on a Tpetra operator definitely should be enough.

This is because I am now testing the feasibility of the Belos solver. When solving my actual problems, I have to customize operators.

**Comment by lixiangliang** [comment] 2022-01-07 02:22
> @lixiangliang In addition to @cgcgcg's recommendations, I'd suggest checking convergence with a single RHS.

Set "Block Size" = 1, and only solve one right-hand side vector each time, and the result is convergent. And if the solver is changed to "Belos::PseudoBlockGmresSolMgr", the calculation result is also convergent.

**Comment by cgcgcg** [comment] 2022-01-07 02:57
Are you using a custom MultiVector implementation as well, or is that standard. Cause inner products, norms, etc come from the MultiVectorTraits. Maybe we somewhere are using the wrong kind of transpose?

**Comment by lixiangliang** [comment] 2022-01-07 03:45
[Solver.zip](https://github.com/trilinos/Trilinos/files/7826190/Solver.zip)
@cgcgcg I am attaching my code, you can browse to see if there are any errors in use, thank you very much.

**Comment by lixiangliang** [comment] 2022-01-07 03:50
> I've run this example in Matlab with the two right-hand sides separately. The implicit and explicit residuals don't diverge in this case. They shouldn't diverge in Belos, either.
> 
> That said, the solver doesn't converge in either the implicit or explicit residuals until the 14th iteration.
> 
> Can you give us a printout of the Belos output?

@jennloe Below is the print information I generated, thank you.
`*******************************************************
***** Belos Iterative Solver:  Block Gmres 
***** Maximum Iterations: 100
***** Block Size: 2
***** Residual Test: 
*****   Test 1 : Belos::StatusTestImpResNorm<>: (2-Norm Res Vec) / (2-Norm Prec Res0), tol = 0.001
*******************************************************
Iter   0, [  1] :    1.000000e+00
            [  2] :    1.000000e+00
		  
resvector_explicit[0] = 0.207194 //explicit residuals printed by myself
resvector_explicit[1] = 0.179263	
resvector_implicit[0] = 0.18653	 //implicit residuals printed by myself
resvector_implicit[1] = 0.17632
Iter   1, [  1] :    1.865297e-01
            [  2] :    1.763205e-01
		  
resvector_explicit[0] = 0.10342
resvector_explicit[1] = 0.108174
resvector_implicit[0] = 0.0771013
resvector_implicit[1] = 0.0781182
Iter   2, [  1] :    7.710131e-02
            [  2] :    7.811815e-02
	
resvector_explicit[0] = 0.106946
resvector_explicit[1] = 0.0980552
resvector_implicit[0] = 0.0426799
resvector_implicit[1] = 0.0431368
Iter   3, [  1] :    4.267989e-02
            [  2] :    4.313675e-02
		  
resvector_explicit[0] = 0.259759
resvector_explicit[1] = 0.244193
resvector_implicit[0] = 0.0177319
resvector_implicit[1] = 0.018062
Iter   4, [  1] :    1.773193e-02
            [  2] :    1.806198e-02
		  
resvector_explicit[0] = 0.264829
resvector_explicit[1] = 0.248429
resvector_implicit[0] = 0.00318504
resvector_implicit[1] = 0.00326891
Iter   5, [  1] :    3.185043e-03
            [  2] :    3.268905e-03
		  
resvector_explicit[0] = 0.264449
resvector_explicit[1] = 0.248048
resvector_implicit[0] = 0.000414805
resvector_implicit[1] = 0.000428049
Iter   6, [  1] :    4.148046e-04
            [  2] :    4.280490e-04
Belos::BlockGmresSolMgr::solve(): Warning! Solver has experienced a loss of accuracy!
Passed.......OR Combination -> 
  OK...........Number of Iterations = 6 < 100
  Converged....(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.000414805 < 0.001
               residual [ 1 ] = 0.000428049 < 0.001`

**Comment by cgcgcg** [comment] 2022-01-07 05:14
Maybe print the value of `Teuchos::ETransp mode` in your `apply` method to check whether it's always the same. As far as I can tell, you always do a non-transpose apply. If you see different values of `mode`, then that might be the issue.

**Comment by lixiangliang** [comment] 2022-01-07 09:11
> Maybe print the value of `Teuchos::ETransp mode` in your `apply` method to check whether it's always the same. As far as I can tell, you always do a non-transpose apply. If you see different values of `mode`, then that might be the issue.

@cgcgcg After testing, "Teuchos::ETransp mode" is always "NO TRANS", which may not be caused by transpose. Maybe it's because of my wrong use of the solver "BlockGmresSolMgr"? If you can, please take a look at my code to see if there are any errors in use. Thank you so much.

**Comment by cgcgcg** [comment] 2022-01-07 18:08
@jennloe When I try running one of the Belos tests in a complex build:
```
./Belos_bl_gmres_complex_hb.exe --verbose --num-rhs=2 --blocksize=2
```
it fails as well. Would that be expected behavior, or would that be good for a reproducer?

**Comment by jennloe** [comment] 2022-01-07 21:23
@cgcgcg That shouldn't be failing.  Probably qualifies as a good reproducer.
@hkthorn was wondering if there are problems with losing orthogonality in the subspace, but that seems less likely if the `./Belos_bl_gmres_complex_hb.exe` is failing also.  That test uses random rhs vectors, right?

**Comment by jennloe** [comment] 2022-01-07 21:31
@cgcgcg  In what way is this failing?  For the two right-hand sides individually, you really do need 14 iterations to converge.  See plot below from Matlab.  

<img width="496" alt="image" src="https://user-images.githubusercontent.com/28164775/148609979-0941713e-7c4a-4b38-84ef-82f0c136b677.png">


However, I'm running this matrix and one right-hand side in Belos with Kokkos backend, and it is not converging because the solver stops after 13 iterations... Let me tweak the GMRES subspace size and see what happens.  Also, I'll see if I can make it run with both right-hand sides.

<pre>
Dimension of matrix: 14
Number of right-hand sides: 1
Max number of Gmres iterations: 13
Relative residual tolerance: 1e-05

Belos::BlockGmresSolMgr::solve():  Warning! Requested Krylov subspace dimension is larger than operator dimension!
 The maximum number of blocks allowed for the Krylov subspace will be adjusted to 14

Belos::StatusTestGeneralOutput: Failed
  (Num calls,Mod test,State test): (1, 25, Passed Failed Undefined)
   Failed.......OR Combination -> 
     OK...........Number of Iterations = 0 < 13
     Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
                  residual [ 0 ] = 1 > 1e-05

Passed.......OR Combination -> 
  Failed.......Number of Iterations = 13 == 13
  Unconverged..(2-Norm Res Vec) / (2-Norm Prec Res0)
               residual [ 0 ] = 0.000341372 > 1e-05

================================================================================

                      TimeMonitor results over 1 processor

Timer Name                                  Global time (num calls)    
--------------------------------------------------------------------------------
Belos: BlockGmresSolMgr total solve time    0.1665 (1)                 
Belos: ICGS[2]: Ortho (Inner Product)       0.002738 (26)              
Belos: ICGS[2]: Ortho (Norm)                0.001336 (14)              
Belos: ICGS[2]: Ortho (Update)              0.1613 (26)                
Belos: ICGS[2]: Orthogonalization           0.1657 (14)                
Belos: Operation Op*x                       0.000315 (14)              
Belos: Operation Prec*x                     0 (0)                      
================================================================================
---------- Actual Residuals (normalized) ----------

Problem 0 :     0.000341372

ERROR:  Belos did not converge!
</pre>

**Comment by lixiangliang** [comment] 2022-01-08 07:17
> @jennloe When I try running one of the Belos tests in a complex build:
> 
> ```
> ./Belos_bl_gmres_complex_hb.exe --verbose --num-rhs=2 --blocksize=2
> ```
> 
> it fails as well. Would that be expected behavior, or would that be good for a reproducer?

@cgcgcg @jennloe Yes, I ran this test case a bit too. In the output information, it is found that there is such a `Belos::BlockGmresSolMgr::solve(): Warning! Solver has experienced a loss of accuracy!`, and the reason for this `warning` should be that the implicit residuals converged but the explicit residuals did not converge. This is the same problem with my own test program.

**Comment by cgcgcg** [comment] 2022-01-22 00:27
@jennloe Could this be an issue with complex and multiple RHS? In what way do the BLAS calls change compared to a single RHS? Maybe some complex transpose isn't hooked up correctly somewhere?

**Comment by dridzal** [comment] 2022-01-22 00:32
@cgcgcg : @hkthorn has narrowed down the issue to the Householder transform that is used to solve the least-squares system for block RHS.

**Comment by cgcgcg** [comment] 2022-01-22 00:34
Nice, thanks for the update!

**Comment by hkthorn** [comment] 2022-02-01 17:42
@lixiangliang Sorry for the delay.  I have found the issue in the block Gmres solver, within the Householder transformation, and it has been fixed in a PR.  Thanks for reporting this and your patience!

**Comment by lixiangliang** [comment] 2022-02-14 07:47
> 

@hkthorn Thank you for your fix, but after my test, I found that the calculation efficiency is very low. The calculation time of the same equation using `BlockGmres `is much slower than that of `PseudoBlockGmres`, which I cannot understand.

**Comment by hkthorn** [comment] 2022-02-14 16:18
@lixiangliang That's very interesting, thanks for the response.  Block iterative methods are not guaranteed to be more effective than the pseudo-block solvers, it depends on the right-hand side vectors.

**Closed** 2023-03-18 12:27 UTC
Labels: type: question, pkg: Belos, MARKED_FOR_CLOSURE, CLOSED_DUE_TO_INACTIVITY
