### ISSUE TITLE
TrilinosInstallTests Failing in PR

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#10896] opened 2022-08-17 15:43 UTC
These guys:

- TrilinosInstallTests_doInstall
- TrilinosInstallTests_find_package_Trilinos
- TrilinosInstallTests_simpleBuildAgainstTrilinos

See example:
https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=392610

**Comment by bartlettroscoe** [comment] 2022-08-17 15:51
@csiefer2, I will try to reproduce and update the doInstall test to show the tail of the install command to see what is failing.  (Can't show the entire STDOUT since that is over 1 MB in size.)

**Comment by bartlettroscoe** [comment] 2022-08-17 15:56
> Awesome, thanks. That same build has Zoltan2Sphynx dying like this:
> 
> ninja: error: '/usr/lib64/liblapack.so', needed by 'packages/teuchos/numerics/src/libteuchosnumerics.so.13.5', missing and no known rule to make it

Well that is why then the install is failing.  If the build does not work, the install will fail as well  (because the install target is dependent on all of the output targets).  But it would still be nice to update the doInstall test to show at least some of those errors (and to warn users that if the build fails, these tests will fail as well).

> So I'm wondering if something system-related happened like the disk filling up again....

No.  Do a search of the GitHub issues (e.g. "ninja: error: '/usr/lib64/liblapack.so'") and you will see why.  I just reported this this morning.  (If you are no sure how to search github issues, I can provide some tips)

**Comment by csiefer2** [comment] 2022-08-17 15:58
@bartlettroscoe The install is failing on another build as well which doesn't have any build failures

https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-10827-test&field2=buildstarttime&compare2=84&value2=NOW

**Comment by csiefer2** [comment] 2022-08-17 15:59
Although it is on one of the cursed machines...

**Comment by bartlettroscoe** [comment] 2022-08-17 16:03
> @bartlettroscoe The install is failing on another build as well which doesn't have any build failures

@csiefer2, no, those clang-10.0.0  builds on the 'ascic0xy' machines also have the same build failures (because system BLAS and LAPACK are not being installed), they are just not being reported to CDash.  See explanation in https://github.com/trilinos/Trilinos/issues/10893#issuecomment-1218138724.

If we could pull the trigger on upgrading the min CMake version (i.e. the issue #10355 open since March), this you would see those build errors.  But we can't upgrade CMake until all of the PR chaos calms down. (Or maybe we should just pull the trigger on upgrading the min CMake version everywhere?)

**Comment by csiefer2** [comment] 2022-08-17 16:04
@bartlettroscoe Glad to see you're on top of this!

**Comment by bartlettroscoe** [comment] 2022-08-17 16:07
> @bartlettroscoe Glad to see you're on top of this!

@csiefer2, I want my PRs to get merged too.  And if I can help other Trilinos developers in the process, win-win.  Just put in a good word :-)

**Comment by jhux2** [comment] 2022-08-17 16:32
> But we can't upgrade CMake until all of the PR chaos calms down. (Or maybe we should just pull the trigger on upgrading the min CMake version everywhere?)

I vote for upgrading!

**Comment by csiefer2** [comment] 2022-08-17 16:35
Does SEMS provide whatever version of cmake we need?  If so, then I have no objection to bumping the cmake version.

**Comment by GrahamBenHarper** [comment] 2022-08-17 16:39
I believe so. The highest cmake I see on my SEMS machine is `sems-cmake/3.23.1      (D)`

**Comment by bartlettroscoe** [comment] 2022-08-18 02:39
@csiefer2, to try to avoid this type of confusion in the future, I have attempted to improve these tests to make it more clear what is happening when there is a build error.  Please see the PR #10897.  You just need to look at the top and click on a few CDash links.  It should not take more than 5 mins.

Hopefully this will save future developers the trouble of filing issues when they see these.

**Comment by bartlettroscoe** [comment] 2022-08-18 02:42
> Does SEMS provide whatever version of cmake we need? If so, then I have no objection to bumping the cmake version.

@GrahamBenHarper, @csiefer2, @jhux2, please see comment on status of readiness to upgrade minimum CMake version for Trilinos in https://github.com/trilinos/Trilinos/issues/10355#issuecomment-1218259912.

**Comment by jhux2** [comment] 2022-08-18 16:54
```
weaver: cmake/3.23.1
cee-build031: sems-cmake/3.19.1
vortex: cmake/3.23.1
```

@GrahamBenHarper I just do a `module load sems-env`, correct?

**Comment by GrahamBenHarper** [comment] 2022-08-18 17:28
@jhux2 I don't think I have access to cee-build machines for some reason. I'm looking at cee-compute, and you're right. The latest version of cmake I can find is `sems-cmake/3.19.1`... The latest cmake I see under the sierra modules is `sierra-cmake/3.20.0`, but sparc has a `sparc-cmake/3.23.2`. That sounds like a mild problem.

**Closed** 2023-09-20 12:27 UTC
Labels: type: bug, stage: in review, MARKED_FOR_CLOSURE, CLOSED_DUE_TO_INACTIVITY, autotester
