### ISSUE TITLE
Amesos2 build errors when enabling MKL/Pardiso

### ISSUE THREAD

**Issue by crdohrm** [trilinos/Trilinos#4458] opened 2019-02-21 14:11 UTC
I would like the enable Amesos with MKL/Pardiso, but run into build errors like

[ 97%] Building CXX object packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_PardisoMKL.cpp.o
In file included from /ascldap/users/crdohrm/Trilinos.fork/packages/amesos2/src/Amesos2_PardisoMKL_FunctionMap.hpp(64),
                 from /ascldap/users/crdohrm/Trilinos.fork/packages/amesos2/src/Amesos2_PardisoMKL_decl.hpp(65),
                 from /ascldap/users/crdohrm/Trilinos.fork/packages/amesos2/src/Amesos2_PardisoMKL.cpp(45):
/ascldap/users/crdohrm/Trilinos.fork/packages/amesos2/src/Amesos2_PardisoMKL_TypeMap.hpp(93): error: namespace "Amesos2::PMKL" has no member "_MKL_Complex8"
    class ValueTypeConversionTraits<Amesos2::PMKL::_MKL_Complex8, TypeFrom>

Also, the build works fine if I enable Amesos rather than Amesos2.

@trilinos/amesos2

## Additional Information
Here's the configuration used

#!/bin/bash

TRILINOSHOME=/home/crdohrm/Trilinos.fork
TRILINOSINSTALLDIR=/home/crdohrm/Trilinos.fork/INSTALL_RELEASE_INTEL
BUILDTYPE=release
MKLROOT=/projects/sierra/linux_rh6/SDK/compilers/intel/composer_xe_2017.1.132/compilers_and_libraries/linux/mkl

rm -f CMakeCache.txt
rm -rf CMakeFiles

cmake \
    -D Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
    -D CMAKE_INSTALL_PREFIX:PATH=${TRILINOSINSTALLDIR} \
    -D CMAKE_BUILD_TYPE:STRING=${BUILDTYPE} \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D BUILD_SHARED_LIBS:BOOL=OFF \
    -D Teuchos_ENABLE_STACKTRACE:BOOL=ON \
    -D Trilinos_ENABLE_Fortran:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF \
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    -D TPL_ENABLE_MKL:BOOL=ON \
    -D TPL_ENABLE_PARDISO_MKL:BOOL=ON \
    -D Trilinos_EXTRA_LINK_FLAGS:STRING="-Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_blacs_openmpi_lp64.a -Wl,--end-group -lpthread -lm -ldl" \
    -D MKL_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
    -D MKL_INCLUDE_DIRS:FILEPATH="${MKLROOT}/include" \
    -D TPL_BLAS_LIBRARIES:STRING="${MKLROOT}/lib/intel64/libmkl_blas95_lp64.a" \
    -D TPL_LAPACK_LIBRARIES:STRING="${MKLROOT}/lib/intel64/libmkl_lapack95_lp64.a" \
    -D PARDISO_MKL_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
    -D PARDISO_MKL_INCLUDE_DIRS:FILEPATH="${MKLROOT}/include" \
    \
    \
    ${TRILINOSHOME}

**Comment by srajama1** [comment] 2019-02-21 21:19
@crdohrm This is a strange error. _MKL_Complex8 is define in the mkl_types.h. I just checked the header and it is there in both 17 and 18 versions. This is not a MKL versioning issue. Can you confirm this in your installation of MKL in ${MKLROOT}/include/mkl_types.h.

You won't see this in Amesos because it doesn't use the complex version. Amesos2 we enabled both double and complex as they are always there.

**Comment by crdohrm** [comment] 2019-02-21 21:34
Yes, I can confirm that _MKL_Complex8 is defined in ${MKLROOT}/include/mkl_types.h.

The error message above says

namespace "Amesos2::PMKL" has no member "_MKL_Complex8"

Is the problem that _MKL_Complex8 is not in the Amesos2::PMKL namespace?

**Comment by srajama1** [comment] 2019-02-22 15:22
Actually we include mkl_types.h in the namespace Amesos2::PMKL, that is how why this has been working. We do this so there is no name conflicts between two solves (say SuperLU* variations). What is the compiler and its version here ?

**Comment by crdohrm** [comment] 2019-02-22 15:57
Currently Loaded Modulefiles:
  1) sntools/master
  2) sierra-python/2.7
  3) sierra-git/2.6.1
  4) sierra-cmake/3.12.2
  5) sierra-mkl/17.0-2017.2.174
  6) sierra-compiler/intel/17.0-2017.2.174
  7) sierra-mpi/openmpi/1.10.2
  8) sierra-devel/intel-17.0.2-openmpi-1.10.2

**Comment by srajama1** [comment] 2019-02-22 17:59
@ndellingwood As I know you are working with TPLs for another amesos2 issue, can you add this compiler combination to your testing. If you are tied up in other things I will come to this in the weekend.

**Comment by ndellingwood** [comment] 2019-02-22 20:02
@srajama1 I won't be able to get to it today, I can try and get this resolved by early next week if that is okay once I've got the other issue under control.

**Comment by srajama1** [comment] 2019-02-22 21:36
@ndellingwood : I will try to reproduce in the weekend. Today is taken with other things. I will update the github issue on how far I get in the weekend.

**Comment by ndellingwood** [comment] 2019-02-22 22:00
@srajama1 sounds good, if you have a start on reproducing it we can jump right into it next week, thanks!

**Comment by ndellingwood** [comment] 2019-03-07 00:55
PR #4562 issued with fix, thanks @srajama1 for the initial footwork tracking down issue and suggesting fix.

**Comment by ndellingwood** [comment] 2019-03-07 19:29
@crdohrm PR #4562 was merged into Trilinos' develop branch with a fix. Please reopen if you encounter more issues.

**Closed by ndellingwood** 2019-03-07 19:29 UTC
Labels: build, pkg: Amesos2
