### ISSUE TITLE
Tpetra: RowMatrixTranspose has no thread parallelism

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#2236] opened 2018-02-12 19:45 UTC
Add another on to the todo list...

**Comment by mhoemmen** [comment] 2018-06-08 18:47
This is a duplicate of https://github.com/trilinos/Trilinos/issues/664 , which has more discussion, so I'm closing this issue in favor of that one.  Thanks!

**Closed by mhoemmen** 2018-06-08 18:47 UTC
Labels: Tpetra, TpetraRF
