### ISSUE TITLE
Sacado: CUDA build errors in test with RDC ON

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2891] opened 2018-06-05 22:44 UTC
@trilinos/sacado 

With a static CUDA build and with relocatable device code (RDC) enabled, I get the following build errors:
```
/tmp/tmpxft_00001079_00000000-2_Sacado_Fad_Kokkos_CommTests_Serial_dlink.reg.c: At global scope:
.../nvidia/cuda_9.0.176/bin/crt/link.stub:92:118: error: redefinition of ‘const unsigned char def_module_id_str_48_tmpxft_00007161_00000000_6_Teuchos_Utils_cpp1_ii_dbeaaeb9 []’
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
                                                                                                                      ^
/tmp/tmpxft_00001079_00000000-2_Sacado_Fad_Kokkos_CommTests_Serial_dlink.reg.c:145:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_48_tmpxft_00007161_00000000_6_Teuchos_Utils_cpp1_ii_dbeaaeb9)
 ^
```
Have y'all ever seen those?  Here are my relevant build options:
```
-D CMAKE_BUILD_TYPE=RELEASE
-D BUILD_SHARED_LIBS=OFF
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
-D Trilinos_ENABLE_OpenMP=OFF
-D TPL_ENABLE_Pthread=OFF
-D Trilinos_ENABLE_Sacado=ON
-D Trilinos_ENABLE_Stokhos=OFF
-D Kokkos_ENABLE_Serial=ON
-D Kokkos_ENABLE_OpenMP=OFF
-D Kokkos_ENABLE_Pthread=OFF
-D Kokkos_ENABLE_Cuda=ON
-D Kokkos_ENABLE_Cuda_UVM=ON
-D Kokkos_ENABLE_Cuda_Lambda=ON
-D Kokkos_ENABLE_Cuda_Relocatable_Device_Code=ON
-D TPL_ENABLE_CUDA=ON
-D KOKKOS_ARCH="Pascal60"
```
I'm using CUDA 9.0.176, GCC 4.9.3, OpenMPI 1.10.2, and CMake 3.8.2.

Sierra (in particular, Aria) needs RDC to work.

**Comment by mhoemmen** [comment] 2018-06-05 22:51
FYI, this is in a test.  Sacado builds fine with tests disabled, so this might not be a blocker for Sierra.

**Comment by mhoemmen** [comment] 2018-06-05 23:49
@nmhamster @crtrott @ibaned y'all ever see errors like this?

**Comment by rppawlo** [comment] 2018-06-06 12:16
Haven't seen that exact error, but we had to ifdef a different code path in sacado before for RDC.
https://github.com/trilinos/Trilinos/pull/1944

**Comment by ibaned** [comment] 2018-06-06 14:32
Anything that defines symbols twice will work with the GNU linker but fail with NVIDIA's linker. I expect we'll find many of these along the way.

**Comment by etphipp** [comment] 2018-06-06 14:39
Looking at the compiler error, that appears to be some internal NVIDIA linker/compiler symbol:
```
static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
```
There is no "static const unsigned char" in all of Sacado.

**Comment by etphipp** [comment] 2018-06-06 14:40
What Cuda version and machine is this from?

**Comment by etphipp** [comment] 2018-06-06 14:43
Never mind, I see that it is Cuda 9.

**Comment by etphipp** [comment] 2018-06-06 14:58
It also may have something to do with Teuchos_Utils.cpp:
```
error: redefinition of ‘const unsigned char def_module_id_str_48_tmpxft_00007161_00000000_6_Teuchos_Utils_cpp1_ii_dbeaaeb9 []’
```
Looking in that file, there is a static symbol `static double Teuchos::Utils::chopVal_`, but it seems to be initialized properly in the cpp file, so I don't see what could be wrong there.  Also Sacado doesn't explicitly include Teuchos_Utils.hpp anywhere or explicitly link to that file.  It must come from somewhere else in Teuchos if that is the source of the problem.

**Comment by mhoemmen** [comment] 2018-06-06 14:59
@etphipp It's one of our CEELAN GPU machines, ascicgpuN (replace N with an appropriate number).

**Comment by etphipp** [comment] 2018-06-06 15:32
We could try changing line 111 of Teuchos_Utils.hpp to
```
static constexpr double chopVal_ = 1.0e-16;
```
and comment out line 47 of Teuchos_Utils.cpp.  I have no idea if that will fix it, or if it is even related.

**Comment by ibaned** [comment] 2018-06-06 15:36
That variable looks like its correctly defined... it may be as simple as `libteuchoscore.a` being listed twice on the link line. @mhoemmen can you check whether thats the case with `make VERBOSE=1`?

**Comment by mhoemmen** [comment] 2018-06-06 17:02
@ibaned I think you're right about `libteuchoscore.a`.  Here's the link line:
```
[ 17%] Linking CXX executable Sacado_Fad_Kokkos_CommTests_Serial.exe
cd /ascldap/users/mhoemme/prj/Trilinos/build-Trilinos/packages/sacado/test/UnitTests && /projects/sparc/tools/cee-rhel6/cmake-3.8.2/gcc-4.9.3/bin/cmake -E cmake_link_script CMakeFiles/Sacado_Fad_Kokkos_CommTests_Serial.dir/link.txt --verbose=1
/sierra/sntools/SDK/mpi/openmpi/1.10.2-nvidia-9.0.176-RHEL6/bin/mpicxx   -pedantic -Wall -Wno-long-long -Wwrite-strings   -fPIC  -I./ -I/ascldap/users/mhoemme/prj/Trilinos/Trilinos/packages/kokkos/core/src -I/ascldap/users/mhoemme/prj/Trilinos/Trilinos/packages/kokkos/containers/src -I/ascldap/users/mhoemme/prj/Trilinos/Trilinos/packages/kokkos/algorithms/src -I/ascldap/users/mhoemme/prj/Trilinos/Trilinos/packages/kokkos/core/src/eti --std=c++11 --relocatable-device-code=true -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored -expt-extended-lambda -arch=sm_60 -I/sierra/sntools/SDK/compilers/nvidia/cuda_9.0.176/include   -O3 -DNDEBUG  -rdynamic CMakeFiles/Sacado_Fad_Kokkos_CommTests_Serial.dir/Fad_Kokkos_CommTests_Serial.cpp.o  -o Sacado_Fad_Kokkos_CommTests_Serial.exe ../../src/libsacado.a ../../../teuchos/core/src/libteuchoscore.a ../../../kokkos/containers/src/libkokkoscontainers.a ../../../../liblast_lib.a ../../../teuchos/kokkoscomm/src/libteuchoskokkoscomm.a ../../../teuchos/kokkoscompat/src/libteuchoskokkoscompat.a ../../../teuchos/remainder/src/libteuchosremainder.a ../../../teuchos/numerics/src/libteuchosnumerics.a /usr/lib64/liblapack.so /usr/lib64/libblas.so ../../../teuchos/comm/src/libteuchoscomm.a ../../../teuchos/parameterlist/src/libteuchosparameterlist.a ../../../teuchos/parser/src/libteuchosparser.a ../../../teuchos/core/src/libteuchoscore.a ../../../kokkos/core/src/libkokkoscore.a /usr/lib64/libdl.so /sierra/sntools/SDK/compilers/nvidia/cuda_9.0.176/lib64/libcudart.so /sierra/sntools/SDK/compilers/nvidia/cuda_9.0.176/lib64/libcublas.so /sierra/sntools/SDK/compilers/nvidia/cuda_9.0.176/lib64/libcufft.so -lmpi -ldl -lgomp
```
When I removed the first instance of `libteuchoscore.a`, the test in question successfully linked.

**Comment by ibaned** [comment] 2018-06-06 17:31
Oh good, thats much easier to fix. I have a plan to modify `nvcc_wrapper` such that it will remove all but the last occurrence of each library, since this is something CMake itself controls internally, thats probably the easiest way we can avoid these errors.

**Comment by ibaned** [comment] 2018-06-06 18:56
I think if you use reasonable modern CMake then CMake is the one making the decision that this library shows up more than once. TriBITS might be able to carry out ugly hacks to force certain CMake behavior, but that would be a big step backwards in the way Trilinos builds and takes advantage of modern CMake (for example, exporting information in package files to users of Trilinos). Since this is just a deficiency of the NVIDIA linker, maybe a low-level NVIDIA-only workaround is more appropriate.

**Comment by mhoemmen** [comment] 2018-06-08 04:32
@ibaned FYI, if you decide to make those changes to `nvcc_wrapper`, @micahahoward would like an option _not_ to strip away extra libraries.

**Comment by ibaned** [comment] 2018-06-08 14:05
Agreed, it should be controlled by whether RDC is on or not.

**Comment by mhoemmen** [comment] 2018-06-11 15:53
@ibaned Victor (@vbrunini ) asks whether we've filed a bug with NVIDIA about their linker.  My answer was "probably yes but I'll ask Dan."

**Comment by ibaned** [comment] 2018-06-11 16:00
@crtrott and @nmhamster requested that I develop a reproducer for this bug, so I think they did submit it to NVIDIA.

**Comment by rppawlo** [comment] 2018-10-29 20:42
Has there been any progress on this issue (either with changes to nvcc_wrapper or feedback from nvidia)? There is a need for RDC in empire.

**Comment by bartlettroscoe** [comment] 2019-02-21 16:06
FYI: I will go ahead and set up some nightly "Specialized" ATDM Trilinos CUDA 9.2 RDC builds on 'white'/'ride' and 'waterman'.  If you want to get updates on this, add yourself as a watcher to  [TRIL-262](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-262).

**Comment by bartlettroscoe** [comment] 2019-02-21 21:15
FYI: Seeing lots of link failures in Sacado in ATDM Trilinos CUDA build on 'ride' shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4605510).  The first link error shown for the target `Sacado_MPLTests` shows the following link line (sorted to show duplicates):

```
"/home/projects/ppc64le-pwr8-nvidia/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88/bin/mpicxx"
"--diag_suppress=esa_on_defaulted_function_ignored"
"--relocatable-device-code=true"
"--std=c++11"
"-DNDEBUG"
"-L/home/projects/ppc64le-pwr8/netlib/3.8.0/gcc/7.2.0/lib"
"-O3"
"-Xcudafe"
"-arch=sm_37"
"-expt-extended-lambda"
"-lblas"
"-lblas"
"-ldl"
"-lgfortran"
"-lgfortran"
"-lgomp"
"-lgomp"
"-llapack"
"-lm"
"-o"
"/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/lib64/libcublas.so"
"/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/lib64/libcudart.so"
"/home/projects/ppc64le-pwr8-nvidia/cuda/9.2.88/lib64/libcufft.so"
"packages/kokkos/containers/src/libkokkoscontainers.a"
"packages/kokkos/core/src/libkokkoscore.a"
"packages/sacado/src/libsacado.a"
"packages/sacado/test/UnitTests/CMakeFiles/Sacado_MPLTests.dir/MPLTests.cpp.o"
"packages/sacado/test/UnitTests/Sacado_MPLTests.exe"
"packages/teuchos/comm/src/libteuchoscomm.a"
"packages/teuchos/core/src/libteuchoscore.a"
"packages/teuchos/core/src/libteuchoscore.a"
"packages/teuchos/kokkoscomm/src/libteuchoskokkoscomm.a"
"packages/teuchos/kokkoscompat/src/libteuchoskokkoscompat.a"
"packages/teuchos/numerics/src/libteuchosnumerics.a"
"packages/teuchos/parameterlist/src/libteuchosparameterlist.a"
"packages/teuchos/parser/src/libteuchosparser.a"
"packages/teuchos/remainder/src/libteuchosremainder.a"
```

Need to figure out how "libteuchoscore.a" is getting duplicated on the link line.  I can look at this but it will not be until after SIAM CSE19 next week.

@vbrunini, is there an Kokkos CMake configure option to get the Kokkos compiler flags to add `--remove-duplicate-link-files` to the link lines or do we have to do that manually.

**Comment by etphipp** [comment] 2019-02-21 21:38
I just had a thought.  Could it be how Sacado specifies its dependencies on Teuchos through Tribits, which currently are:
```
SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES Teuchos KokkosCore TeuchosKokkosComm)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES TeuchosCore KokkosContainers)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS ADOLC ADIC CppUnit)
```
If you configure Sacado with Teuchos enabled, could this cause libteuchoscore.a to appear twice, once from the library dependency and once from the test dependency.  Btw, I think it was done this way because the Sacado library optionally uses things from several sub-packages.  In addition some tests explicitly use the Teuchos test-harness in TeuchosCore.  But do I need to even specify the TeuchosCore dependency for the tests, since the library already depends on Teuchos?

**Comment by bartlettroscoe** [comment] 2019-02-21 22:05
@etphipp, 

This looks like it could be a TriBITS defect.  It should not put on a link libs twice in a case like this.  There must be some error in the TriBITS logic.  But this is a strange use case.  When a package is broken into subpackages, you are supposed to point to the specific subpackages you depend on (or there was not much purpose in breaking that thing into subpackages).  I will see if I can reproduce this behavior with some test code in TriBITS.

For now, can we try making Sacado point to the exact Teuchos subpackages that it needs in the lib dependencies and leave 'TeuchosCore' out of the test dependencies?   After all, it is impossible to disable Teuchos but enable TeuchosCore (see [here](https://tribits.org/doc/TribitsDevelopersGuide.html#enable-disable-of-parent-package-is-enable-disable-for-subpackages)) so this makes no sense.

**Comment by vbrunini** [comment] 2019-02-21 22:11
@bartlettroscoe I believe you have to add ```--remove-duplicate-link-files``` manually

**Comment by etphipp** [comment] 2019-02-21 22:21
I can work on that.  In fact I see this was requested a long time ago (https://github.com/trilinos/Trilinos/issues/1263), which I apparently never did (sorry!).

**Comment by bartlettroscoe** [comment] 2019-02-22 01:48
FYI: Setting the option `--remove-duplicate-link-files` seems to fix the Sacado build.  See commit 10bf75b in my topic branch.

**Comment by etphipp** [comment] 2019-03-05 14:56
PR #4546 fixed the dependencies for Sacado and I verified it eliminates the duplication of libteuchoscore.a on the link line, so I am closing this issue.

**Closed by etphipp** 2019-03-05 14:56 UTC
Labels: build, pkg: Sacado, system: gpu
