### ISSUE TITLE
ShyLU: extern BLAS function declaration breaks Sierra build

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2942] opened 2018-06-14 17:02 UTC
@mwglass reports the following build error, resulting from ShyLU exposing `extern` declarations of BLAS functions in header files, that conflict with `extern` declarations in Sierra (specifically FETI-DP):
```
In file included from .../sierra.base.trilinos/TPLs_src/Trilinos_flat_headers/include/shylu_hts.hpp:47:0,
                 from .../sierra.base.trilinos/TPLs_src/solversNGP/Npt/NptHtsInterface.hpp:5,
                 from .../sierra.base.trilinos/TPLs_src/solversNGP/Npt/SolverNpt.hpp:23,
                 from .../sierra.base.trilinos/FETI-DP/src/NPTEquationSolver.h:28,
                 from .../sierra.base.trilinos/FETI-DP/src/CoarseNPTEquationSolver.h:15,
                 from .../sierra.base.trilinos/FETI-DP/src/CoarseNPTEquationSolver.C:11:
.../sierra.base.trilinos/TPLs_src/Trilinos_flat_headers/include/shylu_hts_impl_def.hpp:112:49: error: declaration of 'void Experimental::htsimpl::sgemm_(char*, char*, Experimental::htsimpl::blas_int*, Experimental::htsimpl::blas_int*, Experimental::htsimpl::blas_int*, float*, float*, Experimental::htsimpl::blas_int*, float*, Experimental::htsimpl::blas_int*, float*, float*, Experimental::htsimpl::blas_int*)' with C language linkage [-Werror]
     float*, blas_int*, float*, float*, blas_int*);
                                                 ^
In file included from .../sierra.base.trilinos/FETI-DP/src/feti_blas.h:12:0,
                 from .../sierra.base.trilinos/FETI-DP/src/ftl_math.h:22,
                 from .../sierra.base.trilinos/FETI-DP/src/DataVector.h:18,
                 from .../sierra.base.trilinos/FETI-DP/src/CoarseNPTEquationSolver.h:14,
                 from .../sierra.base.trilinos/FETI-DP/src/CoarseNPTEquationSolver.C:11:
.../sierra.base.trilinos/FETI-DP/src/feti_blas.h:90:15: error: conflicts with previous declaration 'void feti::sgemm_(const char*, const char*, const int*, const int*, const int*, const float*, const float*, const int*, const float*, const int*, const float*, float*, const int*)' [-Werror]
void _FORTRAN(sgemm)(const char*, const char*, const int* m, const int* n, const int* k, const float* alpha, const float* A, const int* lda, const float* B, const int* ldb,
 ```

@trilinos/shylu @crdohrm 

## Expectations

Trilinos should not cause build errors in downstream libraries or applications that make `extern` declarations of BLAS, etc. functions.

## Possible Solution

Mike and I discussed this.  We decided that the best policy would be for upstream libraries, like Trilinos, never to expose any of the following to applications:

  - TPL header file includes (see e.g., #1194)
  - `extern` declarations of TPL functions (e.g., from the BLAS)

This implies hiding TPL includes and `extern` declarations in a .cpp file.  This solution would add effort to kokkos-kernels development and issues such as #1195, but it will solve all problems of this sort for all downstream libraries and applications.  It also improves encapsulation, a standard good software engineering practice.

## Related Issues
* Related to https://github.com/kokkos/kokkos-kernels/issues/244, https://github.com/kokkos/kokkos-kernels/issues/245, https://github.com/kokkos/kokkos-kernels/issues/246, https://github.com/kokkos/kokkos-kernels/issues/247, #1194, #1195

**Comment by srajama1** [comment] 2018-06-14 18:15
The primary difference in this case is the const. Is that a quick fix or is this refactor to .cpp needed ?

@ambrad : FYI

**Comment by mwglass** [comment] 2018-06-14 18:22
Adding the const would be a quick fix for this particular error but the bigger issue is the inconsistent function declarations for the LAPACK/BLAS across all of our code projects (even within the same project). So adding const may fix this error but reveal others where it would then conflict with another declaration without const.

**Comment by mhoemmen** [comment] 2018-06-14 18:28
I didn't mention above that hiding `extern` declarations may imply writing wrapper functions.  This is the approach I took when fixing #1194.  It may add run-time overhead, but BLAS implementations error-check their input arguments anyway.

**Comment by mwglass** [comment] 2018-06-14 18:37
BTW, just adding the const to the sgemm and dgemm declarations would certainly be a quick fix that would work for our Sierra/Trilinos integration.

**Comment by srajama1** [comment] 2018-06-14 18:43
@ambrad volunteered to take care of this.

@mwglass : Thanks, another level of redirection might slow things down as this is at the bottommost level. We will try to find a solution.

**Comment by ambrad** [comment] 2018-06-14 23:15
@mwglass I merged an intended fix to develop. Please let me know if you still encounter a build error.

**Comment by ambrad** [comment] 2018-06-16 02:05
I'm going to leave this issue open until the Sierra build is confirmed to be OK.

**Comment by mwglass** [comment] 2018-06-18 19:03
Yes, this fixed our Sierra/Trilinos integration issue - Thanks!

**Comment by ambrad** [comment] 2018-06-18 20:11
Thanks for the update.

**Closed by ambrad** 2018-06-18 20:11 UTC
Labels: ShyLU
