### ISSUE TITLE
SEACAS: link error "undefined reference to 'Ioss::Hex8::name'" on rzansel (LLNL)

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#5223] opened 2019-05-22 16:37 UTC
My Trilinos compile on rzansel at LLNL fails with the following errors:
```
packages/seacas/libraries/ioss/src/gen_struc/libIogs.a(Iogs_GeneratedMesh.C.o):(.toc+0x30): undefined reference to `Ioss::Hex8::name'
packages/seacas/libraries/ioss/src/generated/libIogn.a(Iogn_GeneratedMesh.C.o):(.toc+0x30): undefined reference to `Ioss::Hex8::name'
packages/seacas/libraries/ioss/src/generated/libIogn.a(Iogn_GeneratedMesh.C.o):(.toc+0x38): undefined reference to `Ioss::Shell4::name'
```

I inspected the code, and it appears fine.  I am able to work around the issue.

<details>
<summary>possible patch</summary>

```
diff --git a/packages/seacas/libraries/ioss/src/Ioss_Hex8.C b/packages/seacas/libraries/ioss/src/Ioss_Hex8.C
index b6ac9a3..3fef2dd 100644
--- a/packages/seacas/libraries/ioss/src/Ioss_Hex8.C
+++ b/packages/seacas/libraries/ioss/src/Ioss_Hex8.C
@@ -39,6 +39,7 @@
 //------------------------------------------------------------------------
 // Define a variable type for storage of this elements connectivity
 namespace Ioss {
+  const char* Hex8::name = "hex8";
   class St_Hex8 : public ElementVariableType
   {
   public:
diff --git a/packages/seacas/libraries/ioss/src/Ioss_Hex8.h b/packages/seacas/libraries/ioss/src/Ioss_Hex8.h
index cfb9fc2..e4e034b 100644
--- a/packages/seacas/libraries/ioss/src/Ioss_Hex8.h
+++ b/packages/seacas/libraries/ioss/src/Ioss_Hex8.h
@@ -43,7 +43,8 @@ namespace Ioss {
   {
 
   public:
-    static constexpr const char *name = "hex8";
+    //static constexpr const char *name = "hex8";
+    static const char *name;
 
     static void factory();
     ~Hex8() override;
diff --git a/packages/seacas/libraries/ioss/src/Ioss_Shell4.C b/packages/seacas/libraries/ioss/src/Ioss_Shell4.C
index 46ddb95..cf0334e 100644
--- a/packages/seacas/libraries/ioss/src/Ioss_Shell4.C
+++ b/packages/seacas/libraries/ioss/src/Ioss_Shell4.C
@@ -39,6 +39,7 @@
 #include <cassert> // for assert
 
 namespace Ioss {
+  const char* Shell4::name = "shell4";
   class St_Shell4 : public ElementVariableType
   {
   public:
diff --git a/packages/seacas/libraries/ioss/src/Ioss_Shell4.h b/packages/seacas/libraries/ioss/src/Ioss_Shell4.h
index ff5f6bb..7246f37 100644
--- a/packages/seacas/libraries/ioss/src/Ioss_Shell4.h
+++ b/packages/seacas/libraries/ioss/src/Ioss_Shell4.h
@@ -43,7 +43,8 @@ namespace Ioss {
   {
 
   public:
-    static constexpr const char *name = "shell4";
+    //static constexpr const char *name = "shell4";
+    static const char *name;
 
     static void factory();
     ~Shell4() override;
```

</details>

<details>
<summary>cmake configure line</summary>

```
ARGS=(
  -D BUILD_SHARED_LIBS:BOOL=OFF
  -D CMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=OFF
  -D CMAKE_SKIP_INSTALL_RPATH:BOOL=OFF
  -D KOKKOS_ARCH:STRING=Power9,Volta70
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
  -GNinja -DTrilinos_ENABLE_Fortran:BOOL=OFF
  -D MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:BOOL=ON
  -D Trilinos_ENABLE_TESTS:BOOL=OFF
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF
  -D CMAKE_CXX_FLAGS:STRING="--expt-extended-lambda -std=c++11"

  -D Kokkos_ENABLE_Cuda_Lambda:BOOL=ON
  -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON
  -D Kokkos_ENABLE_Profiling:BOOL=ON

  -D Tpetra_INST_SERIAL:BOOL=ON
  -D Tpetra_INST_CUDA:BOOL=ON

  -D MueLu_ENABLE_Kokkos_Refactor=ON
  -D Xpetra_ENABLE_Kokkos_Refactor=ON

  -D Trilinos_ENABLE_Panzer=ON
  -D Panzer_ENABLE_TESTS:BOOL=OFF
  -D Panzer_ENABLE_EXAMPLES:BOOL=OFF
  -D Trilinos_ENABLE_PanzerMiniEM=ON
  -D PanzerMiniEM_ENABLE_EXAMPLES=ON
  -D PanzerMiniEM_ENABLE_TESTS=ON

  -D Trilinos_ENABLE_SEACASExodiff:BOOL=OFF
  -D Trilinos_ENABLE_SEACASEpu:BOOL=OFF
  -D Trilinos_ENABLE_SEACASNemspread:BOOL=OFF
  -D Trilinos_ENABLE_SEACASNemslice:BOOL=OFF
  -D Trilinos_ENABLE_SEACASAprepro:BOOL=OFF
  -D Teuchos_KOKKOS_PROFILING:BOOL=ON

  # pulled these from CMakeCache.txt on waterman, look for the comment
  # //Set in /ascldap/users/jhu/software/trilinos/Trilinos/cmake/std/atdm/ATDMDevEnvSettings.cmake
  -D Panzer_ENABLE_FADTYPE:STRING="Sacado::Fad::DFad<RealType>"
  -D Phalanx_KOKKOS_DEVICE_TYPE:STRING=CUDA
  -D Sacado_ENABLE_HIERARCHICAL_DFAD:BOOL=ON

  -D TPL_FIND_SHARED_LIBS:BOOL=OFF

  -D TPL_ENABLE_CUSPARSE:BOOL=ON

  -D TPL_ENABLE_HDF5:BOOL=ON
  -D HDF5_INCLUDE_DIRS:PATH="${HDF5}/include"
  -D HDF5_LIBRARY_DIRS:PATH="${HDF5}/lib"

  -D TPL_ENABLE_BLAS:BOOL=ON
  -D BLAS_INCLUDE_DIRS:PATH="${LAPACK_INC}"
  -D BLAS_LIBRARY_DIRS:PATH="${LAPACK_DIR}"
  -D TPL_ENABLE_LAPACK:BOOL=ON
  -D LAPACK_INCLUDE_DIRS:PATH="${LAPACK_INC}"
  -D LAPACK_LIBRARY_DIRS:PATH="${LAPACK_DIR}"

  -D F77_BLAS_MANGLE:STRING="(name,NAME) name"
  -D F77_FUNC:STRING="(name,NAME) name"
  -D F77_FUNC_:STRING="(name,NAME) name"

  -D TPL_ENABLE_MPI:BOOL=ON
  -D TPL_ENABLE_CUDA:BOOL=ON
  -D TPL_ENABLE_DLlib:BOOL=OFF

  # HDF5 dependency, for linking SEACAS executables
  #-D Trilinos_EXTRA_LINK_FLAGS:STRING="-lz -ldl -lm"
  -D Trilinos_EXTRA_LINK_FLAGS:STRING="-lz -L$LAPACK_DIR -llapack -lblas  -lxlopt -lxl -L/usr/tce/packages/xl/xl-2018.11.26/xlf/16.1.1/lib -lxlf90 -lxlfmath -lm"
)

cmake ${KEEP_TEMP_FILES} "${ARGS[@]}" ${TRILINOS_DIR}
```

</details>

modules
```
Currently Loaded Modules:
  1) StdEnv
  2) cuda/10.1.105
  3) xl/2018.11.26
  4) spectrum-mpi/rolling-release
  5) lapack/3.8.0-P9-xl-2018.08.24
  6) cmake/3.12.1
  7) hdf5-parallel/1.10.4
```

@trilinos/seacas @jjellio

**Comment by mhoemmen** [comment] 2019-05-22 17:14
@gsjaardema

**Comment by jjellio** [comment] 2019-05-22 17:20
I can confirm this fixed for me on Lassen.

**Comment by gsjaardema** [comment] 2019-05-23 12:40
I will take a look.  I just did a build on vortex which should be similar to rzansel and had no problems. The constexpr isn't really giving any benefit here, so there shouldn't be any issue removing it from the elements.

**Comment by gsjaardema** [comment] 2019-07-29 18:58
This should be fixed now.  Please reopen if the problem is still occurring or reappears.

**Closed by gsjaardema** 2019-07-29 18:58 UTC
Labels: impacting: build, pkg: seacas, type: bug
