### ISSUE TITLE
No default Tpetra Node type specified

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#3228] opened 2018-08-03 15:43 UTC
I can't find my previous ticket about this. Was it closed? The problem is definitely still there.

So I still can't build the pytrilinos interface. I refreshed my repo clone this morning.

```
/admin/rpms/BUILD/trilinos-git/packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:187: Error: CPP #error ""No default Tpetra Node type specified.  Please set the CMake option Tpetra_DefaultNode to a
valid Node type."". Use the -cpperraswarn option to continue swig processing.
make[2]: *** [packages/PyTrilinos/src/DomiPYTHON_wrap.cpp] Error 1
make[2]: Leaving directory `/tmp/trilinos-build'
make[1]: *** [packages/PyTrilinos/src/CMakeFiles/PyTrilinos_Domi.dir/all] Error 2
```

**Comment by mhoemmen** [comment] 2018-08-03 16:06
This is a duplicate of #3202

**Comment by mhoemmen** [comment] 2018-08-03 16:06
@wfspotz

**Closed by mhoemmen** 2018-08-03 16:06 UTC
