### ISSUE TITLE
MueLu: Complex build broken

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#4263] opened 2019-01-25 01:38 UTC
@trilinos/muelu 

https://github.com/trilinos/Trilinos/issues/2426#issuecomment-457394324
https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=4453539

```
In file included from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterEntry.hpp:52:0,
from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp:51,
from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/parameterlist/src/Teuchos_XMLParameterListCoreHelpers.hpp:51,
from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/comm/src/Teuchos_XMLParameterListHelpers.hpp:51,
from /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/muelu/test/scaling/Driver.cpp:51:

/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp: 

 In instantiation of ‘Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&) [with T2 = Xpetra::MultiVector<>; T = Xpetra::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >]’: 
 /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/muelu/test/scaling/Driver.cpp:472:100:
required from ‘int main_(Teuchos::CommandLineProcessor&, Xpetra::UnderlyingLib&, int, char**) [with Scalar = std::complex<double>; LocalOrdinal = int; GlobalOrdinal = int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>]’
/scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/muelu/test/scaling/../unit_tests/MueLu_Test_ETI.hpp:153:104:
required from here /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:289:38: 

error: cannot convert ‘Xpetra::MultiVector<>*’ to ‘Xpetra::MultiVector<std::complex<double>, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >*’ in initialization      node_(r_ptr.access_private_node())
```

[jhux2 edited error for readability]
## Motivation and Context

This blocks Sierra's Trilinos promotion.

## Related Issues
* Blocks #2426

**Comment by jhux2** [comment] 2019-01-25 15:24
I can produce these locally.  @lucbv Are you looking at these?

**Comment by lucbv** [comment] 2019-01-25 15:32
@jhux2, I'm looking at the code, haven't reproduced locally the error. But based on my reading I would imagine that the MV2EpetraMV function might need to be overloaded for `RealValuedMultiVector`.

**Comment by mhoemmen** [comment] 2019-01-25 16:33
Thanks for working on this!  Sierra is getting close with their CMake-based Trilinos build, so we appreciate anything you can do to help us out :-)

**Comment by lucbv** [comment] 2019-01-25 17:01
@jhux2 @mhoemmen,  PR #4268 should fix this issue, let us see how it fairs in the PR tester...

**Comment by lucbv** [comment] 2019-01-25 20:14
@mhoemmen, the PR was just merged in. Since the autotester is not building with complex enabled yet, could you double check that the fix works for Sierra?

**Comment by mhoemmen** [comment] 2019-01-29 06:30
@lucbv I'm in all-day meetings all week, but I'll try :-)

**Comment by lucbv** [comment] 2019-01-29 14:49
@mhoemmen based on the latest update in issue #2426 it seems that MueLu builds but some tests are still failing.
I will look into updating our gold files which should take care of two test failures.
The timing out issues are tracked by @jhux2 and @csiefer2 in issue #4268 I believe.

**Comment by mhoemmen** [comment] 2019-01-30 05:45
Thanks @lucbv !

**Comment by lucbv** [comment] 2019-01-31 17:13
@mhoemmen, a new PR #4305 by @cgcgcg should eliminate some of the test failures, let me know if this helps once it's merged.

**Comment by lucbv** [comment] 2019-02-11 15:06
@mhoemmen I don't see any reason to keep this open so I'll close it now. Feel free to reopen if some more complex related issues pop-up in you Sierra integration builds.

**Closed by lucbv** 2019-02-11 15:06 UTC
Labels: Sierra, build, in progress, pkg: MueLu

**Comment by mhoemmen** [comment] 2019-02-11 21:11
Thanks @lucbv !  I think we're good.  I can open a new issue if needed.
