### ISSUE TITLE
MueLu: Macro redefinition in ETI OFF build

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#3052] opened 2018-07-02 19:20 UTC
Sierra's Trilinos integration build reports the following error:
```
In file included from .../include/MueLu_ParameterListInterpreter.hpp:2:0,                 from .../include/MueLu_CreateTpetraPreconditioner.hpp:22,
                 from [some .cpp file]:
.../include/MueLu_ParameterListInterpreter_def.hpp:225:0: error: "MUELU_KOKKOS_FACTORY" redefined [-Werror]
 #define MUELU_KOKKOS_FACTORY(varName, oldFactory, newFactory) \
 ^
In file included from .../include/MueLu_FactoryManager.hpp:2:0,
                 from .../include/MueLu_Hierarchy_decl.hpp:67,
                 from .../include/MueLu_Hierarchy.hpp:1,
                 from [same .cpp file as above]:
.../include/MueLu_FactoryManager_def.hpp:88:0: note: this is the location of the previous definition
 #define MUELU_KOKKOS_FACTORY(varName, oldFactory, newFactory)   \
```
I'm guessing that MueLu developers didn’t test with ETI (explicit template instantiation) ~~on~~ off [edited by jhux2].
 
Diagnostic: Both macro definitions occur in _def.hpp files, which normally aren’t exposed to each other in ETI=ON builds.
 
`HAVE_MUELU_KOKKOS_REFACTOR` is undefined by default in both Trilinos’ CMake logic, and in Sierra’s Bjam logic for Trilinos.  Thus, MueLu developers are seeing the same macro defines as Sierra.
 
@trilinos/muelu @jhux2 

## Possible Solution

Undefine `MUELU_KOKKOS_FACTORY` before and after each use.

**Comment by jhux2** [comment] 2018-07-02 19:56
@mhoemmen Is this the same error as reported in #2967?  Can you confirm whether PR #2957 is in the code that Sierra is testing?

**Comment by mhoemmen** [comment] 2018-07-03 15:41
@jhux2 wrote:
> @mhoemmen did you mean off?

Yup, off :)

**Comment by mhoemmen** [comment] 2018-07-03 15:42
@jhux2 Sierra's Trilinos integration build tests master Trilinos.  (That makes it different from Sierra's other Dashboard lines.)

**Comment by khpierson** [comment] 2018-07-06 17:16
Was wondering if this issue is being worked? If so, when it might get fixed. This will help SIERRA be able to update to a newer version of trilinos. 

Thanks, -Kendall

**Comment by khpierson** [comment] 2018-07-06 17:57
Thanks for the update, I appreciate it!

**Comment by mhoemmen** [comment] 2018-07-06 17:59
@khpierson Hm, Trilinos hasn't had a develop-to-master promotion since 19 June.  @william76 , is stuff broken?

**Comment by william76** [comment] 2018-07-07 14:36
@mhoemmen There have been ROL errors in the clean track since 6/21.  As a rule, I do not promote develop -> master if there are errors.

See issue #3045

**Comment by mhoemmen** [comment] 2018-07-08 17:45
@william76 thanks for the update!

@micahahoward @rrdrake @prwolfe

**Comment by william76** [comment] 2018-07-18 15:05
@mhoemmen 
Thought you guys would like an update on the dev->master pushes... The ROL errors that were failing in the nightly clean track were fixed yesterday and the builds were clean so I was able to do the develop -> master promotion this morning. :)

**Comment by mhoemmen** [comment] 2018-07-18 19:44
@william76 Awesome!!! Thanks!!! :D

**Comment by cgcgcg** [comment] 2018-07-20 22:49
@khpierson PR #2957 should be in master now. Did it fix things for SIERRA?

**Comment by khpierson** [comment] 2018-07-24 13:11
@cgcgcg Yes, I just checked the dashboard and this issue has been confirmed fixed.

There is another build warning (we have warnings turned into errors), Do you want this submitted as separate issue?

Thanks!
-Kendall

/sierra/dev/nightly/Sierra.trilinos.master/TPLs_src/Trilinos_flat_headers/include/MueLu_TentativePFactory_def.hpp: In instantiation of 'void MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::BuildP(MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level&, MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level&) const [with Scalar = double; LocalOrdinal = int; GlobalOrdinal = long int; Node = Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial>; MueLu::TentativePFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level = MueLu::Level]':
    /sierra/dev/nightly/Sierra.trilinos.master/aero/src/TpetraLinearSolver.C:374:1:   required from here
    /sierra/dev/nightly/Sierra.trilinos.master/TPLs_src/Trilinos_flat_headers/include/MueLu_TentativePFactory_def.hpp:193:34: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
             for (LO lnode = 0; lnode < numNodes; lnode++) {

**Comment by mhoemmen** [comment] 2018-07-24 15:46
@khpierson I submitted that as #3177.  Thanks!

**Comment by jhux2** [comment] 2018-07-24 16:49
closing as fixed

**Closed by jhux2** 2018-07-24 16:49 UTC
Labels: MueLu, build
