### ISSUE TITLE
MueLu_ConvergenceTpetra_MPI tests failing in build Trilinos-atdm-mutrino-intel-opt-openmp-KNL starting before 2018-11-13

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#3862] opened 2018-11-13 16:46 UTC
CC: @trilinos/muelu  @srajama1  (Trilinos Linear Solvers Product Lead), @bartlettroscoe 
 
## Description
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=63&value2=MueLu_ConvergenceTpetra_MPI_&field3=buildstarttime&compare3=84&value3=2018-11-13T00%3A00%3A00&field4=buildstarttime&compare4=83&value4=2018-11-12T00%3A00%3A00) the tests:
* MueLu_ConvergenceTpetra_MPI_1
* MueLu_ConvergenceTpetra_MPI_4

are failing in the build:
* Trilinos-atdm-mutrino-intel-opt-openmp-KNL

Test output:
```
srun: Job 13306723 step creation temporarily disabled, retrying
srun: Step created for job 13306723

p=0: *** Caught standard std::exception of type 'N7Teuchos40CantFindParameterEntryConverterExceptionE' :

 /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/teuchos/parameterlist/src/Teuchos_ParameterEntryXMLConverterDB.cpp:85:
 
 Throw number = 1
 
 Throw test that evaluated to true: it == getConverterMap().end()
 
 Can't find converter for parameter entry of type: long long
 
 End Result: TEST FAILED
srun: error: nid00192: task 0: Exited with exit code 1
srun: Terminating job step 13306723.920
```

## Current Status on CDash

* [Test results for last 30 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=block&field2count=2&field2field1=buildname&field2compare1=61&field2value1=Trilinos-atdm-ats1-knl_intel-18.0.5_mpich-7.7.6_openmp_static_opt&field2field2=buildname&field2compare2=61&field2value2=Trilinos-atdm-ats1-knl_intel-19.0.4_mpich-7.7.6_openmp_static_opt&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=MueLu_ConvergenceTpetra_MPI_1&field3field2=testname&field3compare2=61&field3value2=MueLu_ConvergenceTpetra_MPI_4)

## Steps to Reproduce

One should be able to reproduce this failure on the machine mutrino as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
More specifically, the commands given for the system mutrino are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#mutrino
The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-mutrino-intel-opt-openmp-KNL

$ cmake \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON \
  $TRILINOS_DIR

$ make -j16

$ salloc -N 1 -p standard -J Trilinos-atdm-mutrino-intel-opt-openmp-KNL ctest -j16
```

**Comment by srajama1** [comment] 2018-11-13 19:47
@jhux2

**Comment by jhux2** [comment] 2018-12-01 00:41
@srajama1  I'm working on this issue and am seeing these messages:

`icpc: command line warning #10121: overriding '-xCORE-AVX2' with '-xMIC-AVX512'`

This isn't blocking me, but just an FYI.

**Comment by cgcgcg** [comment] 2018-12-01 00:50
This sounds like someones is setting build flags for Haswell, and it's
being replaced for KNL flags, no? Maybe their build is misconfigured?

Best,
 Christian

**Comment by jhux2** [comment] 2018-12-01 00:55
@cgcgcg This would make sense, since this is a KNL build, but I am compiling on the login nodes, which are Haswell.

**Comment by bartlettroscoe** [comment] 2018-12-01 02:57
@cgcgcg and @jhux2, 

This build configuration is just setting `KOKKOS_ARCH=KNL` so if there is funny business going on with compiler options that is being done inside of Kokkos.  You can see that logic and the compiler options that Kokkos selects, for example, here:

* https://testing.sandia.gov/cdash-dev-view/viewConfigure.php?buildid=4231144

which shows:

```
-- KOKKOS_ARCH='KNL'
-- NOT using the legacy tribits build because KOKKOS_ARCH *is* set
-- 
-- ****************** Kokkos Settings ******************
-- Execution Spaces
--   Device Parallel: None
--     Host Parallel: OpenMP
--       Host Serial: Serial
-- 
-- Architectures:
--     KNL
-- 
-- Enabled options
--   KOKKOS_ENABLE_SERIAL
--   KOKKOS_ENABLE_OPENMP
--   KOKKOS_ENABLE_DEPRECATED_CODE
-- 
-- Final kokkos settings variable:
--   env;KOKKOS_CMAKE=yes;KOKKOS_SRC_PATH=/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/kokkos;KOKKOS_PATH=/lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-KNL/SRC_AND_BUILD/Trilinos/packages/kokkos;KOKKOS_INSTALL_PATH=/usr/local;KOKKOS_ARCH=KNL;KOKKOS_DEVICES=OpenMP,Serial;KOKKOS_DEBUG=no;KOKKOS_OPTIONS=disable_profiling,disable_dualview_modify_check
-- *****************************************************
```

Is there something that should be changed?

**Comment by jhux2** [comment] 2018-12-03 20:15
I'm returning to this issue.  Is the recipe to reproduce missing an ingredient?  Note the illegal instruction message.

```
> salloc -N 1 -p standard -J Trilinos-atdm-mutrino-intel-opt-openmp-KNL ctest -R "MueLu_ConvergenceTpetra_MPI_1" -V

salloc: Granted job allocation 13923083
salloc: Waiting for resource configuration
salloc: Nodes nid00120 are ready for job
UpdateCTestConfiguration  from :/projects/trilinos/jhu/build-trilinos-github-issue-3862/DartConfiguration.tcl
Parse Config file:/projects/trilinos/jhu/build-trilinos-github-issue-3862/DartConfiguration.tcl
 Add coverage exclude regular expressions.
SetCTestConfiguration:CMakeCommand:/projects/netpub/atdm/cmake-3.11.4/bin/cmake
UpdateCTestConfiguration  from :/projects/trilinos/jhu/build-trilinos-github-issue-3862/DartConfiguration.tcl
Parse Config file:/projects/trilinos/jhu/build-trilinos-github-issue-3862/DartConfiguration.tcl
Test project /projects/trilinos/jhu/build-trilinos-github-issue-3862
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 69
    Start 69: MueLu_ConvergenceTpetra_MPI_1

69: Test command: /opt/slurm/bin/srun "--mpi=pmi2" "--ntasks-per-node" "36" "--ntasks" "1" "--hint=nomultithread" "-c 4" "/projects/trilinos/jhu/build-trilinos-github-issue-3862/packages/muelu/test/convergence/MueLu_Convergence.exe" "--linAlgebra=Tpetra"
69: Test timeout computed to be: 600
69: srun: error: nid00120: task 0: Illegal instruction
69: srun: Terminating job step 13923083.0
1/1 Test #69: MueLu_ConvergenceTpetra_MPI_1 ....***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
]  1.20 sec

0% tests passed, 1 tests failed out of 1

Subproject Time Summary:
MueLu    =   1.20 sec*proc (1 test)

Total Test time (real) =   2.13 sec

The following tests FAILED:
	 69 - MueLu_ConvergenceTpetra_MPI_1 (Failed)
Errors while running CTest
salloc: Relinquishing job allocation 13923083
```

**Comment by jhux2** [comment] 2018-12-03 20:44
Ah, the batch submission command is wrong, should be
```
salloc -N 1 -p knl -J Trilinos-atdm-mutrino-intel-opt-openmp-KNL ctest -j16
```

**Comment by bartlettroscoe** [comment] 2020-03-28 16:52
FYI: These tests have been failing for almost 1.5 years.  I think it is time to disable them.

**Comment by bartlettroscoe** [comment] 2020-06-06 20:11
CC: @rmmilewi

FYI: Example of what comment content might look like for tool being developed in #3887.

----

<h2>Test results for issue #3862 as of YYYY-MM-DD</h2>

<p>
<font color="red">Tests with issue trackers Failed: twif=2</font><br>
</p>


<details>

<summary><b>Detailed test results:</b> (click to expand)</b></summary>

<h3><font color="red">Tests with issue trackers Failed: twif=2</font></h3>
<table style="width:100%" boarder="1">

<tr>
<th>Site</th>
<th>Build Name</th>
<th>Test Name</th>
<th>Status</th>
<th>Details</th>
<th>Consec&shy;utive Non-pass Days</th>
<th>Non-pass Last 30 Days</th>
<th>Pass Last 30 Days</th>
<th>Issue Tracker</th>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/test/18213577">MueLu_&shy;ConvergenceTpetra_&shy;MPI_&shy;1</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/test/18213577"><font color="red">Failed</font></a></td>
<td align="left">Completed (Failed)</td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=MueLu_ConvergenceTpetra_MPI_1&field3=site&compare3=61&value3=mutrino"><font color="red">20</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=MueLu_ConvergenceTpetra_MPI_1&field3=site&compare3=61&value3=mutrino"><font color="red">20</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=MueLu_ConvergenceTpetra_MPI_1&field3=site&compare3=61&value3=mutrino"><font color="green">0</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3862">#3862</a></td>
</tr>

<tr>
<td align="left">mutrino</td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=site&compare2=61&value2=mutrino">Trilinos-atdm-mutrino-intel-opt-openmp-KNL</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/test/18213578">MueLu_&shy;ConvergenceTpetra_&shy;MPI_&shy;4</a></td>
<td align="left"><a href="https://testing-dev.sandia.gov/cdash/test/18213578"><font color="red">Failed</font></a></td>
<td align="left">Completed (Failed)</td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=MueLu_ConvergenceTpetra_MPI_4&field3=site&compare3=61&value3=mutrino"><font color="red">20</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=MueLu_ConvergenceTpetra_MPI_4&field3=site&compare3=61&value3=mutrino"><font color="red">20</font></a></td>
<td align="right"><a href="https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2020-05-07&end=2020-06-05&filtercombine=and&filtercombine=&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-mutrino-intel-opt-openmp-KNL&field2=testname&compare2=61&value2=MueLu_ConvergenceTpetra_MPI_4&field3=site&compare3=61&value3=mutrino"><font color="green">0</font></a></td>
<td align="right"><a href="https://github.com/trilinos/Trilinos/issues/3862">#3862</a></td>
</tr>

</table>

</details>
</body>
</html>

**Comment by bartlettroscoe** [comment] 2020-06-18 14:46
FYI: I just updated the "Current status on CDash" above to point to the new 'ats1' builds which is:

* https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=block&field2count=2&field2field1=buildname&field2compare1=61&field2value1=Trilinos-atdm-ats1-knl_intel-18.0.5_mpich-7.7.6_openmp_static_opt&field2field2=buildname&field2compare2=61&field2value2=Trilinos-atdm-ats1-knl_intel-19.0.4_mpich-7.7.6_openmp_static_opt&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=MueLu_ConvergenceTpetra_MPI_1&field3field2=testname&field3compare2=61&field3value2=MueLu_ConvergenceTpetra_MPI_4

Let's see if we can make it to 2 years with this issue open and these tests still failing.  Less than 5 months left until we reach that goal.

**Comment by cgcgcg** [comment] 2020-06-24 15:08
@bartlettroscoe Looks like the last iteration came back clean.

**Comment by cgcgcg** [comment] 2020-06-30 17:03
Closing as fixed.

**Closed by cgcgcg** 2020-06-30 17:03 UTC
Labels: ATDM Sev: Nonblocker, PA: Linear Solvers, client: ATDM, pkg: MueLu, type: bug
