### ISSUE TITLE
Build error when trying to include blas libraries

### ISSUE THREAD

**Issue by ddingeara** [trilinos/Trilinos#10380] opened 2022-03-29 17:18 UTC
Why is the Trilinos build system turning user supplied blas libraries into  make targets?? Thanks!

[ 72%] Built target stk_transfer_utils_lib
[ 73%] Built target stk_tools_lib
make[2]: *** No rule to make target `/home/ddinge/lapack-3.10.0/lib/libfblas.a', needed by `packages/stk/stk_tools/stk_tools/stk_block_extractor'.  Stop.
make[1]: *** [packages/stk/stk_tools/stk_tools/CMakeFiles/stk_block_extractor.dir/all] Error 2

Here is my cmake

cmake -DTPL_ENABLE_MPI=ON -DMPI_BASE_DIR=/home/dortley/opt/ -DTrilinos_ENABLE_ALL_PACKAGES=ON -DCMAKE_INSTALL_PREFIX=/home/ddinge/trilinos-master/build -DTPL_ENABLE_Netcdf=ON -DNetcdf_LIBRARY_DIRS="/home/ddinge/netcdf-c-4.8.1/build/lib;/home/ddinge/pnetcdf-1.12.3/build/lib" -DNetcdf_INCLUDE_DIRS="/home/ddinge/netcdf-c-4.8.1/build/include;/home/ddinge/pnetcdf-1.12.3/build/include"  -DNetCDF_BINARY_DIR=/home/ddinge/netcdf-c-4.8.1/build/bin -D TPL_ENABLE_BLAS=ON -DTPL_BLAS_LIBRARIES:FILEPATH="/home/ddinge/lapack-3.10.0/lib/libcblas.a;/home/ddinge/lapack-3.10.0/lib/libfblas.a" -DLAPACK_LIBRARY_DIRS=/home/ddinge/lapack-3.10.0/lib -DBoost_INCLUDE_DIRS=/home/ddinge/boost_1_78_0/boost -DTPL_ENABLE_Matio=OFF -D TPL_ENABLE_HDF5=ON -DHDF5_INCLUDE_DIRS=/home/ddinge/hdf5-1.10.8/build/include -DHDF5_LIBRARY_DIRS=/home/ddinge/hdf5-1.10.8/build/lib

**Comment by jhux2** [comment] 2022-03-29 18:07
@ddingeara Please see https://docs.trilinos.org/files/TrilinosBuildReference.html, Section 5.15.

**Comment by ddingeara** [comment] 2022-03-29 18:25
Hi Jonathan,

I did read it and I followed the instructions. I tried the techniques there and variations. Here are a few relevant parts of my cmake.

-DTPL_BLAS_LIBRARIES="/home/ddinge/lapack-3.10.0/lib/libcblas.a;/home/ddinge/lapack-3.10.0/lib/libfblas.a"

-DTPL_BLAS_LIBRARIES:FILEPATH="/home/ddinge/lapack-3.10.0/lib/libcblas.a;/home/ddinge/lapack-3.10.0/lib/libfblas.a"

-D TPL_ENABLE_BLAS=ON -DTPL_BLAS_LIBRARIES:FILEPATH="/home/ddinge/lapack-3.10.0/lib/libcblas.a;/home/ddinge/lapack-3.10.0/lib/libfblas.a"

-D TPL_ENABLE_BLAS=ON -DTPL_BLAS_LIBRARIES:FILEPATH="/home/ddinge/lapack-3.10.0/lib/libcblas.a;/home/ddinge/lapack-3.10.0/lib/libfblas.a"
-D BLAS_LIBRARY_NAMES="cblas;fblas"

The result is the same

make[2]: *** No rule to make target `/home/ddinge/lapack-3.10.0/lib/libfblas.a', needed by `packages/stk/stk_tools/stk_tools/stk_block_extractor'.  Stop.

Thanks

Dennis

**Comment by ddingeara** [comment] 2022-03-29 18:36
If it helps I think the library is being made a target within

CheckHostBlasReturnComplex.cmake

IF (KOKKOSKERNELS_HAS_TRILINOS)
    SET(CMAKE_REQUIRED_LIBRARIES ${TPL_BLAS_LIBRARIES})
  ELSE()
    # For TPLs, just pull out the required libraries from the target properies.
    IF (KOKKOSKERNELS_ENABLE_TPL_ARMPL)
      GET_TARGET_PROPERTY(CMAKE_REQUIRED_LIBRARIES KokkosKernels::ARMPL INTERFACE_LINK_LIBRARIES)
    ELSE()
      SET(CMAKE_REQUIRED_LIBRARIES ${BLAS_LIBRARIES})
    ENDIF()
  ENDIF()

But I could be wrong.

Dennis

**Comment by alanw0** [comment] 2022-03-29 19:19
@ddingeara @jhux2
We think it's possible that the "no rule for target" error means that the library/path wasn't found. Can you double-check your path?

We have built trilinos using a couple of different ways of specifying blas/lapack:
1. we have a module for netlib-lapack, and when we load that module, we don't need to explicitly enable blas or lapack in cmake flags.
2. on other systems, we enable blas and lapack, and specify paths in the same way that you do, and we don't see anything obviously wrong with your specification if the paths are valid.

If all your paths are valid, please attach your full cmake output log and we'll look further to see what we can suggest.

**Comment by ddingeara** [comment] 2022-03-29 19:49
The path is valid

***@***.*** build]$ ls -l /home/ddinge/lapack-3.10.0/lib/libcblas.a
-rw-r--r-- 1 ddinge users 379078 Mar 17 15:27 /home/ddinge/lapack-3.10.0/lib/libcblas.a

See attached

Dennis

**Comment by tasmith4** [comment] 2022-03-29 19:58
@ddingeara the attached log apparently got stripped out of your email by Github, can you log in to Github and attach it directly to a comment?

**Comment by ddingeara** [comment] 2022-03-29 20:04
Logs attached
[CMakeOutput.log](https://github.com/trilinos/Trilinos/files/8374662/CMakeOutput.log)
[CMakeError.log](https://github.com/trilinos/Trilinos/files/8374663/CMakeError.log)
d

**Comment by alanw0** [comment] 2022-03-29 20:20
@ddingeara These logs are not quite what we're looking for. Can you re-run cmake in a clean build directory and put the console output into a file and attach that?
Also, these logs only show errors regarding libfblas.a, not libcblas.a. Can you confirm that libfblas.a exists in that directory also?

**Comment by ddingeara** [comment] 2022-03-29 20:28
***@***.*** build]$ ls -l /home/ddinge/lapack-3.10.0/lib/libcblas.a
-rw-r--r-- 1 ddinge users 379078 Mar 17 15:27 /home/ddinge/lapack-3.10.0/lib/libcblas.a
***@***.*** build]$ ls -l /home/ddinge/lapack-3.10.0/lib/
total 13676
-rw-r--r-- 1 ddinge users   379078 Mar 17 15:27 libcblas.a
-rw-r--r-- 1 ddinge users 12379766 Mar 15 14:47 liblapack.a
-rw-r--r-- 1 ddinge users   609816 Mar 17 15:26 librefblas.a
-rw-r--r-- 1 ddinge users   627652 Mar 15 14:48 libtmglib.a

cmake output uploaded

Dennis

**Comment by ddingeara** [comment] 2022-03-29 21:31
[cmakeout.txt](https://github.com/trilinos/Trilinos/files/8375127/cmakeout.txt)

**Comment by tasmith4** [comment] 2022-03-30 02:16
@ddingeara so it looks like the issue is that libfblas.a is not present in /home/ddinge/lapack-3.10.0/lib.  I don't know the details of your LAPACK/BLAS install, so I'm unsure which libraries are actually needed.  What happens if you take that out of your TPL_BLAS_LIBRARIES argument?  i.e. use this instead:
```
-DTPL_BLAS_LIBRARIES:FILEPATH="/home/ddinge/lapack-3.10.0/lib/libcblas.a"
```
Alternatively, what if you include the librefblas.a which is present in your directory?
```
-DTPL_BLAS_LIBRARIES:FILEPATH="/home/ddinge/lapack-3.10.0/lib/libcblas.a;/home/ddinge/lapack-3.10.0/lib/librefblas.a"
```

If neither of these work, and you really truly need libfblas.a, then since it looks like you're building this copy of LAPACK yourself, I'd suggest consulting the documentation of the particular LAPACK distribution you're working with to see how to rebuild it so that it generates libfblas.a.

**Comment by ddingeara** [comment] 2022-10-11 08:01
Thanks Tim you second suggestion got me past my issue. You can close the ticket.

Dennis

**Comment by jhux2** [comment] 2022-10-12 18:01
closing as fixed

**Closed by jhux2** 2022-10-12 18:01 UTC
Labels: type: question, pkg: STK, impacting: configure or build
