### ISSUE TITLE
Zoltan:  question about Zoltan_config.h

### ISSUE THREAD

**Issue by RongquanHE** [trilinos/Trilinos#11960] opened 2023-06-09 14:29 UTC
### Description
Trilinos/Trilinos/packages/zoltan/src/include/Zoltan_config.h, the file named by Zoltan_config.h.in, I think it is a mistake.

**Comment by jhux2** [comment] 2023-06-09 16:41
@RongquanHE Could you please be more specific?  If you're running into configure or build problems, please provide instructions to reproduce.

@trilinos/zoltan

**Comment by jhux2** [comment] 2023-06-16 16:25
Closing due to lack of information.  Please reopen if you can provide more details.

**Closed by jhux2** 2023-06-16 16:25 UTC
Labels: type: bug, pkg: Zoltan
