### ISSUE TITLE
Teuchos: Unknown CMake command "TRIBITS_SET_AND_INC_DIRS"

### ISSUE THREAD

**Issue by cgcgcg** [trilinos/Trilinos#11501] opened 2023-01-25 15:08 UTC
@trilinos/teuchos 

### Description
In a nightly build we are getting
```
CMake Error at packages/teuchos/core/src/CMakeLists.txt:65 (TRIBITS_SET_AND_INC_DIRS):
  Unknown CMake command "TRIBITS_SET_AND_INC_DIRS".
```
see
https://testing.sandia.gov/cdash/build/11447071/configure

I'm a bit confused about how that can happen. No other builds seem to be affected by this.

**Comment by bartlettroscoe** [comment] 2023-01-25 15:52
@cgcgcg, my guess is that this is caused by using an older version of Trilinos/TriBITS in the "outer" driver repo as shown in the configure output [here](https://testing.sandia.gov/cdash/build/11447071/configure) showing:

```
-- PROJECT_SOURCE_DIR='/home/gbharpe/Programming/cpp/Nightly/SEMS-OPENMPI-4.0.5_RELEASE_DEFAULT/Trilinos'
...
-- Trilinos_TRIBITS_DIR='/home/gbharpe/Programming/cpp/Nightly/Trilinos-source/cmake/tribits'
```

My guess is that the "outer" Trilinos git repo `/home/gbharpe/Programming/cpp/Nightly/Trilinos-source` is an old version of Trilinos/TriBITS while the "inner" Trilinos git repo `/home/gbharpe/Programming/cpp/Nightly/SEMS-OPENMPI-4.0.5_RELEASE_DEFAULT/Trilinos` is up to date, as shown in that configure output:

```
Trilinos repos versions:
--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
4766f4b12cc [Mon Jan 23 17:04:57 2023 -0600] <trilinos@sandia.gov>
Merge Pull Request #11492 from gsjaardema/Trilinos/SEACAS-clean-up-recent-change
--------------------------------------------------------------------------------
```

Have your cron/Jenkins/whatever driver update the "outer" Trilinos git repo at `/home/gbharpe/Programming/cpp/Nightly/Trilinos-source` before running the `ctest -S` script that drives the inner Trilinos update, build, test, and submit.

**Comment by cgcgcg** [comment] 2023-01-25 15:58
@bartlettroscoe That makes sense. Thank you!

**Comment by bartlettroscoe** [comment] 2023-01-25 16:04
FYI: You can see the outer ctest -S driver script logged in the notes for that build [here](https://testing.sandia.gov/cdash/build/11447071/notes#note3).

**Comment by GrahamBenHarper** [comment] 2023-02-10 00:14
Closing this as fixed.

It was simply fixed by telling the cronjob to update the outer git repo first. Related to #11540 since that particular build is also struggling with its SuperLU version.

**Closed by GrahamBenHarper** 2023-02-10 00:14 UTC
Labels: type: question, PA: Framework
