### ISSUE TITLE
Pytrilinos installation error

### ISSUE THREAD

**Issue by kvmkrao** [trilinos/Trilinos#1821] opened 2017-10-05 23:15 UTC
@wfspotz 
I used gcc5.4, python3.6, swig3.0 and mpich 3.0 modules to build Pytrilinos.  The configuration options set  
for the build are 

> cmake \
>  -D Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
>  -D CMAKE_INSTALL_PREFIX:PATH=/home/vkotteda/Software/pytrilinos/install \
>  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
>  -D BUILD_SHARED_LIBS:BOOL=ON \
>  -D TPL_ENABLE_MPI:BOOL=ON \
>  -D MPI_BASE_DIR=$MPIDIR/bin \
>  -D Trilinos_ENABLE_Fortran:BOOL=ON \
>  -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
>  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
>  -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
>  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
> \
>   -D Trilinos_ENABLE_TESTS:BOOL=OFF \
>   -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
>   -D Trilinos_ENABLE_Epetra:BOOL=ON \
>   -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
>   -D Trilinos_ENABLE_Domi:BOOL=ON \
>   -D Trilinos_ENABLE_AztecOO:BOOL=ON \
>   -D Trilinos_ENABLE_PyTrilinos:BOOL=ON \
> \
>  -D TPL_ENABLE_Boost:BOOL=ON \
>  -D Boost_INCLUDE_DIRS:FILEPATH="$BOOSTDIR/include" \
>  -D Boost_LIBRARY_DIRS:FILEPATH="$BOOSTDIR/lib" \
>  -D TPL_ENABLE_BoostLib:BOOL=ON \
>  -D BoostLib_INCLUDE_DIRS:FILEPATH="$BOOSTDIR/include" \
>  -D BoostLib_LIBRARY_DIRS:FILEPATH="$BOOSTDIR/lib" \
> \
>  -D TPL_ENABLE_Netcdf:BOOL=ON \
>  -D Netcdf_INCLUDE_DIRS:PATH="$NETCDFDIR/include" \
>  -D Netcdf_LIBRARY_DIRS:PATH="$NETCDFDIR/lib" \
> \
>   -D TPL_ENABLE_BLAS:BOOL=ON \
>   -D TPL_BLAS_LIBRARIES:FILEPATH=$LAPDIR/libblas.so.3 \
>   -D TPL_ENABLE_LAPACK:BOOL=ON \
>   -D TPL_LAPACK_LIBRARIES:FILEPATH=$LAPDIR/liblapack.so.3 \
> \
>  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
>   -D TPL_ENABLE_BLAS:BOOL=ON \
>   -D TPL_ENABLE_LAPACK:BOOL=ON \
>   -D Trilinos_ENABLE_PyTrilinos:BOOL=ON \
>   -D PyTrilinos_DOCSTRINGS:BOOL=OFF \
>   -D PyTrilinos_ENABLE_TESTS:BOOL=ON \
>   -D PyTrilinos_INSTALL_PREFIX:PATH=/home/vkotteda/Software/pytrilinos/install \
> /home/vkotteda/Software/Trilinos/gitclone

There were no errors during the build. However the following error stops the installation of the Pytrilinos. 

 Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/AztecOO_ConditionNumber.h
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/AztecOO_ConfigDefs.h
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/AztecOO_Version.h
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/lib/cmake/PyTrilinos/PyTrilinosConfig.cmake
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/lib/cmake/PyTrilinos/PyTrilinosTargets.cmake
-- Installing: /home/vkotteda/Software/pytrilinos/install/lib/cmake/PyTrilinos/PyTrilinosTargets-debug.cmake
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/Makefile.export.PyTrilinos
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/lib/libpytrilinos.so.12.13
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/lib/libpytrilinos.so.12
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/lib/libpytrilinos.so
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_config.h
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_PythonException.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_FILEstream.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_Util.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/numpy_include.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_NumPyImporter.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_NumPy_Util.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_DAP.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_Teuchos_Util.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_Epetra_Util.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_LinearProblem.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_Domi_Util.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/PyTrilinos_EpetraExt_Util.hpp
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/include/swigpyrun.h
-- Up-to-date: /home/vkotteda/Software/pytrilinos/install/lib/python3.6/site-packages/PyTrilinos/Teuchos.py

> CMake Error at packages/PyTrilinos/src/cmake_install.cmake:99 (file):
>   file INSTALL cannot find
>   "/home/vkotteda/Software/pytrilinos/packages/PyTrilinos/src/PyTrilinos/Teuchos.pyc".
> Call Stack (most recent call first):
>   packages/PyTrilinos/cmake_install.cmake:66 (include)
>   cmake_install.cmake:72 (include)

I appreciate your suggestion to overcome this error.  

Thank you.

**Comment by wfspotz** [comment] 2017-10-05 23:19
What is the full version number for SWIG?

**Comment by kvmkrao** [comment] 2017-10-06 03:25
It is 3.0.8. 
Thank you.

**Comment by wfspotz** [comment] 2017-10-06 16:57
This looks like Issue #1749, which I have not been able to fix, because I have not been able to reproduce it. I would like to sit down with you and see if I/we can figure this out together. Let's plan to do it while you are here for TUG.

**Comment by kvmkrao** [comment] 2017-10-06 18:09
Thank you @wfspotz. Sure, I will show you the installation error.  

The installation error was resulted with the following repo
> --------------------------------------------------------------------------------
> 02fb98c [Tue Aug 29 11:01:13 2017 -0400] <prokopenkoav@ornl.gov>
> MueLu: fix misprint in Test_ETI for CUDA
>  --------------------------------------------------------------------------------

The current git repo works well ( #1820) and does not throw the installation error when I build
pytrilinos with anaconda2/python 2.7.13 and SWIG 3.0.12. Therefore, the installation is successful. 

> --------------------------------------------------------------------------------
> d6eed5d [Thu Sep 28 13:47:58 2017 -0600] <bmpersc@sandia.gov>
> Update release notes for 12.12.
>  --------------------------------------------------------------------------------

However, the current repo results in the same installation error for anaconda3/python 3.6.1 and SWIG 4.0.0. 

Thank you.

**Comment by gpkc** [comment] 2017-10-08 17:07
@kvmkrao I've written in #1749 how to workaround this problem, if you haven't figured out yet.

**Comment by wfspotz** [comment] 2017-10-09 16:23
Closing in favor of #1749

**Closed by wfspotz** 2017-10-09 16:23 UTC
Labels: build, PyTrilinos, resolved/duplicate
