### ISSUE TITLE
Promote Tpetra::Experimental::Block* classes to non-Experimental

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#619] opened 2016-09-15 23:50 UTC
The objective of this issue is to free up the Experimental::Block\* classes for backwards-incompatible, NGP-friendly refactoring, while providing current Experimental::Block\* users with the current impl.

**Comment by mhoemmen** [comment] 2016-09-16 15:54
@tcfisher may be interested in the outcome.

**Comment by mhoemmen** [comment] 2016-09-16 18:02
Here is the current plan:

  1. Import Tpetra::Experimental::Block* classes into Tpetra namespace with `using` declarations
  2. Change Block* tests to use the classes in the Tpetra namespace
  3. Once we decide to make a change to a Block* class, we'll first copy that class, as it stands now, into the Tpetra namespace.  Then, we'll start modifying the version of the class in the Tpetra::Experimental namespace.

**Comment by mhoemmen** [comment] 2016-11-09 21:17
@ambrad is taking this up now.  I will help him review.

**Comment by ambrad** [comment] 2016-11-10 22:00
@mhoemmen, the commit above is ready for review. checkin.py was already run on it, and I tested an app against it. (No rush.) Thanks!

**Comment by mhoemmen** [comment] 2016-11-12 21:15
@ambrad, I just took a look at the commit, and it looks great!  If you have a chance, you might like to try a test with ETI OFF, just to make sure that everything works right with the decl vs. def header files.  Thanks!

**Comment by ambrad** [comment] 2016-11-12 22:32
Thanks for reviewing Mark. I checked with an app with and without ETI, with both namespaces, thus doing installation testing for all four cases. I'll push the commit later today.

**Comment by mhoemmen** [comment] 2016-11-12 22:53
@ambrad Awesome, thanks!!! :-D

**Comment by ambrad** [comment] 2016-11-12 23:08
OK, pushed. I'm going to keep this issue open to track the sequence of steps. The next steps are:

2a. We will inform users to switch to Tpetra::Block*.

2b. Similarly, we will modify Trilinos-internal users of Tpetra::Experimental::Block* to use Tpetra::Block* instead.

**Comment by mhoemmen** [comment] 2016-11-13 01:03
Thanks @ambrad !  The main user should be @tcfisher .  @bmpersc may be able to help with associated integration issues.

**Comment by mhoemmen** [comment] 2016-11-15 04:51
See #179 discussion.  I think #179 is really just a duplicate of this issue.

**Comment by mhoemmen** [comment] 2017-01-11 00:27
Hi @tcfisher !  You can use Tpetra:: instead of Tpetra::Experimental:: now!  @ambrad says to bug him if it breaks.

**Comment by kddevin** [comment] 2017-10-30 19:23
From the conversation and FY17 closeout reports, I understand that this task is done. 
Thus, I am going to close this issue.  If my understanding is incorrect, please reopen and clarify what remains to be done (e.g., 2a and 2b above?).  Thanks.
@ambrad @mhoemmen

**Closed by kddevin** 2017-10-30 19:23 UTC
Labels: in progress, task, Tpetra, TpetraRF

**Comment by ambrad** [comment] 2017-10-30 19:30
Yes, closing is appropriate. 2a is done. 2b needs to be done the first time a new experimental BlockCrsMatrix class is brought in. For now, it doesn't matter either way. Main thing was to make it possible.
