### ISSUE TITLE
Test Teko_testdriver_tpetra_MPI_1 is failing in new GCC 4.8.4 + OpenMPI 1.10.1 + OpenMP build

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2712] opened 2018-05-09 21:11 UTC
**CC:** @trilinos/teko, @fryeguy52

## Next Action Status

PR #2715 was merged on 5/10/2018.  The test `Teko_testdriver_tpetra_MPI_1` passed in build `GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP` on 5/11/2018.  Next: Find someone to debug and fix the test.

## Description

The test `Teko_testdriver_tpetra_MPI_1` is failing in the new build `GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP` as shown at:

* https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP&field2=testname&compare2=61&value2=Teko_testdriver_tpetra_MPI_1&field3=buildstarttime&compare3=84&value3=now

The most recent run of this test shown at:

* https://testing-vm.sandia.gov/cdash/testDetails.php?test=46422819&build=3496203

shows the failure output:

```
...
Teko: LSCPrecFact::buildPO BuildStateTime = 0.04688
Teko: LSCPrecFact::buildPO GetInvTime = 2.86102e-06
Teko: LSCPrecFact::buildPO TotalTime = 0.0475988
   "strategy" ... FAILED ( PID = 0 )
Test "LSCStabilized_tpetra" completed ... FAILED (1)
...
Teko: Building LSC strategy "The Cat"
LSC Construction failed: Strategy "The Cat" could not be constructed
   Teko: Begin debug MSG
      Looked up "NS LSC"
      Built Teuchos::RCP<Teko::PreconditionerFactory>{ptr=0x1d14a48,node=0x1e48230,strong_count=1,weak_count=0}
   Teko: End debug MSG
LSC Construction failed: Strategy "The Cat" requires a "Strategy Settings" sublist
...
Tests Passed: 90, Tests Failed: 1
(Incidently, you want no failures)
Teko tests failed
```

**NOTE:** This build satisfies all of the requirements for the GCC 4.8.4 build described in #2317 and #2462.  Other than the ShyLU_DD failures addressed in #2691, this failing test is the only test blocking this build from being 100% passing.

## Steps to Reproduce

One should be able to reproduce this failing test on any SNL COE RHEL6 machine that mounts the SEMS env.  After cloning the Trilinos git repo and checking out the `develop` branch, one should be able to do:

```
$ cd <some-build-dir>/

$ source <trilinos-dir>/cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP_env.sh

$ cmake \
  -C <trilinos-dir>/cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teko=ON \
  <trilinos-dir>

$ make -j16

$ ctest -VV -R Teko_testdriver_tpetra_MPI_1
```

## Related Issues

* Blocking Issues: #2462

**Comment by bartlettroscoe** [comment] 2018-05-09 21:15
CC: @trilinos/framework 

@eric-c-cyr, this failure looks identical to the failure reported and addressed in #2652.  But now this error is being triggered by the combination of GCC 4.8.4 and OpenMP being enabled.

Should we just set `Teko_DISABLE_LSCSTABALIZED_TPETRA_ALPAH_INV_D` for this build and disable this one sub-unit test like we dod for #2652?

As mentioned above, the urgency in getting this fixed is that this is blocking turning on OpenMP for the GCC 4.8.4 Trilinos auto PR build.  Currently, there is no Kokkos threading at all being tested in those builds.

**Comment by eric-c-cyr** [comment] 2018-05-10 01:57
Yes lets add that option to disable it. 

@egphill could you look at this in more detail? I'm not sure why this keeps failing.

**Comment by bartlettroscoe** [comment] 2018-05-10 13:25
@trilinos/teko,

I created PR #2715 that disables this one subunit test.  It passed after applying the commit cc675128c980d6d359871b2a06c0a19788d47f6d.

Please approve the PR #2715 so that we can merge after the auto PR testing completes.

**Comment by bartlettroscoe** [comment] 2018-05-10 22:01
I merged PR #2715 so we should see this test for this build passing tomorrow.

**Comment by bartlettroscoe** [comment] 2018-05-11 12:15
This test is now shown passing in this build as shown at:

* https://testing-vm.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3501376

I will now mark this as "Disabled Tests" and "Stalled" and leave it open.

**Comment by prwolfe** [comment] 2018-06-21 13:02
I am seeing this in a gcc 4.9.3 build with openmpi 1.10.1, so it is likely the mph version and not the compiler or OpenMP. I also built in debug and it failed, but I have not checked closer.

**Comment by prwolfe** [comment] 2018-06-21 14:52
Some quick work with cout shows
* this does not fail when run without mpi
* the failure in test_strategy is in iStrat.getOuterStabilization which is protected by an ifdef

`
#ifndef TEKO_DISABLE_LSCSTABALIZED_TPETRA_ALPAH_INV_D
....
#endif
`

which tells me someone has had issues with this before.  Anyone recall what the issue here was?

**Comment by bartlettroscoe** [comment] 2018-06-21 15:28
> Anyone recall what the issue here was?

@prwolfe, yes, take a look [above](https://github.com/trilinos/Trilinos/issues/2712#issuecomment-387878134).

**Comment by prwolfe** [comment] 2018-06-21 16:08
@bartlettroscoe Those comments and issue #2654 discuss what was done, but never come to an understanding of the underlying issue.  I guess thats where it will stand for now.

**Comment by bartlettroscoe** [comment] 2018-06-21 16:42
> but never come to an understanding of the underlying issue

@prwolfe, a Teko developer could not figure out what was going on so just told us to disable these individual unit tests for that build.

**Comment by william76** [comment] 2018-11-19 15:09
@trilinos/teko 

@bartlettroscoe 
@prwolfe 	

Did someone re-enable `Teko_testdriver_tpetra_MPI_1` last week, possibly on the 14th?  This test is failing again in CDash Nightly Clean.

These are the PR's that got [merged on the 14th][2].

@csiefer2 could any of the modifications you made last week on the 14th that touched cmake have turned this guy on? It appears that `Teko_testdriver_tpetra_MPI_1` was disabled by this issue for the PR testing a while ago, but not in nightly clean... which is interesting since it wasn't breaking on nightly clean testing that showed up on the 14/15th.

[1]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-11-15&filtercount=2&showfilters=1&filtercombine=or&field1=groupname&compare1=63&value1=Clean&field2=groupname&compare2=63&value2=Continuous
[2]: https://github.com/trilinos/Trilinos/pulls?utf8=%E2%9C%93&q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+merged%3A2018-11-14+base%3Adevelop+

FYI @trilinos/framework

**Comment by eric-c-cyr** [comment] 2018-11-19 15:17
There is only one test that is failing in this. We should just disable entirely.

**Comment by eric-c-cyr** [comment] 2018-11-19 15:17
There is only one test that is failing in this. We should just disable entirely.

**Comment by eric-c-cyr** [comment] 2018-11-19 16:04
@william76, could you see if this works for you. I was able to reproduce and it fixed locally

**Comment by william76** [comment] 2018-11-19 16:22
@eric-c-cyr Thanks!

**Closed** 2021-07-21 12:24 UTC
Labels: ATDM Sev: Nonblocker, CLOSED_DUE_TO_INACTIVITY, Disabled Tests, MARKED_FOR_CLOSURE, PA: Linear Solvers, Stalled, client: ATDM, pkg: Teko, type: bug
