### ISSUE TITLE
KokkosCore_UnitTest_PushFinalizeHook_terminate

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#2147] opened 2018-01-10 16:17 UTC
KokkosCore_UnitTest_PushFinalizeHook_terminate is failing nightly testing in the Clean track for the GCC 4.9.3 SERIAL Release test (Linux-gcc-4.9.3-SERIAL_Release_gcc_4.9.3__DEV).

Link to CDash test failure: https://testing.sandia.gov/cdash/testDetails.php?test=43875080&build=3321502

@trilinos/kokkos 

### Error Message

> Kokkos::finalize: A finalize hook (set via Kokkos::push_finalize_hook) threw an exception that it did not catch.  Per std::atexit rules, this results in std::terminate.  This is finalize hook number 0 (1-based indexing) out of 1 to call.  Remember that Kokkos::finalize calls finalize hooks in reverse order from how they were pushed.
> PASSED: I am the custom std::terminate handler.

**Comment by mhoemmen** [comment] 2018-01-10 16:25
@william76 Huh, this passes for me.  The test is _supposed_ to do that; in fact, the unit test framework searches for the last line of the above print-out.  

@bartlettroscoe Does the unit test framework on some machines check for abnormal termination too?

**Comment by william76** [comment] 2018-01-10 16:30
@mhoemmen Yeah, it's a little confusing because the output line shows "PASSED"... so I think it's doing what the test expects... is there a special string that's expected in the output by TriBITS to determine pass/fail at the framework level?

**Comment by mhoemmen** [comment] 2018-01-10 16:37
@william76 Check out the CMakeLists.txt file in that directory.  It looks for that PASSED string explicitly.  I think the issue is that on _some_ (not all) systems, the abnormal termination makes the unit test framework think that the test failed.

If this hinders progress, please feel free to disable the test for now by commenting out those lines in the CMakeLists.txt file.  I would like the test to work at some point, because it checks the assertion that uncaught exceptions in finalize hooks cause `std::terminate` to be called.  This makes finalize hooks behave exactly like `atexit` hooks.

**Comment by bartlettroscoe** [comment] 2018-01-11 15:50
I am not sure why CTest thinks this test is failing.  From what I see, CTest should see this test as passing.

It looks like this test was added with:

```
TRIBITS_ADD_EXECUTABLE_AND_TEST(
  UnitTest_PushFinalizeHook_terminate
  SOURCES
    UnitTest_PushFinalizeHook_terminate.cpp
  COMM serial mpi
  NUM_MPI_PROCS 1
  PASS_REGULAR_EXPRESSION "PASSED: I am the custom std::terminate handler."
    TESTONLYLIBS kokkos_gtest ${TEST_LINK_TARGETS}
)
```

which just calls `ADD_TEST()` and sets CTest the property `PASS_REGULAR_EXPRESSION "PASSED: I am the custom std::terminate handler."` and runs the bare executable:

```
/scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly@2/SERIAL_Release_gcc_4.9.3__DEV/BUILD/packages/kokkos/core/unit_test/KokkosCore_UnitTest_PushFinalizeHook_terminate.exe
```

You can see this is the case by looking at the generated CTestConfig.cmake file which shows (on my machine):

```
add_test(KokkosCore_UnitTest_PushFinalizeHook_terminate_MPI_1 "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/5.3.0/openmpi/1.6.5/bin/mpiexec" "-np" "1" "/ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-5.3.0/MPI_RELEASE_DEBUG_SHARED_PT/packages/kokkos/core/unit_test/KokkosCore_UnitTest_PushFinalizeHook_terminate.exe")
set_tests_properties(KokkosCore_UnitTest_PushFinalizeHook_terminate_MPI_1 PROPERTIES  LABELS "Kokkos" PASS_REGULAR_EXPRESSION "PASSED: I am the custom std::terminate handler." PROCESSORS "1" REQUIRED_FILES "/ascldap/users/rabartl/Trilinos.base/BUILDS/GCC-5.3.0/MPI_RELEASE_DEBUG_SHARED_PT/packages/kokkos/core/unit_test/KokkosCore_UnitTest_PushFinalizeHook_terminate.exe")
```

If you look in the implementation file:

```
kokkos/core/unit_test/UnitTest_PushFinalizeHook_terminate.cpp
```

you see this does not use the Teuchos unit test framework.

Therefore, the behavior of this test has nothing to do with TriBITS or the Teuchos UnitTest harness.

One idea is that if Kokkos is printing to std::cerr instead of std::cout, then I have found that CTest PASS_REGULAR_EXPRESSION will not grep that always.  If that is the problem, fix for that is to use TRIBITS_ADD_ADVANCED_TEST() like I did in the commit  624664d82b873f7a6748f45acce0f8b105fc5348.  In fact, given what I see above, that is the first thing I would try.  Just do like I did in the commit  624664d82b873f7a6748f45acce0f8b105fc5348.  In fact, I see that this test is failing in the serial build and not in the MPI build.  That shows that the problem is indeed due to the std::cerr problem with raw CTest.  This is fully explained in the comment in 624664d82b873f7a6748f45acce0f8b105fc5348.

**Comment by mhoemmen** [comment] 2018-01-11 16:19
@bartlettroscoe What was weird to me is that CTest reported the test as passing when I ran it locally.

**Comment by mhoemmen** [comment] 2018-01-11 16:20
@bartlettroscoe I'll try `TRIBITS_ADD_ADVANCED_TEST` -- thanks!  I would like to keep the test if at all possible, because it checks a promise.  It's very easy for those promises to go away (Kokkos churns pretty heavily).

**Comment by bartlettroscoe** [comment] 2018-01-11 18:40
> What was weird to me is that CTest reported the test as passing when I ran it locally.

Did you have MPI enabled?  If so, filtering the raw executable output through `mpiexec` makes it pass.  It is only when you run it in serial that it will fail due to the STDERR vs. STDOUT thing described in https://github.com/trilinos/Trilinos/commit/624664d82b873f7a6748f45acce0f8b105fc5348.

**Comment by mhoemmen** [comment] 2018-01-11 20:01
@bartlettroscoe Ah, yes, that makes sense now.  I ran it with MPI enabled, so it was going through mpiexec.

**Comment by mhoemmen** [comment] 2018-01-11 22:58
The above pull request is for Kokkos.  I will push a separate pull request for Trilinos that has the same fix.

**Comment by william76** [comment] 2018-01-12 21:20
Still failing. :(

https://testing.sandia.gov/cdash/testDetails.php?test=43875080&build=3325118

**Comment by bartlettroscoe** [comment] 2018-01-12 21:34
It has not been updated yet to use TRIBITS_ADD_ADVANCED_TEST().  Look at the command it is running.

**Comment by mhoemmen** [comment] 2018-01-13 03:06
@william76 Ross just merged it two hours ago, no?

@bartlettroscoe Is it OK now?

**Comment by bartlettroscoe** [comment] 2018-01-13 15:26
> @bartlettroscoe Is it OK now?

Looks like it is passing today:

* https://testing.sandia.gov/cdash/viewTest.php?onlydelta&buildid=3327118

Note the changed commandline for the test:

`/projects/sems/install/rhel6-x86_64/sems/utility/cmake/3.5.2/bin/cmake \"-DTEST_CONFIG=\" \"-P\" \"/scratch/trilinos/workspace/trilinos-folder/Trilinos_generic_nightly/SERIAL_Release_gcc_4.9.3__DEV/BUILD/packages/kokkos/core/unit_test/KokkosCore_UnitTest_PushFinalizeHook_terminate.cmake\"`

See, it is a TriBITS ctest -P script that runs the test and checks the results, not raw CTest.  That is why it works now.

Closing as complete.

**Closed by bartlettroscoe** 2018-01-13 15:26 UTC
Labels: Kokkos

**Comment by mhoemmen** [comment] 2018-01-15 17:06
Thanks @bartlettroscoe ! :D
