### ISSUE TITLE
Tempus: Test errors causing PR's to fail.

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#8289] opened 2020-10-30 21:53 UTC
## Bug Report
@trilinos/tempus 

### Description
There are a few tests in Tempus consistently failing in Pull Requests.
CDash link: https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8160802

### Steps to Reproduce
This appears to be only happening in the gcc 8.3.0 PR builds.  See the Master Merge job #8283 for an example.
- [Link to the full CDash output is here][1].

[1]: https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-8283-test&field2=buildstarttime&compare2=84&value2=NOW

**Comment by ccober6** [comment] 2020-10-30 22:15
@william76 So I have been looking at this, and it only fails on ascic166 (note that it does not fail on ascic141, ascic142 or ascic144).  I can not reproduce it on ascic169 (or cee-build013 or my mac).  From what I see so far, my best guess is it is somewhere in Teuchos::ParameterList.

Until I can reproduce it, I do not think I have a chance to debug it.  Do you know who I can talk to about getting access ascic166, as it is the only machine showing this failure?

**Comment by ccober6** [comment] 2020-10-30 22:58
@william76 See #3276 also.

**Comment by william76** [comment] 2020-11-01 16:23
@prwolfe Isn't ascic166 that node which we had issues with in the past that was intermittent and difficult to track down? 
I'll see if I can get on later today during my kiddo's nap and 'disable' ascic166 again like we did in the past.

I'm on baby duty Monday but I'll try and call into our standup meeting :)

@ccober6 thanks for having a look into this. Good catch on the ascic166 node being the only place this seems to be happening.  I'm not sure what you'd need to gain access to them, Paul probably knows. I think we had some issue with that node like a year ago where it would consistently fail jobs but it was tricky to track down since the Jenkins jobs don't always land there on when it dispatches a build... In the meantime, I'll 'disable' the node from our Trilinos build pool when I get a chance later today and see if that makes things happy.

**Comment by prwolfe** [comment] 2020-11-02 14:10
Not that I recall - we did fill it's disk a few times, but I checked that.

**Comment by bartlettroscoe** [comment] 2020-11-02 17:40
FYI: As shown in [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-10-26&end=2020-11-02&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-&field2=buildname&compare2=63&value2=gcc_8.3.0&field3=subprojects&compare3=93&value3=Tempus&field4=testsfailed&compare4=43&value4=0) it looks like there are now 14 different PR test iterations that have failed due to this.  The most recent was on 2020-10-31 (in the 'develop' to 'master' promotion).

**Comment by bartlettroscoe** [comment] 2020-11-02 17:49
CC: @ccober6, @etphipp 

@trilinos/framework, can we please just stop running the `gcc_8.3.0` PR build on the machine 'ascic166'.  As mentioned by @ccober6 [above](https://github.com/trilinos/Trilinos/issues/8289#issuecomment-719824083), if you look at [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-10-26&end=2020-11-02&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=PR-&field2=buildname&compare2=63&value2=gcc_8.3.0&field3=subprojects&compare3=93&value3=Tempus&field4=testspassed&compare4=43&value4=0) it seems that these Tempus tests always pass when run on machines other than 'ascic166' and they always fail when run on 'ascic166'.

This is really impacting people's ability to get their PRs merged so it would be good to just take the easy path and just stop the `gcc_8.3.0` PR builds from running on the machine 'ascic166' for now.

**Comment by ccober6** [comment] 2020-11-09 21:25
It was determined that ascic169 may be the problem as all other platforms pass.  Closing as "Not my problem".  :)

**Closed by ccober6** 2020-11-09 21:25 UTC
Labels: pkg: Tempus, type: bug

**Comment by bartlettroscoe** [comment] 2020-11-09 22:18
> It was determined that ascic169 may be the problem as all other platforms pass. 

@ccober6, how was this resolved then?  Was 'ascic169' taken out of the pool of machines that can run that GCC 8.3.0 build?

**Comment by ccober6** [comment] 2020-11-09 23:19
@bartlettroscoe Yes, I believe so.
