### ISSUE TITLE
Make Ifpack2::RILUK have a proper reuse capability.

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#651] opened 2016-09-23 21:45 UTC
@trilinos/ifpack2, @mhoemmen , @srajama1 

RILUK's symbolic-phase information cannot be reused right now. Users must call initialize() before compute(), always. See, e.g., the logic surrounding
    #define IFPACK2_HAS_PROPER_REUSE
in MueLu_Ifpack2Smoother_def.hpp. This issue is focused on making RILUK have a proper symbolic/numeric/apply division of labor and so a reuse capability.

**Comment by mhoemmen** [comment] 2016-09-23 22:11
Duplicate of #570 -- thanks for reporting and for the additional info, though!

**Closed by mhoemmen** 2016-09-23 22:11 UTC
Labels: duplicate, Ifpack2
