### ISSUE TITLE
New compile error in NOX_LAPACK_LinearSolver.H

### ISSUE THREAD

**Issue by rrdrake** [trilinos/Trilinos#1327] opened 2017-05-16 12:22 UTC
As of a day or two ago, I see this error when compiling:

```
... -c /scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-loca/src-lapack/LOCA_LAPACK_Group.C
In file included from /scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-lapack/NOX_LAPACK_Group.H:58:0,
                 from /scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-loca/src-lapack/LOCA_LAPACK_Group.H:56,
                 from /scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-loca/src-lapack/LOCA_LAPACK_Group.C:51:
/scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-lapack/NOX_LAPACK_LinearSolver.H: In instantiation of bool NOX::LAPACK::Lin
earSolver<T>::solve(bool, int, T*) [with T = std::complex<double>]:
/scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-loca/src-lapack/LOCA_LAPACK_Group.C:593:53:   required from here
/scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos/packages/nox/src-lapack/NOX_LAPACK_LinearSolver.H:258:7: error: no matching function for call to Teuchos::LAPACK<int, std::complex<double> >::GELSS(int&, int&, int&, std::complex<double>*, int&, std::complex<double>*&, int&, std::complex<double>*, int&, int*, std::complex<double>*, int&, int*)
```

The configure line is

```
cmake
    -D Trilinos_SKIP_FORTRANCINTERFACE_VERIFY_TEST:BOOL=ON
    -D CMAKE_INSTALL_PREFIX:PATH="/scratch/rrdrake/devbnb/TPL/trilinos/devel/build/gnu47_opt/inst"
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF
    -D Trilinos_ENABLE_TESTS:BOOL=OFF
    -D Trilinos_ENABLE_Gtest:BOOL=OFF
    -D CMAKE_CXX_COMPILER:FILEPATH="/projects/alegra/mpi/ompi1.6.5_gcc473/bin/mpiCC"
    -D CMAKE_C_COMPILER:FILEPATH="/projects/alegra/mpi/ompi1.6.5_gcc473/bin/mpicc"
    -D CMAKE_Fortran_COMPILER:FILEPATH="gfortran" -DCMAKE_BUILD_TYPE=None
    -D Trilinos_ENABLE_STRONG_C_COMPILE_WARNINGS:BOOL=OFF
    -D Trilinos_ENABLE_STRONG_CXX_COMPILE_WARNINGS:BOOL=OFF
    -D F77_FUNC_:STRING="(name,NAME) name ## _"
    -D F77_FUNC:STRING="(name,NAME) name ##_"
    -D CMAKE_C_FLAGS:STRING="-O2 -funroll-loops -DCODE_MP -DOMPI_SKIP_MPICXX -DNDEBUG"
    -D CMAKE_CXX_FLAGS:STRING="-std=c++11 -O2 -funroll-loops -DCODE_MP -DOMPI_SKIP_MPICXX -DNDEBUG"
    -D CMAKE_Fortran_FLAGS:STRING="-O2 -funroll-loops -DCODE_MP -DOMPI_SKIP_MPICXX -DNDEBUG"
    -D CMAKE_EXE_LINKER_FLAGS:STRING="-Xlinker -rpath -Xlinker /projects/alegra/gcc473/lib64 -L/projects/alegra/gcc473/lib64 -lgfortran"
    -D Trilinos_EXTRA_LINK_FLAGS:STRING="-Xlinker -rpath -Xlinker /projects/alegra/gcc473/lib64 -L/projects/alegra/gcc473/lib64 -lgfortran"
    -D CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES="-Xlinker -rpath -Xlinker /projects/alegra/gcc473/lib64 -L/projects/alegra/gcc473/lib64 -lgfortran" -DCMAKE_AR:STRING="/scratch/rrdrake/devbnb/TPL/trilinos/devel/build/gnu47_opt/ar_dispatch"
    -D TPL_ENABLE_MPI:BOOL=ON
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
    -D Trilinos_ENABLE_Teuchos:BOOL=ON
    -D Trilinos_ENABLE_Triutils:BOOL=ON
    -D Trilinos_ENABLE_Epetra:BOOL=ON
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON
    -D Teuchos_ENABLE_COMPLEX:BOOL=ON
    -D Teuchos_ENABLE_FLOAT:BOOL=ON
    -D Teuchos_ENABLE_STACKTRACE:BOOL=OFF
    -D EpetraExt_BUILD_BTF:BOOL=OFF
    -D EpetraExt_BUILD_EXPERIMENTAL:BOOL=ON
    -D EpetraExt_BUILD_TRANSFORM:BOOL=ON
    -D EpetraExt_BUILD_GRAPH_REORDERINGS=ON
    -D Trilinos_ENABLE_AztecOO:BOOL=ON
    -D AztecOO_ENABLE_AZLU:BOOL=ON
    -D Trilinos_ENABLE_Amesos:BOOL=ON
    -D Amesos_ENABLE_SuperLUDist:BOOL=ON
    -D Amesos_ENABLE_KLU:BOOL=ON
    -D Amesos_ENABLE_UMFPACK:BOOL=ON
    -D Amesos2_ENABLE_KLU2:BOOL=ON
    -D Amesos2_ENABLE_SuperLUDist:BOOL=OFF
    -D Amesos2_ENABLE_Basker:BOOL=ON
    -D Trilinos_ENABLE_Amesos2:BOOL=ON
    -D Trilinos_ENABLE_Anasazi:BOOL=ON
    -D Trilinos_ENABLE_MueLu:BOOL=ON
    -D Trilinos_ENABLE_ML:BOOL=ON
    -D Trilinos_ENABLE_TrilinosCouplings:BOOL=ON
    -D ML_ENABLE_Enrich:BOOL=OFF
    -D Trilinos_ENABLE_Ifpack:BOOL=ON
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON
    -D Trilinos_ENABLE_NOX:BOOL=ON
    -D NOX_BUILD_PRERELEASE:BOOL=OFF
    -D NOX_ENABLE_LOCA:BOOL=ON
    -D Trilinos_ENABLE_Zoltan:BOOL=ON
    -D Trilinos_ENABLE_Isorropia:BOOL=ON
    -D Trilinos_ENABLE_Pamgen:BOOL=ON
    -D Trilinos_ENABLE_Belos:BOOL=ON
    -D NOX_ENABLE_ABSTRACT_IMPLEMENTATION_EPETRA:BOOL=ON
    -D NOX_ENABLE_ABSTRACT_IMPLEMENTATION_LAPACK:BOOL=ON
    -D Trilinos_ENABLE_Shards:BOOL=ON
    -D Trilinos_ENABLE_Rythmos:BOOL=ON
    -D Trilinos_ENABLE_Thyra:BOOL=ON
    -D Trilinos_ENABLE_Stratimikos:BOOL=ON
    -D Trilinos_ENABLE_Sacado:BOOL=ON
    -D Trilinos_ENABLE_Intrepid:BOOL=ON
    -D Trilinos_ENABLE_Intrepid2:BOOL=ON
    -D Intrepid2_ENABLE_Boost:BOOL=ON
    -D Trilinos_ENABLE_KokkosCore:BOOL=ON
    -D TPL_ENABLE_BLAS:BOOL=ON
    -D TPL_ENABLE_LAPACK:BOOL=ON
    -D TPL_BLAS_LIBRARIES:STRING="-L/projects/alegra/TPL/lapackblas/3.0-n1/lib/gnu47_opt -lblas"
    -D TPL_LAPACK_LIBRARIES:STRING="-L/projects/alegra/TPL/lapackblas/3.0-n1/lib/gnu47_opt -llapack"
    -D TPL_ENABLE_y12m:BOOL=ON
    -D y12m_LIBRARY_DIRS:FILEPATH="/projects/alegra/TPL/y12m/1.0/lib/gnu47_opt"
    -D TPL_ENABLE_SuperLUDist:BOOL=ON
    -D SuperLUDist_INCLUDE_DIRS:FILEPATH="/projects/alegra/TPL/superludist/2.0/include"
    -D SuperLUDist_LIBRARY_DIRS:FILEPATH="/projects/alegra/TPL/superludist/2.0/lib/gnu47_opt"
    -D TPL_ENABLE_UMFPACK:BOOL=ON
    -D UMFPACK_INCLUDE_DIRS:FILEPATH="/projects/alegra/TPL/umfpack/4.1/include"
    -D UMFPACK_LIBRARY_DIRS:FILEPATH="/projects/alegra/TPL/umfpack/4.1/lib/gnu47_opt"
    -D TPL_ENABLE_AMD:BOOL=ON
    -D AMD_INCLUDE_DIRS:FILEPATH="/projects/alegra/TPL/umfpack/4.1/include"
    -D AMD_LIBRARY_DIRS:FILEPATH="/projects/alegra/TPL/umfpack/4.1/lib/gnu47_opt"
    -D TPL_ENABLE_ParMETIS:BOOL=ON
    -D ParMETIS_INCLUDE_DIRS:FILEPATH="/projects/alegra/TPL/parmetis/3.1/include"
    -D ParMETIS_LIBRARY_DIRS:FILEPATH="/projects/alegra/TPL/parmetis/3.1/lib/gnu47_opt" "-DBoost_INCLUDE_DIRS=/projects/alegra/TPL/boost/1.54b/include" "-DBoost_LIBRARY_DIRS=/projects/alegra/TPL/boost/1.54b/lib/gnu47_opt" -DBoost_NO_SYSTEM_PATHS:BOOL=ON -DBoost_NO_BOOST_CMAKE:BOOL=ON
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON
    -D Trilinos_VERBOSE_CONFIGURE:BOOL=ON /scratch/rrdrake/devbnb/TPL/trilinos/devel/TrilinosGIT/Trilinos
```

**Comment by ibaned** [comment] 2017-05-16 12:31
@trilinos/nox @trilinos/teuchos

**Comment by krcb** [comment] 2017-05-16 13:13
This is likely related to changes from #1284. @MicheldeMessieres or I should be able to address these later today. @bartlettroscoe this doesn't appear to have been caught by the regular checkin-test approach, nor the CI builds, so we should try and figure out why this happened.

**Comment by ikalash** [comment] 2017-05-16 14:39
Just to provide another data point: this error started for me as well 2 days ago, in my builds with an OpenMP and CUDA KokkosNode (not serial).  Here is the verbose output containing the error in the Albany ride CDash: http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=52803 .

**Comment by jmgate** [comment] 2017-05-16 14:45
@seamill and I were trying to figure this out yesterday&mdash;looks to be related to `-D Teuchos_ENABLE_COMPLEX:BOOL=ON`.

**Comment by krcb** [comment] 2017-05-16 16:45
We think we have a handle on this; it appears that the code concerned is using a legacy GELSS interface that only supports real (not complex) types. When built with complex support enabled an appropriate implementation is not found. The changes that could have resulted in this were made in #1251.

**Comment by rppawlo** [comment] 2017-05-16 17:01
This is from a recent change I made. The argument list just needs to be fixed for complex data types. @hkthorn said she would fix this this morning since she knows the lapack interface and has reproduced it locally.

**Comment by rppawlo** [comment] 2017-05-16 17:04
@krcb - this probably happened because I pushed this change late last week maybe right before your push. It added a new call to the lapack interface and probably was not included in your refactor. The checkin test script doesn't tests complex so it wasn't caught until nightly tests enabled complex.

**Comment by bartlettroscoe** [comment] 2017-05-16 17:10
> The checkin test script doesn't tests complex so it wasn't caught until nightly tests enabled complex.

The basic CI build does not contain complex.  That was a deliberate decision (see #482 and #362).

Hopefully this is not too difficult to fix (most problems with std::complex are not).

**Comment by hkthorn** [comment] 2017-05-16 17:17
@rppawlo @krcb @bartlettroscoe @jmgate I'm on it and testing the fix right now.

**Comment by rppawlo** [comment] 2017-05-16 17:26
Thanks @hkthorn ! Sorry for the disruption.

**Comment by hkthorn** [comment] 2017-10-04 23:07
I think this problem is fixed now.  Closing it.

**Closed by hkthorn** 2017-10-04 23:07 UTC
Labels: build, NOX
