### ISSUE TITLE
Anasazi:  Anasazi Tests failing randomly on ATDM cuda 10 build on ride

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#5221] opened 2019-05-22 14:39 UTC
## Bug Report
CC: @trilinos/anasazi, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
## Description
 There are frequent test failures in the anasazi package on the cuda 10 ride build.  They seem to be random.

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Anasazi_&field3=status&compare3=61&value3=Failed&field4=buildstarttime&compare4=84&value4=2019-05-22T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-05-01T00%3A00%3A00) the tests:
* Anasazi_Epetra_BlockDavidson_auxtest_MPI_4
* Anasazi_Epetra_GeneralizedDavidson_nh_test_MPI_4
* Anasazi_Epetra_GeneralizedDavidson_test_MPI_4
* Anasazi_Epetra_IRTR_auxtest_0_MPI_4
* Anasazi_Epetra_IRTR_auxtest_2_MPI_4
* Anasazi_Epetra_IRTR_auxtest_3_MPI_4
* Anasazi_Epetra_IRTR_auxtest_4_MPI_4
* Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4
* Anasazi_Epetra_OrthoManagerTester_0_MPI_4
* Anasazi_GeneralizedDavidsonThyra_test_MPI_4

have failed at least once in the last 3 weeks in the build:
* Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug

most recently a test failed on 2019-05-20.  Test output shows the following in each test I looked at:

```
[white35:115428:0:115428] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x1000a1d0010)
```

## Current Status on CDash

The current status of the anasazi test suite on this build can be found [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug&field2=testname&compare2=65&value2=Anasazi_&field3=buildstarttime&compare3=84&value3=today&field4=buildstarttime&compare4=83&value4=yesterday)

## Steps to Reproduce

One should be able to reproduce this failure on ride or white as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for ride or white are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ridewhite

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Anasazi=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
```

**Comment by bartlettroscoe** [comment] 2019-08-14 18:24
Closing as duplicate of #5713

**Closed by bartlettroscoe** 2019-08-14 18:24 UTC
Labels: ATDM Env Issue, ATDM Sev: Blocker, PA: Linear Solvers, client: ATDM, pkg: Anasazi, resolved: duplicate, type: bug
