### ISSUE TITLE
Sacado:  Derivative is wrong when using auto type deduction

### ISSUE THREAD

**Issue by amgebauer** [trilinos/Trilinos#11916] opened 2023-05-25 11:09 UTC
## Bug Report
@etphipp

### Description
The derivative becomes zero if `auto` is used for the return type after a mathematical expression with Fad-types.

### Steps to Reproduce
This minimal example demonstrates the problem:

```c++
#include <Sacado.hpp>
#include <iostream>

using FADdouble = Sacado::Fad::DFad<double>;

template <typename Number>
auto multiply(Number number1, Number number2) {
  return number1 * number2;
}

int main() {
  // int
  std::cout << "2*3=" << multiply(2, 3) << "\n"; // prints 2*3=6

  // FAD without auto
  FADdouble x1 = FADdouble(1, 0, 2);
  FADdouble x2 = 3;
  FADdouble result_fad = multiply(x1, x2);
  std::cout << "2*3=" << result_fad << "\n"; // prints 2*3=6 [ 3 ] (correct derivative)

  // FAD with auto
  auto result_auto = multiply(x1, x2);
  std::cout << "2*3=" << result_auto << "\n"; // prints 2*3=6 [ 0 ] (wrong derivative)
  return 0;
}
```

**Comment by etphipp** [comment] 2023-05-25 15:16
This is actually expected behavior.  Sacado uses a technique called expression templates to reduce temporaries in the derivative computation, which means each operation is not evaluated until the whole expression is assigned to a Fad object.  Thus, you should not use `auto` as the return type of expressions involving Fad objects since the result will be the expression object, not a Fad, and it almost always results in unexpected behavior (as in this case).  Unfortunately, I am not aware of any way of preventing users from using `auto` in this way though.

**Comment by etphipp** [comment] 2023-05-25 16:51
Correct.  Not only can this produce incorrect results, it can cause seg faults as, e.g., the compiler is free to deallocate `x` in `test()` before the print statement is executed.

**Comment by etphipp** [comment] 2023-05-25 16:51
Can we close this?

**Closed** 2023-05-25 16:52 UTC
Labels: type: bug
