### ISSUE TITLE
Trilinos install failure

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#303] opened 2016-04-19 14:40 UTC
It looks like starting this morning on the machines where I do nightly tests of Trilinos, as well as other people's nightly test machines, the Trilinos installation no longer works properly.  This is the error: 

[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_Epetra_StokhosMPSolver.cpp.o
[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_Epetra_NECoupledModelEvaluator.cpp.o
[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_PerformSolve.cpp.o
[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_Epetra_PerformSolve.cpp.o
[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_Epetra_PerformAnalysis.cpp.o
[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_PerformAnalysis.cpp.o
Linking CXX static library libpiro.a
[100%] Built target piro
Install the project...
-- Install configuration: "RELEASE"

CMake Error at cmake_install.cmake:44 (FILE):

  file cannot create directory: /cmake.  Maybe need administrative
  privileges.

**Comment by bmpersc** [comment] 2016-04-19 14:47
This is unlikely to be an issue with Trilinos. This looks more like there is something going on with the disk on the machine you are installing on. Based on the error given it looks like it may have been trying to install into "/" which you very likely do not have permissions to create files in and likely not what you intended. This is likely to be caused by an unset variable, either in your configure script or by not setting the install prefix during configure. Can you check to make sure that you are setting the install prefix correctly? Some other things to check are that you do have permissions to create files/directories in the given install location and that the disk is not full. Both of these end up causing very similar errors.

**Comment by bmpersc** [comment] 2016-04-19 15:12
It was reported that another build was suffering from the same issue and I was able to verify that the install path is being set to something reasonable and that they have permissions and plenty of disk space so I did some digging. It does look like there was a change to what is installed for Trilinos, however, this was made nearly 2 weeks ago on 4/5/2016. Can you comment out lines 7-10 of Trilinos/cmake/CallbackSetupExtraOptions.cmake and try installing again. Please let me know if that fixes the issue or not. If it does we'll need to look into a proper fix, but it will at least isolate the issue.

**Comment by bmpersc** [comment] 2016-04-19 17:48
#304 is related to this.

**Comment by bmpersc** [comment] 2016-04-19 18:21
It looks like this was addressed with #304 so closing this issue as well.

**Closed by bmpersc** 2016-04-19 18:21 UTC
