### ISSUE TITLE
Re-definition of default argument (Mac/clang errors) in Tpetra_CrsMatrix_dec.hpp

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#3332] opened 2018-08-22 02:43 UTC
I have a new set of build errors on Mac clang:

/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp:4924:102: error: 
      redefinition of default argument
  ...typename CrsMatrixType::node_type> >& domainMap = Teuchos::null,
                                           ^           ~~~~~~~~~~~~~
/Users/naluIt/gitHubWork/nightlyBuildAndTest/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp:132:102: note: 
      previous definition is here
  ...typename CrsMatrixType::node_type> >& domainMap = Teuchos::null,
                                           ^           ~~~~~~~~~~~~~

These files were touched back on the second. As such, I am not sure if this is a false positive or not as there have been a few build issues today all over the place:)

8027bc1e packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp (Mark Hoemmen          2018-08-02 16:33:58 -0600  132)                                                                typename CrsMatrixType::node_type> >& domainMap = Teuchos::null,

@mhoemmen, any ideas?

**Comment by mhoemmen** [comment] 2018-08-22 02:53
@spdomin Thanks for reporting!  @rppawlo mentioned this too.  It's likely related to #3320.  My guess is that the PR tests don't include an ETI OFF build (do you folks turn on ETI?).

**Comment by mhoemmen** [comment] 2018-08-22 03:50
Confirmed on a local laptop build.  @trilinos/framework @bartlettroscoe this is a little weird -- the changes passed PR testing (see PR #3320, just merged today), but as Stefan points out, the line of code in question wasn't changed too recently.  I've also noticed that PR testing doesn't always pick up on new commits pushed to a branch.  Sometimes it does, but not always or right away.  I wonder if something like that happened here.

**Comment by mhoemmen** [comment] 2018-08-22 04:02
PR #3333 proposes a fix.

**Comment by rppawlo** [comment] 2018-08-22 11:29
This started showing up with the merge yesterday for adding the template aliases #3320 - we always build with ETI and this did break our ETI builds with gcc 7.2. Maybe the template aliases forced something new in the instantiations?

**Comment by rppawlo** [comment] 2018-08-22 11:29
Thanks @mhoemmen !

**Closed by rppawlo** 2018-08-22 11:29 UTC
Labels: Tpetra, TpetraRF, build, in progress

**Comment by jwillenbring** [comment] 2018-08-22 15:13
@mhoemmen 
CC: @trilinos/framework 

It looks like what happened is not that the wrong sha was tested. The issue is that the next test was never reported to CDash. The build number 1092 failed, then the PR was modified, then 1093 failed, this time due to a communication issue that caused it to not be reported to CDash. When you clicked on the link, 1092 was still at the top, and you I suspect (logically) thought that the failure at the top was referring to the most recent test. We are continuing to try to work out these communication issues.

**Comment by dridzal** [comment] 2018-08-22 15:52
We had 50 build failures in ROL last night, with gcc 6.1.0.  Looking at the build errors, which report invalid function arguments in Tpetra, could this be related?

**Comment by mhoemmen** [comment] 2018-08-22 19:15
@jwillenbring Thanks for the report!

**Comment by mhoemmen** [comment] 2018-08-22 19:26
My theory for why this issue didn't show up sooner, is that turning Tpetra classes into type aliases may have changed ADL (argument-dependent lookup) for those functions.
