### ISSUE TITLE
Single Byte libmuelu-adapters.a library for Trilinos develop/Cuda build

### ISSUE THREAD

**Issue by PaulMullowney** [trilinos/Trilinos#11178] opened 2022-10-21 17:02 UTC
This is on Summit with gcc 10.2.0, cuda 11.4.2
Trilinos Hash: 49de2e9a90adf2c79fa3fe6e2e15644cfcc77e58

I see: 
[mullowne@login2.summit trilinos]$ ls -al /gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilinos-develop-cqnylrvaulxligtafv4fs35c4gp35uh3/lib//libmuelu*

-rw-r--r-- 1 mullowne cfd116         8 Oct 20 17:27 /gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilinos-develop-cqnylrvaulxligtafv4fs35c4gp35uh3/lib//libmuelu-adapters.a

-rw-r--r-- 1 mullowne cfd116 235098780 Oct 20 17:27 /gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilinos-develop-cqnylrvaulxligtafv4fs35c4gp35uh3/lib//libmuelu.a

-Paul

**Comment by PaulMullowney** [comment] 2022-10-21 17:23
This could be the same as: 
https://github.com/trilinos/Trilinos/issues/11038

**Comment by cgcgcg** [comment] 2022-10-21 17:27
@PaulMullowney Did you disable Ifpack2 in your build?

**Comment by cgcgcg** [comment] 2022-10-21 17:29
@trilinos/muelu

**Comment by jhux2** [comment] 2022-10-21 17:29
@PaulMullowney Can you post your configure line?

**Comment by PaulMullowney** [comment] 2022-10-21 17:31
'/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/cmake-3.21.3-7st3jbsm6qhqw4hoysgdbpw6butsljtp/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilinos-develop-cqnylrvaulxligtafv4f\
s35c4gp35uh3' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilino\
s-develop-cqnylrvaulxligtafv4fs35c4gp35uh3/lib;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilinos-develop-cqnylrvaulxligtafv4fs35c4gp35uh3/lib64;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/boost-1.76.0-i6yufw6tcvqpwwcyuxfujaj47om2age4/lib;/gpfs/alpine/cfd116/proj-sha\
red/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/cgns-4.3.0-7okqjedzbkzu7ag4oetpit4gfem5hx3u/lib;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/hdf5-1.10.7-ssm3jkqyd3xy46b4nhosfkvrbcjhgzji/lib;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-ht5bw4jruhjujvkzcvp\
ra5lryg5vfhy4/lib;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/hwloc-2.8.0-asjs4kla63qqgszwtbr2vpukrxn7m4cd/lib;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/libxml2-2.9.10-fs2vh7wfmj5eqlljohqzs4dwrtvkjrfi/lib;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/o\
pt/spack/linux-rhel8-ppc64le/gcc-10.2.0/matio-1.5.17-jvqbm5btgokcyzak6mdl63kftvjhyzvr/lib;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/zlib-1.2.11-2rg3opablnzvdehrgcygxseka3hrtoxd/lib;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hw\
o6/lib;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netcdf-c-4.8.1-pms74iwtf3b4hyg5et6xgbitbfbjmxgj/lib;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/parallel-netcdf-1.12.2-ltouogrjcollqxo5smcp3bqgr3zl6slx/lib;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/\
parmetis-4.0.3-6ydhmpbcuopm5d52pwzg7egd3z3d7ko4/lib;/sw/summit/cuda/11.4.2/lib64;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5/lib64' '-DCMAKE_PREFIX_PATH:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/parmetis-4.0\
.3-6ydhmpbcuopm5d52pwzg7egd3z3d7ko4;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hwo6;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/matio-1.5.17-jvqbm5btgokcyzak6mdl63kftvjhyzvr;/gpfs/alpine/c\
fd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/kokkos-nvcc-wrapper-3.2.00-f2b6lo6654yr4teclkqrpjgljeef62pi;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/hwloc-2.8.0-asjs4kla63qqgszwtbr2vpukrxn7m4cd;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-man\
ager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/cgns-4.3.0-7okqjedzbkzu7ag4oetpit4gfem5hx3u;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/parallel-netcdf-1.12.2-ltouogrjcollqxo5smcp3bqgr3zl6slx;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5;/sw/summit/spack\
-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netcdf-c-4.8.1-pms74iwtf3b4hyg5et6xgbitbfbjmxgj;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/zlib-1.2.11-2rg3opablnzvdehrgcygxseka3hrtoxd;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/libxml2-2.9.10-fs2vh7wfmj5eqlljohqzs4dwrtvkjrfi;/sw/summit/cuda/11.4.2;/sw/summit/\
spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-ht5bw4jruhjujvkzcvpra5lryg5vfhy4;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/hdf5-1.10.7-ssm3jkqyd3xy46b4nhosfkvrbcjhgzji;/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/cmake-3.21.3-7st3jbsm6qhqw4hoysgdbpw6butsljtp;/sw/summit/spac\
k-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/boost-1.76.0-i6yufw6tcvqpwwcyuxfujaj47om2age4' '-DTrilinos_VERBOSE_CONFIGURE:BOOL=OFF' '-DBUILD_SHARED_LIBS:BOOL=OFF' '-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF' '-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF' '-DTrilinos_ENABLE_CXX11:BOOL=ON' '-DTrilinos_ENABLE_DEBUG:BOOL=OFF' '-DTrilinos_ENABLE\
_EXAMPLES:BOOL=OFF' '-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON' '-DTrilinos_ENABLE_TESTS:BOOL=OFF' '-DTrilinos_ENABLE_Fortran:BOOL=OFF' '-DTrilinos_ENABLE_OpenMP:BOOL=OFF' '-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON' '-DCMAKE_CXX_STANDARD:STRING=14' '-DTrilinos_ENABLE_Adelus:BOOL=OFF' '-DTrilinos_ENABLE_Amesos:BOOL=OFF' '-DTrilinos\
_ENABLE_Amesos2:BOOL=ON' '-DTrilinos_ENABLE_Anasazi:BOOL=OFF' '-DTrilinos_ENABLE_AztecOO:BOOL=OFF' '-DTrilinos_ENABLE_Belos:BOOL=ON' '-DTrilinos_ENABLE_Epetra:BOOL=OFF' '-DTrilinos_ENABLE_EpetraExt:BOOL=OFF' '-DTrilinos_ENABLE_FEI:BOOL=OFF' '-DTrilinos_ENABLE_Gtest:BOOL=ON' '-DTrilinos_ENABLE_Ifpack:BOOL=OFF' '-DTrilinos_ENABLE_Ifpack2:BOOL=ON\
' '-DTrilinos_ENABLE_Intrepid:BOOL=OFF' '-DTrilinos_ENABLE_Intrepid2:BOOL=OFF' '-DTrilinos_ENABLE_Isorropia:BOOL=OFF' '-DTrilinos_ENABLE_Kokkos:BOOL=ON' '-DTrilinos_ENABLE_MiniTensor:BOOL=OFF' '-DTrilinos_ENABLE_Mesquite:BOOL=OFF' '-DTrilinos_ENABLE_ML:BOOL=OFF' '-DTrilinos_ENABLE_MueLu:BOOL=ON' '-DTrilinos_ENABLE_NOX:BOOL=OFF' '-DTrilinos_ENA\
BLE_Pamgen:BOOL=OFF' '-DTrilinos_ENABLE_Panzer:BOOL=OFF' '-DTrilinos_ENABLE_Pike:BOOL=OFF' '-DTrilinos_ENABLE_Piro:BOOL=OFF' '-DTrilinos_ENABLE_Phalanx:BOOL=OFF' '-DTrilinos_ENABLE_PyTrilinos:BOOL=OFF' '-DTrilinos_ENABLE_ROL:BOOL=OFF' '-DTrilinos_ENABLE_Rythmos:BOOL=OFF' '-DTrilinos_ENABLE_Sacado:BOOL=OFF' '-DTrilinos_ENABLE_SCOREC:BOOL=OFF' '\
-DTrilinos_ENABLE_Shards:BOOL=ON' '-DTrilinos_ENABLE_ShyLU:BOOL=OFF' '-DTrilinos_ENABLE_STK:BOOL=ON' '-DTrilinos_ENABLE_Stokhos:BOOL=OFF' '-DTrilinos_ENABLE_Stratimikos:BOOL=OFF' '-DTrilinos_ENABLE_Teko:BOOL=OFF' '-DTrilinos_ENABLE_Tempus:BOOL=OFF' '-DTrilinos_ENABLE_Thyra:BOOL=OFF' '-DTrilinos_ENABLE_Tpetra:BOOL=ON' '-DTrilinos_ENABLE_Trilino\
sCouplings:BOOL=OFF' '-DTrilinos_ENABLE_Triutils:BOOL=ON' '-DTrilinos_ENABLE_Zoltan:BOOL=ON' '-DTrilinos_ENABLE_Zoltan2:BOOL=ON' '-DEpetraExt_BUILD_BTF:BOOL=OFF' '-DEpetraExt_BUILD_EXPERIMENTAL:BOOL=OFF' '-DEpetraExt_BUILD_GRAPH_REORDERINGS:BOOL=OFF' '-DAmesos2_ENABLE_Basker:BOOL=OFF' '-DAmesos2_ENABLE_LAPACK:BOOL=ON' '-DTrilinos_ENABLE_SEACAS\
:BOOL=ON' '-DTrilinos_ENABLE_SEACASExodus:BOOL=ON' '-DTrilinos_ENABLE_SEACASIoss:BOOL=ON' '-DTrilinos_ENABLE_SEACASEpu:BOOL=ON' '-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON' '-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON' '-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON' '-DTrilinos_ENABLE_SEACASChaco:BOOL=OFF' '-DTrilinos_ENABLE_SEACASNemslice:BOOL=OFF' '-D\
TPL_ENABLE_ADIOS2:BOOL=OFF' '-DTPL_ENABLE_Boost:BOOL=ON' '-DBoost_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/boost-1.76.0-i6yufw6tcvqpwwcyuxfujaj47om2age4/include' '-DBoost_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/boost-1.76.0-i6yufw6tcvqpwwcyuxfujaj47om2age4' '-DBoost_LIB\
RARY_NAMES:STRING=boost_graph;boost_graph_parallel;boost_graph-mt;boost_graph_parallel-mt;boost_prg_exec_monitor;boost_prg_exec_monitor-mt' '-DBoost_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/boost-1.76.0-i6yufw6tcvqpwwcyuxfujaj47om2age4/lib' '-DTPL_ENABLE_CUDA:BOOL=ON' '-DCUDA_INCLUDE_DIRS:STRING=/sw/sum\
mit/cuda/11.4.2/include' '-DCUDA_ROOT:STRING=/sw/summit/cuda/11.4.2' '-DCUDA_LIBRARY_NAMES:STRING=cudart' '-DCUDA_LIBRARY_DIRS:STRING=/sw/summit/cuda/11.4.2/lib64' '-DTPL_ENABLE_HDF5:BOOL=ON' '-DHDF5_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/hdf5-1.10.7-ssm3jkqyd3xy46b4nhosfkvrbcjhgzji/include' '-DHDF5_R\
OOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/hdf5-1.10.7-ssm3jkqyd3xy46b4nhosfkvrbcjhgzji' '-DHDF5_LIBRARY_NAMES:STRING=hdf5' '-DHDF5_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/hdf5-1.10.7-ssm3jkqyd3xy46b4nhosfkvrbcjhgzji/lib' '-DTPL_ENABLE_HYPRE:BOOL=OFF' '-DTPL_ENABLE_MUMPS:B\
OOL=OFF' '-DTPL_ENABLE_UMFPACK:BOOL=OFF' '-DTPL_ENABLE_SuperLU:BOOL=OFF' '-DTPL_ENABLE_SuperLUDist:BOOL=OFF' '-DTPL_ENABLE_X11:BOOL=OFF' '-DTPL_ENABLE_STRUMPACK:BOOL=OFF' '-DTPL_ENABLE_BLAS:BOOL=ON' '-DBLAS_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5/inc\
lude' '-DBLAS_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5' '-DBLAS_LIBRARY_NAMES:STRING=blas' '-DBLAS_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5/lib64' '-DTPL_ENABLE_CGNS\
:BOOL=ON' '-DCGNS_INCLUDE_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/cgns-4.3.0-7okqjedzbkzu7ag4oetpit4gfem5hx3u/include' '-DCGNS_ROOT:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/cgns-4.3.0-7okqjedzbkzu7ag4oet\
pit4gfem5hx3u' '-DCGNS_LIBRARY_NAMES:STRING=cgns' '-DCGNS_LIBRARY_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/cgns-4.3.0-7okqjedzbkzu7ag4oetpit4gfem5hx3u/lib' '-DTPL_ENABLE_LAPACK:BOOL=ON' '-DLAPACK_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-1\
0.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5/include' '-DLAPACK_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-lapack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5' '-DLAPACK_LIBRARY_NAMES:STRING=lapack' '-DLAPACK_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netlib-l\
apack-3.9.1-ehzlxfcscrj6q5vzslpicc7woxv6vmx5/lib64' '-DTPL_ENABLE_Matio:BOOL=ON' '-DMatio_INCLUDE_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/matio-1.5.17-jvqbm5btgokcyzak6mdl63kftvjhyzvr/include' '-DMatio_ROOT:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/sp\
ack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/matio-1.5.17-jvqbm5btgokcyzak6mdl63kftvjhyzvr' '-DMatio_LIBRARY_NAMES:STRING=matio' '-DMatio_LIBRARY_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/matio-1.5.17-jvqbm5btgokcyzak6mdl63kftvjhyzvr/lib' '-DTPL_ENABLE_METIS:BOOL=ON' '-DME\
TIS_INCLUDE_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hwo6/include' '-DMETIS_ROOT:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hw\
o6' '-DMETIS_LIBRARY_NAMES:STRING=metis' '-DMETIS_LIBRARY_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hwo6/lib' '-DTPL_ENABLE_Netcdf:BOOL=ON' '-DNetcdf_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/n\
etcdf-c-4.8.1-pms74iwtf3b4hyg5et6xgbitbfbjmxgj/include' '-DNetcdf_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netcdf-c-4.8.1-pms74iwtf3b4hyg5et6xgbitbfbjmxgj' '-DNetcdf_LIBRARY_NAMES:STRING=netcdf' '-DNetcdf_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/netcdf-c-4.8.1-pms74iwtf3\
b4hyg5et6xgbitbfbjmxgj/lib' '-DTPL_ENABLE_SCALAPACK:BOOL=OFF' '-DTPL_ENABLE_Zlib:BOOL=ON' '-DZlib_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/zlib-1.2.11-2rg3opablnzvdehrgcygxseka3hrtoxd/include' '-DZlib_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/zlib-1.2.11-2rg3opablnzvdehrg\
cygxseka3hrtoxd' '-DZlib_LIBRARY_NAMES:STRING=z' '-DZlib_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/zlib-1.2.11-2rg3opablnzvdehrgcygxseka3hrtoxd/lib' '-DTPL_ENABLE_Pnetcdf:BOOL=ON' '-DPnetcdf_INCLUDE_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/parallel-netcdf-1.12.2-ltouogrjc\
ollqxo5smcp3bqgr3zl6slx/include' '-DPnetcdf_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/parallel-netcdf-1.12.2-ltouogrjcollqxo5smcp3bqgr3zl6slx' '-DPnetcdf_LIBRARY_NAMES:STRING=pnetcdf' '-DPnetcdf_LIBRARY_DIRS:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/parallel-netcdf-1.12.2-ltouogrjcollq\
xo5smcp3bqgr3zl6slx/lib' '-DTPL_ENABLE_HWLOC:BOOL=ON' '-DHWLOC_INCLUDE_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/hwloc-2.8.0-asjs4kla63qqgszwtbr2vpukrxn7m4cd/include' '-DHWLOC_ROOT:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-pp\
c64le/gcc-10.2.0/hwloc-2.8.0-asjs4kla63qqgszwtbr2vpukrxn7m4cd' '-DHWLOC_LIBRARY_NAMES:STRING=hwloc' '-DHWLOC_LIBRARY_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/hwloc-2.8.0-asjs4kla63qqgszwtbr2vpukrxn7m4cd/lib' '-DTPL_ENABLE_MPI:BOOL=ON' '-DCMAKE_C_COMPILER:STRING=/sw/summit\
/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-ht5bw4jruhjujvkzcvpra5lryg5vfhy4/bin/mpicc' '-DCMAKE_CXX_COMPILER:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-ht5bw4jruhjujvkzcvpra5lryg5vfhy4/bin/mpicxx' '-DCMAKE_Fortran_COMPILER:STRING=/sw/summit/spack-e\
nvs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-ht5bw4jruhjujvkzcvpra5lryg5vfhy4/bin/mpif90' '-DMPI_BASE_DIR:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.3-20210112-ht5bw4jruhjujvkzcvpra5lryg5vfhy4' '-DTPL_ENABLE_ParMETIS:BOOL=ON' '-DParMETIS_LIBRARY_DIRS:STRING=/gpfs/alpin\
e/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/parmetis-4.0.3-6ydhmpbcuopm5d52pwzg7egd3z3d7ko4/lib;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hwo6/lib' '-DParMETIS_LIBRARY_NAMES:STRING=parmetis;metis' '\
-DTPL_ParMETIS_INCLUDE_DIRS:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/parmetis-4.0.3-6ydhmpbcuopm5d52pwzg7egd3z3d7ko4/include;/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/metis-5.1.0-6juzlrbmtcnayvt5qhfw4e46yxf3hwo6/inclu\
de' '-DTPL_Netcdf_Enables_Netcdf4:BOOL=ON' '-DTPL_Netcdf_PARALLEL:BOOL=ON' '-DPNetCDF_ROOT:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/parallel-netcdf-1.12.2-ltouogrjcollqxo5smcp3bqgr3zl6slx' '-DTPL_ENABLE_Cholmod:BOOL=OFF' '-DTeuchos_ENABLE_COMPLEX:BOOL=OFF' '-DTeuchos_ENABLE_FLOAT:BOOL=OFF' '-DTpetra_INST_OPENMP:BOOL\
=OFF' '-DTpetra_INST_DOUBLE:BOOL=ON' '-DTpetra_INST_COMPLEX_DOUBLE:BOOL=OFF' '-DTpetra_INST_COMPLEX_FLOAT:BOOL=OFF' '-DTpetra_INST_FLOAT:BOOL=OFF' '-DTpetra_INST_SERIAL:BOOL=ON' '-DTpetra_INST_INT_INT:BOOL=OFF' '-DTpetra_INST_INT_LONG:BOOL=ON' '-DTpetra_INST_INT_LONG_LONG:BOOL=OFF' '-DKokkos_ENABLE_CUDA:BOOL=ON' '-DKokkos_ENABLE_OPENMP:BOOL=OF\
F' '-DKokkos_ENABLE_CUDA_UVM:BOOL=ON' '-DKokkos_ENABLE_CUDA_LAMBDA:BOOL=ON' '-DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON' '-DKokkos_ARCH_VOLTA70:BOOL=ON' '-DCMAKE_INSTALL_NAME_DIR:STRING=/gpfs/alpine/cfd116/proj-shared/mullowne/spack-manager/spack/opt/spack/linux-rhel8-ppc64le/gcc-10.2.0/trilinos-develop-cqnylrvaulxligtafv4fs35c4gp35u\
h3/lib' '-DSTK_ENABLE_TESTS:BOOL=OFF' '-DSEACAS_ENABLE_SEACASSupes:BOOL=OFF' '-DTrilinos_ENABLE_SEACASSupes:BOOL=OFF' '/gpfs/alpine/proj-shared/cfd116/mullowne/spack-manager/environments/nalu-dev-trilinos-develop_gcc-10.2.0_cuda-11.4.2/trilinos'

**Comment by cgcgcg** [comment] 2022-10-21 17:32
`Trilinos_ENABLE_Ifpack2:BOOL=ON`, so I don't think this is https://github.com/trilinos/Trilinos/issues/11038

**Comment by cgcgcg** [comment] 2022-10-21 17:35
@PaulMullowney Not sure if that's the issue, but could you pull develop and try again?

**Comment by PaulMullowney** [comment] 2022-10-21 17:36
Ok.

**Comment by PaulMullowney** [comment] 2022-10-21 17:49
No luck.

**Comment by cgcgcg** [comment] 2022-10-21 19:09
Hm. @jhux2 will try to reproduce.

**Comment by jhux2** [comment] 2022-10-21 19:26
Ok, I can reproduce.

**Comment by jhux2** [comment] 2022-10-21 22:12
The root cause is that after #11100, it's possible that there are no sources to add to `libmuelu-adapters.a`, but it's unconditionally created.  I see two possibilities:

1. Create a dummy file so that the library is never empty.
2. If the source list is empty, don't create the library.

Does ExaWind or any other app we know of assume the existence of `libmuelu-adapters`?

**Comment by jhux2** [comment] 2022-10-21 22:35
@PaulMullowney A PR is up to fix this.  After it merges, `libmuelu-adapters` will be generated only if there are adapter source files to be added.

**Comment by PaulMullowney** [comment] 2022-10-22 01:44
Excellent. Thanks for working through this so quickly!

**Comment by jhux2** [comment] 2022-10-25 18:11
@PaulMullowney FYI, PR has merged.

**Comment by vbrunini** [comment] 2022-10-25 18:21
It looks like #11100 also removed `libmuelu-interface`, is that permanently gone and downstream usage should just link against `libmuelu.a` now?

**Comment by jhux2** [comment] 2022-10-25 20:26
> It looks like #11100 also removed `libmuelu-interface`, is that permanently gone and downstream usage should just link against `libmuelu.a` now?

@vbrunini That's correct.

**Comment by jhux2** [comment] 2022-10-27 14:34
@vbrunini I had to reintroduce `libmuelu-interface` in order to get cmake to capture the path to all required headers and install them. See #11199.

**Comment by jhux2** [comment] 2022-11-02 19:05
Closing as resolved (https://github.com/trilinos/Trilinos/pull/11199#issuecomment-1293883800).

**Closed by jhux2** 2022-11-02 19:05 UTC
Labels: type: bug, pkg: MueLu
