### ISSUE TITLE
Intrepid2: Warnings....

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#8554] opened 2021-01-08 20:30 UTC
## Enhancement
@trilinos/intrepid2

@mperego, I think that you use celltools in a wrong way. A device level code is included in the following projection tools. It also causes host device warnings. This needs to be fixed.

```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefL2.hpp(389): warning: calling a __host__ function("Intrepid2::CellTools< ::Kokkos::Cuda> ::mapToReferenceSubcell<double,  ::Kokkos::LayoutStride,  ::Kokkos::Device< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> ,  ::Kokkos::MemoryTraits<(unsigned int)0u>  , double,  ::Kokkos::LayoutStride,  ::Kokkos::Device< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> ,  ::Kokkos::MemoryTraits<(unsigned int)0u>  > ") from a __host__ __device__ function(" const") is not allowed

/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefL2.hpp(409): warning: calling a __host__ function("Intrepid2::CellTools< ::Kokkos::Cuda> ::mapToReferenceSubcell<double,  ::Kokkos::LayoutStride,  ::Kokkos::Device< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> ,  ::Kokkos::MemoryTraits<(unsigned int)0u>  , double,  ::Kokkos::LayoutStride,  ::Kokkos::Device< ::Kokkos::Cuda,  ::Kokkos::CudaUVMSpace> ,  ::Kokkos::MemoryTraits<(unsigned int)0u>  > ") from a __host__ __device__ function(" const") is not allowed
```

@CamelliaDPG There is warning in your code.

Currently the variable is used for compiling on host but it is not used with cuda. I am not sure how this code can pass the PR test but I see the following warnings. Would you please fix the warnings ? I compile the code with "Intrepid2_ENABLE_DEBUG"
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Shared/Intrepid2_TensorViewIterator.hpp(140): warning: variable "contracting" was set but never used
```

**Comment by kyungjoo-kim** [comment] 2021-01-08 21:10
@mperego Now I realize why the host device warnings are blocking for uvm removal. Without relying on uvm, we need to use explicit deep copy between host and device. Previously, assignment operator works with uvm and it can move data between host and device. So, your projection code might work generously. Without uvm, it cannot work. We first need to find a solution to replace your usage of cell tools to proceed uvm removal.

**Comment by CamelliaDPG** [comment] 2021-01-08 21:31
@kyungjoo-kim, I believe the warning in TensorViewIterator is resolved as part of #8457; this is very close to being merged.  (All PR tests are passing, but I'm still working on fixing a CUDA failure I'm seeing in tests on vortex.)

**Comment by mperego** [comment] 2021-01-08 22:29
@kyungjoo-kim OK, I think tha'ts easy to fix using `Impl::OrientationTools::mapSubcellCoordsToRefCell` as I did in the other projectionTools, I guess I forgot to fix that in the L2 one. I'll fix that.

**Comment by mperego** [comment] 2021-01-11 21:29
@kyungjoo-kim are these warnings gone now?

**Comment by kyungjoo-kim** [comment] 2021-01-11 21:50
@mperego I have not tested it yet. I will assure it later today.

**Comment by mperego** [comment] 2021-01-11 21:56
No rush. Thanks.

**Comment by kyungjoo-kim** [comment] 2021-01-11 22:01
@mperego Your warnings seems to be gone. There are other warnings which might be treated by @CamelliaDPG 
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Shared/Intrepid2_Data.hpp(56): warning: variable "otherNominalExtent" was declared but never referenced
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Shared/Intrepid2_Data.hpp(305): warning: variable "expectedDataExtent" was declared but never referenced
```
This warnings are legit and must be addressed.
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Cell/Intrepid2_CellGeometryDef.hpp(1056): warning: calling a __host__ function("Teuchos::RCP< ::Intrepid2::Basis< ::Kokkos::Cuda, double, double> > ::~RCP") from a __host__ __device__ function("Intrepid2::CellGeometry<double, (int)1,  ::Kokkos::Cuda> ::~CellGeometry") is not allowed
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Shared/Intrepid2_CellGeometryTestUtils.hpp(90): warning: calling a __host__ function("Teuchos::RCP< ::Intrepid2::Basis< ::Kokkos::Cuda, double, double> > ::RCP") from a __host__ __device__ function("") is not allowed
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/src/Cell/Intrepid2_CellToolsDefJacobian.hpp(432): warning: calling a __host__ function("shards::CellTopology::CellTopology") from a __host__ __device__ function("") is not allowed
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/unit-test/MonolithicExecutable/ProjectedGeometryTests.cpp(254): warning: calling a __host__ function("shards::CellTopology::CellTopology") from a __host__ __device__ function("") is not allowed
```

**Comment by mperego** [comment] 2021-01-11 22:39
@kyungjoo-kim how can we reproduce these warnings?

**Comment by kyungjoo-kim** [comment] 2021-01-11 22:40
@mperego compile the code with enabling cuda and debug flag (-D Intrepid2_ENABLE_DEBUG=ON).

**Comment by mperego** [comment] 2021-01-11 22:46
OK, thanks. @CamelliaDPG to avoid issue with the cellTopology, you might be able to use the cell topology key instead, which can be used on device. I've done that a lot for the projections.

**Comment by CamelliaDPG** [comment] 2021-01-11 22:51
@kyungjoo-kim, thanks for alerting me to this.  I'm not sure how best to fix the `__host__ function` warnings, though.  It looks like these are (all?) coming from the destructor of CellGeometry.  CellGeometry has members of types (including CellTopology, RCP<Basis>) that are not CUDA-aware, so its destructor will call their destructors.  Do you have any suggestion for the best way to handle this?  I'd very much prefer not to have to redesign CellGeometry so that it doesn't have such members (and I'm not clear on how destructors work within device code).

**Comment by kyungjoo-kim** [comment] 2021-01-11 22:58
I think that you should not use RCP. Using RCP in a device code is very dangerous (actually it does not make sense at all). The array rcp pointer mostly indicates host address and it does not give you information where the memory is located even if the pointer indicates to device address. You need to remove all RCP things if your intention is to use the code on device.

**Comment by CamelliaDPG** [comment] 2021-01-11 23:01
@kyungjoo-kim, I don't use the RCP in device code.  It is a member of CellGeometry, which provides device implementation of `operator()`, among other things.

**Comment by CamelliaDPG** [comment] 2021-01-11 23:07
To be clear, I'm also not constructing CellGeometry on device.  Given that, I'm not sure why the destructor is getting called (if it is indeed getting called).

**Comment by kyungjoo-kim** [comment] 2021-01-11 23:10
I did not take a look at the details but the warning message is somewhere in a device code calls basis destructor which is RCP. Even if you do not directly use the RCP in the device code, the warning message indicate that the code is used. Considering the nature of the RCP, any assignment operator of the RCP object will access a host code to increase/decrease the reference counting.

**Comment by CamelliaDPG** [comment] 2021-01-11 23:28
@kyungjoo-kim, OK, thanks for the guidance.  I'll see what I can figure out.

**Closed** 2021-03-26 03:57 UTC
Labels: type: enhancement
