### ISSUE TITLE
New timed-out Amesos2 tests in Trilinos-atdm-sems-gcc-7-2-0 build on 2/20/2018

### ISSUE THREAD

**Issue by bartlettroscoe** [trilinos/Trilinos#2270] opened 2018-02-20 23:07 UTC
**CC:** @trilinos/amesos2

##  Next Action Status 

The tests were disabled in all `Trilinos_ENABLE_DEBUG=ON` builds on 2/22/2018 (see [below](https://github.com/trilinos/Trilinos/issues/2270#issuecomment-367815146)).  Next: Fix the tests so that they pass?

## Description

The tests:

* Amesos2_KLU2_UnitTests_MPI_2
* Amesos2_Superlu_UnitTests_MPI_2

timed out at 10 minutes in the build `Trilinos-atdm-sems-gcc-7-2-0` this morning as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3396946

Prior to this morning, these tests were taking:

* Amesos2_KLU2_UnitTests_MPI_2: 1.5s
* Amesos2_Superlu_UnitTests_MPI_2: 1.7s

It looks like these tests are hanging due to an exception being thrown?

## Steps to Reproduce

Using the `do-configure` script:

```
#!/bin/bash
cmake \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/sems/atdm/SEMSATDMSettings.cmake,cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake \
-DDART_TESTING_TIMEOUT:STRING=300.0 \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DCTEST_BUILD_FLAGS=-j10 \
-DCTEST_PARALLEL_LEVEL=10 \
"$@" \
$TRILINOS_DIR
```

Anyone should be able to reproduce these failures on any SNL COE RHEL6 machine as shown below:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/sems/atdm/load_atdm_7.2_dev_env.sh

$ ./do-configure -DTrilinos_ENABLE_Amesos2=ON

$ make -j16

$ ctest -j16
```

NOTE: The timeout like `-DDART_TESTING_TIMEOUT:STRING=300.0` is important or ctest will never end.

**Comment by bartlettroscoe** [comment] 2018-02-20 23:10
I think it is worth waiting to see what happens for this build tomorrow.  If these two tests timeout again, then this is not a fluke and someone needs to debug this (at which time I will post exact reproduceability instructions).

**Comment by bartlettroscoe** [comment] 2018-02-20 23:38
I don't think this is a fluke from looking at:

* https://testing.sandia.gov/cdash/testSummary.php?project=1&name=Amesos2_KLU2_UnitTests_MPI_2&date=2018-02-20
* https://testing.sandia.gov/cdash/testSummary.php?project=1&name=Amesos2_Superlu_UnitTests_MPI_2&date=2018-02-20

it looks like all of the "Debug" builds have these tests timing out.   From looking at the test output:

```

 p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  MultiVector unpack kernel had 2 out-of bounds index/ices.  Here they are: [-1, -1].
 [FAILED]  (0.0132 sec) Superlu_double_int_int_NonContgGID_UnitTest
 Location: /jenkins/slave/workspace/Trilinos-atdm-sems-gcc-7-2-0/SRC_AND_BUILD/Trilinos/packages/amesos2/test/solvers/Superlu_UnitTests.cpp:379
 

The following tests FAILED:
    5. Superlu_double_int_int_NonContgGID_UnitTest ... 
```

Therefore, I think these tests are hanging because rank 0 is throwing in a debug-mode build and not rank 1.  Therefore, I think this test needs to be debugged and fixed.

I will post exact reproducability instructions.  And I suspect that this hanging might be avoided by switching to the MPI driver for the unit test harness (but I will look).  But the test will still fail.

Looking at the new commits pulled for this build at:

* https://testing.sandia.gov/cdash/viewNotes.php?buildid=3397161##note4

there are no commits to the Amesos2 package itself so some change to one of the upstream packages must have triggered this but it is not obvious which commit this might be.

Can someone on the @trilinos/amesos2 team look into this?

**Comment by ndellingwood** [comment] 2018-02-20 23:55
@bartlettroscoe is this a new configuration that is being tested? No changes have been made in Amesos2 since Nov 30 - the most recent commit I see is 4cc536243e01657dd42551e79af0002053ce901d
I wonder if some recent changes either exposed a bug or have a bug...

I don't think I'll get to look at this until some point tomorrow, should I remove the test in the meantime to clean the nightlies up?

**Comment by bartlettroscoe** [comment] 2018-02-21 01:31
@ndellingwood, thanks for looking into this.  We can disable this test if you want but I think that it is okay to let it fail again tonight if you can fix this tomorrow.  If not, then we can disable this test in debug builds for now and then you can fix it offline without pressure.  This test passes fine in a non-debug build so customers would not likely trigger this problem since they would do a non-debug build usually.

And as I said above, I don't think any changes to Amesos2 caused this failure.  It looks like some change to an upstream package caused this failure.  We could run git bisect on the new commits pulled and figure this out to be sure but it might be just as easy to debug this.   These tests don't get run by the standard CI build because they are marked as "NIGHTLY" for some reason as shown at:

* https://testing-vm.sandia.gov/cdash/viewConfigure.php?buildid=3325740

which shows:

```
Processing enabled package: Amesos2 (Libs, Tests, Examples)
...
-- Amesos2_KLU2_UnitTests: NOT added test because Trilinos_TEST_CATEGORIES='BASIC' does not match this test's CATEGORIES='NIGHTLY'!
...
-- Amesos2_Superlu_UnitTests: NOT added test because Trilinos_TEST_CATEGORIES='BASIC' does not 
```

These tests run pretty fast usually (less than 2s) so should they not be elevated to "BASIC" tests?  That way they would get run in CI testing and automated PR testing and help to protect them.  Can you make that change?

If you look at the configure output you will also see that one of the tests are not getting run an MPI build as well:

```
-- Amesos2_klu2_simple: NOT added test because TPL_ENABLE_MPI='ON' and COMM='serial'!
```

Can we just define this run with "NUM_MPI_PROCS 1" and let it run in an MPI build as well?  Would that be hard to do?  That way it will get run more and help to protect it.

In any case, I added a "Steps to Reproduce" section above to describe how to reproduce (which I am running right now for myself to make sure I can reproduce this locally).

**Comment by bartlettroscoe** [comment] 2018-02-21 13:55
I followed the above "Steps to Reproduce" on the CEE-LAN machine ceerws1113 and I got:

```
82% tests passed, 2 tests failed out of 11

Subproject Time Summary:
Amesos2    = 1246.83 sec*proc (11 tests)

Total Test time (real) = 300.11 sec

The following tests FAILED:
          1 - Amesos2_KLU2_UnitTests_MPI_2 (Timeout)
          3 - Amesos2_Superlu_UnitTests_MPI_2 (Timeout)
```

Note that you can likely also reproduce this failure on any debug-mode build by configuring with `-DTrilinos_TEST_CATEGORIES=NIGHTLY` when configuring.  For example, you could do this with the standard SEMS env:

* https://github.com/trilinos/Trilinos/wiki/SEMS-Dev-Env

**Comment by srajama1** [comment] 2018-02-21 15:08
If I have to bet on what could have caused the failure among the commits Ross pointed out, I would bet on the Tpetra map changes.

@trilinos/tpetra @trilinos/muelu @lucbv @kddevin

**Comment by lucbv** [comment] 2018-02-21 15:45
@srajama1, the Tpetra map change is essentially a change in the logic of Tpetra map. It is probably a good thing that it makes other packages fail because it exposed a fragile handling of maps that might have no GIDs on a rank, this happens when you want to repartition.
More information on what was done to the Tpetra map can be found in this #2250 issue.

**Comment by mhoemmen** [comment] 2018-02-21 16:21
@bartlettroscoe I'm curious if this is related to the "check-in tests != PR testing" issue.

**Comment by ndellingwood** [comment] 2018-02-21 17:54
@bartlettroscoe - @lucbv discussed the changes in #2250 with me for maps. 
I'll post a summary of what was done in Amesos2 to handle maps with non-contiguous GIDs to resolve issue #889, this unit test exercises that added functionality and it would be good to confirm that behavior of the Tpetra routines used in those routines has not changed. 

@bartlettroscoe I won't have a chance to look more carefully at this until later today, I have some PRs in progress needed for kokkos integration testing for the next snapshot into Trilinos, so it is probably better to disable the tests until I can help diagnose underlying issues.

**Comment by lucbv** [comment] 2018-02-21 18:50
@ndellingwood I think I caught something in debug mode, here is what the test returns now:

```
8. KLU2_double_int_int_NonContgGID_UnitTest ...  0: computeGatherMap:
  0: computeGatherMap: Calling createOneToOne
 1: computeGatherMap:
  1: computeGatherMap: Calling createOneToOne
  0: computeGatherMap: Gathering Map counts
  1: computeGatherMap: Gathering Map counts
  1: computeGatherMap: Computing MPI_Gatherv displacements
  0: computeGatherMap: Computing MPI_Gatherv displacements
  1: computeGatherMap: Calling MPI_Gatherv
  1: computeGatherMap: Creating gather Map
  0: computeGatherMap: Calling MPI_Gatherv
  0: computeGatherMap: Creating gather Map
 0: computeGatherMap: done
 1: computeGatherMap: done
 1: computeGatherMap:
  1: computeGatherMap: Calling createOneToOne
 0: computeGatherMap:
  0: computeGatherMap: Calling createOneToOne
  1: computeGatherMap: Gathering Map counts
  0: computeGatherMap: Gathering Map counts
  1: computeGatherMap: Computing MPI_Gatherv displacements
  0: computeGatherMap: Computing MPI_Gatherv displacements
  0: computeGatherMap: Calling MPI_Gatherv
  0: computeGatherMap: Creating gather Map
  1: computeGatherMap: Calling MPI_Gatherv
  1: computeGatherMap: Creating gather Map
 1: computeGatherMap: done
 0: computeGatherMap: done
 0: computeGatherMap:
  0: computeGatherMap: Calling createOneToOne
 1: computeGatherMap:
  1: computeGatherMap: Calling createOneToOne
  1: computeGatherMap: Gathering Map counts
  0: computeGatherMap: Gathering Map counts
  1: computeGatherMap: Computing MPI_Gatherv displacements
  0: computeGatherMap: Computing MPI_Gatherv displacements
  0: computeGatherMap: Calling MPI_Gatherv
  0: computeGatherMap: Creating gather Map
  1: computeGatherMap: Calling MPI_Gatherv
  1: computeGatherMap: Creating gather Map
 0: computeGatherMap: done
 1: computeGatherMap: done

 
 p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  MultiVector unpack kernel had 2 out-of bounds index/ices.  Here they are: [-1, -1].
 [FAILED]  (0.0358 sec) KLU2_double_int_int_NonContgGID_UnitTest
 Location: /home/lberge/Research/Trilinos_checkin/packages/amesos2/test/solvers/KLU2_UnitTests.cpp:383
 
 1: computeGatherMap:
  1: computeGatherMap: Calling createOneToOne
9. KLU2_double_int_int_ComplexSolve_UnitTest ... 
 
 p=0: *** Caught standard std::exception of type 'std::invalid_argument' :
 
  /home/lberge/Research/Trilinos_checkin/packages/tpetra/core/src/Tpetra_Map_def.hpp:129:
  
  Throw number = 1
  
  Throw test that evaluated to true: minNumGlobalElements != maxNumGlobalElements || numGlobalElements != minNumGlobalElements
  
  Tpetra::Map constructor: All processes must provide the same number of global elements.  Process 0 set numGlobalElements = 3.  The calling process 0 set numGlobalElements = 3.  The min and max values over all processes are 3 resp. 10.
 [FAILED]  (0.000539 sec) KLU2_double_int_int_ComplexSolve_UnitTest
 Location: /home/lberge/Research/Trilinos_checkin/packages/amesos2/test/solvers/KLU2_UnitTests.cpp:550
```

I will chase this down and see if I can find an appropriate fix in `Tpetra` or `Amesos2`.

**Comment by mhoemmen** [comment] 2018-02-22 00:45
In some cases `TPETRA_VERBOSE=Tpetra::Export` may even help; @tjfulle did some work with that not long ago.  My goal is to have as much of that behavior controlled at run time as we can stand for good performance.  It's 2018; we shouldn't need to recompile for stuff like that ;-) .

**Comment by mhoemmen** [comment] 2018-02-22 00:45
@lucbv Thanks for looking at this btw! :D

**Comment by bartlettroscoe** [comment] 2018-02-22 13:43
> I won't have a chance to look more carefully at this until later today, I have some PRs in progress needed for kokkos integration testing for the next snapshot into Trilinos, so it is probably better to disable the tests until I can help diagnose underlying issues.

@ndellingwood,

I was not able to get to disable this last night. Can you go ahead and disable these tests in all debug builds until this can be fixed?  These tests can be disabled by adding the argument:

```
   EXCLUDE_IF_NOT_TRUE ${PROJECT_NAME}_ENABLE_DEBUG
```

to the [TRIBITS_ADD_TEST()](https://tribits.org/doc/TribitsDevelopersGuide.html#formal-arguments-tribits-add-test) commands that add these tests.  That will print a nice message at configure time that the test is being disabled when debugging is not enabled.

Also, while you are at it, can you please remove the argument:

```
   CATEGORIES NIGHTLY
```

from these tests?  These tests run fast and they should not be relegated to "Nightly" tests.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#test-test-category-nightly

That will better protect these tests going forward.

**Comment by lucbv** [comment] 2018-02-22 16:32
@mhoemmen, @ndellingwood, OK I think that I know what the error is, it stared at me for a while and I finally noticed that at some point an exporter is constructed with the following maps:
```
p=1 | redist_mv.getMap()->getNodeElementList(): {}
p=1 | redist_mv_PIDs: {}
p=1 | redist_mv_LIDs: {}
p=1 | contigMap->getNodeElementList(): {}
p=1 | contigMap_PIDs: {}
p=1 | contigMap_LIDs: {}
p=0 | redist_mv.getMap()->getNodeElementList(): {0, 2, 4, 5, 7, 9}
p=0 | redist_mv_PIDs: {0, 0, 0, 0, 0, 0}
p=0 | redist_mv_LIDs: {0, 1, 2, 3, 4, 5}
p=0 | contigMap->getNodeElementList(): {0, 1, 2, 3, 4, 5}
p=0 | contigMap_PIDs: {0, 0, 0, 0, 0, 0}
p=0 | contigMap_LIDs: {0, 1, 2, 3, 4, 5}
```
My understanding of Tpetra is that it will work only if the two maps have the same GIDs, otherwise I don't know how it will figure out the correspondence between the two maps?
My guess is that instead of doing an export here, a map replacement, from non contiguous to contiguous, is enough?

By the way this all happens in `Amesos2_TpetraMultiVecAdapter_def.hpp` in the method `get1dCopy`.

**Comment by tjfulle** [comment] 2018-02-22 16:51
@mhoemmen said:

> In some cases TPETRA_VERBOSE=Tpetra::Export may even help; @tjfulle did some work with that not long ago.

There is *very limited* coverage of `TPETRA_VERBOSE=<Name>`.  The only places in the code where `TPETRA_VERBOSE` and `TPETRA_DEBUG` are understood by a named variant (as opposed to just `TPETRA_VERBOSE=ON` or `OFF`, ditto for  `TPETRA_DEBUG`) are places where I have needed it - and I don't think `Tpetra::Export` is one of them.  I agree, it would be nice to expand the coverage for the named versions of these variables to allow for easier debugging of select portions of code.

**Comment by mhoemmen** [comment] 2018-02-22 19:05
@tjfulle Some relaxing evening I might try going through Tpetra classes to target `TPETRA_VERBOSE` a bit finer....

**Comment by lucbv** [comment] 2018-02-22 19:55
@mhoemmen, does my explanation above make sense to you?

**Comment by mhoemmen** [comment] 2018-02-22 20:35
@lucbv Sorry, I got distracted a bit.  Export lets some source Map indices not exist in the target Map, and Import lets some target Map indices not exist in the source Map.  See `isLocallyComplete_` documentation in `Tpetra_ImportExportData_decl.hpp`.  This is also true of Epetra as far as I know; it's ancient behavior.

**Comment by mhoemmen** [comment] 2018-02-22 20:35
@lucbv Where is this code that you mentioned?

**Comment by ndellingwood** [comment] 2018-02-22 20:41
@bartlettroscoe I added the check `${PROJECT_NAME}_ENABLE_DEBUG` to the CMakeLists.txt to remove the KLU2, SuperLU and Basker tests that are causing the hang for the time being. I was not able to make it work with `EXCLUDE_IF_NOT_TRUE` but tested locally that the tests are not building when Debug is enabled (and still build when Debugging is not enabled). Will revert when the issue is addressed. 
Removed `CATEGORIES NIGHTLY` arguments from the tests also. 
I will address your other suggestions for cleaning up the `CMakeLists.txt` file in a later commit, thanks for the suggestions.

Testing with checkin script which should push when done. Not enabling forward packages since only Amesos2 unit tests are affected:
`./checkin-test-sems.sh --no-enable-fwd-packages --enable-packages=Amesos2 --do-all --push`

**Comment by lucbv** [comment] 2018-02-22 20:53
@mhoemmen the code is in `Amesos2_TpetraMultiVecAdapter_def.hpp` on line 223 and below. To trigger this you can run the `KLU2_unit_tests` specifically `KLU2_NonContgGID`.

Even though this might be acceptable behavior for Tpetra, I am not sure that it is the intent of the code in `Amesos2`, further more it seems that the new Kokkos refactor in debug mode is not complying with this behavior based on the error message I reported:

```
 p=0: *** Caught standard std::exception of type 'std::runtime_error' :
 
  MultiVector unpack kernel had 2 out-of bounds index/ices.  Here they are: [-1, -1].
 [FAILED]  (0.0358 sec) KLU2_double_int_int_NonContgGID_UnitTest
 Location: /home/lberge/Research/Trilinos_checkin/packages/amesos2/test/solvers/KLU2_UnitTests.cpp:383
```

The message above is somewhat tricky to reproduce I have seen it come and go during my tests. I am not too sure why it would do that?

**Comment by mhoemmen** [comment] 2018-02-22 21:24
Thanks @lucbv !  I'm curious what the KLU2 adapter could be doing that the other adapters aren't doing.  It would be weird to have GIDs in the source Map that aren't in the target Map; wouldn't that mean that KLU2 isn't solving the whole linear system?

**Comment by bartlettroscoe** [comment] 2018-02-22 21:34
> I added the check ${PROJECT_NAME}_ENABLE_DEBUG to the CMakeLists.txt to remove the KLU2, SuperLU and Basker tests that are causing the hang for the time being.

@ndellingwood, thanks for doing that.  Did you put this GitHub Issue ID like `#2270` in the commit message by any chance?  If you do that, it will show up in this GitHub Issue and it makes it easy to trace commits to GitHub issues and visa versa.

**Comment by lucbv** [comment] 2018-02-22 21:37
@mhoemmen I think that this not the intent of the unit-test, it is the result of a bad understanding of what the maps are doing. Also both map are actually on the root rank when this export happens so it technically does not send any data anywhere... I could be just luck that things worked as expected.
Would you recommend to simply replace the maps in the RHS and operator instead of trying to do an export?

**Comment by bartlettroscoe** [comment] 2018-02-22 21:56
> I'm curious if this is related to the "check-in tests != PR testing" issue.

@mhoemmen, as described [above](https://github.com/trilinos/Trilinos/issues/2270#issuecomment-367160249), these tests only fail when `-DTrilinos_ENABLE_DEBUG=ON` and `-DTrilinos_TEST_CATEGORY=NIGHTLY`.  The issue is that the CI build that I set up sets `-DTrilinos_ENABLE_DEBUG=ON` but sets `-DTrilinos_TEST_CATEGORY=BASIC`.  And the Trilinos "Clean" builds shown yesterday at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-02-21&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Clean

all seem to be `-DTrilinos_ENABLE_DEBUG=OFF` builds.

**Comment by mhoemmen** [comment] 2018-02-22 22:06
@lucbv wrote:
> Would you recommend to simply replace the maps in the RHS and operator instead of trying to do an export?

I need to look more closely at the test, but the intent of the Amesos2 interface should be redistribution between the user's distribution, and the distribution required by the particular sparse direct solver.  KLU2 is not a distributed solver, so the adapter _should_ compute the "gather Map" and use that for the solver.  My guess is that Amesos2 isn't doing the right thing there.

**Comment by ndellingwood** [comment] 2018-02-22 23:47
@bartlettroscoe 

> Did you put this GitHub Issue ID like #2270 in the commit message by any chance?

Yes, a message with the merge into Trilinos popped up in this issue after the checkin script finished as well.

**Comment by srajama1** [comment] 2018-04-20 15:16
@ndellingwood : We need to get to the bottom of this next week or so ..

**Comment by bartlettroscoe** [comment] 2018-04-27 12:48
We have not seen these tests timing out in a long time.  What this issue fixed?

**Comment by bartlettroscoe** [comment] 2018-04-27 12:56
Okay, [above](https://github.com/trilinos/Trilinos/issues/2270#issuecomment-367815146), I see that the tests got disabled for debug builds. 

As per the documented process [Triaging and addressing ATDM Trilinos Failures](https://snl-wiki.sandia.gov/display/CoodinatedDevOpsATDM/Triaging+and+addressing+ATDM+Trilinos+Failures),  I have added the "Disabled Tests" and "Stalled" labels and added a "## Next Action Status" field to properly mange this issue.

**Comment by bartlettroscoe** [comment] 2018-04-27 13:06
FYI: For some reason, this Issue is not properly showing up in the query:

* https://github.com/trilinos/Trilinos/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22Disabled+Tests%22+label%3AATDM

But if I remove the "label:ATDM" argument, it shows up in the query:

* https://github.com/trilinos/Trilinos/labels/Disabled%20Tests

This must be some type of GitHub query defect.  Hopefully we don't see this problem with other issues.

**Comment by bartlettroscoe** [comment] 2018-04-27 13:40
> I tried both of your queries and both showed the the same 6 issues including this issue (#2270). Strange, is it possible your result is cached?

@allevin, I had hit "Ctrl+R" several times and it did not work with Chrome on Windows 7. But I just tried again just now and it works on the same browser.   Strange.  Don't know what that means but hopefully this is not a GitHub issue.

**Comment by ndellingwood** [comment] 2018-08-17 15:49
This should be fixed by #3300, will wait to close until a couple successful passes of the atdm tests.

**Comment by ndellingwood** [comment] 2018-08-20 16:37
Since no new issues from #3300 have been reported from the ATDM builds after re-enabling these tests with debug enabled I'll close the issue. Thanks all involved during the triaging.

**Comment by bartlettroscoe** [comment] 2018-08-20 16:48
Looking at [this query for Amesos2_KLU2_UnitTests_MPI_2](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&date=2018-08-19&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-sems-gcc-7-2-0&field2=testname&compare2=61&value2=Amesos2_KLU2_UnitTests_MPI_2&field3=buildstarttime&compare3=83&value3=2018-08-15) we can see this test is now running now passing again in this `Trilinos-atdm-sems-gcc-7-2-0` build starting 8/18/2018.

However, looking at [this query for Amesos2_Superlu_UnitTests_MPI_2](https://testing-vm.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=and&date=2018-08-19&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-sems-gcc-7-2-0&field2=testname&compare2=61&value2=Amesos2_Superlu_UnitTests_MPI_2&field3=buildstarttime&compare3=83&value3=2018-08-15), we don't see this test running againt.

@ndellingwood, should the test `Amesos2_Superlu_UnitTests_MPI_2` be running and passing in the `rilinos-atdm-sems-gcc-7-2-0` build?

Re-opening the issue until we resolve the status of `Amesos2_Superlu_UnitTests_MPI_2` for this build.

**Comment by srajama1** [comment] 2019-01-24 23:43
@tjfulle : Did this issue get resolved, just checking. Thanks !

**Closed** 2021-07-07 12:24 UTC
Labels: ATDM Sev: Nonblocker, CLOSED_DUE_TO_INACTIVITY, Disabled Tests, MARKED_FOR_CLOSURE, PA: Linear Solvers, Stalled, client: ATDM, pkg: Amesos2, type: bug
