### ISSUE TITLE
Specifying relative path to install location on configure results in unexpected behavior

### ISSUE THREAD

**Issue by krcb** [trilinos/Trilinos#7431] opened 2020-05-26 20:15 UTC
## Bug Report
@trilinos/\<PackageName\>

### Description

Configuring using a relative install prefix `-DCMAKE_INSTALL_PREFIX` results in `Trilinos_INSTALL_DIR` written in TrilinosConfig.cmake (installed in `lib/cmake/Trilinos`) being specified with a relative path (rather than an absolute path). If `Trilinos_INSTALL_DIR` is used in a downstream application, where the relative path from the build space no longer points to the install location, then this can have unexpected and difficult to diagnose consequences.

@bartlettroscoe 

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by bartlettroscoe** [comment] 2020-05-26 21:46
@krcb, how is the `CMAKE_INSTALL_PREFIX` cache var being passed in?  Is it given a type or is it just passed in as:

```
-DCMAKE_INSTALL_PREFIX=lib/cmake/Trilinos
```

?

**Comment by bartlettroscoe** [comment] 2020-05-26 21:57
@krcb, 

Note:

* https://gitlab.kitware.com/cmake/cmake/issues/16445

The problem is that if no type is provided for `CMAKE_INSTALL_PREFIX`, then how do you expect the relative paths to be interpreted?  Is this relative to the current working directory (which would be the base build directory)? I guess that would be the safe assumption in this case.

We could update TriBITS to guarantee the user that a relative path in `CMAKE_INSTALL_PREFIX` will be interpreted w.r.t. to the current working directory (which should always be the base project build dir).

But note that in some contexts that if you provide a relative path, then it is actually interpreted in terms of the source directory base, not the build directory.  For example, if CMake code does:

```
include(<relative-path>)
```

it assumed to be relative the the `${CMAKE_CURRENT_SOURCE_DIR}` (but that is not documented in https://cmake.org/cmake/help/v3.17/command/include_directories.html).

Let me know.

**Comment by krcb** [comment] 2020-05-26 22:29
@bartlettroscoe In this specific case, I had configured (run cmake from the command line) with `-DCMAKE_INSTALL_PREFIX:PATH="../../install/trilinos"`. Prior to `Trilinos_INSTALL_DIR` being added to `TrilinosConfig.cmake`, `Trilinos_INSTALL_DIR` was being set (likely by the downstream application) to be an absolute path. My sense is that `CMAKE_INSTALL_PREFIX` should be converted to an absolute path to avoid these kind of inconsistencies (there might be some problems related to `RPATH` though).

**Comment by bartlettroscoe** [comment] 2020-05-26 23:07
@krcb,

>  In this specific case, I had configured (run cmake from the command line) with `-DCMAKE_INSTALL_PREFIX:PATH="../../install/trilinos"`.

According to the the documentation at:

*  In this specific case, I had configured (run cmake from the command line) with -DCMAKE_INSTALL_PREFIX:PATH="../../install/trilinos"

> Furthermore, if the `<type>` is `PATH` or `FILEPATH` and the `<value>` provided on the command line is a relative path, then the set command will treat the path as relative to the current working directory and convert it to an absolute path.

That suggests that CMake would be converting `../../install/trilinos` to an absolute path before any CMakeLists.txt code would ever see it.

What version of CMake are you seeing that `-DCMAKE_INSTALL_PREFIX:PATH="../../install/trilinos"` is not resulting in an absolute path automatically by CMake?

> My sense is that `CMAKE_INSTALL_PREFIX` should be converted to an absolute path to avoid these kind of inconsistencies (there might be some problems related to `RPATH` though).

@krcb, I agree.  But we need to define what that path will be relative to when the user provides `--DCMAKE_INSTALL_PREFIX=<rel-path>` with no type provided.  Should we say this will be interpreted w.r.t. the current working directory (`${CMAKE_CURRENT_BINARY_DIR}`)?

**Comment by krcb** [comment] 2020-05-27 13:23
> What version of CMake are you seeing that -DCMAKE_INSTALL_PREFIX:PATH="../../install/trilinos" is not resulting in an absolute path automatically by CMake?

@bartlettroscoe This is with cmake-3.14.5 on OSX. Note that the documentation for this version of cmake doesn't mention that this variable is converted to an absolute, just that this path is prepended to install locations, see:

https://cmake.org/cmake/help/v3.14/variable/CMAKE_INSTALL_PREFIX.html?highlight=cmake_install#variable:CMAKE_INSTALL_PREFIX

> Should we say this will be interpreted w.r.t. the current working directory (${CMAKE_CURRENT_BINARY_DIR})

Yes, I think this is the right approach, as this matches the expected behavior that you quoted above:

> ... if the <type> is PATH or FILEPATH and the <value> provided on the command line is a relative path, then the set command will treat the path as relative to the current working directory and convert it to an absolute path.

**Closed** 2022-02-16 12:24 UTC
Labels: type: bug, client: ATDM, ATDM Config, ATDM DevOps, MARKED_FOR_CLOSURE, CLOSED_DUE_TO_INACTIVITY
