### ISSUE TITLE
ROL build failure in updated CI build

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#993] opened 2017-01-10 17:11 UTC
@trilinos/rol 

A build is failing (internal compiler error...) after updating the Trilinos CI build on sadl30906.

[link to failure](http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2694326)

There are 3 general possible causes for this failure:

1) ROL was changed and this caused the new failure.

2) The changes to the CI build parameters since the last one uncovered the failure, and the failure is valid.

3) The changes to the CI build parameters were made somehow in an invalid way and the parameters need to be updated. The failure is invalid, but rather a misconfiguration issue.

**Comment by dridzal** [comment] 2017-01-10 19:36
This is due to the internal compiler error caused by MueLu code, see #992 .  ROL uses MueLu for several examples.  My best guess is that on sadl30906.srn.sandia.gov the compiler occasionally runs out of memory, or that there is a related memory corruption.  I've noticed that most ROL tests that use MueLu take a very long time to compile.  Also, the compiler memory use is very high for these tests (many GB).  Anyway, can we attribute this failure to insufficient or faulty hardware, and close the issue?  @jwillenbring ?

**Comment by mhoemmen** [comment] 2017-01-10 21:08
Is ETI OFF for this build?  ETI OFF builds tend to be more expensive, so it could help to reduce the N in `make -j N`.

**Comment by dridzal** [comment] 2017-01-10 21:24
I don't know where to look for that build script.

**Comment by dridzal** [comment] 2017-01-11 21:11
@jwillenbring , could you please check if ETI is on or off for this build?

**Comment by jwillenbring** [comment] 2017-01-11 21:30
ETI is on. One change I made when this started failing was to switch

-DTrilinos_ENABLE_DEBUG_SYMBOLS=ON

**Comment by dridzal** [comment] 2017-01-11 21:47
I think it would be useful to disable the debug symbols temporarily, just to see if that pushed the memory use over the edge.

**Comment by jwillenbring** [comment] 2017-01-13 15:10
Disabling dub symbols eliminated the errors in bot the initial build, and a rebuild yesterday.

@bartlettroscoe is it important to have -DTrilinos_ENABLE_DEBUG_SYMBOLS=ON for the CI build? Using this option for the "old" CI build results in internal compiler errors.

**Comment by bartlettroscoe** [comment] 2017-01-13 16:04
> @bartlettroscoe is it important to have -DTrilinos_ENABLE_DEBUG_SYMBOLS=ON for the CI build? Using this option for the "old" CI build results in internal compiler errors.

We want the standard CI build to do as much checking as possible without the cost going up too much.  If `-DTrilinos_ENABLE_DEBUG_SYMBOLS=ON` is catching more defects, then we should turn it on.  In fact, once this is fixed, I will enable that for the standard CI build.

Note that the CI build should also be turning on debug-mode runtime checking (i.e `-DTrilinos_ENABLE_DEBUG=ON`).  But we otherwise want to use optimized compiler flags because we want the tests to run as fast as they can (especially important with more expensive debug-mode runtime checks turned on).

**Comment by dridzal** [comment] 2017-01-13 17:17
@bartlettroscoe -- just to clarify:  Enabling debug symbols isn't catching more defects.  The compiler crashes (internal error), because, we suspect, it runs out of memory with symbols enabled (only on this particular machine).  I observe this all the time on low-powered laptops.
@jwillenbring -- can we add RAM to this machine?  Alternatively, can we reduce the N in make -jN?

**Comment by jwillenbring** [comment] 2017-01-13 18:10
@dridzal we can reduce -jN. It is currently set to 10. Before doing that's I wanted confirmation from Ross that this option is needed. I am also not sure what to try for a reduced value. The build is already too slow. That said, the parallel speed up isn't great anyway. In the medium term we should get this build off of this machine. Maybe I should up the priority of moving the build. We want the CI build to be very fast.

**Comment by bartlettroscoe** [comment] 2017-01-13 18:34
If configuring with `-DTrilinos_ENABLE_DEBUG_SYMBOLS=ON` (which just add `-g` in a portable way) does not help catch any errors, just consumes more memory, then I would say that you can leave it off for now.  But I think that having it on helps to catch problems with C++ code consuming too much memory.  If it kills the CI machine, it will also kill many users systems as well.  We need an effort to reduce build times and compiler memory usage in general in Trilinos (which have gotten a bit out of control).  Stories like outlined in [this epic](https://github.com/trilinos/Trilinos/milestone/22) will hep with that a good bit.

**Comment by dridzal** [comment] 2017-01-13 18:48
We have completely lost track of ... let's call it small computing.  Since we put in some power examples in ROL that utilize the entire new solver stack, we have been getting complaints from university collaborators that they can't compile the examples due to out-of-memory errors and other types of internal compiler errors.  They tend to use lower-end laptops with 4GB to 8GB of memory.  I tell them to compile with -j1, enable ETI, and kill all unnecessary processes, but that's often not enough.  It would be interesting to track down which packages, or which combinations of packages, are the biggest memory consumers when it comes to compiling.

**Closed** 2017-01-16 20:22 UTC
Labels: ROL

**Comment by dridzal** [comment] 2017-01-16 20:26
I think it's safe to close this issue.  We can view it as a hardware limitation of sadl30906, or a general issue with the templated solver stack -- compilation simply requires significant resources, specifically memory.
