### ISSUE TITLE
MueLu:  ETI Build Error in Sierra coming from new MueLu object

### ISSUE THREAD

**Issue by nate945** [trilinos/Trilinos#11078] opened 2022-09-29 15:10 UTC
## Bug Report
@trilinos/\<MueLu\>

### Description
Working on new Trilinos master integration to Sierra. Last integration was about 3 weeks ago. The build is failing in Trilinos prior to getting to any of the Sierra part. One of the relevant failures below.

As best as I can tell there recently added object (MueLu_MatrixFreeTentativeP) which is being build via explicit template instantiation, but does not build with our Sierra configuration for Trilinos. It seems to be trying to call an atomic_add of mixed float/double precision, which at first glance seems like a function that cannot exist. Here is the error:

2925 /scratch/CODE2/objs/tpls/spack/spack/.spack/stage/nkcrane/spack-st
age-trilinos-2022.09.28-majjzefbcz2qw7jwjeucicoanmt7t4r4/spack-src
/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:42:3: required from
here
>> 2926 /scratch/CODE2/objs/tpls/spack/spack/.spack/stage/nkcrane/spack-st
age-trilinos-2022.09.28-majjzefbcz2qw7jwjeucicoanmt7t4r4/spack-src
/packages/muelu/src/Transfers/Matrix-Free/MueLu_MatrixFreeTentativ
eP_kokkos_def.hpp:96:31: error: no matching function for call to '
atomic_add(Kokkos::complex<float>*, Kokkos::complex<double>)'

The potentially relevant parts of our Trilinos configuration options are:
'HAVE_GCC_ABI_DEMANGLE:BOOL=ON',
'HAVE_TEUCHOS_BLASFLOAT:BOOL=ON',
'HAVE_TEUCHOS_BLASFLOAT_DOUBLE_RETURN:BOOL=OFF',

'Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF',
'Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF',
'Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF',
'Trilinos_ENABLE_COMPLEX:BOOL=ON',
'Trilinos_ENABLE_DEBUG:BOOL={}'.format('ON' if '+debug' in self.spec else 'OFF'),
'Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON',
'Trilinos_ENABLE_FLOAT:BOOL=ON',
'Trilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION:BOOL=ON',
'Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL={}'.format(
"ON" if '+deprecated_warnings' in self.spec else "OFF"),
'Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=%s' % ""

Of course there is also piles of other complexity in the Sierra build system that might play in here somewhere too.
I'd like to first see if there is a way to fix or workaround this to get the Sierra-Trilinos integration through. Also if there is something in our configuration that doesn't match what Trilinos tests for builds I'd like to try to identify and remedy that. 

Thanks!

### Steps to Reproduce
This is the SHA we are trying to integrate
1. SHA1:  f2c5e6655cbd1d18c5b777d4ffda603bf1a72f9f 

Also have tons other full log files, configure scripts, etc. I'd be happy to share with someone on the Sandia side and/or pair/walkthrough the issue.

1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by nate945** [comment] 2022-09-29 15:12
This is a duplicate of internal ticket: tagging additional participants from there
@vbrunini @srajama1 @ndellingwood @crtrott

**Comment by tasmith4** [comment] 2022-09-29 15:17
@jhux2 @cgcgcg @csiefer2

**Comment by crtrott** [comment] 2022-09-29 15:22
Hey Nate, tried to call you on teams and phone. We need the full configuration. Also is it possible you are explicitly turning off desul atomics? Because this works with desul atomics on. Note the option to turn of desul atomics is Kokkos_ENABLE_IMPL_DESUL_ATOMICS. That "Impl" means its not really a supported user option. 

Anyway with desul atomics off, you can't mix the value and pointer type that way. In the desul atomics we worked harder to make this possible by playing some tricks with how template argument deduction works. We only test with desul atomics on in Trilinos, turning them off is not generally supported, and is only there to debug potential performance issues. Feel free to give me a call.

**Comment by crtrott** [comment] 2022-09-29 15:24
Just to make that clear: what I am saying here is that if this is because Kokkos_ENABLE_IMPL_DESUL_ATOMICS was set by Sierra, then this is a user error enabling an unsupported option and not per se a bug in Trilinos. This particular atomic would never have worked with desul atomics off, Trilinos just doesn't test that way since its an unsupported option from Kokkos. If you really want to fix that in the code place, cast the alpha to the value_type of the views in that line in Muelu, so it doesn't get upcast to complex<double>. But per-se this is NOT a bug in Trilinos.

**Comment by crtrott** [comment] 2022-09-29 15:26
Removed the bug label, until I get proof that I am wrong with what is going on :-)

**Comment by nate945** [comment] 2022-09-29 15:29
@crtrott Thanks! that is super helpful.  Yes we do appear to have the DESUL atomics turned off.  I'm not sure of the history of that.  I'll try turning those back on and see if that resolves this.  Then can go from there to understand if there is a compelling reason that option was turned on previously and figure out the path forward there.  Ideally if we can remove that option to get a more consistent configuration.

**Comment by vbrunini** [comment] 2022-09-29 15:31
We disabled them because of this Kokkos issue: https://github.com/kokkos/kokkos/issues/4611 . Looks like it was fixed in Kokkos 3.6 so we should be able to re-enable them.

**Comment by crtrott** [comment] 2022-09-29 15:33
Ah yeah there it is. I mean if you have other regressions let us know. Atomics are unfortunately a very complicated VAST area. Desul supports something like 6000 distinct atomic operations hitting different code paths. I definitely know of a lot of combination where desul atomics perform better than the classic atomics, because we hit the right path now and didn't before.

**Comment by nate945** [comment] 2022-09-29 15:39
OK, thanks!  I think our best path forward if it works is definitely to try and get rid of the DESUL disable option, reevaluate performance, and hopefully all will be well and we'll have a somewhat less one-off Sierra configuration which will streamline these integrations going forward.  Will take a couple days to get that data and will report back.

**Comment by GrahamBenHarper** [comment] 2022-09-29 18:51
> That will likely not help: because the issue is that Multivector is float, while Scalar is double the way that function gets instantiated in the failing thing.

I introduced this error, but I'm away at a conference at the moment. I will do my best to take a look at things when there is time. I believe I understand what is happening, but it also confuses me since it slipped past the complex build on the AT somehow.

**Comment by crtrott** [comment] 2022-09-29 20:08
It is not confusing that it slipped past the AT build in Trilinos: Trilinos does not test with DESUL disabled, because it is not considered a proper public option.

**Comment by crtrott** [comment] 2022-09-29 20:10
Also I looked with Christian at this: the issue is the sqrt in there, which takes an integer argument and will return a double because of that, thus upcasting all the other arguments. Desul atomics can deal with mixed argument types where appropriate, the old atomic interface can not.

**Closed** 2022-10-13 14:23 UTC
Labels: pkg: MueLu, client: Sierra
