### ISSUE TITLE
MueLu: undefined references

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#1301] opened 2017-05-08 23:37 UTC
When compiling Albany I get the errors:

/home/amota/LCM/trilinos-install-serial-gcc-release/lib/libmuelu-adapters.so.12.11: undefined reference to `MueLu::HierarchyManager<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::exportCount_'
/home/amota/LCM/trilinos-install-serial-gcc-release/lib/libmuelu-adapters.so.12.11: undefined reference to `MueLu::HierarchyManager<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::ctorCount_'

**Comment by jhux2** [comment] 2017-05-09 00:01
@lxmota @trilinos/muelu Could you please post your configure script, or send it to me directly via email.

**Comment by jhux2** [comment] 2017-05-09 00:03
Btw, I'm not sure why, but github seems to think that it's May 9.  It's still May 8. :)

**Comment by lxmota** [comment] 2017-05-09 00:05
@jhux2 Here is my Trilinos configuration script:

#!/bin/bash

# WARNING: This file is generated automatically. Any changes made here
# will be lost when the package is configured again.  Any permament
# changes should go into the corresponding template at the top level
# LCM directory.

if [ -f ./CMakeCache.txt ]; then
    rm ./CMakeCache.txt
fi

if [ -d ./CMakeFiles ]; then
    rm ./CMakeFiles -rf
fi

export OMPI_CC=/usr/bin/gcc
export OMPI_CXX=/usr/bin/g++
export OMPI_FC=/usr/bin/gfortran

#
# The CMake command.
#
cmake \
 -D BUILD_SHARED_LIBS:BOOL=ON \
 -D CMAKE_BUILD_TYPE:STRING="RELEASE" \
 -D CMAKE_CXX_COMPILER:FILEPATH="$MPI_BIN/mpicxx" \
 -D CMAKE_C_COMPILER:FILEPATH="$MPI_BIN/mpicc" \
 -D CMAKE_Fortran_COMPILER:FILEPATH="$MPI_BIN/mpif90" \
 -D CMAKE_INSTALL_PREFIX:PATH=/home/amota/LCM/trilinos-install-serial-gcc-release \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
\
 -D TPL_ENABLE_MPI:BOOL=ON \
 -D TPL_ENABLE_BinUtils:BOOL=OFF \
 -D TPL_MPI_INCLUDE_DIRS:STRING="$MPI_INC" \
 -D TPL_MPI_LIBRARY_DIRS:STRING="$MPI_LIB" \
 -D MPI_BIN_DIR:PATH="$MPI_BIN" \
\
 -D TPL_ENABLE_Boost:BOOL=ON \
 -D TPL_ENABLE_BoostLib:BOOL=ON \
 -D Boost_INCLUDE_DIRS:STRING="$BOOST_INC" \
 -D Boost_LIBRARY_DIRS:STRING="$BOOST_LIB" \
 -D BoostLib_INCLUDE_DIRS:STRING="$BOOSTLIB_INC" \
 -D BoostLib_LIBRARY_DIRS:STRING="$BOOSTLIB_LIB" \
\
 -D TPL_ENABLE_yaml-cpp:BOOL=ON \
 -D yaml-cpp_INCLUDE_DIRS:STRING="$YAML_CPP_INC" \
 -D yaml-cpp_LIBRARY_DIRS:STRING="$YAML_CPP_LIB" \
\
 -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
 -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
 -D Trilinos_ENABLE_CXX11:BOOL=ON \
 -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
 -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF \
 -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
 -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
 \
 -D Teuchos_ENABLE_STACKTRACE:BOOL=OFF \
 -D Teuchos_ENABLE_DEFAULT_STACKTRACE:BOOL=OFF \
 -D Kokkos_ENABLE_CXX11:BOOL=ON \
 -D Kokkos_ENABLE_Cuda_UVM:BOOL=OFF \
 -D Kokkos_ENABLE_EXAMPLES:BOOL=OFF \
 -D Kokkos_ENABLE_OpenMP:BOOL=OFF \
 -D Kokkos_ENABLE_Pthread:BOOL=OFF \
 -D Kokkos_ENABLE_Serial:BOOL=ON \
 -D Kokkos_ENABLE_TESTS:BOOL=OFF \
 -D TPL_ENABLE_CUDA:STRING=OFF \
 -D TPL_ENABLE_CUSPARSE:BOOL=OFF \
\
 -D Amesos2_ENABLE_KLU2:BOOL=ON \
 -D EpetraExt_USING_HDF5:BOOL=OFF \
 -D Intrepid2_ENABLE_KokkosDynRankView:BOOL=ON \
 -D MiniTensor_ENABLE_TESTS:BOOL=ON \
 -D ROL_ENABLE_TESTS:BOOL=OFF \
 -D Phalanx_INDEX_SIZE_TYPE:STRING="INT" \
 -D Phalanx_KOKKOS_DEVICE_TYPE:STRING="SERIAL" \
 -D Phalanx_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
 -D Tpetra_ENABLE_Kokkos_Refactor:BOOL=ON \
 -D Tpetra_INST_PTHREAD:BOOL=OFF \
\
 -D TPL_ENABLE_HDF5:BOOL=OFF \
 -D TPL_ENABLE_HWLOC:STRING=OFF \
 -D TPL_ENABLE_Matio:BOOL=OFF \
 -D TPL_ENABLE_Netcdf:BOOL=ON \
 -D TPL_ENABLE_X11:BOOL=OFF \
 -D TPL_Netcdf_INCLUDE_DIRS:STRING="/usr/local/netcdf/include" \
 -D TPL_Netcdf_LIBRARY_DIRS:STRING="/usr/local/netcdf/lib" \
 -D TPL_Netcdf_LIBRARIES:STRING="/usr/local/netcdf/lib/libnetcdf.so" \
 -D TPL_Netcdf_PARALLEL:BOOL=ON \
\
 -D Trilinos_ENABLE_Amesos2:BOOL=ON \
 -D Trilinos_ENABLE_Amesos:BOOL=ON \
 -D Trilinos_ENABLE_Anasazi:BOOL=ON \
 -D Trilinos_ENABLE_AztecOO:BOOL=ON \
 -D Trilinos_ENABLE_Belos:BOOL=ON \
 -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
 -D Trilinos_ENABLE_Epetra:BOOL=ON \
 -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
 -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
 -D Trilinos_ENABLE_Ifpack:BOOL=ON \
 -D Trilinos_ENABLE_Intrepid2:BOOL=ON \
 -D Trilinos_ENABLE_Kokkos:BOOL=ON \
 -D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
 -D Trilinos_ENABLE_KokkosContainers:BOOL=ON \
 -D Trilinos_ENABLE_KokkosCore:BOOL=ON \
 -D Trilinos_ENABLE_KokkosExample:BOOL=OFF \
 -D Trilinos_ENABLE_MiniTensor:BOOL=ON \
 -D Trilinos_ENABLE_ML:BOOL=ON \
 -D Trilinos_ENABLE_MueLu:BOOL=ON \
 -D Trilinos_ENABLE_NOX:BOOL=ON \
 -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
 -D Trilinos_ENABLE_Pamgen:BOOL=ON \
 -D Trilinos_ENABLE_Phalanx:BOOL=ON \
 -D Trilinos_ENABLE_Piro:BOOL=ON \
 -D Trilinos_ENABLE_ROL:BOOL=ON \
 -D Trilinos_ENABLE_Rythmos:BOOL=ON \
 -D Trilinos_ENABLE_SEACAS:BOOL=ON \
 -D Trilinos_ENABLE_STKClassic:BOOL=OFF \
 -D Trilinos_ENABLE_STKIO:BOOL=ON \
 -D Trilinos_ENABLE_STKMesh:BOOL=ON \
 -D Trilinos_ENABLE_Sacado:BOOL=ON \
 -D Trilinos_ENABLE_Shards:BOOL=ON \
 -D Trilinos_ENABLE_Stokhos:BOOL=ON \
 -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
 -D Trilinos_ENABLE_TESTS:BOOL=OFF \
 -D Trilinos_ENABLE_Teko:BOOL=ON \
 -D Trilinos_ENABLE_Tempus:BOOL=ON \
 -D Trilinos_ENABLE_Teuchos:BOOL=ON \
 -D Trilinos_ENABLE_ThreadPool:BOOL=ON \
 -D Trilinos_ENABLE_Thyra:BOOL=ON \
 -D Trilinos_ENABLE_Tpetra:BOOL=ON \
 -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
 -D Trilinos_ENABLE_Zoltan:BOOL=ON \
\
 -D Trilinos_EXTRA_REPOSITORIES:STRING="DataTransferKit" \
\
 -D Trilinos_ENABLE_DataTransferKit:BOOL=ON \
 -D DataTransferKit_ENABLE_DBC:BOOL=ON \
 -D DataTransferKit_ENABLE_TESTS:BOOL=OFF \
 -D DataTransferKit_ENABLE_EXAMPLES:BOOL=OFF \
 -D TPL_ENABLE_MOAB:BOOL=OFF \
 -D TPL_ENABLE_Libmesh:BOOL=OFF \
/home/amota/LCM/Trilinos

**Comment by jhux2** [comment] 2017-05-09 00:17
@lxmota. Thanks, I'll have a look.

**Comment by bartlettroscoe** [comment] 2017-05-09 14:16
The standard post-push CI build also shows many build failures due to this:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2883655&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

This shows a lot of these link failures for Stokhos ( @trilinos/stokhos ) , Piro, Panzer ( @trilinos/panzer ), and TrilinosCouplings.   We are also seeing, for example, these link failures show up for Stokhos as well today for all of the automated builds:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=Stokhos&date=2017-05-09

Therefore, it is not just the CI build that is showing these build failures.

However, the checkin-test.py script seems to have been used to push these commits as shown by the top commit:

```
commit 778a1ff97c1c092ea055a890a427739cfa781ee5
Author: Jonathan Hu <jhu@sandia.gov>
Date:   Mon May 8 12:07:19 2017 -0700

    EpetraExt: fix matrix reader bug
    
    This commit fixes a race condition in MatrixMarketFileToCrsMatrixHandle.
    Previously, if process 0 failed to read the specified matrix data file, it
    returned immediately, but all other processes continued on to an MPI
    broadcast.
    
    In the case of an error condition, process zero will now broadcast the
    error code to all processes in the communicator, and they will all
    return.
    
    Build/Test Cases Summary
    Enabled Packages: EpetraExt, MueLu
    Disabled Packages: Stokhos,TrilinosCouplings,Intrepid2
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=760,notpassed=0 (70.29 min)
    Other local commits for this build/test group: 10e8fcc, 7f336e9, 384aab8, fb0ede8
```

@jhux2, did you use the checkin-test-sems.sh script with the SEMS env to test and push or your own custom local env?  Not sure why that would matter but thought I would ask.

It would be good to get the to bottom of how the checkin-test.py script was able to allow these commits to be pushed.  I will checkout this version of Trilinos locally and then run the checkin-test-sems.sh script to see what happens and report back here.

**Comment by bartlettroscoe** [comment] 2017-05-09 15:29
When I checked out the commit 778a1ff97c1c092ea055a890a427739cfa781ee5, the checkin-test-sems.sh script was able to reproduce the build failures.  They were all Stokhos link failures (see details below).

Now that I look at the commit log showing what was tested more closely which was:

```
    Build/Test Cases Summary
    Enabled Packages: EpetraExt, MueLu
    Disabled Packages: Stokhos,TrilinosCouplings,Intrepid2
    Enabled all Forward Packages
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=760,notpassed=0 (70.29 min)
    Other local commits for this build/test group: 10e8fcc, 7f336e9, 384aab8, fb0ede8
```

this shows that Stokhos was disabled and not tested.  Therefore, the build that @jhux2 did would not have shown these build failures.

@jhux2, why did you disable Stokhos, TrilihnosCouplings, and Intrepid2?  Those are all important Primary Tested packages and need to be tested pre-push.

What this shows is that if a simple `checkin-test-sems.sh --do-all --push` would have been used to test and push the changes, then these failures would have not gotten into the 'develop' branch.

----

**DETAILED NOTES:**

I checked out this commit locally using:

```
$ cd Trilinos/

$ git checkout 778a1ff97c1c092ea055a890a427739cfa781ee5
Note: checking out '778a1ff97c1c092ea055a890a427739cfa781ee5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 778a1ff... EpetraExt: fix matrix reader bug
```

I then ran a rebuild (not build from scratch) to duplicate the enables shown in commit ??? with:

```
$  ./checkin-test-sems.sh --enable-all-packages=off --enable-packages=EpetraExt,MueLu --local-do-all
```

which showed in the configure output:

```
Trilinos repos versions:
--------------------------------------------------------------------------------
*** Base Git Repo: Trilinos
778a1ff [Mon May 8 12:07:19 2017 -0700] <jhu@sandia.gov>
EpetraExt: fix matrix reader bug
 --------------------------------------------------------------------------------
```

The returned with build failures:

```
FAILED CONFIGURE/BUILD/TEST: Trilinos: crf450.srn.sandia.gov

Tue May  9 09:15:02 MDT 2017

Enabled Packages: EpetraExt, MueLu
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Forward Packages

Build test results:
-------------------
0) MPI_RELEASE_DEBUG_SHARED_PT => FAILED: build failed => Not ready to push! (57.60 min)
```

The build failures where:

```
$ grep "Error " MPI_RELEASE_DEBUG_SHARED_PT/make.out 
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_SacadoTraitsUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SacadoTraitsUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_NormalizedHermiteBasisUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_NormalizedHermiteBasisUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorSerializationTests.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SacadoMPVectorSerializationTests.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TensorProductBasisUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TensorProductBasisUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_MatrixFreeOperatorUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_MatrixFreeOperatorUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_SacadoUQPCESerializationTests.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SacadoUQPCESerializationTests.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_ExponentialRandomFieldUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_ExponentialRandomFieldUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_SparseGridQuadratureUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SparseGridQuadratureUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_KokkosViewUQPCEUnitTest_Serial.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_KokkosViewUQPCEUnitTest_Serial.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixUQPCEUnitTest_Serial.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_KokkosCrsMatrixUQPCEUnitTest_Serial.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_DivisionOperatorUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_DivisionOperatorUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_StieltjesUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_StieltjesUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_AlgebraicExpansionUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_AlgebraicExpansionUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_QuadExpansionUnitTest.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_QuadExpansionUnitTest.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_SacadoPCECommTests.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_SacadoPCECommTests.dir/all] Error 2
make[2]: *** [packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.exe] Error 1
make[1]: *** [packages/stokhos/test/UnitTest/CMakeFiles/Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial.dir/all] Error 2
make: *** [all] Error 2
```

Therefore, the checkin-test-sems.sh script reproduced the failures.

**Comment by etphipp** [comment] 2017-05-09 15:30
I'm getting many nightly build failures in Stokhos as well, with the same error.  See, e.g., here:

http://testing.sandia.gov/cdash/buildSummary.php?buildid=2885597

**Comment by jhux2** [comment] 2017-05-09 18:39
@lxmota @bartlettroscoe @etphipp I've reverted these commits.  During checkin I saw that all the Stokhos tests pass.  I'll be sure to enable Stokhos next time prior to pushing.

**Comment by etphipp** [comment] 2017-05-09 19:03
I have a commit ready that fixes the Stokhos linker errors.  ETI files for the new HierarchyManager just needed to be created.  And these needed to be written by hand since the pattern is different from the other classes.  Were there other linker errors than those arising from Stokhos?  If not, you can revert your revert and I can push these changes.

One thing that might have caused the error Alejandro reported was a new cpp file was added without a change to a CMakeLists.txt file.  And I believe the ETI files are brought in by a glob, so cmake may not have been rerun to pick up the new file.  When adding files pulled in by a glob, it is nice to make a trivial CMakeLists.txt change so cmake is automatically rerun.

**Comment by jhux2** [comment] 2017-05-09 20:16
@etphipp I hadn't considered that it might be due to globbing.  I'll do a local configure/build that mimics one of the MueLu dashboard failures to see if globbing is the root cause.  If that works, then I'll unrevert.

**Comment by bartlettroscoe** [comment] 2017-05-09 21:13
> One thing that might have caused the error Alejandro reported was a new cpp file was added without a change to a CMakeLists.txt file. And I believe the ETI files are brought in by a glob, so cmake may not have been rerun to pick up the new file. When adding files pulled in by a glob, it is nice to make a trivial CMakeLists.txt change so cmake is automatically rerun.

What context are we talking about here?  The checkin-test.py script always does an explicit configure so it would catch an issue like this.  The fact that I demonstrated that the checkin-test.py script caught the issue suggests that globing is not the key problem.

**Comment by bartlettroscoe** [comment] 2017-05-09 21:32
This issue was closed but the most recent complete CI build still shows build failures:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2885756&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

Reopening until we get confirmation that the build is fixed.

**Comment by jhux2** [comment] 2017-05-09 22:38
> This issue was closed but the most recent complete CI build still shows build failures:
> 
> Reopening until we get confirmation that the build is fixed.

The continuous builds haven't pulled in the revert commits.

**Comment by bartlettroscoe** [comment] 2017-05-09 23:46
> The continuous builds haven't pulled in the revert commits.

It is a good policy to place an Issue "in review" and wait for confirmation of passing on CDash before closing an Issue.  It is too easy for an issue to be fixed on a person's own private machine but have it broken for the standard builds and other people's builds.

**Comment by jhux2** [comment] 2017-05-10 15:58
Stokhos builds are [clean](http://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=Stokhos).  Closing this issue.

**Closed by jhux2** 2017-05-10 15:58 UTC
Labels: MueLu, Panzer, Piro, Stokhos, Trilinos Couplings

**Comment by bartlettroscoe** [comment] 2017-05-10 15:59
The CI build yesterday night:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2885925&filtercount=3&showfilters=1&field1=groupname&compare1=61&value1=Continuous&field2=buildstarttime&compare2=84&value2=now&filtercombine=and

showed all passing builds (and the deltas).

Thanks
