### ISSUE TITLE
MueLu tests failing with checkin script and secondary-stable code enabled

### ISSUE THREAD

**Issue by kddevin** [trilinos/Trilinos#146] opened 2016-02-17 21:01 UTC
@trilinos/muelu 
I am running the checkin script with secondary-stable code enabled.  I see the following failures in MueLu.  Since MueLu uses Zoltan and Zoltan2, I want to make sure that these errors are expected, and not caused by my code changes.  I list my custom configuration options at the bottom of this issue.  Is there some other CMake magic that I need (and, if so, can it be made the default in the checkin script)?

```
1222 - MueLu_ParameterListInterpreterTpetra_MPI_1 (Failed)
1223 - MueLu_ParameterListInterpreterTpetra_MPI_4 (Failed)
```

Error message for 1222:
p=0: **\* Caught standard std::exception of type 'std::invalid_argument' :
 /home/kddevin/code/Trilinos/packages/teuchos/remainder/src/Trilinos_Details_LinearSolverFactory.hpp:599:
 Throw number = 209
 Throw test that evaluated to true: factory.get () == NULL
 Trilinos::Details::getLinearSolver: Package "Ifpack2" is valid, but it never registered a LinearSolverFactory for template parameters MV = Tpetra::MultiVector<double,int,long int,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>, OP = Tpetra::Operator<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, NormType = double.  Trilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION = OFF.

Error message for 1223:
p=0: **\* Caught standard std::exception of type 'std::invalid_argument' :
 /home/kddevin/code/Trilinos/packages/teuchos/remainder/src/Trilinos_Details_LinearSolverFactory.hpp:599:
 Throw number = 132
 Throw test that evaluated to true: factory.get () == NULL
 Trilinos::Details::getLinearSolver: Package "Ifpack2" is valid, but it never registered a LinearSolverFactory for template parameters MV = Tpetra::MultiVector<double,int,long int,Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>, OP = Tpetra::Operator<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, NormType = double.  Trilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION = OFF.

My configuration options:
-D Trilinos_ENABLE_SECONDARY_STABLE_CODE=ON
-D Trilinos_ENABLE_Epetra:BOOL=ON
-D Trilinos_ENABLE_Galeri:BOOL=ON
-D Trilinos_ENABLE_Pamgen:BOOL=ON
-D Zoltan_ENABLE_EXAMPLES:BOOL=ON
-D Zoltan_ENABLE_TESTS:BOOL=ON
-D Zoltan2_ENABLE_EXAMPLES:BOOL=ON
-D Zoltan2_ENABLE_TESTS:BOOL=ON
-D Zoltan2_ENABLE_Experimental:BOOL=ON
-D Zoltan_ENABLE_Scotch:BOOL=ON
-D Zoltan2_ENABLE_Scotch:BOOL=ON
-D Scotch_LIBRARY_DIRS:FILEPATH="/home/kddevin/code/Scotch/scotch_6.0.3/32bit_openmpi/lib"
-D Scotch_INCLUDE_DIRS:FILEPATH="/home/kddevin/code/Scotch/scotch_6.0.3/32bit_openmpi//include"
-D Zoltan_ENABLE_ParMETIS:BOOL=ON
-D Zoltan2_ENABLE_ParMETIS:BOOL=ON
-D ParMETIS_LIBRARY_DIRS:FILEPATH="/home/kddevin/code/ParMETIS/ParMETIS-4.0.3/32bit_openmpi"
-D ParMETIS_INCLUDE_DIRS:FILEPATH="/home/kddevin/code/ParMETIS/ParMETIS-4.0.3/32bit_openmpi"
-D Teuchos_ENABLE_STACKTRACE=OFF
-D MPI_BIN_DIR:PATH=/usr/lib64/openmpi/bin
-D TPL_ENABLE_MPI:BOOL=ON
-D MPI_EXEC_MAX_NUMPROCS:STRING=12
-D TPL_ENABLE_Boost=OFF
-D TPL_ENABLE_Netcdf=OFF
-D TPL_ENABLE_BoostLib=OFF
-D Trilinos_ENABLE_SEACAS:BOOL=OFF
-D Trilinos_ENABLE_STK:BOOL=OFF
-D DART_TESTING_TIMEOUT:STRING=1300
-D Amesos2_ENABLE_KLU2=ON

**Comment by tawiesn** [comment] 2016-02-17 21:10
The ParameterListInterpreter tests are currently failing (also because of other issues, so this is not your fault). But thanks for reporting this new issue. As far as i can see it is also cannot be caused by changes in Zoltan2. Feel free to deactivate these tests when running the checkin script.

**Comment by jhux2** [comment] 2016-02-17 21:12
Karen,
  Could you attach the output of the cmake configure process so we can see exactly what's being enabled?
Thanks,
Jonathan

**Comment by kddevin** [comment] 2016-02-17 21:54
@trilinos/muelu 
Thanks, Jonathan.  Here is it.
[configure_out.txt](https://github.com/trilinos/Trilinos/files/135232/configure_out.txt)

**Comment by mhoemmen** [comment] 2016-12-14 20:54
I'm closing this since it doesn't appear to be an issue any more.  Please reopen if needed.  Thanks!

**Closed by mhoemmen** 2016-12-14 20:54 UTC
Labels: MueLu, ready
