### ISSUE TITLE
Tpetra fails to Configure CUDA in Nightly build on Apollo

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1755] opened 2017-09-20 14:56 UTC
@trilinos/tpetra 

Linux-gcc-4.9.3-MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF has been failing the Nightly build since 9/12.

It looks like it's a cmake error on CUDA:
```
Processing enabled package: Epetra (Libs)
Did not find new version of lapack. dggsvd3 is not available.
Processing enabled package: Tpetra (Classic, TSQR, Core, Tests, Examples)
CMake Error at packages/tpetra/CMakeLists.txt:39 (MESSAGE):
  If building with CUDA, Tpetra requires that you set
  Kokkos_ENABLE_Cuda_Lambda:BOOL=ON, if it is not already ON by default.  For
  details, please refer to Trilinos issue #1682
  (https://github.com/trilinos/Trilinos/issues/1682).  You should also make
  sure, at least with CUDA_VERSION 7.5 or 8.0, to add
  "--expt-extended-lambda" to CMAKE_CXX_FLAGS.


-- Configuring incomplete, errors occurred!
See also "/home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.9.3_cuda_8.0.44/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF/BUILD/CMakeFiles/CMakeOutput.log".
See also "/home/jenkins/slave/workspace/Trilinos_apollo_gcc_4.9.3_cuda_8.0.44/MPI_RELEASE_DEV_DownStream_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-OFF_CUDA-ON_COMPLEX-OFF/BUILD/CMakeFiles/CMakeError.log".
```

Link to one of the fails:
https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3103572

**Comment by tjfulle** [comment] 2017-09-20 15:07
@william76, this is a known issue, see #1630.  A permanent fix is in the works, for now add `-std=c++11 ---expt-extended-lambda` to `CMAKE_CXX_FLAGS`

**Comment by mhoemmen** [comment] 2017-09-20 15:15
On second thought, I should leave this open -- the issue is that apollo has the wrong build options set :-)

**Comment by william76** [comment] 2017-09-20 15:17
@mhoemmen I could add the options that @tjfulle mentioned, but I don't have access to a CUDA machine currently... so I don't think I can test it.  Would you guys rather set the flags or leave that test failing for now since a permanent fix is in the works?

**Comment by tjfulle** [comment] 2017-09-20 15:18
@william76, this issue is discussed more thoroughly in #1682 (the remedy is still the same as I posted).

**Comment by tjfulle** [comment] 2017-09-20 15:23
@william76, I believe the consensus is that we will provide a detailed CMake error message describing how `CMAKE_CXX_FLAGS` should be set to properly configure and build Tpetra on CUDA.  It will be up to individuals to implement the correct flags for now.

We would rather not implement the flags directly in Tpetra since Kokkos is coming up with a platform independent solution.    The permanent fix is being tracked in #1400.

@mhoemmen can correct me if I am wrong.

**Comment by mhoemmen** [comment] 2017-09-20 15:25
@tjfulle is right -- temporary solution would be to change Apollo's build options to add the flags in question, permanent solution would be not to need to do this.

**Comment by jwillenbring** [comment] 2017-09-21 16:07
@mhoemmen @tjfulle I would support the temporary solution here to clean up the nightly failures, and then certainly implement the permanent solution. If we want to leave this failure as a reminder we should move the build to the specialized track instead of nightly.

**Comment by mhoemmen** [comment] 2017-09-21 17:15
@jwillenbring I don't have access to this computer to change its build settings.

**Comment by tjfulle** [comment] 2017-09-22 21:00
@jwillenbring , I don't have access either.

**Comment by jhux2** [comment] 2017-09-22 22:55
I don't think access to the machine itself is necessary.  This change can probably be done through the machine scripts in the repository:  `Trilinos/cmake/ctest/drivers/apollo`.

**Comment by mhoemmen** [comment] 2017-09-25 17:58
@jhux2 wrote:
> I don't think access to the machine itself is necessary. This change can probably be done through the machine scripts in the repository: Trilinos/cmake/ctest/drivers/apollo.

It's not quite so obvious as that.  Jenkins can let servers control build settings, e.g., through `JENKINS_CMAKE_FLAGS`.

**Comment by mhoemmen** [comment] 2017-09-25 17:59
@trilinos/framework

**Comment by mhoemmen** [comment] 2017-09-25 17:59
@jwillenbring I assigned this to you, but please feel free to reassign if there is a better person.

**Comment by william76** [comment] 2017-09-26 17:03
@jwillenbring I added the Cmake flags described above to the Jenkins job that drives this test.  We'll see how it turns out in tonight's run.

**Comment by bmpersc** [comment] 2017-09-26 17:04
@mhoemmen the JENKINS_CMAKE_FLAGS is not a jenkins thing to my knowledge. It looks like @crtrott  added that to only the Apollo jobs. It is fairly cryptic as JENKINS_CMAKE_FLAGS is only used to set CMAKE_CXX_FLAGS for the Trilinos configure which I would never have guessed.

I am a little concerned about doing so for 2 reasons.
1. The options @tjfulle suggested are -std=c++11 and --expt-extended-lambda, but I seem to recall there being some discussion about having -std=c++11 on the compile line twice being bad. Should I verify that the job already has this and just add --expt-extended-lambda or am I misremembering the issue?
2. changing substantive and necessary options like this in jenkins and only jenkins makes me nervous. The method we've previously used is to allow jenkins to control the environment(compilers, TPLs, etc.), but not the configure. This would be a change to that. I'd be more comfortable making this change to the test files for apollo directly, but I see that at least one job on apollo is already using the JENKINS_CMAKE_FLAGS. I'm not sure what would happen if we were to just add those flags. It would certainly change all jobs. If that is a problem I can't really say.

**Comment by etphipp** [comment] 2017-09-26 19:24
This needs to get resolved quickly because we now have no regular cuda testing.  It appears Stokhos broke on Cuda some time in the last few weeks and no one noticed because we don't have any testing once this build went down.

**Comment by mhoemmen** [comment] 2017-09-26 19:37
See #1776 for the failing Stokhos test in CUDA builds.

**Comment by mhoemmen** [comment] 2017-09-27 02:39
@bmpersc I don't really know what the right thing is to do here.

**Comment by bmpersc** [comment] 2017-09-27 16:33
@mhoemmen since the changes to the compiler options was already done by the time I completed my comment I figure we can just roll with it for now. It looks like this still failed last night, but that was due to the lack of the cuda lambda option not also being set. I just pushed that up to the testing for this so we'll see if things are fixed tomorrow.

**Comment by mhoemmen** [comment] 2017-09-27 16:43
Thanks @bmpersc ! :-D

**Comment by mhoemmen** [comment] 2017-09-30 16:51
Apollo successfully configured with CUDA at least as of 29 Sep 2017:

https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-09-29&subproject=Tpetra

Thanks!!!

**Closed by mhoemmen** 2017-09-30 16:51 UTC
Labels: Framework
