### ISSUE TITLE
Kokkos/ROL: build failure with gcc-9.3.0

### ISSUE THREAD

**Issue by shardest** [trilinos/Trilinos#9056] opened 2021-04-26 15:31 UTC
## Bug Report
@trilinos/kokkos

### Description
The Trilinos build was successful. Compiling the ROL example rol/example/rosenbrock/example_01.cpp fails with an error in kokkos when using gcc-9.3.0. I am building the example outside of Trilinos, so it is possible that there is something wrong with my setup, but I thought I'd put in an issue because it builds if I use clang, and I suspect that it is a self-contained problem that isn't related to ROL.

### Steps to Reproduce
1. SHA1:  010e25eda392dcd9df9221affedf3dec8c1423d4
1. Configure script: #!/bin/sh
cd trilinos-build
cmake -DTPL_ENABLE_MPI=ON -DMPI_BASE_DIR=/usr/lib/x86_64-linux-gnu/openmpi/ -DTrilinos_ENABLE_ROL=ON -DCMAKE_INSTALL_PREFIX=/usr/local -DTPL_ENABLE_Netcdf=OFF -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF ../Trilinos
[configure.log](https://github.com/trilinos/Trilinos/files/6378258/configure.log)

In file included from /usr/local/include/impl/Kokkos_Profiling.hpp:52,
                 from /usr/local/include/impl/Kokkos_Tools.hpp:52,
                 from /usr/local/include/Kokkos_HostSpace.hpp:60,
                 from /usr/local/include/Kokkos_Atomic.hpp:72,
                 from /usr/local/include/Kokkos_Complex.hpp:47,
                 from /usr/local/include/Teuchos_ScalarTraits.hpp:59,
                 from /usr/local/include/Teuchos_BLAS.hpp:70,
                 from /usr/local/include/Teuchos_SerialDenseMatrix.hpp:47,
                 from /usr/local/include/Teuchos_SerialDenseVector.hpp:52,
                 from /usr/local/include/ROL_LinearAlgebra.hpp:51,
                 from /usr/local/include/ROL_ConstraintDef.hpp:48,
                 from /usr/local/include/ROL_Constraint.hpp:416,
                 from /usr/local/include/ROL_ConstraintManager.hpp:47,
                 from /usr/local/include/ROL_OptimizationProblem.hpp:49,
                 from /usr/local/include/ROL_TestProblem.hpp:52,
                 from /usr/local/include/ROL_Rosenbrock.hpp:58,
                 ...
/usr/local/include/Kokkos_Tuners.hpp: In instantiation of ‘constexpr const double Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<std::map, 20, long int, std::vector<long int, std::allocator<long int> >, std::less<long int>, std::allocator<std::pair<const long int, std::vector<long int, std::allocator<long int> > > > >::tuning_step’:
/usr/local/include/Kokkos_Tuners.hpp:324:35:   required from ‘Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<Container, MaxDimensionSize, TemplateArguments>::MultidimensionalSparseTuningProblem(Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<Container, MaxDimensionSize, TemplateArguments>::ProblemSpaceInput, const std::vector<std::__cxx11::basic_string<char> >&) [with Container = std::map; long unsigned int MaxDimensionSize = 20; TemplateArguments = {long int, std::vector<long int, std::allocator<long int> >, std::less<long int>, std::allocator<std::pair<const long int, std::vector<long int, std::allocator<long int> > > >}; Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<Container, MaxDimensionSize, TemplateArguments>::ProblemSpaceInput = std::map<long int, std::vector<long int> >]’
/usr/local/include/Kokkos_Tuners.hpp:348:10:   required from ‘auto Kokkos::Tools::Experimental::make_multidimensional_sparse_tuning_problem(const Container<TemplateArguments ...>&, std::vector<std::__cxx11::basic_string<char> >) [with long unsigned int MaxDimensionSize = 20; Container = std::map; TemplateArguments = {long int, std::vector<long int, std::allocator<long int> >, std::less<long int>, std::allocator<std::pair<const long int, std::vector<long int, std::allocator<long int> > > >}]’
/usr/local/include/Kokkos_Tuners.hpp:356:47:   required from here
/usr/local/include/Kokkos_Tuners.hpp:295:18: error: ‘(9.99e-1 / 2.0e+1)’ is not a constant expression
  295 |       tuning_max / max_space_dimension_size;
      |       ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by shardest** [comment] 2021-04-26 15:32
I don't think that this is related to ROL, but wanted to make you aware of the issue, @dpkouri

**Comment by jjellio** [comment] 2021-04-26 20:16
@DavidPoliakoff

**Comment by DavidPoliakoff** [comment] 2021-04-26 20:19
Quick patch: remove "constexpr" on the line above the one in question:

```
                static constexpr double tuning_step = tuning_max / max_space_dimension_size;
```

Needs to not be constexpr
```

**Comment by DavidPoliakoff** [comment] 2021-04-26 20:24
Candidate fix here: https://github.com/kokkos/kokkos/pull/3969

**Comment by DavidPoliakoff** [comment] 2021-04-26 20:27
Fix is broken, I'll iterate

**Comment by DavidPoliakoff** [comment] 2021-04-26 22:06
Fix passes our testing. @shardest : could you say what machine you run this on? I want to check that your build passes with my branch

**Comment by shardest** [comment] 2021-04-26 22:08
This build was on my personal linux machine, running xubuntu 20.04 LTS

**Comment by DavidPoliakoff** [comment] 2021-04-26 22:21
This will be hard to debug. My PR is based off of Kokkos `develop`. I'll try to check out Trilinos and try to do the same thing on top of the Kokkos you have in Trilinos

**Comment by DavidPoliakoff** [comment] 2021-04-26 22:47
@shardest: apologies, but I don't seem to be able to reproduce this on a machine I have access to. I'll see whether my patch against Kokkos gets merged, but theoretically that expression is constexpr I think, modulo perhaps some weirdness with floating point? I'll phone a friend :)

**Comment by shardest** [comment] 2021-04-26 22:54
I don't really understand what is going on, but from what I was reading, perhaps that quotient isn't exactly representable as a double? If I simply change 0.999 to 0.5 (for example), it compiles without any other changes.

**Comment by jjellio** [comment] 2021-04-26 22:57
I mentioned David: My curiosity is if David's tuning work should even be impacting you.

Seems maybe an installation bug if Experimental headers are getting slurped w/out explicit user effort.

The compile bug is curious - but the real question to me is why you are seeing it in the first place ;)

**Comment by shardest** [comment] 2021-04-26 22:58
Also works replacing 0.999 with 0.99. Could do that or compute the result (9.99e-1 / 2.0e+1) = 0.04995 and store it, relegating the computation to a comment... Not a nice solution though.

**Comment by shardest** [comment] 2021-04-26 23:00
@jjellio - @dpkouri can correct me if I'm mistaken, but I think it was a surprise to them that ROL would even depend on this. As a user of ROL, in this case, I certainly have no explicit need for kokkos or tuners.

**Comment by DavidPoliakoff** [comment] 2021-04-26 23:02
@jjellio : no, if you use TeamPolicy's or MDRangePolicy's the tuning stuff is in there. Our experience is that when we try to hide these headers, we wind up with a much bigger mess. I'm in a bit of a bind here, though, I don't think the Kokkos side will change this unless we can reproduce with SEMS modules, it's hard to know whether my fix even _fixes_ your problem otherwise (though it should). I'll keep digging in (in fact, I am digging in on Slack)

**Comment by DavidPoliakoff** [comment] 2021-04-26 23:08
And it looks like the inclusion path is via Kokkos->Teuchos->ROL

**Comment by jjellio** [comment] 2021-04-26 23:19
@shardest Can you post the full compile line? `make VERBOSE=1 -j1` or `ninja -v -j1` 
Wrap in three back ticks (code block) and it won't look as horrible)

I'm wondering if there is a C++ flag that's off.  GCC should use MPFR to do preprocessor arithmetic - I have no idea what it uses for `constexpr` (you'd think mpfr as well, but who knows)

**Comment by jjellio** [comment] 2021-04-26 23:27
Worth adding - didn't Kokkos 3.3 just merge into Develop? This stuff gets tested, but you may be the unlucky first user with this exact config line...
I'll be building more `trilinos/develop` tomorrow, and I definitely build ROL so I can add a data point maybe.

**Comment by ndellingwood** [comment] 2021-04-26 23:52
@jjellio Kokkos 3.4 merged today but after this issue was filed (and the Trilinos SHA referenced in the original post is from 4 days prior)

**Comment by shardest** [comment] 2021-04-27 16:33
Thanks for the help, everyone. Now, I am really confused. I had mentioned trying different values (other than 0.999) and that it built. Now, I switched it back to 0.999, and it still builds. Evidently, something else in my system or setup changed. Maybe I initially built without -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF and then didn't clean everything up when I added it, or maybe I inadvertently updated something. At any rate, I can no longer reproduce the issue. I tried building on an ews blade with gcc-9.3.0, and can't reproduce it there either. So I hope this wasn't all just a waste of time. I would suggest closing this issue unless anyone else can reproduce it.

If it is of any use, the relevant part of my compile line (now working) looked like this (everything else was associated with include directories, unrelated libraries, or options for the object file):
`-std=c++14 -Wall -fopenmp -O3 -DNDEBUG -pthread -frounding-math`

**Comment by DavidPoliakoff** [comment] 2021-04-27 16:45
@shardest, not at all a waste of time. The next people to hit this will (hopefully) see your issue and know to ping me. No problem for me if we close. I'll close my corresponding PR, but not delete the branch :)

**Comment by jjellio** [comment] 2021-04-27 23:05
@DavidPoliakoff You could poke around to get added to the Trilinos/kokkos project. You'd get notifications if that is mentioned.

**Comment by Chrismarsh** [comment] 2021-07-28 19:44
@shardest @DavidPoliakoff Definitely not a waste of time for poor folks like me who run into this!

I have 2/3 machines hitting this in various ways. However for  me, it's code that depends on Belos/Kokkos that hits the probem.

Machine 1: An HPC cluster at my university, gcc 9.3.0 building master as of today (b3b2d8c63dd71e223a0296778f0fe5adf52a2aa5)

```In file included from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Complex.hpp:49,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Teuchos_ScalarTraits.hpp:59,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosStubTsqrAdapter.hpp:34,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosMultiVecTraits.hpp:57,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosLinearProblem.hpp:49,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosSolverManager.hpp:52,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosSolverFactory.hpp:47,
                 from /globalhome/cbm038/HPC/CHM/src/math/LinearAlgebra.hpp:29,
                 from /globalhome/cbm038/HPC/CHM/src/math/LinearAlgebra.cpp:24:
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_NumericTraits.hpp:150:1: error: ‘(1.5e+1 * 2.4100000000000001e+0)’ is not a constant expression
  150 | DIGITS10_HELPER_INTEGRAL(short)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_NumericTraits.hpp:152:1: error: ‘(3.1e+1 * 2.4100000000000001e+0)’ is not a constant expression
  152 | DIGITS10_HELPER_INTEGRAL(int)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_NumericTraits.hpp:154:1: error: ‘(6.3e+1 * 2.4100000000000001e+0)’ is not a constant expression
  154 | DIGITS10_HELPER_INTEGRAL(long int)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_NumericTraits.hpp:156:1: error: ‘(6.3e+1 * 2.4100000000000001e+0)’ is not a constant expression
  156 | DIGITS10_HELPER_INTEGRAL(long long int)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
```

and 

```
In file included from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/impl/Kokkos_Profiling.hpp:51,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/impl/Kokkos_Tools.hpp:52,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_HostSpace.hpp:60,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Atomic.hpp:72,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Complex.hpp:47,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Teuchos_ScalarTraits.hpp:59,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosStubTsqrAdapter.hpp:34,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosMultiVecTraits.hpp:57,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosLinearProblem.hpp:49,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosSolverManager.hpp:52,
                 from /globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/BelosSolverFactory.hpp:47,
                 from /globalhome/cbm038/HPC/CHM/src/math/LinearAlgebra.hpp:29,
                 from /globalhome/cbm038/HPC/CHM/src/math/LinearAlgebra.cpp:24:
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Tuners.hpp: In instantiation of ‘constexpr const double Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<std::map, 20, long int, std::vector<long int, std::allocator<long int> >, std::less<long int>, std::allocator<std::pair<const long int, std::vector<long int, std::allocator<long int> > > > >::tuning_step’:
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Tuners.hpp:338:35:   required from ‘Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<Container, MaxDimensionSize, TemplateArguments>::MultidimensionalSparseTuningProblem(Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<Container, MaxDimensionSize, TemplateArguments>::ProblemSpaceInput, const std::vector<std::__cxx11::basic_string<char> >&) [with Container = std::map; long unsigned int MaxDimensionSize = 20; TemplateArguments = {long int, std::vector<long int, std::allocator<long int> >, std::less<long int>, std::allocator<std::pair<const long int, std::vector<long int, std::allocator<long int> > > >}; Kokkos::Tools::Experimental::MultidimensionalSparseTuningProblem<Container, MaxDimensionSize, TemplateArguments>::ProblemSpaceInput = std::map<long int, std::vector<long int> >]’
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Tuners.hpp:362:10:   required from ‘auto Kokkos::Tools::Experimental::make_multidimensional_sparse_tuning_problem(const Container<TemplateArguments ...>&, std::vector<std::__cxx11::basic_string<char> >) [with long unsigned int MaxDimensionSize = 20; Container = std::map; TemplateArguments = {long int, std::vector<long int, std::allocator<long int> >, std::less<long int>, std::allocator<std::pair<const long int, std::vector<long int, std::allocator<long int> > > >}]’
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Tuners.hpp:370:47:   required from here
/globalhome/cbm038/HPC/.local/easybuild/software/2020/avx2/MPI/gcc9/openmpi4/trilinos/master/include/Kokkos_Tuners.hpp:309:52: error: ‘(9.99e-1 / 2.0e+1)’ is not a constant expression
  309 |   static constexpr double tuning_step = tuning_max / max_space_dimension_size;
      |                                         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Machine 2: Colleagues machine Ubuntu 20.04 + gcc9.3.0 also building master
```
/home/kgreen/.conan/data/trilinos/master/CHM/stable/package/2a22058bf7d0cb9e9ee92edd67c773206a0968a6/include/Kokkos_Tuners.hpp:309:52: error: '(9.99e-1 / 2.0e+1)' is not a constant expression
  309 |   static constexpr double tuning_step = tuning_max / max_space_dimension_size;
```

Machine 3: Github actions env
Works as expected, also building master
https://github.com/Chrismarsh/conan-trilinos/runs/3175365944?check_suite_focus=true

**Comment by Chrismarsh** [comment] 2021-07-29 17:58
I can confirm that the above pull request (kokkos/kokkos#3969) resolves this for me. 
However, I also need to change the `DIGITS10_HELPER_INTEGRAL(TYPE)` macro to not be `static constexpr`
trilinos/master/include/Kokkos_NumericTraits.hpp L 146

**Comment by DavidPoliakoff** [comment] 2021-07-29 19:22
@nliber, don't know if you remember this one. We convinced ourselves that our expressions were constexpr. Do you know why a compiler would barf on those? I'll try to reproduce this one again, it has been a minute since I looked at this. Probably won't have an answer today, just for some fair warning

**Comment by DavidPoliakoff** [comment] 2021-07-29 19:27
Okay never mind that happened quicker than I thought. Reproducer:

https://godbolt.org/z/j1aaPaWP1

If you divide by a double by a size_t template value, that's non-constexpr. But if you divide by just a static constexpr size_t, you're fine. Because _haha logic is dead_

**Comment by DavidPoliakoff** [comment] 2021-07-29 19:28
I'll file a Kokkos bug

**Comment by DavidPoliakoff** [comment] 2021-07-29 19:36
Okay, that's how I'm starting my morning tomorrow. Just verified that these need a fix if the compiler is older than GCC11

**Comment by Chrismarsh** [comment] 2021-07-29 19:43
>If you divide by a double by a size_t template value, that's non-constexpr. But if you divide by just a static constexpr size_t, you're fine. Because haha logic is dead

Oof, good to know.

Thanks for taking a look at this!

**Comment by DavidPoliakoff** [comment] 2021-07-29 20:45
Minimal reproducer with both parts: https://godbolt.org/z/4Yf1cs68c

**Comment by Chrismarsh** [comment] 2021-08-31 18:45
I just needed a fresh mind, was being silly.

I have a PR here that resolves this for me
https://github.com/kokkos/kokkos/pull/4278

Because C++11 has a constexpr digits10 I just used that instead of the expression that is causing issues. It is not clear to me what [log10_2](https://github.com/kokkos/kokkos/blob/develop/core/src/Kokkos_NumericTraits.hpp#L144) is and why it is 2.41 as [log10(2)=0.301[...]](https://www.wolframalpha.com/input/?i=log10%282.0%29) unless I'm totally missing something basic?

**Closed** 2022-11-09 12:42 UTC
Labels: type: bug, MARKED_FOR_CLOSURE, CLOSED_DUE_TO_INACTIVITY
