### ISSUE TITLE
trilinos@develop +cuda %gcc@11.2.0 ^cuda@11.4.4: agent/agent_radix_sort_onesweep.cuh(225): error: expected an identifier

### ISSUE THREAD

**Issue by eugeneswalker** [trilinos/Trilinos#11630] opened 2023-03-06 15:35 UTC
I'm having some trouble building the following `trilinos@develop` spec with Spack:
```
  - trilinos@develop +cuda cuda_arch=80 +amesos +amesos2 +anasazi +aztec +belos +boost
    +epetra +epetraext +ifpack +ifpack2 +intrepid +intrepid2 +isorropia +kokkos +ml
    +minitensor +muelu +nox +piro +phalanx +rol +rythmos +sacado +stk +shards +shylu
    +stokhos +stratimikos +teko +tempus +tpetra +trilinoscouplings +zoltan +zoltan2
    +superlu-dist gotype=long_long ^superlu-dist@develop
```

Here using:
* spack@develop (97c2dd3a5ac64dc338df79c41e8f88b177c32867 from `Sun Mar 5 09:33:23 2023 -0800`)
* Ubuntu 20.04, X86_64
* CUDA 11.4.4
* GCC 11.2.0
* Docker container image `esw123/trilinos-ci-base:2023-03-05`

Spack environment: [spack.yml.txt](https://github.com/trilinos/Trilinos/files/10899786/spack.yml.txt)

<details><summary>Concretization</summary><pre>
==> Starting concretization
==> Environment concretized in 29.82 seconds.
==> Concretized trilinos@develop+amesos+amesos2+anasazi+aztec+belos+boost+cuda+epetra+epetraext+ifpack+ifpack2+intrepid+intrepid2+isorropia+kokkos+minitensor+ml+muelu+nox+phalanx+piro+rol+rythmos+sacado+shards+shylu+stk+stokhos+stratimikos+superlu-dist+teko+tempus+tpetra+trilinoscouplings+zoltan+zoltan2 cuda_arch=80 gotype=long_long ^superlu-dist@develop
 -   y2ueswl  trilinos@develop%gcc@11.2.0~adelus~adios2+amesos+amesos2+anasazi+aztec~basker+belos+boost~chaco~complex+cuda~cuda_rdc~debug~dtk+epetra+epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~exodus+explicit_template_instantiation~float+fortran~gtest~hdf5~hypre+ifpack+ifpack2+intrepid+intrepid2~ipo+isorropia+kokkos~mesquite+minitensor+ml+mpi+muelu~mumps+nox~openmp~panzer+phalanx+piro~python~rocm~rocm_rdc+rol+rythmos+sacado~scorec+shards+shared+shylu+stk+stokhos+stratimikos~strumpack~suite-sparse~superlu+superlu-dist+teko+tempus+thyra+tpetra+trilinoscouplings~uvm+wrapper~x11+zoltan+zoltan2 build_system=cmake build_type=RelWithDebInfo cuda_arch=80 cxxstd=17 dev_path=/trilinos gotype=long_long arch=linux-ubuntu20.04-x86_64
[+]  4gsjoyl      ^boost@1.80.0%gcc@11.2.0~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug+exception~fiber~filesystem+graph~graph_parallel~icu~iostreams~json~locale~log+math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded+stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=98 patches=a440f96 visibility=hidden arch=linux-ubuntu20.04-x86_64
[+]  bhzpcns      ^cmake@3.25.2%gcc@11.2.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64
[+]  w5d2qa2          ^ncurses@6.4%gcc@11.2.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  wgbg7zv          ^openssl@1.1.1t%gcc@11.2.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
[+]  u4lngtf              ^ca-certificates-mozilla@2023-01-10%gcc@11.2.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  6mvuwgi      ^cuda@11.4.4%gcc@11.2.0+allow-unsupported-compilers~dev build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  yarrong          ^libxml2@2.10.3%gcc@11.2.0~python build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  m3pvej7              ^libiconv@1.17%gcc@11.2.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  wtu7z3r              ^xz@5.4.1%gcc@11.2.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  yjcfm6i      ^hwloc@2.9.0%gcc@11.2.0~cairo+cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools cuda_arch=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  3uwybxz          ^libpciaccess@0.16%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  q3utows              ^libtool@2.4.7%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  v64trbu              ^util-macros@1.19.3%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  k4gexxg          ^pkgconf@1.8.0%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  muiv2e5      ^kokkos-nvcc-wrapper@3.2.00%gcc@11.2.0+mpi build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  b45jour      ^metis@5.1.0%gcc@11.2.0~gdb~int64~ipo~real64+shared build_system=cmake build_type=RelWithDebInfo patches=4991da9,93a7903,b1225da arch=linux-ubuntu20.04-x86_64
[+]  5uekxti      ^mpich@4.1%gcc@11.2.0~argobots~cuda+fortran+hwloc+hydra+libxml2+pci~rocm+romio~slurm~two_level_namespace~vci~verbs~wrapperrpath build_system=autotools datatype-engine=auto device=ch4 netmod=ofi pmi=pmi arch=linux-ubuntu20.04-x86_64
[+]  ybkua77          ^findutils@4.9.0%gcc@11.2.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-x86_64
[+]  2kqs3hq          ^libfabric@1.16.1%gcc@11.2.0~debug~kdreg build_system=autotools fabrics=sockets,tcp,udp arch=linux-ubuntu20.04-x86_64
[+]  4kablpa          ^yaksa@0.2%gcc@11.2.0~cuda~rocm build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  oilw3eu              ^autoconf@2.69%gcc@11.2.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-x86_64
[+]  hyuiaqt              ^automake@1.16.5%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  kub57xs              ^m4@1.4.19%gcc@11.2.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]  q5jegbp                  ^diffutils@3.8%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  qhzhqvi                  ^libsigsegv@2.13%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  m7i64w3              ^python@3.10.8%gcc@11.2.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-ubuntu20.04-x86_64
[+]  mc2w3wp                  ^expat@2.5.0%gcc@11.2.0+libbsd build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  yghmqer                      ^libbsd@0.11.7%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  iumn6fg                          ^libmd@1.0.4%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  tapsqxr                  ^gettext@0.21.1%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  ihb6sad                      ^tar@1.34%gcc@11.2.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64
[+]  4whp3qf                          ^pigz@2.7%gcc@11.2.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]  hd2hz4g                          ^zstd@1.5.2%gcc@11.2.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  4wrppns                  ^libffi@3.4.4%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  2v6oql6                  ^libxcrypt@4.4.33%gcc@11.2.0~obsolete_api build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  2d5q4vg                  ^readline@8.2%gcc@11.2.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
[+]  gpdw6tb                  ^sqlite@3.40.1%gcc@11.2.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  do5lyjw                  ^util-linux-uuid@2.38.1%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  rlmkapc      ^openblas@0.3.21%gcc@11.2.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=114f95f,d3d9b15 symbol_suffix=none threads=none arch=linux-ubuntu20.04-x86_64
[+]  wtxegrh          ^perl@5.36.0%gcc@11.2.0+cpanm+open+shared+threads build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  3npiopn              ^berkeley-db@18.1.40%gcc@11.2.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]  l62f6pr              ^bzip2@1.0.8%gcc@11.2.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
[+]  yfzzydf              ^gdbm@1.23%gcc@11.2.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]  jnczgdt      ^parmetis@4.0.3%gcc@11.2.0~gdb~int64~ipo+shared build_system=cmake build_type=RelWithDebInfo patches=4f89253,50ed208,704b84f arch=linux-ubuntu20.04-x86_64
[+]  5ksxncf      ^superlu-dist@develop%gcc@11.2.0~cuda~int64~ipo~openmp~rocm+shared build_system=cmake build_type=RelWithDebInfo arch=linux-ubuntu20.04-x86_64
[+]  4a4hcyy      ^zlib@1.2.13%gcc@11.2.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-x86_64

</pre></details>

Install error:
```
$> spack -e . install
...
==> Installing trilinos-develop-y2ueswlcwyue7nqkigjrcjzy26f7x7qe
==> No binary for trilinos-develop-y2ueswlcwyue7nqkigjrcjzy26f7x7qe found: installing from source
==> No patches needed for trilinos
==> trilinos: Executing phase: 'cmake'
==> trilinos: Executing phase: 'build'
                                                                                                                                                                                         g

==> Error: ProcessError: Command exited with status 2:
    'make' '-j48'

4 errors found in build log:
     9632                      from /trilinos/packages/stokhos/src/sacado/kokkos/vector/amesos2/Stokhos_Amesos2_MP_Vector.hpp:50,
     9633                      from /trilinos/packages/stokhos/src/sacado/kokkos/vector/muelu/Stokhos_MueLu_MP_Vector.hpp:55,
     9634                      from /trilinos/spack-build-y2ueswl/packages/stokhos/src/MueLu_RefMaxwell_MP_Vector_16_Serial.cpp:54:
     9635     /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeho
              lder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-11.2.0/superlu-dist-develop-5ksxncfv4vteyzsh4s6izjefjpfq2b
              cd/include/superlu_dist_config.h:10: note: this is the location of the previous definition
     9636        10 | #define HAVE_PARMETIS TRUE
     9637           |
  >> 9638     /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeho
              lder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-11.2.0/cuda-11.4.4-6mvuwgiq7xhrpq56wmu6dx47oiry545y/bin/..
              /targets/x86_64-linux/include/cub/device/dispatch/../../agent/agent_radix_sort_onesweep.cuh(225): error: expected an identifier
     9639
     9640     In file included from /trilinos/packages/zoltan/src/include/zoltan_types.h:85,
     9641                      from /trilinos/packages/zoltan/src/include/zoltan.h:51,
     9642                      from /trilinos/packages/zoltan/src/include/zoltan_cpp.h:57,
     9643                      from /trilinos/packages/muelu/src/Rebalancing/MueLu_ZoltanInterface_decl.hpp:53,
     9644                      from /trilinos/spack-build-y2ueswl/packages/muelu/src/MueLu_ZoltanInterface.hpp:1,

     ...

     9706                      from /trilinos/packages/stokhos/src/sacado/kokkos/vector/muelu/Stokhos_MueLu_MP_Vector.hpp:55,
     9707                      from /trilinos/spack-build-y2ueswl/packages/stokhos/src/MueLu_ZoltanInterface_MP_Vector_16_Serial.cpp:54:
     9708     /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeho
              lder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-11.2.0/superlu-dist-develop-5ksxncfv4vteyzsh4s6izjefjpfq2b
              cd/include/superlu_dist_config.h:10: note: this is the location of the previous definition
     9709        10 | #define HAVE_PARMETIS TRUE
     9710           |
     9711     1 error detected in the compilation of "/trilinos/spack-build-y2ueswl/packages/stokhos/src/MueLu_Zoltan2Interface_MP_Vector_16_Serial.cpp".
  >> 9712     make[2]: *** [packages/stokhos/src/CMakeFiles/stokhos_muelu_mp_16_serial.dir/build.make:1927: packages/stokhos/src/CMakeFiles/stokhos_muelu_mp_16_serial.dir/MueLu_Zoltan2In
              terface_MP_Vector_16_Serial.cpp.o] Error 1
     9713     make[2]: *** Waiting for unfinished jobs....
     9714     /trilinos/packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp(217): warning: calling a constexpr __host__ function("Stokhos::StaticFixedStorage<int, double, (int
              )16,  ::Kokkos::Serial> ::StaticFixedStorage(const Stokhos::StaticFixedStorage<int, double, (int)16,  ::Kokkos::Serial> &)") from a __host__ __device__ function("Sacado::MP
              ::Vector< ::Stokhos::StaticFixedStorage<int, double, (int)16,  ::Kokkos::Serial> > ::Vector") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used t
              o allow this.
     9715
     9716     In file included from /trilinos/packages/zoltan/src/include/zoltan_types.h:85,
     9717                      from /trilinos/packages/zoltan2/core/src/algorithms/Zoltan2_TPLTraits.hpp:55,
     9718                      from /trilinos/packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1.hpp:20,

     ...

     10017                     from /trilinos/packages/stokhos/src/sacado/kokkos/vector/muelu/Stokhos_MueLu_MP_Vector.hpp:55,
     10018                     from /trilinos/spack-build-y2ueswl/packages/stokhos/src/MueLu_ParameterListInterpreter_MP_Vector_16_Serial.cpp:54:
     10019    /spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeho
              lder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholde/linux-ubuntu20.04-x86_64/gcc-11.2.0/superlu-dist-develop-5ksxncfv4vteyzsh4s6izjefjpfq2b
              cd/include/superlu_dist_config.h:10: note: this is the location of the previous definition
     10020       10 | #define HAVE_PARMETIS TRUE
     10021          |
     10022    make[2]: Leaving directory '/trilinos/spack-build-y2ueswl'
  >> 10023    make[1]: *** [CMakeFiles/Makefile2:13970: packages/stokhos/src/CMakeFiles/stokhos_muelu_mp_16_serial.dir/all] Error 2
     10024    make[1]: Leaving directory '/trilinos/spack-build-y2ueswl'
  >> 10025    make: *** [Makefile:159: all] Error 2
```

Full logs:
[build-logs.tgz](https://github.com/trilinos/Trilinos/files/10899867/build-logs.tgz)

FYI @jwillenbring @keitat @kuberry @psakievich @sethrj

**Comment by fryeguy52** [comment] 2023-03-06 16:13
@eugeneswalker I don't know if this is the cause but when building trilinos@develop through spack I have to add cxxstd=17 to my spec as the current default s 14, but develop requires 17

**Comment by sethrj** [comment] 2023-03-06 16:17
There's a conflict
```python
    conflicts("cxxstd=14", when="@14:")
```
which will prevent it building witih C++14 on develop.

**Comment by ndellingwood** [comment] 2023-03-06 18:44
Here is the referenced cub line: https://github.com/NVIDIA/cub/blob/c1aa59a1a792ec6821f154dd47973f43f1be01be/cub/agent/agent_radix_sort_onesweep.cuh#L225 , which defines a static var `EMPTY`

I ran into a similar problem with cuda/11.4 builds with Amesos2 KLU2 code due to defining a macro named `EMPTY`, which I resolved by renaming the macro. As added info (in case useful), I did not see the error with cuda/11.2 since the corresponding version of cub did not contain the static var `EMPTY` in the cuda/11.2 version; I mention just in case you have encountered similar discrepancies with different cuda versions

I did not encounter any further problems with Trilinos after the Amesos2::KLU2 updates, but I see a couple other spots in Trilinos that define an `EMPTY` macro (various solvers in common/auxiliarySoftware/SuiteSparse/src), I will put in a PR today to rename those

If the problem in this issue is due to similar causes that I encountered, and updates to Trilinos do not resolve the problem, then similar updates may be needed for SuperLU_Dist as well which defines a macro named `EMPTY` in a few files, and should be reported to the developers. The `EMPTY` macro is defined in the following locations:
https://github.com/xiaoyeli/superlu_dist/blob/5c134712a0ab22775b1c801acaf42b05965a3215/SRC/util_dist.h#L74
https://github.com/xiaoyeli/superlu_dist/blob/5c134712a0ab22775b1c801acaf42b05965a3215/SRC/colamd.c#L674
https://github.com/xiaoyeli/superlu_dist/blob/5c134712a0ab22775b1c801acaf42b05965a3215/SRC/old_colamd.c#L363

**Comment by eugeneswalker** [comment] 2023-03-06 22:45
> ... I did not see the error with cuda/11.2 since the corresponding version of cub did not contain the static var `EMPTY` in the cuda/11.2 version; I mention just in case you have encountered similar discrepancies with different cuda versions ...

Yes! I do not see this problem when using CUDA 11.2.2, all else equal. Thank you!

**Comment by ndellingwood** [comment] 2023-03-07 03:53
Thanks for the udpate @eugeneswalker , glad you're able to continue working for now

PR #11635 up which renames various usages of the macro `EMPTY`. If the same problem continues with cuda/11.4 after merge of that PR, the next step might be do a similar renaming of the `EMPTY` macro in the SuperLU_DIST source code and see if that resolves the issue, and file a corresponding issue with the development team

**Comment by ndellingwood** [comment] 2023-03-13 21:11
PR #11635 has been merged

@eugeneswalker I'm going to close this issue as being resolved on the Trilinos side. If you get a chance, I'd be curious to hear if your build issues are resolved or if you continue to experience similar compilation error messages (in which case, developers for SuperLU_Dist and/or other TPLs used in the build may need to be notified to make similar renaming changes to macros defined with name `EMPTY`)

**Closed** 2023-03-13 21:11 UTC
Labels: type: bug
