### ISSUE TITLE
Work-around (not a bug) for recent changes to check-in test script

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#924] opened 2016-12-13 20:48 UTC
I discussed this with @maherou , and he agreed that it would be helpful for me to post these instructions, as a way to smooth the eventual transition to a pull request model.

Suppose that you were using the (old) check-in test script before.  The #482 fix broke this process.  If you want your old check-in test scripts to work, you'll need to do the following:

  1. Change path to internal check-in.py script: `${TRILINOS_PATH}/cmake/tribits/ci_support/checkin-test.py` (replace `${TRILINOS_PATH}` with path to your Trilinos source directory)

  2. Add the following arguments to the script: `--default-builds="" –extra-builds=MPI_DEBUG,SERIAL_RELEASE` (this removes that MPI_RELEASE_DEBUG_* build and replaces it with the old builds, and also enables all packages, not just Primary Tested)

**Comment by mhoemmen** [comment] 2016-12-13 22:48
The @trilinos/muelu team also expressed an interest in this workflow.

**Comment by bartlettroscoe** [comment] 2016-12-14 01:50
Should have already been covered by my email:

----

From: Bartlett, Roscoe A 
Sent: Friday, December 09, 2016 4:09 PM
To: 'Trilinos Developers List'
Cc: 'Trilinos Framework List'
Subject: New Trilinos checkin-test policy: checkin-test-sems.sh

Hello Trilinos Developers,

...

   https://github.com/trilinos/Trilinos/wiki/Policies-|-Safe-Checkin-Testing

...

For those still using the raw Python checkin-test.py script for other purposes, you can still use the raw script as described in the note at the bottom of that wiki page.

...

----

And the bottom of that wiki page says:

* The raw checkin-test.py script under Trilinos/cmake/tribits/ci_support/checkin-test.py can still be used for doing local development work and testing or any workflow other than pushing to the main Trilinos 'develop' branch. (Use the checkin-test-sems.sh script as an example template.)

One minor amendment you want to make is to use `--default-builds= --st-extra-builds=<build1>,<build2>,...`.  That will not test experimental packages that get changed.

But why not just use checkin-test-sems.sh using the standard SEMS env and the standard set of PT packages to push?

**Comment by mhoemmen** [comment] 2016-12-14 20:32
MueLu developers didn't know how to use checkin-test-sems.sh, and requested a patch to get the old workflow back.

**Comment by mhoemmen** [comment] 2016-12-14 20:42
See also #930.

**Comment by bartlettroscoe** [comment] 2016-12-15 21:08
I think this is now addressed in:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing

which states:

* The raw script `Trilinos/checkin-test.py` can still be used for doing local development work and testing or any workflow and can even be used for pushing (but please prefer to use the `checkin-test-sems.sh` script on a RHEL 6 machine with the SEMS env when pushing to the main Trilinos 'develop' branch).  However, unless you can define the `MPI_RELEASE_DEBUG_SHARED_PT.config` file to support the full set of PT packages and TPLs, then just disable that build by running with your own defined builds by passing in `--default-builds= --st-extra-builds=<build0>,<build1>,...`.

See https://github.com/trilinos/Trilinos/issues/930#issuecomment-267428172.

Can we close this Issue and just point to the updated wiki page?

**Comment by mhoemmen** [comment] 2016-12-16 00:06
@bartlettroscoe wrote:
> Can we close this Issue and just point to the updated wiki page?

I'm OK with that, as long as it's OK with the @trilinos/muelu developers.  Thanks!

**Comment by tawiesn** [comment] 2016-12-17 16:53
I would be ok with closing it.

**Comment by jhux2** [comment] 2016-12-22 22:11
@bartlettroscoe Argh, I just followed the instructions on the wiki (not the instructions here), and my COMMON.config file is getting blown away.  I thought COMMON.config is where I stash things like the location of blas and lapack.  Is this expected behavior?

**Comment by jhux2** [comment] 2016-12-22 22:17
The file "MPI_RELEASE_DEBUG_SHARED_ST.config" is also getting overwritten.  Do the common defaults now go in a different file?

**Comment by jhux2** [comment] 2016-12-22 22:32
The instructions from @mhoemmen work for me -- I'll continue to use the old checkin script.

**Comment by bartlettroscoe** [comment] 2016-12-22 22:38
> Argh, I just followed the instructions on the wiki (not the instructions here), and my COMMON.config file is getting blown away. I thought COMMON.config is where I stash things like the location of blas and lapack. Is this expected behavior?

> The file "MPI_RELEASE_DEBUG_SHARED_ST.config" is also getting overwritten. Do the common defaults now go in a different file?

@jhux2, the whole point of the SEMS env and the checkin-test-sems.sh script is that it defines a complete and sufficient env to perform a pre-push CI build with the newly updated set of PT Triilnos packages and TPLs.  Therefore, we don't want people to be setting anything extra if they are using checkin-test-sems.sh.  If you feel the need to mess with these CMake options, then you don't have the SEMS modules defined correctly and you should not be using checkin-test-sems.sh.

However, this does not stop you from trying to use the updated checkin-test..py script and the newly defined MPI_RELEASE_DEBUG_SHARED_ST build to run a standard CI build on your machine without the SEMS env.  The issue is that you just can't do that with the checkin-test-sems.sh script.  Instead, you will need to write your own driver script that directly calls checkin-test.py and sets up COMMON.conf and MPI_RELEASE_DEBUG_SHARED_ST.config that finds everything correctly for your env to support that build (and all the TPLs that are needed).  That is what I was trying to explain at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing#raw_checkin_test_py

I can demonstrate that with an env built out of the standard CASL VERA build env (which includes all of these TPLs but different versions and different version of the compiler and MPI).  But I would never use that env to do the final pre-push testing for Trilinos because it would different from the standard CI build.  But for local testing, that would actually be pretty helpful so I will do that soon.

Does this make sense?  If not, please let me know and then let's talk through this over the phone or better-yet Skype for Business.  It should hopefully not take longer than a few minutes to clear up these misunderstandings.

**Comment by jhux2** [comment] 2016-12-22 22:46
> However, this does not stop you from trying to use the updated checkin-test..py script and the newly defined MPI_RELEASE_DEBUG_SHARED_ST build to run a standard CI build on your machine without the SEMS env. The issue is that you just can't do that with the checkin-test-sems.sh script. Instead, you will need to write your own driver script that directly calls checkin-test.py and sets up COMMON.conf and MPI_RELEASE_DEBUG_SHARED_ST.config that finds everything correctly for your env to support that build (and all the TPLs that are needed). That is what I was trying to explain at:

Right, I now realize that the sems script *should* pick up everything automagically from the SEMS modules that are loaded.  For the moment, I am happy with the old script approach, so I'm going to stay with that.

**Comment by bartlettroscoe** [comment] 2016-12-22 22:56
> Right, I now realize that the sems script should pick up everything automagically from the SEMS modules that are loaded. For the moment, I am happy with the old script approach, so I'm going to stay with that.

Sounds good.

But just to ask, do you have access to the SEMS env that you could use to test/push with the checkin-test-sems.sh script?  That would maximize the chances that the standard CI build will keep working.  As we have seen just in the last month since this new CI build has been running, little differences in GCC and OpenMPI versions can break the CI build for others.

Otherwise, can we close this issue?  Is what I wrote at:

* https://github.com/trilinos/Trilinos/wiki/Policies-%7C-Safe-Checkin-Testing#raw_checkin_test_py

(which is same thing @mhoemmen said [above](https://github.com/trilinos/Trilinos/issues/924#issue-195364177)) sufficient?

**Comment by jhux2** [comment] 2016-12-22 23:08
Yes, let's close this issue.

**Closed by jhux2** 2016-12-22 23:08 UTC
Labels: Framework
