### ISSUE TITLE
Framework: Cuda PR testing fails all tests (PR Testing Blocked)

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#5147] opened 2019-05-09 20:21 UTC
Something is seriously messed up with the Cuda testing as part of the autotesting system.  *All* cuda tests are failing.

All PRs will likely be blocked until this is fixed.

https://github.com/trilinos/Trilinos/pull/5144

**Comment by csiefer2** [comment] 2019-05-09 20:22
@trilinos/framework @jwillenbring @prwolfe @william76

**Comment by william76** [comment] 2019-05-10 14:11
#5124 as well...

@jwillenbring @prwolfe @ZUUL42 

I had a quick glance over at the [cuda jobs on Jenkins][1] and they're definitely all failing.  Have any of you guys had a chance to look at it?

Is it possible it's an additive problem?  @bartlettroscoe are you seeing cuda errors with ATDM testing, or is this just affecting our Trilinos PRs?

[1]: https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/Trilinos_pullrequest_cuda_9.2/

**Comment by bartlettroscoe** [comment] 2019-05-10 14:17
Something as gone wrong on 'ride'.  This is not a problem with the code.  If you look at the [ATDM Trilinos CUDA builds today](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-05-10&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda), it is clear the problem is with 'ride' and not Trilinos itself.

Someone needs to contact 'ride-help' and ask what changed.  I know there was an upgrade of jenkins-srn.sandia.gov that completed Wednesday 5/1/2019.  That seems like the first place to start.

**Comment by william76** [comment] 2019-05-10 14:18
@bartlettroscoe Thanks!
I just saw a new email thread that Paul kicked off with ride-help and Si has responded.  =)

**Comment by prwolfe** [comment] 2019-05-10 14:27
I saw failures in atom jobs as well. I put in a ticket with the ride admins, but it's possible that the wrapper script may be the common thread.

**Comment by prwolfe** [comment] 2019-05-10 14:27
Otherwise I am with Ross - it's not at our end.

**Comment by nmhamster** [comment] 2019-05-10 14:32
@prwolfe / @william76 / @bartlettroscoe - can you give me nodes you were running on please?

**Comment by csiefer2** [comment] 2019-05-10 14:35
Thanks for hunting this down!

**Comment by prwolfe** [comment] 2019-05-10 14:39
I am seeing this on most of them

13, 16, 7, 12, 11, 10

Which is why I had thought of software changes…

-----------------------------------------------------------------------
Recommending policy and creating automation to
enable DevOps in the Trilinos and CTH organizations.

**Comment by nmhamster** [comment] 2019-05-10 14:52
@prwolfe / @william76 / @bartlettroscoe - there hasn't been any changes in the Ride environment (yet). The CUDA-10.1 upgrade is schedule so it will change shortly. I am a bit slammed today but this sounds like a high priority so I'll see if we can get a look at it.

**Comment by bartlettroscoe** [comment] 2019-05-10 14:58
Looking at [this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-05-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=buildname&compare2=63&value2=cuda&field3=site&compare3=61&value3=ride&field4=buildstarttime&compare4=83&value4=2019-05-01) it seems something changed between 5/8/2019 and 5/9/2019.   Unfortunately, we don't have version info shown on CDash for the builds on ride on 5/9/2019 because of CDash being down due to a bad upgrade.  Luckily, we have first-parent history on the 'atdm-nightly' branch to figure this out.

```
$ cd Trilinos/

$ git log-short --name-status --first-parent github/atdm-nightly

a0f4145 "Merge remote-tracking branch 'origin/develop' into atdm-nightly"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Wed May 8 21:05:25 2019 -0600 (2 days ago)

39aabb7 "Merge remote-tracking branch 'origin/develop' into atdm-nightly"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue May 7 21:05:19 2019 -0600 (3 days ago)

...
```

The set of commits pulled over that time are:

```
$ git log-short --no-merges --dirstat=0 a0f4145 --not 39aabb7

568c586 "MueLu: Rebase"
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Tue May 7 16:10:10 2019 -0600 (3 days ago)

  20.0% packages/muelu/test/interface/complex/Output/
  47.4% packages/muelu/test/interface/default/Output/
  16.1% packages/muelu/test/interface/kokkos-complex/Output/
  16.3% packages/muelu/test/interface/kokkos/Output/
   0.0% packages/muelu/test/interface/

906d25e "Tpetra: Fix #4951 (remove normImpl ETI)"
Author: Mark Hoemmen <mhoemme@sandia.gov>
Date:   Tue May 7 15:10:57 2019 -0600 (3 days ago)

  12.2% packages/stokhos/src/
  87.7% packages/tpetra/core/src/

7586e20 "avoid double testing a condition"
Author: Geoffrey C Danielson <gcdanie@sandia.gov>
Date:   Tue May 7 14:20:42 2019 -0600 (3 days ago)

 100.0% packages/tpetra/core/src/

b8f43ef "MueLu: Updateing diagonal limiting"
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Tue May 7 11:05:25 2019 -0600 (3 days ago)

  75.9% packages/muelu/src/Misc/
  24.0% packages/muelu/test/unit_tests/

e1abc04 "Xpetra: More Updates"
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Tue May 7 11:05:09 2019 -0600 (3 days ago)

 100.0% packages/xpetra/sup/Utils/

709486d "Xpetra: Making code compile"
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon May 6 14:20:07 2019 -0600 (3 days ago)

   1.1% packages/muelu/test/unit_tests/
  98.8% packages/xpetra/sup/Utils/

c570e5d "MueLu: Adding relative diagonal flooring to both RAP and RAPShift"
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon May 6 10:09:56 2019 -0600 (3 days ago)

   7.1% packages/muelu/doc/UsersGuide/
  16.4% packages/muelu/src/Misc/
   2.7% packages/muelu/src/MueCentral/
  73.5% packages/muelu/test/unit_tests/

fb27d53 "Xpetra: Adding relative diagonal flooring capability"
Author: Chris Siefert <csiefer@sandia.gov>
Date:   Mon May 6 10:09:31 2019 -0600 (3 days ago)

 100.0% packages/xpetra/sup/Utils/

b425c76 "add throw to row matrix add"
Author: Geoffrey C Danielson <gcdanie@sandia.gov>
Date:   Fri May 3 13:31:43 2019 -0600 (7 days ago)

 100.0% packages/tpetra/core/src/
```

and the total diffs:

```
$ git diff --dirstat=0 a0f4145 --not 39aabb7
   0.6% packages/muelu/doc/UsersGuide/
   1.8% packages/muelu/src/Misc/
   0.2% packages/muelu/src/MueCentral/
  14.2% packages/muelu/test/interface/complex/Output/
  33.7% packages/muelu/test/interface/default/Output/
  11.4% packages/muelu/test/interface/kokkos-complex/Output/
  11.5% packages/muelu/test/interface/kokkos/Output/
   0.0% packages/muelu/test/interface/
   6.4% packages/muelu/test/unit_tests/
   1.8% packages/stokhos/src/
  13.6% packages/tpetra/core/src/
   4.2% packages/xpetra/sup/Utils/
```

None of those changes impact any of the env or driver scripts or even Kokkos (and we are seeing Kokkos failures too as shown [here](https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=5012956)).

So it does not look like there were any changes in Trilinos that could have caused this.

**Comment by bartlettroscoe** [comment] 2019-05-10 14:59
> I know there was an upgrade of jenkins-srn.sandia.gov that completed Wednesday 5/1/2019. That seems like the first place to start.

Sorry, a change on 5/1/2019 can't be it.  But there was some "maintenance" on several machines on 5/8/2019.  But 'ride' nor the jenkins-srn server were mentioned.

**Comment by nmhamster** [comment] 2019-05-10 14:59
@bartlettroscoe - we are looking into this for you, but Ride will be in DST for the CUDA 10.1 upgrade most of the day.

**Comment by nmhamster** [comment] 2019-05-11 21:48
@bartlettroscoe / @prwolfe / @william76 - I think we have root caused the issue on Ride. This affects CUDA9.2 and 10.1 builds. The details are rather laborious to go into, so I will try to save your weekend time for something more interesting. There is a fix which the admins will need to put in place when the DST work continues on Monday. I'll do some shake out testing after than to confirm we are in good shape. Just wanted to give you a heads up on possible progress.

**Comment by prwolfe** [comment] 2019-05-13 12:28
Si,

Thanks for the update. I appreciate the effort this must have taken to run down.

-----------------------------------------------------------------------
Recommending policy and creating automation to
enable DevOps in the Trilinos and CTH organizations.

**Closed** 2019-05-15 21:32 UTC
Labels: Framework, PA: Framework, type: bug
