### ISSUE TITLE
Kokkos test

### ISSUE THREAD

**Issue by kyungjoo-kim** [trilinos/Trilinos#29] opened 2015-11-24 21:17 UTC
Kokkos testing in Trilinos does not work. It looks like the cmake does not properly include src directory in Kokkos. The configuration that I use is okay with the old Sandia repo. 

Kyungjoo
```
cd                                                                                                            
/nfshome/kyukim/Work/lib/trilinos/build/shylu/compton/intel-test/packages/kokkos/example/query_device         
&& /home/software/intel/ics_install/impi/4.1.1.036/intel64/bin/mpiicpc                                        
-O3 -g -mavx -opt-report=5 -DMPICH_IGNORE_CXX_SEEK -std=c++11 -O3                                             
-DNDEBUG                                                                                                      
-I/nfshome/kyukim/Work/lib/trilinos/build/shylu/compton/intel-test                                            
-I/nfshome/kyukim/Work/lib/trilinos/build/shylu/compton/intel-test/packages/kokkos/example/query_device       
-I/nfshome/kyukim/Work/lib/trilinos/trunk/packages/kokkos/example/query_device                                
-o CMakeFiles/KokkosExample_query_device.dir/query_device.cpp.o -c                                            
/nfshome/kyukim/Work/lib/trilinos/trunk/packages/kokkos/example/query_device/query_device.cpp                 
icpc: remark #10397: optimization reports are generated in *.optrpt                                           
files in the output location                                                                                  
/nfshome/kyukim/Work/lib/trilinos/trunk/packages/kokkos/example/query_device/query_device.cpp(47):            
catastrophic error: cannot open source file "Kokkos_Macros.hpp"                                               
  #include <Kokkos_Macros.hpp>
```

**Comment by crtrott** [comment] 2015-11-25 21:50
Do you have a replication case? For me it works.

**Comment by kyungjoo-kim** [comment] 2015-11-25 22:01
Yes I see for both my local machine and compton. I send you my configuration script to your sandia email.

**Comment by mhoemmen** [comment] 2016-03-06 13:29
I'm closing this issue since it looks like it's not a bug (anymore).  Please feel free to reopen if this is not the case.

**Closed by mhoemmen** 2016-03-06 13:29 UTC
Labels: help wanted, Kokkos
