### ISSUE TITLE
MueLu: expected type-specifier error

### ISSUE THREAD

**Issue by hillyuan** [trilinos/Trilinos#5952] opened 2019-09-21 02:14 UTC
## Bug Report
@trilinos/\MueLu

### Description
Following  error when compile in Ubuntu with gcc

> MueLu_FactoryManager_def.hpp:163:108: error: expected type-specifier before ‘ScaledNullspaceFactory’

**Comment by DABH** [comment] 2019-09-21 19:22
This is a duplicate of https://github.com/trilinos/Trilinos/issues/5948 but your fix looks good, thanks for getting to the bottom of this

**Comment by mhoemmen** [comment] 2019-09-23 15:13
@trilinos/muelu

**Comment by csiefer2** [comment] 2019-09-23 16:00
See #5963

**Comment by jhux2** [comment] 2019-09-23 18:19
Closing as duplicate of #5948.

**Closed by jhux2** 2019-09-23 18:19 UTC
Labels: impacting: build, pkg: MueLu, type: bug
