### ISSUE TITLE
Warnings using Ninja for Building Trilinos

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#2245] opened 2018-02-16 03:20 UTC
@trilinos/framework @bartlettroscoe @trilinos/muelu 

I am getting these warnings when building using Ninja on the testbeds. Just FYI. In general Ninja seems to be faster although we are still working through build timings etc.

```
ninja: warning: multiple rules generate packages/muelu/doc/Tutorial/src/laplace2d.cpp. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate packages/muelu/example/ParameterList/ml_ParameterList.xml. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
```

**Comment by mayrmt** [comment] 2018-02-16 05:18
I get the same warnings. Haven't found the reason or a solution, yet.

**Comment by bartlettroscoe** [comment] 2018-02-16 15:03
This is shown to cause non-determinate build errors with the ATDM build of Trilinos as shown, for example, here:

* https://testing-vm.sandia.gov/cdash/viewBuildError.php?buildid=3302028

I will take a look.  These are usually pretty easy to fix.

**Comment by aprokop** [comment] 2018-02-16 15:32
I remember @nschloe submitted something similar a long time ago, but I can no longer find it. The problem is it's hard to figure out what leads to duplicate rules.

**Comment by nschloe** [comment] 2018-02-16 15:44
@aprokop You probably mean https://github.com/trilinos/Trilinos/issues/25.

**Comment by bartlettroscoe** [comment] 2018-02-16 15:47
If found the problems.  The problem is the misunderstanding about the usage of `TRIBITS_COPY_FILES_TO_BINARY_DIR()`. If you just run:

```
$ cd Trilinos/
$ find packages/muelu/ -name CMakeLists.txt -exec grep -nH ml_ParameterList.xml {} \;
$ find packages/muelu/ -name CMakeLists.txt -exec grep -nH laplace2d.cpp {} \
```

The problem is the misunderstanding about the arguments passed to `TRIBITS_COPY_FILES_TO_BINARY_DIR()` as documented at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-copy-files-to-binary-dir

I am not sure how to fix these because I don't understand what these are doing and why.    for example, one of the lines I took out was:

```
diff --git a/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt b/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeL
index b5dadb6..ca8348a 100644
--- a/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt
+++ b/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt
@@ -5,8 +5,6 @@
 # FILE TO FORCE THE RECONFIGURE ON OTHER PEOPLE'S BUILDS.
 FILE(GLOB xmlFiles RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.xml)
 
-LIST(APPEND xmlFiles "../../../../example/ParameterList/ml_ParameterList.xml")
-
 TRIBITS_COPY_FILES_TO_BINARY_DIR(ParameterList_MLParameterListInterpreter_cp
   SOURCE_FILES ${xmlFiles}
   )
```

That command is just copying the file `ml_ParameterList.xml` into the directory:

```
${CMAKE_CURRENT_BINARY_DIR}/../../../../example/ParameterList/ml_ParameterList.xml
```
which is the same as:

```
${Trilinos_BINARY_DIR}/example/ParameterList/ml_ParameterList.xml
```

What that command is  **NOT** doing is copying that file into:

```
${Trilinos_BINARY_DIR}/test/unit_tests/ParameterList/MLParameterListInterpreter/ml_ParameterList.xml
```

The commit that added this was:

```
commit fae650dc412d8e2c886a1c5a1cf3c897f7ded92f
Author: Jeremie Gaidamour <jngaida@sandia.gov>
Date:   Fri Oct 12 10:11:47 2012 -0600

    MueLu: added unit tests to MLParameterListInterpreter
    disabled by default

diff --git a/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt b/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeL
index ca8348a..f669335 100644
--- a/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt
+++ b/packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt
@@ -5,6 +5,8 @@
 # FILE TO FORCE THE RECONFIGURE ON OTHER PEOPLE'S BUILDS.
 FILE(GLOB xmlFiles RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.xml)
 
+LIST(APPEND xmlFiles "../../../../example/ParameterList/ml_ParameterList.xml")
+
 TRIBITS_COPY_FILES_TO_BINARY_DIR(ParameterList_MLParameterListInterpreter_cp
   SOURCE_FILES ${xmlFiles}
-  )
+  ) 
```

How did this work?

The logic around `laplace2d.cpp` is a little strange as well.  I has to do with a duplicate copy of that file for a tutorial.  I can just remove it for now and let someone else fix it.

**Comment by bartlettroscoe** [comment] 2018-02-16 15:52
I am issuing a PR to fix this now.

**Comment by bartlettroscoe** [comment] 2018-02-16 16:05
I issued PR #2246.  Take a careful look at the copy of the file `ml_ParameterList.xml` that I took out.  It just does not make sense to me.  And look at the documentation:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-copy-files-to-binary-dir

and carefully run the build target for the file copy and carefully see what it copies and where (i.e. using `make VERBOSE=1 <copy_target_name>`).

Let me know if you have questions.

**Comment by bartlettroscoe** [comment] 2018-02-20 23:50
Anyone watching this issue willing to review the PR #2246?  The auto testing passed and it is ready to merge.

**Comment by bartlettroscoe** [comment] 2018-02-21 15:09
I pushed the PR #2246 branch with the checkin-test-sems.sh script so this issue should be resolved.  I also build MueLu completely from scratch and the test suite passed.  The only thing that I am not sure about is the generation of the tutorial which is not part of the test suite.  But that should be okay (and if not would be easy to fix).

Someone can confirm but otherwise I think this can be closed.

**Comment by mayrmt** [comment] 2018-02-21 15:35
I looked at the MueLu tutorial. The PDF builds and looks ok.

**Comment by mayrmt** [comment] 2018-02-21 16:15
I looked at the tutorial. The pdf compiles and looks good.

**Comment by jhux2** [comment] 2018-02-22 16:58
@nmhamster Can this issue be closed?

**Comment by bartlettroscoe** [comment] 2018-03-01 14:00
I can verify that this issue has been resolved (by me) and I verified that we non longer see these warnings and we have not seen any build problems with MueLu.

Therefore, I am closing as complete.

**Closed by bartlettroscoe** 2018-03-01 14:00 UTC
Labels: ATDM, MueLu, build
