### ISSUE TITLE
Teuchos LAPACK test missing #include <vector>

### ISSUE THREAD

**Issue by ndaman** [trilinos/Trilinos#2031] opened 2017-11-29 20:38 UTC
I am building Trilinos for Peridigm following instructions here: https://peridigm.sandia.gov/content/trilinos

The build fails when compiling Trilinos/packages/teuchos/numerics/test/LAPACK/cxx_main.cpp ('vector' is not a member of 'std').

It appears that somewhere in the include chain, this file is missing an #include <vector> line. It appears to be fixed by adding that include to the cxx_main.cpp file, but I am not sure if it is mean to be included elsewhere so that would not be necessary.

**Comment by mhoemmen** [comment] 2017-12-04 05:23
@ndaman What compiler are you using?  This may be a duplicate of #2041.

**Comment by nmhamster** [comment] 2017-12-04 14:57
@mhoemmen - I think master is only up to November 28th so the change has not made it through.

**Comment by ndaman** [comment] 2017-12-04 15:30
@mhoemmen I am building using gcc 7.2.1 (from a Fedora VM, if that changes anything).

**Comment by mhoemmen** [comment] 2017-12-04 16:46
@ndaman Could you try the develop branch of Trilinos?  That might fix the issue for you.

**Comment by ndaman** [comment] 2017-12-04 19:23
@mhoemmen confirmed that the develop branch fixed the problem.

I now get an error while "Linking CXX executable ThyraEpetraAdapters_TestThyraDebugHang.exe", is it best to open a new issue for that?

**Comment by mhoemmen** [comment] 2017-12-04 20:34
@ndaman Please file a new issue for that and add me to the CC list with an at-mention; thanks!

**Comment by mhoemmen** [comment] 2017-12-04 20:35
@ndaman Thanks!  I will close this issue, then, in favor of #2041.

**Closed by mhoemmen** 2017-12-04 20:35 UTC
Labels: build, Teuchos
