### ISSUE TITLE
Ifpack2: converting Tpetra matrices to Hypre matrices

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#9154] opened 2021-05-19 16:21 UTC
## Question
@trilinos/ifpack2

@keitat forwarded a user's comment about the speed of converting Tpetra matrices to Hypre matrices, specifically that the conversion seems to be slow.

"We have been using the IfPack2 wrapper for Hypre which works pretty well using Serial. 
I recently transfered the IfPack2 code into our ... project to work on some aspects, in particular the GPU utilization which was not working properly through IfPack2. I now have the code running on the GPU but it seems very slow in the initialization of the matrix.

[The] reference to the function `CopyTpetraToHypre` which seems to be the problem. It is copying the matrix row by row and seems to trigger memory allocation at each iteration which ends up with very poor performances. 
I didnt see a dedicated function in Hypre to use matrices from Tpetra::CRSMatrix aka Kokkos."

**Comment by csiefer2** [comment] 2021-05-19 18:57
Tpetra and Hypre have different matrix formats (unless you're on 1 MPI rank).  Copying is basically inevitable.

**Comment by jhux2** [comment] 2021-05-19 18:59
@keitat The interface in question was developed for research purposes.  If you have suggestions on how to improve it, we would welcome the contribution!

**Comment by jhux2** [comment] 2021-05-19 19:02
@JulienLoiseau

**Comment by JulienLoiseau** [comment] 2021-05-20 02:52
@jhux2 @csiefer2 
Indeed some copies are needed between the Tpetra format and the Hypre one for the matrix. 
The problem I have is that the current copy in `CopyTpetraToHypre` is doing so row by row: 

```
  std::vector<GO> new_indices(Matrix->getNodeMaxNumRowEntries());  
  for(LO i = 0; i < (LO) Matrix->getNodeNumRows(); i++){
    Teuchos::ArrayView<const SC> values;
    Teuchos::ArrayView<const LO> indices;
    Matrix->getLocalRowView(i, indices, values);
    for(LO j = 0; j < (LO)indices.size(); j++){
      new_indices[j] = GloballyContiguousColMap_->getGlobalElement(indices[j]);
    }
    GO GlobalRow[1];
    GO numEntries = (GO) indices.size();
    GlobalRow[0] = GloballyContiguousRowMap_->getGlobalElement(i);    
    AMANZI_CHK_ERR(HYPRE_IJMatrixSetValues(HypreA_, 1, &numEntries, GlobalRow, new_indices.data(), values.getRawPtr()));
  }
```

Which generate multiple useless computations/copies that could be avoided if the Matrix was transfered at once (the local matrix on each rank using the global indices)

I did a version that is working on my side, reducing the transfer time for a 30^3 mesh from 20s to less than a second. 
This is still a preliminary version, I am now looking to access directly to the device pointers of the Tpetra::CRSMatrix with Kokkos to avoid the copy CPU->GPU in Hypre (that seems to take directly device pointers) and then the computation on the GPU of the structure. But this is not really needed since for now Tpetra only supports UVM. 

This faster version: 
```
  // Compute the number of columns per rows for each row 
  std::vector<LO> colsperrow(Matrix->getNodeNumRows()); 
  for(LO i = 0; i < (LO) Matrix->getNodeNumRows(); i++){
    colsperrow[i] = Matrix->getNumEntriesInLocalRow(i);
  }

  auto nrows = Matrix->getNodeNumRows(); 
  auto rowindices = GloballyContiguousRowMap_->getMyGlobalIndices();
  auto values = Matrix->getLocalValuesView(); 
  // This function might become deprecated 
  // but it seems to be possible to access the raw structure in Tpetra::CRSMatrix::CRSGraph
  auto colindices = Matrix->getCrsGraph()->getNodePackedIndices();

  HYPRE_IJMatrixSetValues(HypreA_,nrows,colsperrow.data(),rowindices.data(),colindices.get(),values.data()));
```

**Comment by csiefer2** [comment] 2021-05-20 03:12
I'm not really understand what you're trying to show.  Where is the redundant computation?   I find it hard to believe that avoiding calls to getLocalRowView (which does nothing besides pointer arithmetic) decreases costs by 20x.

**Comment by JulienLoiseau** [comment] 2021-05-20 12:31
@csiefer2 
The bottleneck I had by using the IfPack2 interface was in the `CopyTpetraToHypre`. 
The multiple calls to `HYPRE_IJMatrixSetValues` in the for loop (first version) caused a problem. Nothing to do with `getLocalRowView` in particular.
Reducing this call to  `HYPRE_IJMatrixSetValues` to one solved this problem for me by a factor of 20.

**Comment by csiefer2** [comment] 2021-05-20 15:12
@JulienLoiseau Ah, so the problem is that Hypre doesn't like multiple calls to HYPRE_IJMatrixSetValues.  Got it.

Feel free to put up a PR if you want that code in Ifpack2.  It looked correct to me.

**Comment by JulienLoiseau** [comment] 2021-05-27 21:17
@csiefer2 
Before submitting a PR I am working on a version capable to pass the device pointers directly to Hypre. 

So far I have: 

```

  LO nrows = Matrix->getNodeNumRows(); 

  // Compute the cols per rows directly on the device 
  Kokkos::View<LO*,Kokkos:: DefaultExecutionSpace> colsperrow("ColsPerRow",nrows); 
  auto rowPtrs = Matrix->getCrsGraph()->getLocalGraph().row_map; 
  Kokkos::parallel_for(nrows,
    KOKKOS_LAMBDA(const int i){
      colsperrow(i) = rowPtrs[i+1]-rowPtrs[i]; 
  }); 

  auto rowindices = Matrix->getRowMap()->getMyGlobalIndices();

  Kokkos::View<SC*,Kokkos:: DefaultExecutionSpace> 
    values = Matrix->getLocalValuesView(); 
  // Columns indices are stored on device 
  Kokkos::View<LO*,Kokkos:: DefaultExecutionSpace> 
    colindices = Matrix->getCrsGraph()->getLocalGraph().entries; 

  AMANZI_CHK_ERR(HYPRE_IJMatrixSetValues(HypreA_,nrows,colsperrow.data(),
                                        rowindices.data(),colindices.data(),values.data()));
```

The only array that I cannot find a way to access directly on the device is: 
```
  auto rowindices = Matrix->getRowMap()->getMyGlobalIndices();
```

In this case `auto` is a `Kokkos::View` in the `HostSpace`: https://docs.trilinos.org/dev/packages/tpetra/doc/html/classTpetra_1_1Map.html#a996d3fc75f04dd447230f08d1d44b088
In the `tpetra` code it returns `lgMapHost_` but we really want `lgMap_`. 

Do you know a way to access the Device View? 

Of course for this is useless since `Trilinos` and `Tpetra` are only working using `UVM` but they should support `no-UVM` soon (mid june?). Might as well be ready. 

Thank you for your time, 
Julien

**Comment by csiefer2** [comment] 2021-06-01 22:43
Do a A->getLocalMatrix() and get the local map from there.

**Comment by JulienLoiseau** [comment] 2021-08-31 20:36
This latest version works with multiple MPI ranks: 
```
//==============================================================================
template<class MatrixType>
int Hypre<MatrixType>::CopyTpetraToHypre(){
  using LO = local_ordinal_type;
  using GO = global_ordinal_type;
  using SC = scalar_type;

  Teuchos::RCP<const crs_matrix_type> Matrix = Teuchos::rcp_dynamic_cast<const crs_matrix_type>(A_);
  if(Matrix.is_null()) 
    throw std::runtime_error("Hypre<MatrixType>: Unsupported matrix configuration: Tpetra::CrsMatrix required");

  LO nrows = Matrix->getNodeNumRows();
  Kokkos::View<LO*,Kokkos::DefaultExecutionSpace> colsperrow("ColsPerRow",nrows);
  auto rowPtrs = Matrix->getCrsGraph()->getLocalGraph().row_map;
  Kokkos::parallel_for(nrows,
    KOKKOS_LAMBDA(const int i){
      colsperrow(i) = rowPtrs[i+1]-rowPtrs[i];
  });
  auto rowindices = Matrix->getRowMap()->getMyGlobalIndices();
  auto values = Matrix->getLocalValuesView();
  auto colindices = Matrix->getCrsGraph()->getLocalGraph().entries;
  Kokkos::View<GO*,Kokkos::DefaultExecutionSpace>
    new_colindices("nci",colindices.size());
  for(int i = 0 ; i < colindices.size(); ++i){
    new_colindices[i] = GloballyContiguousColMap_->getGlobalElement(colindices[i]);
  }

  IFPACK2_CHK_ERR(HYPRE_IJMatrixSetValues(HypreA_,nrows,colsperrow.data(),
    rowindices.data(),new_colindices.data(),values.data()));
  IFPACK2_CHK_ERR(HYPRE_IJMatrixAssemble(HypreA_));
  IFPACK2_CHK_ERR(HYPRE_IJMatrixGetObject(HypreA_, (void**)&ParMatrix_));
  if (Dump_)
    IFPACK2_CHK_ERR(HYPRE_ParCSRMatrixPrint(ParMatrix_,"A.mat"));
  return 0;
} //CopyTpetraToHypre()
```

The function CopyTpetraToHypre also needs to be moved from private to public scope to call the `Kokkos::parallel_for` on device.

I will provide an MR if this seems ok and we can close this issue.

**Comment by cgcgcg** [comment] 2021-08-31 23:35
Yes, please create a PR. Not sure I understand the need to move from private to public, but maybe that will become clearer. Also, since this code isn't nightly tested, please make sure that you run it on a couple of problems.

**Closed** 2022-10-05 12:44 UTC
Labels: type: question, pkg: Ifpack2, client: xSDK, MARKED_FOR_CLOSURE, CLOSED_DUE_TO_INACTIVITY
