### ISSUE TITLE
Percept: build issue

### ISSUE THREAD

**Issue by Tread84** [trilinos/Trilinos#7833] opened 2020-08-12 20:43 UTC
I was installing Trilinos on Ubuntu 18.04.4. The first time it stop doing the panzer package installation, which I was able to correct by reducing the number of processors handling the installation. However, when I got to about 83% of the make install process, I received the following error:

[ 83%] Linking CXX executable perceptX
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::ROTG(float*, float*, float*, float*) const':
Teuchos_BLAS.cpp:(.text+0xd): undefined reference to `srotg_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::TRMV(Teuchos::EUplo, Teuchos::ETransp, Teuchos::EDiag, int const&, float const*, int const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x3f7): undefined reference to `strmv_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::GEMM(Teuchos::ETransp, Teuchos::ETransp, int const&, int const&, int const&, float const&, float const*, int const&, float const*, int const&, float const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x46a): undefined reference to `sgemm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::SYMM(Teuchos::ESide, Teuchos::EUplo, int const&, int const&, float const&, float const*, int const&, float const*, int const&, float const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x4f7): undefined reference to `ssymm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::SYRK(Teuchos::EUplo, Teuchos::ETransp, int const&, int const&, float const&, float const*, int const&, float const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x553): undefined reference to `ssyrk_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::HERK(Teuchos::EUplo, Teuchos::ETransp, int const&, int const&, float const&, float const*, int const&, float const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x5b3): undefined reference to `ssyrk_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::TRMM(Teuchos::ESide, Teuchos::EUplo, Teuchos::ETransp, Teuchos::EDiag, int const&, int const&, float const&, float const*, int const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x635): undefined reference to `strmm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, float>::TRSM(Teuchos::ESide, Teuchos::EUplo, Teuchos::ETransp, Teuchos::EDiag, int const&, int const&, float const&, float const*, int const&, float*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x6b5): undefined reference to `strsm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::ROTG(double*, double*, double*, double*) const':
Teuchos_BLAS.cpp:(.text+0x6cd): undefined reference to `drotg_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::TRMV(Teuchos::EUplo, Teuchos::ETransp, Teuchos::EDiag, int const&, double const*, int const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x8a7): undefined reference to `dtrmv_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::GEMM(Teuchos::ETransp, Teuchos::ETransp, int const&, int const&, int const&, double const&, double const*, int const&, double const*, int const&, double const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x91a): undefined reference to `dgemm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::SYMM(Teuchos::ESide, Teuchos::EUplo, int const&, int const&, double const&, double const*, int const&, double const*, int const&, double const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0x9a7): undefined reference to `dsymm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::SYRK(Teuchos::EUplo, Teuchos::ETransp, int const&, int const&, double const&, double const*, int const&, double const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0xa03): undefined reference to `dsyrk_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::HERK(Teuchos::EUplo, Teuchos::ETransp, int const&, int const&, double const&, double const*, int const&, double const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0xa63): undefined reference to `dsyrk_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::TRMM(Teuchos::ESide, Teuchos::EUplo, Teuchos::ETransp, Teuchos::EDiag, int const&, int const&, double const&, double const*, int const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0xae5): undefined reference to `dtrmm_'
../teuchos/numerics/src/libteuchosnumerics.a(Teuchos_BLAS.cpp.o): In function `Teuchos::BLAS<int, double>::TRSM(Teuchos::ESide, Teuchos::EUplo, Teuchos::ETransp, Teuchos::EDiag, int const&, int const&, double const&, double const*, int const&, double*, int const&) const':
Teuchos_BLAS.cpp:(.text+0xb65): undefined reference to `dtrsm_'
/usr/local/lib/libblas.a(sgemv.c.o): In function `sgemv_':
sgemv.c:(.text+0x11f): undefined reference to `input_error'
/usr/local/lib/libblas.a(sger.c.o): In function `sger_':
sger.c:(.text+0xbf): undefined reference to `input_error'
/usr/local/lib/libblas.a(dgemv.c.o): In function `dgemv_':
dgemv.c:(.text+0x11f): undefined reference to `input_error'
/usr/local/lib/libblas.a(dger.c.o): In function `dger_':
dger.c:(.text+0xbf): undefined reference to `input_error'
collect2: error: ld returned 1 exit status
packages/percept/CMakeFiles/perceptX.dir/build.make:168: recipe for target 'packages/percept/perceptX' failed
make[2]: *** [packages/percept/perceptX] Error 1
CMakeFiles/Makefile2:17947: recipe for target 'packages/percept/CMakeFiles/perceptX.dir/all' failed
make[1]: *** [packages/percept/CMakeFiles/perceptX.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2

Tried fixing the issue the same way that I fixed the panzer error, but unforturnately that did not work. I can install without the percept package, as I am fairly sure that it is not required to use Albany and Deal.ii. Any help fixing this problem would be greatly appreciated.

**Comment by jhux2** [comment] 2020-08-12 23:55
@trilinos/percept

**Comment by jhux2** [comment] 2020-08-18 16:50
Closing as a duplicate of #7846.

**Closed by jhux2** 2020-08-18 16:50 UTC
Labels: pkg: Percept, type: bug
