### ISSUE TITLE
Kokkos: invalid use of incomplete type build error on CEE linux

### ISSUE THREAD

**Issue by dicengine** [trilinos/Trilinos#92] opened 2016-01-22 12:52 UTC
This has been an issue for the last couple days with building VOTD Trilinos. Here are the configure results, build error, and cmake configuration files.

[make.txt](https://github.com/trilinos/Trilinos/files/100780/make.txt)
[cmake.txt](https://github.com/trilinos/Trilinos/files/100781/cmake.txt)
[do-cmake.txt](https://github.com/trilinos/Trilinos/files/100782/do-cmake.txt)

**Comment by crtrott** [comment] 2016-01-22 16:39
I am looking into it, can you do a make with VERBOSE=1 to get the actual build line. One way how you could get this behavior is if the -fopenmp flag is not set, which in a normal Trilinos build should automatically happen if you enable OpenMP in Trilinos (as you do).

**Comment by crtrott** [comment] 2016-01-22 16:42
Never mind, I just reproduced the behavior with your input script. Pretty curious that this could happen at all, since the nightly tests actually pass in all combination (Pthreads, Pthreads+OpenMP, OpenMP etc).

**Comment by dicengine** [comment] 2016-01-22 16:43
Here's the verbose output if it's any help still. Looks like -fopenmp is set.
[make.txt](https://github.com/trilinos/Trilinos/files/101130/make.txt)

**Comment by crtrott** [comment] 2016-01-22 17:22
For now here is a workaround. Add the following line to the configure and everything should work. It will take a few days to get a proper fix into Trilinos:
-D Kokkos_ENABLE_Pthread=OFF \

Sorry for the inconvenience. I leave the ticket open until it is fixed and will add an accompanying ticket on the kokkos github site.

**Comment by crtrott** [comment] 2016-01-22 18:42
I got a fix on Kokkos develop branch. Just need to get a merge into Trilinos done (which will take a bit).

**Comment by crtrott** [comment] 2016-01-23 02:15
Pushed to master and Trilinos closing the issue

**Closed by crtrott** 2016-01-23 02:15 UTC
Labels: bug, Kokkos

**Comment by dicengine** [comment] 2016-01-23 02:18
Thanks Christian! -DT

On Jan 22, 2016, at 7:15 PM, Christian Trott <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #92<https://github.com/trilinos/Trilinos/issues/92>.
