### ISSUE TITLE
TeuchosCore_TypeConversions_UnitTest_MPI_1 Fails on POWER8 RHEL7.3 with CUDA 8.0.44 and GCC 5.4.0

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#704] opened 2016-10-13 18:22 UTC
I am running on POWER8 with GCC 5.4.0 and CUDA 8.0.44 with OpenMPI 1.10.4. A number of tests are failing including TeuchosCore_TypeConversions_UnitTest_MPI_1.

```
$ ctest -V -R TeuchosCore_TypeConversions_UnitTest_MPI_1
```

```
UpdateCTestConfiguration  from :/ascldap/users/sdhammo/git/trilinos-github-repo/build-power8-rhel73-no-cuda/DartConfiguration.tcl
Parse Config file:/ascldap/users/sdhammo/git/trilinos-github-repo/build-power8-rhel73-no-cuda/DartConfiguration.tcl
 Add coverage exclude regular expressions.
SetCTestConfiguration:CMakeCommand:/home/projects/pwr8-rhel73-lsf/cmake/3.6.2/bin/cmake
UpdateCTestConfiguration  from :/ascldap/users/sdhammo/git/trilinos-github-repo/build-power8-rhel73-no-cuda/DartConfiguration.tcl
Parse Config file:/ascldap/users/sdhammo/git/trilinos-github-repo/build-power8-rhel73-no-cuda/DartConfiguration.tcl
Test project /ascldap/users/sdhammo/git/trilinos-github-repo/build-power8-rhel73-no-cuda
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 66
    Start 66: TeuchosCore_TypeConversions_UnitTest_MPI_1

66: Test command: /ascldap/users/projects/pwr8-rhel73-lsf/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44/bin/mpiexec "-np" "1" "/ascldap/users/sdhammo/git/trilinos-github-repo/build-power8-rhel73-no-cuda/packages/teuchos/core/test/TypeConversions/TeuchosCore_TypeConversions_UnitTest.exe"
66: Test timeout computed to be: 1500
66: Teuchos::GlobalMPISession::GlobalMPISession(): started processor with name white28 and rank 0!
66:
66: ***
66: *** Unit test suite ...
66: ***
66:
66:
66: Sorting tests by group name then by the order they were added ... (time = 2.69e-05)
66:
66: Running unit tests ...
66:
66: 0. asSafe_realToReal_UnitTest ... [Passed] (0.000292 sec)
66: 1. asSafe_stringToReal_UnitTest ...
66:  Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
66:  valF = -3.40282347e+38 == -3.40282347e+38 : passed
66:  Test that code {valF = as<float> (os.str ());} does not throw : passes
66:  valF = -3.40282347e+38 == -3.40282347e+38 : passed
66:  Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
66:  valF = 3.40282347e+38 == 3.40282347e+38 : passed
66:  Test that code {valF = as<float> (os.str ());} does not throw : passes
66:  valF = 3.40282347e+38 == 3.40282347e+38 : passed
66:  Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
66:  valF = -1.00000000e+00 == -1.00000000e+00 : passed
66:  Test that code {valF = as<float> (os.str ());} does not throw : passes
66:  valF = -1.00000000e+00 == -1.00000000e+00 : passed
66:  Test that code {valF = asSafe<float> (os.str ());} does not throw : passes
66:  valF = -1.00000000e+00 == -1.00000000e+00 : passed
66:  Test that code {valF = as<float> (os.str ());} does not throw : passes
66:  valF = -1.00000000e+00 == -1.00000000e+00 : passed
66:  Test that code {valF = asSafe<float> (os.str ());} throws std::range_error: passed
66:
66:  Exception message for expected exception:
66:
66:   /ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/core/src/Teuchos_as.hpp:558:
66:
66:   Throw number = 1
66:
66:   Throw test that evaluated to true: errno == ERANGE && (val != 0)
66:
66:   Teuchos::ValueTypeConversionTraits<float, std::string>::convert: The value in the given string "-1.79769313e+308" overflows float.
66:
66:  Test that code {valF = asSafe<float> (os.str ());} throws std::range_error: passed
66:
66:  Exception message for expected exception:
66:
66:   /ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/core/src/Teuchos_as.hpp:558:
66:
66:   Throw number = 2
66:
66:   Throw test that evaluated to true: errno == ERANGE && (val != 0)
66:
66:   Teuchos::ValueTypeConversionTraits<float, std::string>::convert: The value in the given string "1.79769313e+308" overflows float.
66:
66:  Test that code {valD = asSafe<double> (os.str ());} does not throw : passed
66:  valD = -1.79769313486231571e+308 == -1.79769313486231571e+308 : passed
66:  Test that code {valD = as<double> (os.str ());} does not throw : passed
66:  valD = -1.79769313486231571e+308 == -1.79769313486231571e+308 : passed
66:  Test that code {valD = asSafe<double> (os.str ());} does not throw : passed
66:  valD = 1.79769313486231571e+308 == 1.79769313486231571e+308 : passed
66:  Test that code {valD = as<double> (os.str ());} does not throw : passed
66:  valD = 1.79769313486231571e+308 == 1.79769313486231571e+308 : passed
66:  Test that code {valD = asSafe<double> (os.str ());} does not throw : passed
66:  valD = -1.00000000000000000e+00 == -1.00000000000000000e+00 : passed
66:  Test that code {valD = as<double> (os.str ());} does not throw : passed
66:  valD = -1.00000000000000000e+00 == -1.00000000000000000e+00 : passed
66:  Test that code {valD = asSafe<double> (os.str ());} throws std::range_error: failed (code did not throw an exception at all)
66:  Test that code {valD = asSafe<double> (os.str ());} throws std::range_error: failed (code did not throw an exception at all)
66:  Test that code {valLD = asSafe<long double> (os.str ());} does not throw : passed
66:  valLD = -1.79769e+308 == -1.79769e+308 : passed
66:  Test that code {valLD = as<long double> (os.str ());} does not throw : passed
66:  valLD = -1.79769e+308 == -1.79769e+308 : passed
66:  Test that code {valLD = asSafe<long double> (os.str ());} does not throw : passed
66:  valLD = 1.79769e+308 == 1.79769e+308 : passed
66:  Test that code {valLD = as<long double> (os.str ());} does not throw : passed
66:  valLD = 1.79769e+308 == 1.79769e+308 : passed
66:  Test that code {valLD = asSafe<long double> (os.str ());} does not throw : passed
66:  valLD = -1 == -1 : passed
66:  Test that code {valLD = as<long double> (os.str ());} does not throw : passed
66:  valLD = -1 == -1 : passed
66:  [FAILED]  (0.000326 sec) asSafe_stringToReal_UnitTest
66:  Location: /ascldap/users/sdhammo/git/trilinos-github-repo/packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp:274
66:
66: 2. asSafe_stringToIntPositiveOverflow_UnitTest ... [Passed] (2.79e-05 sec)
66: 3. asSafe_stringToIntNegativeOverflow_UnitTest ... [Passed] (2.29e-05 sec)
66: 4. asSafe_double_int_realToSignedIntTypeOverflow_UnitTest ... [Passed] (3.1e-05 sec)
66: 5. asSafe_double_long_realToSignedIntTypeOverflow_UnitTest ... [Passed] (0 sec)
66: 6. asSafe_double_long_long_type_realToSignedIntTypeOverflow_UnitTest ... [Passed] (0 sec)
66: 7. asSafe_double_short_realToSignedIntTypeOverflow_UnitTest ... [Passed] (3.1e-05 sec)
66: 8. asSafe_double_unsigned_int_type_realToUnsignedIntTypeOverflow_UnitTest ... [Passed] (0.00011 sec)
66: 9. asSafe_double_unsigned_long_long_type_realToUnsignedIntTypeOverflow_UnitTest ... [Passed] (9.2e-05 sec)
66: 10. asSafe_double_unsigned_long_type_realToUnsignedIntTypeOverflow_UnitTest ... [Passed] (8.61e-05 sec)
66: 11. asSafe_double_unsigned_short_type_realToSignedIntTypeOverflow_UnitTest ... [Passed] (2.91e-05 sec)
66: 12. asSafe_float_int_realToSignedIntTypeOverflow_UnitTest ... [Passed] (0 sec)
66: 13. asSafe_float_long_realToSignedIntTypeOverflow_UnitTest ... [Passed] (0 sec)
66: 14. asSafe_float_long_long_type_realToSignedIntTypeOverflow_UnitTest ... [Passed] (9.54e-07 sec)
66: 15. asSafe_float_short_realToSignedIntTypeOverflow_UnitTest ... [Passed] (2.81e-05 sec)
66: 16. asSafe_float_unsigned_int_type_realToUnsignedIntTypeOverflow_UnitTest ... [Passed] (8.39e-05 sec)
66: 17. asSafe_float_unsigned_long_long_type_realToUnsignedIntTypeOverflow_UnitTest ... [Passed] (8.42e-05 sec)
66: 18. asSafe_float_unsigned_long_type_realToUnsignedIntTypeOverflow_UnitTest ... [Passed] (8.2e-05 sec)
66: 19. asSafe_float_unsigned_short_type_realToSignedIntTypeOverflow_UnitTest ... [Passed] (2.69e-05 sec)
66: 20. asSafe_int_stringToIntegerPositive_UnitTest ... [Passed] (5.01e-06 sec)
66: 21. asSafe_int_stringToIntegerShouldThrow_UnitTest ... [Passed] (4.1e-05 sec)
66: 22. asSafe_int_stringToIntegerNegative_UnitTest ... [Passed] (5.96e-06 sec)
66: 23. asSafe_int_unsigned_int_type_negativeSignedIntToUnsignedInt_UnitTest ... [Passed] (3.89e-05 sec)
66: 24. asSafe_long_stringToIntegerPositive_UnitTest ... [Passed] (5.01e-06 sec)
66: 25. asSafe_long_stringToIntegerShouldThrow_UnitTest ... [Passed] (2e-05 sec)
66: 26. asSafe_long_stringToIntegerNegative_UnitTest ... [Passed] (4.05e-06 sec)
66: 27. asSafe_long_long_type_stringToIntegerPositive_UnitTest ... [Passed] (1e-05 sec)
66: 28. asSafe_long_long_type_stringToIntegerShouldThrow_UnitTest ... [Passed] (2.12e-05 sec)
66: 29. asSafe_long_long_type_stringToIntegerNegative_UnitTest ... [Passed] (5.01e-06 sec)
66: 30. asSafe_long_long_type_unsigned_long_long_type_negativeSignedIntToUnsignedInt_UnitTest ... [Passed] (4.2e-05 sec)
66: 31. asSafe_long_unsigned_long_type_negativeSignedIntToUnsignedInt_UnitTest ... [Passed] (3.7e-05 sec)
66:
66: *** RealType = double, UnsignedIntType = unsigned int, maxVal = 1.79769e+308, maxUnsignedIntVal = 4294967295, asSafe (maxVal) = (asSafe threw an exception)
66:
66: *** RealType = double, UnsignedIntType = unsigned long long, maxVal = 1.79769e+308, maxUnsignedIntVal = 18446744073709551615, asSafe (maxVal) = (asSafe threw an exception)
66:
66: *** RealType = double, UnsignedIntType = unsigned long int, maxVal = 1.79769e+308, maxUnsignedIntVal = 18446744073709551615, asSafe (maxVal) = (asSafe threw an exception)
66:
66: *** RealType = float, UnsignedIntType = unsigned int, maxVal = 3.40282e+38, maxUnsignedIntVal = 4294967295, asSafe (maxVal) = (asSafe threw an exception)
66:
66: *** RealType = float, UnsignedIntType = unsigned long long, maxVal = 3.40282e+38, maxUnsignedIntVal = 18446744073709551615, asSafe (maxVal) = (asSafe threw an exception)
66:
66: *** RealType = float, UnsignedIntType = unsigned long int, maxVal = 3.40282e+38, maxUnsignedIntVal = 18446744073709551615, asSafe (maxVal) = (asSafe threw an exception)
66: 32. asSafe_short_stringToIntegerPositive_UnitTest ... [Passed] (1.31e-05 sec)
66: 33. asSafe_short_stringToIntegerShouldThrow_UnitTest ... [Passed] (5.29e-05 sec)
66: 34. asSafe_short_stringToIntegerNegative_UnitTest ... [Passed] (8.82e-06 sec)
66: 35. asSafe_short_unsigned_short_type_negativeSignedIntToUnsignedInt_UnitTest ... [Passed] (5.6e-05 sec)
66: 36. asSafe_unsigned_int_type_stringToIntegerPositive_UnitTest ... [Passed] (1.12e-05 sec)
66: 37. asSafe_unsigned_int_type_stringToIntegerShouldThrow_UnitTest ... [Passed] (5.39e-05 sec)
66: 38. asSafe_unsigned_long_long_type_stringToIntegerPositive_UnitTest ... [Passed] (1.1e-05 sec)
66: 39. asSafe_unsigned_long_long_type_stringToIntegerShouldThrow_UnitTest ... [Passed] (3.19e-05 sec)
66: 40. asSafe_unsigned_long_type_stringToIntegerPositive_UnitTest ... [Passed] (7.87e-06 sec)
66: 41. asSafe_unsigned_long_type_stringToIntegerShouldThrow_UnitTest ... [Passed] (2.98e-05 sec)
66: 42. asSafe_unsigned_short_type_stringToIntegerPositive_UnitTest ... [Passed] (8.11e-06 sec)
66: 43. asSafe_unsigned_short_type_stringToIntegerShouldThrow_UnitTest ... [Passed] (5.29e-05 sec)
66: 44. as_int_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.22e-05 sec)
66: 45. as_int_int_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.41e-05 sec)
66: 46. as_int_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.39e-05 sec)
66: 47. as_int_long_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 48. as_int_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.5e-05 sec)
66: 49. as_int_long_long_type_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.19e-05 sec)
66: 50. as_int_short_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 51. as_int_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 52. as_int_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (2.41e-05 sec)
66: 53. as_int_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (2.1e-05 sec)
66: 54. as_int_unsigned_short_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 55. as_long_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (4.98e-05 sec)
66: 56. as_long_int_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.41e-05 sec)
66: 57. as_long_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.19e-05 sec)
66: 58. as_long_long_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.41e-05 sec)
66: 59. as_long_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.29e-05 sec)
66: 60. as_long_long_long_type_negativeSignedIntToSignedInt_UnitTest ... [Passed] (3.39e-05 sec)
66: 61. as_long_long_type_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (2.81e-05 sec)
66: 62. as_long_long_type_int_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 63. as_long_long_type_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 64. as_long_long_type_long_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 65. as_long_long_type_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 66. as_long_long_type_long_long_type_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 67. as_long_long_type_short_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.79e-05 sec)
66: 68. as_long_long_type_short_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 69. as_long_long_type_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 70. as_long_long_type_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 71. as_long_long_type_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 72. as_long_long_type_unsigned_short_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 73. as_long_short_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 74. as_long_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 75. as_long_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 76. as_long_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 77. as_long_unsigned_short_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 78. as_short_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 79. as_short_int_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 80. as_short_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.79e-05 sec)
66: 81. as_short_long_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 82. as_short_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 83. as_short_long_long_type_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 84. as_short_short_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.79e-05 sec)
66: 85. as_short_short_negativeSignedIntToSignedInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 86. as_short_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.79e-05 sec)
66: 87. as_short_unsigned_short_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 88. as_unsigned_int_type_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 89. as_unsigned_int_type_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 90. as_unsigned_int_type_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 91. as_unsigned_int_type_short_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 92. as_unsigned_int_type_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 93. as_unsigned_int_type_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.79e-05 sec)
66: 94. as_unsigned_int_type_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 95. as_unsigned_long_long_type_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 96. as_unsigned_long_long_type_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 97. as_unsigned_long_long_type_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 98. as_unsigned_long_long_type_short_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 99. as_unsigned_long_long_type_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (4.2e-05 sec)
66: 100. as_unsigned_long_long_type_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (2.88e-05 sec)
66: 101. as_unsigned_long_long_type_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 102. as_unsigned_long_long_type_unsigned_short_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 103. as_unsigned_long_type_int_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 104. as_unsigned_long_type_long_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 105. as_unsigned_long_type_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3e-05 sec)
66: 106. as_unsigned_long_type_short_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 107. as_unsigned_long_type_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3e-05 sec)
66: 108. as_unsigned_long_type_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.1e-05 sec)
66: 109. as_unsigned_long_type_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3.39e-05 sec)
66: 110. as_unsigned_short_type_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (3e-05 sec)
66: 111. as_unsigned_short_type_short_positiveFirstIntToSecondInt_UnitTest ... [Passed] (2.79e-05 sec)
66: 112. as_unsigned_short_type_unsigned_int_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.88e-05 sec)
66: 113. as_unsigned_short_type_unsigned_long_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.81e-05 sec)
66: 114. as_unsigned_short_type_unsigned_long_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.91e-05 sec)
66: 115. as_unsigned_short_type_unsigned_short_type_positiveFirstIntToSecondInt_UnitTest ... [Passed] (1.79e-05 sec)
66:
66: The following tests FAILED:
66:     1. asSafe_stringToReal_UnitTest ...
66:
66: Total Time: 0.00537 sec
66:
66: Summary: total = 116, run = 116, passed = 115, failed = 1
66:
66: End Result: TEST FAILED
66: -------------------------------------------------------
66: Primary job  terminated normally, but 1 process returned
66: a non-zero exit code.. Per user-direction, the job has been aborted.
66: -------------------------------------------------------
66: --------------------------------------------------------------------------
66: mpiexec detected that one or more processes exited with non-zero status, thus causing
66: the job to be terminated. The first process to do so was:
66:
66:   Process name: [[10953,1],0]
66:   Exit code:    1
66: --------------------------------------------------------------------------
1/1 Test #66: TeuchosCore_TypeConversions_UnitTest_MPI_1 ...***Failed  Required regular expression not found.Regex=[End Result: TEST PASSED
]  0.53 sec

0% tests passed, 1 tests failed out of 1

Label Time Summary:
Teuchos    =   0.53 sec (1 test)

Total Test time (real) =   1.22 sec

The following tests FAILED:
     66 - TeuchosCore_TypeConversions_UnitTest_MPI_1 (Failed)
Errors while running CTest
```

**Comment by bartlettroscoe** [comment] 2016-10-13 23:08
@nmhamster, I think this is basically a duplicate of #400 (with GCC 5.3.0) which appears to be a duplicate of #257 (with GCC 4.9).  Since this happens with multiple versions of GCC and CUDA, my guess is that this is non-IEEE floating-point behavior of the GCC compiler on this system or something that affects all of these compiler versions.

@mhoemmen, it looks like the `asSafe<double>(os.str ());` function is not throwing in this block of unit testing code:

* https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp#L411

for this compiler on this platform for some reason.  Strangely, the `asSafe<long double>(os.str ());` seems to throw just fine.  Looking at the implementation of the double conversion function at:

* https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/src/Teuchos_as.hpp#L632

it looks like this is just using the C99 function `strtod()`?  I wonder what would happen if we added direct conversion from std::string to double using the C++11 function `std::strtod()`?

This unit test depends on several things.  It depends on the behavior of std::ostringstream in writing the min value of `long double`.  It depends on how C99 `strtod()` behaves when underflowing.  What if the behavior of stdtod() on this platform on underflow is to just return 0 instead of the correct behavior?  The offical documentation for `strtod()` here:

* http://www.cplusplus.com/reference/cstdlib/strtod/

says "If the correct value is out of the range of representable values for the type, a positive or negative HUGE_VAL is returned, and errno is set to ERANGE."

In any case, I don't think this is a Teuchos defect.  I think this is a defect in the implementation of `stdtod()` provided on this system.  Not sure what to do about that other than just document it and perhaps disable these tests on this system if we need 100% clean tests.  But I think this is a warning about this system.  But if we can't catch invalid conversion from string to double on this one system, that does not really cause me much concern.  This function is really for validating user input from a text file like when reading in a ParameterList.  Since people are likely to validate their input PLs on another machine before running on a system like this, I think the conversion error would be caught there.

**Comment by nmhamster** [comment] 2016-10-14 16:59
@bartlettroscoe what would you suggest we do with the issue? I think there is some danger in our development efforts that we are implicitly assuming X86 is "correct" with respect to operational behavior perhaps. Do we need to catalogue these or can we just close them out?

**Comment by bartlettroscoe** [comment] 2016-10-14 17:53
> I think there is some danger in our development efforts that we are implicitly assuming X86 is "correct" with respect to operational behavior perhaps. 

I don't think this is X86 behavior per say.  The behavior documented at:

* http://www.cplusplus.com/reference/cstdlib/strtod/

is supposed to hold on **all** systems.

> Do we need to catalogue these or can we just close them out?

Right now, I think there is value in letting these unit tests fail since there are no Nightly automated tests submitted to that will fail and send out CDash error emails.  But if these failing tests are blocking some automated processes or hiding new defects on this machine, then we should disable just these unit tests on this machine.  Or we can try to fix the behavior for just this machine.

Trilinos developers and stakeholders need to discuss how to deal with issues like this for our next generation systems.  There is going to be some non-standard behavior with some of these new systems.  It is just not clear to me the best way to address them.

As for these Trilinos GitHub issues, I am not sure.  I have added a note to mention this at the next Trilinos Leaders Meeting.

**Comment by mhoemmen** [comment] 2016-10-14 22:37
@nmhamster @bartlettroscoe As far as I know, there's nothing in Trilinos that depends on correctness of `long double`-related standard library functions.  I'll be happy if we disable the tests for `long double`-related conversions on platforms with non-compliant implementations.  The commented-out test and comments in lines 169-187 hint at the mess that is the current state of cross-platform `long double` support.

https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp#L169

**Comment by bartlettroscoe** [comment] 2016-10-16 16:49
But the unit tests that are failing here:

https://github.com/trilinos/Trilinos/blob/master/packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp#L411

seem to be protected by `if (sizeof (long double) > sizeof (double)` so that must mean that `long double` is a different type from `double` on this platform.  But I guess that does not guarantee that all `long double` and `double` behavior is correct on all platforms.  So should these unit tests be made a little bit more fine-grained and we should put in different checks for invalid conversions from strings to `double`?  I don't think the underflow behavior from converting from a `long double` in string to a `double` is important behavior.  I can't think of a use case of the top of my head why where that behavior be seen.

**Comment by nmhamster** [comment] 2016-10-16 17:02
@bartlettroscoe almost certain long double and double won't be the same going forward on at least some of the testbeds. We can talk more offline if needed on that.

**Comment by mhoemmen** [comment] 2016-10-17 18:47
`long double` and `double` really should NOT be the same.  It's only Windows that seems to show this weird behavior.  In any case, this is one of the reasons why I don't rely on `long double`; it's hard enough convincing vendors to implement `double` correctly ;-P  I'm happy just getting rid of this test.

**Closed** 2021-02-17 12:26 UTC
Labels: CLOSED_DUE_TO_INACTIVITY, MARKED_FOR_CLOSURE, pkg: Teuchos, type: bug
