### ISSUE TITLE
ML: implicit declaration of function ‘ML_Operator_Copy_Statistics’ 

### ISSUE THREAD

**Issue by nschloe** [trilinos/Trilinos#376] opened 2016-05-20 11:22 UTC
When compiling Trilinos, ML gives the warning

```
/«PKGBUILDDIR»/packages/ml/src/Coarsen/ml_aggregate.c:2097:3: warning: implicit declaration of function ‘ML_Operator_Copy_Statistics’ [-Wimplicit-function-declaration]
   ML_Operator_Copy_Statistics(mat,permuted_Amat);
   ^
```

That's one of only two that the Debian build complains about, so it'd be great if this could be addressed (even though it's minor).

**Comment by aprokop** [comment] 2017-06-10 06:00
Duplicate of #860

**Closed by aprokop** 2017-06-10 06:00 UTC
Labels: ML
