### ISSUE TITLE
MueLu: Link error when when compiling with CUDA

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#1574] opened 2017-08-03 22:18 UTC
On ride, when configuring Trilinos with the following (OpenMP) options:

```sh
  -D Trilinos_ENABLE_OpenMP:BOOL=ON \
  -D Kokkos_ENABLE_OpenMP:BOOL=ON \
  -D Tpetra_INST_OPENMP:BOOL=OFF \
```

I get the following  @trilinos/muelu build error

```sh
collect2: error: ld returned 1 exit status
make[2]: *** [packages/muelu/test/paramlist/MueLu_paramlist.exe] Error 1
make[1]: *** [packages/muelu/test/paramlist/CMakeFiles/MueLu_paramlist.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

The actual error is:

```sh
../../src/libmuelu.so.12.13: undefined reference to `Tpetra::MultiVector<double, int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace>, false>::scale(Teuchos::ArrayView<double const> const&)'
```

**Comment by tjfulle** [comment] 2017-08-03 22:21
Other relevant configure options:

```sh
    -D Trilinos_ENABLE_Kokkos=ON \
   -D Kokkos_ENABLE_Cuda=ON \
    -D Kokkos_ENABLE_Serial:BOOL=ON \
    -D Kokkos_ENABLE_OpenMP:BOOL=ON \
    -D Kokkos_ENABLE_Pthread:BOOL=OFF \
    -D Kokkos_ENABLE_Cuda:BOOL=ON \
    -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
```

**Comment by tjfulle** [comment] 2017-08-03 22:31
Compiler information: `gcc-5.4`, `openmpi-1.10.4`, `cuda-8.0.44`

**Comment by jhux2** [comment] 2017-08-03 23:19
@tjfulle Your configure line enables OpenMP but disables explicit instantiation for it.  What's the motivation?

**Comment by tjfulle** [comment] 2017-08-03 23:37
@jhux2, it's how Sierra builds.

The other OpenMP enables were to get past compile time errors :)

**Comment by jhux2** [comment] 2017-08-04 19:31
> @jhux2, it's how Sierra builds.
>
> The other OpenMP enables were to get past compile time errors :)

@tjfulle I guess the Sierra configuration does not result in this error, but rather the additional cmake options?  Would you please specify the base Sierra build, and then what options were added that caused the problem?  Thanks.

**Comment by tjfulle** [comment] 2017-08-04 19:33
@mhoemmen , do you know the configuration that Sierra uses?

**Comment by mhoemmen** [comment] 2017-08-04 20:00
I think it's pretty reasonable for users to enable OpenMP in the compiler, but not enable it in solvers.  If MueLu does not intend to support this use case, that's fine, but then it should check for this at configure time.  The build issue didn't show up in Sierra's build, it showed up when Tim was attempting to test Tpetra changes in downstream packages.

**Comment by mhoemmen** [comment] 2017-08-04 20:12
Here are the relevant build options that Sierra enables in `TPLs_src/Nbtools/Trilinos/dev/TpetraCore/Jamfile`.  Just `<define>` means that the macro is unconditionally defined; it's also possible to add conditional defines, like "only if CUDA build" or "only if OpenMP enabled."
```
    <define>HAVE_TPETRACORE_MPI
    <define>HAVE_TPETRA_MPI
    <cuda>on:<define>HAVE_TPETRACORE_CUDA
    <cuda>on:<define>HAVE_TPETRA_CUDA
    <define>HAVE_TPETRA_INST_INT_LONG
    <define>HAVE_TPETRA_INST_DOUBLE
    <define>HAVE_TPETRA_INST_COMPLEX_DOUBLE
    <define>HAVE_TPETRA_INST_SERIAL
    <openmp>on:<define>HAVE_TPETRA_INST_OPENMP
    <cuda>on:<define>HAVE_TPETRA_INST_CUDA
    <define>HAVE_TPETRA_INT_INT
    <define>HAVE_TPETRA_INT_LONG
    <define>HAVE_TPETRA_INT_UNSIGNED
    <define>HAVE_TPETRA_FLOAT
    <define>HAVE_TPETRA_DOUBLE
    <define>HAVE_TPETRA_COMPLEX_FLOAT
    <define>HAVE_TPETRA_COMPLEX_DOUBLE
    <define>HAVE_TPETRA_SERIAL
    <openmp>on:<define>HAVE_TPETRA_OPENMP
    <openmp>on:<define>HAVE_TPETRA_DEFAULTNODE_OPENMPWRAPPERNODE
    <cuda>on:<define>HAVE_TPETRA_CUDA
    <cuda>on:<define>HAVE_TPETRA_DEFAULTNODE_CUDAWRAPPERNODE
    <lapack>mkl:<define>HAVE_TPETRA_THREADED_MKL
```
I'll need to look more carefully at the Kokkos options that Sierra uses.

**Comment by mhoemmen** [comment] 2017-08-06 00:28
> If MueLu does not intend to support this use case, that's fine, but then it should check for this at configure time.

I think I realize what the issue is now -- MueLu has to build if Tpetra is disabled, which means it needs to instantiate Node types independently of Tpetra.  It's tricky :-) .

**Comment by mhoemmen** [comment] 2017-09-12 21:38
@tjfulle Could this be a duplicate of #1726 ?  Just curious.

**Comment by tjfulle** [comment] 2017-09-12 21:44
No, I don't think so; but @tawiesn mentioned missing OpenMP node types in a comment for #1726, that could be the same issue

**Comment by mhoemmen** [comment] 2017-10-02 02:10
This is still a thing.  See my #1786 comments.

**Closed** 2021-04-12 17:21 UTC
Labels: MARKED_FOR_CLOSURE, pkg: MueLu
