### ISSUE TITLE
Intrepid2 is not allowed to depend on ROL

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#579] opened 2016-08-24 03:03 UTC
My commit d5e30d157957623ca631484a50f8eadb5814e332 did not cause this.  Intrepid2 listed "Rol" as a dependency; that was misspelled (TriBITS is case sensitive).  `git blame` suggests that this was commit b1bfe019.

ROL comes after Intrepid2 in the package dependency list, so Intrepid2 is not allowed to depend on ROL.  CMake configuration of Trilinos stops with an error:

Processing Project, Repository, and Package dependency files and building internal dependencies graph ...

CMake Error at cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:141 (MESSAGE):
  Error, the package 'Rol' is listed as a dependency of the package
  'Intrepid2' is in the list 'Trilinos_SE_PACKAGES' but the package 'Rol' is
  either not defined or is listed later in the package order.  Check the
  spelling of 'Rol' or see how it is listed in
  Trilinos_PACKAGES_AND_DIRS_AND_CLASSIFICATIONS in relationship to
  'Intrepid2'.

I e-mailed @lxmota -- this breaks the whole Trilinos build, but I don't just want to revert because there are three commits in a row that changed Intrepid2.  Not sure whether it's safe to revert just one of them.

**Comment by lxmota** [comment] 2016-08-24 04:03
I reverted the last 4 commits, 3 of them mine and one yours so that the state is as before I committed anything.

Before committing the troublesome commits, I rebuilt and tested Trilinos from scratch with gcc and clang and I did not get the error. That is why I pushed those commits.

Is there no way then to make Intrepid2 dependent on ROL?

**Comment by mhoemmen** [comment] 2016-08-24 14:13
> I rebuilt and tested Trilinos from scratch with gcc and clang and I did not get the error.

I totally believe that you did this :-)  I'm just curious why it was able to work.  Did you rerun CMake first, or just type "make"?  If the latter, did CMake run on its own first?

**Comment by mhoemmen** [comment] 2016-08-24 14:17
> Is there no way then to make Intrepid2 dependent on ROL?

I just looked at the package dependencies -- it looks like you could do this.  You would just need to edit Trilinos/PackagesList.cmake to put ROL above Intrepid2.

**Comment by maherou** [comment] 2016-08-24 15:39
I would like to discuss the details of what happened here.  The positive thing to note is that the regression in cmake execution was caught on the develop branch.  But I would like to figure out if we can change processes or policies to reduce the risk of this kind regression in the future.  Perhaps changes like this should be reviewed before committing?

**Comment by mhoemmen** [comment] 2016-08-24 17:15
> But I would like to figure out if we can change processes or policies to reduce the risk of this kind regression in the future. Perhaps changes like this should be reviewed before committing?

I'm not even sure how it was technically possible.  If Intrepid2 and ROL were both enabled, TriBITS normally catches issues like this and stops the configure with an error message.  I was using the check-in test script -- could it be that a regular CMake configure works differently?

**Comment by lxmota** [comment] 2016-08-24 17:29
Sorry about this. When I said that I rebuild and tested Trilinos I mean I erased the build directory completely, started from a clean source and ran CMake in a new build directory.

I still need to make Intrepid2 dependent on ROL but now I'm afraid to break things. How should I proceed?

**Comment by jhux2** [comment] 2016-08-24 17:41
> Sorry about this. When I said that I rebuild and tested Trilinos I mean I erased the build directory completely, started from a clean source and ran CMake in a new build directory.
> 
> I still need to make Intrepid2 dependent on ROL but now I'm afraid to break things. How should I proceed?

@lxmota At the very least, you should run the checkin script with secondary stable code enabled.

**Comment by mhoemmen** [comment] 2016-08-24 17:54
> I still need to make Intrepid2 dependent on ROL but now I'm afraid to break things. How should I proceed?

Would it ever make sense for ROL to depend on Intrepid2?

If not, then it is safe for Intrepid2 to depend on ROL.  Just edit Trilinos/PackagesList.cmake, and put the ROL line above Intrepid2.  Run the check-in test script with `--default-builds="" --extra-builds=MPI_DEBUG,SERIAL_RELEASE`, so that all packages are enabled.  Otherwise, it won't test ROL, which is not Primary Tested.

If it would ever make sense for ROL to depend on Intrepid2, then you might want to think about putting your Intrepid2 code in a different place -- either in ROL as an optional subpackage, or in TrilinosCouplings.

**Comment by maherou** [comment] 2016-08-24 17:59
@lxmota, Alejandro,

Since we don't know how the regression in the build process happened, please have someone from the Trilinos framework (Brent, Jim W, Ross) review your code before committing it to the main GitHub repo.  Nothing fancy, but a kind of sanity check.  Thanks.

**Comment by lxmota** [comment] 2016-08-24 18:01
Okay, will do. Thanks.

**Comment by mperego** [comment] 2016-08-24 18:02
ROL might need to depend on Intrepid2 for testing.. in fact Intrepid(1) is an optional dependency for ROL now. Let @dridzal and @dpkouri weigh on this.

**Comment by mhoemmen** [comment] 2016-08-24 18:05
> ROL might need to depend on Intrepid2 for testing . . . .

We could put those ROL tests that depend on Intrepid2 in a subpackage of Intrepid2.  There are other ways to make this work :-)  but I'll let @dridzal and @dpkouri talk first.

**Comment by lxmota** [comment] 2016-08-24 18:10
I'm open to move the Intrepid2 code to ROL since it implements MiniTensor ROL adaptors. @dridzal suggested to do that when we first discussed the work that we are trying to do. That way Intrepid2 would not be dependent on ROL. But then ROL would now be optionally dependent on Intrepid2.

**Comment by mperego** [comment] 2016-08-24 18:23
That might work.I think it is OK for Rol to have an optional dependency on Intrepid2.

**Comment by dridzal** [comment] 2016-08-24 20:29
Yes, it is OK for ROL to optionally depend on Intrepid2.  We already have an optional dependency on Intrepid, because of the PDE-OPT suite of tools and problems in PDE-constrained optimization.  In the future, we would like to use Intrepid2 as well, of course.  Also, note that there are at least 4 adapters in ROL that optionally include other Trilinos packages or TPLs, so this would be very natural.


________________________________

**Comment by lxmota** [comment] 2016-08-24 20:44
Okay then. I'll go ahead and move the MiniTensor ROL adaptors from Intrepid2 to ROL, then ask Brent, Jim W or Ross to quick-check it (as @maherou suggested) before running the checkin script to commit it

**Comment by lxmota** [comment] 2016-09-12 21:27
I made the commit above and used the check-in script to test it last week. No problems so far so I'm closing this issue.

**Closed by lxmota** 2016-09-12 21:27 UTC
Labels: bug, Intrepid2, ROL
