### ISSUE TITLE
Tpetra/Belos: multiply with locally empty multivectors produces incorrect results

### ISSUE THREAD

**Issue by pohm01** [trilinos/Trilinos#9583] opened 2021-08-18 18:26 UTC
## Bug Report
@trilinos/tpetra @trilinos/belos

### Description
Problematic uninitialized values propagated in reduce call when multiply done using multivectors that are locally empty on a process.

If you do the following Tpetra::MultiVector multiply call

`C->multiply(trans, no_trans, alpha, A, B, beta)`

where `beta=0` and and `alpha=1` (i.e. C = A^T * B) and memory is distributed to trigger Case 2 in the multiply routine (Case 2: C(local) = A^T(distr) * B  (distr)). A problem arises when `A` and `B` have `getLocalLength()=0` on a process. When this occurs the local computation (in this case KokkosBlas::gemm) does not do anything to the local `C` since the local vectors have zero length. Since `C` is allocated but the values are not initialized, it is left filled with random noise. So when `C->reduce()` is called the uninitialized values are included.

This currently manifests itself in Belos during orthogonalization. Specifically `packages/belos/src/BelosICGSOrthoManager.hpp` line `1252` (`MatOrthoManager<ScalarType,MV,OP>::innerProd(*Q[i],X,MX,*C[i]);`).

### Steps to Reproduce
Currently happens in a Drekar simulation.
Here is a PR with small test that reproduces the error in Tpetra: #9593

**Comment by jennloe** [comment] 2021-08-19 15:50
@GrahamBenHarper Was this the issue you mentioned to me a few days ago?

**Comment by GrahamBenHarper** [comment] 2021-08-19 16:04
@jennloe yep!

**Comment by jennloe** [comment] 2021-08-19 16:05
The definition of `MatOrthoManager::innerProd()` is at `BelosMatOrthoManager.hpp` line 115-145.  This is probably failing in line 144: ` MVT::MvTransMv(SCT::one(),*P,*Q,Z);`.  

Looking at `BelosMultiVecTraits_Tpetra.hpp`, the `MvTransMV` (line 446) calls the following:
```
475       MV C_mv = makeStaticLocalMultiVector (A, numRowsC, numColsC);
476       // Filling with zero should be unnecessary, in theory, but not
477       // in practice, alas (Issue_3235 test fails).
478       C_mv.putScalar (ZERO);
479       C_mv.multiply (Teuchos::CONJ_TRANS, Teuchos::NO_TRANS, alpha, A, B, ZERO);
480       Tpetra::deep_copy (C, C_mv);
```

Looks like there was a similar issue in #3235 and the solution was to initialize C to zeros.  So if C is being initialized to zero here, why is it filled with random noise??

**Comment by cgcgcg** [comment] 2021-08-19 16:21
@pohm01 Are you by any chance using Tpetra wrapped by Thyra? Cause then this would need to be checked in the Thyra adapter, not the Tpetra adapter.

**Comment by pohm01** [comment] 2021-08-19 16:21
@jennloe Oops, I overlooked a bit of the path being taken (my bad). Drekar is using stratamikos, so the `MvTransMv` being used is `packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp`

**Comment by pohm01** [comment] 2021-08-19 17:20
I created a small PR #9593 with a tpetra test that sets up the conditions for the bug and reproduces it.

**Comment by jennloe** [comment] 2021-08-19 18:12
So I think the big question is whether we should put a fix for this in Tpetra or only adjust for it in the Tpetra-Thyra-Belos adapters.  

I haven't finished digging into the Thyra adapter, but since issue #3235 only mentions the Tpetra adapter, I suspect that the Thyra adapter needs the same fix.

**Comment by cgcgcg** [comment] 2021-08-19 19:52
I'd vote Tpetra. This is gonna bite anyone who calls `multiply` with an empty rank, right?

**Comment by kyungjoo-kim** [comment] 2021-08-19 20:11
@jennloe If the GEMM (beta=0,local length=0) does not initialize the matrix C, then the problem is that kokkos gemm does not follow the standard implementation of blas. The reference implmentation has the following quick return and scaling routine of C.
```
*                                                                                                             
*     Quick return if possible.                                                                               
*                                                                                                             
      IF ((M.EQ.0) .OR. (N.EQ.0) .OR.
     +    (((ALPHA.EQ.ZERO).OR. (K.EQ.0)).AND. (BETA.EQ.ONE))) RETURN
*                                                                                                             
*     And if  alpha.eq.zero.                                                                                  
*                                                                                                             
      IF (ALPHA.EQ.ZERO) THEN
          IF (BETA.EQ.ZERO) THEN
              DO 20 J = 1,N
                  DO 10 I = 1,M
                      C(I,J) = ZERO
   10             CONTINUE
   20         CONTINUE
          ELSE
              DO 40 J = 1,N
                  DO 30 I = 1,M
                      C(I,J) = BETA*C(I,J)
   30             CONTINUE
   40         CONTINUE
          END IF
          RETURN
      END IF
```

**Comment by kddevin** [comment] 2021-08-30 23:01
@pohm01 I put a patch in Trilinos branch tpetra_9583; see #9635.    
It removes the early exit from kokkos-kernels' gemm in your use case.  Would you please try it?  
If it helps, we'll report back to https://github.com/kokkos/kokkos-kernels/issues/1088.  Thanks.

**Comment by pohm01** [comment] 2021-08-31 15:08
@kddevin the fix seems to work in the Drekar simulation I'm running. Thanks!

**Closed** 2022-02-17 21:34 UTC
Labels: type: bug, pkg: Tpetra, pkg: Belos
