### ISSUE TITLE
Xpetra:  error: ISO C++ forbids nested type 'TpetraVector' with same name as enclosing class [-fpermissive]

### ISSUE THREAD

**Issue by Mark-E-Hamilton** [trilinos/Trilinos#5061] opened 2019-05-01 17:18 UTC
I pulled in the most recent of Trilinos master for a Sierra integration build with ETI off. While building this file

/scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.cpp

It generated the following error:
```
In file included from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/Headers/Xpetra_UseShortNames.hpp:49:0,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp:335,
                 from /scratch/sierra/sierra_master/objs/tpls/Trilinos/b2ed81b8c8472240/packages/xpetra/src/Xpetra_TpetraVector.hpp:2,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/MultiVector/Xpetra_TpetraMultiVector_def.hpp:1028,
                 from /scratch/sierra/sierra_master/objs/tpls/Trilinos/b2ed81b8c8472240/packages/xpetra/src/Xpetra_TpetraMultiVector.hpp:2,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp:62,
                 from /scratch/sierra/sierra_master/objs/tpls/Trilinos/b2ed81b8c8472240/packages/xpetra/src/Xpetra_TpetraCrsMatrix.hpp:1,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp:54,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp:60,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp:54,
                 from /scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.cpp:50:
/scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp:164:73: error: ISO C++ forbids nested type 'TpetraVector' with same name as enclosing class [-fpermissive]
 typedef Xpetra::TpetraVector<Scalar, LocalOrdinal, GlobalOrdinal, Node> TpetraVector;
                                                                         ^~~~~~~~~~~~
/scratch/sierra/sierra_master/TPLs_src/Trilinos/packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp:164:73: error: 'Xpetra::TpetraVector<Scalar, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >::TpetraVector' has the same name as the class in which it is declared
```

**Comment by csiefer2** [comment] 2019-05-01 17:29
Last night or this morning?  Stuff changed at 11am last night.

**Comment by mhoemmen** [comment] 2019-05-01 18:02
@csiefer2 Mark will have to say more, but I'm pretty sure it's just the latest commit on master:
```
commit f58da722e20f5e1c72954f5e16081cce0c2826ec (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 91b1358661 410cdbcd44
Author: trilinos-autotester <trilinos-autotester@trilinos.org>
Date:   Wed May 1 04:07:16 2019 -0600

    Merge Pull Request #5053 from trilinos/Trilinos/master_merge_20190501_000613

    Automatically Merged using Trilinos Master Merge AutoTester
    PR Title: Trilinos Master Merge PR Generator: Auto PR created to promote from master_merge_20190501_000613 branch to master
    PR Author: trilinos-autotester
```

**Comment by Mark-E-Hamilton** [comment] 2019-05-01 18:48
As Mark said, it was the master commit from this morning about noon. I've reverted it for now so that I can get back to the set of errors I had yesterday.

**Comment by csiefer2** [comment] 2019-05-01 20:54
Yeah, looks like that's my doing.  Will try to see if I can reproduce.

**Comment by csiefer2** [comment] 2019-05-01 21:09
Can you email me some reproduction instructions (e.g. configure lines), because my no-eti builds work just fine.

**Comment by Mark-E-Hamilton** [comment] 2019-05-01 22:12
Okay, it's big, but this is the command that we use:
```
cmake -G "Unix Makefiles" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -D Trilinos_EXTRA_LINK_FLAGS:STRING="" \
  -D CMAKE_BUILD_TYPE:STRING=release \
  -D LAPACK_LIBRARY_DIRS:PATH=/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/lapack/lib \
  -D LAPACK_LIBRARY_NAMES:STRING="src-lapack-c;src-lapack-d;src-lapack-s;src-lapack-z" \
  -D BLAS_LIBRARY_DIRS:PATH=/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/lapack/lib \
  -D BLAS_LIBRARY_NAMES:STRING="src-blas-c;src-blas-d;src-blas-s;src-blas-z" \
  -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
  -D Kokkos_ENABLE_Cuda_Relocatable_Device_Code:BOOL=OFF \
  -D TPL_ENABLE_CUDA:BOOL=OFF \
  -DCMAKE_CXX_COMPILER_LAUNCHER= \
  -DCMAKE_C_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpicc \
  -DCMAKE_CXX_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpicxx \
  -DCMAKE_Fortran_COMPILER=/projects/sierra/linux_rh7/SDK/mpi/openmpi/1.10.2-gcc-7.2.0-RHEL6/bin/mpif90 \
  -DKokkos_ENABLE_SIERRA_BUILD:BOOL=OFF \
  -DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
  -DCMAKE_INSTALL_PREFIX:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb" \
  -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -DTrilinos_ENABLE_Gtest:BOOL=OFF \
  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=OFF \
  -DTPL_ENABLE_MPI:BOOL=ON \
  -DCMAKE_EXTRA_LINK_FLAGS:STRING= \
  -DCMAKE_C_FLAGS_RELEASE_OVERRIDE:STRING="\
  -DNDEBUG" \
  -DCMAKE_CXX_FLAGS_RELEASE_OVERRIDE:STRING="\
  -DNDEBUG" \
  -DCMAKE_Fortran_FLAGS_RELEASE_OVERRIDE:STRING="\
  -DNDEBUG" \
  -DCMAKE_C_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -Wno-inline -w " \
  -DCMAKE_CXX_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -Wno-inline -w " \
  -DCMAKE_Fortran_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -Wno-inline -w  " \
  -DTrilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
  -DTPL_ENABLE_Pthread:BOOL=OFF \
  -DHAVE_GCC_ABI_DEMANGLE:BOOL=ON \
  -DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
  -DTPL_ENABLE_ParMETIS:BOOL=ON \
  -DParMETIS_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/ParMetis/include;/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/ParMetis/metis/include" \
  -DParMETIS_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/ParMetis/lib;/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/ParMetis/metis/lib" \
  -DMETIS_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/ParMetis/metis/include" \
  -DMETIS_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/ParMetis/metis/lib" \
  -DTPL_ENABLE_UMFPACK:BOOL=ON \
  -DUMFPACK_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/umfpack/include" \
  -DUMFPACK_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/umfpack/lib" \
  -DTPL_ENABLE_y12m:BOOL=ON \
  -Dy12m_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/y12m/lib" \
  -DTPL_ENABLE_Boost:BOOL=ON \
  -DTPL_Boost_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/boost" \
  -DTPL_ENABLE_yaml-cpp:BOOL=OFF \
  -Dyaml-cpp_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/yaml-cpp/include/include/yaml-cpp" \
  -Dyaml-cpp_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/yaml-cpp/lib" \
  -DSuperLU_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/superlu/include" \
  -DSuperLU_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/superlu/lib" \
  -DScotch_INCLUDE_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/scotch/include" \
  -DScotch_LIBRARY_DIRS:PATH="/scratch/sierra/sierra_master2/objs/tpls/trilinos_tpls/674bc76fb281e0bb/TPLs_src/scotch/lib" \
  -DTrilinos_ENABLE_ThreadPool:BOOL=ON \
  -DTrilinos_ENABLE_Zoltan:BOOL=ON \
  -DZoltan_ENABLE_Scotch:BOOL=OFF \
  -DTrilinos_ENABLE_Zoltan2:BOOL=ON \
  -DZoltan2_ENABLE_Scotch:BOOL=OFF \
  -DZoltan2_ENABLE_Experimental:BOOL=ON \
  -DZoltan2_ENABLE_HYPERGRAPHMODEL:BOOL=OFF \
  -DTrilinos_ENABLE_Shards:BOOL=ON \
  -DTrilinos_ENABLE_Mesquite:BOOL=OFF \
  -DTrilinos_ENABLE_Teuchos:BOOL=ON \
  -DTrilinos_ENABLE_RTOp:BOOL=ON \
  -DTrilinos_ENABLE_Epetra:BOOL=ON \
  -DTrilinos_ENABLE_EpetraExt:BOOL=ON \
  -DTrilinos_ENABLE_Triutils:BOOL=ON \
  -DTrilinos_ENABLE_Thyra:BOOL=ON \
  -DTrilinos_ENABLE_AztecOO:BOOL=ON \
  -DTrilinos_ENABLE_Amesos:BOOL=ON \
  -DTrilinos_ENABLE_Amesos2:BOOL=ON \
  -DTrilinos_ENABLE_Belos:BOOL=ON \
  -DTrilinos_ENABLE_Intrepid:BOOL=ON \
  -DTrilinos_ENABLE_IntrepidIntrepid2:BOOL=OFF \
  -DIntrepid_ENABLE_KokkosCore:BOOL=OFF \
  -DTrilinos_ENABLE_Ifpack:BOOL=ON \
  -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
  -DTrilinos_ENABLE_Tpetra:BOOL=ON \
  -DTrilinos_ENABLE_Kokkos:BOOL=ON \
  -DTrilinos_ENABLE_KokkosCore:BOOL=ON \
  -DTrilinos_ENABLE_KokkosContainers:BOOL=ON \
  -DTrilinos_ENABLE_KokkosTSQR:BOOL=OFF \
  -DTrilinos_ENABLE_Anasazi:BOOL=ON \
  -DTrilinos_ENABLE_ML:BOOL=ON \
  -DTrilinos_ENABLE_MueLu:BOOL=ON \
  -DTrilinos_ENABLE_Stratimikos:BOOL=OFF \
  -DTrilinos_ENABLE_NOX:BOOL=ON \
  -DTrilinos_ENABLE_FEI:BOOL=ON \
  -DTrilinos_ENABLE_TrilinosCouplings:BOOL=ON \
  -DTrilinos_ENABLE_MOOCHO:BOOL=OFF \
  -DTrilinos_ENABLE_Sacado:BOOL=ON \
  -DSacado_ENABLE_KokkosCore:BOOL=ON \
  -DTrilinos_ENABLE_Stokhos:BOOL=ON \
  -DTrilinos_ENABLE_Pamgen:BOOL=ON \
  -DPamgen_ENABLE_Boost:BOOL=OFF \
  -DTrilinos_ENABLE_Rythmos:BOOL=ON \
  -DTrilinos_ENABLE_ThyraEpetraExtAdapters:BOOL=ON \
  -DTrilinos_ENABLE_Xpetra:BOOL=ON \
  -DTrilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON \
  -DTacho_ENABLE_INT_INT:BOOL=ON \
  -DAmesos2_ENABLE_ShyLU_NodeTacho:BOOL=OFF \
  -DTrilinos_ENABLE_ShyLU_NodeHTS:BOOL=ON \
  -DTrilinos_ENABLE_ShyLUFastILU:BOOL=ON \
  -DTrilinos_ENABLE_Isorropia:BOOL=OFF \
  -DTrilinos_ENABLE_STKClassic:BOOL=OFF \
  -DTrilinos_ENABLE_STK:BOOL=OFF \
  -DTrilinos_ENABLE_SEACAS:BOOL=OFF \
  -DAmesos_ENABLE_SuperLU:BOOL=ON \
  -DAmesos2_ENABLE_SuperLU:BOOL=ON \
  -DAztecOO_ENABLE_AZLU:BOOL=ON \
  -DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
  -DTrilinos_ENABLE_FLOAT:BOOL=ON \
  -DZoltan_ENABLE_METIS:BOOL=OFF \
  -DStokhos_ENABLE_Ifpack:BOOL=OFF \
  -DStokhos_ENABLE_ML:BOOL=OFF \
  -DStokhos_ENABLE_Anasazi:BOOL=OFF \
  -DStokhos_ENABLE_Sacado:BOOL=ON \
  -DStokhos_ENABLE_NOX:BOOL=OFF \
  -DStokhos_ENABLE_KokkosClassic:BOOL=OFF \
  -DStokhos_ENABLE_KokkosCore:BOOL=OFF \
  -DStokhos_ENABLE_Tpetra:BOOL=OFF \
  -DStokhos_ENABLE_Ifpack2:BOOL=OFF \
  -DStokhos_ENABLE_AztecOO:BOOL=OFF \
  -DStokhos_ENABLE_Stratimikos:BOOL=OFF \
  -DStokhos_ENABLE_Belos:BOOL=OFF \
  -DML_ENABLE_ParMETIS:BOOL=OFF \
  -DML_ENABLE_METIS:BOOL=OFF \
  -DNOX_ENABLE_ABSTRACT_IMPLEMENTATION_THYRA:BOOL=OFF \
  -DKOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF \
  -DKOKKOS_ENABLE_PROFILING:BOOL=ON \
  -DTrilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION:BOOL=ON \
  -DTrilinos_ENABLE_MiniTensor:BOOL=ON \
  -DTrilinos_ENABLE_Galeri:BOOL=OFF \
  -DTpetra_INST_SERIAL:BOOL=ON \
  -DTpetra_INST_INT_LONG:BOOL=ON \
  -DTpetra_INST_INT_LONG_LONG:BOOL=OFF /scratch/sierra/sierra_master2/TPLs_src/Trilinos
make -j 256
make -j1
```

**Comment by mhoemmen** [comment] 2019-05-01 22:35
I didn't realize that Trilinos' PR testing has no static library builds: https://github.com/trilinos/Trilinos/issues/5058
That could be related.

**Comment by csiefer2** [comment] 2019-05-01 23:22
Lovely.

**Comment by kddevin** [comment] 2019-05-02 19:42
I see this too on my mac:
```
In file included from /Users//code/Trilinos/packages/xpetra/src/Headers/Xpetra_UseShortNames.hpp:49:
/Users//code/Trilinos/packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp:164:73: error: member 'TpetraVector' has the same name as its class
typedef Xpetra::TpetraVector<Scalar, LocalOrdinal, GlobalOrdinal, Node> TpetraVector;
```
Kitchen-sink build -- probably way more inclusive than needed:
```
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Tpetra_INST_INT_INT:BOOL=ON \
-D Tpetra_INST_INT_LONG_LONG:BOOL=OFF \
-D CMAKE_BUILD_TYPE:STRING="DEBUG" \
\
-D TPL_ENABLE_MPI:BOOL=ON \
\
-D TPL_ENABLE_BinUtils:BOOL=OFF \
-D TPL_ENABLE_Pthread:BOOL=OFF \
\
-D CMAKE_C_FLAGS:STRING="-Wall  -pedantic -Wno-unknown-pragmas -Wno-narrowing -Wno-inline -Wshadow -Wdeprecated-declarations -Wempty-body  -Wignored-qualifiers -Wmissing-field-initializers  -Wsign-compare  -Wtype-limits   -Wuninitialized -Winit-self -fstrict-aliasing -Wno-long-long" \
-D CMAKE_CXX_FLAGS:STRING="-Wall -pedantic -Wno-unknown-pragmas -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-inline -Wshadow -Wdeprecated-declarations -Wempty-body  -Wignored-qualifiers -Wmissing-field-initializers  -Wsign-compare  -Wtype-limits   -Wuninitialized -Winit-self -fstrict-aliasing" \
\
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=ON \
\
-D Trilinos_ENABLE_SHADOW_WARNINGS:BOOL=ON \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
\
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Nox:BOOL=ON \
-D Trilinos_ENABLE_ROL:BOOL=ON \
-D ROL_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_MiniTensor:BOOL=OFF \
-D ROL_ENABLE_MiniTensor:BOOL=OFF \
-D Trilinos_ENABLE_Panzer:BOOL=ON \
-D Trilinos_ENABLE_Tempus:BOOL=ON \
-D Trilinos_ENABLE_PanzerAdaptersSTK:BOOL=OFF \
-D Trilinos_ENABLE_PanzerAdaptersIOSS:BOOL=OFF \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_TrilinosCouplings:BOOL=ON \
-D Trilinos_ENABLE_STKIO:BOOL=OFF \
-D Trilinos_ENABLE_STKUtil:BOOL=OFF \
\
-D Teuchos_ENABLE_STACKTRACE:BOOL=OFF \
```



                                                                        ^

**Comment by csiefer2** [comment] 2019-05-02 20:57
Can reproduce from Mark's configure

**Comment by kddevin** [comment] 2019-05-02 21:01
One diff is that I have -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON

**Comment by csiefer2** [comment] 2019-05-02 21:05
We decided not to write ETI for the  to[X|T]petra() functions when we did the first ETI system, for simplicity.  This issue demonstrates that such a thing doesn't work and we need to rethink our approach.

@jhux2

**Comment by kddevin** [comment] 2019-05-02 21:43
With only -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON, compilation is fine.
But also specifying the following breaks the build:
-D Tpetra_INST_INT_INT:BOOL=ON \
-D Tpetra_INST_INT_LONG_LONG:BOOL=OFF \

**Comment by jhux2** [comment] 2019-05-02 21:52
> We decided not to write ETI for the to[X|T]petra() functions when we did the first ETI system, for simplicity. This issue demonstrates that such a thing doesn't work and we need to rethink our approach.

@csiefer2 But this is happening in a *non* ETI build.

**Comment by csiefer2** [comment] 2019-05-02 21:54
And Karen's ETI build too.

**Comment by csiefer2** [comment] 2019-05-03 15:45
#5088 for fix

**Comment by csiefer2** [comment] 2019-05-03 15:47
@jhux2 Ignore my previous comment about the to[X|T]petra functions.  That was incorrect.

**Comment by csiefer2** [comment] 2019-05-03 20:36
@Mark-E-Hamilton Fix is in develop.  Please check the nighties and close if I've resolved your issue.

**Comment by mhoemmen** [comment] 2019-05-03 22:44
@ajpowelsnl

**Comment by etphipp** [comment] 2019-05-03 22:47
> @Mark-E-Hamilton Fix is in develop. Please check the nighties and close if I've resolved your issue.

Even with that commit, I still get build errors with clang:
```
/home/etphipp/Trilinos/Trilinos/packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp:164:73: error: 
      member 'TpetraVector' has the same name as its class
typedef Xpetra::TpetraVector<Scalar, LocalOrdinal, GlobalOrdinal, Node> TpetraVe...
                                                                        ^
In file included from /home/etphipp/Trilinos/build/opt_mpi_openmp_clang/packages/xpetra/src/Utils/ExplicitInstantiation/Xpetra_TpetraVector.cpp:55:
/home/etphipp/Trilinos/Trilinos/packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp:365:13: error: 
      destructor cannot be declared using a typedef
      'Xpetra::TpetraVector<type-parameter-0-0, int, long long,
      Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace>
      >::TpetraVector' (aka 'TpetraVector<Scalar, int, long long,
      KokkosDeviceWrapperNode<Kokkos::OpenMP> >') of the class name
    virtual ~TpetraVector() { }
```
Note that the _def.hpp file still includes Xpetra_UseShortNames.hpp:

```
#if ((defined(EPETRA_HAVE_OMP) && (!defined(HAVE_TPETRA_INST_OPENMP) || !defined(HAVE_TPETRA_INST_INT_LONG_LONG))) || \
    (!defined(EPETRA_HAVE_OMP) && (!defined(HAVE_TPETRA_INST_SERIAL) || !defined(HAVE_TPETRA_INST_INT_LONG_LONG))))

  // specialization of TpetraVector for GO=int and NO=SerialNode
  template <class Scalar>
  class TpetraVector<Scalar, int, long long, EpetraNode>
    : public virtual Vector<Scalar,int,long long,EpetraNode>,
      public TpetraMultiVector<Scalar,int,long long,EpetraNode>
  {
    typedef int LocalOrdinal;
    typedef long long GlobalOrdinal;
    typedef EpetraNode Node;

#undef XPETRA_TPETRAMULTIVECTOR_SHORT
#include "Xpetra_UseShortNames.hpp"
```

**Comment by jjellio** [comment] 2019-05-06 05:13
I suspect the problem is:
```
#undef XPETRA_TPETRAMULTIVECTOR_SHORT  => XPETRA_TPETRAVECTOR_SHORT
#include "Xpetra_UseShortNames.hpp"
```
As-is, it would seem the above will result in `typedef Xpetra::TpetraVector<...> TpetraVector` within the TpetraVector class, which would likely cause hell in paradise.

**Comment by jjellio** [comment] 2019-05-06 05:21
No, the above isn't 100% it.

I think the problem is you can't have MultiVector typedef'd either, since this class inherits from it.

Doing this fixes it for me: (I'll need to verify the thing links at the end though!)

This needs to be done twice (both places short names is used - To be safe, I redefine that macro afterward, so the preprocessor state is consistent later)
```
#undef XPETRA_TPETRAMULTIVECTOR_SHORT
#undef XPETRA_TPETRAVECTOR_SHORT
#include "Xpetra_UseShortNames.hpp"
#define XPETRA_TPETRAMULTIVECTOR_SHORT
#define XPETRA_TPETRAVECTOR_SHORT
```

**Comment by csiefer2** [comment] 2019-05-06 14:37
#5096

**Comment by etphipp** [comment] 2019-05-06 20:29
PR #5096 resolved the clang build errors I reported.  Thanks!

**Closed** 2019-05-07 09:58 UTC
Labels: client: Sierra, type: bug
