### ISSUE TITLE
Tpetra: Compile error after commit 47e569d

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#2574] opened 2018-04-18 01:25 UTC
@trilinos/tpetra 

## Expectations

Trilinos should compile without error.

## Current Behavior

Compile errors with both clang and gcc of this type:

[trilinos-serial-gcc-release.log](https://github.com/trilinos/Trilinos/files/1922123/trilinos-serial-gcc-release.log)

## Motivation and Context

Tpetra used for nightly tests and production runs in Albany. This error prevents further development.

## Definition of Done

Compile without error.

## Steps to Reproduce

Enable Tpetra and compile Trilinos.

## Your Environment

commit 47e569d

-DTrilinos_ENABLE_Tpetra:BOOL=ON

Fedora 27, gcc 7.3.1 or clang 5.01

**Comment by tjfulle** [comment] 2018-04-18 01:34
@lxmota can you email me your configure script so I can reproduce the compile error?

**Comment by lxmota** [comment] 2018-04-18 01:38
We use a modules system that has CMake as the controller program, and therefore there is no configure script. We have a CMake template with multiple variables that gets filled in on the fly when CMake is invoked.

But @ikalash sees the same error and she does have configure scripts. So I'm reaching out to her to provide one.

**Comment by tjfulle** [comment] 2018-04-18 02:45
Thanks @ikalash!  I’ll get this building locally.  Hopefully it’ll fail and I can push a fix soon

**Comment by ikalash** [comment] 2018-04-18 02:46
Thanks @tjfulle !

**Comment by mhoemmen** [comment] 2018-04-18 04:12
Thanks @tjfulle ! :D

**Comment by tjfulle** [comment] 2018-04-18 04:13
Hmmm, using @ikalash's configure script I wasn't able to see a build failure locally.  I also didn't see any failures with the checkin script, and the PR testing passed.  I use gcc 6.4.0 locally.  @ikalash, are you also using gcc 7.2.0 like @lxmota?  I'll log on to a CEE machine and try with gcc 7.2.0 in the sems environment to see if I can see a failure.

**Comment by ikalash** [comment] 2018-04-18 04:29
No, I'm using gcc-6.4.1.  Hmmm that's odd that you don't see the problem.  Lets wait until the Albany nightlies run to confirm that the issue occurs there from a clean clone / build.

**Comment by ikalash** [comment] 2018-04-18 15:10
The error showed up in a number of our nightly tests, e.g. 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=69644 

(this was was from the CEE using sems modules, so no unusual OS there).  

What is interesting is my OpenMP and CUDA Trilinos built just fine.  I'm guessing it is b/c that build does not turn on something that the regular Serial KokkosNode build does.  Here is the OpenMP cmake script, if you'd like to compare it to the Serial build one: https://github.com/gahansen/Albany/blob/master/doc/nightlyTestHarness/do-cmake-trilinos-mpi-tpetra-openmp .

**Comment by mhoemmen** [comment] 2018-04-18 15:44
@tjfulle Does that code only have a forward declaration of CrsMatrix, not an actual declaration?  That would explain why it doesn't get the default template parameter values.

**Comment by mhoemmen** [comment] 2018-04-18 16:06
@ikalash It could definitely be that!  I had thought @tjfulle had tested w/ ETI both ON and OFF though.  There were a few somewhat risky includes in that pull request that might have caused some circular including and thus canceled out some content, but I figured testing ETI both ON and OFF should catch them.

**Comment by tjfulle** [comment] 2018-04-18 16:06
@ikalash, I used all of the configurations from the albany dashboard and I don't see a build failure locally.  But, I believe I see the problem and will have a workaround committed soon.

**Comment by tjfulle** [comment] 2018-04-18 16:07
@mhoemmen, I built with ETI ON/OFF (see above comment).  But, I have a fix ready to commit.

**Comment by tjfulle** [comment] 2018-04-18 16:38
@ikalash, @lxmota - @mhoemmen and I just talked about a suspicious include in a Tpetra implementation detail.  Neither of us know why it was there, but it seems to be the source of the problem.  I've put in the fix and am now testing to be sure nothing downstream breaks.  I am very confident this is the source of the build errors.  The will be pushed as soon as the build/tests complete.

**Comment by mhoemmen** [comment] 2018-04-18 16:45
@tjfulle U ROCK

**Comment by tjfulle** [comment] 2018-04-19 01:38
Should be fixed with #2584.

**Comment by lxmota** [comment] 2018-04-19 02:02
I can confirm that Trilinos now compiles with gcc and clang on my local machine.

We'll see what our nighty Albany tests produce: http://cdash.sandia.gov/CDash-2-3-0/index.php?project=Albany

**Comment by ikalash** [comment] 2018-04-19 14:41
Everything was good in the nightly test harness for Albany as well.  I think this issue can be closed.

**Comment by mhoemmen** [comment] 2018-04-19 15:13
Thanks everyone! :D

**Closed** 2018-04-19 15:13 UTC
Labels: Tpetra, bug, build
