### ISSUE TITLE
wrapTpetraSolver example for solving tri-diagonal linear system

### ISSUE THREAD

**Issue by kvmkrao** [trilinos/Trilinos#1598] opened 2017-08-10 19:29 UTC
I ran this example -diagonal CG solver (packages/belos/tpetra/example/) on Hansen. It was observed that  the solver time on GPU nodes is less compared to that on Haswell nodes. 

Haswell nodes | Solver time in sec
-- | --
1 (32 MPI) | 17.18
2 (64 MPI ) | 13.06
3 (96 MPI) | 9.436

The solver time on K80 GPUs is 

GPU nodes | Times in sec
-- | --
1 (4MPI, 1 GPU) | 4.569
2 (8 MPI, 2 GPUs) | 2.338
3 (16 MPI, 3 GPUs) | 1.659

I was trying to use this example to solve a linear system that contains maximum three non-zero elements in a row as it is useful to integrate with a legacy code. 

```
   typedef Kokkos::View<mag_type**, device_type> dev_view_type;
   typedef typename dev_view_type::HostMirror host_view_type;

    dev_view_type diag_d ("diag", lclNumRows, 3);
    host_view_type diag_h = Kokkos::create_mirror_view (diag_d);

      for (LO lclRow = 0; lclRow < lclNumRows; ++lclRow) {
        diag_h(lclRow,0) = - ONE/(ONE + ONE + ONE) ;
        diag_h(lclRow,1) = ONE ; //diag_h(lclRow) * scalingFactor;
        diag_h(lclRow,2) = - ONE/(ONE + ONE + ONE) ;
      }
```
I could not compile this code without errors. 
Is it appropriate to use this code for solving a tri-diagonal linear system?.  If yes, could please suggest me the changes.   
 
**Compilation errors:** 
> 50%] Building CXX object CMakeFiles/example.dir/wrapTpetraSolver.cpp.o
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(713): error: expected a declaration
> 
> /ascldap/users/vkkotte/Trilinos/install/include/Kokkos_View.hpp(1105): error: static assertion failed with "Incompatible View copy assignment"
>           detected during:
>             instantiation of "Kokkos::View<DataType, Properties...> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=const double *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=double **, RP=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(710): here
>             instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(804): here
> 
> /ascldap/users/vkkotte/Trilinos/install/include/impl/Kokkos_ViewMapping.hpp(2915): error: static assertion failed with "View assignment must have compatible dimensions"
>           detected during:
>             instantiation of "void Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::assign(Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::DstType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::SrcType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::TrackType &) [with DstTraits=Kokkos::ViewTraits<const double *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, SrcTraits=Kokkos::ViewTraits<double **, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/install/include/Kokkos_View.hpp(1106): here
>             instantiation of "Kokkos::View<DataType, Properties...> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=const double *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=double **, RP=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(710): here
>             instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(804): here
> 
> /ascldap/users/vkkotte/Trilinos/install/include/impl/Kokkos_ViewMapping.hpp(1015): error: static assertion failed with "ViewOffset assignment requires equal rank"
>           detected during:
>             instantiation of "Kokkos::Experimental::Impl::ViewOffset<Dimension, Kokkos::LayoutLeft, std::enable_if<<expression>, void>::type>::ViewOffset(const Kokkos::Experimental::Impl::ViewOffset<DimRHS, Kokkos::LayoutLeft, void> &) [with Dimension=Kokkos::Experimental::Impl::ViewDimension<0UL>, DimRHS=Kokkos::Experimental::Impl::ViewDimension<0UL, 0UL>]" 
> (2946): here
>             instantiation of "void Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::assign(Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::DstType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::SrcType &, const Kokkos::Experimental::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if<<expression>, void>::type>::TrackType &) [with DstTraits=Kokkos::ViewTraits<const double *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, SrcTraits=Kokkos::ViewTraits<double **, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/install/include/Kokkos_View.hpp(1106): here
>             instantiation of "Kokkos::View<DataType, Properties...> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=const double *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=double **, RP=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(710): here
>             instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(804): here
> 
> /ascldap/users/vkkotte/Trilinos/run/WrapTpetraSolver/modified/wrapTpetraSolver.cpp(687): warning: variable "nonzero" was declared but never referenced
>           detected during instantiation of "TestDiagonalOperator<SC, LO, GO, NT>::TestDiagonalOperator(const Teuchos::RCP<const TestDiagonalOperator<SC, LO, GO, NT>::map_type> &, TestDiagonalOperator<SC, LO, GO, NT>::mag_type) [with SC=Tpetra::Details::DefaultTypes::scalar_type, LO=Tpetra::Details::DefaultTypes::local_ordinal_type, GO=Tpetra::Details::DefaultTypes::global_ordinal_type, NT=Tpetra::Details::DefaultTypes::node_type]" 
> (804): here
> 
> 4 errors detected in the compilation of "/tmp/tmpxft_0000a090_00000000-7_wrapTpetraSolver.cpp1.ii".
> make[2]: *** [CMakeFiles/example.dir/wrapTpetraSolver.cpp.o] Error 2
> make[1]: *** [CMakeFiles/example.dir/all] Error 2
> make: *** [all] Error 2

Thank you.

**Comment by mhoemmen** [comment] 2017-08-11 22:15
@kvmkrao wrote:
> Is it appropriate to use this code for solving a tri-diagonal linear system?

It should _work_, but there are likely faster algorithms if you want to solve only tridiagonal linear systems.

Could you please post the CMake options that you used to build Trilinos?  Please put them in a code block, with three back quotes, 
```
like this.
```

**Comment by kvmkrao** [comment] 2017-08-12 00:04
I thought of changing this example to solve a tri-diagonal linear system. And, modify this further to solve a penta- and septa - diagonal linear system.  I am using a code (please see the attachment) to solve a penta-diagonal linear system. I ran this code on KNL, Haswell and GPU nodes. And, observed that the solver time on Haswell node is  better compared to GPU as well as KNL nodes. Therefore, I am not sure of integrating this code with a legacy code. 
So, I was looking for examples to solve the same. I found some of them where cloning is performed on the Tpetra objects (trilinoscouplings,    muelu/example/advanced, Xpetra, Zoltan2, ....) and solved the linear system on different devices.  But, could not compile them without errors. I also tried to compile the 05_solver example at tpetra/core/example/Lesson07-Kokkos-Fill. And, I am not successful in that.  I appreciate your advice on an appropriate example for my problem. Thank you. 
 

The script used to build Trilinos is  
``` 
module purge
module load cmake/3.4.3
module load gcc/4.9.3
module load openmpi/1.10.6/gcc/4.9.3/cuda/8.0.61
module load boost/1.62.0/openmpi/1.10.6/gcc/4.9.3/cuda/8.0.61
module load cuda/8.0.61
module load netcdf/4.4.1.1/openmpi/1.10.6/gcc/4.9.3/cuda/8.0.61
module load hdf5/1.10.0.p1/openmpi/1.10.6/gcc/4.9.3/cuda/8.0.61

export NVCC_WRAPPER_DEFAULT_COMPILER=/home/projects/x86-64-haswell/gcc/4.9.3/bin/g++
export OMPI_CXX=/home/vkkotte/Trilinos/src/packages/kokkos/config/nvcc_wrapper
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1

BOOSTDIR=$BOOST_ROOT
NETCDF=$NETCDF_ROOT 
HDF5DIR=$HDF5_ROOT
BLAS=/home/vkkotte/Trilinos/Software/lapack/install/
LAPACK=/home/vkkotte/Trilinos/Software/lapack/install/
BUILD_DIR=/home/vkkotte/Trilinos/install1

cmake -D CMAKE_INSTALL_PREFIX:PATH=$BUILD_DIR \
      -D CMAKE_BUILD_TYPE:STRING=RELEASE \
      -D CMAKE_C_COMPILER="mpicc" \
      -D CMAKE_CXX_COMPILER="mpicxx" \
      -D CMAKE_Fortran_COMPILER="mpif90" \
      -D BLAS_LIBRARY_NAMES:STRING="libblas.so.3" \
      -D BLAS_LIBRARY_DIRS:PATH=$BLAS/lib64 \
      -D BLAS_INCLUDE_DIRS:PATH=$BLAS/include \
      -D LAPACK_LIBRARY_NAMES:STRING="liblapack.so.3" \
      -D LAPACK_LIBRARY_DIRS:PATH=$LAPACK/lib64 \
\
      -D CMAKE_CXX_FLAGS="-std=c++11 --expt-extended-lambda -DKOKKOS_CUDA_USE_LAMBDA" \
      -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
      -D Trilinos_ENABLE_DEBUG:BOOL=OFF \
      -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
\
      -D TPL_ENABLE_MPI:BOOL=ON \
\
      -D TPL_ENABLE_Boost:BOOL=ON \
      -D TPL_ENABLE_BoostLib:BOOL=ON \
      -D Boost_INCLUDE_DIRS:FILEPATH=$BOOSTDIR/include \
      -D Boost_LIBRARY_DIRS:FILEPATH=$BOOSTDIR/lib \
      -D BoostLib_INCLUDE_DIRS:FILEPATH=$BOOSTDIR/include \
      -D BoostLib_LIBRARY_DIRS:FILEPATH=$BOOSTDIR/lib \
      -D TPL_ENABLE_HDF5:BOOL=ON \
      -D TPL_ENABLE_Netcdf:BOOL=ON \
      -D TPL_Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
      -D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
      -D HDF5_INCLUDE_DIRS:PATH=$HDF5DIR/include \
      -D HDF5_LIBRARY_DIRS:PATH=$HDF5DIR/lib \
      -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
      -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
      -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
      -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
      -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
\
      -D Trilinos_ENABLE_CXX11:BOOL=ON \
      -D Trilinos_ENABLE_Tpetra:BOOL=ON \
      -D Kokkos_ENABLE_Cuda:BOOL=ON \
      -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
      -D Kokkos_ENABLE_EXAMPLES:BOOL=OFF \
      -D Kokkos_ENABLE_OpenMP:BOOL=OFF \
      -D Kokkos_ENABLE_Pthread:BOOL=OFF \
      -D Kokkos_ENABLE_TESTS:BOOL=ON \
      -D Kokkos_ENABLE_DEBUG:BOOL=ON \
      -D TPL_ENABLE_CUDA:BOOL=ON \
\
      -D Trilinos_ENABLE_Amesos:BOOL=ON \
      -D Trilinos_ENABLE_Amesos2:BOOL=ON \
      -D Trilinos_ENABLE_Xpetra:BOOL=ON \
      -D Trilinos_ENABLE_Epetra:BOOL=ON \
      -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
      -D Trilinos_ENABLE_Zoltan:BOOL=OFF \
      -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
      -D Trilinos_ENABLE_Belos:BOOL=ON \
      -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
      -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
      -D Trilinos_ENABLE_MueLu:BOOL=ON \
      -D Trilinos_ENABLE_TESTS:BOOL=OFF \
      -D Trilinos_ENABLE_Teuchos:BOOL=ON \
      -D Trilinos_ENABLE_Stokhos:BOOL=ON \
      -D Tpetra_INST_CUDA:BOOL=ON \
      -D Trilinos_ENABLE_Kokkos:BOOL=ON \
/home/vkkotte/Trilinos/src
```

Thank you.

**Comment by mhoemmen** [comment] 2017-08-13 22:16
@kvmkrao Here are some tips and questions:
 
  1. If you are using MPI, don't set `CMAKE_C_COMPILER` or `CMAKE_CXX_COMPILER`.  If the MPI binaries (e.g., `mpicxx`) are in your PATH, then you only need to set `TPL_ENABLE_MPI:BOOL=ON`.  If they are not in your PATH, then it generally suffices to set `MPI_BASE_DIR` to the base directory of your MPI installation.
  2. Don't specify `CMAKE_CXX_FLAGS` explicitly.  Just delete that whole line from your configuration.
  3. Don't turn off OpenMP (`Trilinos_ENABLE_OpenMP` should be `ON`).
  4. If you just want to use Belos, Ifpack2, and Tpetra, you don't need any of the TPLs other than the BLAS and LAPACK.
  5. If you have already set `CMAKE_BUILD_TYPE=RELEASE`, then you don't need to set `Trilinos_ENABLE_DEBUG:BOOL=OFF`.  It's a release build; `Trilinos_ENABLE_DEBUG` defaults to `OFF` in that case.

Could you please also post a few of the build errors?

**Comment by mhoemmen** [comment] 2017-08-13 23:29
Oops, I must have let my access to Hansen slip; my login doesn't work.  I'll reapply, but in the meantime, you could try the White testbed; there are more GPUs on that one.  Let me know if you get the above build working on Hansen.

**Comment by kvmkrao** [comment] 2017-08-14 20:10
@mhoemmen Thanks a lot for your tips. 
I modified the configuration file as per your suggestions and it is as follows: 
( Modifications: 
1. The cmake options to specify the C_ and CXX_ compiler paths have been removed. 
2. Removed  CXX_FLAGS. 
3. Turned on OpenMP (Trilinos_ENABLE_OpenMP=ON). 
4. The TPLs used in this build are BLAS and Lapack. The packages considered in this build are Teuchos, Tpetra, Belos, Ifpack2 and Kokkos. 
5. only CMAKE_BUILD_RELEASE option is used in the configuration file. )

```
cmake -D CMAKE_INSTALL_PREFIX:PATH=$BUILD_DIR \
      -D CMAKE_BUILD_TYPE:STRING=RELEASE \
      -D BLAS_LIBRARY_NAMES:STRING="libblas.so.3" \
      -D BLAS_LIBRARY_DIRS:PATH=$BLAS/lib64 \
      -D BLAS_INCLUDE_DIRS:PATH=$BLAS/include \
      -D LAPACK_LIBRARY_NAMES:STRING="liblapack.so.3" \
      -D LAPACK_LIBRARY_DIRS:PATH=$LAPACK/lib64 \
      -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
      -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=ON \
      -D TPL_ENABLE_MPI:BOOL=ON \
      -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
      -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
      -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
      -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
\
      -D Trilinos_ENABLE_CXX11:BOOL=ON \
      -D Kokkos_ENABLE_Cuda:BOOL=ON \
      -D Kokkos_ENABLE_Cuda_UVM:BOOL=ON \
      -D Kokkos_ENABLE_OpenMP:BOOL=OFF \
      -D Kokkos_ENABLE_Pthread:BOOL=OFF \
      -D TPL_ENABLE_CUDA:BOOL=ON \
\
      -D Trilinos_ENABLE_Tpetra:BOOL=ON \
      -D Trilinos_ENABLE_Belos:BOOL=ON \
      -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
      -D Trilinos_ENABLE_OpenMP:BOOL=ON \
      -D Trilinos_ENABLE_Teuchos:BOOL=ON \
      -D Tpetra_INST_CUDA:BOOL=ON \
      -D Trilinos_ENABLE_Kokkos:BOOL=ON \
../src ```

There were no errors during the installation. So, I used this to compile the same code. And, it was observed that the compilation errors are same as in the previous comment. 

No problem. Thank you.  
I loaded gcc (5.4.0) and cuda (8.0.44) modules on white11 and installed the library. The installation was successful.  So, this build is used to compile the code. The compilation errors are same as on Hansen. 

Thank you.

**Comment by mhoemmen** [comment] 2017-08-14 22:07
```
with DstTraits=Kokkos::ViewTraits<const double *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, SrcTraits=Kokkos::ViewTraits<double **, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>]
```
Looks like you're trying to assign a 2-D Kokkos::View (`double**`) to a 1-D Kokkos::View (`const double*`).

**Comment by mhoemmen** [comment] 2017-08-14 22:11
I don't see that the line numbers in your posted file match those in `wrapTpetraSolver.cpp`, the file that you modified.  Could you repost or post a link?  

It looks like you got the build to work correctly on both Hansen and White, and the issue is in the example code that you modified.  Is that correct?

**Comment by kvmkrao** [comment] 2017-08-14 22:51
@mhoemmen 
I have added/modified some lines in wrapTpetraSolver.cpp. Therefore, there is a mismatch in line numbers in the actual code and the modified code. Please see the modified code attached with this comment. 

Correct @mhoemmen. I installed it without errors on Hansen as well as white. Yes, Sir. There is an issue with the modified code. Thanks. 
[wrapTpetraSolver_mod.txt](https://github.com/trilinos/Trilinos/files/1223666/wrapTpetraSolver_mod.txt)

**Comment by mhoemmen** [comment] 2017-08-14 23:28
@kvmkrao Thanks for posting the updated code.  Line 716 assigns `diag_d`, a 2-D Kokkos::View (see line 696 for the declaration of `diag_d`), to `diag_`, a 1-D Kokkos::View (see line 760 for the declaration of `diag_`).  You can't do that.  

It looks like you want `diag_` to store the local tridiagonal matrix.  This means that `diag_` must be a 2-D Kokkos::View (e.g., `View<const double**, device_type>`).

**Comment by mhoemmen** [comment] 2017-09-04 19:47
I think we answered the question, so I'll close this issue.  Please feel free to reopen if the question was not answered, or to open a new issue for a different question.  Thanks!

**Closed by mhoemmen** 2017-09-04 19:47 UTC
Labels: Kokkos, question, Tpetra
