### ISSUE TITLE
Intrepid2 or MueLu CUDA compile error

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1572] opened 2017-08-03 17:16 UTC
Builds for muelu are broken for cuda.
4 errors detected in the compilation of "/tmp/tmpxft_0001e136_00000000-7_MueLu_IntrepidPCoarsenFactory.cpp1.ii".

**Comment by ibaned** [comment] 2017-08-03 17:27
@trilions/muelu

**Comment by ibaned** [comment] 2017-08-03 17:27
@trilinos/muelu

**Comment by jhux2** [comment] 2017-08-03 18:18
@bathmatt I see the error on the EMPIRE jenkins dashboard.  Can you post or send the cmake configure for Trilinos?

**Comment by bathmatt** [comment] 2017-08-03 18:59
[bs.txt](https://github.com/trilinos/Trilinos/files/1198289/bs.txt)

This is a tar file.  Untar it and have workspace/Trilinos /workspace/BuildScripts 
export WORKSPACE=/path/to/workspace
export JOB_NAME=Trilinos-cuda-debug
 and then run the right build and test script for the different platforms.

**Comment by bathmatt** [comment] 2017-08-03 20:24
@jhux2 I don't really interact with gitlab since we blocked gmail here.  can you contact me directly at work with questions or comments?

**Comment by jhux2** [comment] 2017-08-03 20:28
@bathmatt Sure, will do.  My build is progressing on ride, I'm just waiting for the error.

**Comment by lucbv** [comment] 2017-08-03 20:42
@jhux2 could this be related to the error we see on the CDash? These error are related to a kokkos refactor inside intrepid2 which PCoarsen is using.

**Comment by jhux2** [comment] 2017-08-03 20:44
@lucbv Possibly, I will look.

**Comment by lucbv** [comment] 2017-08-03 20:50
Ok I am adding @mperego and @ndellingwood they should be able to shade light on this : )
[here](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3035658) is the CDash issue

**Comment by ibaned** [comment] 2017-08-03 21:52
Albany is also seeing this compile error [here](http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=57030).
@trilinos/intrepid2

**Comment by ndellingwood** [comment] 2017-08-03 22:07
Looking into the issue with @mperego

**Comment by ndellingwood** [comment] 2017-08-04 00:48
Broken with commit d0a772200f8ba721d1e78e680a18878c2ec0f260
Replicating some of the code modifications from that commit in a previous clean commit 094338dd9690bf57c05633c2fbea88df70e1e291 did not reproduce errors from cdash, still digging.

**Comment by mperego** [comment] 2017-08-04 14:11
@ndellingwood and I will try to fix this today. If we don't succeed we'll revert the offending commit.
@bathmatt @trilinos/muelu @ibaned let us know if you prefer to have the committed reverted right away.

**Comment by ibaned** [comment] 2017-08-04 14:26
@mperego fixed by the end of the day is fine with me, not critical

**Comment by ndellingwood** [comment] 2017-08-04 21:29
Got a fix passing tests (Cuda and Serial) with Cuda 7.5 + gcc 4.9.3 + OpenMPI 1.8.7; issued PR #1579, @ibaned is running checkin-test script on it now.

**Comment by ibaned** [comment] 2017-08-07 13:30
The pull request with the fix has been accepted by the checkin script. Please reopen if this particular issue persists.

**Closed by ibaned** 2017-08-07 13:30 UTC
Labels: Intrepid2, MueLu

**Comment by ndellingwood** [comment] 2017-08-07 16:29
Fix passed checkin testing by @ibaned, pushed as commit f170111.
@bathmatt @mperego @jhux2  is this safe to close now?

**Comment by ibaned** [comment] 2017-08-07 16:30
yep I did close it already

**Comment by ndellingwood** [comment] 2017-08-07 16:33
Thanks @ibaned! Forgot to refresh my browser and didn't see the message, I kept the issue up since Github emails don't come through consistently (though the PR one did).

**Comment by jhux2** [comment] 2017-08-07 16:54
> Fix passed checkin testing by @ibaned, pushed as commit f170111.
> @bathmatt @mperego @jhux2 is this safe to close now?

@ndellingwood Yes, thanks very much for your quick help.  The EMPIRE dashboard shows the builds working under CUDA, and the MueLu dashboard is clean as well under CUDA.
