### ISSUE TITLE
MueLu: MueLu_BlockedTransfer_Tpetra_MPI_4 broken on CI build

### ISSUE THREAD

**Issue by william76** [trilinos/Trilinos#1633] opened 2017-08-22 17:18 UTC
@trilinos/muelu 
@mayrmt 

MueLu_BlockedTransfer_Tpetra_MPI_4 is breaking as of yesterday (8/21) on the CI builds for both the ceerws and sadl machines.
- https://testing.sandia.gov/cdash/testDetails.php?test=40809776&build=3068338
- https://testing.sandia.gov/cdash/testDetails.php?test=40807106&build=3068045

Looks like blockedtransfer tests were enabled here(?) :
https://github.com/trilinos/Trilinos/commit/e995e6c5ca1b005eaf15e13b5d25ba898fd27907#diff-4c215a14b73d202d5f2530ac76e32f69

**Comment by jhux2** [comment] 2017-08-22 17:36
@william76 This test was moved out of experimental yesterday. It's been failing for a while there, so this isn't a new failure, just newly exposed.

**Comment by jhux2** [comment] 2017-08-22 20:24
@csiefer2

**Comment by bmpersc** [comment] 2017-08-24 15:29
@jhux2 @csiefer2 If this has been failing for a while in experimental shouldn't it be put back into experimental until it is passing? This is currently showing up on all of our continuous builds and has been for days.

**Comment by jhux2** [comment] 2017-08-24 15:31
@bmpersc @csiefer2 @tawiesn Agreed.  Today we'll either fix it, disable it, or move it back to experimental.

**Comment by csiefer2** [comment] 2017-08-25 14:27
Checkin test is baking on a fix.  I'd totally assign this to myself, but (unsurprisingly) github's web site doesn't work correctly.

**Comment by lucbv** [comment] 2017-08-25 15:02
@csiefer2 we need to have a talk about github ; )

**Comment by csiefer2** [comment] 2017-08-25 15:42
@lucbv : The problem is that github _chose_ not to support Firefox ESR, which means that random bits and pieces of the github website won't work on our windows browsers...

**Comment by lucbv** [comment] 2017-08-25 17:22
The latest build on [ceerws1113](https://testing.sandia.gov/cdash/buildSummary.php?buildid=3073563) is not failing on the test any more.

**Comment by csiefer2** [comment] 2017-08-25 17:52
Looks like we're good to go!

**Closed by csiefer2** 2017-08-25 17:52 UTC
Labels: bug, MueLu, tests
