### ISSUE TITLE
Compadre: Configuration errors with TRIBITS_ADD_ADVANCED_TEST

### ISSUE THREAD

**Issue by ndellingwood** [trilinos/Trilinos#10975] opened 2022-09-01 03:11 UTC
## Bug Report
@trilinos/compadre 

### Description
I encountered configure errors with Trilinos for an OpenMP build with gcc/9.5, cmake/3.23.2 on my Mac:

```
...
Processing enabled package: Compadre (Libs, Tests)
CMake Error at cmake/tribits/core/package_arch/TribitsAddAdvancedTest.cmake:1295 (message):
  Must have EXEC, CMND, or COPY_FILES_TO_TEST_DIR for TEST_0
Call Stack (most recent call first):
  packages/compadre/examples/CMakeLists.tribits.cmake:529 (TRIBITS_ADD_ADVANCED_TEST)
  packages/compadre/CMakeLists.txt:9 (include)
  packages/compadre/examples/CMakeLists.txt:1 (include_tribits_build)


-- Configuring incomplete, errors occurred!
See also "/Users/ndellin/Research/trilinos/Trilinos/Build/ConfigIssue/CMakeFiles/CMakeOutput.log".
See also "/Users/ndellin/Research/trilinos/Trilinos/Build/ConfigIssue/CMakeFiles/CMakeError.log".
```

### Steps to Reproduce
1. SHA1: 83e360dfdad394df2965fe10e29e960f2760513e
2. Configure: enabling compadre and its tests along with OpenMP should be sufficient (may occur with other backends as well)
```bash
cmake \
-D CMAKE_CXX_COMPILER:FILEPATH="`which g++`" \
-D CMAKE_C_COMPILER:FILEPATH="`which gcc`" \
-D CMAKE_Fortran_COMPILER:FILEPATH="`which gfortran`" \
-D Trilinos_ENABLE_OpenMP:BOOL=ON \
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH=${BLAS_PATH}/lib \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${LAPACK_PATH}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH=${LAPACK_PATH}/lib \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
-D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Kokkos_ENABLE_OPENMP:BOOL=ON \
  -D Kokkos_ENABLE_SERIAL:BOOL=ON \
-D Trilinos_ENABLE_Compadre:BOOL=ON \
 -D Compadre_ENABLE_TESTS:BOOL=ON \
$TRILINOS_DIR
```

**Comment by kuberry** [comment] 2022-09-01 21:26
It seems like this would have to be a CMake issue, right? I loaded CMake 3.23.2 (Linux) and can't reproduce.

**Comment by kuberry** [comment] 2022-09-14 18:35
@ndellingwood Is this still an issue?

**Comment by ndellingwood** [comment] 2022-09-14 19:46
@kuberry I'm still seeing the configuration error, I just tested with SHA f440ba5af62aa5fef631537c9f4b16cdf3e80174 
I'm on MacOS, using xcode command line tools version 13.4 and homebrew installs of gcc/9.5.0 cmake/3.24.1

**Comment by kuberry** [comment] 2022-09-15 13:26
@ndellingwood I'm running xcode command line tools 14.0, so can't reproduce your xcode setup. I did a brew install of gcc/9.5.0. CMake on brew is now 3.24.2. Would you mind updating and then letting me know if it is still an issue?

The advanced tests you are having an issue with have the line:
```
TEST_0 CMND ${PYTHON_EXECUTABLE}
```

and the configuration complaint is that there is no CMND given. Can you verify whether `PYTHON_EXECUTABLE` is defined?

**Comment by kuberry** [comment] 2022-09-15 13:27
If it turns out that `PYTHON_EXECUTABLE` isn't defined for you, I could add `PYTHON_EXECUTABLE` to the conditional before adding the test.

**Comment by ndellingwood** [comment] 2022-09-19 17:50
@kuberry it looks like `PYTHON_EXECUTABLE` is not defined for me, I added a message to output the variable to the examples/CMakeLists.txt and reconfigured i.e.:
```diff
diff --git a/packages/compadre/examples/CMakeLists.tribits.cmake b/packages/compadre/examples/CMakeLists.tribits.cmake
index c50a6e71ca6..18c79346c10 100644
--- a/packages/compadre/examples/CMakeLists.tribits.cmake
+++ b/packages/compadre/examples/CMakeLists.tribits.cmake
@@ -526,6 +526,7 @@ if (NOT(Compadre_DEBUG OR Compadre_EXTREME_DEBUG))
     @ONLY
     ) # end configure_file
   set(testName GMLS_Manifold_Multiple_Evaluation_Sites)
+  message("CHECK ON PYTHON_EXECUTABLE: ${PYTHON_EXECUTABLE}")
   TRIBITS_ADD_ADVANCED_TEST(
     ${testName}
     TEST_0 CMND ${PYTHON_EXECUTABLE} ARGS ${CMAKE_CURRENT_BINARY_DIR}/GMLS_Manifold_Multiple_Evaluation_Sites.py --porder=3 --grids=3 --in-trilinos=True
```

which gave output indicating it was not found:

```
CHECK ON PYTHON_EXECUTABLE: PYTHON_EXECUTABLE-NOTFOUND
CMake Error at cmake/tribits/core/package_arch/TribitsAddAdvancedTest.cmake:1295 (message):
  Must have EXEC, CMND, or COPY_FILES_TO_TEST_DIR for TEST_0
Call Stack (most recent call first):
  packages/compadre/examples/CMakeLists.tribits.cmake:530 (TRIBITS_ADD_ADVANCED_TEST)
  packages/compadre/CMakeLists.txt:9 (include)
  packages/compadre/examples/CMakeLists.txt:1 (include_tribits_build)
```

**Comment by kuberry** [comment] 2022-09-19 18:47
Ok, thanks @ndellingwood. This clears it up. I think the correct fix for this would be to add `PYTHON_EXECUTABLE` to the conditional that adds these tests. I'll make a PR.

**Closed** 2022-09-20 19:46 UTC
Labels: type: bug, pkg: Compadre
