### ISSUE TITLE
Intrepid2: 

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#8801] opened 2021-02-22 20:50 UTC
## Bug Report
@trilinos/intrepid2

### Description
The test ```Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1``` is failing in the develop->master candidate build for ats2. See https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=8752143

This needs to pass to complete #8129 

### Steps to Reproduce
SHA1: develop
Use the PR environment from cmake/std/sems/PullRequestCuda10.1.243TestingEnv.sh and instructions from https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

**Comment by mperego** [comment] 2021-02-23 21:17
@CamelliaDPG  I assigned you to this issue given that you are the most familiar with the failing test
`Intrepid2_unit-test_MonolithicExecutable_Intrepid2_Tests_MPI_1`
Let me know if you cannot look into this.

**Comment by CamelliaDPG** [comment] 2021-02-23 21:35
@mperego, yes, I can look into this.  @prwolfe, I'm puzzled by this; I've just been running the same set of tests on vortex without issue, on a fork that is for practical purposes the same as Trilinos develop.  But I will try a fresh pull from develop, and with the precise testing environment specified, and see if I can reproduce.

**Comment by CamelliaDPG** [comment] 2021-02-23 21:48
@prwolfe, which TestingSettings `.cmake` file should I be using?  I see `PullRequestLinuxCuda10.1.105TestingSettings.cmake` and `PullRequestLinuxCuda10.1.105uvmTestingSettings.cmake`, among others.

**Comment by CamelliaDPG** [comment] 2021-02-23 21:52
@prwolfe, also, I don't see `PullRequestCuda10.1.243TestingEnv.sh`.  I see `PullRequestCuda10.1.105TestingEnv.sh` and `PullRequestCuda10.1.105uvmTestingEnv.sh`.

**Comment by CamelliaDPG** [comment] 2021-02-23 22:48
@prwolfe, my apologies.  I had accidentally been working against master, not develop.  I now see `PullRequestCuda10.1.243TestingEnv.sh` and `PullRequestLinuxCuda10.1.243TestingSettings.cmake`.

**Comment by prwolfe** [comment] 2021-02-24 14:24
> @prwolfe, my apologies. I had accidentally been working against master, not develop. I now see `PullRequestCuda10.1.243TestingEnv.sh` and `PullRequestLinuxCuda10.1.243TestingSettings.cmake`.

Things happen ;->. It looks like this is still in the build from 4pm last night ( see https://testing.sandia.gov/cdash/build/8757099 ). I have this running every 12 hours and posting to Experimental. You can monitor there if you think it is intermittent.

**Comment by CamelliaDPG** [comment] 2021-02-26 20:05
@prwolfe, I believe I've fixed this in PR #8819.  (It's not intermittent, but as best as I can tell the issue is the compiler's fault.  #8819 is effectively a refactor that works around the misbehavior.)

**Comment by CamelliaDPG** [comment] 2021-03-03 16:48
@prwolfe, FYI, #8819 has now been merged.  It looks to me like the tests you linked to have not been running for the past week or so.  When they're back up and running, would you please check whether this issue is resolved?  Thanks!

**Comment by prwolfe** [comment] 2021-03-03 16:57
That job is still running. - a better query might be https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2021-03-01&end=now&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=pull&field2=groupname&compare2=63&value2=Experimental. One of them failed yesterday due to communication errors and this mornings had a filesystem issue so 1343 tests failed - lovely. I will watch this afternoons run and let you know what I see.

**Comment by prwolfe** [comment] 2021-03-09 17:06
I can confirm this has passed in the previous 2 builds and I am closing this. Thanks @CamelliaDPG!

**Comment by CamelliaDPG** [comment] 2021-03-09 17:18
Excellent.  Thanks, @prwolfe!

**Comment by prwolfe** [comment] 2021-04-19 20:43
It would appear that this issue has re-occured. The crash records only go back to April 4th, but I see failures every day since.

**Comment by CamelliaDPG** [comment] 2021-04-19 22:10
@prwolfe, thanks for letting us know.  I'll take a look, hopefully sometime in the next few days.

**Comment by mperego** [comment] 2021-04-19 22:25
@CamelliaDPG Thanks for looking into that. Apparently it started failing again after I merged PR #8966 .

**Comment by CamelliaDPG** [comment] 2021-04-19 22:29
Thanks, @mperego; I'll keep that in mind as a possible clue.

**Comment by CamelliaDPG** [comment] 2021-04-23 03:19
@prwolfe @mperego I believe #9044 will fix this.

**Closed** 2021-07-19 13:51 UTC
Labels: type: bug
