### ISSUE TITLE
Framework: PR testing should enable complex by default

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2426] opened 2018-03-20 17:37 UTC
PR (pull request) testing should enable complex by default.  This is because at least two major internal customers need complex arithmetic to work.

I know it takes longer to build but it seems like PR testing should test the most used build configurations.

@trilinos/framework @prwolfe @rrdrake @rppawlo

**Comment by bartlettroscoe** [comment] 2018-11-28 03:03
As the Intel build dominates the PR builds, the GCC 4.8.4 build could have complex enabled and it would not impact the total wall-clock time for PR testing.

**Comment by kddevin** [comment] 2019-01-15 22:04
Can addition of complex scalar types to at least some of the PR builds be made a high priority?
We have a growing number of users of complex scalars, and are seeing repeated issues from not including this in PR testing.
Thanks!
@jwillenbring @william76 @bartlettroscoe @trilinos/framework

**Comment by jmgate** [comment] 2019-01-15 22:07
This just bit Charon again earlier this week.

**Comment by jwillenbring** [comment] 2019-01-15 22:08
@kddevin 

@ZUUL42 - let's talk about this Monday at the standup. Please bring it up as a parking lot.

@mhoemmen - could you list exactly the option(s) this will require? Do all packages use the same complex option?

**Comment by bartlettroscoe** [comment] 2019-01-15 22:40
Adding `Trilinos_ENABLE_COMPLEX_DOUBLE=ON` should be done for one of the GCC PR builds but not all of the builds (and not the Intel build which is the current bottle-neck in build times).  We need to have at least one PR build with complex disabled because having the code work with complex enabled does not guarantee that it will work with complex disabled and there are critical customers (e.g. SPARC and EMPIRE) that don't enable complex.

So I would say add `Trilinos_ENABLE_COMPLEX_DOUBLE=ON` to either the gcc-4.8.4 or the gcc-7.2.0 build, but not both.

Agreed?

**Comment by mhoemmen** [comment] 2019-01-16 00:04
- Salinas developers are the only ones who need complex.  They claim that they likely only use `complex<double>`, not `complex<float>`.  @crdohrm can clarify exactly what Trilinos packages Salinas uses with complex numbers.
  - @theguruat12 is currently testing the Sierra build with various Trilinos complex options.
  - @kddevin A newer GCC version would likely build faster with complex enabled.
  - @bartlettroscoe Yes, please at least enable `complex<double>` in one build.  I will report if Sierra needs more than that.

Thanks all!

**Comment by jwillenbring** [comment] 2019-01-17 05:37
@mhoemmen @kddevin 

Do [these results](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4420045) look reasonable? If so, we would need to clean up these issues prior to making the change. If not, please advise as to how the build should be modified.

**Comment by mhoemmen** [comment] 2019-01-17 16:08
@jwillenbring Yes, we should clean up these issues before making the change.

**Comment by mhoemmen** [comment] 2019-01-17 16:09
@trilinos/tpetra @trilinos/muelu Hey, the tests are broken with complex enabled.

@kyungjoo-kim would you happen to know anything about that complex dot product?

**Comment by mhoemmen** [comment] 2019-01-17 17:23
I'm pretty sure I know what's wrong with the complex BLAS dot product in kokkos-kernels:

https://github.com/kokkos/kokkos-kernels/issues/360#issuecomment-455251898

We fixed this in Teuchos quite a while ago.  I'm pretty sure that the same solution would apply.

**Comment by ZUUL42** [comment] 2019-01-24 23:14
I noticed the associated PR for a few fixes, #4253 , was merged in. So, I kicked off another build with complex doubles enabled.
Here are [the updated results](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4453517). Looks like there are still a few issues that remain.

**Comment by ZUUL42** [comment] 2019-01-28 18:18
I kicked off a complex doubles enabled build on Friday evening after Issue #4263 / PR #4268 merged.
Looks like it builds w/o error, but there are still a few tests that fail for @trilinos/muelu & @trilinos/kokkos-kernels .
[Results as of Friday 01/25 evening](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4457963)

**Comment by bartlettroscoe** [comment] 2019-01-28 18:21
@lucbv, here is the GitHub issue for adding complex support testing to the Trilinos PR builds.  Hopefully this will answer your questions in https://github.com/trilinos/Trilinos/issues/4273#issuecomment-457957565.

**Comment by srajama1** [comment] 2019-01-28 18:33
@ndellingwood @kyungjoo-kim I thought complex was clean after the recent changes. May be this is a different path/blas etc.

**Comment by ndellingwood** [comment] 2019-01-28 18:40
@kyungjoo-kim did the complex fixes in kokkos-kernels get patched into Trilinos?

**Comment by kyungjoo-kim** [comment] 2019-01-28 18:42
no. it is not patched to trilinos. however, I did not see this error when i test it.

**Comment by srajama1** [comment] 2019-01-28 18:46
Can we apply that patch irrespective of this issue ? This new issue might block PR testing so we need to prioritize this.

**Comment by kyungjoo-kim** [comment] 2019-01-28 19:16
I don't think that the fix on kokkoskernels kokkos/kokkos-kernels#374 fixes this problem but kokkos/kokkos-kernels#373 might do fix the issue.

**Comment by kyungjoo-kim** [comment] 2019-01-28 19:20
BTW, if this error happens only some architecture only, kokkos/kokkos-kernels#374 should be aplied in order to detect a right fortran interface. I checked a bit and kokkoskernels has been already too much modified and it would be better snapshot the entire repo to trilinos.

**Comment by lucbv** [comment] 2019-01-29 14:46
@ZUUL42 thanks for updating the results. It looks like the failed tests in @trilinos/muelu are due to timeouts and old gold file that were not updated when interface changes occurred.
I will look into the gold file issues.

**Comment by ZUUL42** [comment] 2019-01-29 15:51
@ndellingwood I'm triggering a build manually for the job Trilinos_pullrequest_gcc_7.2.0 with trilinos/Trilinos/develop as the target branch and jwillenbring/Trilinos/complex_pr_test2 as the source branch. [The only line change enables complex doubles](https://github.com/trilinos/Trilinos/compare/develop...jwillenbring:complex_pr_test2).

**Comment by ndellingwood** [comment] 2019-01-29 17:19
Thanks @ZUUL42 , we'll use that info to reproduce the failure and get a patch into Trilinos.

**Comment by ndellingwood** [comment] 2019-01-29 23:31
I reproduced the failures on White with gcc/7.2 build and `complex<double>` enabled, also confirmed PR kokkos/kokkos-kernels#374 fix the issue (using the override configuration trick to test with the kokkos-kernels develop branch VOTD). If feasible we would like to fix this with the next kokkos + kokkos-kernels promotion, I'm going to run integration tests overnight and if things are in good shape we will follow through with the promotion; otherwise we will issue a patch to Trilinos.
@kyungjoo-kim @crtrott @srajama1

**Comment by ndellingwood** [comment] 2019-02-04 22:41
@ZUUL42  Kokkos+KokkosKernels promotion testing is nearly finished, hoping to snapshot into Trilinos in the next couple days. This will address the complex test problems in kokkos-kernels reported elsewhere in this issue. kokkos/kokkos#1981 is tracking promotion progress.

**Comment by lucbv** [comment] 2019-02-05 14:18
@mhoemmen, the complex build in MueLu is now clean, let us know if you see anything problematic during the trilinos promotion in Sierra

**Comment by lucbv** [comment] 2019-02-05 17:14
@mhoemmen feel free to close that issue, I feel it would be impolite for me to close it for you : )

**Comment by ndellingwood** [comment] 2019-02-06 00:52
PR #4329 issued with kokkos + kokkos-kernels promotion to v 2.8.00 which should address the complex failures in kokkos-kernels documented in this issue.

**Comment by ndellingwood** [comment] 2019-02-06 16:38
@ZUUL42 @jwillenbring @william76 PR #4329 merged into Trilinos develop, hope this fixes the last of the complex issues blocking the new PR test. Thanks for the hard work adding the complex build to the PR testing!

**Comment by jwillenbring** [comment] 2019-02-12 22:44
With #2426 merged, we can close this issue.

**Closed by jwillenbring** 2019-02-12 22:44 UTC
Labels: Framework
