### ISSUE TITLE
Framework: Still testing GCC 4.7.2 in Experimental Track

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#3670] opened 2018-10-18 21:45 UTC
Trilinos will not configure with a GCC that old.  Please shoot this test.

**Comment by mhoemmen** [comment] 2018-10-19 18:15
@trilinos/framework yes please, in fact this may be a duplicate of another issue

**Comment by jwillenbring** [comment] 2018-11-13 15:50
This test was removed yesterday and didn't show up on the dashboard today.

**Closed by jwillenbring** 2018-11-13 15:50 UTC
Labels: Framework
