### ISSUE TITLE
muelu: muelu/matlab/src/MueLu_MatlabUtils.cpp does not compile

### ISSUE THREAD

**Issue by branfosj** [trilinos/Trilinos#8813] opened 2021-02-24 21:33 UTC
## Bug Report
@trilinos/muelu

### Description
I'm trying to compile Trilinos 13.0.1 with MueLu and MATLAB support. Compilation is failing, as per the error below.

### Steps to Reproduce
The code is the 13.0.1 release with #7870 and #8227 applied.

* icc / ifort / imkl: 2019.5.281
* Boost 1.71.0
* MATLAB: 2020a

Configure:
```
cmake -DCMAKE_INSTALL_PREFIX=/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Trilinos/13.0.1-iomkl-2019b-MATLAB -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_C_COMPILER='icc' -DCMAKE_C_FLAGS='-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC' -DCMAKE_CXX_COMPILER='icpc' -DCMAKE_CXX_FLAGS='-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC' -DCMAKE_Fortran_COMPILER='ifort' -DCMAKE_Fortran_FLAGS='-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC' -DCMAKE_VERBOSE_MAKEFILE=ON -DBOOST_ROOT=/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Boost/1.71.0-iompi-2019b -DBoost_NO_SYSTEM_PATHS=ON -DBoost_NO_BOOST_CMAKE=ON  -DCMAKE_C_FLAGS="-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC"  -DCMAKE_CXX_FLAGS="-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC"  -DCMAKE_Fortran_FLAGS="-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC"  -DKokkos_ENABLE_SERIAL:BOOL=ON  -DTpetra_INST_SERIAL:BOOL=ON  -DTrilinos_ENABLE_OpenMP:BOOL=ON  -DKokkos_ENABLE_OPENMP:BOOL=ON  -DTpetra_INST_INT_INT:BOOL=ON  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON  -DMueLu_ENABLE_Tutorial:BOOL=OFF  -DTrilinos_ENABLE_MueLu:BOOL=ON  -DTPL_ENABLE_MATLAB:BOOL=ON  -DMATLAB_ARCH=glnxa64  -DMATLAB_ROOT=/rds/bear-apps/2019b/EL7-cascadelake/software/MATLAB/2020a  -DTrilinos_EXTRA_LINK_FLAGS="-lrt -lm -lgfortran"  -DTrilinos_ENABLE_EXAMPLES:BOOL=OFF  -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON  -DTPL_ENABLE_BLAS:BOOL=ON  -DBLAS_LIBRARY_DIRS="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/imkl/2019.5.281-iompi-2019b/mkl/lib/intel64"  -DBLAS_LIBRARY_NAMES="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5;pthread"  -DTPL_ENABLE_LAPACK:BOOL=ON  -DLAPACK_LIBRARY_DIRS="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/imkl/2019.5.281-iompi-2019b/mkl/lib/intel64"  -DLAPACK_LIBRARY_NAMES="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5;pthread"  -DTPL_ENABLE_MKL:BOOL=ON  -DMKL_LIBRARY_DIRS:PATH="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/imkl/2019.5.281-iompi-2019b/mkl/lib/intel64"  -DMKL_INCLUDE_DIRS:PATH="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/imkl/2019.5.281-iompi-2019b/mkl/include"  -DTPL_ENABLE_Boost:BOOL=ON  -DBoost_INCLUDE_DIRS:PATH="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Boost/1.71.0-iompi-2019b/include"  -DBoost_LIBRARY_DIRS:PATH="/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-cascadelake/software/Boost/1.71.0-iompi-2019b/lib"  -DTrilinos_ENABLE_TrilinosCouplings:BOOL=OFF  -DBUILD_SHARED_LIBS=ON  /dev/shm/build-branfosj-admin/branfosj-admin-1/Trilinos-GOQIj/src
make -j 40
```

Fails with
```
/dev/shm/build-branfosj-admin/branfosj-admin-1/Trilinos-GOQIj/src/packages/teuchos/core/src/Teuchos_RCP.hpp(297): error: a value of type "const Tpetra::Map<Tpetra::Details::DefaultTypes::local_ordinal_type={int}, Tpetra::Details::DefaultTypes::global_ordinal_type={int}, Tpetra::Details::DefaultTypes::node_type> *" cannot be used to initialize an entity of type "const Tpetra::Map<MueLu::mm_LocalOrd={Tpetra::Details::DefaultTypes::local_ordinal_type={int}},
          MueLu::mm_GlobalOrd={Tpetra::Details::DefaultTypes::global_ordinal_type={int}}, MueLu::mm_node_t> *"
    : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
           ^
          detected during instantiation of "Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2> &) [with T=const Tpetra::Map<MueLu::mm_LocalOrd={Tpetra::Details::DefaultTypes::local_ordinal_type={int}}, MueLu::mm_GlobalOrd={Tpetra::Details::DefaultTypes::global_ordinal_type={int}}, MueLu::mm_node_t>, T2=const Tpetra::Map<Tpetra::Details::DefaultTypes::local_ordinal_type={int}, Tpetra::Details::DefaultTypes::global_ordinal_type={int}, Tpetra::Details::DefaultTypes::node_type>]" at line 277 of
                    "/dev/shm/build-branfosj-admin/branfosj-admin-1/Trilinos-GOQIj/src/packages/muelu/matlab/src/MueLu_MatlabUtils_def.hpp"

compilation aborted for /dev/shm/build-branfosj-admin/branfosj-admin-1/Trilinos-GOQIj/src/packages/muelu/matlab/src/MueLu_MatlabUtils.cpp (code 2)
```

**Comment by mayrmt** [comment] 2021-02-24 21:36
@trilinos/muelu

**Comment by jhux2** [comment] 2021-02-24 21:59
@csiefer2

**Comment by csiefer2** [comment] 2021-03-01 15:58
Let me see if I can find a copy of Matlab 2020a...

**Comment by branfosj** [comment] 2021-03-01 17:16
I've done some further testing - I've removed Boost. I've also tested building with Matlab 2019b and Matlab 2018b. I see the same failure with both of those Matlab versions.

My current cmake command:
```
cmake -DCMAKE_INSTALL_PREFIX=../install-matlab2018b -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_C_COMPILER='icc' -DCMAKE_C_FLAGS='-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC' -DCMAKE_CXX_COMPILER='icpc' -DCMAKE_CXX_FLAGS='-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC' -DCMAKE_Fortran_COMPILER='ifort' -DCMAKE_Fortran_FLAGS='-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC' -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_FLAGS="-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC"  -DCMAKE_CXX_FLAGS="-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC"  -DCMAKE_Fortran_FLAGS="-O2 -xHost -fp-speculation=strict -fp-model strict -fPIC"  -DKokkos_ENABLE_SERIAL:BOOL=ON  -DTpetra_INST_SERIAL:BOOL=ON  -DTrilinos_ENABLE_OpenMP:BOOL=ON  -DKokkos_ENABLE_OPENMP:BOOL=ON  -DTpetra_INST_INT_INT:BOOL=ON  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON  -DMueLu_ENABLE_Tutorial:BOOL=OFF  -DTrilinos_ENABLE_MueLu:BOOL=ON  -DTPL_ENABLE_MATLAB:BOOL=ON  -DMATLAB_ARCH=glnxa64  -DMATLAB_ROOT=$EBROOTMATLAB  -DTrilinos_EXTRA_LINK_FLAGS="-lm"  -DTrilinos_ENABLE_EXAMPLES:BOOL=OFF -DTrilinos_ENABLE_Fortran:BOOL=OFF -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON  -DTPL_ENABLE_BLAS:BOOL=ON  -DBLAS_LIBRARY_DIRS="$EBROOTIMKL/mkl/lib/intel64"  -DBLAS_LIBRARY_NAMES="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5;pthread"  -DTPL_ENABLE_LAPACK:BOOL=ON  -DLAPACK_LIBRARY_DIRS="$EBROOTIMKL/mkl/lib/intel64"  -DLAPACK_LIBRARY_NAMES="mkl_intel_lp64;mkl_intel_thread;mkl_core;iomp5;pthread"  -DTPL_ENABLE_MKL:BOOL=ON  -DMKL_LIBRARY_DIRS:PATH="$EBROOTIMKL/mkl/lib/intel64"  -DMKL_INCLUDE_DIRS:PATH="$EBROOTIMKL/mkl/include"  -DTPL_ENABLE_Boost:BOOL=OFF  -DTrilinos_ENABLE_TrilinosCouplings:BOOL=OFF  -DBUILD_SHARED_LIBS=ON ../Trilinos-trilinos-release-13-0-1/
```

**Comment by csiefer2** [comment] 2021-03-02 23:18
Using Matlab 2020b, gcc 5.3.0 and lapack 3.4.0, everything builds and links just fine using today's Trilinos develop and my configure.

I suspect the problem is then specific to either (a) the MKL or (b) using the Intel compiler.  I've never tried it with either before, but I'll give it a go and report back.

**Comment by csiefer2** [comment] 2021-03-03 20:59
Things build and link Matlab 2020b, using Intel 17.0.1 (w/ gcc 5.3.0) as its backup with no MKL.

So I'm guessing MKL is the issue.

**Comment by branfosj** [comment] 2021-03-03 21:15
I've been doing some more testing. I can repeat the error with GCC and OpenBLAS - i.e. without MKL.

I've tested with code 1a61be2dc0378de70f515792f215889d6f449004 and latest develop (93c8bfe3dd655f2251c8a89461d6d1091fee6e93):
* GCC 10.2
* OpenBLAS 0.3.12
* MATLAB 2020a

CMake:
```
cmake -DCMAKE_INSTALL_PREFIX=../install-gcc -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER='gcc' -DCMAKE_C_FLAGS='-fPIC' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_CXX_FLAGS='-fPIC' -DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_Fortran_FLAGS='' -DCMAKE_VERBOSE_MAKEFILE=ON -DKokkos_ENABLE_SERIAL:BOOL=ON  -DTpetra_INST_SERIAL:BOOL=ON  -DTrilinos_ENABLE_OpenMP:BOOL=ON  -DKokkos_ENABLE_OPENMP:BOOL=ON  -DTpetra_INST_INT_INT:BOOL=ON  -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON  -DMueLu_ENABLE_Tutorial:BOOL=OFF  -DTrilinos_ENABLE_MueLu:BOOL=ON  -DTPL_ENABLE_MATLAB:BOOL=ON  -DMATLAB_ARCH=glnxa64  -DMATLAB_ROOT=$EBROOTMATLAB  -DTrilinos_EXTRA_LINK_FLAGS="-lm"  -DTrilinos_ENABLE_EXAMPLES:BOOL=OFF -DTrilinos_ENABLE_Fortran:BOOL=OFF -DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON  -DTPL_ENABLE_BLAS:BOOL=ON  -DBLAS_LIBRARY_DIRS="$EBROOTOPENBLAS/lib"  -DBLAS_LIBRARY_NAMES="openblas"  -DTPL_ENABLE_LAPACK:BOOL=ON  -DLAPACK_LIBRARY_DIRS="$EBROOTOPENBLAS/lib"  -DLAPACK_LIBRARY_NAMES="openblas" -DTPL_ENABLE_Boost:BOOL=OFF  -DTrilinos_ENABLE_TrilinosCouplings:BOOL=OFF -DBUILD_SHARED_LIBS=ON ../Trilinos
```

Error:
```
In file included from /rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/tpetra/classic/NodeAPI/Kokkos_DefaultNode.hpp:48,
                 from /rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/muelu/src/Headers/MueLu_ConfigDefs.hpp:54,
                 from /rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp:50,
                 from /rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_def.hpp:50,
                 from /rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils.cpp:46:
/rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp: In instantiation of ‘Teuchos::RCP<T>::RCP(const Teuchos::RCP<T2>&) [with T2 = const Tpetra::Map<>; T = const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >]’:
/rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/muelu/matlab/src/MueLu_MatlabUtils_def.hpp:277:120:   required from here
/rds/projects/2017/branfosj-rse/ProblemSolving/tril/Trilinos/packages/teuchos/core/src/Teuchos_RCP.hpp:297:19: error: cannot convert ‘const Tpetra::Map<>*’ to ‘const Tpetra::Map<int, int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >*’ in initialization
  297 |   : ptr_(r_ptr.get()), // will not compile if T is not base class of T2
      |          ~~~~~~~~~^~
      |                   |
      |                   const Tpetra::Map<>*
```

**Comment by csiefer2** [comment] 2021-03-03 21:21
Oh.  I see it now.  The matlab interface (as written) only works with the Kokkos::Serial node type, not Kokkos::OpenMP.

**Comment by branfosj** [comment] 2021-03-03 21:54
Thanks! That was the problem - I've successfully built Trilinos.

**Comment by csiefer2** [comment] 2021-03-03 21:54
Cool!

**Comment by cgcgcg** [comment] 2021-12-01 19:34
Closing as fixed. Please reopen if necessary.

**Closed by cgcgcg** 2021-12-01 19:34 UTC
Labels: type: bug, pkg: MueLu
