### ISSUE TITLE
No Trilinos checkin emails

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#2029] opened 2017-11-29 01:57 UTC
I haven't received any Trilinos checkin emails since November 22nd.

@trilinos/framework 
@bmpersc

**Comment by bartlettroscoe** [comment] 2017-11-29 13:40
Same for me

**Comment by dridzal** [comment] 2017-11-30 01:30
Would providing github with a different email address solve these problems?  An email address associated with a non-Sandia server that does not reject email.

**Comment by bmpersc** [comment] 2017-11-30 16:24
@dridzal the email we are using is not on a Sandia machine. It is on the trilinos.org server. This issue is actually different than the throttling issue for notifications. I don't know all the specifics, but it has to do with the mailman server on trilinos.org. I know that the issue is being looked into, but I don't know what the status of it is.

**Comment by jwillenbring** [comment] 2017-11-30 16:34
John P is looking into this and hopes to have it fixed by the end of the day.

**Comment by jwillenbring** [comment] 2017-12-01 16:36
This should now be resolved. Please close if it isn't. It was a problem with the server trying to use the wrong mail protocol.

**Comment by jhux2** [comment] 2017-12-01 17:31
@jwillenbring Thanks!

**Comment by jhux2** [comment] 2017-12-04 20:41
I'm still not receiving any checkin emails.

**Comment by bartlettroscoe** [comment] 2017-12-05 02:19
I just checked and I can confirm that I am not getting any checking emails since 11/22/2017 either.

**Closed** 2021-06-02 13:10 UTC
Labels: CLOSED_DUE_TO_INACTIVITY, Framework tasks, MARKED_FOR_CLOSURE
