### ISSUE TITLE
Use fence() instead of CUDA_LAUNCH_BLOCKING=1 in Tpetra

### ISSUE THREAD

**Issue by ambrad** [trilinos/Trilinos#217] opened 2016-03-16 16:33 UTC
My understanding is that, right now, we need to set CUDA_LAUNCH_BLOCKING=1 to use Tpetra and possibly other Trilinos packages on the GPU.

This flag synchronizes launch of kernels; that is, one kernel launches and completes, and then the next does.

In application development, we'd like to avoid that for two reasons.

First, we'd like to run with Tpetra but test that our own application code does not have a race condition between kernels. I believe blocking is being forced on the app by that env var, so that means we can't test for a race condition in our own code.

I'm not sure what effect the CUDA_LAUNCH_BLOCKING flag has in the case of having multiple GPUs per node. But, second, we'll certainly want to make sure we can have multiple kernels launched from one MPI rank running simultaneously across GPUs on a node.

I believe the proper fix for this is to track down places in Tpetra where fence() needs to be used. Once fence() is used in all the right spots, then CUDA_LAUNCH_BLOCKING can be set to 0.

**Comment by mhoemmen** [comment] 2016-03-17 07:10
@ambrad Sorry about not getting to this sooner.  I was out of internet access for a few days.

@crtrott -- I recall that CUDA_LAUNCH_BLOCKING=1 has something to do with UVM.  Is that right?

**Comment by crtrott** [comment] 2016-03-17 16:44
Ok the issue is that you can not access any UVM allocations on the host after a kernel was launched, until a fence is reached. If you do you get a segfault. CUDA_LAUNCH_BLOCKING=1 auto fences all kernel executions. The correct solution is to fence in the right places. But that is probably a lot. Also technically the place where you want to fence, is not the place of kernel implementation, but the next point of possible data access on the host. Furthermore you can't really get data races between kernel launches at the moment. If you simply execute in the same execution space (instance) then kernels are executed serially. We need to implement execution space instances to allow concurrent kernel execution. The only exception right now are for example Cuda+OpenMP kernel. But again you can't have data races currently since they are not allowed to access a common memory space (with UVM you get segfault as described above).

**Comment by nmhamster** [comment] 2016-03-17 16:47
Can we auto-fence in the CUDA backend if UVM is in use so this issue goes away?

**Comment by crtrott** [comment] 2016-03-17 16:57
You can actually still write code which doesn't use UVM memory even if you set the default memory space in Kokkos to UVM. And if we auto-fence than it is not different than setting the environment variable. Andrew specifically does NOT want any kind of auto-fence.

**Comment by ambrad** [comment] 2016-03-17 18:16
> Furthermore you can't really get data races between kernel launches at the moment.

@crtrott , I thought serialization of kernel launch+run applies to reduction and perhaps scan only. I have the impression that parfor kernel launches are serialized but the *run* of the kernels is parallel. Hence the following race condition I thought could happen:

launch parfor kernel to produce data A
fence?
launch parfor kernel to produce data B that depends on data A

If there is no fence, then B likely uses the wrong data. My understanding is that CUDA_LAUNCH_BLOCK=1 will serialize the runs of these kernels, and CUDA_LAUNCH_BLOCK=0 will let them run simultaneously.

**Comment by crtrott** [comment] 2016-03-17 18:33
No this is not the case. Since we only submit to a single cuda stream in the cuda backend, kernels will NOT overlap. A single stream is supposed to be serial execution. In order to overlap kernels you need to submit them to different streams. This is on our medium term plan, but requires the implementation of Execution Space instances. The only place we use different streams right now is for asynchronous men copies.

**Comment by ambrad** [comment] 2016-03-17 19:04
OK, thanks all. I'm going to close this issue, then. There's no need to have the capability to run with CUDA_LAUNCH_BLOCKING=0 until kernels can run simultaneously.

**Comment by mhoemmen** [comment] 2016-03-18 01:16
@ambrad If OK with you, I'm reopening this, just so users can see it ("it crashed!", read issues, see this, apply palm to forehead).  Feel free to close again if it really should stay closed.

**Comment by mhoemmen** [comment] 2016-03-18 01:18
> Also technically the place where you want to fence, is not the place of kernel implementation, but the next point of possible data access on the host.

We could take care of some of that with DualView, but only if we hide the actual Views and only expose them through calling a method (that fences on first host access).  That wouldn't take care of plain-old Views though.

**Comment by mhoemmen** [comment] 2016-05-03 00:07
https://github.com/kokkos/kokkos/issues/230 should fix this, so I'll close it here.

**Closed by mhoemmen** 2016-05-03 00:07 UTC
Labels: Tpetra
