### ISSUE TITLE
Issue with building against installed Trilinos: can't find Kokkos headers

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#13639] opened 2024-11-30 19:53 UTC
It looks like Teuchos_ScalarTraits.hpp may be including an obsolete Kokkos header, Kokkos_Complex.hpp: 

```
/nightlyAlbanyTests/Results/Trilinos/build/install/include/Teuchos_ScalarTraits.hpp:27:10: fatal error: Kokkos_Complex.hpp: No such file or directory
```
This is causing some failures in our Albany nightlies: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=313841 

@trilinos/teuchos 
@trilinos/kokkos

**Comment by cgcgcg** [comment] 2024-12-02 22:38
I built Trilinos with complex enabled. I can confirm that the installation does not have `Kokkos_Complex.hpp`, but the header is present in the source tree.

**Comment by bartlettroscoe** [comment] 2024-12-02 23:03
CC: @ndellingwood, @masterleinad 

> Actually, the header is also present in the installation, in the subfolder `include/kokkos`.

Sounds like the `#include` in `Teuchos_ScalarTraits.hpp` needs to be updated to be:

```
#include "kokkos/Kokkos_Complex.hpp"
```

But how would that work from the source tree for Kokkos and Teuchos?

**Comment by dalg24** [comment] 2024-12-02 23:06
No that's a build and/or install issue.  It is intended to work as `#include <Kokkos_Complex.hpp>` if you link against the Kokkos::kokkos target.

**Comment by masterleinad** [comment] 2024-12-02 23:08
There are a bunch of uses in `Trilinos`:
```
$ git grep -n 'Kokkos_Complex.hpp'
packages/kokkos-kernels/batched/KokkosBatched_Util.hpp:50:#include "Kokkos_Complex.hpp"
packages/kokkos-kernels/batched/dense/impl/KokkosBatched_Vector_SIMD_Arith.hpp:21:#include "Kokkos_Complex.hpp"
packages/kokkos-kernels/batched/dense/impl/KokkosBatched_Vector_SIMD_Logical.hpp:21:#include "Kokkos_Complex.hpp"
packages/kokkos-kernels/batched/dense/impl/KokkosBatched_Vector_SIMD_Math.hpp:21:#include "Kokkos_Complex.hpp"
packages/kokkos-kernels/batched/dense/impl/KokkosBatched_Vector_SIMD_Misc.hpp:21:#include "Kokkos_Complex.hpp"
packages/kokkos-kernels/batched/dense/impl/KokkosBatched_Vector_SIMD_Relation.hpp:21:#include "Kokkos_Complex.hpp"
packages/kokkos-kernels/batched/dense/src/KokkosBatched_Vector_SIMD.hpp:21:#include <Kokkos_Complex.hpp>
packages/kokkos-kernels/common/src/Kokkos_ArithTraits.hpp:26:#include <Kokkos_Complex.hpp>
packages/kokkos-kernels/common/unit_test/Test_Common_Sorting.hpp:29:#include <Kokkos_Complex.hpp>
packages/kokkos-kernels/sparse/unit_test/Test_Sparse_SortCrs.hpp:32:#include <Kokkos_Complex.hpp>
packages/kokkos/CHANGELOG.md:1262:- Get rid of SYCL workaround in Kokkos_Complex.hpp [\#3884](https://github.com/kokkos/kokkos/pull/3884)
packages/kokkos/algorithms/src/Kokkos_Random.hpp:25:#include <Kokkos_Complex.hpp>
packages/kokkos/core/src/Kokkos_Core.hpp:69:#include <Kokkos_Complex.hpp>
packages/kokkos/core/src/Kokkos_MathematicalSpecialFunctions.hpp:31:#include <Kokkos_Complex.hpp>
packages/kokkos/core/unit_test/TestComplex.hpp:20:// The suppression needs to happen before Kokkos_Complex.hpp is included to be
packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp:19:#include "Kokkos_Complex.hpp"
packages/teuchos/core/src/Teuchos_ScalarTraits.hpp:27:#include "Kokkos_Complex.hpp"
packages/tpetra/core/src/Tpetra_BlockView.hpp:23:#include "Kokkos_Complex.hpp"
packages/tpetra/core/src/Tpetra_ConfigDefs.hpp:227:#include <Kokkos_Complex.hpp>
packages/tpetra/core/src/Tpetra_Details_Blas.hpp:23:#include "Kokkos_Complex.hpp"
packages/tpetra/core/src/Tpetra_Details_MpiTypeTraits.hpp:40:#include "Kokkos_Complex.hpp"
packages/tpetra/tsqr/src/Tsqr_NodeTsqrFactory.hpp:23:#  include "Kokkos_Complex.hpp"
```

**Comment by dalg24** [comment] 2024-12-02 23:11
I expected that our Trilinos nightlies against Kokkos develop included some sort of smoke tests that involved an install of Trilinos...

**Comment by dalg24** [comment] 2024-12-02 23:14
Does the Trilinos CI not test against an install?!

**Comment by crtrott** [comment] 2024-12-02 23:26
It does not.

**Comment by crtrott** [comment] 2024-12-02 23:29
@bartlettroscoe no it shouldn't be included that way. If you build against an external Kokkos you will need to include it as just "Kokkos_Complex.hpp".

**Comment by ndellingwood** [comment] 2024-12-02 23:38
> I expected that our Trilinos nightlies against Kokkos develop included some sort of smoke tests that involved an install of Trilinos...

@dalg24 some of our nightlies build and test [`${TRILINOS_DIR}/demos/simpleBuildAgainstTrilinos`](https://github.com/trilinos/Trilinos/tree/master/demos/simpleBuildAgainstTrilinos) against an install of Trilinos , but the issue was not picked up with that test

**Comment by ndellingwood** [comment] 2024-12-02 23:50
Possibly related https://github.com/sandialabs/Albany/pull/1095 ?
They mention "Kokkos_INSTALL_DIR was being set by the Kokkos Tribits build system which is no longer supported", and @cgcgcg [comment](https://github.com/trilinos/Trilinos/issues/13639#issuecomment-2513118509) pointed out the `include/kokkos` subfolder in the install dir, which seems like similar behavior

**Comment by cgcgcg** [comment] 2024-12-03 14:13
I reverted to before the latest Kokkos promotion and Kokkos include files are installed in the `include/` folder, not in `include/kokkos/`.

**Comment by masterleinad** [comment] 2024-12-03 15:11
> I reverted to before the latest Kokkos promotion and Kokkos include files are installed in the `include/` folder, not in `include/kokkos/`.

I am seeing
```
$ninja install
[0/1] Install the project...
-- Install configuration: "RELEASE"
-- Installing: /tmp/trilinos-install/./TrilinosRepoVersion.txt
-- Installing: /tmp/trilinos-install/lib/external_packages/DLlib/DLlibConfig.cmake
-- Installing: /tmp/trilinos-install/lib/external_packages/DLlib/DLlibConfigVersion.cmake
-- Installing: /tmp/trilinos-install/include/Trilinos_version.h
-- Installing: /tmp/trilinos-install/include/Trilinos_version_date.h
-- Up-to-date: /tmp/trilinos-install/include/kokkos
-- Up-to-date: /tmp/trilinos-install/include/kokkos/Kokkos_HostSpace.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/Kokkos_Core.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/Kokkos_CopyViews.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Traits.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_CPUDiscovery.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_ParseCommandLineArgumentsAndEnvironmentVariables.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Profiling_C_Interface.h
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Default_Graph_Impl.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Stacktrace.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_NvidiaGpuArchitectures.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_SharedAlloc.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_ChaseLev.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskBase.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_HostSharedPtr.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Command_Line_Parsing.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Tools_Generic.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskPolicyData.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskQueue_impl.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_MultipleTaskQueue.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_StringManipulation.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_BitOps.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskNode.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Tools.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Half_MathematicalFunctions.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/KokkosExp_IterateTileGPU.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskResult.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_SimpleTaskScheduler.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_SingleTaskQueue.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_InitializationSettings.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Volatile_Load.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_ConcurrentBitset.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/KokkosExp_Host_IterateTile.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Default_Graph_fwd.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskQueueMultiple.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_LIFO.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Profiling_Interface.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_GraphImpl_fwd.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Utilities.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_GraphImpl.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_OptionalRef.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_HostBarrier.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_TaskQueueMemoryManager.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_LinkedListNode.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_ExecSpaceManager.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_QuadPrecisionMath.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Default_GraphNode_Impl.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_ZeroMemset_fwd.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_Default_GraphNodeKernel.hpp
-- Up-to-date: /tmp/trilinos-install/include/kokkos/impl/Kokkos_GraphImpl_Utilities.hpp
[...]
```
with latest `develop` but also
```
[...]
set_target_properties(Kokkos::kokkoscore PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<COMPILE_LANGUAGE:CXX>:KOKKOS_DEPENDENCE>"
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:CXX>:>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/kokkos"
  INTERFACE_LINK_LIBRARIES "Kokkos::LIBDL"
  INTERFACE_LINK_OPTIONS "\$<\$<LINK_LANGUAGE:CXX>:-DKOKKOS_DEPENDENCE>"
)
[...]
```
as long as `Trilinos` and downstream apps properly use `target_link_libraries`, `/tmp/trilinos-install/include/kokkos` should be an include directory when compiling.

**Comment by bartlettroscoe** [comment] 2024-12-03 17:53
CC: @dalg24 

@ikalash, how is the customer build system pulling in Trilinos libraries?  It is using modern CMake so that the include directories will be passed along using the interface target properties after calling `find_package(Trilinos)` (or better, `find_package(<Package1>)`, `find_package(<Package2>)`, ...).?

Otherwise, we would need to examine the `CMakeLists.txt` files in the downstream project, the installed `<Package>Config.cmake` files, and the full build line (showing the include directories on the compile line) to see what is happening.

**Comment by ikalash** [comment] 2024-12-03 18:06
@bartlettroscoe : you will find the CMakeLists.txt file for the code here https://github.com/E3SM-Project/cism-piscees/blob/ali_interface/CMakeLists.txt .  It is dated by probably a decade or so...

**Comment by masterleinad** [comment] 2024-12-03 18:17
> you will find the CMakeLists.txt file for the code here [E3SM-Project/cism-piscees@`ali_interface`/CMakeLists.txt](https://github.com/E3SM-Project/cism-piscees/blob/ali_interface/CMakeLists.txt) . It is dated by probably a decade or so...

That repository doesn't seem to be public.

**Comment by bartlettroscoe** [comment] 2024-12-03 19:07
> > you will find the CMakeLists.txt file for the code here [E3SM-Project/cism-piscees@`ali_interface`/CMakeLists.txt](https://github.com/E3SM-Project/cism-piscees/blob/ali_interface/CMakeLists.txt) . It is dated by probably a decade or so...
> 
> That repository doesn't seem to be public.

I can't view that repo either.

**Comment by ikalash** [comment] 2024-12-03 19:31
Sorry about that, I forgot that the repo is not public.  I have attached the CMakeLists.txt file.

[CMakeLists.txt](https://github.com/user-attachments/files/17997946/CMakeLists.txt)

**Comment by crtrott** [comment] 2024-12-03 20:48
Note this minimal CMake example works perfectly fine:

```
# Kokkos minimally requires 3.16 right now,
# but your project can set it higher
cmake_minimum_required(VERSION 3.16)

# Projects can safely mix languages - must have C++ support
# Kokkos flags will only apply to C++ files
project(Example CXX)

# Look for an installed Kokkos
find_package(Trilinos REQUIRED)

add_executable(example main.cpp)

# This is the only thing required to set up compiler/linker flags
target_link_libraries(example Kokkos::kokkos)
```

**Comment by crtrott** [comment] 2024-12-03 20:51
I renamed the title of the issue. It's clearly not an obsolete include, but a problem with building something against an installed Trilinos. And the issue seems to be some outdated way of defining dependencies (or not defining them for that matter).

**Comment by ikalash** [comment] 2024-12-03 20:55
Thank you for renaming the issue.  My original title of the issue was based on a conjecture.

**Comment by crtrott** [comment] 2024-12-04 00:16
@ikalash btw. I (and others) believe this is really a downstream issue, where Trilinos is not correctly consumed by E3SM/Albany. I.e. the cmake on the user side needs to be fixed. It just happened to work before, but wasn't following proper cmake usage.

**Comment by ikalash** [comment] 2024-12-04 00:18
@crtrott : you are probably right on this.  Would someone with cmake expertise (e.g., @bartlettroscoe ) be available to help me figure out how to fix the CMakeLists.txt logic.  I am not the original author of the cmake build system for this code, and it is pretty old.

**Comment by crtrott** [comment] 2024-12-04 00:24
We probably can identify someone tomorrow.

**Comment by ikalash** [comment] 2024-12-04 00:26
@crtrott sounds great, thank you!

**Comment by bartlettroscoe** [comment] 2024-12-13 19:07
Actually, the equivalent simple CMake file for Trilinos is:

```
# Kokkos minimally requires 3.16 right now,
# but your project can set it higher
cmake_minimum_required(VERSION 3.16)

# Projects can safely mix languages - must have C++ support
# Kokkos flags will only apply to C++ files
project(Example CXX)

# Look for an installed Kokkos
find_package(Trilinos REQUIRED)

add_executable(example main.cpp)

# This is the only thing required to set up compiler/linker flags
target_link_libraries(example Trilinos::all_libs)
```

**Comment by rppawlo** [comment] 2024-12-13 21:14
@dsjense

**Comment by bartlettroscoe** [comment] 2024-12-17 21:15
FYI: The issue was that there were some intermediate library targets in the customer's app that did not link to the Trilinos libraries, and therefore did not get the updated Kokkos include dirs from the imported Kokkos library targets (pulled in from `find_package(Kokkos)`).  Only the final exectuable was linking against the Trilinos libraries.  Once the proper target_link_libraries() commands were called, the Kokkos include dirs were added to the object file compile lines and the full app built and the tests ran.

If anyone has any questions about this, please let me know.

Otherwise, we can now close this issue :-)

**Closed by bartlettroscoe** 2024-12-17 21:15 UTC
Labels: type: bug, pkg: Teuchos, client: Albany
