### ISSUE TITLE
MueLu: Utilities_kokkos Cuthill McKee failing w/o UVM

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#10012] opened 2021-12-13 21:36 UTC
These two tests in MueLu are failing on our non-UVM nightly test builds:

The following tests FAILED:
    66. Utilities_kokkos_double_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_CuthillMcKee_UnitTest ... 
    81. Utilities_kokkos_std_complex0double0_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_CuthillMcKee_UnitTest ... 

[Test link here](https://testing.sandia.gov/cdash/test/108095534)

**Comment by jhux2** [comment] 2021-12-13 23:29
This looks to be a duplicate of #9988.

**Comment by cgcgcg** [comment] 2022-03-03 20:12
Fixed by #10027.

**Closed by cgcgcg** 2022-03-03 20:12 UTC
Labels: type: bug, pkg: MueLu
