### ISSUE TITLE
ifpack2: Nalu diffs due to Trilinos update

### ISSUE THREAD

**Issue by wjhorne** [trilinos/Trilinos#8985] opened 2021-04-07 15:41 UTC
Nalu (@spdomin)  regression testing now fails due to recent Trilinos updates. The first commit that appears to cause issues is

commit - 5454d52b2500eb3311cba6195e319585067c41e7
date      - Feb 19, 2021
Author. - Brian Kelley (@brian-kelley) 

In addition to producing diffs in our tests we have also noticed a new speedup of roughly 30% for a few of our test cases. 

I have placed a bisection result below between the most recent build and the last non-diffing Trilinos build below.

git bisect start
bad: [64d50199f342860b00d16cb78cb5730de66438b9] Merge Pull Request #8978 from trilinos/Trilinos/master_merge_20210406_000559
good: [021a3e21e987635dde87b51ec95b76038689046f] Merge pull request #8699 from seheracer/fix8540
bad: [c9463736612768471137eddeff9e8461efff9193] Merge Pull Request #8804 from trilinos/Trilinos/tpetra_8794_new
good: [484d903abb81f84161ceeef767b6abeb68ce5eb3] AmesosEpetra and Ifpack2.
bad: [d7993ee5ad57327889139b17d753d8d0b8086df7]  Oops
good: [ab5db9493fe2482c50828d29b4cd6e0a5c7ce4ae] Merge Pull Request #8780 from jwillenbring/Trilinos/issue-8391
bad: [817210a252363d023f58c6a167e7d6ec93d943a7] Merge Pull Request #8786 from kuberry/Trilinos/develop
bad: [7f6152a8533d088aae82ca59dc6b856208449de3] Use cached MV to replace getColumnMapMV from CrsMatrix
bad: [884cbc63baef4a1093e7745af6b15725285976cf] Reduce redundant code in CRS (GS/SGS use same fn)
good: [32ae214841e8ba8e8428eddec03edef99ac2ec8a] Moved BlockCrs GS functionality into Relaxation
bad: [5454d52b2500eb3311cba6195e319585067c41e7] Enabled new local GS code for CRS

First bad commit: [5454d52b2500eb3311cba6195e319585067c41e7] Enabled new local GS code for CRS

**Comment by brian-kelley** [comment] 2021-04-07 15:50
@wjhorne Is there a reproducer I can build? Is the test just getting the wrong answer/increased iterations from a GS/SGS Relaxation preconditioned solve?

**Comment by wjhorne** [comment] 2021-04-07 16:00
The latest Nalu build ( bebc794eb6a7b30a2db82791c435e01305ba9645 ) will reproduce the issue. The regression test case "dgNonConformalThreeBlade" is the case used to produce the bisection I sent before. 

I will check the number of iterations and will get back to you in just a moment. There is not a matrix/RHS dump that I have readily available.

**Comment by wjhorne** [comment] 2021-04-07 16:20
Looking through the logs I do not see changes in the number of iterations. It appears that only the residuals have slightly changed.

**Comment by spdomin** [comment] 2021-04-07 17:09
Most of our Nalu regression tests are sensitive to order-of-ops changes - for a reason. We have a test that checks for formal order of accuracy to establish correctness of a result, however, in our algorithm the nonlinear solution is reached despite minor tweaks in a, e.g., preconditioner.

Let us know the nature of your changes and if you feel confident in the correctness - possibly some sort of unit test you ran on your side to help. 

I can fire up a verification test to make sure we still see design-order convergence later today or tomorrow.

**Comment by brian-kelley** [comment] 2021-04-07 17:17
@spdomin Ifpack2 does test this code, but not to a very tight tolerance like this. Symbolically the new version of GS/SGS should be exactly equivalent to the old version - I think the only differences are from nonassociativity of float addition. I'm building Nalu to see what the differences look like. It may be possible to get back to bitwise equivalence with the old code with no slowdown, but I'm not sure yet.

**Comment by spdomin** [comment] 2021-04-07 17:30
@brian-kelley, thank you for looking at this - much appreciated. Since all of our cases are non-linear, transient fluids cases, after the first solve of anything, diffs will show up in both the matrix and residual/DOFs.

Looking at the tests that differ, none are a simple heat conduction mechanics. I think we may simply need a profession opinion that 1) the diffs are expected and 2) the code changes were correct.

As noted, I have planned to run an analytical convergence plot to help paint the correctness from the application side.

**Comment by brian-kelley** [comment] 2021-04-07 19:25
@spdomin The mesh should be automatically decomposed, right? I'm getting
```
    Start 14: dgNonConformalThreeBlade

14: Test command: /usr/bin/sh "-c" "mpiexec -np 4 --oversubscribe /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/NaluBuild/naluX -i /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/Nalu/reg_tests/test_files/dgNonConformalThreeBlade/dgNonConformalThreeBlade.i -o dgNonConformalThreeBlade.log && /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/Nalu/reg_tests/pass_fail.sh dgNonConformalThreeBlade /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/Nalu/reg_tests/test_files/dgNonConformalThreeBlade/dgNonConformalThreeBlade.norm.gold 0.000000000000001 && mpiexec -np 4 --oversubscribe /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/NaluBuild/naluX -i /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/Nalu/reg_tests/test_files/dgNonConformalThreeBlade/dgNonConformalThreeBlade_rst.i -o dgNonConformalThreeBlade_rst.log && /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/Nalu/reg_tests/pass_fail.sh dgNonConformalThreeBlade_rst /run/media/bmkelle/6b046acd-4efd-4f43-a567-1699d733ba4c/Nalu/Nalu/reg_tests/test_files/dgNonConformalThreeBlade/dgNonConformalThreeBlade_rst.norm.gold 0.000000000000001"
14: Test timeout computed to be: 1500
14: 
14: Exodus Library Warning/Error: [ex__check_file_type]
14: 	ERROR: Could not open file '../../mesh/threeBladeMesh.g.4.0', error = No such file or directory.
14: 
14: Exodus Library Warning/Error: [ex_open_int]
14: 	ERROR: failed to open ../../mesh/threeBladeMesh.g.4.0 of type 0 for reading. Either the file does not exist,
14: 	or there is a permission or file format issue.
14: 
14: Exodus Library Warning/Error: [ex__check_file_type]
14: 	ERROR: Could not open file '../../mesh/threeBladeMesh.g.4.1', error = No such file or directory.
```
threeBladeMesh.g is in the mesh folder but not the 4-rank decomposed files.

This is the log:
```
   Nalu Version: v1.5-1-gbebc794
   Nalu GIT Commit SHA: bebc794eb6a7b30a2db82791c435e01305ba9645-DIRTY
   Trilinos Version: 13.1-g5e02cac

   TPLs: Boost, HDF5, netCDF, STK, Trilinos, YAML_cpp and zlib

              Copyright 2014 Sandia Corporation.
      This software is released under the license detailed
   in the file, LICENSE, which is located in the top-level Nalu
                     directory structure
-----------------------------------------------------------------


Realm Options Review: realm_1
===========================
Element-based scheme will be activated
Warning: When using automatic_decomposition_type, one must have a serial file
Nalu will deactivate aura ghosting
SolutionOptions::load() unit_vector not supplied; will use 0,0,1

Turbulence Model Review:
===========================
Turbulence Model is: laminar 0

PPE review:
===========================
Realm::create_mesh(): Begin
```
I used do-configTrilinos_debug to build Trilinos.

**Comment by wjhorne** [comment] 2021-04-07 19:27
You might need to run submodule init and submodule update in the main directory. All computational meshes are included as a separate submodule and they will not be present otherwise.

**Comment by brian-kelley** [comment] 2021-04-07 19:35
@wjhorne I did that (the NaluBuild/reg_tests/mesh symlinked dir has the 200 or so mesh files in it), it just looks like threeBladeMesh.g.4.0 ... threeBladeMesh.g.4.3 aren't included in the NaluMesh repo. threeBladeMesh.g is there.

**Comment by spdomin** [comment] 2021-04-07 20:29
This regression test uses automatic mesh decomposition:

`    automatic_decomposition_type: rcb
`

As such, the single mesh file is all that one needs. The error you are showing suggests that NetCDF/PNetCDF, and HDF5 were not built with all of the required options. I can't recall which one is the culprit when auto-decamp does not work..

Check out:

https://nalu.readthedocs.io/en/latest/source/user/build_manually.html#linux-and-osx

**Comment by spdomin** [comment] 2021-04-07 20:52
Alternatively, you can use the Seacas decomp tool inside your mesh location while removing the auto-decomp line command. This might be easier than working through any TPL build nuances.. 

>decomp -j 4 threeBladeMesh.g

**Comment by brian-kelley** [comment] 2021-04-07 21:16
@spdomin Thanks, I was able to get it running with manual decomp.

**Comment by brian-kelley** [comment] 2021-04-07 21:35
@wjhorne @spdomin OK, I got dgNonConformalThreeBlade to pass by changing the order of additions.
Bad:
```
(((b_i - A_i1 * x_1) - A_i2 * x_2) + ...)
```
Good:
```
b_i - ((A_i1 * x_1 + A_i2 * x_2) + ...)
```
The only reason I changed it was to avoid initializing the sum to 0, but that doesn't really matter performance wise. I can see why the old way was better numerically since b may be a lot bigger than the Ax terms. I'll open a PR with this.

**Comment by spdomin** [comment] 2021-04-07 21:49
Yes, I agree... Thanks..

**Comment by brian-kelley** [comment] 2021-04-08 16:59
OK, that fix has been merged. Let me know if there are any other issues.

**Closed by brian-kelley** 2021-04-08 16:59 UTC

**Comment by spdomin** [comment] 2021-04-08 20:38
I will report back after our nightly build and test process to confirm closure.
