### ISSUE TITLE
Compadre:  GMLS Python Script, can't find file

### ISSUE THREAD

**Issue by DaveBeCoding** [trilinos/Trilinos#10839] opened 2022-08-08 16:57 UTC
## Bug Report
@trilinos/compadre 

### Description
GMLS testing executes test python script, and fails with:
```

Running: "/path/to/python/2.7.9/bin/python" "/path/to/build/packages/compadre/examples/GMLS_Staggered_Manifold.py" "--porder=3" "--grids=4" "--in-trilinos=True"

--------------------------------------------------------------------------------

['/path/to/build/packages/compadre/examples/Compadre_GMLS_Staggered_Manifold_Test.exe', '--p', '3', '--nt', '100', '--d', '3', '--ns', '2000', '--solver', 'QR', '--problem', 'MANIFOLD', '--kokkos-threads=4']
Traceback (most recent call last):
  File "/path/to/build/packages/compadre/examples/GMLS_Staggered_Manifold.py", line 45, in <module>
    output = subprocess.check_output(output_commands, stderr=devnull)
  File "/path/to/python/2.7.9/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/path/to/python/2.7.9/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/path/to/python/2.7.9/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory



```

### Steps to Reproduce
1. See errors,  https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-__UNKNOWN__-test-rhel7_sems-clang-10.0.0-openmpi-1.10.1-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-532&field2=buildstamp&compare2=61&value2=20220727-1638-Experimental

2. Follow instructions in https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors  and use 
https://github.com/srbdev/Trilinos/commits/framework-pr-clang10-c%2B%2B17-test for step 5 "Reproducing PR testing errors"

**Comment by kuberry** [comment] 2022-08-08 18:31
Hi @DaveBeCoding, can you confirm whether `/path/to/build/packages/compadre/examples/Compadre_GMLS_Manifold_Test.exe` exists?

**Comment by srbdev** [comment] 2022-08-18 19:05
After digging into this more, we realized that the issue isn't with the Compadre package. Trilinos did fail to build but wasn't properly reporting to CDash so it's another issue unrelated to this. Closing.

Cc: @DaveBeCoding

**Closed by srbdev** 2022-08-18 19:05 UTC
Labels: type: bug, pkg: Compadre
