### ISSUE TITLE
Ifpack2 - SIMD/Vectorization Intrinsics Error with Type Conversion on HSW/Kepler37 Optimized Build

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#2390] opened 2018-03-15 01:37 UTC
@trilinos/ifpack2 :

Running an optimized build for HSW/Kepler37 with GCC 4.9.3 and CUDA 9.0. The following error is created. If this code is using STK::SIMD or SIMD Types, its possible there is a invalid type conversion present in this library. This particular file generates all kinds of warnings.

Compile line is (lots of stuff) and:

```
-pedantic -Wall -Wno-long-long -Wwrite-strings   -fPIC -lineinfo  --std=c++11 -expt-extended-lambda -march=core-avx2 -mtune=core-avx2 -arch=sm_37   -g -O0   -o CMakeFiles/ifpack2.dir/Ifpack2_BlockTriDiContainer_Serial.cpp.o -c /home/sdhammo/git/trilinos-sparc-gitlab-repo/build-sparc-493-90176-arch/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_Serial.cpp
```

Produces the following error when using `KOKKOS_ARCH=HSW;Kepler37`

```
...
/home/sdhammo/git/trilinos-sparc-gitlab-repo/packages/kokkos-kernels/src/batched/KokkosBatched_InnerTrsm_Serial_Impl.hpp(1367): warning: calling a __host__ function from a __host__ __device__ function is not allowed

/home/sdhammo/git/trilinos-sparc-gitlab-repo/packages/kokkos-kernels/src/batched/KokkosBatched_InnerTrsm_Serial_Impl.hpp(1380): warning: calling a __host__ function from a __host__ __device__ function is not allowed

/home/projects/x86-64/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include/avxintrin.h(54): error: Internal Compiler Error (codegen): "unsupported type during translation!"

make[2]: *** [packages/ifpack2/src/CMakeFiles/ifpack2.dir/build.make:927: packages/ifpack2/src/CMakeFiles/ifpack2.dir/Ifpack2_BlockTriDiContainer_Serial.cpp.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:11785: packages/ifpack2/src/CMakeFiles/ifpack2.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

**Comment by nmhamster** [comment] 2018-03-15 01:44
Removing the Haswell flags (`-march=core-avx2 -mtune=core-avx2`) and recompiling by hand seems to work and produce an object file, or at least no compile errors. This could be a compiler bug?

**Comment by nmhamster** [comment] 2018-03-15 01:45
Same problem for `packages/ifpack2/src/Ifpack2_BlockTriDiContainer_Cuda.cpp`

**Comment by mhoemmen** [comment] 2018-03-15 03:57
It looks like a kokkos-kernels issue that just happens to manifest in Ifpack2.  I will add an issue to track it there.

**Comment by kyungjoo-kim** [comment] 2018-03-15 15:32
@nmhamster 

Does this have default cuda space ? If so, vector intrinsic path is not right path. It looks like that I did a mistake in kokkoskernels promotion. However, i believe that all integration tests should filter out this kind of compiler errors during kokkos integration. 

@ndellingwood 

Do we test cuda build with x86 architectures during the integration ? If so, the integration tests are not done properly.

**Comment by crtrott** [comment] 2018-03-15 16:18
No we don't test CUDA on X86 during integration, we were running this on White.

**Comment by kyungjoo-kim** [comment] 2018-03-15 16:29
Where can I reproduce this ?

**Comment by nmhamster** [comment] 2018-03-15 16:43
Migrating discussion to Mark's issue: KokkosKernels #183.

**Comment by crtrott** [comment] 2018-03-15 16:55
Si fix your link ;-)

**Comment by mhoemmen** [comment] 2018-03-15 17:42
@crtrott I fixed @nmhamster 's link in his comment above.

**Comment by srajama1** [comment] 2018-03-15 18:57
@kyungjoo-kim : Let us fix in Kokkoskernels and apply a patch in Trilinos. I am not sure it is worth doing another integration right away. If this is a platform we are going to run on, we should add this as part of integration testing.

**Comment by crtrott** [comment] 2018-03-15 23:45
I think he wanted to link to KokkosKernels.

**Comment by mhoemmen** [comment] 2018-03-16 15:06
@micahahoward may be interested in following this discussion.

**Comment by kyungjoo-kim** [comment] 2018-05-31 20:55
@nmhamster I think that this issue is resolved now as the code passes SPARC tests.  I am closing this.

**Closed by kyungjoo-kim** 2018-05-31 20:55 UTC
Labels: Ifpack2, KokkosKernels, bug
