### ISSUE TITLE
PackageName: ML  General Summary of the Question : How to create epectra_crsmatrix from user matrix

### ISSUE THREAD

**Issue by srinadhupreetham** [trilinos/Trilinos#5406] opened 2019-06-19 10:38 UTC
## EPECTRA CRS MATRIX
@trilinos/\ML\>

How to create epectracrds matrix from user matrix please post the sample code

**Comment by mayrmt** [comment] 2019-06-19 11:06
This seems to be a duplicate of #5227.

Closing in favour of duplicate #5227.

**Closed by mayrmt** 2019-06-19 11:06 UTC
Labels: type: question
