### ISSUE TITLE
Ifpack2 RILUK with overlap does not work properly as smoother in MueLu

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#558] opened 2016-08-16 22:32 UTC
@trilinos/ifpack2

Reported by a user:

I'm running a Drekar MHD test case that requires Ifpack2's RILUK smoother for MueLu.   I observed that the number of GMRES iterations has increased unexpectedly by a factor of 3 recently.  The increase appears to be due to the following Ifpack2 check-in to address issue #514.

```
commit b9182479ae30d1b642e7c918a5214a5599c0ad53
Date:   Wed Jul 27 17:41:35 2016 -0600

    Ifpack2: Use LocalSparseTriangularSolver in ILUT & RILUK (#514)
```
I'm not sure if the issue is with the computation of the RILUK factors or the apply.

Without overlap, the convergence is correct, so it must be an interaction between Ifpack2's AdditiveSchwarz and commit b918247.

**Comment by mhoemmen** [comment] 2016-08-16 22:38
This quite possibly relates to Bugzilla 5992 and #438.  Does the column Map in question obey the requirements that LocalFilter imposes?

Does this mean we can fix how AdditiveSchwarz does overlap, once and for all?  I wouldn't quite use the words "utter disaster," but it's been a pain in our side off and on for years now.

**Comment by pwxy** [comment] 2016-08-17 01:27
Unfortunately it is not as simple as the case where overlap=1 gives the same convergence as overlap=0.  This will take more careful investigation into AdditiveSchwarz.

**Comment by mhoemmen** [comment] 2016-08-17 14:12
@pwxy wrote:
> This will take more careful investigation into AdditiveSchwarz.

Right, but could you send us the domain Map and column Map of the input matrix?  That might help us know whether #438 is to blame here.

**Comment by pwxy** [comment] 2016-08-17 14:52
I have include all four maps dumped by MueLu.  I looked at the domain map and column map, and they are different.

[mhd_matrix.zip](https://github.com/trilinos/Trilinos/files/422839/mhd_matrix.zip)

**Comment by mhoemmen** [comment] 2016-08-17 15:41
> I looked at the domain map and column map, and they are different.

The issue is not that they are different; it's whether the remote entries in the column Map always occur at the end on each process, and whether the local entries in the column Map always occur in the same order as in the domain Map on each process.

**Comment by mhoemmen** [comment] 2016-08-17 15:42
@jhux2 I guess I'm taking this then?  Are you interested in helping out?

**Comment by jhux2** [comment] 2016-08-17 16:43
@mhoemmen Yes, I'd like to help out.

**Comment by mhoemmen** [comment] 2016-08-17 17:09
@jhux2 Thanks!  I'll take a look at the Maps to see if they obey the LocalFilter criterion.  If they don't, then the next step would be to fix that issue (#438), which would mean rewriting how AdditiveSchwarz does overlap.  If they do, then it's possible that my commit broke things.

**Comment by mhoemmen** [comment] 2016-08-17 22:49
Fixing #561 will help me automate the process of determining whether fittedness of Maps is causing this issue.

**Comment by mhoemmen** [comment] 2016-08-18 16:03
I just wrote a little tester thingie (I'll commit it later) that reads two Maps and tells me whether (map1, map2) is a fitted pair on all processes.  It looks like the domain Map and the column Map that @pwxy posted is a fitted pair on all processes.

**Comment by mhoemmen** [comment] 2016-08-19 04:11
I'm working on another test for LocalSparseTriangularSolver.  After that, I will write a test that uses LocalFilter with LocalSparseTriangularSolver, to make sure that LocalFilter works (with fitted domain and column Maps).  Then, I'll plug the whole thing into overlapping domain decomposition and see if _that_ works.

**Comment by mhoemmen** [comment] 2016-08-22 03:09
Fixing #570 would probably not fix this issue, alas, because RILUK sets up its two LocalSparseTriangularSolver instances (one for L and one for U) in compute().

**Comment by ambrad** [comment] 2016-08-22 03:51
@mhoemmen, I agree that fixing #570, and also the LocalSparseTriangularSolver bug, won't fix this issue. 1. MueLu::Ifpack2Smoother appears to call initialize() unnecessarily (according to the proper semantics of initialize vs compute) just to work around issue #570. 2. And I suspect that this issue (#558) is happening in the code path MueLu::Ifpack2Smoother -> Ifpack2::AdditiveSchwarz -> Ifpack2::RILUK. 1 & 2 imply that initialize/compute issues are not relevant.

**Comment by jhux2** [comment] 2016-08-22 19:47
@pwxy Can you generate a small matrix and RHS that demonstrate the issue?  By small, I mean small enough that we could commit them to the repo as input to a unit test.

**Comment by mhoemmen** [comment] 2016-08-24 02:57
@ambrad @jhux2 

I just wrote a pretty extensive test for LocalSparseTriangularSolver.  It looks like there might be something wrong with either it, or Tpetra's sparse triangular solve.  I'm attaching a patch that adds an extensive test.  It compares LocalSparseTriangularSolver's results against a known exact solution, a dense solve, and a reference sparse triangular solve implementation included in the test.

It looks like what's wrong may be related to the diagonal.  It doesn't get the right answer, regardless of whether I store L's unit diagonal explicitly or let it be implicit, but the answer is differently wrong both times.
[0001-TMP-Ifpack2-Improve-LocalSparseTriangularSolver-unit.txt](https://github.com/trilinos/Trilinos/files/433942/0001-TMP-Ifpack2-Improve-LocalSparseTriangularSolver-unit.txt)

**Comment by mhoemmen** [comment] 2016-08-24 22:45
I'm taking off the "in progress" label, since this is stalling.

**Comment by pwxy** [comment] 2016-09-01 11:54
Here is an 8x3x3 element drekar mhd test case (matrix with 1152 rows) for 2 MPI processes that exhibits the bug.

In the tarball, the "nox" directory contains the matrix J_0 and RHS f_0 that nox dumps.  The "muelu" directory contains the matrix and the four maps that muelu outputs (row,column,range,domain).

the following are the ifpack2 smoother parameters specified for muelu by my drekar input deck


                <Parameter name="smoother: type"                          type="string"   value="SCHWARZ"/>
                <ParameterList name="smoother: params">
                   <Parameter name="schwarz: overlap level"            type="int"    value="1"/>
                   <Parameter name="schwarz: combine mode"             type="string" value="Zero"/> 
                   <Parameter name="schwarz: use reordering"           type="bool"   value="false"/> 
              
                   <Parameter name="subdomain solver name"             type="string" value="RILUK"/>
                   <ParameterList name="subdomain solver parameters">
                      <Parameter name= "fact: iluk level-of-fill"         type="int"    value="0"/>
                      <Parameter name= "fact: absolute threshold"         type="double" value="0."/>
                      <Parameter name= "fact: relative threshold"         type="double" value="1."/>
                      <Parameter name= "fact: relax value"                type="double" value="0."/>
                   </ParameterList>

                </ParameterList>



Prior to the bug, this was the "correct" belos GMRES convergence history:


  Iter   0, [ 1] :    1.000000e+00
  Iter   1, [ 1] :    2.504016e-01
  Iter   2, [ 1] :    5.099765e-03
  Iter   3, [ 1] :    1.620560e-03
  Iter   4, [ 1] :    2.527391e-04


with the bug, this is the current belos GMRES convergence history:

  Iter   0, [ 1] :    1.000000e+00
  Iter   1, [ 1] :    2.500550e-01
  Iter   2, [ 1] :    1.857588e-02
  Iter   3, [ 1] :    2.365366e-03
  Iter   4, [ 1] :    5.202696e-04

[8x3x3elem.zip](https://github.com/trilinos/Trilinos/files/449543/8x3x3elem.zip)

**Comment by ambrad** [comment] 2016-09-27 23:59
I'm looking into this. Will report back.

**Comment by ambrad** [comment] 2016-09-29 01:38
@mhoemmen, what do you think of this:

In LocalFilter's ctor, a domain map was created in this case as follows:
```
    const size_t numCols = A_->getDomainMap ()->getNodeNumElements ();
    localDomainMap_ =
      rcp (new map_type (numCols, indexBase, localComm,
                         Tpetra::GloballyDistributed, A_->getNode ()));
```

But I think numCols should actually be
```
    const size_t numCols = A_->getNodeNumCols ();
```
I think that's because A_ is an OverlappingMatrix, whose domain map is just the original matrix's domain map. This map is not relevant to the overlapping matrix; it's the overlapping matrix's column map that is relevant since it expresses the overlap intended by Schwarz.

This solution also has the virtual of mimicing what is down for rowCols a few lines earlier, I'm pretty sure for the same reason.

**Comment by ambrad** [comment] 2016-09-29 03:06
@mhoemmen, here's an intriguing alternative.

Instead of saying that LocalFilter has a bug in its local DomainMap, it might be better to say that (i) LocalFilter has a bug in its local *RangeMap* and (ii) OverlappingRowMatrix has bugs in getDomainMap and getRangeMap. These, taken together, are the cause of this issue.

Right now, OverlappingRowMatrix uses A_->getDomain/RangeMap (where A_ is the user's matrix) has the domain and range maps. But if instead it uses ColMap_ and RowMap_, respectively, then these will reflect the requested overlap. (Actually, ColMap_.isSameAs(RowMap_), by construction.)

Meanwhile, we could return LocalFilter to using numRows = getRangeMap()->getNodeNumElements() (about which there is a FIXME comment) and continue to use numCols = getDomainMap()->getNodeNumElements(). I think this expresses the intent of LocalFilter to filter based on domain and range maps.

This approach also passes all tests and fixes this issue.

**Comment by mhoemmen** [comment] 2016-09-29 16:06
> This approach also passes all tests and fixes this issue.

Fantastic!!! :-D  Thanks for trying this out!

> Right now, OverlappingRowMatrix uses A_->getDomain/RangeMap (where A_ is the user's matrix) as the domain and range maps. But if instead it uses ColMap_ and RowMap_, respectively, then these will reflect the requested overlap. (Actually, ColMap_.isSameAs(RowMap_), by construction.)

This suggests that the input vector to OverlappingRowMatrix::apply should have the same Map as ColMap_, and that the output vector to OverlappingRowMatrix::apply should have the same Map as RowMap_.  Is that right?

**Comment by ambrad** [comment] 2016-09-29 16:24
@mhoemmen, that is correct, as I understand the point of overlap > 0. On a processor, the block that results from overlap > 0 is intended to act on a vector having a map reflecting that overlap > 0. Hence the domain map should not be that of the original matrix, but rather that of the overlapped one. That then implies that this overlapped matrix ought to have col map == domain map by construction.

**Comment by mhoemmen** [comment] 2016-09-29 17:16
> On a processor, the block that results from overlap > 0 is intended to act on a vector having a map reflecting that overlap > 0.

That makes sense.  Just to summarize for posterity: AdditiveSchwarz is supposed to take responsibility for the initial Import.  That Import results in an input (Multi)Vector for the subdomain solver.  The subdomain solver thus should not have to do another Import.  This implies that the subdomain solver's column Map should be the same as its domain Map.

This introduces a minor problem, namely that domain and range Maps are supposed to be one to one (nonoverlapping).  The right way to solve that would be to restrict the domain Map of the subdomain solver, so that its communicator only has one process.  This correctly reflects that the subdomain solver only works on a single process.  (A full generalization of AdditiveSchwarz that allows multiprocess subdomain solvers, would restrict the domain Map to the subdomain's subcommunicator.)  As a result, after AdditiveSchwarz does its Import, what really happens is that the resulting (Multi)Vector gets _restricted_ to the subdomain's subcommunicator (which is `MPI_COMM_SELF` or its equivalent, in this case).  This is a no-communication operation and should not require copying any data.

**Comment by ambrad** [comment] 2016-09-29 22:27
@mhoemmen, @jhux2, @pwxy, I have just pushed a commit to fix this issue.

@pwxy, would you close this commit (or let me know to close it) when you've confirmed that it indeed fixes the issue you reported? Thanks again for reporting it.

**Comment by jhux2** [comment] 2016-09-29 22:29
@ambrad Nice job!

**Comment by mhoemmen** [comment] 2016-09-29 23:12
@ambrad wrote:
> I have just pushed a commit to fix this issue.

YOU ROCK

**Comment by pwxy** [comment] 2016-09-30 13:45
I did some quick testing with the ifpack2 RILUK AdditiveSchwarz (up to 1024 MPI processes), and @ambrad 's fix work for those test cases.  Excellent job @ambrad !  Thanks so much!

**Closed by pwxy** 2016-09-30 13:45 UTC
Labels: bug, Ifpack2, MueLu
