### ISSUE TITLE
ePetra: OMP statement incompatible with OMP 4.0 / GCC 9 data sharing rules

### ISSUE THREAD

**Issue by StefanBruens** [trilinos/Trilinos#5390] opened 2019-06-16 10:29 UTC
## Bug Report
@trilinos/ePetra

### Description
https://www.gnu.org/software/gcc/gcc-9/porting_to.html
> GCC releases before 9 were implementing an OpenMP 3.1 data sharing rule that const qualified variables without mutable member are predetermined shared, ... GCC 9 started implementing the OpenMP 4.0 and later behavior. When not using default clause or when using default(shared), this makes no difference, but if using default(none), previously the choice was not specify the const qualified variables on the construct at all, ...

### Steps to Reproduce
Try to build with GCC 9
```
[  299s] /home/abuild/rpmbuild/BUILD/Trilinos-trilinos-release-12-10-1/packages/epetra/src/Epetra_CrsGraph.cpp: In member function 'int Epetra_CrsGraph::OptimizeStorage()':
[  299s] /home/abuild/rpmbuild/BUILD/Trilinos-trilinos-release-12-10-1/packages/epetra/src/Epetra_CrsGraph.cpp:1949:7: error: 'numMyBlockRows' not specified in enclosing 'parallel'
[  299s]  1949 |       for(int i = 0; i < numMyBlockRows; i++) {
[  299s]       |       ^~~
[  299s] /home/abuild/rpmbuild/BUILD/Trilinos-trilinos-release-12-10-1/packages/epetra/src/Epetra_CrsGraph.cpp:1947:9: error: enclosing 'parallel'
[  299s]  1947 | #pragma omp parallel for default(none) shared(indexOffset,all_indices,indices)
[  299s]       |         ^~~
[  299s] /home/abuild/rpmbuild/BUILD/Trilinos-trilinos-release-12-10-1/packages/epetra/src/Epetra_CrsGraph.cpp:1989:6: error: 'numMyBlockRows' not specified in enclosing 'parallel'
```

**Comment by rppawlo** [comment] 2019-08-30 12:12
Just confirmed this - epetra with OpenMP enabled is broken for gcc 9.2, tested on both mac and linux machines. @kddevin - is there any plans to fix this? We have a temporary workaround in #5823 for my specific use case but it is not the correct long term fix.

**Comment by ikalash** [comment] 2019-09-06 15:11
Any idea when this issue might be resolved?  The Albany OpenMP nightly build is broken due to this issue (#5836).

**Comment by rppawlo** [comment] 2019-09-06 17:52
@ikalash - if you don't need openmp in epetra but do need it enabled for other packages (e.g. tpetra), you can use this as a workaround:
```
-D Epetra_ENABLE_OpenMP:BOOL=OFF \
```
we are doing this for drekar builds.

**Comment by mhoemmen** [comment] 2019-09-06 18:00
@rppawlo Should we turn off OpenMP in Epetra by default?

**Comment by rppawlo** [comment] 2019-09-06 18:06
@mhoemmen - that would eliminate one extra configure flag for drekar, charon and empire for gcc 9+. Do we have anyone assigned to fix this? It seems to be a syntax change that might be quick to fix. If not, then that is probably the best option to set to OFF by default.

**Comment by mhoemmen** [comment] 2019-09-06 18:12
@rppawlo I set OpenMP support to OFF by default in PR #5871.

**Comment by ikalash** [comment] 2019-09-06 21:41
@rppawlo : Thanks, that fixed the issue!

**Closed** 2020-01-02 17:26 UTC
Labels: pkg: Epetra, type: bug
