### ISSUE TITLE
problem with Ifpack2::AdditiveSchwarz  and sparse direct subdomain solves

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#460] opened 2016-06-23 22:29 UTC
A user has reported that Ifpack2's additive Schwarz with sparse direct solves from Amesos2 does not work properly as a smoother in MueLu.  After an initial look, I discovered that the Ifpack2 test that tests this was accidentally disabled (I don't know when).  I enabled it locally and found the test fails.

**Comment by jhux2** [comment] 2016-06-23 22:30
@allafa

**Comment by jhux2** [comment] 2016-06-24 19:28
@allaffa

**Comment by mhoemmen** [comment] 2016-08-02 23:40
@jhux2 Which test?

**Comment by jhux2** [comment] 2016-08-05 22:30
> @jhux2 Which test?

@mhoemmen Ifpack2's AdditiveSchwarz SuperLU unit test.

**Comment by brian-kelley** [comment] 2016-08-06 03:34
How was the test disabled? I looked at UnitTestAdditiveSwartz.cpp and it doesn't seem to be commented out. I was worried because I pushed changes 6 days before this issue cropped up, even though my changes shouldn't have affected this test.

**Comment by mhoemmen** [comment] 2016-08-06 17:46
@brian-kelley @jhux2 I'm confused too.  It looks like the SuperLU test in ifpack2/test/unit_tests/Ifpack2_UnitTestAdditiveSchwarz.cpp should run, as long as Amesos2 and SuperLU are enabled.  The CMakeLists.txt file looks like it's building that .cpp file.

**Comment by mhoemmen** [comment] 2016-08-06 17:46
@brian-kelley You have to brag more when you push a big change; I had no idea ;-)

**Comment by brian-kelley** [comment] 2016-08-06 18:43
It wasn't really a major change, just the Container Factory for block relaxation. Additive Swartz never uses containers, and I never touched any additive Swartz related tests or sources.

**Comment by jhux2** [comment] 2016-08-10 18:18
The Ifpack2::AdditiveSchwarz SuperLU unit test is guarded by the macro HAVE_AMESOS2_SUPERLU.  I never included Amesos2_config.h, however, so the macro is undefined and hence the test doesn't run.

**Comment by jhux2** [comment] 2016-08-16 21:06
If I set overlap=0, the test passes.

**Comment by jhux2** [comment] 2016-08-18 00:17
I've reenabled the test with overlap=0 (commit cb801b6).  It passes, but overlap>1 will make it fail.  I also generalized the test to use either KLU2 or SuperLU.

**Comment by mhoemmen** [comment] 2016-08-18 02:29
Hm, Ifpack2's Amesos2 wrapper just lets Amesos2 apply the factorization; it does not use Ifpack2::LocalSparseTriangularSolver.  Thus suggests that #558 is about overlap.

**Comment by mhoemmen** [comment] 2016-08-24 03:55
See patch I posted an hour ago to #558.

**Comment by jhux2** [comment] 2016-08-24 16:18
@mhoemmen I didn't see a patch attached ot #558.  Did you mean commit 46075d3?

**Comment by mhoemmen** [comment] 2016-08-24 17:16
@jhux2 See commit https://github.com/trilinos/Trilinos/commit/46075d305ad43c906ff7bba84ec4c6d4488e4773 :-)

**Comment by mhoemmen** [comment] 2016-08-24 17:17
@jhux See commit https://github.com/trilinos/Trilinos/commit/46075d305ad43c906ff7bba84ec4c6d4488e4773, which includes a test showing that LocalSparseTriangularSolver is correct.

**Comment by mhoemmen** [comment] 2016-10-04 18:21
@ambrad did your recent changes fix this one?

**Comment by ambrad** [comment] 2016-10-04 19:48
@mhoemmen, no. I put overlap = 1 back in the test, and it still throws as reported above.

**Comment by mhoemmen** [comment] 2016-10-04 20:18
@ambrad Thanks for the update!  I'm looking at Ifpack2's Amesos2 wrapper now to see if it has the same problem that LocalSparseTriangularSolver had with respect to Imports.

**Comment by mhoemmen** [comment] 2016-10-04 20:41
Weird things about Ifpack2's Amesos2 wrapper:
  - Funny FIXME comments in setMatrix (I just contacted @jhux2 to ask)
  - Why does initialize() copy the matrix?  Why does it do so using a weird Import?  (Amesos2 should just be able to take the matrix directly; it accepts the matrix as an `RCP<const Matrix>`, so it promises not to change the matrix.)
  - It looks like initialize() does initialization that depends on the matrix's values
  - Why does apply() create offset views?  Amesos2 should be able to handle any necessary communication or remapping on its own.

**Comment by mhoemmen** [comment] 2016-10-04 22:35
For some reason, this test wasn't ever building for me.  Trying again, and explicitly enabling Amesos2 this time.

**Comment by mhoemmen** [comment] 2016-10-04 22:43
I built the test, verified that it built (including the SuperLU test), and it passes for me.
@jhux2, could you show me exactly what test is failing, and what it prints when it fails?

**Comment by jhux2** [comment] 2016-10-04 22:50
> I built the test, verified that it built (including the SuperLU test), and it passes for me.
> @jhux2, could you show me exactly what test is failing, and what it prints when it fails?

Did you change the overlap to 1 in test SparseDirectSolver?  See the comment around line 562.

**Comment by mhoemmen** [comment] 2016-10-04 22:53
@jhux2 wrote:
> Did you change the overlap to 1 in test SparseDirectSolver? See the comment around line 562.

Ah, I see, this is not the Amesos2 wrapper test.  I am looking at Ifpack2_UnitTestAdditiveSchwarz.cpp now.

**Comment by jhux** [comment] 2016-10-04 23:33
I'm sorry I don't know what this is about and why I'm receiving the emails. Swing by my desk tomorrow so we can connect please. Thanks :)



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mhoemmen** [comment] 2016-10-04 23:42
@jhux You were @-mentioned by mistake.  I fixed the comment in question.  Please unsubscribe from this issue.

**Comment by mhoemmen** [comment] 2016-10-05 00:22
@jhux2 I changed the overlap to 1 (around line 562 of Ifpack2_UnitTestAdditiveSchwarz.cpp, as you mentioned) and got the test to fail.

I'm wondering if the same thing as in @ambrad 's fix for RILUK's use of LocalSparseTriangularSolver in AdditiveSchwarz (get the Maps right) will work here.  I started trying it out.

**Comment by jhux2** [comment] 2016-10-11 15:49
@bmpersc I thought be89a0d was just moving the test, not a fix.

**Comment by bmpersc** [comment] 2016-10-11 16:06
@jhux2 this seems to have been an automated thing that github did based on the commit log in be89a0d where it said "This will help us fix #460." Apparently having fix and a bug number are enough to automatically close a ticket.

**Comment by jhux2** [comment] 2016-10-11 16:36
> @jhux2 this seems to have been an automated thing that github did based on the commit log in be89a0d where it said "This will help us fix #460." Apparently having fix and a bug number are enough to automatically close a ticket.

@bmpersc Ok, good to know.

**Comment by mhoemmen** [comment] 2016-10-24 15:59
@jhux2 explained just now that the "user" in his original report was a summer student working with Ray.

**Comment by brian-kelley** [comment] 2017-06-14 21:52
I think I solved this issue. In AdditiveSchwarz::apply(), with overlap, the OverlappingB and OverlappingY vectors are still distributed across all procs when localApply() is called (which in turn runs the inner solver). For some reason, Amesos2 expects those vectors to have _global_ length matching the nrows of the local matrix, which didn't match on parallel problems. I just copied the local entries of OverlappingB and OverlappingY into non-distributed MVs and it worked with or without overlap (0, 1 or 2).

**Comment by mhoemmen** [comment] 2017-06-14 23:01
Awesome!  Thanks @brian-kelley !  I think you could even just have the non-distributed MVs view the data of the distributed MVs, without needing a copy.

**Comment by brian-kelley** [comment] 2017-06-16 20:23
Alright, so I did fix the SparseDirectSolver test completely, but I wanted to get your input before checking it in. (See [my fork, branch SchwarzFix460](https://github.com/brian-kelley/Trilinos/commits/SchwarzFix460)).

There's definitely some weirdness with the way Amesos2 validates solver input. I had create new Tpetra::Maps that are "locally replicated" and have the same number of global rows as the real B/Y have local rows, then make a shallow copy into new multivectors (one map and one new MV per process). Then I also had to run the solver one column at a time - passing the whole MV at once still didn't work. All of this is done when I see that the "subdomain solver name" parameter is "AMESOS2".

So I have a fix but it's pretty kludgy and there's probably a better way.

**Comment by srajama1** [comment] 2017-06-16 20:34
Can you @trilinos/amesos2 team a test case. I also don't quite get what you mean about the weirdness. If you want to stop by please feel free. I would like to understand this better.

**Comment by brian-kelley** [comment] 2017-06-19 13:46
I was wrong, there's nothing wrong with Amesos2. Ifpack2's Amesos2Wrapper just detected parallel problems incorrectly, by only checking whether A_'s row map's comm is > 1 process . If A is local only (as with AdditiveSchwarz), the wrapper thought the problem was serial and did not create local versions of X and Y. I just made it also check X's and Y's maps to see if they are distributed.

I made a [PR](https://github.com/trilinos/Trilinos/pull/1439) to make sure my changes are OK.

**Comment by brian-kelley** [comment] 2017-06-19 14:49
The change is checked in so this test is fixed.

**Comment by dridzal** [comment] 2017-06-19 16:40
Hi All, could this fix be related to my observation from several months ago that the subdomain solves with the direct solver were requiring too much memory?  Basically, I noticed that the total memory use for the factorizations, instead of going down with the increasing number of subdomains, went up significantly.

**Comment by brian-kelley** [comment] 2017-06-19 17:09
@dridzal That's a good idea, could you run your problem again (with this fix) and report back?

When I tried to profile MueLu + AdditiveSchwarz + KLU2 to diagnose your bad memory scaling, I didn't actually replicate the issue you saw. Once I got my [parameter list](https://gist.github.com/brian-kelley/042ea6855dd82743bf1f7dceab796582) right, the total memory usage stayed almost exactly constant with 1, 2, 4 or 8 processes.

**Comment by dridzal** [comment] 2017-06-19 21:11
@brian-kelley  I was using a very similar parameter list, so I don't think that's the issue.  I have a question about your comment "memory usage stayed almost exactly constant".  Take the extreme case where the LU factorization always results in fully dense triangular factors (we have a case close to this).  Then, as you increase the number of subdomains, the memory use should go down.  In fact, for N subdomains you should only require 1/N-th of the memory to store the factors.

Structurally, DD with 3 subdomains and no overlap should transform the dense factor

x
x x
x x x
x x x x
x x x x x
x x x x x x

into

x
x x
o o x
o o x x
o o o o x
o o o o x x

Could you please comment?

**Comment by brian-kelley** [comment] 2017-06-19 21:23
Yes, I agree with everything you said - you should see total memory decrease with more subdomains. The test runs I used definitely didn't result in fully dense triangular factors - I was using a very simple and very sparse 500x500 2D Laplacian problem, which has 1,248,000 nonzeros. For reference, it takes 10 MB to store those double values directly. Here is how much memory the AdditiveSchwarz and KLU2 compute() used:

| Processes | Per process (MB) | Total (MB) |
|--------|--------|--------:|
| 1 | 18.1 | 18.1 |
| 2 | 9.2 | 18.4 |
| 4 | 4.56 | 18.24 |
|  8 | 2.4 | 19.2 |

When I say "memory used", I mean total allocated blocks after minus total allocated blocks before.

**Comment by brian-kelley** [comment] 2017-06-19 21:39
@dridzal I don't really know the mathematical differences between KLU2 and ILU, but in case this is useful I just tried running the exact same matrix through ILU(0) in matlab and L and U were each 9.988 MB (full CRS) - A was 15.98 MB by itself.

**Comment by dridzal** [comment] 2017-06-19 23:22
@brian-kelley I agree that your example is too simple.  It looks like your LU factor size is essentially linear in the number of variables, and not quadratic as we would expect for more realistic problems.  My guess is that the factors are essentially banded, possibly with only a few subdiagonals or superdiagonals.  In this case, I don't expect any memory savings.  Do you have a more challenging example?

**Comment by brian-kelley** [comment] 2017-06-19 23:51
I could look around Galeri for a better example. Actually, the muelu scaling test driver might allow that already, I'll have a look tomorrow.

**Comment by aprokop** [comment] 2017-06-20 01:59
@dridzal Could you provide more description on your example where you get dense factors? Galeri examples provide only standard 2D/3D Laplacian and elasticity problems which would certainly not reproduce that.

**Comment by brian-kelley** [comment] 2017-06-20 14:36
@aprokop Are there any existing MueLu tests that use a denser matrix?

**Comment by aprokop** [comment] 2017-06-20 15:08
@brian-kelley Not that I know of. The densest ones are probably elasticity and possibly the high order stuff Chris is using.

**Comment by dridzal** [comment] 2017-06-20 17:29
@aprokop @brian-kelley   I need to solve a fully coupled thermal-fluids problem in 3D.  The @trilinos/rol team have a 2D implementation right now in the rol/examples/PDE-OPT/thermal-fluid directory.  We'll have the 3D implementation done in a few weeks.  However, aren't there Matrix Market examples that you could try?  Something like

http://math.nist.gov/MatrixMarket/data/SPARSKIT/fidap/fidapm37.html

You would have to partition the problem somehow for parallel studies, but my guess is that Zoltan can help.  Basically, any 3D example with slightly more interesting physics (fluids, structures) and a few hundred nonzeros per row would do.

**Comment by aprokop** [comment] 2017-06-20 17:40
We have support in MueLu for reading in the MatrixMarket and running multigrid hierarchy with it. This way we could use a single level multigrid preconditioner with a describe Ifpack2 smoother for it. @brian-kelley What do you think?

**Comment by dridzal** [comment] 2017-06-20 17:46
Another great test may be a matrix resulting from a frequency-domain edge-element discretization of Maxwell's equation.  The @trilinos/rol team will be able to provide a test matrix in the next month or so.  It is possible that @csiefer2 already has such an example.

**Comment by brian-kelley** [comment] 2017-06-20 18:15
@aprokop Yes, I could do that.

**Comment by brian-kelley** [comment] 2017-06-20 20:09
I have a simple problem being set up with fidapm37.mtx from the link above. 9152 rows, 765944 nonzeros. Here are the mem stats from just the additive schwarz inner preconditioner compute(). This is with the same parameter list from above - overlap=1.

| Processes aka subdomains | Per process (MB) | Total (MB) |
|--------|--------|--------:|
| 1 | 9.36 | 9.36 |
| 2 | 4.16 | 8.32 |
| 4 | 1.89 | 7.56 |
|  8 | 1.03 | 8.24 |

**Closed by brian-kelley** 2017-06-20 20:09 UTC
Labels: Amesos2, Ifpack2

**Comment by mhoemmen** [comment] 2017-06-20 20:40
@brian-kelley Is there a way we could make this a test that runs nightly?  Not saying you _should_ necessarily, just wondering if it's possible.

**Comment by dridzal** [comment] 2017-06-20 20:43
Great, this is going in the right direction -- thanks for following up.  I think that for more complex problems, the savings would be even greater.  I hope to provide a few examples soon.  Two quick questions: 1) Are the subdomain solves and the serial solve all using the same permutation strategy for the factorization?  2) Do the numbers change significantly with overlap=0?
As a side note, when I last used Additive Schwarz with Amesos2, I could only select a non-overlapping DD.  I guess this has been fixed, right?

**Comment by brian-kelley** [comment] 2017-06-20 20:47
@mhoemmen It would be tricky because that matrix file is 24 MB. That is the ascii matrix market format though, so there's definitely potential for storing it more efficiently in some binary format...

**Comment by brian-kelley** [comment] 2017-06-20 20:55
@dridzal 
1: Yes, because I had reordering completely off. I'll see what happens if I turn it on - then it's always RCM reordering by default I think.
2: The way I had it configured, setting overlap=0 doesn't seem to have changed memory at all...
3: Yes, that was this issue and it's fixed now.

**Comment by jhux** [comment] 2017-06-21 15:21
Please remove me from this email distribution list

**Comment by mhoemmen** [comment] 2017-06-21 15:46
I just removed the @ - mention that mentioned your name.  You can unsubscribe from individual issues if you like.  If you don't know how to do this, we'll be happy to point you to resources.

**Comment by mhoemmen** [comment] 2017-06-21 15:47
@brian-kelley wrote:
> It would be tricky because that matrix file is 24 MB.

Can @dridzal write us a test that generates the matrix on the fly?  He should have an interest in a performance regression test.

**Comment by mhoemmen** [comment] 2017-06-21 15:48
I've heard other folks complain about RCM not working....

**Comment by dridzal** [comment] 2017-06-21 21:50
I will provide a challenging test in the next week or so.  The test will generate the matrix on the fly, and it will be possible to vary its size by changing the input mesh.  I'll just need some help from you with accessing the performance statistics (memory use).  The test will be hosted in ROL, in a rol/example/PDE-OPT subdirectory.

**Comment by brian-kelley** [comment] 2017-06-22 14:09
@dridzal Measuring memory (linux/mac - I don't know about win32 or cygwin):
~~~~
#ifdef __APPLE__
#include <malloc/malloc.h>
#else
#include <malloc.h>
~~~~
and then
~~~~
inline size_t getCurrentAlloc()
{
#ifdef __APPLE__
    return mstats().bytes_used;
#else
    return mallinfo().uordblks;
#endif
}
~~~~
to get the total currently allocated bytes. I measured this at the beginning and end of the sections and then took the difference.

**Comment by brian-kelley** [comment] 2017-06-22 16:36
@dridzal I wanted to run one more test to get the full picture. Total memory for AdditiveSchwarz::compute() (MB):
| Processes/subdomains | RCM, overlap 0 | RCM, overlap 1 | no reorder, overlap 0 | no reorder, overlap 1 |
|--------|--------|--------|---------|---------:|
| 1 | 8.71 | 8.71 | 7.70 | 7.70 |
| 2 | 11.69 | 14.29 | 11.62 | 14.30 |
| 4 | 12.36 | 10.16 | 12.34 | 10.17 |
| 8 | 7.75 | 27.70 | 7.71 | 27.68 |

**Comment by srajama1** [comment] 2017-06-22 17:42
@brian-kelley : If memory is the important thing, RCM is not great ordering for direct solvers. Depending on which solver you use in Trilinos, you should let its native ordering take over.
