### ISSUE TITLE
MueLu_ExplicitInstantiation.hpp not copied to include directory when installing Trilinos

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#969] opened 2017-01-04 17:33 UTC
@trilinos/muelu 

When installing Trilinos, built with `-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON`, the file `MueLu_ExplicitInstantiation.hpp` is not copied to `<build directory>/include`.  

This caused build errors when I attempted to build `Trilinos/packages/muelu/test/scaling/Driver.cpp` on its own.  Copying the header file manually to the include directory resolved the build problem.

**Comment by aprokop** [comment] 2017-01-04 18:21
@trilinos/muelu Sounds like an obvious bug.

**Comment by jhux2** [comment] 2017-01-06 00:40
@tjfulle I'm unable to reproduce this.  I configured/built with ETI enabled.  After doing a "make install", I see that ``MueLu_ExplicitInstantiation.hpp`` has been copied into $CMAKE_INSTALL_PREFIX/include.

Would you please attach your cmake configure script?  Thanks.

**Comment by tjfulle** [comment] 2017-01-06 15:32
@jhux2, my configuration is pretty standard, I believe:

```
#!/bin/sh
/usr/bin/cmake \
-DCMAKE_INSTALL_PREFIX=/home/tjfulle/Development/Trilinos/Builds/develop/sems-gcc4.7.2 \
-DTrilinos_TRIBITS_DIR:PATH=/ascldap/users/tjfulle/Development/Trilinos/Source/cmake/tribits \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DTrilinos_TEST_CATEGORIES:STRING=BASIC \
-DTrilinos_TRACE_ADD_TEST:BOOL=ON \
-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=OFF \
-DDART_TESTING_TIMEOUT:STRING=600.0 \
-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DTrilinos_EXTRA_LINK_FLAGS="-lgomp -ldl" \
-DCMAKE_BUILD_TYPE:STRING=DEBUG \
-DTrilinos_ENABLE_DEBUG:BOOL=ON \
-DTrilinos_ENABLE_DEBUG_SYMBOLS:BOOL=ON \
-DTeuchos_ENABLE_DEBUG:BOOL=ON \
-DTpetra_ENABLE_DEBUG:BOOL=ON \
-DTeuchos_ENABLE_DEFAULT_STACKTRACE:BOOL=OFF \
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-DTrilinos_SHOW_DEPRECATED_WARNINGS:BOOL=ON \
-DTrilinos_ENABLE_OpenMP=ON \
-DTrilinos_ENABLE_CHECKED_STL:BOOL=ON \
-DCMAKE_CXX_FLAGS:STRING="-Wall --pedantic -O3" \
-DCMAKE_C_FLAGS:STRING="-Wall --pedantic -O3" \
-DTrilinos_ENABLE_CXX11:BOOL=ON \
-DTPL_ENABLE_MPI:BOOL=ON \
-DMPI_BASE_DIR:PATH=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/openmpi/1.8.7 \
-DCMAKE_CXX_COMPILER:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/openmpi/1.8.7/bin/mpicxx \
-DCMAKE_C_COMPILER:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.7.2/openmpi/1.8.7/bin/mpicc \
-DTrilinos_ENABLE_Tpetra:BOOL=ON \
-DTrilinos_ENABLE_TpetraCore:BOOL=ON \
-DTrilinos_ENABLE_Ifpack2:BOOL=ON \
-DTrilinos_ENABLE_Amesos2:BOOL=ON \
-DTrilinos_ENABLE_MueLu:BOOL=ON \
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTrilinos_ENABLE_Belos:BOOL=ON \
-DTrilinos_ENABLE_Xpetra:BOOL=ON \
-DTrilinos_ENABLE_Sacado:BOOL=ON \
-DTrilinos_ENABLE_Amesos:BOOL=ON \
-DTrilinos_ENABLE_Epetra:BOOL=ON \
-DTrilinos_ENABLE_EpetraExt:BOOL=ON \
-DTrilinos_ENABLE_KokkosExample:BOOL=OFF \
-DTrilinos_ENABLE_MeshingGenie:BOOL=OFF \
-DTrilinos_ENABLE_SEACAS:BOOL=OFF \
-DTrilinos_ENABLE_Shards:BOOL=OFF \
-DTrilinos_ENABLE_FEI:BOOL=OFF \
-DTrilinos_ENABLE_Moertel:BOOL=OFF \
-DTrilinos_ENABLE_Panzer:BOOL=OFF \
-DTrilinos_ENABLE_ThreadPool:BOOL=OFF \
-DTrilinos_ENABLE_OptiPack:BOOL=OFF \
-DTrilinos_ENABLE_Rythmos:BOOL=OFF \
-DTrilinos_ENABLE_Intrepid:BOOL=OFF \
-DTPL_ENABLE_BLAS:BOOL=ON \
-DTPL_ENABLE_LAPACK:BOOL=ON \
-DTPL_ENABLE_Zlib:BOOL=ON \
-DZlib_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.7.2/base/include \
-DZlib_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.7.2/base/lib \
-DTPL_ENABLE_Netcdf:BOOL=ON \
-DNetcdf_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.7.2/openmpi/1.8.7/parallel/include \
-DNetcdf_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.7.2/openmpi/1.8.7/parallel/lib \
-DTPL_ENABLE_HDF5:BOOL=ON \
-DHDF5_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.7.2/openmpi/1.8.7/parallel/include \
-DHDF5_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.7.2/openmpi/1.8.7/parallel/lib \
-DTPL_ENABLE_ParMETIS:BOOL=ON \
-DParMETIS_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.7.2/openmpi/1.8.7/parallel/include \
-DParMETIS_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.7.2/openmpi/1.8.7/parallel/lib \
-DTPL_ENABLE_Boost:BOOL=ON \
-DBoost_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.7.2/base/include \
-DBoost_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.7.2/base/lib \
-DTPL_ENABLE_BoostLib:BOOL=ON \
-DBoostLib_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.7.2/base/include \
-DBoostLib_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.7.2/base/lib \
-DTPL_ENABLE_SuperLU:BOOL=ON \
-DSuperLU_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.7.2/base/include \
-DSuperLU_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.7.2/base/lib \
-DTPL_ENABLE_Scotch:BOOL=ON \
-DScotch_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/scotch/6.0.3/gcc/4.7.2/openmpi/1.8.7/parallel/include \
-DScotch_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/scotch/6.0.3/gcc/4.7.2/openmpi/1.8.7/parallel/lib \
-DTPL_ENABLE_Pthread:BOOL=ON \
-DTPL_ENABLE_BinUtils:BOOL=OFF \
-DTPL_ENABLE_CSparse:BOOL=OFF \
-DTPL_ENABLE_Matio:BOOL=OFF \
-DTPL_ENABLE_METIS:BOOL=OFF \
-DTPL_ENABLE_X11:BOOL=OFF \
-DTPL_ENABLE_GLM:BOOL=OFF \
-DIfpack2_Cheby_belos_MPI_1_DISABLE:BOOL=ON \
/ascldap/users/tjfulle/Development/Trilinos/Source
```

**Comment by mhoemmen** [comment] 2017-01-06 16:24
Just curious -- what happens if you enable Intrepid?  (MueLu depends on it, at least optionally.)

**Comment by jhux2** [comment] 2017-01-07 01:19
> @jhux2, my configuration is pretty standard, I believe:

@tjfulle Thanks, that was helpful.  I use ninja by default, which installs the header file in question just fine.  Please pull and try again.

**Comment by tjfulle** [comment] 2017-01-10 05:23
@jhux2, I just pulled and rebuilt the `develop` branch, `MueLu_ExplicitInstantiation.hpp` is copied correctly.  This issue can probably be closed.  I should note, however, I had originally filed this issue after building the `master` branch (I erroneously thought I had checked out the `develop` branch).  Not sure if that makes a difference in closing this...

**Comment by mhoemmen** [comment] 2017-01-10 05:30
@tjfulle looks like @jhux2 fixed a broken thing regardless :-) thanks for reporting! I'll close this.

**Closed by mhoemmen** 2017-01-10 05:30 UTC
Labels: bug, build, MueLu
