### ISSUE TITLE
Stokhos: Compilation hang with CUDA RDC

### ISSUE THREAD

**Issue by sebrowne** [trilinos/Trilinos#11377] opened 2022-12-12 16:00 UTC
## Bug Report
@trilinos/stokhos 

### Description
The following four files hang when compiling with relocatable device code.  I've confirmed that if I disable Stokhos, the build completes.
packages/stokhos/src/MueLu_SemiCoarsenPFactory_kokkos_UQ_PCE_Cuda.cpp
packages/stokhos/src/MueLu_ScaledNullspaceFactory_UQ_PCE_Cuda.cpp
packages/stokhos/src/MueLu_SaPFactory_kokkos_UQ_PCE_Cuda.cpp
packages/stokhos/src/MueLu_CoalesceDropFactory_kokkos_UQ_PCE_Cuda.cpp

### Steps to Reproduce
1. Use the GenConfig for sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_rdc_uvm_deprecated-on_all
2. Build with ninja (suspect make will work as well)
3. After a while, look at  top, and it will show an indefinite hang on those four source files (I've let it get as far as 8hrs per file, so I'm comfortable calling that a hang)

Note that since it's a build issue, you can replicate it on a machine without GPUs.

If you need a smaller reproducer, I suspect that building with CUDA11/GCC10.1.0/OpenMPI4.0.5 with RDC enabled and Stokhos enabled will also reproduce, but I have not explicitly tested that yet.  Also not sure how much "smaller" that will be....

**Comment by sebrowne** [comment] 2022-12-12 16:00
@e10harvey

**Comment by sebrowne** [comment] 2022-12-12 19:54
I think that's an option to nvcc_wrapper.  It looks like CMake thinks your compiler is g++ directly as opposed to mpicxx or nvcc_wrapper.

**Comment by etphipp** [comment] 2022-12-12 20:30
I figured it out.  I am reusing the build directory from a previous Cuda genconfig build but forgot to delete the cmake cache.

**Comment by etphipp** [comment] 2022-12-15 17:26
I've gotten to where I can finally reproduce this.  I let it run for a couple days and it never completed.  The amount of memory used seems to be changing so I don't think it is actually hung, maybe it is stuck in an infinite loop or something.  Regardless, I'm not sure what can really be done except disable the PCE scalar type in this build with
```
-D Stokhos_ENABLE_PCE_Scalar_Type=OFF \
```
I don't like doing that, but I don't see what else to do as these are instantiations of MueLu classes on that scalar type (we can't just not compile these three files as there will be linking errors).

**Comment by etphipp** [comment] 2022-12-15 17:27
Actually, instead of that let's just disable MueLu in Stokhos:
```
-D Stokhos_ENABLE_MueLu=OFF \
```

**Comment by sebrowne** [comment] 2022-12-15 17:29
Shall I also add a warning if they enable MueLu in Stokhos when building for a GPU?  Or just disallow that combination in TriBITS?  I'm happy to turn it off in our build configuration, but I think it's best if we prevent (or at least) warn anybody (future me) from enabling a known-bad combination.

**Comment by etphipp** [comment] 2022-12-15 17:39
A warning would be good.  I don't want to disallow it in TriBITS though because that makes it more difficult to experiment with it by turning it back on.  And I don't want to disable this in GPU builds in general, just the RDC build as it is fine for non-RDC builds.

**Comment by sebrowne** [comment] 2022-12-19 14:01
@etphipp do you want to leave this open?  I'm satisfied with the disable approach in #11394 for the nightly build

**Comment by etphipp** [comment] 2022-12-19 14:51
Closing.

**Closed by etphipp** 2022-12-19 14:51 UTC
Labels: type: bug, pkg: Stokhos, impacting: configure or build
