### ISSUE TITLE
MueLu: unit tests are not compiling if Kokkos is disabled

### ISSUE THREAD

**Issue by tawiesn** [trilinos/Trilinos#522] opened 2016-07-25 15:11 UTC
It says

> ‘initialize’ is not a member of ‘Kokkos’

See http://testing.sandia.gov/cdash/viewBuildError.php?buildid=2514149

**Comment by tawiesn** [comment] 2016-07-25 15:13
One possibility would be to check whether Kokkos is enabled. But do we have to call Kokkos::initialize and finalize explicitly? 
@mhoemmen Can you comment on this? Isn't the node initializing and finalizing Kokkos if necessary?

**Comment by mhoemmen** [comment] 2016-07-25 17:07
> @mhoemmen Do we have to call Kokkos::initialize and finalize explicitly or is this automatically done by the Node if necessary? Couldn't we skip the initialize and finalize in the unit tests then?

Node does call Kokkos::initialize and Kokkos::finalize explicitly, if necessary.  See also #513 (now fixed).

The problem is calling Kokkos::initialize after Kokkos::finalize.  Suppose that you have a .cpp file with two unit tests.  If the first one invokes Node's constructor explicitly, then the Node instance will go away at the end of the test.  Node's destructor will then call Kokkos::finalize.  The next unit test will thus violate Kokkos' requirement by calling Kokkos::initialize again.

There are three ways to avoid this issue:

1. Never create or handle Node instances explicitly
2. Use Tpetra::Map (preferred) or KokkosClassic::Details::getNode (NOT preferred, will go away at some point) to create Node instances.  This keeps around a static Node instance, so Kokkos::finalize won't get called until main() exits.
3. Write your own unit test main() function, that calls Kokkos::initialize and Kokkos::finalize explicitly.

**Comment by tawiesn** [comment] 2016-07-25 21:40
MueLu unit tests follow option 3, that is we have our own unit test main routine where we call Kokkos::initialize and Kokkos::finalize. We have to guard these calls.

**Comment by mhoemmen** [comment] 2016-07-25 21:47
> We have to guard these calls.

That's right.  I prefer that to the "fake Kokkos" approach.

**Comment by lucbv** [comment] 2019-08-30 22:32
@trilinos/muelu
I feel this has long been resolved since @csiefert create `MueLu_test_ETI.hpp` which takes care of the initialization of `Kokkos` in tests. I tentatively close this but if it needs to be reopened, feel free to do so.

**Closed by lucbv** 2019-08-30 22:32 UTC
Labels: pkg: MueLu, stage: ready, type: bug
