### ISSUE TITLE
PyTrilinos: libpytrilinos.so, undefined symbols

### ISSUE THREAD

**Issue by sagitter** [trilinos/Trilinos#866] opened 2016-11-20 21:26 UTC
Hi all.

`libpytrilinos.so` library has various undefined symbols:

```
$ ldd -r /usr/lib64/libpytrilinos.so.12.8.1
	linux-vdso.so.1 (0x00007fff581e4000)
	libtpetra.so.12 => /lib64/libtpetra.so.12 (0x00007fc73aa3f000)
	libepetraext.so.12 => /lib64/libepetraext.so.12 (0x00007fc73a70f000)
	libepetra.so.12 => /lib64/libepetra.so.12 (0x00007fc73a3ba000)
	libteuchoscomm.so.12 => /lib64/libteuchoscomm.so.12 (0x00007fc73a154000)
	libteuchosparameterlist.so.12 => /lib64/libteuchosparameterlist.so.12 (0x00007fc739b3d000)
	libteuchoscore.so.12 => /lib64/libteuchoscore.so.12 (0x00007fc7398e0000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc739558000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc739341000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc738f7e000)
	libtpetrakernels.so.12 => /lib64/libtpetrakernels.so.12 (0x00007fc738723000)
	libtpetraclassicnodeapi.so.12 => /lib64/libtpetraclassicnodeapi.so.12 (0x00007fc738518000)
	libteuchosnumerics.so.12 => /lib64/libteuchosnumerics.so.12 (0x00007fc7382f2000)
	libteuchoskokkoscompat.so.12 => /lib64/libteuchoskokkoscompat.so.12 (0x00007fc7380e6000)
	libkokkoscore.so.12 => /lib64/libkokkoscore.so.12 (0x00007fc737e86000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc737b7c000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fc73794e000)
	libtriutils.so.12 => /lib64/libtriutils.so.12 (0x00007fc7376fc000)
	liblapack.so.3 => /lib64/liblapack.so.3 (0x00007fc736efc000)
	libblas.so.3 => /lib64/libblas.so.3 (0x00007fc736ca5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc736a88000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555aa02b4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc736884000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007fc736552000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007fc736312000)
undefined symbol: PyDict_SetItem	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_ValueError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_KeyError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyDict_SetItemString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyImport_ImportModule	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyType_IsSubtype	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyString_FromString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_SetAttrString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_Fetch	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_RuntimeError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_Print	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_SetString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_CallObject	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyCObject_AsVoidPtr	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_IsInstance	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_WriteUnraisable	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _Py_ZeroStruct	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyImport_ImportModuleLevel	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_Init	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyString_Format	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _PyInstance_Lookup	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _PyWeakref_CallableProxyType	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyDict_Next	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyInstance_Type	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _PyObject_New	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyInt_FromLong	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _Py_NoneStruct	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_Clear	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyDict_New	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyInt_AsLong	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_RichCompareBool	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PySequence_GetItem	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _Py_NotImplementedStruct	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PySequence_Size	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_TypeError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: Py_BuildValue	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyType_Ready	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PySequence_Concat	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyFloat_FromDouble	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_IsTrue	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyDict_GetItemString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_Free	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyBool_FromLong	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _Py_TrueStruct	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _PyObject_GetDictPtr	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyTuple_GetItem	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyFloat_Type	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_IndexError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: _PyWeakref_ProxyType	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_Malloc	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyFloat_AsDouble	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyTuple_SetItem	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyBool_Type	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyInstance_NewRaw	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_Restore	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_Type	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_Call	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyArg_UnpackTuple	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PySequence_Check	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyString_AsString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyLong_FromVoidPtr	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyCapsule_Import	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_GetAttr	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_GetAttrString	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyDict_GetItem	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_CallFunctionObjArgs	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyTuple_New	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_Str	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_Format	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyString_FromFormat	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_AttributeError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyExc_ImportError	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyTuple_Size	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyErr_Occurred	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyCObject_Type	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyString_ConcatAndDel	(/usr/lib64/libpytrilinos.so.12.8.1)
undefined symbol: PyObject_GenericGetAttr	(/usr/lib64/libpytrilinos.so.12.8.1)
```

It's built on Fedora 24 with `Python2.7`; should not it be linked to `libpython.so`?

Build log: https://kojipkgs.fedoraproject.org//work/tasks/5595/16545595/build.log

**Comment by wfspotz** [comment] 2016-11-21 15:26
This is a known issue. Adding Brent.

If you build the Trilinos library strictly for using PyTrilinos, then from within Python, PyTrilinos is loaded dynamically into an environment where all of these Python/C API functions are defined.

If you attempt to build Trilinos for a dual use for the C++ interface **and** the Python interface, you run into this problem. The pytrilinos library is included in the list with all of the other Trilinos libraries, and when you try to link, you get these undefined symbols.

The solution is to take those lists of libraries, where the Trilinos build system exports them, and remove pytrilinos from the lists. I have done this in an ad-hoc manner on projects that want the dual-use Trilinos. But a better solution would be for the Trilinos build system to automatically exclude pytrilinos from the export lists.

I am wondering if it would be possible to add an `EXCLUDE_FROM_EXPORT` option (or something similar) to the `TRIBITS_ADD_LIBRARY` CMake command?

**Comment by bartlettroscoe** [comment] 2016-11-21 15:31
> I am wondering if it would be possible to add an EXCLUDE_FROM_EXPORT option (or something similar) to the TRIBITS_ADD_LIBRARY CMake command?

Sounds like something we will need to resolve.   Are there any automated tests that can be added to PyTrilinos that could help catch this?  Without that it will be hard to know if it is fixed and to help it stay fixed.

**Comment by wfspotz** [comment] 2016-11-21 15:48
Automated tests would attempt to build a trivial executable that links against the exported list of Trilinos libraries. I believe it would fail at the linking step if `libpytrilinos` is in the list. I use the plural "tests" because we would need to test CMake exports and Makefile exports.

**Comment by ilovezfs** [comment] 2017-02-01 12:11
Any update here?

**Comment by wfspotz** [comment] 2017-02-01 14:34
@bartlettroscoe, I have wanted to fix this for some time. It seems like the TriBITS modification would be trivial.

**Comment by bangerth** [comment] 2017-06-17 16:27
Any news? The deal.II project gets about one mail per month from people complaining that they can't build, and the only thing we can do is tell them to edit their Trilinos installation by hand :-( This is compounded if they are using a Trilinos installation they can't edit (e.g., if it is provided as a module on a supercomputer).

**Comment by ibaned** [comment] 2017-06-17 16:38
@trilinos/framework there seems to be a lot of users checking up on this...

**Comment by bartlettroscoe** [comment] 2017-06-20 21:45
@wfspotz, I will contact you offline to discuss the issue.

**Comment by bartlettroscoe** [comment] 2017-06-20 23:06
@wfspotz and I talked about the problem and I think I know what can be done to address the issue.  I will create a TriBITS issue for this and then look into a solution in the next couple of days.

There is another project at ORNL called Denovo that uses TriBITS and creates Python modules but they have never had a problem like this.  Thinking about why they have never had a problem is that they always put their python SWIG wrappers into their own packages (or subpackages) and they never have any downstream client C++ packages depend on these Python SWIG wrapper SE packages.  And the never use something like `TrilinosConfig.cmake`.

At the core of the problem is the `TrilinosConfig.cmake` file (code for which I think was implemented by @bmpersc and modified by @nschloe?).  That file takes everything that Trilinos was built with and sucks it in to client projects.  A more modular and likely better long-term and more scalable approach is instead for clients to use `FIND_PACKAGE(<TrilinosPackageName>)` for just the packages that they use from an installation of Trilinos.  That way, clients would only get libraries for the packages that they directly use instead of everything that Trilinos was built and installed with.  Then, you could have a single installation of Trilinos that served a number of customers (i.e. by installing a superset of the Trilinos packages with TPL support needed by all of those clients).  In that case, you would set up `PyTrilinosConfig.cmake` to be very different from other such C/C++ packages.  Transitioning toward `FIND_PACKAGE(<TrilinosPackageName>)`  and away from `FIND_PACKAGE(Trilinos)` would become even more useful once TriBITSPub/TriBITS#63 is completed.  With some of the use cases that will be supported with that refactoring, a single `TrilinosConfig.cmake` file will not make sense anymore.
 
Being that as it may, we can still modify TriBITS to allow exclude libs like libpytrilinos from `TrilinosConfig.cmake`.  That is what I will work on in the coming days.  However, I don't think I can really test this myself since I have never been able to build PyTrilinos on the machines where I had accounts (but I have not tried in many years) so I may need help in testing a possible fix.

**Comment by bartlettroscoe** [comment] 2017-06-21 15:03
FYI: This will be addressed in the coming days tracked in TriBITSPub/TriBITS#198.

**Closed** 2021-03-24 12:16 UTC
Labels: CLOSED_DUE_TO_INACTIVITY, MARKED_FOR_CLOSURE, pkg: PyTrilinos
