### ISSUE TITLE
Zoltan2­_mjtest tests failing build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug and randomly in PR builds starting 2019-11-26

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#6412] opened 2019-12-09 18:39 UTC
## Bug Report
CC: @trilinos/zoltan2, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52
  
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-09&end=2019-12-08&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=testname&compare2=65&value2=Zoltan2_mjTest&field3=status&compare3=62&value3=Passed&field4=site&compare4=61&value4=sems-rhel7) the tests:
* Zoltan2_mjTest_geomgen_noholes_uvmOff_MPI_3
* Zoltan2_­mjTest_­geomgen_­nomjparts_­uvmOff_­MPI_­3
* Zoltan2_­mjTest_­geomgen_­uvmOff_­MPI_­3
* Zoltan2_­mjTest_­uvmOff_­MPI_­4

are failing in the build:
* Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

They are failing like this:
```console
[ascicgpu14:78755] *** End of error message ***
[ascicgpu14:78754] *** Process received signal ***
[ascicgpu14:78754] Signal: Segmentation fault (11)
[ascicgpu14:78754] Signal code: Invalid permissions (2)
[ascicgpu14:78754] Failing at address: 0x7fb942a02688
[ascicgpu14:78756] *** Process received signal ***
[ascicgpu14:78756] Signal: Segmentation fault (11)
[ascicgpu14:78756] Signal code: Invalid permissions (2)
[ascicgpu14:78756] Failing at address: 0x7f5a10a02680
```

## Current Status on CDash

* [Status of tests Zoltan2_mjTestXXX in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug for current testing day](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=today&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=testname&compare2=65&value2=Zoltan2_mjTest&field3=site&compare3=61&value3=sems-rhel7)

## Steps to Reproduce

One should be able to reproduce this failure on with a sems rhel7 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel7 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Zoltan2=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j4
```

**Comment by kddevin** [comment] 2019-12-09 19:12
@fryeguy52 Did this test include code from https://github.com/trilinos/Trilinos/pull/6406 ? 
If not, we'd like to wait until the test is re-run with this fix before jumping on this issue.  When will the test be re-run?  Thanks

@MicheldeMessieres

**Comment by bartlettroscoe** [comment] 2019-12-09 19:40
FYI: As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-10-29&end=2019-11-27&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=testname&compare3=65&value3=Zoltan2_&field4=status&compare4=61&value4=failed&field5=testoutput&compare5=95&value5=Signal%3A%20Segmentation%20fault%20(11)), these tests started failing showing this segfault on testing day 2019-11-26.  The new commits pulled that day are shown [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5050699#!#note2).  Looking at those commits, the following PRs merged the day before may have caused this:

* PR #5332: @MicheldeMessieres 

NOTE: The above query links are to the testing-dev.sandia.gov/cdash/ site since the testing.sandia.gov/cdash/ site seems to be not responding very well.

And we can look at the results today shown [here](https://testing-dev.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=5074849) which **does** contain the merged PR #6406 as shown [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5074824#!#note2).

Therefore, it looks like this issue is not resolved.

FYI: We will likely be disabling many of these cuda+complex tests in this ATDM Trilinos build because the ATDM APPs don't use them.

**Comment by kddevin** [comment] 2019-12-09 19:41
Thanks for the clarification @bartlettroscoe 
@MicheldeMessieres is looking at the issue today.

**Comment by kddevin** [comment] 2019-12-09 20:46
@bartlettroscoe :  @MicheldeMessieres was unable to reproduce these problems on white.  Can he access the sems-rhel7 machine on which these tests were run?  Thanks.

**Comment by MicheldeMessieres** [comment] 2019-12-09 20:49
@kddevin @bartlettroscoe  Just realized my complex option was not enabling in CMake. Starting a clean build resolved the issue. So if complex is causing the bug I may reproduce it. I did not test complex before.  Otherwise on white I have ride and and Pascal60 so might need new access to a machine. I'll post as soon as this build completes.

**Comment by MicheldeMessieres** [comment] 2019-12-09 21:57
@kddevin @bartlettroscoe Still all passing for me so I think I'll need to get access to a machine which can load sems-rhel7 and the Volta70 GPU.

**Comment by bartlettroscoe** [comment] 2019-12-11 23:14
FYI: It looks like one of these randomly failing tests `Zoltan2_mjTest_geomgen_nomjparts_MPI_3` is impacting the standard post CI build as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-11&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Continuous&field2=buildname&compare2=61&value2=Linux-GCC-4.8.4-MPI_RELEASE_DEBUG_SHARED_PT_OPENMP_CI&field3=status&compare3=61&value3=failed) showing 2 failures in since 2019-12-04.  And it looks like this test has killed several Trilinos PR iterations (5 total) since 2019-11-21 as shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-11&filtercount=3&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=testname&compare2=61&value2=Zoltan2_mjTest_geomgen_nomjparts_MPI_3&field3=status&compare3=61&value3=failed).

@trilinos/framework,

You may want to disable this test in PR testing until it can be verifiablely fixed so that it does not bring down other PR testing iterations.

**Comment by MicheldeMessieres** [comment] 2019-12-12 01:38
@bartlettroscoe @kddevin I opened up #6440 to track the randomly failing Zoltan2_mjTest_geomgen_nomjparts_MPI_3. We had indeterminate results in MJ even before #5332 but the new tests run twice and self compare to catch this. I thought I had eliminated all of these. So it might be reasonable to disable temporarily as it looks like we're still generating valid partitions, just not always the exact same results. I will resolve it.

**Comment by MicheldeMessieres** [comment] 2019-12-12 17:28
@bartlettroscoe @kddevin  I believe this one is now resolved if I'm reading the cdash right. Fix #6431 I expect also repaired this though perhaps for different reasons. There was a pure device buffer being sent to the reduceAll for the UVM off tests.

**Comment by bartlettroscoe** [comment] 2019-12-12 18:23
CC: @kddevin 

@MicheldeMessieres, I agree.  Looks like these tests are fixed as shown on CDash [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-12-12&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=testname&compare2=65&value2=Zoltan2_mjTest&field3=site&compare3=61&value3=sems-rhel7) showing:

Test Name | Status | Time | Proc Time | Details | Build Time | Processors 
-- | -- | -- | -- | -- | -- | -- 
Zoltan2_mjTestPremigrate_MPI_4 | Passed | 7s 80ms | 28s 320ms | Completed | 2019-12-12T03:33:14 MST | 4
Zoltan2_mjTest_geomgen_MPI_3 | Passed | 6s 330ms | 18s 990ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_noholes_MPI_3 | Passed | 6s 470ms | 19s 410ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_noholes_uvmOff_MPI_3 | Passed | 6s 260ms | 18s 780ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_nomjparts_MPI_3 | Passed | 6s 330ms | 18s 990ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_nomjparts_odd_MPI_3 | Passed | 6s 240ms | 18s 720ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_nomjparts_odd_uvmOff_MPI_3 | Passed | 6s 320ms | 18s 960ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_nomjparts_uvmOff_MPI_3 | Passed | 6s 350ms | 19s 50ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_geomgen_uvmOff_MPI_3 | Passed | 6s 190ms | 18s 570ms | Completed | 2019-12-12T03:33:14 MST | 3
Zoltan2_mjTest_MPI_4 | Passed | 6s 590ms | 26s 360ms | Completed | 2019-12-12T03:33:14 MST | 4
Zoltan2_mjTest_simple_rectilinear_boxes_MPI_4 | Passed | 6s 620ms | 26s 480ms | Completed | 2019-12-12T03:33:14 MST | 4
Zoltan2_mjTest_uvmOff_MPI_4 | Passed | 6s 610ms | 26s 440ms | Completed | 2019-12-12T03:33:14 MST | 4

However, can we also assume that the random failures are addressed as well?  But I guess we have the new issue #6440 that covers that so I think we can close this issue #6422 

Closing as complete.

Thanks!

FYI: I have left Zoltan2 enabled in this cuda+complex build.

**Comment by bartlettroscoe** [comment] 2019-12-12 18:23
Closing as complete for real.

**Closed by bartlettroscoe** 2019-12-12 18:23 UTC
Labels: ATDM Sev: Blocker, PA: Data Services, client: ATDM, pkg: Zoltan2, type: bug

**Comment by bartlettroscoe** [comment] 2019-12-17 22:03
@rppawlo, @bathmatt, @kddevin,

Were the changes to Zoltan2 that broke these Zoltan2 tests the same changes that broke EMPIRE's usage of Zoltan2?
