### ISSUE TITLE
Trilinos shouldn't install include/gtest/gtest.h

### ISSUE THREAD

**Issue by yurivict** [trilinos/Trilinos#10747] opened 2022-07-12 17:04 UTC
```
[22/24] Installing trilinos-13.4.0...
pkg: trilinos-13.4.0 conflicts with googletest-1.12.1 (installs files into the same place).  Problematic file: /usr/local/include/gtest/gtest.h
```

It conflicts with googletest ans shouldn't be necessary to use the library.

**Comment by cgcgcg** [comment] 2022-07-12 21:56
Duplicate of #8001?

**Comment by jhux2** [comment] 2022-08-01 17:55
Closing, since as noted, this is a duplicate of #8001.

**Closed by jhux2** 2022-08-01 17:55 UTC
Labels: type: bug
