### ISSUE TITLE
Piro: Compile error while disabling ROL and Teko

### ISSUE THREAD

**Issue by lxmota** [trilinos/Trilinos#8641] opened 2021-01-26 19:31 UTC
## Bug Report
@trilinos/piro

### Description
Compiling Trilinos with Piro enabled and ROL and Teko disabled results in this compile error:

`[100%] Building CXX object packages/piro/src/CMakeFiles/piro.dir/Piro_PerformAna
lysis.cpp.o
/home/amota/LCM/Trilinos/packages/piro/src/Piro_PerformAnalysis.cpp:85:10: fatal error: Teko_InverseLibrary.hpp: No such file or directory
   85 | #include "Teko_InverseLibrary.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

The same error is produced if Piro and ROL are enabled but not teko.

The CMake configuration is:

```
SetCTestConfiguration:ConfigureCommand:"/usr/bin/cmake"

"-DBUILD_SHARED_LIBS:BOOL=ON"

"-DCMAKE_BUILD_TYPE:STRING=DEBUG"

"-DCMAKE_CXX_COMPILER:FILEPATH=/usr/lib64/openmpi/bin/mpicxx"

"-DCMAKE_C_COMPILER:FILEPATH=/usr/lib64/openmpi/bin/mpicc"

"-DCMAKE_Fortran_COMPILER:FILEPATH=/usr/lib64/openmpi/bin/mpif90"

"-DCMAKE_INSTALL_PREFIX:PATH=/home/amota/LCM/trilinos-install-serial-gcc-debug"

"-DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF"

"-DTPL_ENABLE_MPI:BOOL=ON"

"-DTPL_ENABLE_BinUtils:BOOL=OFF"

"-DTPL_MPI_INCLUDE_DIRS:STRING=/usr/include/openmpi-x86_64"

"-DTPL_MPI_LIBRARY_DIRS:STRING=/usr/lib64/openmpi/lib"

"-DMPI_BIN_DIR:PATH=/usr/lib64/openmpi/bin"

"-DTPL_ENABLE_Boost:BOOL=ON"

"-DTPL_ENABLE_BoostLib:BOOL=ON"

"-DBoost_INCLUDE_DIRS:STRING=/usr/include/boost"

"-DBoost_LIBRARY_DIRS:STRING=/usr/lib64"

"-DBoostLib_INCLUDE_DIRS:STRING=/usr/include/boost"

"-DBoostLib_LIBRARY_DIRS:STRING=/usr/lib64"

"-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF"

"-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF"

"-DTrilinos_ENABLE_CXX11:BOOL=ON"

"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF"

"-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON"

"-DTrilinos_VERBOSE_CONFIGURE:BOOL=OFF"

"-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="

"-DTeuchos_ENABLE_STACKTRACE:BOOL=OFF"

"-DTeuchos_ENABLE_DEFAULT_STACKTRACE:BOOL=OFF"

"-DKokkos_ENABLE_CUDA_UVM:BOOL=OFF"

"-DKokkos_ENABLE_EXAMPLES:BOOL=OFF"

"-DKokkos_ENABLE_OPENMP:BOOL=OFF"

"-DKokkos_ENABLE_PTHREAD:BOOL=OFF"

"-DKokkos_ENABLE_SERIAL:BOOL=ON"

"-DKokkos_ENABLE_TESTS:BOOL=OFF"

"-DTPL_ENABLE_CUDA:STRING=OFF"

"-DTPL_ENABLE_CUSPARSE:BOOL=OFF"

"-DAmesos2_ENABLE_KLU2:BOOL=ON"

"-DROL_ENABLE_TESTS:BOOL=OFF"

"-DPhalanx_INDEX_SIZE_TYPE:STRING=INT"

"-DPhalanx_KOKKOS_DEVICE_TYPE:STRING=SERIAL"

"-DPhalanx_SHOW_DEPRECATED_WARNINGS:BOOL=OFF"

"-DTpetra_ENABLE_Kokkos_Refactor:BOOL=ON"

"-DTpetra_INST_PTHREAD:BOOL=OFF"

"-DTPL_ENABLE_HDF5:BOOL=OFF"

"-DTPL_ENABLE_HWLOC:STRING=OFF"

"-DTPL_ENABLE_Matio:BOOL=OFF"

"-DTPL_ENABLE_Netcdf:BOOL=ON"

"-DTPL_ENABLE_X11:BOOL=OFF"

"-DTPL_Netcdf_INCLUDE_DIRS:STRING=/usr/include"

"-DTPL_Netcdf_LIBRARY_DIRS:STRING=/usr/lib64"

"-DTPL_Netcdf_LIBRARIES:STRING=/usr/lib64/libnetcdf.so"

"-DTrilinos_ENABLE_Amesos2:BOOL=ON"

"-DTrilinos_ENABLE_Amesos:BOOL=OFF"

"-DTrilinos_ENABLE_Anasazi:BOOL=ON"

"-DTrilinos_ENABLE_AztecOO:BOOL=OFF"

"-DTrilinos_ENABLE_Belos:BOOL=ON"

"-DTrilinos_ENABLE_EXAMPLES:BOOL=OFF"

"-DTrilinos_ENABLE_Epetra:BOOL=OFF"

"-DTrilinos_ENABLE_EpetraExt:BOOL=OFF"

"-DTrilinos_ENABLE_Ifpack2:BOOL=ON"

"-DTrilinos_ENABLE_Ifpack:BOOL=OFF"

"-DTrilinos_ENABLE_Intrepid2:BOOL=ON"

"-DTrilinos_ENABLE_Kokkos:BOOL=ON"

"-DTrilinos_ENABLE_KokkosAlgorithms:BOOL=ON"

"-DTrilinos_ENABLE_KokkosContainers:BOOL=ON"

"-DTrilinos_ENABLE_KokkosCore:BOOL=ON"

"-DTrilinos_ENABLE_MiniTensor:BOOL=ON"

"-DTrilinos_ENABLE_ML:BOOL=OFF"

"-DTrilinos_ENABLE_MueLu:BOOL=ON"

"-DTrilinos_ENABLE_NOX:BOOL=ON"

"-DTrilinos_ENABLE_OpenMP:BOOL=OFF"

"-DTrilinos_ENABLE_Pamgen:BOOL=ON"

"-DTrilinos_ENABLE_Phalanx:BOOL=ON"

"-DTrilinos_ENABLE_Piro:BOOL=ON"

"-DTrilinos_ENABLE_ROL:BOOL=OFF"

"-DTrilinos_ENABLE_Rythmos:BOOL=ON"

"-DTrilinos_ENABLE_SEACAS:BOOL=ON"

"-DTrilinos_ENABLE_SEACASAprepro_lib:BOOL=ON"

"-DTrilinos_ENABLE_STKExprEval:BOOL=ON"

"-DTrilinos_ENABLE_STKIO:BOOL=ON"

"-DTrilinos_ENABLE_STKMesh:BOOL=ON"

"-DTrilinos_ENABLE_Sacado:BOOL=ON"

"-DTrilinos_ENABLE_Shards:BOOL=ON"

"-DTrilinos_ENABLE_Stratimikos:BOOL=ON"

"-DTrilinos_ENABLE_TESTS:BOOL=OFF"

"-DTrilinos_ENABLE_Teko:BOOL=OFF"

"-DTrilinos_ENABLE_Tempus:BOOL=ON"

"-DTrilinos_ENABLE_Teuchos:BOOL=ON"

"-DTrilinos_ENABLE_Thyra:BOOL=ON"

"-DTrilinos_ENABLE_Tpetra:BOOL=ON"

"-DTrilinos_ENABLE_Zoltan2:BOOL=OFF"

"-DTrilinos_ENABLE_Zoltan:BOOL=ON"

"-DTempus_ENABLE_TESTS:BOOL=OFF"

"-DTempus_ENABLE_EXAMPLES:BOOL=OFF"

"-DTempus_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON"

"-DTpetra_INST_INT_LONG_LONG:BOOL=ON"

"-DTpetra_INST_INT_INT:BOOL=OFF"

"-DTpetra_INST_INT_LONG:BOOL=OFF"

"-DTrilinos_ENABLE_DataTransferKit:BOOL=ON"

"-DDataTransferKit_ENABLE_DBC:BOOL=ON"

"-DDataTransferKit_ENABLE_TESTS:BOOL=OFF"

"-DDataTransferKit_ENABLE_EXAMPLES:BOOL=OFF"

"-DTPL_ENABLE_MOAB:BOOL=OFF"

"-DTPL_ENABLE_Libmesh:BOOL=OFF"

"-DTrilinos_EXTRA_REPOSITORIES:STRING=DataTransferKit" "-GUnix Makefiles" "/home/amota/LCM/Trilinos"

```

**Comment by ikalash** [comment] 2021-01-26 20:07
Hmmm, this is odd.  @mperego, were any changes made to Piro or ROL recently that would cause this behavior?  Or perhaps there were some changes to Teko - tagging @eric-c-cyr ?  I haven't made any changes to Piro for awhile but maybe you have been making some for the Hessians/optimization @mperego ?

**Comment by kliegeois** [comment] 2021-01-26 20:31
This must be related to my PR. I can resolve this.

**Comment by ikalash** [comment] 2021-01-26 22:56
Thank you @kliegeois that would be great if you could look at / fix it.

**Comment by kliegeois** [comment] 2021-01-29 15:34
This should have been resolved now.

**Comment by ikalash** [comment] 2021-01-29 16:37
Thank you @kliegeois .  We won't know until Monday if the problem is fixes (the nightlies where this was showing up do not run over the weekend).  I will check Monday morning and close the issue if things are good.

**Comment by kliegeois** [comment] 2021-01-29 16:48
Thanks @ikalash !

**Comment by kliegeois** [comment] 2021-02-01 07:31
I reopened this issue as my commit message closed it automatically.

@ikalash feels free to close it if needed.

**Comment by ikalash** [comment] 2021-02-01 16:32
The issue has been resolved.  Thanks again @kliegeois !

**Closed by ikalash** 2021-02-01 16:32 UTC
Labels: client: LCM, pkg: Piro, type: bug
