### ISSUE TITLE
KokkosSparse::CrsMatrix Default SizeType

### ISSUE THREAD

**Issue by mndevec** [trilinos/Trilinos#153] opened 2016-02-24 14:53 UTC
SizeType in the KokkosSparse::CrsMatrix is set with default 
--- SizeType = typename ViewTraits< DataType*, Arg1Type, Arg2Type, void >::size_type. 
This default appears to be size_t when run on Host, which is the default used by tpetra as well.

This makes default OrdinalType int, and SizeType as size_t at Kokkos CrsMatrix (Columns are stored as int's while row pointers are stored as size_t.). This causes problems when calling TPL's like MKL that expects same data type for those (Which is also the case for cuSPARSE).

As the matrix is sparse, wouldn't it be better to use the default SizeType as OrdinalType?
@crtrott @mhoemmen  @srajama1 @egboman  @aprokop @ambrad

**Comment by crtrott** [comment] 2016-02-24 17:00
The issue is that the size type has to be able to capture NNZ while the ordinal type only has to capture number of columns/rows. In particular when looping over a single row (i.e. you get a RowView from the matrix) its much faster to use int than size_t on many architectures. On the other hand imagining >2B nnz in a matrix is not too hard anymore considering that we have nodes with half a terabyte.

**Comment by mndevec** [comment] 2016-02-24 17:36
I understand that issue. However, current default case causes deep copies in most TPL calls, and they will fail in the case you mention. I was wondering if the general and default use case really requires SizeType to be size_t.

**Comment by egboman** [comment] 2016-02-24 17:47
Do you suggest the default SizeType should be OrdinalType, so in a typical use case they are both int? How does Tpetra handle this issue?

**Comment by crtrott** [comment] 2016-02-24 17:53
Tpetra is effectively using the size_type of the Kokkos memory space (i.e. size_t on HostSpace and int on Cuda).

**Comment by crtrott** [comment] 2016-02-24 17:57
Here are options: 
i) we use GlobalOrdinal Type as our offset type
ii) We use LocalOrdinal type as our offset type
iii) We add another template parameter :-(
iv) We have a configure option to set this

All options are bad for different reasons:
i) One is kind of bad since we were actually hoping to get rid of that and just always use some 64 bit integer type for global ordinal, since there is little down side to that. 
ii) Is bad since it means we need to go to 64 bit Local Ordinals for pretty much all the new architectures if you don't just want to run out of HBW. 
iii) is bad because it is another template parameter.

**Comment by aprokop** [comment] 2016-02-25 00:37
Mark's patches in #147 implement a fix for it, making offset indices type be that of col indices (i.e., LocalOrdinal).

@crtrott Why do we need 64-bit local ordinals? In the situation with 0.5TB of memory per node, do we really assume running a single MPI rank on it?

**Comment by crtrott** [comment] 2016-02-25 00:47
I said we need 64bit offsets not local ordinals. Local Ordinal must cover numRows. Offset must cover NNZ. With 32 bit integers for both offset and local ordinal we are limited to 24GB for a linear system which is only 5% of a Coral Node. With 64 bit offsets but 32 bit local ordinals we can easily cover half a terabyte, while still keeping all index calculations in a row view to 32 bit.

**Comment by crtrott** [comment] 2016-02-25 00:48
Also going to 64 bit local ordinals will cost us 30% performance on SPMV.

**Comment by aprokop** [comment] 2016-02-25 02:47
> I said we need 64bit offsets not local ordinals

Sorry, that's what I meant. Thank you for mentioning Coral, I did not realize the size of its memory. A configure option would then make more sense. Should we have something saying whether you are going to run Trilinos on a large HPC cluster, or on a home workstation? For the later case, you may want to switch things to 32-bit stuff, while for the later to 64. We kind of already have such implicit option through Tpetra ETI for GlobalOrdinal.

**Comment by mhoemmen** [comment] 2016-02-26 03:54
Sorry for getting into this conversation late -- lots of stuff happened over the past 24 hours.  If we're doing to do the inspector-executor interface with MKL anyway, we could do the following:

- If # entries in an MPI process won't fit in MKL_INT, use our native kernels.
- Otherwise, copy offsets into MKL_INT and invoke inspector-executor tuning interface at fillComplete.

This is more complicated, but it makes all of this a run-time decision, rather than adding more template parameters.

**Comment by mhoemmen** [comment] 2016-03-17 07:49
Hey @mndevec -- did you mean to close this one?  Not sure if we actually have fixed this yet.

**Comment by mhoemmen** [comment] 2016-06-09 20:40
@mndevec I'm thinking about this again.  I think a reasonable way to fix this, is to treat it like any other extra data that a TPL may need.  That is, if the row offsets type _we_ use does not match the row offsets type the TPL uses, then we make a deep copy of the row offsets and stash them in the TPL handle (that Tpetra will keep).

We only need to copy the row offsets at first fillComplete.  The graph isn't allowed to change on subsequent fillComplete calls.  Total extra storage is half that of a double-precision vector that stores the result of a sparse mat-vec (assuming `MKL_INT == int`).  Also, at copy time, we can test whether the matrix is too big, and call our sparse mat-vec implementation instead of MKL if it is.

**Comment by mhoemmen** [comment] 2016-06-09 20:40
Thus, I'll close this issue unless somebody wishes to reopen discussion.

**Closed by mhoemmen** 2016-06-09 20:40 UTC
Labels: Tpetra
