### ISSUE TITLE
SpMV performance difference between Tpetra and Epetra

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#7616] opened 2020-07-01 18:52 UTC
Using's MueLu scaling driver, Trilinos develop `d0684fdb`, I've observed about a 4x difference in SpMV performance between Epetra and Tpetra:

```
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.529216 - 99.6897% [1]
|   |   |   Belos: Operation Op*x: 0.229234 - 43.3157% [1000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.158566 - 69.1721% [1000]
|   |   |   |   Remainder: 0.0706679 - 30.8279%
|   |   |   Remainder: 0.299982 - 56.6843%
|   |   Remainder: 0.00113784 - 0.214338%
```

```
|   |   Belos: PseudoBlockCGSolMgr total solve time: 2.41673 - 99.9169% [1]
|   |   |   Tpetra::MV ctor (map,numVecs,zeroOut): 0.00112069 - 0.0463721% [4]
|   |   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.960608 - 39.7482% [3002]
|   |   |   Tpetra::MV::dot (Teuchos::ArrayView): 0.421893 - 17.4572% [2001]
|   |   |   |   Tpetra::multiVectorSingleColumnDot: 0.412475 - 97.7675% [2001]
|   |   |   |   Remainder: 0.00941887 - 2.23252%
|   |   |   Tpetra::MV::norm2 (host output): 0.118102 - 4.88684% [1001]
|   |   |   Belos: Operation Op*x: 0.889249 - 36.7955% [1000]
|   |   |   |   Tpetra::CrsMatrix::apply: 0.887847 - 99.8423% [1000]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 0.88043 - 99.1646% [1000]
|   |   |   |   |   Remainder: 0.00741739 - 0.835435%
|   |   |   |   Remainder: 0.0014023 - 0.157694%
|   |   |   Remainder: 0.0257586 - 1.06585%
|   |   Remainder: 0.000636912 - 0.0263324%
```

cmake:

```
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cee-rhel7-clang-relwithdebinfo-serial

ARGS=(
  -GNinja
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake
  -DCMAKE_BUILD_TYPE=RELWITHDEBINFO

  -DTpetra_INST_INT_INT=ON
  -DTrilinos_ENABLE_Epetra=ON
  -DMueLu_ENABLE_Epetra=ON

  -DTrilinos_ENABLE_MueLu=ON
  -DTrilinos_ENABLE_ML=ON

  -DTrilinos_ENABLE_TESTS=OFF
  -DMueLu_ENABLE_TESTS=ON
  -DMueLu_ENABLE_EXAMPLES=ON
  -DXpetra_ENABLE_Epetra=ON
  -DML_ENABLE_TESTS=ON
  -DML_ENABLE_EXAMPLES=ON
  -DAztecOO_ENABLE_EXAMPLES=ON
  -DAztecOO_ENABLE_TESTS=ON

)

cmake "${ARGS[@]}" ${TRILINOS_DIR}
```

**Comment by jhux2** [comment] 2020-07-01 18:54
I've replicated this performance difference on 4 MPI ranks.   I went as far back as `bb609d2`  (~1.5 years), and the difference persists.

**Comment by jhux2** [comment] 2020-07-01 18:56
@trilinos/kokkos-kernels @trilinos/tpetra @csiefer2

**Comment by jhux2** [comment] 2020-07-01 20:09
More data for Laplace2D, 1 MPI rank, 10K rows.

Epetra
```
|   Driver: 5 - Belos Solve: 0.218262 - 29.4029% [1]
|   |   Belos: Operation Op*x: 0.000208657 - 0.0955993% [1]
|   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.000147905 - 70.8843% [1]
|   |   |   Remainder: 6.0752e-05 - 29.1157%
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.216287 - 99.0949% [1]
|   |   |   Belos: Operation Op*x: 0.0747978 - 34.5827% [492]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.0558016 - 74.6033% [492]
|   |   |   |   Remainder: 0.0189962 - 25.3967%
|   |   |   Remainder: 0.141489 - 65.4173%
|   |   Remainder: 0.00176675 - 0.809462%
|   Remainder: 0.000478402 - 0.0644474%
```

Tpetra
```
|   Driver: 5 - Belos Solve: 0.795323 - 58.2421% [1] 
|   |   Tpetra::MV ctor (map,numVecs,zeroOut): 8.0313e-05 - 0.0100982% [1]
|   |   Belos: Operation Op*x: 0.000682506 - 0.0858149% [1] 
|   |   |   Tpetra::CrsMatrix::apply: 0.000678514 - 99.4151% [1]
|   |   |   |   Tpetra::CrsMatrix::localApply: 0.000662229 - 97.5999% [1]
|   |   |   |   Remainder: 1.6285e-05 - 2.4001%
|   |   |   Remainder: 3.992e-06 - 0.584903%
|   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.000176429 - 0.0221833% [1]
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.792962 - 99.7031% [1]
|   |   |   Tpetra::MV ctor (map,numVecs,zeroOut): 0.00035386 - 0.0446251% [4]
|   |   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.259062 - 32.6701% [1556]
|   |   |   Tpetra::MV::dot (Teuchos::ArrayView): 0.127099 - 16.0284% [1037]
|   |   |   |   Tpetra::multiVectorSingleColumnDot: 0.117226 - 92.232% [1037]
|   |   |   |   Remainder: 0.00987307 - 7.76799%
|   |   |   Tpetra::MV::norm2 (host output): 0.0337977 - 4.26221% [519]
|   |   |   Belos: Operation Op*x: 0.347229 - 43.7889% [518]
|   |   |   |   Tpetra::CrsMatrix::apply: 0.34601 - 99.649% [518]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 0.339105 - 98.0044% [518]
|   |   |   |   |   Remainder: 0.00690485 - 1.99556%
|   |   |   |   Remainder: 0.00121892 - 0.351043%
|   |   |   Remainder: 0.0254206 - 3.20578%
|   |   Remainder: 0.00142178 - 0.178767%
|   Remainder: 0.00238805 - 0.174879

**Comment by srajama1** [comment] 2020-07-01 23:15
@lucbv : Can you help with this please ?

**Comment by jhux2** [comment] 2020-07-01 23:17
Interesting data point:  @csiefer2 sees similar behavior, but @cgcgcg doesn't.

**Comment by lucbv** [comment] 2020-07-02 00:36
@srajama1 
Yep, we actually already discussed this on the MueLu side. I will try to reproduce these results on my workstation and then look at why the host implementation is not more effective in Serial.

**Comment by lucbv** [comment] 2020-07-02 05:28
So I did a build using the recipe given by @jhux2 here is the results:
### Tpetra
```
Belos: Operation Op*x                                                                      0.1139 (353)
```
### Epetra
```
Belos: Operation Op*x                                                                      0.02779 (347)
```
I guess it also shows about 4x~5x difference in favor of Epetra. I will be able to look into what Kokkos-kernels does and let you know what looks incorrect in the implementation. Of course first idea is to implement a naive approach for the serial backend which would likely perform about as well as the default serial algorithm in Epetra?

**Comment by lucbv** [comment] 2020-07-02 05:30
@jhux2 what timers did you enable? Also at the moment I am running the following command line:
```
./MueLu_Driver.exe --matrixType=Laplace2D --nx=100 --ny=100 --no-solve-preconditioned --its=1000 --linAlgebra=Epetra
```
Does that seem reasonable compared to what you ran?

**Comment by jhux2** [comment] 2020-07-02 15:12
@lucbv Yes, that's what I tested.

**Comment by jhux2** [comment] 2020-07-02 16:21
I rebuilt using gcc 9.2:

```
mpirun -np 1 ./MueLu_Driver.exe --linAlgebra=[ET]petra --nx=100 --ny=100 --matrixType=Laplace2D --stacked-timer --noscale --no-solve-preconditioned --its=1000 --tol=1e-100
```

**Epetra**
```
|   Driver: 5 - Belos Solve: 0.174305 - 70.476% [1]
|   |   Belos: Operation Op*x: 0.000176338 - 0.101167% [1]
|   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.00011863 - 67.2742% [1]
|   |   |   Remainder: 5.7708e-05 - 32.7258%
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.170107 - 97.5916% [1]
|   |   |   Belos: Operation Op*x: 0.0862163 - 50.6837% [1000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.0563593 - 65.3696% [1000]
|   |   |   |   Remainder: 0.029857 - 34.6304%
|   |   |   Remainder: 0.0838904 - 49.3163%
|   |   Remainder: 0.00402155 - 2.3072%
|   Remainder: 0.00120601 - 0.487621%
```

**Tpetra**

```
|   Driver: 5 - Belos Solve: 0.296309 - 74.9437% [1]
|   |   Tpetra::MV ctor (map,numVecs,zeroOut): 0.000197469 - 0.0666429% [1]
|   |   Belos: Operation Op*x: 0.000209544 - 0.0707181% [1]
|   |   |   Tpetra::CrsMatrix::apply: 0.000199488 - 95.201% [1]
|   |   |   |   Tpetra::CrsMatrix::localApply: 0.000188859 - 94.6719% [1]
|   |   |   |   Remainder: 1.0629e-05 - 5.32814%
|   |   |   Remainder: 1.0056e-05 - 4.79899%
|   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.000171091 - 0.0577407% [1]
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.293269 - 98.9741% [1]
|   |   |   Tpetra::MV ctor (map,numVecs,zeroOut): 1.5696e-05 - 0.00535208% [4]
|   |   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.0731519 - 24.9436% [3002]
|   |   |   Tpetra::MV::dot (Teuchos::ArrayView): 0.0383788 - 13.0865% [2001]
|   |   |   |   Tpetra::multiVectorSingleColumnDot: 0.0351029 - 91.4644% [2001]
|   |   |   |   Remainder: 0.00327588 - 8.53564%
|   |   |   Tpetra::MV::norm2 (host output): 0.0162037 - 5.52521% [1001]
|   |   |   Belos: Operation Op*x: 0.148461 - 50.6228% [1000]
|   |   |   |   Tpetra::CrsMatrix::apply: 0.146461 - 98.6531% [1000]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 0.142712 - 97.4402% [1000]
|   |   |   |   |   Remainder: 0.00374906 - 2.55976%
|   |   |   |   Remainder: 0.00199962 - 1.3469%
|   |   |   Remainder: 0.0170581 - 5.81652%
|   |   Remainder: 0.00246167 - 0.830779%
|   Remainder: 0.00191287 - 0.483811%
```

**Comment by jhux2** [comment] 2020-07-02 16:23
This is definitely better, but still about a 2x difference.

**Comment by cgcgcg** [comment] 2020-07-02 16:27
Same on geminga:
**Epetra**
```
|   Driver: 5 - Belos Solve: 0.167271 - 66.603% [1]
|   |   Belos: Operation Op*x: 8.8676e-05 - 0.0530135% [1]
|   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 5.5064e-05 - 62.0957% [1]
|   |   |   Remainder: 3.3612e-05 - 37.9043%
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.165504 - 98.9438% [1]
|   |   |   Belos: Operation Op*x: 0.0781587 - 47.2247% [1000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.0511637 - 65.4612% [1000]
|   |   |   |   Remainder: 0.0269951 - 34.5388%
|   |   |   Remainder: 0.0873453 - 52.7753%
|   |   Remainder: 0.00167802 - 1.00318%
|   Remainder: 0.00107961 - 0.429875%
```
**Tpetra**
```
|   Driver: 5 - Belos Solve: 0.202385 - 74.4162% [1]
|   |   Belos: Operation Op*x: 0.000126753 - 0.0626295% [1]
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.201153 - 99.3908% [1]
|   |   |   Belos: Operation Op*x: 0.0971484 - 48.2959% [1000]
|   |   |   Remainder: 0.104004 - 51.7041%
|   |   Remainder: 0.00110609 - 0.546527%
|   Remainder: 0.00170938 - 0.62853%
```

**Comment by cgcgcg** [comment] 2020-07-02 16:28
Could the Tpetra timers lead to slow-down?

**Comment by jhux2** [comment] 2020-07-02 16:43
I am wondering if this is a difference in compiler versions, or if the ATDM scripts are resulting in a different environment.

**Comment by jhux2** [comment] 2020-07-02 17:17
gcc 7.2, using @cgcgcg's configure script.

**Epetra**
```
|   Driver: 5 - Belos Solve: 0.157956 - 72.7816% [1]
|   |   Belos: Operation Op*x: 8.4407e-05 - 0.0534371% [1]
|   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 5.7204e-05 - 67.7716% [1]
|   |   |   Remainder: 2.7203e-05 - 32.2284%
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.155918 - 98.71% [1]
|   |   |   Belos: Operation Op*x: 0.0860124 - 55.1651% [1000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.0593161 - 68.9622% [1000]
|   |   |   |   Remainder: 0.0266963 - 31.0378%
|   |   |   Remainder: 0.0699057 - 44.8349%
|   |   Remainder: 0.00195321 - 1.23655%
|   Remainder: 0.000603125 - 0.277903%
```

**Tpetra**

```
|   Driver: 5 - Belos Solve: 0.194567 - 77.1156% [1]
|   |   Tpetra::MV ctor (map,numVecs,zeroOut): 0.000103234 - 0.0530583% [1]
|   |   Belos: Operation Op*x: 0.000108498 - 0.0557638% [1]
|   |   |   Tpetra::CrsMatrix::apply: 0.000106359 - 98.0285% [1]
|   |   |   |   Tpetra::CrsMatrix::localApply: 0.000102951 - 96.7958% [1]
|   |   |   |   Remainder: 3.408e-06 - 3.20424%
|   |   |   Remainder: 2.139e-06 - 1.97146%
|   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 5.2568e-05 - 0.0270179% [1]
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.193489 - 99.4461% [1]
|   |   |   Tpetra::MV ctor (map,numVecs,zeroOut): 9.289e-06 - 0.00480078% [4]
|   |   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.0384443 - 19.869% [3002]
|   |   |   Tpetra::MV::dot (Teuchos::ArrayView): 0.0253743 - 13.1141% [2001]
|   |   |   |   Tpetra::multiVectorSingleColumnDot: 0.0237243 - 93.4972% [2001]
|   |   |   |   Remainder: 0.00165003 - 6.50277%
|   |   |   Tpetra::MV::norm2 (host output): 0.0121507 - 6.2798% [1001]
|   |   |   Belos: Operation Op*x: 0.10903 - 56.3493% [1000]
|   |   |   |   Tpetra::CrsMatrix::apply: 0.108022 - 99.0759% [1000]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 0.105988 - 98.1165% [1000]
|   |   |   |   |   Remainder: 0.00203458 - 1.88348%
|   |   |   |   Remainder: 0.00100752 - 0.924078%
|   |   |   Remainder: 0.0084807 - 4.38303%
|   |   Remainder: 0.000813424 - 0.418069%
|   Remainder: 0.00137399 - 0.544575%
```

**Comment by lucbv** [comment] 2020-07-02 17:21
Yep it's a lot closer with @cgcgcg script... any obvious way to export what is being set by ATDM configuration scripts?
I am guessing it's a no? Should we also look at CMakeCache.txt?

**Comment by jhux2** [comment] 2020-07-02 17:49
I've rerun the gcc-9.2 exec with a larger problem and more iterations:

```
mpirun -np 1 ./MueLu_Driver.exe --linAlgebra=[TE]petra --nx=200 --ny=200 --matrixType=Laplace2D --stacked-timer --noscale --no-solve-preconditioned --its=5000 --tol=1e-200
```

The results are *much* closer now:

**Epetra**
```
|   |   |   Belos: Operation Op*x: 1.37888 - 51.9025% [5000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.926539 - 67.1949% [5000]
|   |   |   |   Remainder: 0.452344 - 32.8051%
|   |   |   Remainder: 1.2778 - 48.0975%
```

**Tpetra**
```
|   |   |   Belos: Operation Op*x: 1.48581 - 51.6447% [5000]
|   |   |   |   Tpetra::CrsMatrix::apply: 1.47998 - 99.608% [5000]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 1.46965 - 99.3022% [5000]
|   |   |   |   |   Remainder: 0.0103274 - 0.697808%
|   |   |   |   Remainder: 0.00582468 - 0.392021%
|   |   |   Remainder: 0.0483089 - 1.67915%
```

**Comment by cgcgcg** [comment] 2020-07-02 19:33
I'm now using this on Geminga:
```
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh clang-opt-serial

cmake \                                                                                                                                                                                                                                                                                                                                       
            -D Trilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \                                                                                                                                                                                                                                                               
            -D CMAKE_BUILD_TYPE:STRING="RELEASE" \                                                                                                                                                                                                                                                                                                    
            -D Trilinos_ENABLE_TESTS:BOOL=OFF \                                                                                                                                                                                                                                                                                                       
            -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \                                                                                                                                                                                                                                                                                                    
            -D Trilinos_ENABLE_Epetra:BOOL=ON \                                                                                                                                                                                                                                                                                                       
            -D Xpetra_ENABLE_Epetra:BOOL=ON \                                                                                                                                                                                                                                                                                                         
            -D MueLu_ENABLE_Epetra:BOOL=ON \                                                                                                                                                                                                                                                                                                          
            -D Trilinos_ENABLE_MueLu:BOOL=ON \                                                                                                                                                                                                                                                                                                        
            -D MueLu_ENABLE_TESTS:STRING=ON \                                                                                                                                                                                                                                                                                                         
            -D MueLu_ENABLE_EXAMPLES:STRING=ON \                                                                                                                                                                                                                                                                                                      
            -D Tpetra_INST_INT_INT:BOOL=ON \                                                                                                                                                                                                                                                                                                          
            -G Ninja \                                                                                                                                                                                                                                                                                                                                
             $TRILINOS_DIR 
```
and I see no difference between Epetra and Tpetra.

**Comment by GeoffDanielson** [comment] 2020-07-10 17:28
On eclipse (using Intel's mpicc):

``
# Load relevant modules
module load cmake/3.12.2

# Configure Trilinos
export TRILINOS_HOME=/ascldap/users/gcdanie/Trilinos

cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D Amesos2_ENABLE_KLU2:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
-D MueLu_ENABLE_TEST:STRING=ON \
-D MueLu_ENABLE_EXAMPLES=ON \
-D MueLu_ENABLE_Kokkos_Refactor:STRING=OFF \
-D MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:STRING=OFF \
-D Xpetra_ENABLE_Epetra=ON \
-D Xpetra_ENABLE_Tpetra=ON \
-D Tpetra_INST_INT_INT=ON \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_BASE_DIR:FILEPATH=$MPIROOT \
-D MPI_EXEC:FILEPATH="/opt/openmpi/1.10/intel/bin/mpiexec" \
${TRILINOS_HOME}
``

Epetra:
``
|   Driver: 5 - Belos Solve: 0.150907 - 65.684% [1]
|   |   Belos: Operation Op*x: 8.1286e-05 - 0.053865% [1]
|   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 5.7927e-05 - 71.2632% [1]
|   |   |   Remainder: 2.3359e-05 - 28.7368%
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.136082 - 90.176% [1]
|   |   |   Belos: Operation Op*x: 0.0784592 - 57.6559% [1000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.058115 - 74.0704% [1000]
|   |   |   |   Remainder: 0.0203442 - 25.9296%
|   |   |   Remainder: 0.0576226 - 42.3441%
|   |   Remainder: 0.0147438 - 9.77014%
|   Remainder: 0.00540495 - 2.35257%
``

Tpetra:
``
|   Driver: 5 - Belos Solve: 0.13595 - 72.7171% [1]
|   |   Tpetra::MV ctor (map,numVecs,zeroOut): 4.505e-06 - 0.00331372% [1]
|   |   Belos: Operation Op*x: 7.9104e-05 - 0.0581861% [1]
|   |   |   Tpetra::CrsMatrix::apply: 7.4444e-05 - 94.109% [1]
|   |   |   |   Tpetra::CrsMatrix::localApply: 7.0535e-05 - 94.7491% [1]
|   |   |   |   Remainder: 3.909e-06 - 5.25093%
|   |   |   Remainder: 4.66e-06 - 5.89098%
|   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 3.9832e-05 - 0.029299% [1]
|   |   Belos: PseudoBlockCGSolMgr total solve time: 0.135354 - 99.5616% [1]
|   |   |   Tpetra::MV ctor (map,numVecs,zeroOut): 1.4451e-05 - 0.0106764% [4]
|   |   |   Tpetra::MV::update(alpha,A,beta,B,gamma): 0.0293793 - 21.7056% [3002]
|   |   |   Tpetra::MV::dot (Teuchos::ArrayView): 0.012538 - 9.26311% [2001]
|   |   |   |   Tpetra::multiVectorSingleColumnDot: 0.0102617 - 81.8451% [2001]
|   |   |   |   Remainder: 0.00227626 - 18.1549%
|   |   |   Tpetra::MV::norm2 (host output): 0.0108779 - 8.0366% [1001]
|   |   |   Belos: Operation Op*x: 0.0656038 - 48.4683% [1000]
|   |   |   |   Tpetra::CrsMatrix::apply: 0.0641364 - 97.7632% [1000]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 0.0619847 - 96.6452% [1000]
|   |   |   |   |   Remainder: 0.00215162 - 3.35476%
|   |   |   |   Remainder: 0.00146743 - 2.23681%
|   |   |   Remainder: 0.0169406 - 12.5157%
|   |   Remainder: 0.000472562 - 0.3476%
|   Remainder: 0.00108434 - 0.579995%
``

**Comment by GeoffDanielson** [comment] 2020-07-10 17:36
On eclipse (using Intel's mpicc):

```
module load cmake/3.12.2

cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D BUILD_SHARED_LIBS:BOOL=ON \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D Amesos2_ENABLE_KLU2:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Fortran:BOOL=OFF \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
-D MueLu_ENABLE_TEST:STRING=ON \
-D MueLu_ENABLE_EXAMPLES=ON \
-D MueLu_ENABLE_Kokkos_Refactor:STRING=OFF \
-D MueLu_ENABLE_Kokkos_Refactor_Use_By_Default:STRING=OFF \
-D Xpetra_ENABLE_Epetra=ON \
-D Xpetra_ENABLE_Tpetra=ON \
-D Tpetra_INST_INT_INT=ON \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_BASE_DIR:FILEPATH=$MPIROOT \
-D MPI_EXEC:FILEPATH="/opt/openmpi/1.10/intel/bin/mpiexec" \
${TRILINOS_HOME}
```

Epetra:
```
|   |   |   Belos: Operation Op*x: 0.0784592 - 57.6559% [1000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.058115 - 74.0704% [1000]
|   |   |   |   Remainder: 0.0203442 - 25.9296%
|   |   |   Remainder: 0.0576226 - 42.3441%
```

Tpetra:
```
|   |   |   Belos: Operation Op*x: 0.0656038 - 48.4683% [1000]
|   |   |   |   Tpetra::CrsMatrix::apply: 0.0641364 - 97.7632% [1000]
|   |   |   |   |   Tpetra::CrsMatrix::localApply: 0.0619847 - 96.6452% [1000]
|   |   |   |   |   Remainder: 0.00215162 - 3.35476%
|   |   |   |   Remainder: 0.00146743 - 2.23681%
|   |   |   Remainder: 0.0169406 - 12.5157%
```

**Comment by tasmith4** [comment] 2020-07-25 16:04
On a CEE EWS blade,

`module load sierra-devel` (GCC 7.2.0, OpenMPI 4.0.3)

CMake:
```
cmake \
-G Ninja \
-D CMAKE_BUILD_TYPE:STRING="RELEASE" \
\
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_BIN_DIR:PATH=${MPI_BIN} \
\
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
\
-D Trilinos_ENABLE_Tpetra:BOOL=ON \
-D Tpetra_INST_INT_INT:BOOL=ON \
-D Trilinos_ENABLE_Ifpack2:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
\
-D Trilinos_ENABLE_Zoltan2:BOOL=ON \
\
-D Trilinos_ENABLE_MueLu:BOOL=ON \
-D MueLu_ENABLE_TESTS:BOOL=ON \
\
${TRILINOS_DIR}
```

**Epetra** (`./MueLu_Driver.exe --linAlgebra=Epetra --nx=200 --ny=200 --matrixType=Laplace2D --stacked-timer --noscale --no-solve-preconditioned --its=5000 --tol=1e-200`):
```
|   |   |   Belos: Operation Op*x: 1.0411 - 48.3267% [5000]
|   |   |   |   Epetra_CrsMatrix::Multiply(TransA,X,Y): 0.779248 - 74.8485% [5000]
|   |   |   |   Remainder: 0.261853 - 25.1515%
```

**Tpetra** (`./MueLu_Driver.exe --linAlgebra=Tpetra --nx=200 --ny=200 --matrixType=Laplace2D --stacked-timer --noscale --no-solve-preconditioned --its=5000 --tol=1e-200`):
```
|   |   |   Belos: Operation Op*x: 1.19749 - 50.1338% [5000]
```

For the Tpetra run, the code did not report any child timings for Belos Op*x, although the output of MueLu_Driver does state that it is using Tpetra.  Not sure if this is indicative of problems with the run ... I'm happy to rerun if someone suggests changes to my CMake line or command-line args.

**Comment by brian-kelley** [comment] 2020-07-27 15:30
@tasmith4 That's expected, since there are no subtimers inside CrsMatrix::apply. We are really just interested in the "Op*x" total.

**Comment by mhoemmen** [comment] 2022-01-24 20:26
I'm curious what became of this.

**Comment by csiefer2** [comment] 2022-03-16 16:34
Nightly Epetra vs. Tpetra matvec performance tests on CTS1 SerialNode show Tpetra running slightly faster than Epetra through most of February (18.5 seconds vs 20.5 for some large number of Matvecs).

**Comment by csiefer2** [comment] 2022-03-16 16:35
Since our performance monitoring is back up now, I think we can close this issue.

**Closed by csiefer2** 2022-03-16 16:35 UTC
Labels: type: bug, pkg: Tpetra, impacting: performance, pkg: KokkosKernels
