### ISSUE TITLE
Failed build with trilinos-release-12-6 

### ISSUE THREAD

**Issue by BarrySmith** [trilinos/Trilinos#135] opened 2016-02-10 01:03 UTC
I'm unable to build the trilinos-release-12-6-branch 

Obtaining errors of the form 

../../../../../tpetra/core/src/libtpetra.so.12.6: undefined reference to `KokkosBlas::Impl::Update<Kokkos::View<int con\
st**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, Kokkos::Impl::Vi\
ewDefault>, Kokkos::View<int const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Me\
moryTraits<1u>, Kokkos::Impl::ViewDefault>, Kokkos::View<int**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokk\
os::HostSpace>, Kokkos::MemoryTraits<1u>, Kokkos::Impl::ViewDefault>, 2>::update(int const&, Kokkos::View<int const**, \
Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, Kokkos::Impl::ViewDefa\
ult> const&, int const&, Kokkos::View<int const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace\
>, Kokkos::MemoryTraits<1u>, Kokkos::Impl::ViewDefault> const&, int const&, Kokkos::View<int**, Kokkos::LayoutLeft, Kok\
kos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, Kokkos::Impl::ViewDefault> const&)'
../../../../../tpetra/core/src/libtpetra.so.12.6: undefined reference to `KokkosSparse::Impl::SPMV_MV<double const*, Ko\
kkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, double const, int, Kokko\
s::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, unsigned long, double const**, Kokkos::LayoutLe\
ft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<3u>, double const*, Kokkos::LayoutLeft, Kok\
kos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, double**, Kokkos::LayoutLeft, Kokkos::Device<\
Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >::spmv_mv(char const*, double const&, KokkosSparse::CrsMa\
trix<double const, int, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, unsigned long> con\
st&, Kokkos::View<double const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Memory\
Traits<3u>, Kokkos::Impl::ViewDefault> const&, double const&, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device\
<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, Kokkos::Impl::ViewDefault> const&)'

Full log including configure options and machine configuration can be found at 

ftp://ftp.mcs.anl.gov/pub/petsc/trilinos-release-12-6-failure

The same configure options have worked successfully with Trilinos 'master' branch.
@jwillenbring

**Comment by jwillenbring** [comment] 2016-02-10 14:56
@mhoemmen let me know if it would be better to have @crtrott or someone else take a look at this.

Thanks

Jim

**Comment by mhoemmen** [comment] 2016-02-11 08:19
Hi Jim!  I am not able to access Github for the next two days, due to travel.  Sorry about that!  I could look at this afterwards.

On Feb 10, 2016, at 10:57 PM, jwillenbring <notifications@github.com<mailto:notifications@github.com>> wrote:


@mhoemmen<https://github.com/mhoemmen> let me know if it would be better to have @crtrott<https://github.com/crtrott> or someone else take a look at this.

Thanks

Jim

-

**Comment by mhoemmen** [comment] 2016-02-15 02:12
@BarrySmith Hi Barry -- I was traveling Thu-Fri last week and am a bit of a jet-lagged zombie at the moment, but I'll make sure that the priority for this gets bumped.

**Comment by mhoemmen** [comment] 2016-02-15 02:13
Adding @crtrott to the CC list.

**Comment by jwillenbring** [comment] 2016-03-03 21:19
My initial attempts to reproduce this have failed. I am going back now and trying to reproduce it through the xSDK install script. My attempts to reproduce did not have all of the TPLs available, so I turned a few options off. I didn't think those were related to the error, but we will see how this other attempt goes.

**Comment by mhoemmen** [comment] 2016-03-09 11:44
Reassigning to @jwillenbring since he has been working on it.  Thanks Jim :-)

**Comment by jwillenbring** [comment] 2016-03-10 21:30
Barry,

I was not able to reproduce this. Here is what I tried:

1) I looked at your configure arguments and tried to reproduce something close by hand with a standard Trilinos build. I did not turn on all TPL's, as they weren't all quickly available, but I didn't turn off anything that I thought looked like a likely problem.
2) When that was unsuccessful, I decided since you are doing this in the context of an xsdk build, I would try to do the same. I tried to build from the xsdk install repo. That build also passed.

Did you use some special options for an xsdk build, or can you offer some other hint as to how I can reproduce this? If you send me the options you passed to the xsdk install process, that would maybe allow me to reproduce the issue.

Thanks

Jim

**Comment by jwillenbring** [comment] 2016-03-10 21:48
Per Barry's comment, I am closing this issue.

**Closed by jwillenbring** 2016-03-10 21:48 UTC
Labels: bug, Kokkos, ready, Tpetra

**Comment by mhoemmen** [comment] 2016-03-11 00:31
Praise Turing! :D
