### ISSUE TITLE
Ifpack2_unit_tests_MPI_4 randomly failing on ATDM waterman build

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4353] opened 2019-02-08 20:17 UTC
CC: @trilinos/ifpack2, @srajama1 (Trilinos Linear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=Ifpack2_unit_tests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-02-08T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2018-12-27T00%3A00%3A00) the test:
* Ifpack2_unit_tests_MPI_4

is randomly failing in the buils:
* Trilinos-atdm-waterman-cuda-9.2-opt

It has failed roughly 6 times in the last month.  Here are some examples of the output when it fails:

```
Error, relErr(Y.get1dView ()[9932],Z.get1dView ()[9932]) = relErr(29832,0) = 1 <= tol = 2.22045e-12: failed!
```

```
p=0 | The following tests FAILED:
p=0 |     48. Ifpack2OverlappingRowMatrix_default_scalar_type_default_local_ordinal_type_default_global_ordinal_type_Test0_UnitTest ... 
p=0 | 
p=0 | Total Time: 6.49 sec
p=0 | 
p=1 | Summary: total = 82, run = 82, passed = 81, failed = 1
p=1 | 
p=1 | End Result: TEST FAILED
```

## Current Status on CDash

[2 Week history of this test](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=Ifpack2_unit_tests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=tomorrow&field5=buildstarttime&compare5=83&value5=2%20weeks%20ago)

## Steps to Reproduce

One should be able to reproduce the build on waterman where this test is randomly failing as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for waterman are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#waterman

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-waterman-cuda-9.2-opt
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Ifpack2=ON \
 $TRILINOS_DIR
$ make NP=16
$ bsub -x -Is -n 20 ctest -j20
```

**Comment by mhoemmen** [comment] 2019-02-08 20:29
@jhux2 and @csiefer2 , we should look at this at some point.  I can't build all of Ifpack2 on waterman at the moment, in particular the AdditiveSchwarz tests, due to some Xpetra thing that doesn't seem to like it when I turn off `GO=int`.

**Comment by bartlettroscoe** [comment] 2019-02-08 20:38
@mhoemmen,

> I can't build all of Ifpack2 on waterman at the moment

Do the exact commands under "Steps to Reproduce" shown [above](https://github.com/trilinos/Trilinos/issues/4353#issue-408308113) not work for you?

**Comment by mhoemmen** [comment] 2019-02-08 20:39
@bartlettroscoe Thanks for the link :-) Bear with me -- I was using a custom waterman configuration, not the standard one.

**Comment by mhoemmen** [comment] 2019-02-08 20:40
@trilinos/ifpack2 Wow, somebody really wrote `relErr(Y.get1dView ()[9932],Z.get1dView ()[9932])`?

**Comment by mhoemmen** [comment] 2019-02-08 23:24
`Ifpack2::OverlappingRowMatrix` depends on the ArrayRCP access functions of `Tpetra::MultiVector`, like `get2dViewNonConst()`.  I did spend some effort trying to make those correct with respect to UVM access, but it's possible that something isn't quite right still.

**Comment by mhoemmen** [comment] 2019-02-13 17:44
PR #4393 may address this issue.

**Comment by bartlettroscoe** [comment] 2019-03-04 20:04
@mhoemmen said:

> PR #4393 may address this issue.

It seems not.  As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=Ifpack2_unit_tests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=83&value4=8%20weeks%20ago) this test failed on 2/15/2019 but the PR was merged 2/14/2019.

But this test has passed the last 14 days, but that is not proof.  Before, that, it passed 10 days in a row  in the last 8 weeks.

I think we need to wait much longer to see if this is fixed.

**Comment by bartlettroscoe** [comment] 2019-04-21 01:32
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercombine=and&filtercombine=&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-waterman-cuda-9.2-opt&field2=testname&compare2=61&value2=Ifpack2_unit_tests_MPI_4&field3=site&compare3=61&value3=waterman&field4=buildstarttime&compare4=84&value4=2019-04-20T00%3A00%3A00&field5=buildstarttime&compare5=83&value5=2019-02-01T00%3A00%3A00) this test has passed contiguously since 2/16/2019 (about 9 weeks) so this must be fixed.

Closing as fixed.

**Closed by bartlettroscoe** 2019-04-21 01:32 UTC
Labels: ATDM Sev: Blocker, PA: Linear Solvers, client: ATDM, pkg: Ifpack2, type: bug
