### ISSUE TITLE
Tpetra: Failing CrsMatrix and MultiVector tests with Cuda

### ISSUE THREAD

**Issue by tjfulle** [trilinos/Trilinos#1510] opened 2017-07-17 21:51 UTC
Two tests fail on the latest development branch when compiled with Cuda on SNL testbed[s]:
 
1.  `TpetraCore_CrsMatrix_WithGraph_Cuda_MPI_4` with the following error:

```
3. CrsMatrix_int_int_double_cuda_node_type_WithGraph_replaceLocal_UnitTest ...Kokkos::DualView::modify ERROR: Concurrent modification of host and device views in DualView "MV::DualView"
```

2.  `TpetraCore_MultiVector_UnitTests_MPI_4` with the following error:

```
16. MultiVector_int_int_double_Kokkos_Compat_KokkosCudaWrapperNode_ScaleAndAssign_UnitTest ... Kokkos::DualView::modify ERROR: Concurrent modification of host and device views in DualView "MV::DualView"
```

**Comment by tjfulle** [comment] 2017-07-17 21:51
Trilinos was configured with:

```sh
#!/bin/bash

EXTRA_ARGS=$@

module purge
module load devpack/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44

TRILINOS_DIR=${HOME}/Developer/VCS/github.com/tjfulle/Trilinos/develop

CUDA=ON
export OMPI_CXX=${TRILINOS_DIR}/packages/kokkos/config/nvcc_wrapper
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1

COMPILER_DIR=
MPI_DIR=${MPI_HOME}
BLAS_DIR=${BLAS_ROOT}
LAPACK_DIR=${LAPACK_ROOT}
HDF5_DIR=${HDF5_ROOT}
NETCDF_DIR=${NETCDF_ROOT}
ZLIB_DIR=${ZLIB_ROOT}
BOOST_DIR=${BOOST_ROOT}
METIS_DIR=${METIS_ROOT}
PARMETIS_DIR=${PARMETIS_ROOT}

EXTRA_C_FLAGS=""
EXTRA_CXX_FLAGS="-arch=sm_60 -lineinfo \
-Xcudafe --diag_suppress=conversion_function_not_usable \
-Xcudafe --diag_suppress=cc_clobber_ignored \
-Xcudafe --diag_suppress=code_is_unreachable"
EXTRA_F_FLAGS=""
LINK_FLAGS=""

rm -f CMakeCache.txt; rm -rf CMakeFiles

cmake \
   -D CMAKE_VERBOSE_MAKEFILE=FALSE \
   -D BUILD_SHARED_LIBS=ON \
   \
   -D CMAKE_BUILD_TYPE:STRING=DEBUG \
   -D Kokkos_ENABLE_DEBUG:BOOL=ON \
   -D Teuchos_ENABLE_DEBUG:BOOL=ON \
   -D CMAKE_CXX_FLAGS_DEBUG:STRING=${CXX_DEBUG_FLAGS} \
   -D Trilinos_ENABLE_DEBUG_SYMBOLS:BOOL=OFF \
   \
   -D CMAKE_C_COMPILER="mpicc" \
   -D CMAKE_CXX_COMPILER="mpicxx" \
   -D CMAKE_Fortran_COMPILER="mpif90" \
   -D CMAKE_C_FLAGS="$EXTRA_C_FLAGS" \
   -D CMAKE_CXX_FLAGS="$EXTRA_CXX_FLAGS" \
   -D CMAKE_Fortran_FLAGS="$EXTRA_F_FLAGS" \
   -D CMAKE_EXE_LINKER_FLAGS="$LINK_FLAGS" \
   -D CMAKE_NO_BUILTIN_CHRPATH=TRUE \
   \
   -D Trilinos_ENABLE_Fortran:BOOL=ON \
   -D Trilinos_ENABLE_OpenMP:BOOL=ON \
   -D Trilinos_ENABLE_COMPLEX:BOOL=OFF \
   -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
   \
   -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
   -D Trilinos_VERBOSE_CONFIGURE=OFF \
   -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
   -D Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
   \
   -D Trilinos_ENABLE_TpetraCore=ON \
   \
   -D TPL_ENABLE_CUDA=${CUDA} \
   -D Kokkos_ENABLE_Cuda=${CUDA} \
   -D Kokkos_ENABLE_Cuda_UVM:BOOL=${CUDA} \
   -D Tpetra_INST_CUDA=${CUDA} \
   \
   -D Trilinos_ENABLE_TESTS=ON \
   -D Trilinos_ENABLE_EXAMPLES=OFF \
   -D DART_TESTING_TIMEOUT:STRING="600" \
   \
   -D TPL_ENABLE_X11=OFF \
   -D TPL_ENABLE_Matio=OFF \
   -D TPL_ENABLE_yaml-cpp:BOOL=OFF \
   \
   -D TPL_ENABLE_MPI=ON \
   -D MPI_USE_COMPILER_WRAPPERS=ON \
   -D MPI_BASE_DIR:PATH=${MPI_DIR} \
   -D MPI_EXEC:PATH="mpirun" \
   -D MPI_EXEC_MAX_NUMPROCS:STRING="4" \
   -D MPI_EXEC_NUMPROCS_FLAG:STRING="--map-by;ppr:2:NUMA:PE=4;-x;OMP_NUM_THREADS=32;-x;OMP_THREAD_PLACES=core;-x;OMP_DISPLAY_ENV=true;-np" \
   \
   -D TPL_ENABLE_BLAS=ON \
   -D BLAS_LIBRARY_DIRS:PATH="${BLAS_DIR}/lib" \
   -D BLAS_LIBRARY_NAMES:STRING="blas" \
   \
   -D TPL_ENABLE_LAPACK=ON \
   -D LAPACK_LIBRARY_DIRS:PATH="${LAPACK_DIR}/lib" \
   -D LAPACK_LIBRARY_NAMES:STRING="lapack" \
   \
   -D TPL_ENABLE_Boost=ON \
   -D Boost_INCLUDE_DIRS:PATH=${BOOST_DIR}/include \
   \
   -D TPL_ENABLE_BoostLib=ON \
   -D BoostLib_INCLUDE_DIRS:PATH=${BOOST_DIR}/include \
   -D BoostLib_LIBRARY_DIRS:PATH=${BOOST_DIR}/lib \
   \
   -D TPL_ENABLE_Netcdf=ON \
   -D Netcdf_INCLUDE_DIRS:PATH="${NETCDF_DIR}/include;${HDF5_DIR}/include" \
   -D Netcdf_LIBRARY_DIRS:PATH="${NETCDF_DIR}/lib;${PNETCDF_ROOT}/lib;${HDF5_DIR}/lib;${ZLIB_DIR}/lib" \
   -D Netcdf_LIBRARY_NAMES:STRING="netcdf;pnetcdf;hdf5_hl;hdf5;z" \
   \
   -D TPL_ENABLE_METIS=ON \
   -D METIS_INCLUDE_DIRS:PATH=${METIS_DIR}/include \
   -D METIS_LIBRARY_DIRS:PATH=${METIS_DIR}/lib \
   \
   -D TPL_ENABLE_ParMETIS=ON \
   -D ParMETIS_INCLUDE_DIRS:PATH=${PARMETIS_DIR}/include \
   -D ParMETIS_LIBRARY_DIRS:PATH=${PARMETIS_DIR}/lib \
   \
   -D TPL_ENABLE_SuperLUDist=OFF \
   \
   -D Trilinos_EXTRA_LINK_FLAGS:STRING="-lmpi -ldl -lutil -lm -ldl -lpthread" \
   \
   ${EXTRA_ARGS} \
   ${TRILINOS_DIR}
```

**Comment by mhoemmen** [comment] 2017-07-17 22:00
Working on this; thanks!

**Comment by mhoemmen** [comment] 2017-07-18 15:18
Interesting, I couldn't replicate with CUDA 7.5 + GCC 4.8.4 in a release build, but I think these errors only show up in debug builds.  We tend not to do debug builds with CUDA as often, since this often has led to link failures downstream (due to running out of memory for the link? not quite sure).  I'll try again with a debug build.

**Comment by mhoemmen** [comment] 2017-07-18 16:25
I was able to replicate exactly those test failures with CUDA 7.5.18 + GCC 4.8.4 in a debug build.

**Comment by mhoemmen** [comment] 2017-07-18 17:10
The issue is two-argument `CrsMatrix::getLocalDiagCopy` with `Teuchos::ArrayView` offsets argument.  In the `TpetraCore_CrsMatrix_WithGraph` test, a bunch of code happens that marks the device version of the DualView inside the Vector as modified.  Two-argument `getLocalDiagCopy` with `Teuchos::ArrayView` offsets marks the host version of the Vector as modified.

I can fix this in `getLocalDiagCopy`.

**Comment by mhoemmen** [comment] 2017-07-18 21:18
I just pushed a fix to develop.  Thanks!

**Closed by mhoemmen** 2017-07-18 21:18 UTC
Labels: Tpetra
