### ISSUE TITLE
Amesos2 builds example using Epetra_CrsMatrix despite being passed -DAmesos2_ENABLE_Epetra=OFF

### ISSUE THREAD

**Issue by prwolfe** [trilinos/Trilinos#1986] opened 2017-11-14 17:36 UTC
@trilinos/amesos2 

## Expectations

I would like this not to build the example or a different matrix type to be used when CrsMAtrix is unavailable.

## Current Behavior

See https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3218963 to view the current error.

## Motivation and Context

This keeps the Sierra representative builds from completing cleanly. We would like to move them up out of specialized.

**Comment by srajama1** [comment] 2017-11-14 17:45
All of us are at SC this week, but will get to this as soon as we can.

@MicheldeMessieres : Both @ndellingwood and I are at SC. Do you have some time to look at this ?

**Comment by hkthorn** [comment] 2017-11-14 19:15
@srajama1 @prwolfe I was in the neighborhood looking at an Amesos2 issue of my own and found this.  The tests that are failing to build are guarded by an ifdef on EpetraExt.  Historically, it has been presumed that if EpetraExt has been built, then Epetra is also built.  In looking at the configure script for this build, Epetra is neither explicitly enabled or disabled.  However, EpetraExt is explicitly enabled.  So, that enables the build of Epetra because it is a required dependency of EpetraExt.  However, the explicit disabling of the Epetra adapters in Amesos2 will eliminate the build of those adapters, but not the build of examples/tests that look at EpetraExt.

So, if there is no objection, I can add the additional logic to those tests/examples that require the Epetra adapters, yet only acknowledge EpetraExt.

**Comment by srajama1** [comment] 2017-11-14 22:17
@hkthorn I would appreciate it if you can take care of the additional logic.

**Comment by hkthorn** [comment] 2017-11-14 22:38
@srajama1 @prwolfe This should be fixed now.  I will wait for testing before closing.

**Comment by hkthorn** [comment] 2017-11-15 18:19
@prwolfe @srajama1 @ndellingwood I fixed the build for the Epetra tests/examples, but now the build failure is a duplicate of #1987.

**Closed** 2017-11-28 17:46 UTC
Labels: Amesos2
