### ISSUE TITLE
Xpetra: Compile Failure on Mac CLANG

### ISSUE THREAD

**Issue by ccober6** [trilinos/Trilinos#6322] opened 2019-11-21 09:18 UTC
## Bug Report
@trilinos/xpetra 

### Description
Not sure when this happened, but I was able to build sometime last week, but now I get a build failure.  Same branch works on the CEE LAN RedHat, so not sure what the issue is.

The errors are like 

```
/Users/ccober/myOffice/Trilinos/packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_def.hpp:250:24: error: no template named 'BlockedVector' in namespace 'Xpetra'; did you mean simply 'BlockedVector'?
      Teuchos::rcp(new Xpetra::BlockedVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>(this->getBlockedMap(), false));
                       ^~~~~~~~~~~~~~~~~~~~~
                       BlockedVector

```

### Steps to Reproduce
1. SHA1:  0f0ebdab
1. Configure script: [build_tempus_s1037643_mac_gcc.sh.txt](https://github.com/trilinos/Trilinos/files/3873685/build_tempus_s1037643_mac_gcc.sh.txt)
1. Configure log:  [configure.log.txt](https://github.com/trilinos/Trilinos/files/3873688/configure.log.txt)
1. Build log:  [make.log.txt](https://github.com/trilinos/Trilinos/files/3873696/make.log.txt)

**Comment by jhux2** [comment] 2019-11-21 15:26
I don’t see the error in this issue, but it could just be the app I’m using.  Might be hard to reproduce, as very few of us develop on macs.  Do y you have a machine we could have access to?

@william76 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ccober6** [comment] 2019-11-26 00:02
Sorry missing the email on this.  The error is in the make.log.txt.  I have an old laptop that remains connected.  I will checkout to see if the same error occurs there also.  If so I can get accounts for you.

**Comment by ccober6** [comment] 2019-11-26 00:17
Explicitly added an example error.

**Comment by ccober6** [comment] 2019-11-26 00:38
So it fails similarly.  :(

Steps to Reproduce

1. SHA1: 647d69ca53
2. Configure script: [build_tempus_s989988_mac_gcc.sh.txt](https://github.com/trilinos/Trilinos/files/3889438/build_tempus_s989988_mac_gcc.sh.txt)
3. Configure log: [configure2.log.txt](https://github.com/trilinos/Trilinos/files/3889432/configure2.log.txt)
4. Build log: [make2.log.txt](https://github.com/trilinos/Trilinos/files/3889428/make2.log.txt)

Example error:
```

/Users/ccober/myOffice/Trilinos/packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_def.hpp:191:39: error: no template named 'VectorFactory' in namespace 'Xpetra'
        using VectorFactory = Xpetra::VectorFactory<Scalar,LocalOrdinal,GlobalOrdinal,Node>;
                              ~~~~~~~~^

```

**Comment by ccober6** [comment] 2019-11-26 00:38
I will set up an account in the morning.

**Comment by ccober6** [comment] 2019-11-26 15:29
@jhux2 So I talked with our sysadmins and they had some suggestions.  They centered around us pair programming this.

1. I have added you to the sharing on s1037643, my mac laptop.  I usually take it home in the evening and weekends.  You should be able to vnc into it and "screen share" my session.  This way you could "drive" if needed.
2. Pair program using skype, but I would "drive".
3. You can login , and cd to a directory I setup for you.  It would not be a home directory but you should have access to everything you might need (maybe :) ).  We might want to do this on my other mac laptop, s989988, as it remains connected most of the time.

What sounds good to you?

**Comment by ccober6** [comment] 2019-12-02 23:29
Hi @jhux2, just touching base on this.  Would you have time in the next week to work on this?

Thanks, Curt

**Comment by jhux2** [comment] 2019-12-03 00:07
@ccober6 Yes, I'll contact you off-line.

**Comment by jhux2** [comment] 2019-12-10 21:32
@ccober6 It appears that @william76 has fixed this issue with his PR #6414 for issue #6404.  I updated this morning and the build goes through on your Mac laptop.  Thank you, @william76!

**Comment by ccober6** [comment] 2019-12-11 19:55
@jhux2, so did a pull and a clean rebuild to get @william76 fix in PR #6414.  Now I am getting the following errors on both my Macs.

```
/Users/ccober/myOffice/Trilinos_Second/packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_def.hpp:197:32: error: 
      'VectorFactory' is not a class, namespace, or enumeration
        const RCP<Vector> vv = VectorFactory::Build(getMap(block, false)...
                               ^
/Users/ccober/myOffice/Trilinos_Second/packages/xpetra/src/Vector/Xpetra_VectorFactory_decl.hpp:74:9: note: 
      'VectorFactory' declared here
  class VectorFactory
        ^
In file included from /Users/ccober/myOffice/Trilinos_Second/packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVectorFactory.cpp:47:
In file included from /Users/ccober/myOffice/Trilinos_Second_build/packages/xpetra/src/Xpetra_BlockedMultiVector.hpp:2:
In file included from /Users/ccober/myOffice/Trilinos_Second/packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_def.hpp:54:
In file included from /Users/ccober/myOffice/Trilinos_Second_build/packages/xpetra/src/Xpetra_MapExtractor.hpp:2:
/Users/ccober/myOffice/Trilinos_Second/packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_def.hpp:569:16: error: 
      'VectorFactory' is not a class, namespace, or enumeration
        return VectorFactory::Build(getMap(i, bThyraMode), bZero);
               ^
/Users/ccober/myOffice/Trilinos_Second/packages/xpetra/src/Vector/Xpetra_VectorFactory_decl.hpp:74:9: note: 
      'VectorFactory' declared here
  class VectorFactory
        ^
```

**Comment by ndellingwood** [comment] 2019-12-11 20:19
I'm seeing the same issue as @ccober6 after a pull with #6414 and #6419
Adding @william76 and @cgcgcg

**Comment by jhux2** [comment] 2019-12-11 20:25
@ccober6 I will do a clean build to see if I can reproduce on your Mac.

**Comment by jhux2** [comment] 2019-12-11 21:23
@ccober6 reports that changing
`const RCP<Vector> vv = VectorFactory::Build(getMap(block, false), false);`
to
`const RCP<Xpetra::Vector<Scalar,LocalOrdinal,GlobalOrdinal,Node> > vv = Xpetra::VectorFactory<Scalar,LocalOrdinal,GlobalOrdinal,Node>::Build(getMap(block, false), false);`

fixes the issue.

**Comment by william76** [comment] 2019-12-11 21:27
@jhux2 should I put that in or do you already have a branch with the change?

**Comment by jhux2** [comment] 2019-12-11 21:36
@william76 I'll put in a PR.

**Comment by william76** [comment] 2019-12-11 21:41
@jhux2 ok. 
I think this was because we don't have the shortnames macros in the def files... there are probably other places in this file where this kind of issue could come up, such as line 325:
```C++
Teuchos::RCP<MultiVector> vv = full->getMultiVector(block, bThyraMode);
```
etc.

I think in more recent classes I did the ETI work on, I put in blocks of lines like this:
```C++
using MultiVector = Xpetra::MultiVector<Scalar,LocalOrdinal,GlobalOrdinal,Node>;
```
at the start of method definition blocks to just define the classes used in the function without having to change all the points of use...

**Comment by lucbv** [comment] 2019-12-11 21:48
@william76 stop adding
```
using MultiVector = Xpetra::MultiVector<Scalar,LocalOrdinal,GlobalOrdinal,Node>;
```
when it is not what you need, this often creates `-Wshadow` warning which I am in the process of cleaning up for issue #6295

Here the issue is that the headers for the VectorFactory and potentially MultiVectorFactory are included in the `def` file and not the `decl` file. If you move them in the `decl` file you will be able to use the short names without re-declaring them.
I am wondering if we have a forward declaration type of file in Xpetra that might be sufficient for the short names?

**Comment by william76** [comment] 2019-12-11 22:11
@lucbv 
`Xpetra_BlockedMultiVector_decl.hpp` does not include `Xpetra_VectorFactory` because there are no uses of `VectorFactory` anywhere in the declarations of `BlockedMultiVector`. It is included in `Xpetra_BlockedMultiVector_def.hpp` because it does get called inside the function bodies.  I was trying to not include headers in the decl files if the declarations don't need them.

If you move the `VectorFactory` headers into `Xpetra_BlockedMultiVector_decl.hpp` you'll need to change them to include `Xpetra_VectorFactory_decl.hpp` etc. for the ones that have been converted to ETI or the circular reference problem might come up again when the decl file never gets fully processed before it wraps around somehow and gets back to the def's ;) 

I put the `using` statements just inside the bodies of the functions in a couple of the more recent def files so I didn't need to change usages of things like `Map`, `MultiVector`, etc. to the fully qualified `Xpetra::classname<templates>` at every usage point.  It was working but admittedly I wasn't looking too closely at shadow declaration warnings :(

**Comment by lucbv** [comment] 2019-12-12 17:40
@william76 fair enough if including the header for `VectorFactory` in the `decl` file leads to circular dependencies then we have to avoid it.
Using full names as @jhux2 did is not a problem and if we want to go ahead with that its fine with me.
I think that adding the block of code below in the `decl` file just after the forward declaration of the BlockedMap could solve the problem and you won't have to use the full names of the object.
```
  template <class LocalOrdinal, class GlobalOrdinal, class Node> class VectorFactory;

#ifndef XPETRA_VECTORFACTORY_SHORT
#define XPETRA_VECTORFACTORY_SHORT
#endif
```
This might be useful if you use the VectorFactory a lot in the `def` file.

**Comment by william76** [comment] 2019-12-12 19:02
@lucbv in which file?

**Comment by lucbv** [comment] 2019-12-12 20:18
@william76 I tested it just out of curiosity and adding the forward declaration plus the macro in `Xpetra_MapExtractor_decl.hpp` allows you to use the shortnames in both `Xpetra_MapExtractor_decl.hpp` and `Xpetra_MapExtractor_def.hpp`. It can be a good option in the future if you want to avoid putting a lot of `using blah = Xpetra::blah<SC,LO,GO,NO>`.

**Comment by jhux2** [comment] 2019-12-16 18:39
Closing as fixed.

**Closed by jhux2** 2019-12-16 18:39 UTC
Labels: pkg: Xpetra, type: bug
