### ISSUE TITLE
Framework:  PR autotester not running

### ISSUE THREAD

**Issue by tasmith4** [trilinos/Trilinos#9283] opened 2021-06-14 17:37 UTC
## Bug Report
@trilinos/framework 

### Description
The PR autotester seems not to have run since sometime on Thursday (June 10).  See for example #9274, #9276, #9278, #9279.  @trilinos/framework, do any of you know what might be going on?

FYI @brian-kelley @jhux2 @alanw0

**Comment by tasmith4** [comment] 2021-06-18 12:46
@trilinos/framework @prwolfe @william76 I notice some PR's are starting to merge, has this issue been resolved, or is anything still outstanding?

**Comment by jhux2** [comment] 2021-06-18 17:33
@tasmith4 The AT is working again.

**Comment by tasmith4** [comment] 2021-06-18 19:54
@jhux2 thanks for pointing me to this other issue.

**Comment by prwolfe** [comment] 2021-06-30 20:24
Closing as duplicate of #9293

**Closed by prwolfe** 2021-06-30 20:24 UTC
Labels: PA: Framework, type: bug
