### ISSUE TITLE
Shylu/Basker:  What causes low parallel performance for these matrices?

### ISSUE THREAD

**Issue by gkovacsds** [trilinos/Trilinos#8136] opened 2020-10-02 15:57 UTC
[github_mtx_samples.zip](https://github.com/trilinos/Trilinos/files/5319007/github_mtx_samples.zip)
@trilinos/shylu

We are doing test runs with some real world circuit matrices with Basker, and with these, parallel performance is 5-6x lower than serial.
Solving one of them (TPS56121) fails with segmentation fault, in serial mode too. (KLU solver is OK with that)
Running on Ubuntu 16.04 and 20.04.

Could you developers take a look at these matrices, and maybe give some advice?

Attached are the matrix files with rhs files.
Also a slightly modified version of /packages/shylu/shylu_node/basker/test/basker_test.cpp
which runs with 3 parameters:  mtxfile rhsfile nthreads

For building we used defines BASKER_KOKKOS and Kokkos_ENABLE_OPENMP is that the recommended setting?

Thank you.

**Comment by jhux2** [comment] 2020-10-02 16:18
@trilinos/shylu

**Comment by jhux2** [comment] 2020-10-02 16:20
@trilinos/amesos2

**Comment by iyamazaki** [comment] 2020-10-07 17:38
Thank you @gkovacsds . We have fixed some of the numerical, and segfault, issues in our fork (https://github.com/iyamazaki/Trilinos/tree/shylu-basker) and are planning to merge into the main branch after a few more fixes/tests. Were you using this fork when you see the segfalut? I could not reproduce the segfault.

We are also aware of the performance issues, especially with the multi-threaded runs, and we are starting to address the issue in another branch.

**Comment by gkovacsds** [comment] 2020-10-08 11:17
I tried Sept 9th   https://github.com/iyamazaki/Trilinos/tree/shylu-basker2   
as it was suggested in my other issue https://github.com/trilinos/Trilinos/issues/7931
I attach the test case with stdout content here.
[crash.zip](https://github.com/trilinos/Trilinos/files/5347391/crash.zip)

Thanks for the feedback.

**Comment by iyamazaki** [comment] 2020-10-12 08:06
@gkovacsds . In my tests, numerical factorization of both KLU2 and ShyLU-Basker failed (singular diagonal block). Can you also share your KLU2 test?

**Comment by gkovacsds** [comment] 2020-10-12 08:23
Sorry I was referring to KLU by Tim Davis/SuiteSparse. That can solve this. 
I only tried Basker as that looks promising, 
we didn't try KLU2, as development seems to have stalled and it looks like a single-thread solver.

**Comment by iyamazaki** [comment] 2020-10-13 05:29
Thank you for the inputs, @gkovacsds . I was wondering if this matrix is singular. Can KLU produce the solution? If the issue is the segfault, we just pushed a small patch to the first branch, shylu-basker. I will merge the patch into the second branch, shylu-basker2.

**Comment by rsiva-web** [comment] 2020-11-03 18:24
@iyamazaki : It is better to get this branches into develop.

**Comment by iyamazaki** [comment] 2020-11-03 19:45
Hi, @rsiva-web. @ndellingwood We just discussed it, and we plan to merge once we resolve the transpose-solve. I think we have plans for fixing other parallel performance issues, but they will be in another PR.

**Comment by iyamazaki** [comment] 2021-08-10 22:18
I'm closing this. [PR 9525](https://github.com/trilinos/Trilinos/pull/9525) should fix the segfault. Hopefully, the performance is also better, but we know the scaling issue. Please let us know if you still see the issue..

**Closed by iyamazaki** 2021-08-10 22:18 UTC
Labels: type: question, pkg: Amesos2, pkg: ShyLU
