### ISSUE TITLE
Non-CUDA Trilinos build seems to be looking for CUDA

### ISSUE THREAD

**Issue by ikalash** [trilinos/Trilinos#6743] opened 2020-02-04 15:52 UTC
It appears the non-CUDA Trilinos builds seem to be looking for CUDA due to changes pushed to the ```develop``` branch yesterday.  Below is the error which occurs when building Trilinos as part of the Albany nightlies:
```
[  0%] Building CXX object commonTools/gtest/CMakeFiles/gtest.dir/gtest/gtest-all.cc.o
Scanning dependencies of target pcu
clang-7: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
[  0%] Building CXX object packages/seacas/libraries/suplib_cpp/CMakeFiles/suplib_cpp.dir/GetLongOpt.C.o
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang-7: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
[  0%] Building C object SCOREC/pcu/CMakeFiles/pcu.dir/pcu.c.o
[  0%] Linking CXX static library libpamgen_extras.a
[  0%] Building C object packages/shards/src/CMakeFiles/shards.dir/Shards_CellTopologyData.c.o
[  0%] Building C object SCOREC/lion/CMakeFiles/lion.dir/lionPrint.c.o
Scanning dependencies of target supes
[  0%] Linking C static library liblast_lib.a
```
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=92869
Perhaps a new configuration option is required now? 

@trilinos/kokkos

**Comment by ibaned** [comment] 2020-02-04 15:53
This is a duplicate of #6734

**Closed by ibaned** 2020-02-04 15:53 UTC
Labels: client: Albany, pkg: Kokkos, type: bug
