### ISSUE TITLE
Belos compilation error on Lassen

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#5404] opened 2019-06-18 22:04 UTC
## Bug Report
@trilinos/belos 

On lassen I'm seeing this.  anyone having the same issue?  how to work around..

```

[ 48%] Building CXX object packages/belos/src/CMakeFiles/belos.dir/Belos_Details_registerSolverFactory.cpp.o
/g/g20/mbetten/work/build/Trilinos/packages/belos/src/BelosLSQRIter.hpp(581): error: identifier "printMat" is undefined
          detected during:
            instantiation of "void Belos::LSQRIter<ScalarType, MV, OP>::iterate() [with ScalarType=double, MV=Belos::MultiVec<double>, OP=Belos::Operator<double>]" 
(307): here
            instantiation of "Belos::LSQRIter<ScalarType, MV, OP>::LSQRIter(const Teuchos::RCP<Belos::LinearProblem<ScalarType, MV, OP>> &, const Teuchos::RCP<Belos::OutputManager<ScalarType>> &, const Teuchos::RCP<Belos::StatusTest<ScalarType, MV, OP>> &, Teuchos::ParameterList &) [with ScalarType=double, MV=Belos::MultiVec<double>, OP=Belos::Operator<double>]" 
/g/g20/mbetten/work/build/Trilinos/packages/belos/src/BelosLSQRSolMgr.hpp(945): here
            instantiation of "Belos::ReturnType Belos::LSQRSolMgr<ScalarType, MV, OP, false>::solve() [with ScalarType=double, MV=Belos::MultiVec<double>, OP=Belos::Operator<double>]" 
/g/g20/mbetten/work/build/Trilinos/packages/belos/src/BelosLSQRSolMgr.hpp(527): here
            instantiation of "Belos::LSQRSolMgr<ScalarType, MV, OP, false>::LSQRSolMgr() [with ScalarType=double, MV=Belos::MultiVec<double>, OP=Belos::Operator<double>]" 
/g/g20/mbetten/work/build/Trilinos/packages/belos/src/BelosSolverFactory.hpp(270): here
            instantiation of "void Belos::Impl::registerSolverSubclassForTypes<SolverClass,Scalar,MV,OP>(const std::string &) [with SolverClass=Belos::LSQRSolMgr<double, Belos::MultiVec<double>, Belos::Operator<double>, false>, Scalar=double, MV=Belos::MultiVec<double>, OP=Belos::Operator<double>]" 
/g/g20/mbetten/work/build/Trilinos/packages/belos/src/Belos_Details_registerSolverFactory.cpp(93): here


```

### Description
What went wrong?  What should have happened?  Do you have an idea what might
fix things?  How has this bug affected you?  What are you trying to accomplish?
What specifically must we demonstrate to call this work complete?

### Steps to Reproduce
1. SHA1:  [insert here]
1. Configure script:  [attach here]
1. Configure log:  [attach here]
1. Build log:  [attach here]
1. Input deck:  [attach here]
1. Do this.
1. Do that.
1. Shake fist angrily at computer.
1. Run log:  [attach here]

**Comment by bathmatt** [comment] 2019-06-18 22:04
@rppawlo @bartlettroscoe

**Comment by bathmatt** [comment] 2019-06-18 22:09
This only exists in main files

```

1000670:Trilinos mbetten$ git grep void\ printMat\(
packages/epetra/test/IntSerialDense/cxx_main.cpp:void printMat(const char* name, Epetra_IntSerialDenseMatrix& matrix);
packages/epetra/test/IntSerialDense/cxx_main.cpp:void printMat(const char* name, Epetra_IntSerialDenseMatrix& matrix) {
packages/epetra/test/SerialDense/cxx_main.cpp:void printMat(const char* name, Epetra_SerialDenseMatrix& matrix);
packages/epetra/test/SerialDense/cxx_main.cpp:void printMat(const char* name, Epetra_SerialDenseMatrix& matrix) {
packages/epetra/test/SerialDense_LL/cxx_main.cpp:void printMat(const char* name, Epetra_SerialDenseMatrix& matrix);
packages/epetra/test/SerialDense_LL/cxx_main.cpp:void printMat(const char* name, Epetra_SerialDenseMatrix& matrix) {
packages/ifpack/test/TriDi/tridi_main.cpp:void printMat(const char* name, Ifpack_SerialTriDiMatrix& matrix);
packages/ifpack/test/TriDi/tridi_main.cpp:void printMat(const char* name, Ifpack_SerialTriDiMatrix& matrix) {

```

none of which is in below

**Comment by bathmatt** [comment] 2019-06-18 22:11
helps if one includes the error message.  I commented out the code calling the print and I'm compiling now, but . . .

**Comment by bathmatt** [comment] 2019-06-18 22:16
@kddevin looks like you broke the code

```

s1000670:Trilinos mbetten$ git blame packages/belos/src/BelosLSQRIter.hpp |grep printMat
c75f6d4fa62 (Karen D. Devine       2019-06-13 10:16:29 -0600 581)           std::cout << "<U, U> = " << printMat(uotuo) << std::endl;
c75f6d4fa62 (Karen D. Devine       2019-06-13 10:16:29 -0600 587)           std::cout << "<AV, U> = alpha = " << printMat(utav) << std::endl;
s1000670:Trilinos mbetten$ 

```

**Comment by bathmatt** [comment] 2019-06-18 22:26
Wait maybe not, it might have been removed somewhere else.  Sorry @kddevin 

```
[ 84%] Building CXX object packages/tempus/src/CMakeFiles/tempus.dir/Tempus_RKButcherTableauBuilder.cpp.o
/g/g20/mbetten/work/build/Trilinos/packages/tempus/src/Tempus_RKButcherTableau.hpp(179): error: identifier "printMat" is undefined
          detected during:
            instantiation of "void Tempus::RKButcherTableau<Scalar>::describe(Teuchos::FancyOStream &, Teuchos::EVerbosityLevel) const [with Scalar=double]" 
(437): here
            implicit generation of "Tempus::RKButcherTableau<Scalar>::
```

**Comment by kddevin** [comment] 2019-06-18 22:51
printMat() is defined in Teuchos_SerialDenseMatrix.hpp and Teuchos_SerialDenseVector.hpp (and similar for banded and symmetric SDM).
These files are included in Tempus_RKButcherTableau.hpp.
Not sure why the compiler isn't seeing them.

**Comment by kddevin** [comment] 2019-06-18 22:53
For your grep, don't grep for the "void" part; these printMat functions return ostreams.  See whether just "printMat" shows up in Teuchos.

**Comment by kddevin** [comment] 2019-06-18 23:11
@bathmatt please provide details of your build.  I tested the PR with the ATDM configuration below and everything was good.  Maybe something happened in the merge?

```
source ../cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
MPI_EXEC=`which mpiexec`


cmake \
  -GNinja \
  -DMPI_EXEC=${MPI_EXEC} \
  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
  -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Teuchos=ON \
  -DTrilinos_ENABLE_Anasazi=ON -DTrilinos_ENABLE_Belos=ON \
  -DTrilinos_ENABLE_ROL=ON -DTrilinos_ENABLE_Stokhos=ON \
  -DTrilinos_ENABLE_Tempus=ON \
.. |& tee OUTPUT.CMAKE
```

**Comment by bathmatt** [comment] 2019-06-19 00:13
wiping everything and trying again

**Comment by bathmatt** [comment] 2019-06-19 12:07
Did that, same issue....  I've uploaded my configure script.  This worked just a bit ago, backdating the version and it's compiling

There is no load-env for this platform.  They don't have prebuilt tpls available so i have an uber build script

[conf.txt](https://github.com/trilinos/Trilinos/files/3305969/conf.txt)

**Comment by srajama1** [comment] 2019-06-19 13:43
@bathmatt : What is the compiler gcc or xlc ?

**Comment by bartlettroscoe** [comment] 2019-06-19 14:55
@bathmatt, any chance we can reproduce this on 'vortex'?  My understanding from the ATDM PI and DevOps meetings yesterday (which I think you missed) is that we can't set up automated builds on the LLNL systems.  Therefore, the best chance we have to support these systems is 'vortex'.

Can we talk offline?

**Comment by bartlettroscoe** [comment] 2019-06-19 15:03
FYI: Belos is looking pretty good in all of our builds as shown on [CDash yesterday](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-06-18&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=subprojects&compare2=93&value2=Belos).  That include GCC 7.2.0 + CUDA 9.2 builds on 'waterman' (the closest thing we have to ATS-2 at this point until we get the green light for 'vortex').

**Comment by bathmatt** [comment] 2019-06-19 15:22
Sure, Ross, call

**Comment by kddevin** [comment] 2019-06-19 16:48
I successfully built using a modified version of @bathmatt 's configure script.  It did not use SEACAS or CUDA, but it did build the Tempus RKButcher and Belos registerSolverFactory files without any problem.  Without being able to reproduce the error, I don't know how to proceed.  If anyone finds an environment that we can access that also exhibits this error, I'll be happy to help resolve it.

**Comment by bathmatt** [comment] 2019-06-19 19:44
Ross asked for my build script, there is typos in it but 

```
module load gcc/7.3.1 cmake/3.12.1
#export INSTALL_DIR=/home/mbetten/builds/test-for-lassen/install
export INSTALL_DIR=/g/g20/mbetten/TPLS-gcc/install
echo Installing in $INSTALL_DIR

export CC=mpicc
export CXX=mpicxx
export CFLAGS=-I$INSTALL_DIR/include
export CPPFLAGS=-I$INSTALL_DIR/include
export LDFLAGS=-L$INSTALL_DIR/lib

cd Trilinos
export TRILINOS_DIR=`pwd`
export KOKKOS_ARCH="Power9;Volta70"
export ARCH="Power9;Volta70"
export OMPI_CXX=${TRILINOS_DIR}/packages/kokkos/bin/nvcc_wrapper
export LLNL_USE_OMPI_VARS="Y"
export NVCC_WRAPPER_DEFAULT_COMPILER=`which  g++`

cd Trilinos
mkdir build-gcc-cuda
cd build-gcc-cuda
export ARCH="Power9;Volta70"
cp ../../configure-cuda.sh .
./configure-cuda.sh 
make -j32 install
cd ../..


```

**Comment by bathmatt** [comment] 2019-06-19 20:13
I'm building trilinos on vortex...  I can give a tarball with all the files if this fails.

**Comment by bartlettroscoe** [comment] 2019-06-19 21:57
FYI: We are going to try to set up a supported ATDM Trilinos configuration on 'vortex' to match @bathmatt's configuration.  Work on that will be tracked in [CDOFA-37](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-37).

**Comment by bathmatt** [comment] 2019-06-19 22:03
It compiles on vortex with the same script...

**Comment by bartlettroscoe** [comment] 2019-06-19 22:12
@bathmatt said:

> It compiles on vortex with the same script...

Matt, are you saying that you can't reproduce the same build error on 'vortex'?

**Comment by bathmatt** [comment] 2019-06-20 12:50
Correct

**Comment by bartlettroscoe** [comment] 2019-06-20 13:42
@bathmatt, if we can't reproduce this build error on 'vortex', I guess that means that 'vortex' is not in sync with 'lassen' at LLNL.

@nmhamster, what should we do here?

**Comment by bathmatt** [comment] 2019-06-21 15:55
no, it compiles fine on vortex, not on lassen

**Comment by jhux2** [comment] 2020-02-18 18:09
@bathmatt Can this be closed as resolved?

**Comment by cgcgcg** [comment] 2020-02-18 18:24
I have never seen this on lassen, so my guess is that the issue can be closed.

**Comment by jhux2** [comment] 2020-02-18 18:34
Agreed.  I will close, @bathmatt can reopen if this is still a problem.

**Closed by jhux2** 2020-02-18 18:34 UTC
Labels: PA: Linear Solvers, client: ATDM, client: EMPIRE, impacting: build, lacks reproducer, pkg: Belos, type: bug
