### ISSUE TITLE
Create Intel 19.0.5 PR Testing Build

### ISSUE THREAD

**Issue by ZUUL42** [trilinos/Trilinos#6294] opened 2019-11-18 20:22 UTC
## Enhancement
@trilinos/framework 

Look into creating a PR Testing build that uses Intel 19.0.5.
Currently we have an Intel 17.0.1 PR testing build.
Intel 19 would likely replace the 17 build.

**Comment by ZUUL42** [comment] 2019-11-18 22:36
I've got this build configured and building successfully.
However @trilinos/zoltan has 1 test failing and @trilinos/zoltan2 has 8 tests failing.
[CDash results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5894219&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20191113-0016-Experimental&filtercombine=and)

**Comment by kddevin** [comment] 2019-11-19 19:06
All the failing tests rely on the TPL Scotch, and the failures appear to be coming from Scotch.  Were the Scotch TPLs rebuilt with these compilers?

**Comment by ZUUL42** [comment] 2019-12-06 18:52
The job cleans and rebuilds the entire project.
I haven't traced it down to _completely_ certain, but it should be a full clean build of the entire codebase.
I'm not familiar with Scotch, but it does appear that there are new recent releases. 6.0.3 is from 2014-10. I'm not sure if updating that would help.

**Comment by kddevin** [comment] 2019-12-06 19:43
Hi, @ZUUL42 .  
Are you saying the PR testing rebuilds TPLs (such as Scotch) as well as Trilinos code?
We do not have a customer driver for upgrading Scotch; indeed, our customers would probably prefer that we don't upgrade the TPLs if possible.
What is your timeframe for completing this issue?  I haven't had time to look at the tests or try to replicate the issues.

**Comment by kddevin** [comment] 2019-12-06 20:45
@ZUUL42 

On cee-lan, I confirmed that building both Trilinos and the Scotch TPL with the Intel 19.0.5 compiler allows all zoltan and zoltan2 tests to pass.

I used module sierra-devel/intel-19.0.5-openmpi-1.10.2 to get consistent compilers and MPI for building both Scotch and Trilinos.

**Comment by ZUUL42** [comment] 2019-12-06 21:32
OK. Thanks for doing that.
I'll check over what I have running and see what I can do.

**Comment by kddevin** [comment] 2020-01-08 21:58
@ZUUL42   I am trying to replicate your errors using sems modules instead of the sierra module.  Can you share which modules you load?   Thanks.

**Comment by ZUUL42** [comment] 2020-01-08 22:04
@kddevin I've gone through a few versions, but you can see the current configuration I'm trying [here](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:intel_19).
Thanks for taking a look.

**Comment by kddevin** [comment] 2020-01-09 18:17
Hi @ZUUL42 
In your script, I see two MPI modules loaded.  Openmpi is loaded before Scotch and MPICH is loaded after Scotch.  Is it possible, then, that the Scotch library selected is built with OpenMPI, while everything else gets build with MPICH?  This would certainly cause Scotch to fail in MPI calls, as you had seen.
I propose you remove the MPICH load, and just use OpenMPI, to see whether that resolves the problem you are seeing.

https://github.com/ZUUL42/Trilinos/blob/61dfcc04b329087242afdb664b4fb83c8282f53b/cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh#L17

**Comment by prwolfe** [comment] 2020-01-21 16:17
> @ZUUL42
> 
> On cee-lan, I confirmed that building both Trilinos and the Scotch TPL with the Intel 19.0.5 compiler allows all zoltan and zoltan2 tests to pass.
> 
> I used module sierra-devel/intel-19.0.5-openmpi-1.10.2 to get consistent compilers and MPI for building both Scotch and Trilinos.

@kddevin - can you send me the Makefile.inc you used to compile scotch and ptscotch please?  I am trying to help @ZUUL42 sort out what's happening on this.

Thanks!

**Comment by kddevin** [comment] 2020-01-21 20:03
I emailed it to you, @prwolfe .

**Comment by prwolfe** [comment] 2020-01-22 19:41
I can confirm that using scotch 6.0.3 and Karens config I was able to get all tests to pass. I did have to set -fPIC to get past a linking error but no other changes. As we discussed at this mornings standup

* The configuration Karen sent over has all pthreads removed and a few other things. Basically it's set to do the minimum and that's likely why it's more reliable
* I was able to get similar but not exact errors with the icc_linux2 configuration that ships with scotch. I expect finding the exact flag that's the culprit will require getting the config used by sems to build their installation
* we talked about spack to build this for us and place results in a cache but that is beyond todays efforts.

I will send a note to sems and see what information we can get on their build.

**Comment by prwolfe** [comment] 2020-03-25 15:30
I am working with Spack this week trying to fix this issue. The basic build looks like this:

Add a packages.yaml file indicating that Spack should use the installed utilities. The files has the following:

> \# -------------------------------------------------------------------------
> \# This file controls default concretization preferences for Spack.
> \#
> \# Per-user settings (overrides default and site settings):
> \#   ~/.spack/packages.yaml
> \# -------------------------------------------------------------------------
> packages:
>   mpich:
>     paths:
>       mpich@3.2%intel@17.0.1 arch=linux-rhel7-skylake: /projects/sems/install/rhel7-x86_64/sems/compiler/intel/17.0.1/mpich/3.2
>       mpich@3.2%intel@19.0.5.281 arch=linux-rhel7-skylake: /projects/sems/install/rhel7-x86_64/sems/compiler/intel/19.0.5/mpich/3.2
>     buildable: False
>   bison:
>     paths:
>       bison: /usr
>   flex:
>     paths:
>       flex: /usr
>   zlib:
>     paths:
>       zlib@1.2.8%intel@19.0.5.281 arch=linux-rhel7-skylake: /projects/sems/install/rhel7-x86_64/sems/tpl/zlib/1.2.8/intel/19.0.5/base

Build with:
- spack install scotch@6.0.3%intel@19.0.5.281 +int64

Use the resulting module instead of the semi scotch module:
- module use /scratch/prwolfe/trilinos/spack/share/spack/modules/linux-rhel7-skylake
- module load scotch-6.0.3-intel-19.0.5.281-s3qe5ez

and then build as normal and all tests will pass. I am looking into how to create a view that will be accessible to others and will ask sems about how to put this under their NFS space.

**Comment by prwolfe** [comment] 2020-04-14 18:58
I found that Spack can create a view for export using

> spack view -d no hardlink scotch-6.0.3-int64 scotch@6.0.3%intel@19.0.5.281+int64^mpich@3.2^zlib@1.2.8

to get only the artifacts from scotch. Be cautious as there is a view subcommand in Spack env which was very misleading.

**Comment by ZUUL42** [comment] 2020-08-25 00:57
I have `trilinos-scotch/6.0.3/nopthread_64bit_parallel` that Paul built with Intel 19 loaded, but I'm still getting some build errors. The majority come from `trilinos/tpl/scotch/6.0.3/intel/19.0.5/openmpi/1.10.1/nopthread_64bit_parallel/include/parmetis.h(100): error: identifier "SCOTCH_Num" is undefined` as well as a handful of other identifiers.

There is also a number of occurances of `error: #error directive: "Specified version of ParMETIS is not compatible with Zoltan2; upgrade to ParMETIS v4 or later, or build Zoltan2 without ParMETIS."`
even though I have `sems-parmetis/4.0.3/parallel` loaded.
I haven't gotten into it recently, but I seem to remember having a lot of issue getting it to build without ParMETIS.

[CDash builds 80-82](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos_pullrequest_intel_19.0.5&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=84&value3=NOW)
[Branch](https://github.com/trilinos/Trilinos/compare/develop...ZUUL42:intel19)
Might anyone have any insight into this?
@kddevin @trilinos/zoltan2 

There's also a few others like `packages/zoltan2/core/src/problems/Zoltan2_PartitioningProblem.hpp(567): error: type name is not allowed this->algorithm_ = rcp(new AlgParMETIS<Adapter>(this->envConst_,`

**Comment by ZUUL42** [comment] 2020-11-12 06:35
This has been stale for quite some time. So, I'm going to submit a PR that puts an Intel 19.0.5 build in place, but turns off the current failing tests.
I'll create a new issue to track work to solve the issue with Scotch.

**Comment by kddevin** [comment] 2020-11-12 19:04
@ZUUL42 @prwolfe Here's an idea.
Scotch has capabilities to sit underneath the ParMETIS interface.  Thus, it creates include files parmetis.h and metis.h, but they are really Scotch files.  Scotch needs them, but at Sandia, no one else does.

For the "identifier SCOTCH_Num undefined" error:  make sure Scotch is not finding ParMETIS' parmetis.h when it is building.  Just unloading your parmetis module while building Scotch may accomplish that.  Scotch needs to find its own parmetis.h, not ParMETIS'.

For the Zoltan2 incompatible parmetis error:
Scotch's "fake" parmetis.h and metis.h files should not be installed with Scotch; only ptscotch*.h and scotch*.h should be installed with Scotch.  
I'm guessing parmetis.h is installed in Scotch's include directory, but the module loads or include paths are specified in an order such that Trilinos finds Scotch's parmetis.h first and tries to use it.
Either way, I think the solution is to **NOT** install Scotch's parmetis.h and metis.h in the Scotch include directories.

**Comment by jwillenbring** [comment] 2020-12-02 22:56
This is done with #8337. Closing.

**Closed by jwillenbring** 2020-12-02 22:56 UTC
Labels: type: enhancement
