### ISSUE TITLE
Re-enable GCC 4.8 testing on nightly track

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/Trilinos#1445] opened 2017-06-21 16:16 UTC
@trilinos/framework 

At the framework standup today, Brent offered to re-enable the GCC 4.8 tests in anticipation of potentially increasing the minimum required Trilinos GCC version from 4.7.2 to GCC 4.8.4. If that decision is finalized, we will increase the continuous testing on SADL to support 4.8.4 instead also.

**Comment by bmpersc** [comment] 2017-06-22 15:23
I have added a GCC 4.8.4 build that will go to the experimental track for now. Once we've shown that it is working we can move it to nightly, or which ever track is appropriate.

**Comment by jwillenbring** [comment] 2017-06-26 12:05
The build @bmpersc added is clean:

[https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2967557](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2967557)

We should promote it to at least nightly, maybe clean since there is serious talk about having 4.8.4 as the minimum compiler version. We could always move it or remove the build later.

**Comment by bmpersc** [comment] 2017-06-26 15:46
Per the standup discussion I have updated the 4.8.4 build to report to the clean track. I will close this ticket once I have confirmed that it is submitting to the clean track properly.

**Comment by bmpersc** [comment] 2017-06-27 15:21
The 4.8.4 build ran correctly on the clean build today. Unfortunately it was bit by an existing intermittent issue with Anasazi which had previously been reported in #1393. I added the failure information from 4.8.4 to that ticket as well. Since this is known intermittent I'm going to close this issue and we can address the Anasazi problem in another ticket.

**Closed** 2017-06-27 15:22 UTC
Labels: tests
