### ISSUE TITLE
Many automated tests are not appearing on the dashboard

### ISSUE THREAD

**Issue by jhux2** [trilinos/Trilinos#541] opened 2016-08-05 17:19 UTC
@tawiesn @aprokop @bartlettroscoe The MueLu nightly dashboard is no longer reporting tests from our two main test machines, geminga and enigma.  The tests from those two machines last appeared on August 1st.  I don't know if it's related, but there was an automated tribits snapshot into Trilinos on that same day.  Below is an error reported from tribits on geminga that appears to be related this issue.

```
Traceback (most recent call last):
   File 
"/home/aprokop/code/trilinos-test/trilinos/cmake/ctest/drivers/geminga/../cron_driver.py", 
line 23, in <module>
     tdd_driver.run_driver(this_path, repo_path)
   File 
"/data/code/trilinos-test/trilinos/cmake/tribits/dashboard_driver/tdd_driver.py", 
line 271, in run_driver
     "CTEST_BINARY_DIRECTORY" : tddDashboardRootDir+"/TDD_BUILD",
   File 
"/data/code/trilinos-test/trilinos/cmake/tribits/dashboard_driver/tdd_driver.py", 
line 182, in invoke_ctest
     extraEnv = environment
   File 
"/data/code/trilinos-test/trilinos/cmake/tribits/dashboard_driver/../python_utils/GeneralScriptSupport.py", 
line 469, in echoRunSysCmnd
     print("  Appending environment:" + extraEnv + "\n")
TypeError: cannot concatenate 'str' and 'dict' objects

Ending nightly Trilinos development testing on geminga: Fri Aug  5 
03:00:02 MDT 2016
```

**Comment by jhux2** [comment] 2016-08-05 17:25
I forgot to mention that tribits fails in the same way on geminga and enigma.

**Comment by bartlettroscoe** [comment] 2016-08-05 18:39
This is related to tribitspub/tribits#119

@wspotz, any idea what the issue might be? Hopefully this is an easy fix.

**Comment by bartlettroscoe** [comment] 2016-08-05 18:39
commented less than a minute ago
This is related to TriBITSPub/TriBITS#119

@wfspotz, any idea what the issue might be? Hopefully this is an easy fix.

**Comment by jhux2** [comment] 2016-08-08 21:04
@trilinos/framework Any word when this might be fixed?   As I said, geminga and enigma are the main MueLu test machines -- they exercise a lot of custom configure options that aren't tested elsewhere.

**Comment by bartlettroscoe** [comment] 2016-08-08 21:14
@jhux2,

Oh boy, it looks like this took out all of the Nighty builds for Trilinos as shown [here](http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2016-08-07).  I will look into getting this fixed ASAP.

How did no one notice this until just Friday?

The problem is that there are no automated tests for this python script so this defect passed through.

**Comment by bartlettroscoe** [comment] 2016-08-08 21:16
NOTE: This did not affect the CI build of Trilinos because that CI build does not use the tdd_driver.py script.

If the TDD system is going to be continued to me maintained, we are going to need to figure out a way to add automated testing for it.

**Comment by jhux2** [comment] 2016-08-08 21:21
> How did no one notice this until just Friday?

We only get emails when there are failing tests;  I just happened to look at the dashboard on Friday.

**Comment by aprokop** [comment] 2016-08-08 21:28
I noticed it few days earlier, but assumed that the dashboard is misbehaving again. I guess the recent months' troubles with dashboard taught us not to expect its presence day to day.

**Comment by bartlettroscoe** [comment] 2016-08-08 21:39
I have added an automated test to expose the problem and have fixed it.  I will snapshot the updated TriBITS into Trilinos and then report back here.

**Comment by bartlettroscoe** [comment] 2016-08-08 22:12
The following commits that I just pushed should hopefully fix this problem:

```
26c2244 "Merge branch 'tribits_github_snapshot' into develop"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Aug 8 17:52:16 2016 -0400 (15 minutes ago)

841e66d "Automatic snapshot commit from tribits at 1205b3f"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Aug 8 17:50:46 2016 -0400 (17 minutes ago)

M       cmake/tribits/python_utils/GeneralScriptSupport.py
```

Someone needs to be "on call" at any point in time and keep an eye on the Trilinos CDash site on a daily basis to make sure things look reasonable.  This is what we do with CASL VERA with an "on call" team on a rotating basis (1 week at a time).

**Comment by jhux2** [comment] 2016-08-08 23:20
@bartlettroscoe Thanks for working this issue so quickly!   Hopefully this fixes the problem.

**Comment by bartlettroscoe** [comment] 2016-08-09 19:49
It looks like some "Nightly" results are showing up again shown here:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2016-08-09

However, I fear that someone may have to manually pull the updated outer Trilinos repo that is used by the TDD system for the various builds or the broken tdd_driver.py script may not get updated.  I am not sure but I fear that might be the case.

**Comment by tawiesn** [comment] 2016-08-09 20:25
Manually pulled the Trilinos repository on enigma. Let's see whether it helps.

**Comment by tawiesn** [comment] 2016-08-09 21:18
Started the nightly tests on my machine and they seem to run. We should see some test results from enigma soon...

**Comment by bartlettroscoe** [comment] 2016-08-09 21:28
Looks like my fears may be unfounded.  For example, we can see builds coming in from muir today here:

* http://my.cdash.org/index.php?project=Trilinos&date=2016-08-09&display=project

but not for the last few days as shown here:

* http://my.cdash.org/index.php?project=Trilinos&date=2016-08-08&display=project
* http://my.cdash.org/index.php?project=Trilinos&date=2016-08-07&display=project

How this update occurred is not clear to me.  If Jenkins is driving the outer build and is pulling from Trilinos, then it would not be affected by a broken tdd_driver.py script.

We will wait and see what happens tomorrow.

**Comment by tawiesn** [comment] 2016-08-09 21:52
> Someone needs to be "on call" at any point in time and keep an eye on the Trilinos CDash site on a daily basis to make sure things look reasonable. This is what we do with CASL VERA with an "on call" team on a rotating basis (1 week at a time). 

I think it is good idea that there is _someone_ watching out every day to check whether there is a problem with the dash board. On the other side, i would expect that all of us _check the dashboard the days after having made a commit_ (just to make sure that nothing is broken), since the checkin script never can catch all problems. Furthermore, it's always good to know whether commits made it into the master branch (or not). If we all follow this principle we wouldn't even need a special "on call" team.

**Comment by bartlettroscoe** [comment] 2016-08-09 22:03
> If we all follow this principle we wouldn't even need a special "on call" team.

From my own experience with this over several projects over many years if that if something is everyone's responsibility then it is no-one's responsibility. The active "on call" member just has to keep a watch and do the most basic triage and pass the issue on to someone else.  The CASL project has been an interesting experimental test bed for these processes.

**Comment by tawiesn** [comment] 2016-08-10 14:51
Enigma is back again as test machine (the tests show up on Monday, since i ran them early yesterday.).

**Comment by bartlettroscoe** [comment] 2016-08-11 15:19
It is hard to tell if *all* of the Nightly builds are back (because none of the builds are marked as "expected builds") but there are a whole bunch of builds showing up today on the main CDash site:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2016-08-11

and builds are also showing up on the my.cdash.org site:

* http://my.cdash.org/index.php?project=Trilinos&date=2016-08-11&display=project

Therefore, I am going to assume this is fixed.  I am putting into review and asking Brent to review the set of builds showing up on CDash (since he should know that better than me).

**Comment by bmpersc** [comment] 2016-08-11 20:01
It looks like all the builds I would expect are reporting.

**Comment by bartlettroscoe** [comment] 2016-08-11 20:34
> It looks like all the builds I would expect are reporting.

Thanks Brent!

Closing as complete.

**Closed by bartlettroscoe** 2016-08-11 20:34 UTC
Labels: bug, Framework, in review, MueLu

**Comment by jhux2** [comment] 2016-08-15 17:04
Thank you, Ross.
