### ISSUE TITLE
Aztecoo:  Solver does not iterate, zero solution returned

### ISSUE THREAD

**Issue by gkovacsds** [trilinos/Trilinos#6935] opened 2020-03-02 17:40 UTC
## Question
@trilinos/Aztecoo

Based on the "aztecoo simple epetra crs matrix" example, I created this small program which reads a marketmatrix mtx file (reader code copied from EpetraExt), also the B vector (as simple text file), and optionally the pre-calculated known solution for checking (simple text file too).
So you can just replace  packages/aztecoo/example/simple_epetra_aztecoo/cxx_main.cpp to compile (copy the included MTXReader.h file there too).

It's all fine with one process calculation, but when I try with more MPI processes I've found that for a sq.matrix about 15000 in size Aztecoo does not make any calculation iterations.
For an 8x8 matrix with for example 4 processes it solves with no problem.
But with a larger matrix like this, it does not even start solving.
Anyone has an idea what am I missing here? 

I zipped the sources, the test matrix files and the outputs it produces for 1 and 2 process runs.
We tried it both on Linux and Windows with the same results.
To run it simply write mtx file as parameter: AztecOO_epetra_crsmatrix.exe nmos4_1.mtx

Thank you.

[mtxsolver.zip](https://github.com/trilinos/Trilinos/files/4276963/mtxsolver.zip)

**Comment by mhoemmen** [comment] 2020-03-02 23:48
@trilinos/aztecoo

**Comment by jhux2** [comment] 2020-03-06 18:52
This looks like a duplicate of #6837.  Did you try what I suggested [there](https://github.com/trilinos/Trilinos/issues/6837#issuecomment-590455269) before you tried rolling your own reader?

**Comment by jhux2** [comment] 2021-12-13 02:12
Closing due to inactivity.  Please reopen if necessary.

**Closed by jhux2** 2021-12-13 02:12 UTC
Labels: type: question, pkg: AztecOO, MARKED_FOR_CLOSURE
