### ISSUE TITLE
Panzer: dofmngr_test, narrowing conversion error (MPI on)

### ISSUE THREAD

**Issue by sagitter** [trilinos/Trilinos#844] opened 2016-11-14 20:04 UTC
Hi all.

`dofmngr_test` does not compile with following error:

```
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp: In member function 'virtual void panzer::tOrientation_testEdgeBasis_tri_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const':
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp:199:27: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
    char tests[] = { 1,1,-1}; // for element 2
                           ^
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp: In member function 'virtual void panzer::tOrientation_testEdgeBasis_quad_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const':
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp:313:29: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
    char tests[] = { 1,1,1,-1}; // for element 2
                             ^
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp: In member function 'virtual void panzer::tOrientation_testFaceBasis_tri_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const':
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp:426:27: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
    char tests[] = { 1,1,-1}; // for element 2
                           ^
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp: In member function 'virtual void panzer::tOrientation_testFaceBasis_quad_UnitTest::runUnitTestImpl(Teuchos::FancyOStream&, bool&) const':
/builddir/build/BUILD/trilinos-12.8.1/buildopenmpi_dir/packages/panzer/disc-fe/test/dofmngr_test/tOrientations.cpp:540:29: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
    char tests[] = { 1,1,1,-1}; // for element 2
                             ^
make[2]: *** [packages/panzer/disc-fe/test/dofmngr_test/CMakeFiles/PanzerDiscFE_tOrientations.dir/build.make:66: packages/panzer/disc-fe/test/dofmngr_test/CMakeFiles/PanzerDiscFE_tOrientations.dir/tOrientations.cpp.o] Error 1
```

Fedora 26 64-bit
GCC 6.2.1
Full log: https://kojipkgs.fedoraproject.org//work/tasks/8580/16448580/build.log

`cmake` configuration:

`+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release '-DCMAKE_C_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_CXX_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_Fortran_FLAGS_RELEASE:STRING=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -Wl,-z,relro -fPIC -Wl,-z,now' '-DCMAKE_EXE_LINKER_FLAGS:STRING=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fPIC -pie -Wl,-z,now -Wl,--as-needed' -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_SKIP_INSTALL_RPATH:BOOL=YES -DBUILD_SHARED_LIBS:BOOL=ON -DTPL_ENABLE_MPI=ON -DMPI_BASE_DIR= -DTrilinos_ENABLE_FORTRAN=ON -DTrilinos_ENABLE_TESTS:BOOL=ON -DTrilinos_ENABLE_OpenMP=ON -DTrilinos_ENABLE_PyTrilinos:BOOL=ON -DTPL_ENABLE_MPI4PY:BOOL=ON -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON -DPyTrilinos_INSTALL_PREFIX:PATH=/usr/lib64 -DPYTHON_VERSION:STRING=2.7 -DTpetra_INST_SERIAL:BOOL=OFF -DCMAKE_VERBOSE_MAKEFILE=TRUE -DTrilinos_VERBOSE_CONFIGURE=OFF -DTrilinos_ENABLE_CXX11=ON -DTrilinos_INSTALL_INCLUDE_DIR=/usr/include/openmpi-ppc64/trilinos -DTrilinos_INSTALL_LIB_DIR=/usr/lib64/openmpi/lib -DTrilinos_INSTALL_RUNTIME_DIR=/usr/lib64/openmpi/bin -DTrilinos_INSTALL_EXAMPLE_DIR=/usr/share/trilinos/examples -DTrilinos_ENABLE_STRONG_C_COMPILE_WARNINGS=OFF -DTrilinos_ENABLE_STRONG_CXX_COMPILE_WARNINGS=OFF -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -DTPL_ENABLE_gtest:BOOL=OFF -DTrilinos_ENABLE_EXAMPLES:BOOL=OFF -DForTrilinos_ENABLE_EXAMPLES:BOOL=OFF -DCTrilinos_ENABLE_EXAMPLES:BOOL=OFF -DPyTrilinos_ENABLE_EXAMPLES:BOOL=OFF -DTrilinos_ENABLE_STK:BOOL=OFF -DTrilinos_ENABLE_ALL_PACKAGES=ON ..`

**Comment by jmgate** [comment] 2016-11-14 20:12
@trilinos/panzer

**Comment by sagitter** [comment] 2016-11-18 09:28
How can i disable this test?
`-D PanzerDofMngr_ENABLE_TESTS:BOOL=OFF` or `-D Panzer_ENABLE_TESTS:BOOL=OFF` do not work.

**Comment by rppawlo** [comment] 2016-11-18 13:32
@sagitter I was able to disable the tests using -D Panzer_ENABLE_TESTS=OFF. The configure output shows that all tests are off (just libraries/subpackages are enabled):
```
Processing enabled package: Rythmos (Libs)
Processing enabled package: Piro (Libs)
Processing enabled package: Panzer (Core, DofMgr, DiscFE, AdaptersSTK)
```
I ran the build and none of the tests, including the problematic one, were built. 
The problematic test is in the disc-fe subpackage directory and the "test" directory doesn't exist:
```
[rppawlo@gge disc-fe]$ pwd
/ascldap/users/rppawlo/junk/BUILD2/packages/panzer/disc-fe
[rppawlo@gge disc-fe]$ ls
CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  PanzerDiscFEConfig.cmake  src
[rppawlo@gge disc-fe]$ 
```
Running panzer tests shows no executables were built either:
```
[rppawlo@gge BUILD2]$ ctest -R Panzer
Test project /ascldap/users/rppawlo/junk/BUILD2
No tests were found!!!
```

You might want to try deleting your CMakeCache.txt file in the build directory and then reconfiguring. If that doesn't work, can you send the CMakeCache.txt file?

**Comment by crtrott** [comment] 2017-01-27 18:27
I seem to have the same issue ...

**Comment by crtrott** [comment] 2017-03-01 18:07
Ok is anybody fixing this??

**Comment by crtrott** [comment] 2017-03-01 18:08
I assigned you Roger ;-), and if you don't fix it till next integration I do it for you :-D

**Comment by rppawlo** [comment] 2017-03-02 01:09
@crtrott - can you send me a configure file (and loaded sems modules if applicable). I can't reproduce. Have tried the -Wnarrowing and all the configure flags mentioned above. I've tried multiple machines and multiple gcc compilers from 5.X and 6.X series. Nothing is working. Is there a specific platform you see this on that I could access?

**Comment by rppawlo** [comment] 2018-04-27 20:25
This should be fixed.

**Closed by rppawlo** 2018-04-27 20:25 UTC
Labels: Panzer, bug
