### ISSUE TITLE
Stokhos + MueLu:  Compile failure with CUDA + UVM

### ISSUE THREAD

**Issue by sebrowne** [trilinos/Trilinos#12767] opened 2024-02-21 23:01 UTC
## Bug Report
@trilinos/stokhos 
@trilinos/muelu 
Compile-time errors in Stokhos and MueLu when building with UVM enabled by default.  We want to add a PR build that exercises this configuration for Albany (@mperego ), so these errors need to be fixed first.  Or we turn off the packages.  But I'm guessing that's not the way we want to go.

### Steps to Reproduce
1. SHA1:  develop HEAD 2024-02-21 (fe842145d8754d2f1f26855a51292df0d83346db)
2. Configure script:
```
source ../Trilinos/packages/framework/GenConfig/gen-config.sh rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_all ../Trilinos
```
This will expose MueLu and Stokhos build errors.

**Comment by cgcgcg** [comment] 2024-02-21 23:08
@sebrowne If the errors are specific to only a couple of spots, could you post them? Or is it all over the place?

**Comment by ndellingwood** [comment] 2024-02-21 23:20
Do MueLu and/or Stokhos expect to also have `-DKokkos_ENABLE_CUDA_UVM=ON` set as well?

**Comment by sebrowne** [comment] 2024-02-21 23:22
@cgcgcg 
File that failed to compiler in MueLu is (well, output file): `packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/ETI_MueLu_UtilitiesBase.cpp.o`

@ndellingwood I stopped setting that option as per input from @csiefer2 and @mperego , but I can turn it back on if needed.  My understanding is that that Kokkos option is going away?

**Comment by sebrowne** [comment] 2024-02-21 23:24
Ignore that my build dir is named 'uvm_off', I promise it was on....

```
/scratch/sebrown/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=size_t *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, RT=size_t *, RP=<std::conditional_t<true, Kokkos::CudaSpace::execution_space, Kokkos::DefaultExecutionSpace>>]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp(205): here
            instantiation of "Teuchos::RCP<MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Vector> MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::GetMatrixDiagonal(const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Matrix &) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=longlong, Node=Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(34): here

/scratch/sebrown/Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(3541): error: static assertion failed with "View assignment must have compatible spaces"
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<size_t *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, SrcTraits=Kokkos::ViewTraits<size_t *, std::conditional_t<true, Kokkos::CudaSpace::execution_space, Kokkos::DefaultExecutionSpace>>]" 
/scratch/sebrown/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1321): here
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=size_t *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, RT=size_t *, RP=<std::conditional_t<true, Kokkos::CudaSpace::execution_space, Kokkos::DefaultExecutionSpace>>]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp(205): here
            instantiation of "Teuchos::RCP<MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Vector> MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::GetMatrixDiagonal(const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Matrix &) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=longlong, Node=Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(34): here

/scratch/sebrown/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=const size_t *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, RT=size_t *, RP=<std::conditional_t<true, Kokkos::CudaSpace::execution_space, Kokkos::DefaultExecutionSpace>>]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp(206): here
            instantiation of "Teuchos::RCP<MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Vector> MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::GetMatrixDiagonal(const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Matrix &) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=longlong, Node=Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(34): here

/scratch/sebrown/Trilinos/packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp(3541): error: static assertion failed with "View assignment must have compatible spaces"
          detected during:
            instantiation of "void Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::assign(Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::DstType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::SrcType &, const Kokkos::Impl::ViewMapping<DstTraits, SrcTraits, std::enable_if_t<<expression>, void>>::TrackType &) [with DstTraits=Kokkos::ViewTraits<const size_t *, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, SrcTraits=Kokkos::ViewTraits<size_t *, std::conditional_t<true, Kokkos::CudaSpace::execution_space, Kokkos::DefaultExecutionSpace>>]" 
/scratch/sebrown/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1321): here
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=const size_t *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, RT=size_t *, RP=<std::conditional_t<true, Kokkos::CudaSpace::execution_space, Kokkos::DefaultExecutionSpace>>]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp(206): here
            instantiation of "Teuchos::RCP<MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Vector> MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::GetMatrixDiagonal(const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Matrix &) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=longlong, Node=Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(34): here

/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp(1015): warning: missing return statement at end of non-void function "MueLu::DetectDirichletRows_kokkos<SC,LO,GO,NO,memory_space>(const Xpetra::Matrix<SC, LO, GO, NO> &, const Teuchos::ScalarTraits<SC>::magnitudeType &, __nv_bool) [with SC=double, LO=int, GO=longlong, NO=Tpetra_KokkosCompat_KokkosCudaWrapperNode, memory_space=Kokkos::HostSpace]"
          detected during:
            instantiation of "Kokkos::View<__nv_bool *, memory_space> MueLu::DetectDirichletRows_kokkos<SC,LO,GO,NO,memory_space>(const Xpetra::Matrix<SC, LO, GO, NO> &, const Teuchos::ScalarTraits<SC>::magnitudeType &, __nv_bool) [with SC=double, LO=int, GO=longlong, NO=Tpetra_KokkosCompat_KokkosCudaWrapperNode, memory_space=Kokkos::HostSpace]" 
(1032): here
            instantiation of "Kokkos::View<__nv_bool *, Kokkos::HostSpace> MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::DetectDirichletRows_kokkos_host(const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Matrix &, const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Magnitude &, __nv_bool) [with Scalar=double, LocalOrdinal=int, GlobalOrdinal=longlong, Node=Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(34): here

/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp(1015): warning: missing return statement at end of non-void function "MueLu::DetectDirichletRows_kokkos<SC,LO,GO,NO,memory_space>(const Xpetra::Matrix<SC, LO, GO, NO> &, const Teuchos::ScalarTraits<SC>::magnitudeType &, __nv_bool) [with SC=std_complex0double0, LO=int, GO=longlong, NO=Tpetra_KokkosCompat_KokkosCudaWrapperNode, memory_space=Kokkos::HostSpace]"
          detected during:
            instantiation of "Kokkos::View<__nv_bool *, memory_space> MueLu::DetectDirichletRows_kokkos<SC,LO,GO,NO,memory_space>(const Xpetra::Matrix<SC, LO, GO, NO> &, const Teuchos::ScalarTraits<SC>::magnitudeType &, __nv_bool) [with SC=std_complex0double0, LO=int, GO=longlong, NO=Tpetra_KokkosCompat_KokkosCudaWrapperNode, memory_space=Kokkos::HostSpace]" 
(1032): here
            instantiation of "Kokkos::View<__nv_bool *, Kokkos::HostSpace> MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::DetectDirichletRows_kokkos_host(const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Matrix &, const MueLu::UtilitiesBase<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Magnitude &, __nv_bool) [with Scalar=std_complex0double0, LocalOrdinal=int, GlobalOrdinal=longlong, Node=Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/scratch/sebrown/Trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp(34): here

4 errors detected in the compilation of "/scratch/sebrown/build_uvm_off/packages/muelu/src/Utils/ExplicitInstantiation/ETI_MueLu_UtilitiesBase.cpp".
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by ndellingwood** [comment] 2024-02-21 23:29
> My understanding is that that Kokkos option is going away?

@sebrowne correct, the plan is for it to go away with the eventual Kokkos version 5, testing builds without `Kokkos_ENABLE_CUDA_UVM` set (but using the package specific options) is a good status check 👍 

I think with Tpetra they had to introduce some additional code so that they could enable and control templating of the Views on `SharedSpace` to support the new configure option as a UVM replacement. Maybe other packages will need to do similar things, for example to get all the ETI stuff working (when it isn't automatically handled by `-DKokkos_ENABLE_CUDA_UVM=ON`)?

**Comment by ndellingwood** [comment] 2024-02-21 23:34
Adding references to the Tpetra PRs, looks like there were already updates to address MueLu, so my guess about needing something like similar SharedSpace support must be wrong:
* https://github.com/trilinos/Trilinos/pull/12622
* https://github.com/trilinos/Trilinos/pull/12626

**Comment by cgcgcg** [comment] 2024-02-21 23:44
@sebrowne Just double checking: does this Trilinos build already have the changes of PR #12738?

**Comment by mperego** [comment] 2024-02-22 00:13
@sebrowne we could disable Stokhos as Albany does not use it. Unless @etphipp is willing to maintain it functional with UVM.

**Comment by sebrowne** [comment] 2024-02-22 13:38
@cgcgcg yes I have that merge commit in my checkout.
@mperego that's fine by me, will let you make the final decision

**Comment by cgcgcg** [comment] 2024-02-22 18:12
@sebrowne Ok, please pull and try again.

**Comment by etphipp** [comment] 2024-02-22 22:39
I was able to reproduce this and Christian's changes did seem to resolve the MueLu errors.  I am working on the stokhos errors.  They shouldn't be hard to fix (just need to modify how some partial specializations were done).

**Comment by etphipp** [comment] 2024-02-24 00:21
I think I got the stokhos errors fixed with PR #12771

**Comment by etphipp** [comment] 2024-02-26 17:07
For PR #12771 one of the builds failed (Intel) but it isn't showing on trilinos-cdash.  Is that on a different cdash?

**Comment by etphipp** [comment] 2024-02-27 15:42
Stokhos errors should be fixed now.

**Comment by sebrowne** [comment] 2024-02-28 16:18
Confirmed the nightly build is fixed, thank you all!  I will be adding a new PR build for CUDA + UVM _without_ tests very soon.

**Comment by cgcgcg** [comment] 2024-04-03 20:42
Closing as fixed. If that's somehow not the case please reopen.

**Closed by cgcgcg** 2024-04-03 20:42 UTC
Labels: type: bug, pkg: MueLu, pkg: Stokhos
