### ISSUE TITLE
Teuchos:  Potential C++11 Non-compliance issues

### ISSUE THREAD

**Issue by csiefer2** [trilinos/Trilinos#1756] opened 2017-09-20 15:45 UTC
From here: http://en.cppreference.com/w/cpp/language/destructor

As any other function, a destructor may terminate by throwing an exception (this usually requires it to be explicitly declared noexcept(false)) (since C++11)

The destructor for Teuchos::RawWorkspace throws an exception without a noexcept(false) declaration.

This causes Visual Studio to whine.

Is this worth fixing?

**Comment by aprokop** [comment] 2017-09-20 16:06
@trilinos/teuchos

**Comment by mhoemmen** [comment] 2017-09-20 17:52
Is this a duplicate of #1303?

**Comment by mhoemmen** [comment] 2017-09-20 17:52
@csiefer2 wrote:
> This causes Visual Studio to whine.

Does this mean "emit a warning" or "refuse to build"?

**Comment by csiefer2** [comment] 2017-09-20 17:55
@mhoemmen : "Emit a warning"

And yeah, this is probably a dupe.

**Comment by mhoemmen** [comment] 2017-09-20 17:59
@csiefer2 wrote:
> And yeah, this is probably a dupe.

No worries! :-) Just wanted to reference that issue.

**Closed by mhoemmen** 2017-09-20 17:59 UTC
Labels: Teuchos
