### ISSUE TITLE
Divide by zero error for rare corner case

### ISSUE THREAD

**Issue by kgbudge** [trilinos/Trilinos#2387] opened 2018-03-14 22:22 UTC
We are seeing a division by zero error in BelosIMGSOrthoManager.hpp, line 1141.  The problem occurs when the initial guess of the solution happens to be exactly right, so that the starting residual vector is exactly zero. We have determined that this can come up in real-world calculations using our application in rare corner cases, where the portion of the operator we're inverting is block identical on the portion of the right hand side that is nonzero. Then when we choose the right hand side as the starting guess of the solution, it _is_ the exact solution.

@trilinos/belos

## Expectations

We cannot easily tolerate division by zero errors, even if they are "benign" in the sense that later code paths never use the result, because we often build on platforms with floating point errors trapped as fatal errors. We need some check that the starting residual is zero that avoids the zero division.

## Steps to Reproduce

Give Belos the identity as its operator to invert and the same vector as both right hand side and starting guess of the solution.

**Comment by mhoemmen** [comment] 2018-03-15 12:58
@trilinos/belos

**Comment by mhoemmen** [comment] 2018-03-15 12:58
@kgbudge Thanks for reporting!

**Comment by maherou** [comment] 2018-03-17 18:51
@kgbudge,  it seems like the expected behavior of this situation is to return as converged after testing this value and finding that it is zero.  Is this a fix you would like to contribute?  Just checking.

**Comment by hkthorn** [comment] 2018-03-19 20:05
@kgbudge @mhoemmen @maherou I have been trying to recreate this issue with the IMGS orthogonalization manager, with no success.   The line of code (1141) in the  BelosIMGSOrthoManager.hpp file is currently a comment about "Copy vector into current column of _basisvecs".  There isn't a division near this line.  The git log for this file indicates that there was a case of lucky breakdown that was not being detected by the orthogonalization methods, but this issue was fixed in July of 2017.  So, I'm going to ask if this issue is being experienced with the most recent release of Trilinos or the development branch, or an older version?  If it is the most recent release or development branch, could you tell me the exact solver setup that is being used (which solver, single-vector or block solve, is the linear system preconditioned?).  Thanks!

**Comment by hkthorn** [comment] 2018-04-25 23:14
@kgbudge @mhoemmen @maherou I have not heard anything about this bug, I can't recreate it, nor can I validate it because the referenced line changed in July of 2017 because of what may be the same issue.  I'm going to consider this bug closed.

**Closed by hkthorn** 2018-04-25 23:14 UTC
Labels: Belos

**Comment by klevzoff** [comment] 2020-08-03 01:09
Hi, a couple years later, I've faced the the same issue with 12.18 release. The offending line in current master is
https://github.com/trilinos/Trilinos/blob/97232ba86fa01f2ec58e4445cb10c7234ef325ad/packages/belos/src/BelosIMGSOrthoManager.hpp#L1165
The same issue can be reproduced with `"ICGS"`, but not with `"DGKS"` which proceeds to converge in 0 iterations (so does AztecOO, after issuing a warning).

The solver is `PSEUDOBLOCK GMRES`, the preconditioner is MueLu (but I bet you could reproduce it with an unpreconditioned solve), and the solver parameters are
```
  Implicit Residual Scaling = Norm of RHS
  Explicit Residual Scaling = Norm of RHS
  Maximum Iterations = 200
  Num Blocks = 200
  Maximum Restarts = 0
  Orthogonalization = IMGS
  Convergence Tolerance = 1e-12
```
In my case, both the RHS vector and initial solution happen to be all-zero, hence scaling either by RHS norm or residual norm leads to the same error. You have to have FP exceptions enabled, e.g. via `feenableexcept(FE_DIVBYZERO)`, to get a signal.

If no one sees this for a while because the issue has been closed, I will post a new one.

**Comment by mhoemmen** [comment] 2020-08-03 04:22
@jennloe might be able to help.  I am no longer a Trilinos developer.

**Comment by hkthorn** [comment] 2020-08-03 14:27
@klevzoff Thanks for bringing this to our attention.  The issue was found recently and fixed in this commit:

commit b0ec091c4e8191dc03ee5781f48099e724736c09
Author: Heidi Thornquist <hkthorn@sandia.gov>
Date:   Fri May 29 14:50:55 2020 -0600

    Fixes calls to normalize zero vectors in ICGS/IMGS (#7454)
    
    The logic that checks if the norm of a vector is zero before normalizing
    it needs to be inserted.  This conditional existed in DGKS, which is why
    this did not come up as a problem before the change to making ICGS[2] the
    default.
    
    The OrthoManager test has been amended to include a check for this
    functionality, so that it does not come up again for customers.
