### ISSUE TITLE
Compilation of Amesos2 with SuiteSparse fails

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#2146] opened 2018-01-10 12:46 UTC
When compiling Amesos2 with the latest version of SuiteSparse (for UMFPACK), I get the following error:
```
In file included from /opt/suitesparse/include/umfpack.h:29:0,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Umfpack_FunctionMap.hpp:56,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Umfpack_decl.hpp:49,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Umfpack.hpp:47,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Factory.hpp:108,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory_def.hpp:52,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Details_LinearSolverFactory.hpp:49,
                 from ~/Downloads/Trilinos/packages/amesos2/src/Amesos2_Details_registerLinearSolverFactory.cpp:45:
/opt/suitesparse/include/SuiteSparse_config.h:62:31: error: declaration does not declare anything [-fpermissive]
 #define SuiteSparse_long long int
```
on Tumbleweed, OpenMPI3 with GCC 7.2. Is that a bug?

**Comment by srajama1** [comment] 2018-01-10 16:13
@anates : What is the version of UMFPACK you are using ? 

@ndellingwood @MicheldeMessieres

**Comment by anates** [comment] 2018-01-11 08:14
The latest one from the website, i.e. UMFPACK 5.7.6

**Comment by srajama1** [comment] 2018-01-11 16:00
Thanks ! It appears something has changed in UMFPACK since 5.0 (tested version w/ Amesos2) ? We will support more recent versions, but till then I recommend switching to 5.0.

**Comment by MicheldeMessieres** [comment] 2018-01-11 16:08
@srajama1 Didn't try this new version yet - do you want me to take care of resolving this?

**Comment by srajama1** [comment] 2018-01-11 16:14
@MicheldeMessieres That would be great. Thanks !

**Comment by anates** [comment] 2018-01-15 08:12
What do you mean with "config"? The command line options/cmake-options?

**Comment by srajama1** [comment] 2018-01-15 19:26
Config in Trilinos lingo is the cmake options.

**Comment by MicheldeMessieres** [comment] 2018-01-16 02:44
@anates Your cmake options may be helpful in case there is some kind of include conflict we haven't tested. It may also be productive to try just a serial build (no openmpi) and verify if that fails in the same way. That would determine if the error might be related to gcc 7.2 and not openmpi and help narrow this down.

For reference, to test umfpack with amesos2 I build the latest SuiteSparse and add the following CMake options to a setup for the latest develop branch. But I did not setup a test for linux with gcc 7.2 yet.

```
  -DTrilinos_ENABLE_Amesos2:BOOL=ON \
  -DAmesos2_ENABLE_TESTS:BOOL=ON \
  -DAmesos2_ENABLE_UMFPACK:BOOL=ON \
  -DUMFPACK_INCLUDE_DIRS:PATH=<path>/SuiteSparse/include' \
  -DUMFPACK_LIBRARY_DIRS:PATH='<path>/SuiteSparse/lib' \
  -DTPL_ENABLE_UMFPACK:BOOL=ON \
```

**Comment by MicheldeMessieres** [comment] 2018-01-17 17:22
@anates I tried with gcc 7.2 and openmpi3 but no luck reproducing this. I do get some new segfaults for one amesos3 test (Amesos2_SolverFactory_UnitTests_MPI_4) with openmpi but the umfpack test seems to build and pass correctly.

I build SuiteSparse just by doing make in the root. If you are building SuiteSparse/Umfpack in a different way and/or turning off any packages, it might be useful if I replicate your process in case that is a factor.

**Comment by srajama1** [comment] 2018-01-17 17:59
@MicheldeMessieres : It might be good to file another bug for the segfault.

**Comment by srajama1** [comment] 2018-01-18 16:16
@MicheldeMessieres Thanks !

**Comment by anates** [comment] 2018-12-18 16:07
Config attached, using SuiteSparse 5.3.0. Sorry for the delay, had many other things to do in the meantime.
[CMakeCache_bug.txt](https://github.com/trilinos/Trilinos/files/2691301/CMakeCache_bug.txt)

**Closed** 2021-07-07 12:23 UTC
Labels: CLOSED_DUE_TO_INACTIVITY, MARKED_FOR_CLOSURE, pkg: Amesos2
