### ISSUE TITLE
Teuchos: RCPNode fails to compile under Intel 17.0.1 (SEMS)

### ISSUE THREAD

**Issue by dridzal** [trilinos/Trilinos#2172] opened 2018-01-18 17:39 UTC
@trilinos/teuchos 
@trilinos/framework 

This error started occurring in my nightly tests after a recent merge from the Trilinos repo into the separate ROL-Trilinos repo.  I'm not sure if it's a code bug, or a CMake / Testing issue.  However, I suspect a code bug because the gnu builds work just fine.

**Error while building C++ object file " CMakeFiles/teuchoscore.dir/Teuchos_RCPNode.cpp.o" in target teuchoscore** 

```
Source File | packages/teuchos/core/src/Teuchos_RCPNode.cpp
Label | TeuchosCoreLibs
Command | [+] "/projects/sems/install/rhel6-x86_64/sems/compiler/intel/17.0.1/openmpi/1.10.1/bin/mpicxx"
Directory | /home/dridzal/development/TEST/rol-trilinos/BUILD/packages/teuchos/core/src
Exit Condition | 2

/ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp(490): error: class "std::multimap<const void *, <unnamed>::RCPNodeInfo, std::less<const void *>, std::allocator<std::pair<const void *const, <unnamed>::RCPNodeInfo>>>" has no member "emplace_hint"
      (*rcp_node_list()).emplace_hint(
                         ^

compilation aborted for /ascldap/users/dridzal/development/TEST/rol-trilinos/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp (code 2)
```

**Comment by ibaned** [comment] 2018-01-18 17:59
This is a duplicate of #2128, and its actually because SEMS set up the Intel 17.0.1 module to point to a GCC version that Trilinos no longer supports. SEMS needs to fix its Intel 17.0.1 module.

You can do this as a workaround in the meantime:
```
module swap sems-gcc/4.7.2 sems-gcc/4.8.4
```
Then reconfigure and recompile Trilinos

**Comment by ibaned** [comment] 2018-01-18 18:02
The effort to fix the SEMS module is tracked by issue #2142

**Comment by bartlettroscoe** [comment] 2018-01-18 18:03
If loading sems-gcc/4.8.4 before loading sems-intel/??? fixes the problem, then we can make the Trilinos/cmake/load_sems_dev_env.sh automatically do that if we like.  But someone needs to test to make sure that a full build of Trilinos will work with that trick.

**Comment by ibaned** [comment] 2018-01-18 18:04
@bartlettroscoe I think that does fix the problem

**Comment by dridzal** [comment] 2018-01-18 19:50
The ROL-Trilinos tests should be able to test this tonight.  Correct, @bartlettroscoe ? Are the SEMS changes propagated automatically, or do I need to do something manually?

**Comment by ibaned** [comment] 2018-01-18 19:53
@dridzal only if they use this script and only if this gets merged into develop.

**Comment by dridzal** [comment] 2018-01-18 19:58
@ibaned They use the pre-push / checkin-test infrastructure.  When will this get into develop?  I can fire off another sync between ROL-Trilinos and Trilinos when the changes are in.

**Comment by mhoemmen** [comment] 2018-01-18 19:58
This is a duplicate of #2128.

**Closed by mhoemmen** 2018-01-18 19:58 UTC
