### ISSUE TITLE
Xpetra fatal error due to missing headers, similar to #5011

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#5098] opened 2019-05-06 12:26 UTC
We have another missing Xpetra missing header file:

In file included from /scratch/spdomin/nightlyBuildAndTest/NaluNightly/include/LinearSolver.h:34:0,
                 from /scratch/spdomin/nightlyBuildAndTest/NaluNightly/src/EnthalpyEquationSystem.C:43:
/home/spdomin/gitHubWork/scratch_build/install/gcc7.2.0/Trilinos_nightly_release/include/MueLu.hpp:63:10: fatal error: Xpetra_CrsMatrixWrap.hpp: No such file or directory
 #include <Xpetra_CrsMatrixWrap.hpp>

This looks almost the same as the foamier issue that @jhux2 fixed and what @bartlettroscoe asked, "How did this pass PR testing? Is the file Xpetra_CrsMatrixFactory.hpp not included in any automated tests run in PR testing? Or are globs not used to install header files."

https://github.com/trilinos/Trilinos/issues/5011

Best,

**Comment by bartlettroscoe** [comment] 2019-05-06 13:59
@trilinos/xpetra, @kddevin (Trilinos Data Services Product Area Lead), @fryeguy52, @micahahoward, @sebrowne 

Yea, this also brought down all of the SPARC Trilinos Integration builds as well.  Therefore, I have added the label `ATDM Sev: Critical`.

Can we figure out why these errors (this and #5011) are slipping through PR testing?  I we run a coverage build on Xpetra, what does that look like?

**Comment by mhoemmen** [comment] 2019-05-06 14:07
@bartlettroscoe wrote:
> Can we figure out why these errors (this and #5011) are slipping through PR testing?

I remember @jhux2 mentioning something about PR tests not having any static builds.  My guess is that this is some combination of static and ETI OFF.

**Comment by bartlettroscoe** [comment] 2019-05-06 14:52
@mhoemmen said:

> My guess is that this is some combination of static and ETI OFF.

It would be good if we could confirm this and then put in a GitHub issue for the Framework team to change on of the PR builds to a static build (likely the GCC 7.2.0 build since static builds as the default for most of the larger customers).

**Comment by jhux2** [comment] 2019-05-06 16:43
I'm looking at this now.

**Comment by bartlettroscoe** [comment] 2019-05-06 16:58
Looks like the file `Xpetra_CrsMatrixFactory.hpp` is not getting installed:

```
$ ls /projects/atdm_devops/trilinos_installs/2019-05-05/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap*
/projects/atdm_devops/trilinos_installs/2019-05-05/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap_decl.hpp
/projects/atdm_devops/trilinos_installs/2019-05-05/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap_def.hpp
/projects/atdm_devops/trilinos_installs/2019-05-05/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap_fwd.hpp
```

but it exists in the build tree:

```
Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/SRC_AND_BUILD/BUILD/packages/xpetra/sup/Xpetra_CrsMatrixWrap.hpp
```

which is just:

```
#include "Xpetra_CrsMatrixWrap_decl.hpp"
```

So this would seem to be a problem if installing a generated header file?  Are there not TriBITS macros that will generate these `XXX.hpp` header files and help add them to the set of header files to install so this is automatic?

So it looks like what we really need is installation testing as part of PR testing (i.e. #5027).

**Comment by jhux2** [comment] 2019-05-06 17:53
PR #5107 should fix this.

**Comment by jjellio** [comment] 2019-05-06 19:24
@bartlettroscoe 

I think one way to help dodge this problem would be to modify `TribitsCreateClientTemplateHeaders` and `TRILINOS_CREATE_CLIENT_TEMPLATE_HEADERS`.  So that it takes a list of HEADERS as input, and appends the created header to that list (set SCOPE PARENT).


Right now, the problem seems to be that the headers are GLOB'd, headers are generated, You then must GLOB in the **binary dir** to find those headers. The default location for GLOB appears to be the source directory.


https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/core/package_arch/TribitsCreateClientTemplateHeaders.cmake

Installation testing would help catch the mistake, but in general the programming interface for doing generated headers leaves the burden of knowing where those functions placed the headers on the user. (And I think most will forget to look in the binary dir, not the source dir)

**Comment by bartlettroscoe** [comment] 2019-05-06 22:33
@jjellio said:

> I think one way to help dodge this problem would be to modify `TribitsCreateClientTemplateHeaders` and `TRILINOS_CREATE_CLIENT_TEMPLATE_HEADERS` so that it takes a list of HEADERS as input, and appends the created header to that list (set SCOPE PARENT).

Just so that I understand what you are suggesting, can you show what the updated call to this function would look like for this Xpetra CMakeLists.txt file?  It looks like PR #5107 just added an additional glob of header files in a new dir to be installed.

What we really need in installation testing as part of PR testing.  It looks like that would have caught this.

**Comment by jhux2** [comment] 2019-05-06 23:33
> PR #5107 should fix this.

PR has merged, let's see what happens overnight.

**Comment by jjellio** [comment] 2019-05-07 05:01
@bartlettroscoe 

My comment is mainly because *all* of the ETI work is subject to the error that manifest here. It just seems it would be cleaner to have the ETI function do the dirty work.

With ETI, there is *always* the pattern:
```
TRILINOS_CREATE_CLIENT_TEMPLATE_HEADERS(${CMAKE_CURRENT_SOURCE_DIR}/CrsMatrix)
SET_AND_INC_DIRS(DIR ${CMAKE_CURRENT_SOURCE_DIR}/CrsMatrix)
# Better remember to do this!
APPEND_SET(HEADERS ${CMAKE_CURRENT_BINARY_DIR}/*.hpp)
```

Why not do:
```
TRILINOS_CREATE_CLIENT_TEMPLATE_HEADERS(
  ${CMAKE_CURRENT_SOURCE_DIR}/CrsMatrix
  HEADERS ${List_Variable} )
```

The function does: (new features)
```
TRILINOS_CREATE_CLIENT_TEMPLATE_HEADERS( DIR HEADERS)
# The current tribits function is outputing to CURRENT_BINARY_DIR
# so we append CURRENT_BINARY_DIR + DIR to the headers

SET_AND_INC_DIRS(DIR)
# append DIR + wherever Tribits will put the generated file
list(APPEND HEADERS DIR CURRENT_BINARY_DIR)
# propagate the value to the parent
SET(HEADERS HEADERS PARENT SCOPE)
# I think both Tribits and Trilinos's function will have to call SET + PARENT SCOPE
```

Now, all ETI work just needs to call the Create Client Template, and the HEADERS variable will get set.

This thought train comes from looking at the Xpetra ETI work - if the pattern followed there is wrong, then we should figure out the best way to do it - as is, it seems error prone to make sure you include/install generated files.

**Comment by bartlettroscoe** [comment] 2019-05-07 12:24
FYI:

Just checked the updated install this morning and it looks like the file `Xpetra_CrsMatrixWrap.hpp` is getting installed now:

```
$ ls /projects/atdm_devops/trilinos_installs/2019-05-07/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap*
/projects/atdm_devops/trilinos_installs/2019-05-07/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap_decl.hpp
/projects/atdm_devops/trilinos_installs/2019-05-07/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap_def.hpp
/projects/atdm_devops/trilinos_installs/2019-05-07/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap_fwd.hpp
/projects/atdm_devops/trilinos_installs/2019-05-07/cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt/include/Xpetra_CrsMatrixWrap.hpp
```

Will reopen this and then close once we get confirmation from the SPARC Trilinos Integration builds later today (for which we get an email tomorrow morning).

**Comment by spdomin** [comment] 2019-05-07 22:15
Looks clean...

100% tests passed, 0 tests failed out of 78
NaluCFD/Nalu SHA1: c77416f1547fbbe99740d10383fee3da4a1dbbad
Trilinos/develop SHA1: 766cf31408577f4896f256826751ae4426a7254a

Feel free to close this issue and, possibly, open an enhancement that helps us in the future.

For @mhoemmen's sake, we build Nalu with the following:

-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \

- and dynamic as well.

best,

**Comment by bartlettroscoe** [comment] 2019-05-07 22:26
I have confirmed this is fixed for SPARC too (but another change to Trilinos is still breaking the build :-)).  See [SPAR-567](https://sems-atlassian-srn.sandia.gov/browse/SPAR-567).

Closing as complete.

**Closed by bartlettroscoe** 2019-05-07 22:26 UTC
Labels: ATDM Sev: Critical, PA: Data Services, client: ATDM, client: SPARC, pkg: Xpetra, stage: in review, type: bug

**Comment by kddevin** [comment] 2019-05-07 22:35
@bartlettroscoe Can you add the Trilinos github issue number for the "another change to Trilinos" mentioned above.  When I try to access the Jira issue, I see, "You can't view this issue
It may have been deleted or you don't have permission to view it. "  THanks.

**Comment by bartlettroscoe** [comment] 2019-05-07 23:01
@kddevin asked:

> Can you add the Trilinos github issue number for the "another change to Trilinos" mentioned above. 

This is an Ifpack2 issue.  See #5132.

**Comment by kddevin** [comment] 2019-05-08 00:00
Thanks, @bartlettroscoe
