### ISSUE TITLE
Xpetra: link error ("file truncated"): GCC 4.9.3, MPI_DEBUG, OpenMP enabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2764] opened 2018-05-16 20:55 UTC
I'm trying to add a new test to Ifpack2.  Ifpack2 depends optionally on Xpetra.  When building Ifpack2's unit tests, I get the following link error:
```
Scanning dependencies of target belostpetra
[ 87%] Linking CXX shared library libxpetra.so
[ 87%] Linking CXX shared library libbelosepetra.so
CMakeFiles/xpetra.dir/Utils/Xpetra_Utils.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[2]: *** [packages/xpetra/src/libxpetra.so.12.13] Error 1
CMakeFiles/belosepetra.dir/BelosEpetraAdapter.cpp.o: file not recognized: make[1]: File truncated*** [packages/xpetra/src/CMakeFiles/xpetra.dir/all] Error 2
```
This is an `MPI_DEBUG` build, with GCC 4.9.3 and OpenMP enabled.  The corresponding `MPI_RELEASE` build does not have this issue.

@trilinos/xpetra @trilinos/muelu

**Comment by jhux2** [comment] 2018-05-16 21:04
@mhoemmen Not sure what's happening.  I wonder if this could be a file size issue, similar to #1605.

Did this work previously for you?
What linker are you using?

**Comment by jhux2** [comment] 2018-05-16 21:36
Out of curiousity, how big are the files that are reported to be truncated?

CMakeFiles/xpetra.dir/Utils/Xpetra_Utils.cpp.o
CMakeFiles/belosepetra.dir/BelosEpetraAdapter.cpp.o

**Comment by mhoemmen** [comment] 2018-05-17 04:59
```
$ ls -l `find . -name Xpetra_Utils.cpp.o`
-rw-rw-r-- 1 mhoemme mhoemme 0 May 16 12:20 ./packages/xpetra/src/CMakeFiles/xpetra.dir/Utils/Xpetra_Utils.cpp.o

$ ls -l `find . -name BelosEpetraAdapter.cpp.o`
-rw-rw-r-- 1 mhoemme mhoemme 0 May 16 12:20 ./packages/belos/epetra/src/CMakeFiles/belosepetra.dir/BelosEpetraAdapter.cpp.o
```

**Comment by jhux2** [comment] 2018-05-17 23:19
I'm stumped. If this is with the SEMS environment, and you'll provide a cmake configuration script, I will try to reproduce on the CEE lan.

**Comment by mhoemmen** [comment] 2018-05-18 03:53
@jhux2 Let me play around with the linker first -- this is a very old SEMS environment, installed locally on my workstation, so the modules may no longer exist or may have been moved.

**Comment by mhoemmen** [comment] 2018-05-18 03:53
@jhux2 Try enabling complex and debug.

**Comment by jjellio** [comment] 2018-05-18 15:06
This isn't a library truncation error. Binutils probably won't change anything.   The .o is whacked. Is your filesystem full?

**Comment by jhux2** [comment] 2018-05-18 17:59
@mhoemmen A debug build with complex and openmp works for me on the CEE lan.  I suspect that there may be something amiss in your local environment.  I will close this, but please reopen if this can be reproduced with a current SEMS environment.

Trilinos master, `d1a98e6f`

```
Currently Loaded Modulefiles:
  1) sems-env
  2) sems-gcc/4.9.2
  3) sems-openmpi/1.10.1
  4) sems-cmake/3.5.2
  5) sems-python/2.7.9
  6) sems-boost/1.58.0/base
  7) sems-superlu/4.3/base
  8) sems-yaml_cpp/0.5.3/base
  9) sems-parmetis/4.0.3/parallel
 10) sems-hdf5/1.8.12/parallel
 11) sems-netcdf/4.4.1/exo_parallel
```

My configure script:
```
#!/bin/bash

#options from command line
EXTRA_ARGS=$@

ARGS=(
  -D Trilinos_ENABLE_OpenMP=ON
  -GNinja -DTrilinos_ENABLE_Fortran:BOOL=OFF
  -D CMAKE_BUILD_TYPE:STRING=DEBUG
  -D Trilinos_ENABLE_MueLu:BOOL=ON
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON
  -D MueLu_ENABLE_TESTS:STRING=ON
  -D Trilinos_ENABLE_COMPLEX:BOOL=ON
)

cmake "${ARGS[@]}" ${EXTRA_ARGS} ../Trilinos
```

**Closed by jhux2** 2018-05-18 17:59 UTC
Labels: Xpetra, build

**Comment by mhoemmen** [comment] 2018-05-19 15:36
@jjellio wrote:
> This isn't a library truncation error. Binutils probably won't change anything. The .o is whacked. Is your filesystem full?

It's possible, but unlikely.  I could use some help getting modules updated on my workstation; it's been a couple years I think.  I might actually just roll my own so I can get a new binutils.
