### ISSUE TITLE
Stratimikos and Rythmos tests failing on many ATDM builds

### ISSUE THREAD

**Issue by fryeguy52** [trilinos/Trilinos#4678] opened 2019-03-20 17:32 UTC
CC: @trilinos/stratimikos, @srajama1 (Trilinos Linear Solvers Product Lead), @rppawlo (Trilinos Nonlinear Solvers Product Lead), @bartlettroscoe, @fryeguy52
 
<Checklist>
<???: Add label "ATDM">
<???: Add label "bug"?>
<???: Add label for affected packages (e.g. "MueLu", "Tpetra", "Kokkos", etc.)>
<???: Add milestone "Initial cleanup of new ATDM builds of Trilinos" or "Keep promoted ATDM builds of Trilinos clean">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
 
## Next Action Status
<status-and-or-first-action>
 
## Description
 
As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-03-20&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=5&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=status&compare2=61&value2=Failed&field3=testname&compare3=62&value3=Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4&field4=buildstarttime&compare4=83&value4=2019-03-20&field5=buildstarttime&compare5=84&value5=2019-03-21) the tests:
* Stratimikos_test_single_stratimikos_solver_driver_belos_np_MPI_1
* Stratimikos_test_single_stratimikos_solver_driver_belos_ml_MPI_1
* Stratimikos_test_single_stratimikos_solver_driver_belos_ifpack_MPI_1
* Rythmos_timeDiscretizedBackwardEuler_amesos_MPI_1

are failing in many ATDM builds.

[new commits when these started failing](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4754139#!#note4)

## Current Status on CDash

currently failing tests in ATDM builds can be seen [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-03-20&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=ATDM&field2=status&compare2=61&value2=Failed&field3=buildstarttime&compare3=83&value3=today&field4=buildstarttime&compare4=84&value4=tomorrow)

## Steps to Reproduce

One should be able to reproduce this failure on with a sems rhel6 environment as described in:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for with a sems rhel6 environment are provided at:
* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel6-environment

The exact commands to reproduce this issue should be:
```
$ cd <some_build_dir>/
$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release
$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_Stratimikos=ON \
 -DTrilinos_ENABLE_Rythmos=ON \
 $TRILINOS_DIR
$ make NP=16
$ ctest -j8
```

**Comment by srajama1** [comment] 2019-03-20 18:11
@cgcgcg @csiefer2 @jjellio @crtrott @jhux2 @mhoemmen : ATDM builds are failing and the commits where this started failing are listed above. I am including everyone who committed in some solver related work to let you know.

**Comment by jhux2** [comment] 2019-03-20 18:31
@srajama1 Could this be related to issue reported by @bartlettroscoe to the Trilinos dev email list?

**Comment by cgcgcg** [comment] 2019-03-20 18:40
The Stratimikos_* tests should get fixed by #4677

**Comment by srajama1** [comment] 2019-03-20 18:57
@jhux2 : Yes, that is right.  I am behind on trilinos-dev emails and checked github mentions first :)

@cgcgcg : Thanks for the quick fix. Hopefully that fixes it and it goes in.

**Comment by bartlettroscoe** [comment] 2019-03-20 20:28
Looking over the commits merged yesterday shown [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=4754139#!#note4), my guess would be the commit 41a6c06:

```
41a6c06:  Stratimikos Belos adapter: Use Belos solver factory
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Tue Mar 12 14:22:57 2019 -0600

A	packages/stratimikos/adapters/belos/src/Belos_Details_Thyra_registerSolverFactory.cpp
A	packages/stratimikos/adapters/belos/src/Belos_Details_Thyra_registerSolverFactory.hpp
M	packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_decl.hpp
M	packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp
A	packages/stratimikos/adapters/belos/src/Thyra_BelosSolverFactory.hpp
```

Could that have triggered this?  That looks like a major change.

It would be good to restore the working of a default tolerance.   I fear that this may impact downstream customer codes as well.

**Comment by bartlettroscoe** [comment] 2019-03-20 20:35
Prior to yesterday, the test ` Stratimikos_test_single_stratimikos_solver_driver_belos_ifpack_MPI_1 ` passed in 1 iteration as shown [here](https://testing-vm.sandia.gov/cdash-dev-view/testDetails.php?test=70954621&build=4723877)!  It was only in the PR build for #4606 that it took 1000 iterations as shown [here](https://testing-vm.sandia.gov/cdash/testDetails.php?test=71389332&build=4742787).  

Can we fix the code so that the default solve tolerance works like it did before #4606?

**Comment by cgcgcg** [comment] 2019-03-20 20:36
@bartlettroscoe Hm, if that's the case let me investigate

**Comment by bartlettroscoe** [comment] 2019-03-20 20:39
@cgcgcg said:

> @bartlettroscoe Hm, if that's the case let me investigate

Can we revert #4606 for now and fix it offline so that it restores correct behavior for default solve tolerance instead of taking this approach?

Still, how did this pass PR testing?

**Comment by mhoemmen** [comment] 2019-03-20 20:39
@cgcgcg I wonder if Stratimikos was setting its own default solver tolerance before, so that introduction of the SolverFactory was letting Belos set the default instead of having Stratimikos set it by hand.

**Comment by cgcgcg** [comment] 2019-03-20 21:20
@mhoemmen I believe the issue is this:
https://github.com/trilinos/Trilinos/blob/b3351b0ad00e579b7e73a4c6864556b0246063be/packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp#L289
We're not setting any of the defaults that are on deeper levels of the parameter list!

**Comment by bartlettroscoe** [comment] 2019-03-26 15:04
With the merge of PR #4684 that reverted the PR #4606, these test failures have now disappeared.

If a new PR is created for making similar changes and it breaks something, we will address that in a new GitHub issue.

Closing as complete.

**Closed by bartlettroscoe** 2019-03-26 15:04 UTC
Labels: ATDM Sev: Blocker, PA: Linear Solvers, PA: Nonlinear Solvers, client: ATDM, pkg: Rythmos, pkg: Stratimikos, type: bug
