### ISSUE TITLE
Intrepid2 now produces a lot of warnings under gcc and even more under cuda

### ISSUE THREAD

**Issue by bathmatt** [trilinos/Trilinos#1223] opened 2017-04-07 16:13 UTC
compiling panzer produces warnings in intrepid2 under these flags.  We need to clean these up to keep things clean going forward
-Wnarrowing and -Wdeprecated-declarations 

examples are 
```
/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefJacobian.hpp:172:80: warning: narrowing conversion of ‘jacobian.Kokkos::Experimental::DynRankView<DataType, Properties>::dimension<int>(0)’ from ‘
std::enable_if<true, long unsigned int>::type {aka long unsigned int}’ to ‘long int’ inside { } [-Wnarrowing]
/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefJacobian.hpp:172:80: warning: narrowing conversion of ‘jacobian.Kokkos::Experimental::DynRankView<DataType, Properties>::dimension<int>(1)’ from ‘
std::enable_if<true, long unsigned int>::type {aka long unsigned int}’ to ‘long int’ inside { } [-Wnarrowing]
/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Shared/Intrepid2_ArrayToolsDefTensor.hpp:793:99: warning: narrowing conversion of ‘output.Kokkos::Experimental::DynRankView<DataType, Properties>::dimension<int>(0)’ from ‘s
td::enable_if<true, long unsigned int>::type {aka long unsigned int}’ to ‘long int’ inside { } [-Wnarrowing]
...
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_BasisValues_Evaluator_impl.hpp:106:3: warning: ‘void PHX::EvaluatorWithBaseImpl<Traits>::addDependentField(const PHX::MDField<SrcDataT, SrcTag0, SrcTag1, SrcTa
g2, SrcTag3, SrcTag4, SrcTag5, SrcTag6, SrcTag7>&) [with DataT = double; Tag0 = panzer::IP; Tag1 = panzer::Dim; Tag2 = void; Tag3 = void; Tag4 = void; Tag5 = void; Tag6 = void; Tag7 = void; Traits = panzer::Traits]’ is deprecated [-Wdepr
ecated-declarations]
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_BasisValues_Evaluator_impl.hpp:106:3: warning: ‘void PHX::EvaluatorWithBaseImpl<Traits>::addDependentField(const PHX::MDField<SrcDataT, SrcTag0, SrcTag1, SrcTa
g2, SrcTag3, SrcTag4, SrcTag5, SrcTag6, SrcTag7>&) [with DataT = Sacado::Fad::DFad<double>; Tag0 = panzer::IP; Tag1 = panzer::Dim; Tag2 = void; Tag3 = void; Tag4 = void; Tag5 = void; Tag6 = void; Tag7 = void; Traits = panzer::Traits]’ is
 deprecated [-Wdeprecated-declarations]
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/evaluators/Panzer_BasisValues_Evaluator_impl.hpp:107:3: warning: ‘void PHX::EvaluatorWithBaseImpl<Traits>::addDependentField(const PHX::MDField<SrcDataT, SrcTag0, SrcTag1, SrcTa
g2, SrcTag3, SrcTag4, SrcTag5, SrcTag6, SrcTag7>&) [with DataT = double; Tag0 = panzer::Cell; Tag1 = panzer::IP; Tag2 = panzer::Dim; Tag3 = panzer::Dim; Tag4 = void; Tag5 = void; Tag6 = void; Tag7 = void; Traits = panzer::Traits]’ is dep
recated [-Wdeprecated-declarations]
```

**Comment by kyungjoo-kim** [comment] 2017-04-18 17:31
Hi @bathmatt 

I cannot reproduce the warning message. I use gcc 4.9.3 on hansen.

Could you tell me what version of gcc is used or just give me the full list of warnings of narrowing ? 

Regarding to the panzer deprecated warning, @rppawlo may address better. In the PHX, the interface is deprecated and it requires "const view type".

**Comment by kyungjoo-kim** [comment] 2017-04-20 17:42
Hi @bathmatt 

I tested for all gcc compilers: 4.7.2, 4.8.4, 4.9.2, 5.2.0, 6.1.0 on kokkosdev. I could not see the narrowing warning. I use "-Wall -Wnarraowing".

**Comment by bathmatt** [comment] 2017-04-20 17:45
OK, odd, I'm seeing it with
dir-src (gcc) 216 $ gcc --version
gcc (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This is from last night...  Maybe a dfad issue?  Don't see how but ...

/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefJacobian.hpp:
In instantiation of ‘static void
Intrepid2::CellTools<ExecSpaceType>::setJacobian(Kokkos::Experimental::DynRankView<DT,
DP ...>, Kokkos::Experimental::DynRankView<inVec2ValueType,
inVec2Properties ...>, Kokkos::Experimental::DynRankView<inArray2ValueType,
inArray2Properties ...>, HGradBasisPtrType) [with jacobianValueType =
Sacado::Fad::DFad<double>; jacobianProperties = {Kokkos::OpenMP};
pointValueType = Sacado::Fad::DFad<double>; pointProperties =
{Kokkos::OpenMP}; worksetCellValueType = Sacado::Fad::DFad<double>;
worksetCellProperties = {Kokkos::OpenMP}; HGradBasisPtrType =
Teuchos::RCP<Intrepid2::Basis<Kokkos::OpenMP, Sacado::Fad::DFad<double>,
Sacado::Fad::DFad<double> > >; ExecSpaceType = Kokkos::OpenMP]’:
/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellTools.hpp:439:16:
required from ‘static void
Intrepid2::CellTools<ExecSpaceType>::setJacobian(Kokkos::Experimental::DynRankView<DT,
DP ...>, Kokkos::Experimental::DynRankView<inVec2ValueType,
inVec2Properties ...>, Kokkos::Experimental::DynRankView<inArray2ValueType,
inArray2Properties ...>, shards::CellTopology) [with jacobianValueType =
Sacado::Fad::DFad<double>; jacobianProperties = {Kokkos::OpenMP};
pointValueType = Sacado::Fad::DFad<double>; pointProperties =
{Kokkos::OpenMP}; worksetCellValueType = Sacado::Fad::DFad<double>;
worksetCellProperties = {Kokkos::OpenMP}; ExecSpaceType = Kokkos::OpenMP]’
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/src/Panzer_PointValues2.hpp:109:5:
required from ‘void panzer::PointValues2<Scalar,
Array>::evaluateValues(const NodeCoordinateArray&, const
PointCoordinateArray&) [with NodeCoordinateArray =
PHX::MDField<Sacado::Fad::DFad<double> >; PointCoordinateArray =
PHX::MDField<Sacado::Fad::DFad<double> >; Scalar =
Sacado::Fad::DFad<double>; Array = PHX::MDField]’
/home/mbetten/Trilinos/Trilinos/packages/panzer/disc-fe/test/core_tests/point_values2.cpp:215:68:
required from here
/home/mbetten/Trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefJacobian.hpp:172:80:
warning: narrowing conversion of
‘jacobian.Kokkos::Experimental::DynRankView<DataType,
Properties>::dimension<int>(0)’ from ‘std::enable_if<true, long unsigned
int>::type {aka long unsigned int}’ to ‘long int’ inside { } [-Wnarrowing]
                               { jacobian.dimension(0),
jacobian.dimension(1) } );

**Comment by ndellingwood** [comment] 2017-04-20 17:56
@bathmatt @kyungjoo-kim  I'll try a run on kokkos-dev with gcc 6.1.0
The -Wnarrowing warnings related to MDRangePolicy should be fixed with the recent refactor on Kokkos develop branch, I'll test with this also to confirm.

**Comment by ndellingwood** [comment] 2017-04-20 20:09
@bathmatt @kyungjoo-kim Replicated the MDRangePolicy-related warnings (narrowing) with gcc/6.1.0 and with Kokkos develop branch copied into Kokkos.

**Comment by ndellingwood** [comment] 2017-04-20 23:32
@bathmatt @kyungjoo-kim Fix added to MDRangePolicy and just pulled into Kokkos develop branch
https://github.com/kokkos/kokkos/pull/743
Should make it into the next snapshot into Trilinos.

**Comment by ndellingwood** [comment] 2017-04-20 23:34
@bathmatt @kyungjoo-kim The fix addresses the narrowing warnings in Intrepid2 that made use of the MDRangePolicy

**Closed** 2017-05-09 22:35 UTC
Labels: Intrepid2, Panzer, Phalanx
