### ISSUE TITLE
Kokkos_core: KOKKOS_VERSION was not declared

### ISSUE THREAD

**Issue by anates** [trilinos/Trilinos#8527] opened 2020-12-28 18:18 UTC
## Bug Report
@trilinos/Kokkos_Core

### Description
After configuring Trilinos with internal packages, but without external TPLs (except MPI) compilation fails with `Kokkos_Core.cpp:938:18: error: ‘KOKKOS_VERSION’ was not declared in this scope; did you mean ‘KOKKOS_FUNCTION’?`

### Steps to Reproduce
1. SHA1:  2126b145e389e7c387dd1e7f755edd5899fb1b70
2. CMakeCache.txt: [CMakeCache_Error.txt](https://github.com/trilinos/Trilinos/files/5748386/CMakeCache_Error.txt)

**Comment by crtrott** [comment] 2021-01-05 22:25
Hi

I can't replicate this. can you give more instructions on what you did? I.e. how did you configure Trilinos etc.

**Comment by cgcgcg** [comment] 2021-05-24 20:03
I encountered this on a very old build folder. Deleting the build and starting from scratch fixed it. Maybe some old leftover files caused this issue? Don't think that anything needs to be done to fix this issue.

**Comment by bartlettroscoe** [comment] 2021-09-03 22:17
FYI: Was this a rebuild or a build from scratch?  If it was a rebuild, my guess this is a duplicate of this bug #6855.

I think this was caused by the big refactoring of the Kokkos build system about 1.5 years ago.

**Closed** 2022-10-05 12:44 UTC
Labels: type: bug, MARKED_FOR_CLOSURE, CLOSED_DUE_TO_INACTIVITY
